microsoft/rushstack

- gulp-core-build-sass/src/SassTask.ts
- gulp-core-build/src/IExecutable.ts
- gulp-core-build/src/index.ts
- gulp-core-build/src/tasks/CleanTask.ts
- gulp-core-build/src/tasks/GulpTask.ts
- node-library-build/package.json
- test-web-library-build/package.json
- web-library-build/package.json
Renaming nuke->clean.
Whenever anybody pulls this change, they will need to update any getNukeMatch API's, as well as updating any build scripts
> Renaming nuke to clean - MAJOR

- common/changes/show_uncaughterrors_2016-11-17-00-29.json
- gulp-core-build/src/logging.ts
Build failed with uncaught exception does not show enough information for diagnosis. If it is unexpected and uncaught, it should be dumped out in full whether verbose or not to help figure out the root issue.
> [show_uncaughterrors] Dump out uncaughtException whether verbose or not.

- common/reviews/PackageDependencies.json
- npmx.json
This turns on the package dependency tracking for web-build-tools.  When someone proposes a change to PackageDependencies.json (i.e. to introduce a new NPM package), we should ask the standard questions:
- How many additional dependencies does it bring in?
- What is the license?
- Do we already have an existing alternative?
- Maturity / code quality of package
- How compatible is its API with TypeScript conventions?
The goal of this process:
- Avoids low quality libraries, which have caused trouble in the past
- Avoids redundant libraries, which is increase learning curve for developers and degrades performance
- Raises awareness about the new library, so other devs can make use of it
- Helps avoid "npm install" sprawl, which is a major factor affecting our CI build times
> Enable PackageDependencies.json in npmx.json

- common/changes/default-ts_2016-12-01-18-43.json
- gulp-core-build-typescript/src/TypeScriptTask.ts
Noticed that without setting the typescript explicitly, it's defaulting to gulp-typescript's dependency which is really old.
> Default ts to local install.

- common/changes/nickpape-tslint-should-warn-when-using-regular-css_2016-12-08-00-38.json
- gulp-core-build-sass/README.md
- gulp-core-build-sass/src/SassTask.ts
- test-web-library-build/gulpfile.js
SASS should write a warning if a regular .scss file is used  when useCSSModules=true
> SASS should write a warning if a regular .scss file is used  when useCSSModules=true

- common/changes/nickpape-start-api-extraction_2017-01-12-00-40.json
- common/reviews/api/test-web-library-build.api.ts
- gulp-core-build-typescript/src/ApiExtractorTask.ts
- gulp-core-build-typescript/src/api-extractor.schema.json
- gulp-core-build/src/tasks/CopyTask.ts
- node-library-build/src/index.ts
- test-web-library-build/config/api-extractor.json
- web-library-build/src/index.ts
Hook the ApiExtractor into both web-library-build & node-library-build, and run it on the test project.
> Hook the ApiExtractor into both web-library-build & node-library-build

- api-extractor/src/DebugRun.ts
- api-extractor/src/TypeScriptHelpers.ts
- api-extractor/src/definitions/ApiDocumentation.ts
- api-extractor/testInputs/example2/example2-output.json
- api-extractor/testInputs/example2/index.ts
-one liner jsDoc comments where being checked for an ending sequence of '*/' at the start of the last time. However the JsDoc comment can all be one line.
> added toString and altered check for end JsDoc sequence

- api-extractor/src/DebugRun.ts
- api-extractor/src/DocElementParser.ts
- api-extractor/src/Token.ts
- api-extractor/src/Tokenizer.ts
- api-extractor/src/definitions/ApiDocumentation.ts
- api-extractor/src/generators/test/ApiFileGenerator.test.ts
- api-extractor/src/test/Token.test.ts
- api-extractor/src/test/Tokenizer.test.ts
- common/changes/pgonzal-fix-errors_2017-01-19-19-29.json
- gulp-core-build-typescript/src/ApiExtractorTask.ts
I got this error, which was confusing:
```
Warning - [apiExtractor] TypeScript error: Error formatting token tag: @inheritd
oc
/some/path/SomeFile.ts#37
Warning - [apiExtractor] TypeScript error: Unexpected text. Text must either be
the first sentences of the JSDoc, or if too long for the first 2-3 sentences the
text must be preceded by a @internalremarks tag.
```
The actual problem was that @inheritdoc should have been specified as an inline tag, rather than a regular tag.  Also, it is certainly not a "TypeScript error".
> Improve confusing error messages from api-extractor

- api-extractor/src/schemas/api-json-schema.json
- common/changes/dagaeta-update-to-json-schema_2017-01-23-23-18.json
Feature work has recently been added to allow a link JSDoc tag to link to an API definition that is internal and external (external in the works). 
The schema needed to be updated to include the members that of linkDocElement that will now be present if a linkDocElement is of reference type 'code' (API definition reference).
> Update to json schema to reflect API definition reference feature 

- .travis.yml
- package.json
- rush.json
Upgrade to Rush 1.5.0 and enable the "allowedEmailRegExps" setting in rush.json.
> Require commits to use GitHub scrubbed addresses

- api-extractor/src/Analyzer.ts
- api-extractor/src/DebugRun.ts
- api-extractor/src/PrettyPrinter.ts
- api-extractor/src/definitions/ApiDocumentation.ts
- api-extractor/src/definitions/ApiEnum.ts
- api-extractor/src/definitions/ApiFunction.ts
- api-extractor/src/definitions/ApiItem.ts
- api-extractor/src/definitions/ApiMember.ts
- api-extractor/src/definitions/ApiMethod.ts
- api-extractor/src/definitions/ApiPackage.ts
- api-extractor/src/definitions/ApiStructuredType.ts
- api-extractor/src/generators/ApiFileGenerator.ts
- api-extractor/src/generators/ApiJsonGenerator.ts
- api-extractor/src/index.ts
- api-extractor/src/schemas/api-json-schema.json
- api-extractor/testInputs/example1/example1-output.ts
- api-extractor/testInputs/example2/example2-output.json
- api-extractor/testInputs/example2/index.ts
- common/changes/dagaeta-package-comments_2017-01-25-02-39.json
- package descriptions are created at the top of the their index.ts file:
```typscript 
/**
* A utility that analyzes a project, detects common JSDoc problems , and generates
* a report of the exported Public API.
*/
declare const packageDescription: void;
```
- if their is no package description no error is reported. We can see this is working by observing that testInput/example2 has a description and testInput/example1 has no package description (with no change in their reported errors count)
> Added description for packages implementation

- api-extractor/src/definitions/ApiEnum.ts
- api-extractor/src/definitions/ApiEnumValue.ts
- api-extractor/src/definitions/ApiFunction.ts
- api-extractor/src/definitions/ApiItem.ts
- api-extractor/src/definitions/ApiMethod.ts
- api-extractor/src/definitions/ApiPackage.ts
- api-extractor/src/definitions/ApiParameter.ts
- api-extractor/src/definitions/ApiProperty.ts
- api-extractor/src/definitions/ApiStructuredType.ts
- api-extractor/src/generators/ApiFileGenerator.ts
- api-extractor/src/generators/ApiJsonGenerator.ts
- common/changes/dagaeta-ApiItemKind_2017-02-01-01-12.json
- common/reviews/api/gulp-core-build-webpack.api.ts
- common/reviews/api/node-library-build.api.ts
- common/reviews/api/web-library-build.api.ts
ApiItemKind enum is a refactoring needed for implementing local API reference resolution
> Added ApiItemKind enum to ApiItem and refactored child classes

- api-extractor/package.json
- api-extractor/src/ApiItemVisitor.ts
- api-extractor/src/DebugRun.ts
- api-extractor/src/Extractor.ts
- api-extractor/src/definitions/ApiDocumentation.ts
- api-extractor/src/definitions/ApiFunction.ts
- api-extractor/src/definitions/ApiItem.ts
- api-extractor/src/definitions/ApiItemContainer.ts
- api-extractor/src/definitions/ApiMember.ts
- api-extractor/src/definitions/ApiMethod.ts
- api-extractor/src/definitions/ApiPackage.ts
- api-extractor/src/definitions/ApiParameter.ts
- api-extractor/src/definitions/ApiProperty.ts
- api-extractor/src/definitions/test/ApiDocumentation.test.ts
- api-extractor/src/generators/test/ApiFileGenerator.test.ts
- api-extractor/src/generators/test/ApiJsonGenerator.test.ts
- api-extractor/src/test/DocElementParser.test.ts
- common/changes/dagaeta-api-extractor-resolve-references_2017-02-01-02-30.json
- common/npm-shrinkwrap.json
- common/reviews/PackageDependencies.json
- common/temp_modules/rush-api-extractor/package.json
- common/temp_modules/rush-node-library-build/package.json
- common/temp_modules/rush-web-library-build/package.json
Refactored the creation of documention for ApiItems to occur after the abstract syntax tree has been created. This will be useful for implementing local API reference inheritdocs.
> ApiExtractor now creates ApiDocumentation after all members have been created

- api-extractor/src/definitions/ApiProperty.ts
- common/changes/dagaeta-readonly-support-ApiProperty_2017-02-02-01-37.json
This check was removed during a refactor #81
> Added support that was missing for detecting readonly on documentation

- common/npm-shrinkwrap.json
- common/temp_modules/rush-gulp-core-build-karma/package.json
- common/temp_modules/rush-gulp-core-build-mocha/package.json
- common/temp_modules/rush-gulp-core-build-sass/package.json
- common/temp_modules/rush-gulp-core-build-serve/package.json
- common/temp_modules/rush-gulp-core-build-typescript/package.json
- common/temp_modules/rush-gulp-core-build-webpack/package.json
- common/temp_modules/rush-node-library-build/package.json
- common/temp_modules/rush-web-library-build/package.json
Publish command does not bump temp_modules. Do it manually. Will likely need to do this again in a few minutes after the next publish.
> Rush generate after last publish

- api-extractor/src/DocItemLoader.ts
- api-extractor/src/definitions/ApiDocumentation.ts
- api-extractor/src/test/DocItemLoader.test.ts
- common/changes/dagaeta-api-extractor-reference-resolver_2017-02-10-20-21.json
- Changed dependency from DocItemLoader to IReferenceResolver. 
- For now the IReferenceResolver is still pointing to the DocItemLoader, but this abstraction will be useful in later development of resolving local API definition references. (Where we don't know if the reference is coming from a JSON file or the extractor dictionary)
> Changed ApiDocumentation dependency to abstract away API reference resolving

- common/changes/nickpape-check-versions-command_2017-02-13-21-56.json
- rush.json
- rush/rush-lib/src/data/VersionMismatchFinder.ts
- rush/rush-lib/src/data/test/VersionMismatchFinder.test.ts
- rush/rush-lib/src/index.ts
- rush/rush-lib/typings/read-package-tree/read-package-tree.d.ts
- rush/rush/src/actions/CheckVersionsAction.ts
- rush/rush/src/actions/RushCommandLineParser.ts
Sample output:
```
@types/es6-collections
^0.5.29
- @microsoft/api-extractor
0.5.29
- @microsoft/rush
- @microsoft/rush-lib
@types/fs-extra
~0.0.34
- @microsoft/api-extractor
>=0.0.34, <0.27.0
- @microsoft/gulp-core-build-typescript
0.0.37
- @microsoft/rush
0.0.34
- @microsoft/rush-lib
@types/node
>=6.0.51 <6.9.1
- @microsoft/api-extractor
^6.0.46
- @microsoft/gulp-core-build
- @microsoft/gulp-core-build-mocha
- @microsoft/gulp-core-build-sass
- @microsoft/gulp-core-build-serve
- @microsoft/gulp-core-build-typescript
- @microsoft/gulp-core-build-webpack
- @microsoft/node-library-build
- @microsoft/package-deps-hash
- @microsoft/web-library-build
6.0.62
- @microsoft/rush
- @microsoft/rush-lib
@types/z-schema
~3.16.31
- @microsoft/api-extractor
- @microsoft/gulp-core-build
3.16.31
- …
```
> Adds a 'check-versions' command which can be used to locate inconsistencies in dependency versions in a repo

- common/changes/dzearing-sass-fix_2017-02-14-08-11.json
- gulp-core-build-sass/src/SassTask.ts
Between 2 versions, the hashes are not regenerating. This makes it so that any modifications to the css content of the file will re-eval the hash.
> SASS: module css hash should be changed when css content changes.

- common/changes/pgonzal-revert-pr102_2017-02-15-08-44.json
- rush/rush/src/actions/InstallAction.ts
The office-ui-fabric-react Travis builds were broken because the evergreen bot is bumping package.json without running "rush generate", which causes _checkThatTempModulesMatch() to fail.  This is a regression caused by PR #102.  Technically the bot *should* run "rush generate" after bumping the version, but insisting on that would be unreasonable because it would break the scenario.
I'm temporarily reverting this feature until we can sort it out.
> Temporarily revert PR #102

- rush.json
- rush/rush-lib/package.json
- rush/rush/package.json
This fixes the bug where you install Rush 1.8.2 and then it prints a banner saying that it's Rush 1.8.0.
> Disable automatic publishing for Rush

- package.json
- rush/rush-lib/package.json
- rush/rush/package.json
- rush/rush/src/actions/RushCommandLineParser.ts
- rush/rush/src/rush.ts
Fix up the NPM package metadata for publishing.  Also bump web-build-tools to use the latest Rush.
> Fix Rush metadata

- common/changes/nickpape-verbose-flags_2017-02-16-20-38.json
- rush/rush/src/actions/RebuildAction.ts
- rush/rush/src/taskRunner/ProjectBuildTask.ts
Some feedback people have given is that the quiet (summary) build should be the default, and they would rather have a `--verbose` flag to display the build logs.
> Make quiet the default, add --verbose

- common/changes/nickpape-add-is-enabled-toggle-instead-of-override_2017-02-16-23-48.json
- common/reviews/api/gulp-core-build.api.ts
- gulp-core-build/src/IExecutable.ts
- gulp-core-build/src/tasks/GulpTask.ts
People have been overriding the isEnabled function to turn tasks off. This is weird. Now, there is a toggle which is read by the default isEnabled function. Consumers should use this toggle.
VSO 310452
> Add enabled toggle to both GulpTask and IExecutable

- common/changes/nickpape-dont-fail-karma-in-nonproduction_2017-02-22-20-08.json
- common/changes/nickpape-dont-fail-karma-in-nonproduction_2017-02-24-02-26.json
- common/reviews/api/gulp-core-build.api.ts
- common/reviews/api/node-library-build.api.ts
- common/reviews/api/web-library-build.api.ts
- gulp-core-build-karma/src/KarmaTask.ts
- gulp-core-build/src/IExecutable.ts
- gulp-core-build/src/tasks/GulpTask.ts
A single unit test failure should not fail the entire build, unless it is a `--production` build.
VSO 310473
> Karma should only fail production builds

- common/changes/nickpape-rush-pinned-versions_2017-02-24-00-38.json
- rush/rush-lib/src/data/RushConfiguration.ts
- rush/rush-lib/src/rush-schema.json
- rush/rush/src/actions/GenerateAction.ts
In certain cases, it is desirable to control which version of a second-level dependency NPM will resolve to.
For example, recently a patch version of `loader-utils` deprecated a function being called by `css-loader`. The version specifier for `loader-utils` was a range: `>=1.0.0 <2.0.0`. However, `loader-utils` is not a top-level dependency of the project, therefore, in order to control the version, we must add it to our package.json.
However, this is undesirable, as we have now added a package as a dependency even though we don't actually depend on it. Additionally, we would likely have to add this dependency to every package.json. Even if we do that, there are still cases where NPM will install side-by-side versions.
The solution: add a new field to rush.json called `pinnedVersions`. …
> Rush: add "pinnedVersions" option

- common/changes/common.json
- common/changes/pinned.json
- common/changes/verbose.json
- rush/rush/src/actions/RebuildAction.ts
Many CI scripts will have to be updated. We should let the new flags bake for a while before removing anything.
> Rush: Deprecate the "--quiet" flag rather than completely removing it 

- common/changes/write-config_2017-03-12-14-57.json
- gulp-core-build-typescript/src/TSLintTask.ts
- The TSLint configuration file can be used for [VSCode TSLint plugin](https://marketplace.visualstudio.com/items?itemName=eg2.tslint).
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/Microsoft/web-build-tools/pull/129%23discussion_r105621243%22%2C%20%22https%3A//github.com/Microsoft/web-build-tools/pull/129%23discussion_r105621439%22%2C%20%22https%3A//github.com/Microsoft/web-build-tools/pull/129%23discussion_r105710804%22%2C%20%22https%3A//github.com/Microsoft/web-build-tools/pull/129%23discussion_r105712938%22%2C%20%22https%3A//github.com/Microsoft/web-build-tools/pull/129%23discussion_r105746332%22%2C%20%22https%3A//github.com/Microsoft/web-build-tools/pull/129%23discussion_r105746908%22%2C%20%22https%3A//github.com/Microsoft/web-build-too …
> Write the TSLint configuration file to the temp directory during build.

- rush/rush/src/actions/GenerateAction.ts
- rush/rush/src/actions/InstallAction.ts
After running install or generate, we almost always want to run `rush link`. We should automatically do this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/web-build-tools/134)
> The install and the generate actions should run link automatically

- common/changes/nickpape-fix-clean_2017-03-16-00-07.json
- common/npm-shrinkwrap.json
- common/reviews/PackageDependencies.json
- common/temp_modules/rush-gulp-core-build/package.json
- common/temp_modules/rush-node-library-build/package.json
- common/temp_modules/rush-rush-lib/package.json
- common/temp_modules/rush-rush/package.json
- common/temp_modules/rush-test-web-library-build/package.json
- gulp-core-build/package.json
- gulp-core-build/src/tasks/CleanTask.ts
- gulp-core-build/src/utilities/FileDeletionUtility.test.ts
- gulp-core-build/src/utilities/FileDeletionUtility.ts
- gulp-core-build/typings-custom/glob-escape/index.d.ts
- rush/rush/src/taskRunner/ProjectBuildTask.ts
- test-web-library-build/src/.gitignore
- test-web-library-build/src/preCopyTest.ts
There is a problem with the `del` package where you cannot specify both a folder, and an item in the folder, else builds will spuriously fail.
Example:
```js
del(['/foo', '/foo/bar.txt'])  // sometimes this will cause an exception, as it tries to delete /foo/bar.txt
```
The fix is to pre-expand the glob matches, and remove any entry if a containing folder for that entry is already specified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/web-build-tools/135)
> Fix an issue with `del` package during rush clean

- .vscode/settings.json
- api-extractor/src/ApiDefinitionReference.ts
- api-extractor/src/DocElementParser.ts
- api-extractor/src/DocItemLoader.ts
- api-extractor/src/ExternalApiHelper.ts
- api-extractor/src/Extractor.ts
- api-extractor/src/IDocElement.ts
- api-extractor/src/IDocItem.ts
- api-extractor/src/ResolvedApiItem.ts
- api-extractor/src/TestFileComparer.ts
- api-extractor/src/definitions/ApiDocumentation.ts
- api-extractor/src/definitions/ApiItem.ts
- api-extractor/src/definitions/ApiPackage.ts
- api-extractor/src/generators/ApiFileGenerator.ts
- api-extractor/src/generators/ApiJsonFile.ts
- common/changes/dzearing-update-sass_2017-03-20-00-22.json
- common/npm-shrinkwrap.json
- common/temp_modules/rush-gulp-core-build-sass/package.json
- common/temp_modules/rush-gulp-core-build-typescript/package.json
- common/temp_modules/rush-node-library-build/package.json
- common/temp_modules/rush-web-library-build/package.json
- gulp-core-build-sass/package.json
Noticed downstream we're also having issues consuming the latest sass-loader bits, due to the outdated dependencies in gcb-sass.
Fixed some whitespace issues in api-extractor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/web-build-tools/138)
> Update sass dependencies.

- common/changes/dzearing-sass-module-export_2017-03-20-20-22.json
- gulp-core-build-sass/src/SassTask.ts
- gulp-core-build-sass/src/sass.schema.json
This change should not change any default behavior, but adds a config setting `moduleExportName` which allows you to tweak how the styles are exported as a css module:
Without providing the config setting, we export as normal:
```ts
export default styles;
```
With a blank string, we export the object:
```ts
export = styles;
```
With a name provided, we export a const:
```ts
export const ${ name } = styles;
```
This helps with integration using the webpack loader stack, which doesn't export defaults and conflicts with the gcb stack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/web-build-tools/142)
> Adding ability to override the export method for sass css modules.

- common/changes/ianc-fixing-tslint-config_2017-04-03-22-52.json
- gulp-core-build-typescript/src/TSLintTask.ts
The TSLint task currently doesn't respect the `removeExistingRules` option because the code that initializes the tasks calls `mergeConfig` instead of `setConfig`.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/web-build-tools/150)
> Fixing the way the TSLint task is configured.

- api-extractor/src/definitions/ApiItem.ts
- api-extractor/testInputs/example2/example2-output.ts
- common/changes/dagaeta-remove-public-api-tag-apipackage_2017-04-05-16-08.json
-We were setting the API tag on ApiPackages to @public by default, this PR removes that line and leaves the API tag unset.
> removed hard coding of @public API tag on ApiPackage documentation

- common/changes/suppressWarning_2017-04-05-06-42.json
- gulp-core-build-sass/src/SassTask.ts
- gulp-core-build-sass/src/sass.schema.json
Add a switch on SASS task config to be able to change CSS module generation warning message type to verbose to avoid exitcode:1 on the end of the build task.
> Switch warning message type to verbose on CSS module generation 

- rush/rush-lib/src/data/PackageReviewConfiguration.ts
- rush/rush-lib/src/data/PinnedVersionsConfiguration.ts
- rush/rush-lib/src/data/RushConfiguration.ts
- rush/rush-lib/src/index.ts
It is difficult to programatically update pinnedVersions, which is a feature that is needed for some internal tooling.
> Rush-lib: Move the pinnedVersions into it's own file

- rush/rush/src/actions/PublishAction.ts
The "rush publish" command bumps versions and creates Git tags by comitting changes to the repo.  Because our CI system isn't configured properly, it's been introducing malformed e-mail addresses like this:
```
Local Admin by Powershell <Local Admin by Powershell> 
```
Spaces are not formally allowed in an e-mail address, and certain commands such as `git filter branch` actually crash when they fail to parse these strings.  We will fix our CI system, but to prevent this in the future, I'm updating "rush publish" to enforce Rush's Git policy (if there is one).
We don't need a `--bypass-policy` option for this command, since it's intended to be run by an automation system.  If you really want a bad e-mail, you can simply add it to the Rush policy.
> Prevent "rush publish" from corrupting Git

- common/changes/nickpape-no-incremental-sass_2017-05-04-22-26.json
- common/npm-shrinkwrap.json
- common/temp_modules/rush-gulp-core-build-sass/package.json
- common/temp_modules/rush-node-library-build/package.json
- common/temp_modules/rush-web-library-build/package.json
- gulp-core-build-sass/package.json
- gulp-core-build-sass/src/SassTask.ts
There is a big bug. Essentially, even if a file has changed, the downstream SASS files are not re-built. Solution is to remove incremental. Shouldn't affect normal builds which run "clean" before build, but it will make `serve` a little slower.
> Remove SASS Incremental

- common/reviews/api/rush-lib.api.ts
- rush/rush-lib/src/RushConstants.ts
- rush/rush-lib/src/data/PinnedVersionsConfiguration.ts
- rush/rush-lib/src/data/RushConfiguration.ts
- rush/rush-lib/src/data/test/RushConfiguration.test.ts
- rush/rush-lib/src/data/test/repo/project1/package.json
- rush/rush-lib/src/data/test/repo/project2/package.json
- rush/rush-lib/src/data/test/repo/project3/package.json
- rush/rush-lib/src/data/test/repo/rush.json
- rush/rush-lib/src/rush-schema.json
- rush/rush/src/utilities/InstallManager.ts
- rush/rush/src/utilities/test/packages/rush.json
This PR includes the following updates for the rush configuration, based on our design discussion:
- remove the "commonFolder" setting from rush.json
- remove the "useLocalNpmCache" setting from rush.json; it is now "always on"
- remove the deprecated "pinnedVersions" setting from rush.json
- Move ancillary config files into the "common/config/rush" folder; an error will be reported if any unrecognized files are found here
- Add unit tests for RushConfiguration
NOTE:  We also discussed some changes for the "packageReviewFile"/PackageDependencies.json feature; I will handle that in a separate PR.
> Trim Rush config, introduce a "common/config/rush" folder

- apps/rush-lib/CHANGELOG.json
- apps/rush-lib/CHANGELOG.md
- apps/rush-lib/package.json
- apps/rush-lib/src/utilities/Utilities.ts
- apps/rush/CHANGELOG.json
- apps/rush/CHANGELOG.md
- apps/rush/package.json
This PR fixes a regression where "rush install" sometimes failed to install the local NPM tool (in the ~/.rush/npm-A.B.C" folder).
> Publish Rush 3.0.3 with fix for install issue

- apps/rush-lib/CHANGELOG.json
- apps/rush-lib/CHANGELOG.md
- apps/rush-lib/package.json
- apps/rush/CHANGELOG.json
- apps/rush/CHANGELOG.md
- apps/rush/package.json
This is a bug fix release:
- Improved the "rush build" change detection: if any file outside a project folder has changed, rebuild all projects.
- The "rush build" command now stores the command-line options used during a build, and forces a full rebuild if the options have changed.
- Fix for a "rush publish" bug involving command line option quoting.
> Publish Rush 3.0.4

- apps/rush/src/taskRunner/ProjectBuildTask.ts
Look for a file in the local .bin folder. If found, use it.
#161 
#162
> Allow for local commands (other than gulp)

- apps/rush-lib/src/data/RushConfiguration.ts
A logic check didn't work correctly because of a typo.  As a result, Rush's check for unrecognized files was also complaining about subdirectories (which is unreasonably pedantic).
> Fix a minor bug where Rush complained about extra directories

- common/changes/@microsoft/api-extractor/pgonzal-api-extractor-readme_2017-06-08-04-58.json
- libraries/api-extractor/README.md
- libraries/api-extractor/package.json
Apparently our [https://www.npmjs.com/package/@microsoft/api-extractor](NPM page) was pretty sparse.  This PR copies some wiki content into the README.md to fix that.
> Update the README.md and package.json for api-extractor

- apps/rush-lib/src/index.ts
- common/reviews/api/rush-lib.api.ts
Exporting the implementation of the JsonSchemaValidator. It is a useful utility that can be reused in many places. We should consider moving this to a more core package and doing an API review.
> Export JsonSchemaValidator

- common/changes/@microsoft/gulp-core-build-typescript/pgonzal-publish-gcb-typescript_2017-06-16-00-57.json
- core-build/gulp-core-build-typescript/README.md
The **gulp-core-build-typescript** package didn't get republished when **api-extractor** was changed.  (We're investigating whether this is due to a bug.)  This PR adds an empty change log record to force republishing.
> Publish gulp-core-build-typescript

- common/changes/@microsoft/api-extractor/pgonzal-api-extractor-cleanups_2017-06-16-02-40.json
- libraries/api-extractor/src/ApiDefinitionReference.ts
- libraries/api-extractor/src/Tokenizer.ts
- libraries/api-extractor/src/definitions/ApiDocumentation.ts
- libraries/api-extractor/src/definitions/test/ApiDocumentation.test.ts
- libraries/api-extractor/src/test/DocElementParser.test.ts
- libraries/api-extractor/testInputs/example2/example2-output.json
- libraries/api-extractor/testInputs/example2/src/MyDocumentedClass.ts
API Extractor does not support the @summary tag, but some old code parsed it.  This PR removes that code and improves some various unit test code.
> Disallow @summary tag

- common/changes/@microsoft/api-extractor/pgonzal-ae-error-strings_2017-06-19-18-55.json
- libraries/api-extractor/src/ApiDefinitionReference.ts
- libraries/api-extractor/src/DocElementParser.ts
- libraries/api-extractor/src/IDocElement.ts
- libraries/api-extractor/src/Token.ts
- libraries/api-extractor/src/Tokenizer.ts
- libraries/api-extractor/src/definitions/ApiDocumentation.ts
- libraries/api-extractor/src/definitions/ApiItem.ts
- libraries/api-extractor/src/definitions/ApiNamespace.ts
- libraries/api-extractor/src/definitions/ApiPackage.ts
- libraries/api-extractor/src/definitions/ApiStructuredType.ts
- libraries/api-extractor/src/definitions/test/ApiDocumentation.test.ts
- libraries/api-extractor/src/generators/test/ApiFileGenerator.test.ts
- libraries/api-extractor/src/test/DocElementParser.test.ts
- libraries/api-extractor/src/test/DocItemLoader.test.ts
- libraries/api-extractor/src/test/Token.test.ts
- libraries/api-extractor/src/test/Tokenizer.test.ts
- libraries/api-extractor/testInputs/example2/example2-output.json
- libraries/api-extractor/testInputs/example2/src/MyDocumentedClass.ts
I reviewed all the `reportWarning()` and `reportError()` calls, and cleaned up the error messages.
> Audit API Extractor error strings

- common/changes/@microsoft/api-extractor/pgonzal-ae-underscore-prefix_2017-06-19-20-20.json
- libraries/api-extractor/src/definitions/ApiDocumentation.ts
- libraries/api-extractor/src/definitions/ApiItem.ts
- libraries/api-extractor/src/test/DocItemLoader.test.ts
- libraries/api-extractor/testInputs/example1/example1-output.api.ts
- libraries/api-extractor/testInputs/example1/folder/AliasClass.ts
- libraries/api-extractor/testInputs/example1/folder/MyClass.ts
- libraries/api-extractor/testInputs/example1/folder/ReleaseTagTests.ts
- libraries/api-extractor/testInputs/example1/index.ts
- libraries/api-extractor/testInputs/example3/example3-output.api.ts
- libraries/api-extractor/testInputs/example3/example3-output.json
- libraries/api-extractor/testInputs/example3/src/MyClass.ts
- libraries/api-extractor/testInputs/example3/src/index.ts
When a definition is *explicitly* marked as `@internal`, an underscore prefix should be added to its *exported* name.  Some examples:
```typescript
/** @internal */
// The underscore is optional here, because an underscore is being
// applied separately where MyClass is exported.
class MyClass {
// The myMethod() member is implicitly internal because
// it's part of an internal class
public myMethod(): void { // <-- MUST NOT have underscore
}
}
/** @public */
class MyPublicClass { // <-- MUST NOT have underscore 
/** @internal */
public _myInternalMethod(): void { // <-- MUST have underscore  
}
}
let _MyClass = MyClass;
export default _MyClass;
```
> API Extractor now warns when an @internal definition is missing the underscore prefix

- common/changes/@microsoft/api-extractor/pgonzal-ae-pipe-bug_2017-06-19-19-29.json
- libraries/api-extractor/src/DocElementParser.ts
- libraries/api-extractor/src/test/DocElementParser.test.ts
- libraries/api-extractor/testInputs/example3/example3-output.json
API Extractor `@link` tags can include optional display text.  For example, "widgets" and "draw() function" in this sample code:
```javascript
/**
* The base class for all {@link https://en.wikipedia.org/wiki/Widget | widgets}.
* @remarks
* Implements the {@link @microsoft/widget-lib:IWidget} interface.  To draw the widget,
* call the {@link BaseWidget.draw | draw() function}.
* @public
*/
```
This PR fixes a bug where certain characters (e.g. an apostrophe) were not allowed in the display text.
It also changes the API JSON semantics slightly:  Before, if display text was omitted, the `value` field would be an empty string, leaving the documentation generator to determine the display text based on the address.  After this PR, API Extractor always provides the display text.
> Fix a bug with handling of @link tags for API Extractor

- apps/rush-lib/src/utilities/Utilities.ts
Processing script parameters is tricky and different on different os. Avoid running sh on top of sh on mac. But windows needs cmd to run on shell to run properly.
> Fix how shell command is executed on mac.

- common/changes/@microsoft/gulp-core-build/nickpape-test_2017-06-27-23-14.json
- common/changes/@microsoft/gulp-core-build/nickpape-test_2017-06-27-23-16.json
- common/changes/@microsoft/web-library-build/nickpape-test_2017-06-27-23-16.json
- core-build/gulp-core-build/src/index.ts
- core-build/test-web-library-build/config/pre-copy.json
- core-build/test-web-library-build/src/preCopyTest.d.ts
- core-build/test-web-library-build/src/preCopyTest.js
- core-build/web-library-build/src/index.ts
* We were experiencing an issue where, if there was a build error, "gulp serve" was ending instead of continuing to watch files for changes.
* This was because we had defined the build tasks twice, once in the watch() block, but again in a serial() block enveloping the two.
* After removing the duplicate build steps, I noticed the issue was that watch() was not kicked off unless there was a file change. Therefore, watch() was changed so that it would always initially invoke itself. 
* While doing that I noticed some issues with the promises (e.g. watch was reporting to gcb that it was completing before it actually was), so I fixed that issue by removing the `return Promise.resolve()` and replacing it with a Promise block that never returns.
> Improve watch()

- common/changes/@microsoft/gulp-core-build-karma/pgonzal-fix-bluebird_2017-07-01-01-10.json
- common/config/rush/npm-shrinkwrap.json
- core-build/gulp-core-build-karma/package.json
Someone recently published a new `@types/bluebird` that relies on TypeScript 2.3 syntax, which breaks our projects.  We don't use `@types/bluebird` (and in fact recommend against using it), however it's an indirect dependency of the `@types/karma` package.  Since it's an unconstrained dependency, the only way to lock its version it to add an explicit dependency on `@types/bluebird`.
I opened [DefinitelyTyped issue \#360](https://github.com/Microsoft/types-publisher/issues/360#issuecomment-312401100) to discuss this policy on their end.  In the meantime, this PR will unblock `rush generate` for **web-build-tools.**
> Fix build break caused by @types/bluebird

- apps/rush-lib/package.json
- apps/rush-lib/src/RushConstants.ts
- apps/rush-lib/src/data/RushConfiguration.ts
- apps/rush-lib/src/data/RushConfigurationProject.ts
- apps/rush-lib/src/data/VersionPolicy.ts
- apps/rush-lib/src/data/VersionPolicyConfiguration.ts
- apps/rush-lib/src/data/test/VersionPolicy.test.ts
- apps/rush-lib/src/data/test/jsonFiles/rushWithIndividualVersion.json
- apps/rush-lib/src/data/test/jsonFiles/rushWithLockVersion.json
- apps/rush-lib/src/index.ts
- apps/rush-lib/src/rush.schema.json
- apps/rush-lib/src/version-policies.schema.json
- apps/rush/src/actions/PublishAction.ts
- apps/rush/src/actions/RushCommandLineParser.ts
- apps/rush/src/actions/VersionAction.ts
- apps/rush/src/utilities/Git.ts
- apps/rush/src/utilities/PublishUtilities.ts
- apps/rush/src/utilities/VersionManager.ts
- apps/rush/src/utilities/test/VersionManager.test.ts
- apps/rush/src/utilities/test/repo/a/package.json
- apps/rush/src/utilities/test/repo/b/package.json
- apps/rush/src/utilities/test/repo/c/package.json
- apps/rush/src/utilities/test/repo/d/package.json
- apps/rush/src/utilities/test/repo/rush.json
- apps/rush/src/utilities/test/repo/version-policies.json
- common/reviews/api/rush-lib.api.ts
Add version policy configuration
Add a "rush version --ensure-version-policy" action that can update project versions to enforce version policy in the Rush repo.
> Add version policy configuration and a Rush action to enforce version policy

- apps/rush/src/utilities/PackageChangeAnalyzer.ts
- apps/rush/src/utilities/test/PackageChangeAnalyzer.test.ts
The below solution is technically correct, but breaks down in certain cases when there are files that are checked into Git that are outputs of the build. Instead, we plan to replace this with a more robust solution involving moving package-deps-hash creation into gulp-core-build.
> Temporarily revert Rush incremental build checking files outside of the project directory

- common/changes/@microsoft/web-library-build/nickpape-fix-serve_2017-07-26-21-38.json
- core-build/web-library-build/src/index.ts
It was not spinning up the server due to a regression in #253 . Fixes #284.
> Fix web-library-buld's gulp serve command

- common/changes/@microsoft/load-themed-styles/msilver-theme-slot-warning-debug-only_2017-07-28-23-44.json
- libraries/load-themed-styles/src/index.ts
Making warnings opt-in rather than opt-out.
> Only warn for missing theme slots if DEBUG is true

- common/changes/@microsoft/loader-load-themed-styles/nickpape-republish-llts_2017-08-15-18-34.json
- webpack/loader-load-themed-styles/gulpfile.js
The current one (1.4.0) has a ~1.6.0 dependency on load-themed-styles. This is causing problems with packages trying to consume the latest gulp-core-build-sass who don't want diamond dependencies.
> Force a publish of loader-load-themed-styles

- apps/rush/package.json
- common/changes/@microsoft/api-extractor/nickpape-create-tgz-temp-modules_2017-08-16-19-18.json
- common/changes/@microsoft/gulp-core-build-typescript/nickpape-create-tgz-temp-modules_2017-08-16-19-18.json
- common/changes/@microsoft/gulp-core-build/nickpape-create-tgz-temp-modules_2017-08-16-19-18.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/npm-shrinkwrap.json
- core-build/gulp-core-build-typescript/src/TypeScriptConfiguration.ts
- core-build/gulp-core-build-typescript/src/TypeScriptTask.ts
- core-build/gulp-core-build/src/tasks/CleanTask.ts
- core-build/gulp-core-build/src/utilities/test/FileDeletionUtility.test.ts
- libraries/api-extractor/src/DebugRun.ts
- libraries/api-extractor/src/DocItemLoader.ts
- libraries/api-extractor/src/definitions/ApiDocumentation.ts
- libraries/api-extractor/src/definitions/ApiItem.ts
- libraries/api-extractor/src/definitions/ApiNamespace.ts
- libraries/api-extractor/src/definitions/ApiPackage.ts
- libraries/api-extractor/src/definitions/test/ApiDocumentation.test.ts
- libraries/api-extractor/src/index.ts
- libraries/api-extractor/src/test/ApiDefinitionReference.test.ts
- libraries/api-extractor/src/test/DocItemLoader.test.ts
* Add tar as a dependency of Rush, which is required work for replacing the temp_modules/*/package.json files with TGZ files. This is necessary because NPM is deprecating the `file:` specifier. It will only work with TGZ files now.
* Fix a bunch of lint errors that occurred after running `rush generate`
> Add tar as a dependency of Rush

- apps/rush-lib/src/data/RushConfigurationProject.ts
- apps/rush-lib/src/data/test/RushConfiguration.test.ts
- apps/rush-lib/src/utilities/JsonFile.ts
- apps/rush/package.json
- apps/rush/src/utilities/InstallManager.ts
- apps/rush/typings/tar/tar.d.ts
- apps/rush/typings/tsd.d.ts
- common/config/rush/npm-shrinkwrap.json
- common/reviews/api/rush-lib.api.ts
Rush needs to make `file:` references to tgz files. NPM has decided to deprecate the behavior of the `file:./...` specified, which used to treat the folder as a project that needed to be installed. Instead, `file:./...` references now just create a symlink, **unless** one is referencing a `.tgz` file. PNPM has also decided to use this behavior.
We should merge this PR to:
1) maintain forwards compatibility with NPM
2) allow us to use PNPM
See:
https://github.com/npm/npm/pull/15900
and
https://github.com/pnpm/pnpm/issues/772
> Rush should create .tgz files instead of package.json for temp_modules

- common/changes/@microsoft/gulp-core-build-typescript/update-tslint_2017-08-22-22-49.json
- common/config/rush/npm-shrinkwrap.json
- core-build/gulp-core-build-typescript/package.json
Upgrades to tslint 5.6 so we can get this [fix](https://github.com/palantir/tslint/commit/a479f436530f0afd52fc65c5a45645bd4a2b5b29)
> Upgrade gulp-core-build-typescript to tslint 5.6

- libraries/api-documenter/src/MarkdownPageRenderer.ts
- libraries/api-documenter/src/test/ExpectedOutput.md
- libraries/api-documenter/src/test/MarkdownPageRenderer.test.ts
This PR implements a couple improvements to the MarkdownPageRenderer class:
1. bold/italics are now handled correctly for strings that:
- span multiple lines
- have spaces in them
- are preceded/followed by a non-whitespace character
- are adjacent to other stylized regions (in which case `` is inserted between the incompatible blocks)
2. If two adjacent IDomText blocks have the same styling, then they are merged to avoid redundant markup (e.g. `**some boldstuff**` instead of `**some** **bold****stuff**`)
> Improve the bold/italics markdown generated by api-documenter

- common/changes/@microsoft/api-extractor/pgonzal-fix-dependencies_2017-08-31-17-20.json
- common/changes/@microsoft/node-core-library/pgonzal-fix-dependencies_2017-08-31-17-20.json
- common/config/rush/npm-shrinkwrap.json
- libraries/api-documenter/package.json
- libraries/api-extractor/package.json
- libraries/node-core-library/package.json
This is a fix for [SPFx GitHub # 820](https://github.com/SharePoint/sp-dev-docs/issues/820).
The error looked like this:
```
TypeError: Cannot read property 'readCommentedJsonFile' of undefined
TypeError: Cannot read property 'readCommentedJsonFile' of undefined
```
The problem was that **api-extractor** recently took a dependency on **node-core-library**, but it was incorrectly listed as a dev dependency.
> Fix issue where api-extractor failed to find node-core-library

- common/changes/@microsoft/api-extractor/pgonzal-major-bump_2017-08-31-18-17.json
- common/changes/@microsoft/gulp-core-build-karma/pgonzal-major-bump_2017-08-31-18-17.json
- common/changes/@microsoft/gulp-core-build-mocha/pgonzal-major-bump_2017-08-31-18-17.json
- common/changes/@microsoft/gulp-core-build-sass/pgonzal-major-bump_2017-08-31-18-17.json
- common/changes/@microsoft/gulp-core-build-serve/pgonzal-major-bump_2017-08-31-18-17.json
- common/changes/@microsoft/gulp-core-build-typescript/pgonzal-major-bump_2017-08-31-18-17.json
- common/changes/@microsoft/gulp-core-build-webpack/pgonzal-major-bump_2017-08-31-18-17.json
- common/changes/@microsoft/gulp-core-build/pgonzal-major-bump_2017-08-31-18-17.json
- common/changes/@microsoft/node-library-build/pgonzal-major-bump_2017-08-31-18-17.json
- common/changes/@microsoft/web-library-build/pgonzal-major-bump_2017-08-31-18-17.json
Some old SPFx releases used a caret dependency for various toolchain libraries, which has been causing regressions because we don't actively retest these old releases.  (SemVer compatibility should avoid breaking changes to APIs, however it doesn't prevent an upgrade from invalidating all the testing and validation that was done for an earlier release.)
This is part of the fix for [SPFx GitHub # 820](https://github.com/SharePoint/sp-dev-docs/issues/820).
> Major bump core build libraries to fix compatibility issue

- common/changes/@microsoft/api-extractor/pgonzal-yaml-documenter2_2017-09-06-00-28.json
- common/reviews/api/api-extractor.api.ts
- libraries/api-documenter/src/DocItemSet.ts
- libraries/api-documenter/src/DocumentationNode.ts
- libraries/api-documenter/src/Documenter.ts
- libraries/api-documenter/src/MarkdownPageRenderer.ts
- libraries/api-documenter/src/MarkdownRenderer.ts
- libraries/api-documenter/src/MarkupBuilder.ts
- libraries/api-documenter/src/RenderingHelpers.ts
- libraries/api-documenter/src/test/ExpectedOutput.md
- libraries/api-documenter/src/test/MarkdownPageRenderer.test.ts
- libraries/api-documenter/src/yaml/YamlGenerator.ts
- libraries/api-extractor/src/api/ApiItem.ts
- libraries/api-extractor/src/markup/MarkupElement.ts
This includes a change to the IMarkupDocumentationLink interface from API Extractor (still an \@alpha API).  This element type is replaced with IMarkupApiLink, which exposes the underlying IApiItemReference.
> YamlGenerator now supports hyperlinks to API items

- common/changes/@microsoft/api-extractor/pgonzal-yaml-documenter3_2017-09-06-03-12.json
- common/reviews/api/api-extractor.api.ts
- libraries/api-documenter/src/DocItemSet.ts
- libraries/api-documenter/src/yaml/YamlGenerator.ts
- libraries/api-documenter/src/yaml/typescript.schema.json
- libraries/api-extractor/src/api/ApiItem.ts
- libraries/api-extractor/src/api/api-json.schema.json
- libraries/api-extractor/testInputs/example2/node_modules/@microsoft/sp-core-library/dist/sp-core-library.api.json
- Correct the API Extractor typings to reflect the *.api.json change that Danny already made a while ago
- Correct the JSON Schema
- Update the sp-core-library.api.json test input based on a more recent build
- Make enum members into a proper ApiItem and DocItem object
- Emit the enum member as "field" items embedded in the YAML file for the enum
> api-documenter now correctly supports enums for YAML

- common/changes/@microsoft/node-core-library/pgonzal-yaml-documenter4_2017-09-07-03-39.json
- libraries/api-documenter/src/DocItemSet.ts
- libraries/api-documenter/src/yaml/YamlGenerator.ts
- libraries/node-core-library/src/JsonFile.ts
This fills out some more content fields in the generated YAML fields.
It also improves `JsonFile.validateNoUndefinedMembers()` to show the full path of where the "undefined" value occurs in the JSON object.  An example error:
```
The value for items[4].syntax.parameters["string \"with\" symbols"].type[0] is undefined
```
> api-documenter now correctly supports function parameters and property types

- common/changes/@microsoft/api-extractor/pgonzal-yaml-documenter8_2017-09-10-00-50.json
- common/reviews/api/api-extractor.api.ts
- libraries/api-documenter/src/MarkupBuilder.ts
- libraries/api-documenter/src/yaml/YamlGenerator.ts
- libraries/api-extractor/src/DocElementParser.ts
- libraries/api-extractor/src/aedoc/ApiDocumentation.ts
- libraries/api-extractor/src/aedoc/Tokenizer.ts
- libraries/api-extractor/src/aedoc/test/Tokenizer.test.ts
- libraries/api-extractor/src/api/api-json.schema.json
- libraries/api-extractor/src/markup/OldMarkup.ts
- libraries/api-extractor/src/test/DocElementParser.test.ts
- libraries/api-extractor/testInputs/example1/example1-output.api.ts
- libraries/api-extractor/testInputs/example1/example1-output.json
- libraries/api-extractor/testInputs/example1/folder/MyClass.ts
- libraries/api-extractor/testInputs/example2/example2-output.json
- libraries/api-extractor/testInputs/example3/example3-output.json
Currently the AEDoc parser removes all newlines and collapses all white space from documentation comments.  This causes long descriptions to get collapsed into a single paragraph (e.g. [here](https://dev.office.com/sharepoint/reference/spfx/sp-core-library/class/servicescope)).  This PR makes it so that two newlines will be interpreted as a paragraph separator.  This is the first of a series of formatting syntax features that will be eventually modeled using the [MarkupElement](https://github.com/Microsoft/web-build-tools/blob/master/libraries/api-extractor/src/markup/MarkupElement.ts) system.  However, to minimize compatibility issues, for now I am simply adding an IParagraphElement to OldMarkup.ts.
This is a somewhat large change because the DocElementParser is a little squirrelly. …
> Add support for paragraph separators in *.api.json files

- .pullapprove.yml
- common/changes/@microsoft/api-extractor/pgonzal-yaml-documenter9_2017-09-28-01-01.json
- libraries/api-documenter/src/yaml/IYamlApiFile.ts
- libraries/api-documenter/src/yaml/YamlGenerator.ts
- libraries/api-documenter/src/yaml/typescript.schema.json
- libraries/api-extractor/src/aedoc/ApiDocumentation.ts
The updated YAML schema supports a number of features that were previously solved using workarounds.
I am also removing the "api-extractor-approvers" group, since it was basically requiring me to self-approve all my PRs.
> Replace documentation workarounds with YAML fields

- apps/rush/src/utilities/VersionManager.ts
- apps/rush/src/utilities/test/VersionManager.test.ts
- apps/rush/src/utilities/test/repo/g/package.json
- apps/rush/src/utilities/test/repo/rush.json
Add a test case for it as well.
> Fix a bug where devDependency version does not get updated when there is no dependency.

- apps/rush/src/actions/PublishAction.ts
This change allows you to pass in a `--tag <tagname>` parameter to rush publish.
> Rush publish: Add npm tag support via --tag

- apps/rush/src/taskRunner/TaskRunner.ts
Problem: If a cyclic dependency exists, "rush install" would succeed, but "rush rebuild" would fail with a stack overflow error.
This PR adds an explicit check for such cycles.  If found, it displays the chain of dependencies that's causing the trouble, and recommends to use the "cyclicDependencyProjects" option in rush.json.
> Fix "rush rebuild" a stack overflow error when a cyclic dependency is encountered

- .gitignore
- common/changes/@microsoft/node-core-library/pgonzal-escape-bug_2017-10-13-18-28.json
- libraries/api-documenter/.gitignore
- libraries/api-documenter/src/MarkdownRenderer.ts
- libraries/api-documenter/src/index.ts
- libraries/api-documenter/src/test/ExpectedOutput.md
- libraries/api-documenter/src/test/MarkdownPageRenderer.test.ts
- libraries/node-core-library/src/FileDiffTest.ts
string.replace("x", "y") only replaces the first match.
> Fix bug where api-documenter was incorrectly escaping certain special characters

- common/changes/@microsoft/api-extractor/pgonzal-ae-fixes_2017-10-20-19-24.json
- libraries/api-extractor/src/DocElementParser.ts
- libraries/api-extractor/src/ast/AstMethod.ts
- libraries/api-extractor/src/ast/AstProperty.ts
- libraries/api-extractor/src/ast/AstStructuredType.ts
- libraries/api-extractor/testInputs/example1/index.ts
This PR takes care of two longstanding backlog issues:
- For class properties such as `public readonly x: Y;`, the `readonly` modifier is now handled correctly
- If a class's constructor is marked as internal, API Extractor generates this boilerplate in the Remarks documentation:
> The constructor for this class is marked as internal. Third-party code should not extend subclasses of the ${this.name} class or instantiate it directly.
> Two minor fixes for API Extractor

- common/changes/@microsoft/api-documenter/pgonzal-publish-api-documenter_2017-10-20-23-51.json
- common/changes/@microsoft/api-extractor/pgonzal-publish-api-documenter_2017-10-21-02-18.json
- libraries/api-documenter/LICENSE
- libraries/api-documenter/README.md
- libraries/api-documenter/package.json
- libraries/api-documenter/src/cli/ApiDocumenterCommandLine.ts
- libraries/api-documenter/src/cli/MarkdownAction.ts
- libraries/api-documenter/src/cli/YamlAction.ts
- libraries/api-extractor/README.md
- libraries/api-extractor/src/cli/RunAction.ts
- libraries/api-extractor/src/extractor/Extractor.ts
- rush.json
Since this tool has a command line, we are publishing the NPM package so that people can now use it without having to enlist and build the web-build-tools repo.  It should still be considered a "code sample" level of support.
> Enable publishing for api-documenter tool

- libraries/api-documenter/src/cli/YamlAction.ts
- libraries/api-documenter/src/utils/DocItemSet.ts
- libraries/api-documenter/src/yaml/OfficeYamlDocumenter.ts
- libraries/api-documenter/src/yaml/YamlDocumenter.ts
Office add-ins had two minor additional requirements beyond the normal api-documenter feature set:
- Ability to mix code snippets into the "Remarks" section for a class
- Ability to hyperlink the "Api Set" tags
This is a prototype that shows how the YamlDocumenter.ts class can be extended; going forward the OfficeYamlDocumenter.ts subclass would be owned by the Office group.
> Add an api-documenter switch for use with Office add-ins

- apps/rush-lib/src/cli/utilities/ChangelogGenerator.ts
When a release is published without any change log entries (e.g. because of a version bump), we currently show a "changes not tracked" notice, for example:
> ## 3.2.2
> Mon, 31 Jul 2017 21:18:26 GMT
> 
> *Changes not tracked*
>
> ## 3.2.1
> Thu, 27 Jul 2017 01:04:48 GMT
>
> ### Patches
> 
> - Upgrade to the TS2.4 version of the build tools and restrict the dependency version requirements.
>
This notice suggests that we made a mistake or did something secret.  Maybe our tooling is broken? 
Maybe the change tracking was disabled for that time period?
We want the message to indicate that there were no significant changes (other than the version bump). 
I'm proposing to change the message to this:
> ## 3.2.2
> Mon, 31 Jul 2017 21:18:26 GMT
> 
> *Version update only*
>
(Feel free to suggest an …
> Improve wording of Rush change log notice

- apps/rush-lib/src/cli/actions/ChangeAction.ts
- apps/rush-lib/src/cli/utilities/ChangeFiles.ts
If 'rush change' finds previously entered comments about current change, it will list those out and provide one option to skip adding more comments, and the other to append more comments.
Examples interactions (Package one has existing comments, and package two does not):
PackageOneName 
Found existing comments:
> blah blah
> I have more to say
? Append to existing comments or skip: Skip
PackageTwoName
? Describe changes, or ENTER if no changes: I have something to say
> 'rush change' should respect previously entered comments for the change.

- apps/rush-lib/src/cli/utilities/InstallManager.ts
Issue #394 reported that when using NPM 5 with Rush, people were encountering this error during "rush link":
```
ERROR: Failed to parse package.json for foo: Invalid version: "file:projects/example.tgz"
```
This turned out to be another NPM 5 regression, tracked externally as [NPM issue 19006](https://github.com/npm/npm/issues/19006).  This PR implements a temporary workaround:  After running "npm install", Rush will check the package.json files and fix up any corrupted "version" fields.
> Implement a temporary workaround for an NPM 5 regression

- apps/api-extractor/package.json
- common/changes/@microsoft/api-extractor/pgonzal-upgrade-cyclic-deps_2017-11-01-05-28.json
- common/changes/@microsoft/gulp-core-build-karma/pgonzal-upgrade-cyclic-deps_2017-11-01-05-28.json
- common/changes/@microsoft/gulp-core-build-mocha/pgonzal-upgrade-cyclic-deps_2017-11-01-05-28.json
- common/changes/@microsoft/gulp-core-build-sass/pgonzal-upgrade-cyclic-deps_2017-11-01-05-28.json
- common/changes/@microsoft/gulp-core-build-serve/pgonzal-upgrade-cyclic-deps_2017-11-01-05-28.json
- common/changes/@microsoft/gulp-core-build-typescript/pgonzal-upgrade-cyclic-deps_2017-11-01-05-28.json
- common/changes/@microsoft/gulp-core-build-webpack/pgonzal-upgrade-cyclic-deps_2017-11-01-05-28.json
- common/changes/@microsoft/gulp-core-build/pgonzal-upgrade-cyclic-deps_2017-11-01-05-28.json
- common/changes/@microsoft/node-core-library/pgonzal-upgrade-cyclic-deps_2017-11-01-05-28.json
- common/changes/@microsoft/ts-command-line/pgonzal-upgrade-cyclic-deps_2017-11-01-05-28.json
- common/config/rush/npm-shrinkwrap.json
- core-build/gulp-core-build-karma/package.json
- core-build/gulp-core-build-mocha/package.json
- core-build/gulp-core-build-sass/package.json
- core-build/gulp-core-build-serve/package.json
- core-build/gulp-core-build-typescript/package.json
- core-build/gulp-core-build-webpack/package.json
- core-build/gulp-core-build/package.json
- libraries/node-core-library/package.json
- libraries/ts-command-line/package.json
Some people reported build failures because **gulp-core-builds** has an indirect dependency on @types/chalk, and DefinitelyTyped doesn't lock these versions.  This PR fixes that.
It also upgrades the cyclic dependencies, so that our *.api.json files are using the latest file format.
> Fix @types/chalk error and upgrade cyclic dependencies

- apps/rush-lib/src/cli/utilities/ChangelogGenerator.ts
Force change log name to be the same as package name to handle the error case when package is renamed but change log is not.
> Force change log name to be the same as package name.

- apps/rush-lib/src/cli/actions/CustomCommandFactory.ts
- apps/rush-lib/src/cli/actions/CustomRushAction.ts
- apps/rush-lib/src/cli/taskRunner/TaskRunner.ts
Some people reported that "rush rebuild" would  make their desktop computers slow because the `--parallelism` flag defaults to using all CPU cores.  This only affects a minority of people, but it's a bad experience.  This PR decreases the default by 1, which was reported to fix the problem.
> Decrease default Rush parallelism

- apps/rush-lib/src/cli/actions/CustomCommandFactory.ts
- apps/rush-lib/src/cli/actions/CustomRushAction.ts
- apps/rush-lib/src/cli/actions/InstallAction.ts
- apps/rush-lib/src/cli/actions/RushCommandLineParser.ts
- apps/rush-lib/src/cli/test/Cli.test.ts
The `rush -h` command was failing when you ran it outside a repo, because code had crept in that assumes there is a RushConfiguration object.
This broke our [3 Minute Demo](https://github.com/Microsoft/web-build-tools/wiki/Rush#3-minute-demo).
> Fix the regression where "rush -h" didn't work outside a repo

- apps/api-extractor/src/ApiDefinitionReference.ts
- apps/api-extractor/src/DocElementParser.ts
- apps/api-extractor/src/DocItemLoader.ts
- apps/api-extractor/src/ExtractorContext.ts
- apps/api-extractor/src/ResolvedApiItem.ts
- apps/api-extractor/src/TypeScriptHelpers.ts
- apps/api-extractor/src/aedoc/ApiDocumentation.ts
- apps/api-extractor/src/aedoc/Tokenizer.ts
- apps/api-extractor/src/aedoc/test/Tokenizer.test.ts
- apps/api-extractor/src/ast/AstItem.ts
- apps/api-extractor/src/ast/AstItemContainer.ts
- apps/api-extractor/src/ast/AstMember.ts
- apps/api-extractor/src/ast/AstMethod.ts
- apps/api-extractor/src/ast/AstModuleVariable.ts
- apps/api-extractor/src/ast/AstNamespace.ts
- apps/api-extractor/src/ast/AstPackage.ts
- apps/api-extractor/src/ast/AstStructuredType.ts
- apps/api-extractor/src/extractor/Extractor.ts
- apps/api-extractor/src/generators/ApiJsonGenerator.ts
- apps/api-extractor/src/generators/Span.ts
- apps/api-extractor/src/markup/Markup.ts
- apps/api-extractor/src/test/ApiDefinitionReference.test.ts
- apps/api-extractor/tsconfig.json
- common/changes/@microsoft/api-extractor/pgonzal-ae-strict-null-checks_2017-11-15-02-10.json
Turn on the **strict-null-checks** setting in tsconfig.json.
> Enable strict-null-checks for api-extractor

- apps/rush-lib/src/cli/utilities/test/packages/c/package.json
GitHub is detecting a security vulnerability in an old version of handlebars, which is being referenced by a sample `package.json` file. We simply need to update this version to remove the warning, which should have no side effects, since this file isn't really used by anything except for some unit tests which read the `rush.json` and `package.json` files.
> Update handlebars in package.json samples so GitHub does not show a warning message

- apps/rush-lib/src/cli/actions/GenerateAction.ts
- apps/rush-lib/src/cli/actions/InstallAction.ts
- apps/rush-lib/src/cli/utilities/InstallManager.ts
We used to extract the tarball and compare the package.json to see if we need to generate a new one. Then we would create a new directory, use it to create a new tarball, then delete the temp directory. This led to situations where locks were still being held on various files.
Instead, we now leave the temp folder in place, and check A) that the tarball exists, B) that the temp file exists, and C) that the temp package.json matches. In case of error during tarball creation, we delete the temp folder.
This is much more straightforward and removes the .old and .new folder distinction. It is also much faster as we don't have to extract every tarball during every rush install.
> Fix issues with file locks during tarball creation

- apps/rush-lib/src/cli/actions/ChangeAction.ts
- apps/rush-lib/src/cli/actions/PublishAction.ts
- apps/rush-lib/src/cli/utilities/ChangelogGenerator.ts
- apps/rush-lib/src/cli/utilities/PublishUtilities.ts
- apps/rush-lib/src/cli/utilities/test/ChangeFiles.test.ts
- apps/rush-lib/src/cli/utilities/test/ChangelogGenerator.test.ts
- apps/rush-lib/src/cli/utilities/test/PublishUtilities.test.ts
- apps/rush-lib/src/cli/utilities/test/hotfixWithPatchChanges/change1.json
- apps/rush-lib/src/cli/utilities/test/hotfixWithPatchChanges/change2.json
- apps/rush-lib/src/cli/utilities/test/hotfixWithPatchChanges/change3.json
- apps/rush-lib/src/cli/utilities/test/multipleHotfixChanges/change1.json
- apps/rush-lib/src/cli/utilities/test/multipleHotfixChanges/change2.json
- apps/rush-lib/src/cli/utilities/test/multipleHotfixChanges/change3.json
- apps/rush-lib/src/cli/utilities/test/packages/rush.json
- apps/rush-lib/src/cli/utilities/test/rootHotfixChange/change1.json
- apps/rush-lib/src/data/ChangeManagement.ts
- apps/rush-lib/src/data/RushConfiguration.ts
- apps/rush-lib/src/data/test/RushConfiguration.test.ts
- apps/rush-lib/src/data/test/repo/rush-npm.json
- apps/rush-lib/src/schemas/rush.schema.json
- common/reviews/api/rush-lib.api.ts
- rush.json
Added a 'hotfix' bump option for `rush change`
It will append -hotfix.1 to the version number or increment the hotfix version if already on a hotfix branch.
> Enabled hotfix changes for rush

- apps/rush-lib/src/cli/actions/VersionAction.ts
We should only need to do the second commit if there are changes to `package.json` files.
> Fix issue with "git commit" not having any files added to index 

- apps/api-extractor/src/DebugRun.ts
- apps/api-extractor/src/ExternalApiHelper.ts
- apps/api-extractor/src/cli/ApiExtractorCommandLine.ts
- apps/api-extractor/src/cli/RunAction.ts
- apps/api-extractor/src/extractor/Extractor.ts
- apps/api-extractor/src/extractor/MonitoredLogger.ts
- common/changes/@microsoft/api-extractor/pgonzal-extractor-error-detection_2017-11-23-01-11.json
- common/changes/@microsoft/gulp-core-build-typescript/pgonzal-extractor-error-detection_2017-11-23-01-11.json
- common/reviews/api/api-extractor.api.ts
- core-build/gulp-core-build-typescript/src/ApiExtractorTask.ts
If API Extractor reports warnings or errors, the build should fail.  However, since `Extractor.analyzeProject()` doesn't return a value, the only way to determine failure is by providing a customLogger.  (This is what **gulp-core-build** does.)  This PR adds a boolean return value to avoid this limitation.
Based on feedback, we're also renaming `Extractor.analyzeProject()` to `Extractor.processProject()`.
This PR also updates the api-extractor command-line tool to return a nonzero exit code if an error occurs.
> Improve api-extractor invocation so it's easier to determine failure

- common/changes/@microsoft/gulp-core-build/olfilato-optional-overrides-jest_2017-11-30-22-33.json
- common/reviews/api/gulp-core-build.api.ts
- common/reviews/api/node-library-build.api.ts
- common/reviews/api/web-library-build.api.ts
- core-build/gulp-core-build/src/tasks/JestTask.ts
- core-build/gulp-core-build/src/tasks/jest.schema.json
Two new optional arguments for Jest task: moduleDirectories and rootDir (directly corresponding to their Jest CLI counterparts). Added logic to the task, so that it automatically picks the default values for those two arguments if they were not provided, otherwise it uses the provided ones.
> Additional jest task arguments; ability to choose between default and passed args

- apps/rush-lib/src/cli/utilities/pnpm/PnpmShrinkwrapFile.ts
There are certain dependencies in the shrinkwrap that have a different format, e.g.:
```
'file:projects/gulp-core-build-karma.tgz':
dependencies:
'@microsoft/node-library-build': 4.2.14
'@types/bluebird': 3.5.3
'@types/gulp': 3.8.32
'@types/karma': 0.13.33
'@types/log4js': 0.0.33
'@types/node': 6.0.88
chai: 3.5.0
gulp: 3.9.1
gulp-karma: /gulp-karma/0.0.5/karma@0.13.22
istanbul-instrumenter-loader: /istanbul-instrumenter-loader/3.0.0/webpack@3.6.0
karma: 0.13.22
karma-coverage: 0.5.5
karma-mocha: /karma-mocha/0.2.2/mocha@3.4.2
karma-mocha-clean-reporter: 0.0.1
karma-phantomjs-launcher: /karma-phantomjs-launcher/1.0.4/karma@0.13.22
karma-sinon-chai: /karma-sinon-chai/1.2.4/5fc1304e1e69a328078cebf8183ed10a
karma-webpack: /karma-webpack/2.0.9/webpack@3.6.0
lolex: 1.4.0
mocha: 3.4.2 …
```
> Fix the way pnpm shrinkwrap file checks for special dependency

- apps/rush-lib/src/data/RushConfigurationProject.ts
- apps/rush-lib/src/data/VersionMismatchFinder.ts
- apps/rush-lib/src/data/test/RushConfiguration.test.ts
- apps/rush-lib/src/data/test/repo/rush-npm.json
- apps/rush-lib/src/schemas/rush.schema.json
- apps/rush/README.md
- common/reviews/api/rush-lib.api.ts
The `rush check` command is normally used to confirm/enforce a single consistent version for any direct-dependencies, across all projects in the repo.
However, sometimes a project needs to violate this rule.  For example, because it is in the process of being migrated into the monorepo, or because it is a backwards compatibility shim.
To support this scenario, I'm introducing a new project-specific setting in **rush.json**.  For example, this is how you would disable `rush check` from processing project2:
```json
"projects": [
{
"packageName": "project1",
"projectFolder": "project1"
},
{
"packageName": "project2",
"projectFolder": "project2",
"skipRushCheck": true
},
{
"packageName": "project3",
"projectFolder": "project3"
}
]
```
> Introduce a new setting "skipRushCheck"

- apps/api-extractor/src/TypeScriptHelpers.ts
- apps/api-extractor/src/generators/PackageTypingsGenerator.ts
- apps/api-extractor/src/test/TypeScriptHelpers.test.ts
- apps/rush-lib/config/api-extractor.json
- build-tests/api-extractor-test-01/dist/index-internal.d.ts
- build-tests/api-extractor-test-01/etc/api-extractor-test-01.api.ts
- build-tests/api-extractor-test-01/src/IInterfaceAsDefaultExport.ts
- build-tests/api-extractor-test-01/src/index.ts
- build-tests/api-extractor-test-02/dist/index-internal.d.ts
- build-tests/api-extractor-test-02/etc/api-extractor-test-02.api.ts
- build-tests/api-extractor-test-02/src/index.ts
- common/changes/@microsoft/api-extractor/pgonzal-dts-generator-5_2018-01-12-01-56.json
- common/changes/@microsoft/gulp-core-build-typescript/pgonzal-dts-generator-5_2018-01-12-01-56.json
- core-build/gulp-core-build-typescript/src/ApiExtractorTask.ts
- core-build/gulp-core-build-typescript/src/schemas/api-extractor.schema.json
- core-build/test-web-library-build/config/api-extractor.json
- libraries/decorators/config/api-extractor.json
This PR fixes a few more PackageTypesGenerator edge cases, enables support in for this feature in GCB, and enables it for some preliminary projects.  Specific fixes:
- The \@packagedocumentation comment is now passed through to the emitted d.ts file
- Fixed a bug where certain definitions were incorrectly classified as ambient
> Enable generatePackageTypings for some projects

- apps/api-extractor/package.json
- common/changes/@microsoft/api-extractor/pgonzal-fix-travis_2018-01-17-20-53.json
- common/changes/@microsoft/gulp-core-build-karma/pgonzal-fix-travis_2018-01-17-20-53.json
- common/changes/@microsoft/gulp-core-build-mocha/pgonzal-fix-travis_2018-01-17-20-53.json
- common/changes/@microsoft/gulp-core-build-sass/pgonzal-fix-travis_2018-01-17-20-53.json
- common/changes/@microsoft/gulp-core-build-serve/pgonzal-fix-travis_2018-01-17-20-53.json
- common/changes/@microsoft/gulp-core-build-typescript/pgonzal-fix-travis_2018-01-17-20-53.json
- common/changes/@microsoft/gulp-core-build-webpack/pgonzal-fix-travis_2018-01-17-20-53.json
- common/changes/@microsoft/gulp-core-build/pgonzal-fix-travis_2018-01-17-20-53.json
- common/changes/@microsoft/node-core-library/pgonzal-fix-travis_2018-01-17-20-53.json
- common/changes/@microsoft/ts-command-line/pgonzal-fix-travis_2018-01-17-20-53.json
- common/config/rush/shrinkwrap.yaml
- core-build/gulp-core-build-karma/package.json
- core-build/gulp-core-build-mocha/package.json
- core-build/gulp-core-build-sass/gulpfile.js
- core-build/gulp-core-build-sass/package.json
- core-build/gulp-core-build-serve/package.json
- core-build/gulp-core-build-typescript/gulpfile.js
- core-build/gulp-core-build-typescript/package.json
- core-build/gulp-core-build-webpack/package.json
- core-build/gulp-core-build/package.json
- libraries/node-core-library/package.json
- libraries/ts-command-line/package.json
- rush.json
This upgrades the cyclic dependencies in web-build-tools to complete the fix from #489.
> Fix tslint warnings that were breaking Travis

- common/changes/@microsoft/node-library-build/pgonzal-temp_2018-01-18-00-38.json
The recent changes didn't cause **node-library-build** to get published for some reason. This change log will.
> Force publishing of node-library-build

- common/changes/@microsoft/gulp-core-build/nickpape-stderr-causes-failure_2018-01-18-01-44.json
- common/reviews/api/gulp-core-build.api.ts
- core-build/gulp-core-build/src/IBuildConfig.ts
- core-build/gulp-core-build/src/index.ts
- core-build/gulp-core-build/src/logging.ts
- core-build/gulp-core-build/src/tasks/JestTask.ts
- core-build/gulp-core-build/src/test/mockBuildConfig.ts
If the `shouldWarningsFailBuild === true`, then we should capture anything written to `process.stderr`. If anything significant is written to `stderr`, we will fail the build.
We have had several cases where things are writing to stderr but are making it into the master build (and causing developers to get the "success with warnings" message). This change will make it impossible to check in any changes that will cause errant warnings to be written to the console.
> Anything written to stderr should cause process to fail

- apps/rush-lib/src/data/RushConfiguration.ts
- apps/rush-lib/src/data/test/RushConfiguration.test.ts
- apps/rush-lib/src/data/test/repo/rush-too-new.json
- common/changes/@microsoft/rush/pgonzal-rush-confusing-error_2018-01-19-20-15.json
The old error:
```
Your rush tool is version 4.2.3, but rush.json requires version 99.0.0. To upgrade, run "npm install @microsoft/rush -g".
```
The new error:
```
'Unable to load rush-too-new.json because its RushVersion is 99.0.0, whereas @microsoft/rush-lib is version 4.2.3. Consider upgrading the library.'
```
> Improve the error message when loading rush.json from a newer release

- common/changes/@microsoft/node-library-build/nickpape-errors-as-warnings_2018-01-18-22-09.json
- common/changes/@microsoft/web-library-build/nickpape-errors-as-warnings_2018-01-18-22-09.json
- common/reviews/api/node-library-build.api.ts
- common/reviews/api/web-library-build.api.ts
- core-build/node-library-build/gulpfile.js
- core-build/web-library-build/gulpfile.js
Treat warnings as errors in production mode when building node-library-build & web-library-build
> Treat warnings as errors in production mode when building node-library-build & web-library-build

- common/changes/@microsoft/stream-collator/nickpape-fix-stream-collator-warnings_2018-01-22-23-24.json
- libraries/stream-collator/src/Interleaver.ts
- libraries/stream-collator/src/test/Interleaver.test.ts
Stream collator appeared to have some code that redirected warnings from stderr to stdout. This was because we didn't want warnings to fail a Rush build. However, we have changed the implementation in Rush, so that Rush always reports everything written to stderr, and we have changed GCB to always fail if `treatWarningsAsErrors === true` and something is written to stderr.
The problem with the code the way it is right now is that Stream Collator is effectively swallowing warnings (by redirecting them to stdout), such that Rush is no longer able to report the warnings in the summary (whereas Rush used to watch for specific warning strings in order to report them in the summary even if they were written to stdout).
> Stop stream-collator from redirecting warnings to stdout

- rush.json
* This fixes an issue where the `--no-optional` flag had no effect. This makes WBT/Rush/pnpm more stable when working cross-platform between Mac and Windows.
https://github.com/pnpm/pnpm/issues/1014
> Bump PNPM to 1.31.0

- apps/rush-lib/src/cli/logic/pnpm/PnpmLinkManager.ts
- common/changes/@microsoft/rush/nickpape-pnpm-symlink-perf_2018-01-26-19-49.json
Right now, we are linking to the the symlink in the `common\temp\node_modules\.local\` folder. However, we ideally should follow that link. This will reduce the number of file system reads that are necessary when tooling code accesses the node_modules folder.
> Rush should link to the realpath of a symlink when using PNPM

- apps/rush-lib/src/cli/actions/CustomRushAction.ts
- apps/rush-lib/src/cli/logic/TaskSelector.ts
- apps/rush-lib/src/cli/taskRunner/TaskRunner.ts
- common/changes/@microsoft/rush/nickpape-rush-fast-build_2018-01-26-20-36.json
This is a useful feature in a developer's inner loop. Oftentimes, they may be working on a package, but they don't care about building downstream packages (perhaps they are running gulp serve in a leaf node, and just trying to fix a bug in a project in the middle of the tree). While this may not guarantee a 100% "correct"  build, it can be helpful for a large number of cases (especially when not changing any API signatures).
> Allow an incremental build mode where we dont invalidate downstream packages

- apps/rush-lib/src/cli/logic/InstallManager.ts
- apps/rush-lib/src/utilities/Utilities.ts
- common/changes/@microsoft/rush/nickpape-pnpm-clean-folders_2018-02-01-22-36.json
If you try to reinstall after the EPERM error in pnpm (https://github.com/pnpm/pnpm/issues/1015), you can end up with a corrupted store. It is safest to go ahead and clean out the store before attempting to reinstall.
> If an install fails, PNPM should clean store before restarting

- rush.json
1.31.6 had several bugfixes around optional dependencies which otherwise may cause problems in web-build-tools.
> Update PNPM to 1.32.0

- apps/rush-lib/src/cli/logic/PackageChangeAnalyzer.ts
- apps/rush-lib/src/cli/logic/base/BaseLinkManager.ts
- apps/rush-lib/src/cli/logic/test/PackageChangeAnalyzer.test.ts
- common/changes/@microsoft/rush/nickpape-rush-build-consider-shrinkwrap.json_2018-02-07-00-48.json
This will make `rush build` more reliable for the average user.
> Rush `build` should add shrinkwrap to package-deps hash

- rush.json
- Upgrade Rush to 4.2.5
- Lock NodeJS to supported LTS version ranges
> Upgrade Rush and lock NodeJS to LTS

- apps/api-extractor/src/generators/PackageTypingsGenerator.ts
- build-tests/api-extractor-test-01/dist/index-internal.d.ts
- build-tests/api-extractor-test-01/etc/api-extractor-test-01.api.ts
- build-tests/api-extractor-test-01/src/DefaultExportEdgeCase.ts
- build-tests/api-extractor-test-01/src/index.ts
- build-tests/api-extractor-test-02/dist/index-internal.d.ts
- build-tests/api-extractor-test-02/package.json
- build-tests/api-extractor-test-02/src/index.ts
- build-tests/api-extractor-test-02/tsconfig.json
- common/changes/@microsoft/api-extractor/pgonzal-ae-default-bug_2018-02-16-00-20.json
- common/changes/@microsoft/api-extractor/pgonzal-ae-default-bug_2018-02-16-00-21.json
- common/changes/@microsoft/api-extractor/pgonzal-ae-default-bug_2018-02-16-00-55.json
This fixes various minor issues encountered while migrating a bunch of projects to use the PackageTypingsGenerator:
- Fix a bug where class names were appearing as `default` in certain situations where `symbol.name` is returns `"default"` even though the definition has a name
- Ensure triple-slash references are included in the output *.d.ts file
- Fix a bug where several import/export patterns were not handled correctly
- Fix a bug where `symbolIsExported` was only considered the first time the Entry was encountered
> Several fixes for packageTypings generator

- apps/rush-lib/src/cli/logic/InstallManager.ts
- common/changes/@microsoft/rush/nickpape-dont-delete-store_2018-02-14-02-42.json
The store should be transactional and therefore should never be corrupted. Only delete the store if they give us the --clean flag.
> Only delete PNPM store in a --clean install

- apps/api-extractor/src/PrettyPrinter.ts
- apps/api-extractor/src/generators/PackageTypingsGenerator.ts
- apps/api-extractor/src/generators/Span.ts
- build-tests/api-extractor-test-01/dist/index-internal.d.ts
- build-tests/api-extractor-test-01/etc/api-extractor-test-01.api.ts
- build-tests/api-extractor-test-01/src/TypeReferencesInAedoc.ts
- build-tests/api-extractor-test-01/src/index.ts
- build-tests/api-extractor-test-02/dist/index-internal.d.ts
- build-tests/api-extractor-test-02/etc/api-extractor-test-02.api.ts
- build-tests/api-extractor-test-02/src/ImportDeduping1.ts
- build-tests/api-extractor-test-02/src/ImportDeduping2.ts
- build-tests/api-extractor-test-02/src/index.ts
- common/changes/@microsoft/api-extractor/pgonzal-ae-import-multiplicity_2018-02-17-01-52.json
This PR improves the way that imports are processed by the packageTypings feature for API Extractor.  For example, these definitions:
```typescript
import * as semver1 from 'semver';
import * as semver2 from 'semver';
import * as semver3 from 'semver';
import { ISimpleInterface } from 'api-extractor-test-01';
import { ISimpleInterface as ISimpleInterface2 } from 'api-extractor-test-01';
```
...will be simplified to this:
```typescript
import * as semver1 from 'semver';
import { ISimpleInterface } from 'api-extractor-test-01';
```
...and all references to these symbols will be automatically fixed up to use the simplified names.
This change required some improvements to the Span class:  It now tracks the parent and previous sibling for each span in the tree.  Also the `Span.modify()` helper …
> Fix issue with duplicated import statements in generated *.d.ts files

- .pullapprove.yml
- rush.json
Bump PNPM to `1.33.2`
* This version has bundled its dependencies, making it far more deterministic and reliable
* This version has removed several dependencies, making it faster to install and execute.
> Bump PNPM to a version that has bundled dependencies

- apps/rush-lib/package.json
- apps/rush-lib/src/start.ts
- apps/rush/package.json
- common/changes/@microsoft/rush/nickpape-rush-warn-on-unsupported-node_2018-02-22-02-18.json
* Versions <6 will fail, since they don't support all of es6
* Versions >=6.0.0 <=6.4.0 may fail, since they don't support all of es6
* Versions ^7.0.0 are non-LTS, and are not officially supported but should work.
* Versions ^9.0.0 are non-LTS, and are not officially supported.
> Rush should warn about unsupported versions of the NodeJS runtime

- common/changes/@microsoft/gulp-core-build-karma/nickpape-pin-karma-webpack_2018-02-27-19-44.json
- core-build/gulp-core-build-karma/package.json
3.0.12 has missing dependencies in it's package.json (on babel-runtime), which is causing pnpm installations to fail. Since we are deprecating karma, the easiest fix is to simply pin karma-webpack to a working version.
> Pin karma-webpack to 3.0.9

- apps/rush-lib/src/cli/logic/InstallManager.ts
- apps/rush-lib/src/cli/logic/base/BaseShrinkwrapFile.ts
- apps/rush-lib/src/cli/logic/npm/NpmShrinkwrapFile.ts
- apps/rush-lib/src/cli/logic/pnpm/PnpmShrinkwrapFile.ts
- apps/rush-lib/src/cli/logic/test/ShrinkwrapFile.test.ts
- apps/rush-lib/src/cli/logic/test/shrinkwrapFile/shrinkwrap.yaml
- common/changes/@microsoft/rush/nickpape-rush-no-generate_2018-02-24-01-58.json
In NPM-land, we used to check to see if a dependency at the root of the node_modules satisfied a dependency described in package.json. This worked because NPM describes the folder structure, as opposed to PNPM, which describes the dependency graph.
With the initial release of PNPM, we lost this heuristic. PNPM only installs what is in the shrinkwrap, regardless of what is in the package.json.
The solution is to modify the temp shrinkwrap file and add the missing dependency, but only if it is being reused by another Rush project.
There are 2 major changes:
1. When we are checking that the dependencies are satisfied by the shrinkwrap, if a dependency is missing from a project, we check all the other projects and collect the versions of the dependency that are being used. We then use the …
> Rush: reduce how often we need to run generate

- apps/rush-lib/src/cli/actions/GenerateAction.ts
- apps/rush-lib/src/cli/logic/InstallManager.ts
- apps/rush-lib/src/index.ts
- apps/rush-lib/src/utilities/LastInstallFlag.ts
- apps/rush-lib/src/utilities/test/LastInstallFlag.test.ts
- apps/rush/src/RushVersionSelector.ts
- common/changes/@microsoft/rush/nickpape-rush-test-pass_2018-03-01-23-00.json
- common/reviews/api/rush-lib.api.ts
* Introduce a last-install.flag API
* Also, fix a bug with installing the package manager
> Abstract Last-Install.flag file into a reusable class

- apps/rush-lib/src/cli/actions/GenerateAction.ts
- common/changes/@microsoft/rush/pgonzal-rush-conservative-generate_2018-03-02-00-20.json
- common/changes/@microsoft/rush/pgonzal-rush-conservative-generate_2018-03-02-00-50.json
Scenario:
1. A person adds a new dependency to their project's `package.json`
2. This requires them to run `rush generate`
Normally this also forces an upgrade of all SemVer range dependencies in shrinkwrap.yaml, which frequently requires the person to fix compatibility issues unrelated to their change.
This is unnecessary for repos that already handle these upgrades automatically in a separate branch.  This PR introduces a new switch "--conservative" that causes PNPM to upgrade only the minimal set of dependencies required to satisfy your `package.json` changes.
**NOTE:** This change requires pnpm-1.35.2 with the fix for https://github.com/pnpm/pnpm/issues/1054
> Add a "--conservative" flag for "rush generate"

- apps/api-extractor/.vscode/launch.json
- apps/api-extractor/src/extractor/Extractor.ts
- apps/api-extractor/src/generators/packageTypings/Entry.ts
- apps/api-extractor/src/generators/packageTypings/PackageTypingsGenerator.ts
- build-tests/api-extractor-test-01/dist/index-preview.d.ts
- build-tests/api-extractor-test-01/dist/index-public.d.ts
- build-tests/api-extractor-test-02/dist/index-preview.d.ts
- build-tests/api-extractor-test-02/dist/index-public.d.ts
- build-tests/api-extractor-test-04/dist/index-internal.d.ts
- build-tests/api-extractor-test-04/dist/index-preview.d.ts
- build-tests/api-extractor-test-04/dist/index-public.d.ts
- common/changes/@microsoft/api-extractor/pgonzal-ae-trimming-2_2018-03-06-01-00.json
This is part of the sprint for trimming definitions from the generated *.d.ts files:
- Set up unit test projects
- Implement temporary strategy for parsing comments
- Trim top-level definitions based on release type
> (api-extractor) Add preliminary support for generating public/preview *.d.ts outputs

- apps/api-documenter/package.json
- apps/api-extractor/package.json
- build-tests/api-extractor-test-01/package.json
- build-tests/api-extractor-test-03/package.json
- build-tests/web-library-build-test/package.json
- common/changes/@microsoft/api-documenter/pgonzal-fix-types_2018-03-12-19-53.json
- common/changes/@microsoft/api-extractor/pgonzal-fix-types_2018-03-12-19-53.json
- common/changes/@microsoft/gulp-core-build-webpack/pgonzal-fix-types_2018-03-12-19-53.json
- common/changes/@microsoft/loader-load-themed-styles/pgonzal-fix-types_2018-03-12-19-53.json
- common/changes/@microsoft/resolve-chunk-plugin/pgonzal-fix-types_2018-03-12-19-53.json
- common/changes/@microsoft/set-webpack-public-path-plugin/pgonzal-fix-types_2018-03-12-19-53.json
- common/changes/@microsoft/ts-command-line/pgonzal-fix-types_2018-03-12-19-53.json
- common/config/rush/shrinkwrap.yaml
- core-build/gulp-core-build-webpack/package.json
- libraries/ts-command-line/package.json
- webpack/loader-load-themed-styles/package.json
- webpack/resolve-chunk-plugin/package.json
- webpack/set-webpack-public-path-plugin/package.json
Recently we had some upgrade breaks due to new versions of "@types/" packages being published with breaking changes.  This PR updates projects to follow the rules:
1. Projects must never use a "~" range for @types projects, because typings never follow SemVer
2. Projects must directly reference the transitive closure of indirect dependencies, since "@types/" projects never constrain versions for their dependencies on other "@types/" packages
> Lock down @types versions

- common/scripts/InstallRushOnlyIfNeeded.js
Our CI definition is failing. This will help investigate.
> Enable logging for broken InstallRushOnlyIfNeeded.js

- apps/api-documenter/src/yaml/YamlDocumenter.ts
- apps/api-extractor/src/generators/ApiFileGenerator.ts
- apps/api-extractor/src/generators/packageTypings/PackageTypingsGenerator.ts
- apps/rush-lib/src/cli/logic/InstallManager.ts
- apps/rush-lib/src/cli/logic/pnpm/PnpmLinkManager.ts
- apps/rush-lib/src/data/ApprovedPackagesConfiguration.ts
- apps/rush-lib/src/data/test/RushConfiguration.test.ts
- apps/rush-lib/src/utilities/Utilities.ts
- common/changes/@microsoft/api-documenter/pgonzal-text-lib_2018-03-14-23-06.json
- common/changes/@microsoft/api-extractor/pgonzal-text-lib_2018-03-14-23-06.json
- common/changes/@microsoft/node-core-library/pgonzal-text-lib_2018-03-14-23-06.json
- common/changes/@microsoft/rush/pgonzal-text-lib_2018-03-14-23-06.json
- common/reviews/api/node-core-library.api.ts
- libraries/node-core-library/src/FileDiffTest.ts
- libraries/node-core-library/src/JsonFile.ts
- libraries/node-core-library/src/Text.ts
- libraries/node-core-library/src/index.ts
This PR introduces three new API functions:
- Text.replaceAll()
- Text.convertToCrLf()
- Text.convertToLf()
This deduplicates a bunch of expressions and utility functions scattered throughout our code.
> Consolidate some text handling functions

- apps/rush-lib/src/cli/actions/CustomRushAction.ts
- apps/rush-lib/src/cli/logic/TaskSelector.ts
- apps/rush-lib/src/cli/taskRunner/TaskRunner.ts
- common/changes/@microsoft/rush/chrisgo-max-parallel_2018-03-16-21-22.json
A change was made recently to rush to make it such that the default parallelism is set to be 1 less than the number of cores on windows. This was to address some performance issues windows users were experiencing when trying to do other tasks while a rush build was running. 
However, in CI environments, we want the maximum amount of available parallelism to get faster builds. This change introduces a 'max' argument to the -p flag that always sets the paralellism to equal the number of cores on the CPU.
> Add support for using all cores on windows machines with -p max flag

- apps/api-extractor/src/api/ApiItem.ts
- apps/api-extractor/src/generators/packageTypings/AstDeclaration.ts
- apps/api-extractor/src/generators/packageTypings/AstSymbol.ts
- apps/api-extractor/src/generators/packageTypings/AstSymbolTable.ts
- build-tests/api-extractor-test-01/dist/index-internal.d.ts
- build-tests/api-extractor-test-01/dist/index-preview.d.ts
- build-tests/api-extractor-test-01/dist/index-public.d.ts
- build-tests/api-extractor-test-01/etc/api-extractor-test-01.api.ts
- build-tests/api-extractor-test-01/src/DeclarationMerging.ts
- build-tests/api-extractor-test-01/src/index.ts
- common/changes/@microsoft/api-extractor/pgonzal-merged-declaration_2018-03-19-18-06.json
- common/reviews/api/api-extractor.api.ts
When we tried to upgrade the cyclic dependencies, API Extractor failed to process an API item that accidentally had two definitions that were being merged:
```typescript
/**
* Return value of a method or function.
* @alpha
*/
export interface IApiReturnValue {
/**
* The data type returned by the function
*/
type: string;
/**
* Describes the return value
*/
description: MarkupBasicElement[];
}
. . .
/**
* Describes a return type and description of the return type
* that is given in documentation comments.
*
* @alpha
*/
export interface IApiReturnValue {
type: string;
description: MarkupBasicElement[];
}
```
I removed the duplicate definition, but also fixed up the *.d.ts generator to handle this case correctly.
> [api-extractor] Fix a bug with handling of merged declarations

- apps/rush-lib/src/cli/logic/pnpm/PnpmShrinkwrapFile.ts
- apps/rush-lib/src/start.ts
- apps/rush/package.json
- apps/rush/src/start.ts
- common/changes/@microsoft/rush/pgonzal-rush-fixes_2018-03-20-19-33.json
- common/changes/@microsoft/rush/pgonzal-rush-fixes_2018-03-20-19-34.json
1. The common/temp/shrinkwrap.yaml was folding duplicates, which made diffs less readable
2. The environment version check needs to happen during startup of rush, not in the entry point for rush-lib  (Regression from #539)
> Fix two minor Rush issues

- apps/rush-lib/src/cli/actions/CustomCommandFactory.ts
- apps/rush-lib/src/cli/actions/CustomRushAction.ts
- apps/rush-lib/src/cli/logic/TaskSelector.ts
- apps/rush-lib/src/cli/taskRunner/ProjectTask.ts
- apps/rush-lib/src/data/CommandLineConfiguration.ts
- apps/rush-lib/src/schemas/command-line.schema.json
- common/changes/@microsoft/rush/qz2017-custom_action_2018-03-20-22-08.json
1. Add optional flag to custom command. If true, only projects with corresponding npm script will run this command. If false, all projects should have the npm script and run this command.
2. Fix naming in custom action code to be more generic.
3. Only collect telemetry for build/rebuild command.
> Add optional flag to custom command and fix other minor issues

- apps/api-documenter/src/yaml/OfficeYamlDocumenter.ts
- common/changes/@microsoft/api-documenter/kbrandl-patch-1_2018-03-21-12-52.json
- common/changes/@microsoft/api-documenter/kbrandl-patch-1_2018-03-21-12-53.json
- common/changes/@microsoft/api-documenter/kbrandl-patch-1_2018-03-21-12-54.json
- Use `#### Examples` heading for code snippets section (instead of `## Snippets`).
- Designate proper language for each code snippet (TypeScript or JavaScript).
- Customize the `API Set #.#` hyperlink target by host.
> Update Office Extension to API Documenter

- apps/rush-lib/src/cli/actions/PublishAction.ts
- common/changes/@microsoft/rush/qz2017-pack_2018-03-21-20-10.json
The parameter "--pack" means packing packages into tarballs instead of publishing to npm registry.
> Support packing packages into tarballs in rush publish action

- common/changes/@microsoft/gulp-core-build-typescript/lib-esnext_2018-03-21-18-42.json
- common/changes/@microsoft/gulp-core-build/lib-esnext_2018-03-21-18-42.json
- common/reviews/api/gulp-core-build.api.ts
- common/reviews/api/node-library-build.api.ts
- common/reviews/api/web-library-build.api.ts
- core-build/gulp-core-build-typescript/src/TypeScriptTask.ts
- core-build/gulp-core-build/src/IBuildConfig.ts
- core-build/gulp-core-build/src/index.ts
This option allows projects to emit modules to the specified directory
using `module: 'esnext'`.
Fixes #576
> Add a `libESNextFolder` option

- common/changes/@microsoft/set-webpack-public-path-plugin/mamooty-findLast_2018-03-29-23-09.json
- common/reviews/api/set-webpack-public-path-plugin.api.ts
- webpack/set-webpack-public-path-plugin/README.md
- webpack/set-webpack-public-path-plugin/src/SetPublicPathPlugin.ts
- webpack/set-webpack-public-path-plugin/src/codeGenerator.ts
Adding new option to ISetWebpackPublicPathOptions, called preferLastFoundScript. This allows for finding the last matching script instead of the first
> Adding new findLast option to ISetWebpackPublicPathOptions

- apps/rush-lib/package.json
- apps/rush-lib/src/cli/logic/pnpm/PnpmLinkManager.ts
- common/changes/@microsoft/rush/pgonzal-better-bin-links_2018-04-04-01-49.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/shrinkwrap.yaml
For example, the **api-extractor** project is a command line tool with a `bin/api-extractor` folder.  Whenever it gets installed, the package manager will normally create a `node_modules/.bin/api-extractor.cmd` launcher to invoke this scriptl.
However, suppose that another local project in this repo is symlinked to the **api-extractor** project by Rush.  When `rush link` creates the local **node_modules/.bin** folder, it is currently just a symlink to `common/temp/node_modules/.bin` which only contains launchers for external dependencies.  So the `api-extractor` command-line won't work.
This PR fixes that, by using `@pnpm/link-bins` to create launchers individually for each project.  This also enables a scenario where two different projects depend on different versions of a command-line …
> [rush] Create "node_modules/.bin" launchers for locally linked dependencies

- apps/rush-lib/src/data/VersionMismatchFinder.ts
- apps/rush-lib/src/data/test/VersionMismatchFinder.test.ts
- common/changes/@microsoft/rush/pgonzal-rush-check-skip-peers_2018-04-04-18-51.json
The purpose of "rush check" is mainly to avoid side-by-side duplicates in the node_modules folder.  Wheras peer dependencies are just a compatibility statement that will be satisfied by a regular dependency.  So "rush check" should not be processing the `peerDependencies` field at all.
> NOTE: It might be useful in the future for Rush to help people keep their peer dependency patterns consistent. But on the other hand, different projects within a repo may express different levels of compatibility for their peers. So we shouldn't try to handle this until someone actually requests it and provides a realistic use case.
> [rush] Peer dependencies should be ignored by "rush check"

- apps/rush-lib/src/cli/taskRunner/ProjectTask.ts
- apps/rush-lib/src/cli/taskRunner/test/ProjectTask.test.ts
- common/changes/@microsoft/rush/pgonzal-rush-windows-slashes_2018-04-05-00-42.json
When running a command from the "scripts" block in package.json, if the command contains Unix-style path slashes, the package managers will convert the slashes to backslashes for the Windows OS.  This is a complicated heuristic.  For example, we want to convert `"node_modules/bin/this && ./scripts/that"` to `"node_modules\bin\this && .\scripts\that"` but we don't want to convert the slashes in  `"cmd.exe /c blah"`.  NPM and PNPM use npm-lifecycle for this, but it unfortunately has a dependency on the entire node-gyp kitchen sink. Yarn has a simplified implementation in fix-cmd-win-slashes.js, but it's not exposed as a library.
Since the "&&" and quoting edge cases are mostly deprecated for Rush projects, we will just do something very basic for now.  We can improve it later if someone …
> [rush] Support execution of lifecycle scripts containing Unix slashes on Windows OS

- apps/rush-lib/src/cli/actions/CheckAction.ts
- apps/rush-lib/src/cli/actions/VersionAction.ts
- apps/rush-lib/src/cli/logic/InstallManager.ts
- apps/rush-lib/src/data/VersionMismatchFinder.ts
- apps/rush-lib/src/data/test/VersionMismatchFinder.test.ts
- common/changes/@microsoft/rush/benkaiser-allowedAlternativeVersions_2018-04-09-18-28.json
There are certain cases where we want to exclude specific projects
versions from rush check, for example testing out new versions of
a library in one project whilst keeping the existing older version in
another project. With this option we can now set explicit version
exceptions (allowedAlternativeVersions) without skipping rush check
entirely for a given project.
> Add allowedAlternativeVersions logic

- apps/rush-lib/src/cli/logic/InstallManager.ts
- apps/rush-lib/src/data/test/repo/rush-npm.json
- apps/rush-lib/src/schemas/rush.schema.json
- apps/rush-lib/src/schemas/version-policies.schema.json
- common/changes/@microsoft/rush/pgonzal-fix-semver_2018-04-11-20-08.json
1. The rush.json schema didn't allow prerelease SemVer tags
2. Fix a regression from the (unpublished) "allowedAlternativeVersions" feature work
> Fix a couple issues to support Rush prereleases

- stack/rush-stack/src/cli/BuildAction.ts
The publishing CI definition was providing "--no-color", which wasn't supported by the rush-stack command line.  This PR is a temporary workaround.  (An upcoming PR will make the command-line options dynamic.)
> [rush-stack] Add support for --no-color

- common/changes/@microsoft/gulp-core-build-typescript/fix-typescript-config-log-warning_2018-04-08-20-55.json
- core-build/gulp-core-build-typescript/src/TypeScriptTask.ts
Previously, TypeScriptConfiguration did not correctly log warnings since
the `this.logWarning` function passed by TypeScriptTask lost its binding
to `TypeScriptTask` when passed to TypeScriptConfiguration:
```
TypeError: Cannot read property 'name' of undefined
at logWarning (.../node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:114:45)
at Function.fixupSettings (.../node_modules/@microsoft/gulp-core-build-typescript/lib/TypeScriptConfiguration.js:94:13)
at TypeScriptTask.executeTask (.../node_modules/@microsoft/gulp-core-build-typescript/lib/TypeScriptTask.js:73:59)
at Promise (.../node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:173:31)
at new Promise (<anonymous>)
at TypeScriptTask.execute (.../node_modules/@microsoft/gulp-core-build/lib/tasks/GulpTask.js:165:16 …
```
> Fix logging warnings in TypeScript config

- apps/rush-lib/etc/examples/legacy-command-line.json
- apps/rush-lib/etc/examples/sample-command-line.json
- build-tests/api-extractor-test-01/api-extractor.json
- build-tests/api-extractor-test-02/api-extractor.json
- build-tests/api-extractor-test-04/api-extractor.json
- build-tests/web-library-build-test/config/serve.json
- common/changes/@microsoft/rush/pgonzal-new-json-schema-url_2018-04-20-00-58.json
Our JSON schemas were recently migrated from this server:
https://dev.office.com/json-schemas/
...to here:
https://developer.microsoft.com/json-schemas/
> Update JSON schemas to point to new server

- apps/rush-lib/src/cli/logic/base/BaseShrinkwrapFile.ts
- apps/rush-lib/src/cli/logic/pnpm/PnpmShrinkwrapFile.ts
- apps/rush-lib/src/cli/logic/test/ShrinkwrapFile.test.ts
- apps/rush-lib/src/cli/logic/test/shrinkwrapFile/shrinkwrap.yaml
- common/changes/@microsoft/rush/ddlbrena-pnpmVersionFix_2018-04-20-06-09.json
Per https://github.com/pnpm/spec/blob/master/shrinkwrap/3.4.md Dependency versions can be relative or absolute (e.g., /foo/1.0.0 or registry.node-modules.io/foo/1.0.0).
PnpmShrinkwrapFile.ts cant handle this today. We get "Invalid Version" error due to _checkDependencyVersion in BaseShrinkWrapFile.js not being able to handle this format.
Also extractVersionFromPnpmVersionSpecifier() in PnpmShrinkwrapFile.ts needs to be able to handle this scenario.
> Fix to handle pnpm relative\absolute dependency path version

- apps/rush-lib/src/cli/actions/CustomRushAction.ts
- apps/rush-lib/src/cli/actions/GenerateAction.ts
- apps/rush-lib/src/cli/actions/InstallAction.ts
- apps/rush-lib/src/cli/logic/TaskSelector.ts
- common/changes/@microsoft/rush/pgonzal-rush-command-line-fix_2018-04-21-06-27.json
After we upgraded **ts-command-line**, the **string list** parameters stopped working due to a type change.
> [rush] Fix minor regression for 5.0.0-dev.5

- apps/rush-lib/src/data/RushConfiguration.ts
- common/changes/@microsoft/rush/pgonzal-relax-version-check_2018-04-23-19-40.json
Future versions are now accepted as long as the major/minor parts match.
> [rush] Relax the rush.json version check for rush-lib

- apps/rush-lib/src/cli/actions/PublishAction.ts
- common/changes/@microsoft/rush/qz2017-tarball_update_2018-04-24-01-07.json
Added --release-type to "rush publish" so that different tarball file get created based on release type.
> Create different tarballs based on release type

- apps/rush-lib/src/cli/actions/VersionAction.ts
- apps/rush-lib/src/cli/logic/VersionManager.ts
- apps/rush-lib/src/data/VersionPolicy.ts
- apps/rush-lib/src/data/VersionPolicyConfiguration.ts
- apps/rush-lib/src/data/test/VersionPolicy.test.ts
- common/changes/@microsoft/rush/qz2017-update_version_2018-04-23-21-25.json
- common/reviews/api/rush-lib.api.ts
It can be useful when the policy version needs to be reset to a different value.
> Allow "rush version --ensure-version-policy" to update policy version directly

- apps/rush-lib/src/cli/actions/BaseRushAction.ts
- apps/rush-lib/src/cli/logic/EventHooksManager.ts
- apps/rush-lib/src/cli/logic/InstallManager.ts
- apps/rush-lib/src/cli/logic/PublishUtilities.ts
- apps/rush-lib/src/cli/taskRunner/ProjectTask.ts
- apps/rush-lib/src/cli/test/Cli.test.ts
- apps/rush-lib/src/utilities/Utilities.ts
- common/changes/@microsoft/rush/pgonzal-issue-12356_2018-04-25-20-03.json
This is a fix for Issue #621.  The problem was that NPM sometimes sets environment variables that pollute Rush's process and cause it to behave differently.  This is bad, because one of Rush's goals is for its operations to have deterministic results on any developer PC.
The fixes:
- Refactor the (still somewhat crufty) command spawning utilities to consistently support customizing the environment
- Update Rush's core utilities to scrub the environment before executing commands
- Correctly set the INIT_CWD variable for Rush's own lifecycle events
> [rush] Fix an issue where .npmrc was not honored when Rush was invoked via an NPM lifecycle script

- apps/rush-lib/src/cli/actions/CustomRushAction.ts
- common/changes/@microsoft/rush/qz2017-build_policy_2018-04-26-21-01.json
Added a new parameter "--to-version-policy VERSION_POLICY_NAME". What it is specified with rush rebuild, all projects with the specified version policy will get build
> [Rush] Add ability to build --to a version policy

- apps/rush-lib/src/cli/logic/InstallManager.ts
- common/changes/@microsoft/rush/pgonzal-rush-install-stability_2018-04-28-23-30.json
When using NPM, "rush install" has workarounds for three NPM bugs:
- NPM doesn't detect changes to @rush-temp/*.tgz files
- NPM doesn't clean up @rush-temp projects
- NPM 5 generates a shrinkwrap file that can't be parsed by its own **read-package-tree** library
These workarounds seemed to be causing occasional issues for PNPM.  PNPM doesn't have any of these bugs, so this PR disables the workarounds when using PNPM.
> [rush] When using PNPM, eliminate some troublesome workarounds for NPM bugs

- apps/rush-lib/src/utilities/Utilities.ts
- apps/rush/src/RushVersionSelector.ts
- apps/rush/src/start.ts
- common/changes/@microsoft/rush/pgonzal-rush-locking_2018-05-01-00-24.json
The Rush version selector installs the appropriate version of rush-lib in the global .rush folder, but there was no LockFile.  This could cause two simultaneous installations to overwrite each others' files.
> [rush] Add a LockFile to avoid a race condition while bootstrapping rush-lib

- apps/api-extractor/src/generators/dtsRollup/DtsRollupGenerator.ts
- common/changes/@microsoft/api-extractor/pgonzal-ae-trimming-fix_2018-05-01-18-50.json
Fix a bug where import statements were not being trimmed.  For example:
```
import { Example } from 'example-lib';
```
If `Example` is marked as `@beta` in the other package, then for a public release this import statement should be excluded.
> [api-extractor] Fix an issue where import statements were not being trimmed

- apps/rush-lib/src/cli/logic/PublishUtilities.ts
- apps/rush-lib/src/utilities/Utilities.ts
- common/changes/@microsoft/rush/qz2017-publish_env_2018-05-01-23-53.json
Rush publish normally needs a special set of npm configuration values. If we do not want to add all those variables as Rush parameters yet, we need "Rush publish" to be able to use the process environment variables.
> Respect process environment when executing "Rush publish"

- apps/rush-lib/src/cli/logic/InstallManager.ts
- common/changes/@microsoft/rush/pgonzal-fix-install-symlink-issue_2018-05-04-02-19.json
If the symlink was a broken link (e.g. because the person had deleted their `~/.rush` folder), then Rush failed to create it again.  The person would have to manually delete it.
> [rush] Fix an issue creating the "common/local-rush" symlink

- apps/rush-lib/src/cli/logic/InstallManager.ts
- apps/rush-lib/src/data/EnvironmentConfiguration.ts
- apps/rush-lib/src/data/RushConfiguration.ts
- apps/rush-lib/src/index.ts
- apps/rush-lib/src/utilities/Utilities.ts
- apps/rush/src/MinimalRushConfiguration.ts
- apps/rush/src/RushVersionSelector.ts
- apps/rush/src/start.ts
- common/changes/@microsoft/rush/pgonzal-rush-preview-variable_2018-05-11-23-39.json
- common/changes/@microsoft/rush/pgonzal-rush-preview-variable_2018-05-12-00-20.json
- common/reviews/api/rush-lib.api.ts
To test out a new Rush version, developers can now set an environment variable RUSH_PREVIEW_VERSION.
Rush will display a warning banner like this:
```
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
WARNING! THE "RUSH_PREVIEW_VERSION" ENVIRONMENT VARIABLE IS SET.
You are previewing Rush version:        5.0.0-dev.16
The rush.json configuration asks for:   5.0.0-dev.17
To restore the normal behavior, unset the RUSH_PREVIEW_VERSION
environment variable.
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
```
> [rush] Add support for RUSH_PREVIEW_VERSION environment variable

- apps/api-documenter/src/yaml/YamlDocumenter.ts
- apps/api-extractor/src/aedoc/ApiDocumentation.ts
- apps/api-extractor/src/api/ApiItem.ts
- apps/api-extractor/src/api/api-json.schema.json
- apps/api-extractor/src/generators/ApiFileGenerator.ts
- apps/api-extractor/src/generators/ApiJsonGenerator.ts
- common/changes/@microsoft/api-documenter/pgonzal-aedoc-decorators_2018-05-14-22-55.json
- common/changes/@microsoft/api-extractor/pgonzal-aedoc-decorators_2018-05-14-22-54.json
- common/reviews/api/api-extractor.api.ts
We are replacing the @sealed/@virtual/@override with AEDoc tags, because decorators don't show up in the *.d.ts files that customers see.
> [api-extractor] Add AEDoc tags for @sealed/@virtual/@override

- apps/rush/CHANGELOG.json
- apps/rush/CHANGELOG.md
Cherry-pick the change log from rush 4.3.3 (PR https://github.com/Microsoft/web-build-tools/pull/670) back into the master branch
> Conflicts:
>	common/changes/@microsoft/rush/pgonzal-fix-install-symlink-issue_2018-05-04-02-19.json
> Merge change log for rush 4.3.3

- apps/rush-lib/src/Rush.ts
- apps/rush-lib/src/RushX.ts
- apps/rush-lib/src/index.ts
- apps/rush-lib/src/utilities/Utilities.ts
- apps/rush/bin/rushx
- apps/rush/src/RushCommandSelector.ts
- apps/rush/src/RushVersionSelector.ts
- apps/rush/src/start.ts
- common/changes/@microsoft/node-core-library/pgonzal-rushx_2018-06-06-19-20.json
- common/changes/@microsoft/rush/pgonzal-rushx_2018-06-06-19-20.json
- common/reviews/api/node-core-library.api.ts
- common/reviews/api/rush-lib.api.ts
- libraries/node-core-library/src/Text.ts
- libraries/node-core-library/src/test/Text.test.ts
Rush 5 will distinguish 3 types of commands:
1. "global" commands that execute once for the whole repo
2. "bulk" commands that are executed separately in each project folder
3. "project" commands, that only affect a single project
This PR addresses #3  and our approach is a separate command line "rushx".
> [rush] Add "rushx" binary for project-specific commands

- common/changes/@microsoft/gulp-core-build-serve/ext-gulp-core-build-serve_2018-06-12-08-10.json
- core-build/gulp-core-build-serve/src/ServeTask.ts
Pass the `hostname` from `serve.json` to `gulpConnect.server()`.
Starting from v5.1.0, gulp-connect uses the `host` parameter to instantiate the server. If the `host` is not specified, it instantiate the serve on `localhost`. When used in a Docker container, localhost is not exposed outside the container. This fix makes it possible to use the `hostname` specified in `serve.json` with `gulpConnect.server()`.
> Pass the hostname from serve.json to gulpConnect.server()

- apps/rush-lib/src/logic/SetupChecks.ts
- common/changes/@microsoft/rush/pgonzal-phantom-folder-check_2018-06-13-02-13.json
This spring we've had several investigations of strange build errors that turned out to be NodeJS finding the wrong library in a stray `node_modules` folder.  Normally `require()` stops at the first match it finds, but for `@types` the TypeScript compiler seems to keep looking in other folders.
With this PR, Rush now warns about phantom `node_modules` folders.  For now the warning is purely informational and does not fail the operation.  Later once the **install-run.js** scenario is proven out, we will make it more strict.
> [rush] Warn about phantom node_modules folders

- apps/rush-lib/src/logic/InstallManager.ts
- common/changes/@microsoft/rush/pgonzal-fix-rush-warning_2018-06-13-18-40.json
- common/config/rush/shrinkwrap.yaml
- rush.json
If a dependency was missing, "rush install" would print two warnings...
```
The NPM shrinkwrap file does not provide "react" (16.4.1) required by the preferred versions from common-versions.json
The NPM shrinkwrap file is missing "react" (16.4.1) required by "@microsoft/api-documenter".
Finished creating temporary modules (0.15 seconds)
```
...when only the second warning was correct.  This occurred because the implicit preferred version was being checked and reported the same way as an explicit setting in **common-versions.json**.
> [rush] Fix a regression where "rush install" printed an incorrect warning

- apps/api-extractor/src/ast/AstFunction.ts
- apps/api-extractor/src/ast/AstMember.ts
- apps/api-extractor/src/ast/AstMethod.ts
- apps/api-extractor/src/ast/AstModule.ts
- apps/api-extractor/src/ast/AstParameter.ts
- apps/api-extractor/src/ast/AstProperty.ts
- apps/api-extractor/src/ast/AstStructuredType.ts
- apps/api-extractor/src/utils/PrettyPrinter.ts
- common/changes/@microsoft/api-extractor/pgonzal-ae-nested-namespaces_2018-06-19-02-49.json
- common/changes/@microsoft/api-extractor/pgonzal-ae-nested-namespaces_2018-06-19-03-08.json
When `namespaceSupport=permissive` is specified in the configuration, allow arbitrary nesting of namespaces.
> [api-extractor] Allow nested namespaces in permissive mode

- common/changes/@microsoft/gulp-core-build-typescript/GolaWaya_2018-06-21-20-19.json
- core-build/gulp-core-build-typescript/src/TypeScriptConfiguration.ts
Changed getGulpTypescriptOptions to prevent accidental mutation of compilerOptions object in immutable this._projectTsConfig resulting in an error in tslint when executing tslint and typescript tasks multiple times in a row within the same parent task (such as in a watch). #712
> Fix mutability on this._projectTsConfig

- libraries/rushell/src/ParseError.ts
- libraries/rushell/src/TextRange.ts
- libraries/rushell/src/Tokenizer.ts
- libraries/rushell/src/test/Tokenizer.test.ts
- libraries/rushell/src/test/__snapshots__/Tokenizer.test.ts.snap
This is an initial sketch of a lexical analyzer for POSIX shell commands. It supports these tokens:
- whitespace
- newlines
- plain text words with escapes
- the "&&" operator
- double-quoted strings with escapes
- dollar variables (e.g. "`$PATH`")
> [rushell] Initial commit of shell tokenizer

- apps/api-documenter/src/yaml/OfficeYamlDocumenter.ts
- common/changes/@microsoft/api-documenter/AlexJ-OfficeMarkdown_2018-06-22-19-16.json
This is a short-term fix to have the listed markdown functionality passed through the AD to OPS.
> API Documenter (Office Extension) - Unencoding code, bold, and italic markdown

- apps/api-documenter/src/yaml/OfficeYamlDocumenter.ts
- common/changes/@microsoft/api-documenter/AlexJ-AllowFunctionArrow_2018-06-25-23-28.json
In code sections, function arrows are displayed like this:
`getCallbackTokenAsync(callback: (result: AsyncResult) =&gt; void): void;`
> [API Documenter] - OfficeYamlDocumenter: Replacing =&lt; with => in remarks sections 

- apps/api-documenter/src/cli/BaseAction.ts
- apps/api-documenter/src/utils/DocItemSet.ts
- apps/api-documenter/src/yaml/YamlDocumenter.ts
- common/changes/@microsoft/api-documenter/pgonzal-api-documenter-links_2018-06-25-22-47.json
Ideally we'd like every type reference (e.g. parameter type, return type, property type) to automatically hyperlink to the corresponding documentation item.  However, today the DocFX YAML schema only supports hyperlinks for simple types (e.g. `MyClass` but not `Promise<MyClass>` or `MyClass | undefined`).
This PR enables support for this limited form of hyperlinking.  When the schema is improved in the future, we will replace this workaround with a full implementation.
> [api-documenter] Add limited support for type reference hyperlinks

- build-tests/web-library-build-test/config/serve.json
- common/changes/@microsoft/gulp-core-build-serve/pgonzal-upgrade-insecure-packages_2018-08-07-20-56.json
- common/changes/@microsoft/gulp-core-build-webpack/pgonzal-upgrade-insecure-packages_2018-08-07-20-56.json
- common/changes/@microsoft/gulp-core-build/pgonzal-upgrade-insecure-packages_2018-08-07-20-56.json
- common/config/rush/common-versions.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/shrinkwrap.yaml
- core-build/gulp-core-build-serve/package.json
- core-build/gulp-core-build-webpack/package.json
- core-build/gulp-core-build/package.json
This PR removes these package versions from our shrinkwrap.yaml file:
- growl 1.9.2
- open 0.0.5
> [gulp-core-build] Eliminate packages with security warnings

- apps/rush-lib/src/cli/actions/BaseInstallAction.ts
- apps/rush-lib/src/cli/actions/InstallAction.ts
- apps/rush-lib/src/cli/actions/UpdateAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/logic/InstallManager.ts
- common/changes/@microsoft/rush/pgonzal-rush-network-concurrency_2018-08-10-18-17.json
People have occasionally been reporting "integrity checksum failed" errors during PNPM install, which result from an ECONNRESET error that seems to be related to an issue with the network connection pool.  (See https://github.com/pnpm/pnpm/issues/1230 for details.)
We found that specifying PNPM's `--network-concurrency 1` option eliminates the error (but increases install times).  This PR exposes this switch to `rush install` so we can use it as a workaround.  We will experiment with different values and perhaps propose applying a default maximum for the PNPM tool.
> [rush] Add a --network-concurrency option for troubleshooting network issues

- apps/rush-lib/src/api/CommonVersionsConfiguration.ts
- common/changes/@microsoft/rush/nickpape-add-missing-api_2018-08-21-22-25.json
- common/reviews/api/rush-lib.api.ts
This is needed for some internal tooling which commits this file to Git, and therefore needs to know the filepath.
> Add an api on CommonVersionsConfiguration to get the filepath

- apps/rush-lib/src/api/ChangeFile.ts
- apps/rush-lib/src/api/CommonVersionsConfiguration.ts
- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/logic/PackageChangeAnalyzer.ts
- apps/rush-lib/src/logic/RushConstants.ts
- common/changes/@microsoft/gulp-core-build-sass/pgonzal-filepath_2018-08-22-22-46.json
- common/changes/@microsoft/gulp-core-build-typescript/pgonzal-filepath_2018-08-22-22-46.json
- common/changes/@microsoft/gulp-core-build/pgonzal-filepath_2018-08-22-22-46.json
- common/changes/@microsoft/rush/pgonzal-filepath_2018-08-22-22-46.json
- common/reviews/api/rush-lib.api.ts
- core-build/gulp-core-build-sass/src/SassTask.ts
- core-build/gulp-core-build-typescript/src/TSLintTask.ts
- core-build/gulp-core-build/src/utilities/FileDeletionUtility.ts
"Filename" is a common English word that appears in dictionaries.  "Filepath" is not.
Thus `fileName` and `filename` are both acceptable casings, but a file path must always be capitalized as `filePath`.
> [rush] Fix capitalization of CommonVersionsConfiguration.filePath

- common/changes/@microsoft/api-documenter/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/api-extractor/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/gulp-core-build-karma/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/gulp-core-build-mocha/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/gulp-core-build-sass/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/gulp-core-build-serve/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/gulp-core-build-typescript/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/gulp-core-build-webpack/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/gulp-core-build/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/load-themed-styles/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/loader-load-themed-styles/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/loader-raw-script/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/loader-set-webpack-public-path/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/node-core-library/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/node-library-build/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/package-deps-hash/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/resolve-chunk-plugin/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/rush/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/set-webpack-public-path-plugin/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/stream-collator/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/ts-command-line/pgonzal-republish-bad-packages_2018-08-23-18-07.json
- common/changes/@microsoft/web-library-build/pgonzal-republish-bad-packages_2018-08-23-18-07.json
Due to a misconfigured CI build definition, we accidentally published empty NPM packages for some projects in this repo.
See https://github.com/Microsoft/web-build-tools/issues/782 for details.
@qz2017
> Republish packages to resolve GitHub issue #782

- apps/rush-lib/src/cli/actions/PublishAction.ts
- apps/rush-lib/src/logic/InstallManager.ts
- apps/rush-lib/src/logic/StandardScriptUpdater.ts
- apps/rush-lib/src/logic/base/BaseLinkManager.ts
- apps/rush-lib/src/logic/npm/NpmLinkManager.ts
- apps/rush-lib/src/utilities/AsyncRecycler.ts
- common/changes/@microsoft/gulp-core-build/pgonzal-symlink-regression_2018-08-29-03-52.json
- common/changes/@microsoft/node-core-library/pgonzal-symlink-regression_2018-08-29-03-52.json
- common/changes/@microsoft/rush/pgonzal-symlink-regression_2018-08-29-03-52.json
- common/reviews/api/node-core-library.api.ts
- core-build/gulp-core-build/src/tasks/GulpTask.ts
- core-build/gulp-core-build/src/tasks/JestTask.ts
- libraries/node-core-library/src/Executable.ts
- libraries/node-core-library/src/FileDiffTest.ts
- libraries/node-core-library/src/FileSystem.ts
- libraries/node-core-library/src/PosixModeBits.ts
- libraries/node-core-library/src/Text.ts
- libraries/node-core-library/src/index.ts
- libraries/node-core-library/src/test/Executable.test.ts
- libraries/node-core-library/src/test/FileSystem.test.ts
This includes the fix for issue https://github.com/Microsoft/web-build-tools/issues/788, which was a Rush regression where the source/target parameters were reversed for `fsx.symlinkSync(linkSource, linkTarget, 'file');`.
**The breaking change:** For all APIs with two path parameters, require explicit naming of the source/target (via an `options` object).
This is particularly tricky when creating a symlink, since the thing we're creating was called the "source" (and the "target" is what the link points to).  We clarified that as follows:
```ts
/**
* The options for FileSystem.createSymbolicLinkJunction(), createSymbolicLinkFile(), createSymbolicLinkFolder(),
* and createHardLink().
*
* @public
*/
export interface IFileSystemCreateLinkOptions {
/**
* The path where the new symlink link …
```
> [node-core-library] Improve FileSystem API to eliminate confusion about "source" and "target" parameters

- common/changes/@microsoft/load-themed-styles/ianc-fixing-lts_2018-08-29-20-18.json
- common/config/rush/common-versions.json
- libraries/load-themed-styles/package.json
- libraries/load-themed-styles/tsconfig.json
This is a temporary fix for issue https://github.com/Microsoft/web-build-tools/issues/796
Due to a tooling change, the legacy "lib-amd/" folder was no longer getting built.
> Downgrading the version of node-library-build in load-themed-styles to fix the lib-amd issue.

- apps/rush-lib/src/logic/InstallManager.ts
- common/changes/@microsoft/rush/pgonzal-prefer-frozen-shrinkwrap_2018-08-31-20-00.json
Based on the discussion in https://github.com/pnpm/pnpm/issues/1342 , we are adding `--prefer-frozen-shrinkwrap false` to the command line for `pnpm install`.
> [rush] Add workaround for issue where shrinkwrap.yaml was sometimes out of sync

- apps/rush-lib/src/api/ChangeManagement.ts
- apps/rush-lib/src/cli/actions/PublishAction.ts
- apps/rush-lib/src/logic/Git.ts
- apps/rush-lib/src/logic/PackageChangeAnalyzer.ts
- apps/rush-lib/src/logic/policy/GitEmailPolicy.ts
- common/changes/@microsoft/node-core-library/pgonzal-relax-rush-email-policy_2018-08-31-22-35.json
- common/changes/@microsoft/rush/pgonzal-relax-rush-email-policy_2018-08-31-22-35.json
- libraries/node-core-library/src/Executable.ts
To simplify onboarding for new developers in a repo, Rush performs various checks to ensure that the Git email address is configured.  However @jbcpollak recently reported that his CI build was failing, because it does not have a Git email configured.  (Presumably the build definition does not need a command such as `rush publish` that would perform Git operations.)
We are relaxing the check as follows:
Require an email and validate it **IF**:
- Git is installed, **AND**
- rush.json is under a Git working folder, **AND**
- At least one email policy regex is defined in rush.json
Or, merely require a correctly formatted email address **IF**:
- Git is installed, **AND**
- rush.json is under a Git working folder, **AND**
- A nonempty value has been configured for the Git email address …
> [rush] Relax the email policy checking

- apps/rush-lib/package.json
- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/cli/actions/InstallAction.ts
- apps/rush-lib/src/cli/actions/UpdateAction.ts
- apps/rush-lib/src/logic/InstallManager.ts
- apps/rush-lib/src/logic/LinkManagerFactory.ts
- apps/rush-lib/src/logic/RushConstants.ts
- apps/rush-lib/src/logic/ShrinkwrapFileFactory.ts
- apps/rush-lib/src/logic/base/BaseShrinkwrapFile.ts
- apps/rush-lib/src/logic/npm/NpmShrinkwrapFile.ts
- apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
- apps/rush-lib/src/logic/yarn/YarnShrinkwrapFile.ts
- apps/rush-lib/src/schemas/rush.schema.json
- apps/rush-lib/typings/tsd.d.ts
- apps/rush-lib/typings/yarnpkg-lockfile/yarnpkg-lockfile.d.ts
- common/changes/@microsoft/node-core-library/pgonzal-yarn-for-rush_2018-09-07-21-04.json
- common/changes/@microsoft/rush/pgonzal-yarn-for-rush_2018-09-07-01-35.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/shrinkwrap.yaml
- common/reviews/api/rush-lib.api.ts
- libraries/node-core-library/src/PackageName.ts
This PR allows [Yarn](https://yarnpkg.com/) to be used in a Rush repo.  (Hurray!!!)
The symlinking model is the same as Rush's approach for NPM.
> [rush] Add support for the Yarn package manager

- apps/api-extractor/src/cli/RunAction.ts
- apps/api-extractor/src/extractor/Extractor.ts
- common/changes/@microsoft/api-extractor/ianc-api-extractor-swap-ts-libs_2018-09-20-23-42.json
- common/changes/@microsoft/gulp-core-build-typescript/ianc-api-extractor-swap-ts-libs_2018-09-20-23-42.json
- common/reviews/api/api-extractor.api.ts
- core-build/gulp-core-build-typescript/src/ApiExtractorTask.ts
- core-build/gulp-core-build-typescript/src/BaseCmdTask.ts
This PR introduces an option to api-extractor to specify a different version of the TypeScript compiler to get lib typings from.
> [api-extractor] Introduce --typescript-lib-package option.

- apps/api-extractor/src/ExtractorContext.ts
- apps/api-extractor/src/extractor/Extractor.ts
- apps/api-extractor/src/utils/TypeScriptMessageFormatter.ts
- apps/api-extractor/src/utils/TypeScriptMessageSerializer.ts
- common/changes/@microsoft/api-extractor/ianc-fixing-api-extractor-error-messages_2018-09-21-00-31.json
This PR fixes an issue where TypeScript errors are often logged as "[Object object]" instead of the actual error message.
> [api-extractor] Fixing incorrect TypeScript error message printing.

- apps/api-extractor/src/cli/RunAction.ts
- apps/api-extractor/src/extractor/Extractor.ts
- common/changes/@microsoft/api-extractor/ianc-adding-skip-lib-check_2018-09-26-08-18.json
- common/changes/@microsoft/gulp-core-build-typescript/ianc-adding-skip-lib-check_2018-09-26-08-18.json
- common/reviews/api/api-extractor.api.ts
- core-build/gulp-core-build-typescript/src/ApiExtractorTask.ts
- core-build/gulp-core-build-typescript/src/schemas/api-extractor.schema.json
This option causes the typechecker to be invoked with the --skipLibCheck option. This option is not recommended and may cause api-extractor to produce incomplete or incorrect declarations, but may be required when dependencies contain declarations that are incompatible with newer versions of TypeScript. If this option is used, it is strongly recommended that broken dependencies be fixed or upgraded.
> [api-extractor] Introducing --skip-lib-check option to api-extractor.

- apps/rush-lib/assets/rush-init/rush.json
- common/changes/@microsoft/rush/pgonzal-fix-rush-init-typo_2018-09-28-21-33.json
We said that projectFolderMinDepth defaults to 2, when it should be 1
> [rush] Fix an incorrect default in the "rush init" template

- apps/rush-lib/src/api/PackageJsonEditor.ts
- apps/rush-lib/src/logic/InstallManager.ts
- apps/rush-lib/src/logic/npm/NpmLinkManager.ts
- apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts
- common/changes/@microsoft/rush/nickpape-fix-rush-update-bug_2018-10-02-23-05.json
- common/config/rush/version-policies.json
- common/reviews/api/rush-lib.api.ts
`rush add` modifies the new `PackageJsonEditor` API, whereas `rush update` was using the deprecated `packageJson` API. So, `rush update` was running using a package.json that wasn't modified, therefore it didn't do anything.
> Rush: fix an issue where after running "rush add", "rush update" was not detecting changes

- .gitignore
When we cleaned up .gitignore we were a little overzealous
> Add missing patterns to .gitignore

- apps/rush-lib/src/api/VersionMismatchFinder.ts
- common/changes/@microsoft/rush/nickpape-check-cyclic_2018-10-05-00-48.json
Right now we ignore cyclic dependencies, but this can be bad.
We want to make sure they are consistent.
> Ensure cyclic dependencies are consistent as well

- common/changes/@microsoft/gulp-core-build-sass/sass-extension-support_2018-09-29-03-21.json
- core-build/gulp-core-build-sass/README.md
- core-build/gulp-core-build-sass/src/SassTask.ts
- core-build/gulp-core-build-sass/src/sass.schema.json
See https://github.com/SharePoint/sp-dev-docs/issues/2637.
> [gulp-core-build-sass] Better support for indented syntax and, likewise, `.sass` extension

- rush.json
@nickpape-msft  FYI your PR https://github.com/Microsoft/web-build-tools/pull/854 changed the `nodeSupportedVersionRange` which was breaking our CI jobs.  I'm temporarily reverting that line.
Since Node 10 is LTS now, next week we'll follow up with a better fix.
> Temporarily restore the old nodeSupportedVersionRange in rush.json

- apps/rush-lib/src/logic/base/BaseLinkManager.ts
- common/changes/@microsoft/rush/pgonzal-fix-symlink-regression_2018-10-08-23-06.json
https://github.com/Microsoft/web-build-tools/pull/805 introduced a regression for NPM/Yarn package managers, which rely on hard links
> [rush] Fix "rush link" regression when using NPM/Yarn package managers

- apps/rush-lib/src/cli/actions/PublishAction.ts
- common/changes/@microsoft/rush/pgonzal-yarn-publish_2018-10-17-03-04.json
The command line for `yarn publish` is incompatible with the options used by PNPM and NPM
> [rush] Fix an issue where "rush publish" didn't work with Yarn

- apps/rush-lib/assets/rush-init/common/config/rush/command-line.json
- apps/rush-lib/src/api/CommandLineJson.ts
- apps/rush-lib/src/cli/RushCommandLineParser.ts
- apps/rush-lib/src/cli/actions/BaseRushAction.ts
- apps/rush-lib/src/schemas/command-line.schema.json
- common/changes/@microsoft/rush/ssrush_2018-10-19-16-25.json
This fixes #887 by allowing commands opt into being allowed to launch other rush commands.
> Expose safeForSimultaneousRushProcesses to custom commands

- apps/rush-lib/src/api/PackageJsonEditor.ts
- apps/rush-lib/src/logic/InstallManager.ts
- common/changes/@microsoft/node-core-library/pgonzal-yarn-bug_2018-10-25-07-31.json
- common/changes/@microsoft/rush/pgonzal-yarn-bug_2018-10-25-03-42.json
- common/changes/@microsoft/rush/pgonzal-yarn-bug_2018-10-25-07-31.json
- common/reviews/api/node-core-library.api.ts
- common/reviews/api/rush-lib.api.ts
- libraries/node-core-library/src/Sort.ts
- libraries/node-core-library/src/index.ts
A package.json can specify a peer dependency (to indicate a general supported range) and also a dev dependency (to request a specific version for development).  Consider **react** and **react-dom** in this example:
```js
"dependencies": {
"prop-types": "^15.5.8"
},
"devDependencies": {
"@types/prop-types": "15.5.1",
"@types/react": "16.4.14",
"@types/react-dom": "16.0.7",
"react": "16.3.1",
"react-dom": "16.3.1"
},
"peerDependencies": {
"react": "^16.0.0",
"react-dom": "^16.0.0"
},
```
In this situation, when using Yarn, `rush install` would complain that the shrinkwrap file did not satisfy the dependencies, even immediately after running `rush update`. 
As part of this PR, I also noticed the the `@rush-temp` projects had a nondeterministic ordering of dependencies in their …
> [rush] Fix issue where "rush install" sometimes would incorrectly ask for "rush update" when using Yarn

- apps/api-extractor/src/extractor/Extractor.ts
- common/changes/@microsoft/api-extractor/sunilsurana-issue912_2018-10-30-05-58.json
- common/reviews/api/api-extractor.api.ts
**PR changes**
Added a public static method in ApiExtractor class which will take the apiextractor json file path. It will load and validate and create apiextractor object and process it.
**Issue description**
If someone is integrating api extractor using library the client has to supply the config object. There was no support of passing the apiextractor config json file.
Fixes https://github.com/Microsoft/web-build-tools/issues/912
> [api-extractor] Add wrapper method to read config file for processing

- apps/api-extractor/src/generators/dtsRollup/AstSymbolTable.ts
- apps/api-extractor/src/generators/dtsRollup/DtsRollupGenerator.ts
- build-tests/api-extractor-test-01/dist/beta/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-01/dist/internal/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-01/dist/public/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-01/etc/api-extractor-test-01.api.ts
- build-tests/api-extractor-test-01/src/EcmaScriptSymbols.ts
- build-tests/api-extractor-test-01/src/index.ts
- build-tests/api-extractor-test-04/dist/beta/api-extractor-test-04.d.ts
- build-tests/api-extractor-test-04/dist/internal/api-extractor-test-04.d.ts
- build-tests/api-extractor-test-04/dist/public/api-extractor-test-04.d.ts
- common/changes/@microsoft/api-extractor/pgonzal-ae-symbol-rollups_2018-11-01-18-33.json
Example input:
```ts
const unexportedCustomSymbol: unique symbol = Symbol('unexportedCustomSymbol');
// Exported by this file, but not exported from index.ts
export const locallyExportedCustomSymbol: unique symbol = Symbol('locallyExportedCustomSymbol');
/** @public */
export const fullyExportedCustomSymbol: unique symbol = Symbol('fullyExportedCustomSymbol');
/** @public */
export class ClassWithSymbols {
public readonly [unexportedCustomSymbol]: number = 123;
public get [locallyExportedCustomSymbol](): string {
return 'hello';
}
public [fullyExportedCustomSymbol](): void {
}
}
```
Before this PR:
-  `fullyExportedCustomSymbol` was included in the .d.ts rollup, but was missing the `export` keyword
- The `unexportedCustomSymbol` and `locallyExportedCustomSymbol` were not included at all, …
> [api-extractor] Fix an issue where EcmaScript symbols weren't being emitted in .d.ts rollups

- apps/rush-lib/src/cli/RushCommandLineParser.ts
- apps/rush-lib/src/cli/scriptActions/BaseScriptAction.ts
- apps/rush-lib/src/scripts/install-run-rush.ts
- apps/rush-lib/src/scripts/install-run.ts
- apps/rush/src/MinimalRushConfiguration.ts
- common/changes/@microsoft/gulp-core-build/nickpape-turn-off-lint-rule_2018-11-06-23-42.json
- common/changes/@microsoft/rush-stack-compiler/nickpape-turn-off-lint-rule_2018-11-05-23-34.json
- common/changes/@microsoft/rush/nickpape-turn-off-lint-rule_2018-11-06-23-42.json
- common/changes/@microsoft/stream-collator/nickpape-turn-off-lint-rule_2018-11-06-23-42.json
- core-build/gulp-core-build/src/GulpProxy.ts
- core-build/gulp-core-build/src/utilities/test/FileDeletionUtility.test.ts
- libraries/stream-collator/src/test/Interleaver.test.ts
- stack/rush-stack-compiler/includes/tsconfig-base.json
- stack/rush-stack-compiler/includes/tslint.json
It is causing issues in SP-Client:
Error - [tslint] no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
> Remove deprecated lint rule

- apps/rush-lib/src/api/RushGlobalFolder.ts
- apps/rush-lib/src/logic/InstallManager.ts
- apps/rush-lib/src/logic/PurgeManager.ts
- build-tests/api-extractor-test-01/package.json
- build-tests/api-extractor-test-02/package.json
- build-tests/api-extractor-test-03/package.json
- build-tests/api-extractor-test-04/package.json
- build-tests/api-extractor-test-05/package.json
- common/changes/@microsoft/node-core-library/pgonzal-prepare-rush-5.5.1_2018-11-07-18-27.json
- common/changes/@microsoft/rush/ianc-node-specific-rush-install_2018-11-06-19-58.json
- common/changes/@microsoft/rush/pgonzal-prepare-rush-5.5.1_2018-11-07-18-27.json
- common/config/rush/shrinkwrap.yaml
- common/config/rush/version-policies.json
- libraries/node-core-library/package.json
Fix a few issues found during testing.
Note that we are skipping 5.5.0, because that release was published incorrectly and later unpublished
> [rush] Prepare to publish Rush 5.5.1

- apps/api-extractor/src/generators/dtsRollup/DtsRollupGenerator.ts
- build-tests/api-extractor-test-01/dist/beta/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-01/dist/internal/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-01/dist/public/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-01/etc/api-extractor-test-01.api.ts
- build-tests/api-extractor-test-01/src/index.ts
- build-tests/api-extractor-test-01/src/variableDeclarations.ts
- build-tests/api-extractor-test-04/dist/public/api-extractor-test-04.d.ts
- common/changes/@microsoft/api-extractor/pgonzal-ae-variable-declaraitons_2018-11-15-09-01.json
- common/config/rush/shrinkwrap.yaml
> [api-extractor] Fix an issue where .d.ts trimming did not work for exported variable declaration

- apps/api-extractor/package.json
- apps/api-extractor/src/generators/dtsRollup/DtsRollupGenerator.ts
- build-tests/api-extractor-test-01/dist/beta/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-01/dist/internal/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-01/dist/public/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-01/etc/api-extractor-test-01.api.ts
- build-tests/api-extractor-test-01/package.json
- build-tests/api-extractor-test-01/src/ReferenceLibDirective.ts
- build-tests/api-extractor-test-01/src/index.ts
- common/changes/@microsoft/api-extractor/pgonzal-ae-reference-lib_2018-11-16-20-09.json
- common/changes/@microsoft/node-core-library/pgonzal-ae-reference-lib_2018-11-16-20-39.json
- common/config/rush/common-versions.json
- common/config/rush/shrinkwrap.yaml
- common/reviews/api/node-core-library.api.ts
- libraries/node-core-library/src/Sort.ts
Fixes https://github.com/Microsoft/web-build-tools/issues/922
@southpolesteve
> [api-extractor] Emit /// <reference lib="" /> in rolled up .d.ts

- apps/api-documenter/src/yaml/YamlDocumenter.ts
- common/changes/@microsoft/api-documenter/addUIDsToExtends_2018-11-27-23-57.json
A couple changes to **YamlDocumenter**.
`_getTypeNameWithDot` should break if `hierarchy.length` is less than 2. 
I also added links to uids in the YAML file generation for extends and implements blocks.
> [api-documenter] fix _getTypeNameWithDot and link implements and extends to uid

- apps/api-documenter/src/start.ts
- apps/api-extractor/.vscode/launch.json
- apps/api-extractor/src/ExtractorContext.ts
- apps/api-extractor/src/extractor/Extractor.ts
- apps/api-extractor/src/generators/dtsRollup/AstSymbolTable.ts
- apps/api-extractor/src/generators/dtsRollup/DtsRollupGenerator.ts
- apps/api-extractor/src/generators/dtsRollup/PackageMetadataManager.ts
- apps/api-extractor/src/start.ts
- apps/rush-lib/src/api/Rush.ts
- apps/rush/src/start.ts
- common/changes/@microsoft/api-documenter/pgonzal-tsdoc-metadata_2018-11-27-06-51.json
- common/changes/@microsoft/api-extractor/pgonzal-tsdoc-metadata_2018-11-27-06-51.json
- common/changes/@microsoft/node-core-library/pgonzal-tsdoc-metadata_2018-11-27-06-51.json
- common/changes/@microsoft/rush-stack/pgonzal-tsdoc-metadata_2018-11-27-06-51.json
- common/changes/@microsoft/rush/pgonzal-tsdoc-metadata_2018-11-27-06-51.json
- common/reviews/api/api-extractor.api.ts
- common/reviews/api/node-core-library.api.ts
- libraries/node-core-library/src/PackageJsonLookup.ts
- libraries/node-core-library/src/test/PackageJsonLookup.test.ts
- stack/rush-stack/src/start.ts
This is based on the discussion in https://github.com/Microsoft/tsdoc/issues/7 .
Instead of the `tsdocFlavor` field in **package.json**:
```json
{
"name": "widget-lib",
"version": "1.0.0",
"main": "lib/index.d.ts",
"typings": "lib/index.js",
"tsdoc": {
"tsdocFlavor": "AEDoc"
}
}
```
...we now recognize that an external package is TSDoc-compatible by looking for a file **dist/tsdoc-metadata.json** with contents like this:
```ts
{
"tsdocVersion": "0.12",
"toolPackages": [
{
"packageName": "@microsoft/api-extractor",
"packageVersion": "7.0.0"
}
]
}
```
This is a prototype until an official implementation is provided by the **\@microsoft/tsdoc** library.
> [api-extractor] Replace the old "tsdocFlavor" field with a dist/api-metadata.json output

- apps/api-extractor/src/generators/DtsRollupGenerator.ts
- build-tests/api-extractor-test-01/dist/beta/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-01/dist/internal/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-01/dist/public/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-02/dist/beta/api-extractor-test-02.d.ts
- build-tests/api-extractor-test-02/dist/internal/api-extractor-test-02.d.ts
- build-tests/api-extractor-test-02/dist/public/api-extractor-test-02.d.ts
- build-tests/api-extractor-test-05/etc/api-extractor-test-05.api.json
- common/changes/@microsoft/api-extractor/pgonzal-ae-accidental-imports_2018-12-19-21-14.json
When creating .d.ts rollup files, sometimes API Extractor needs to include declarations that the developer forgot to export from the entry point.  (For example, a class that is returned by a function call.) The `export` keyword is omitted, since these declarations cannot be imported from the entry point.  However, due to a quirk of the TypeScript compiler, the declarations can still be imported, unless a special `export { }` directive is included in the .d.ts file.
> [api-extractor] Emit "export { }" directive in .d.ts rollup files to prevent incorrect imports

- apps/rush-lib/src/cli/actions/ChangeAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- common/changes/@microsoft/rush/keco-fix-typos_2019-01-11-00-09.json
Fixes a typo of "timestamp" in rush's change action manual page and updates the relevant snapshot file.
Related PR: https://github.com/Microsoft/rushjs.io-website/pull/27
> Fix typo of "timestamp" in rush change action manual page

- apps/api-documenter/src/markdown/MarkdownEmitter.ts
- common/changes/@microsoft/api-documenter/supportInlineTag_2019-01-14-17-55.json
This change prevents the markdown emitter from throwing an error for inline tags when writing nodes.
> api-documenter: handle inline tags

- apps/api-extractor/src/analyzer/AstSymbolTable.ts
- apps/api-extractor/src/analyzer/ExportAnalyzer.ts
- apps/api-extractor/src/analyzer/TypeScriptHelpers.ts
- apps/api-extractor/src/analyzer/TypeScriptInternals.ts
- build-tests/api-extractor-scenarios/build-config.json
- build-tests/api-extractor-scenarios/etc/test-outputs/exportEquals/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/exportEquals/api-extractor-scenarios.api.ts
- build-tests/api-extractor-scenarios/etc/test-outputs/exportEquals/rollup.d.ts
- build-tests/api-extractor-scenarios/package.json
- build-tests/api-extractor-scenarios/src/exportEquals/index.ts
- common/changes/@microsoft/api-extractor/pgonzal-ae-export-equals_2019-01-18-23-05.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/shrinkwrap.yaml
Files containing this sort of construct were incorrectly interpreted as containing ambient declarations:
```ts
declare module '@microsoft/teams-js' {
export = microsoftTeams;
}
```
> [api-extractor] Fix an issue analyzing files with "export="

- core-build/gulp-core-build-typescript/README.md
Add a missing backtick so package names are formatted correctly.
> Fix incorrect formatting in `README.md`

- apps/api-extractor/src/cli/ApiExtractorCommandLine.ts
- apps/rush-lib/src/cli/RushCommandLineParser.ts
- common/changes/@microsoft/api-extractor/master_2019-02-08-22-09.json
- common/changes/@microsoft/node-core-library/master_2019-02-08-22-09.json
- common/changes/@microsoft/rush/master_2019-02-08-22-09.json
- common/reviews/api/node-core-library.api.ts
- libraries/node-core-library/src/InternalError.ts
For Rush and API Extractor, the `--debug` parameter now automatically breaks in the debugger whenever `InternalError` is thrown.  This makes debugging easier.
> [node-core-library] Add InternalError.breakInDebugger property

- apps/rush-lib/assets/rush-init/rush.json
- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/cli/actions/ChangeAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/schemas/rush.schema.json
- apps/rush-lib/src/utilities/VersionControl.ts
- common/changes/@microsoft/rush/ianc-safer-rush-change_2019-02-08-02-22.json
- rush.json
This PR improves the way "rush change" detects the baseline remote, improves the handling of the case where the baseline remote can't be found, and tries to fetch from the remote before detecting changed projects.
> [rush] Improve change detection in "rush change."

- apps/api-extractor/CHANGELOG.json
- apps/api-extractor/CHANGELOG.md
Due to [an incorrect change log in PR 1011](https://github.com/Microsoft/web-build-tools/pull/1011/files#diff-c335bf48a413c4fe1fc365d223f6d232), we accidentally published API Extractor as version 8.0.0 instead of 7.0.19.
We will unpublish 8.0.0 and republish it as 7.0.19.
> [api-extractor] Rollback incorrectly published version 8.0.0 -> 7.0.19

- apps/rush-lib/src/cli/actions/PublishAction.ts
- common/changes/@microsoft/rush/ianc-fixing-issue-with-yarn-pack_2019-02-28-00-29.json
This PR fixes an issue where `rush publish --pack` doesn't work when Yarn is the package manager. Yarn adds a "v" before the version number when it creates tarballs, and the rename operation in Rush doesn't account for this.
> [rush] Fix an issue with rush publish --pack with yarn.

- apps/api-extractor/package.json
- apps/api-extractor/src/collector/MessageRouter.ts
- apps/api-extractor/src/collector/SourceMapper.ts
- common/changes/@microsoft/api-extractor/octogonz-ae-source-maps_2019-03-04-00-59.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/shrinkwrap.yaml
API Extractor analyzes .d.ts files, not .ts files.  When errors are reported, it's annoying for the coordinates to refer to the .d.ts file, since the person has to manually find the corresponding .ts file.
This PR makes use of "declaration maps" (new in TypeScript 3).  It's the same concept as [source maps](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit) except applied to `.d.ts` files instead of `.js` files.
To enable generation of `.d.ts.map` files, add set `declarationMap` in to your **tsconfig.json**.  For example:
```js
{
"compilerOptions": {
"target": "es6",
"module": "commonjs",
"declaration": true,
"sourceMap": true,       // <---- Generates file.js.map
"declarationMap": true,  // <---- Generate file.d.ts.map
"strictNullChecks": true,
. . .
} …
```
> [api-extractor] When reporting error line numbers, use source maps to find the original .ts file

- apps/rush/README.md
- common/changes/@microsoft/rush/ianc-prepare-for-rush-publish_2019-03-15-01-55.json
- common/config/azure-pipelines/templates/build.yaml
- common/config/azure-pipelines/templates/buildAndPublish.yaml
- common/config/rush/version-policies.json
This is now handled automatically by  the `ensureConsistentVersions` setting in rush.json
> [rush] Remove the "rush check" step from the travis.yml template

- apps/rush-lib/src/utilities/VersionControl.ts
- common/changes/@microsoft/rush/octogonz-rush-allow-dot-git_2019-03-17-19-46.json
After we upgraded to Rush 5.6.0, `rush change` was reporting this error:
```
Unable to find a git remote matching the repository URL (undefined). Detected changes are likely to be incorrect.
```
The reason is that our `repository.url` has the ".git" file extension:
```json
"url": "https://github.com/Microsoft/web-build-tools.git"
```
This is because the URL was copy+pasted from the GitHub web site's "Clone" button.  But the file extension is redundant and is dropped by `git clone`, so it doesn't appear in the list of remotes.
This PR relaxes the `rush change` comparison to ignore the `.git` file extension.
> [rush]  Allow the ".git" file extension to be appended to the repository.url setting

- apps/api-extractor/src/api/CompilerState.ts
- apps/api-extractor/src/api/ExtractorConfig.ts
- apps/api-extractor/src/api/IConfigFile.ts
- apps/api-extractor/src/collector/Collector.ts
- apps/api-extractor/src/schemas/api-extractor-defaults.json
- apps/api-extractor/src/schemas/api-extractor-template.json
- apps/api-extractor/src/schemas/api-extractor.schema.json
- common/changes/@microsoft/api-extractor/octogonz-ae-tsconfigfilepath_2019-04-11-05-11.json
- common/changes/@microsoft/api-extractor/octogonz-ae-tsconfigfilepath_2019-04-11-05-22.json
- common/reviews/api/api-extractor.api.md
Fixes issue https://github.com/Microsoft/web-build-tools/issues/1222
This PR adds a new config file setting `tsconfigFilePath` for customizing the path for `tsconfig.json`.
It also improves some config file related error messages.
> [api-extractor] Add a new setting "tsconfigFilePath"

- apps/api-extractor-model/package.json
- apps/api-extractor/package.json
- common/changes/@microsoft/api-extractor-model/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/api-extractor/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/gulp-core-build-mocha/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/gulp-core-build-typescript/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/gulp-core-build/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/node-core-library/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/rush-stack-compiler-2.4/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/rush-stack-compiler-2.7/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/rush-stack-compiler-2.9/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/rush-stack-compiler-3.0/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/rush-stack-compiler-3.1/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/rush-stack-compiler-3.2/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/rush-stack-compiler-3.3/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/changes/@microsoft/ts-command-line/octogonz-bump-cyclics2_2019-04-12-06-24.json
- common/config/rush/shrinkwrap.yaml
- core-build/gulp-core-build-mocha/package.json
- core-build/gulp-core-build-typescript/package.json
- core-build/gulp-core-build/package.json
- libraries/node-core-library/package.json
- libraries/ts-command-line/package.json
- stack/rush-stack-compiler-2.4/package.json
- stack/rush-stack-compiler-2.7/package.json
- stack/rush-stack-compiler-2.9/package.json
- stack/rush-stack-compiler-3.0/package.json
- stack/rush-stack-compiler-3.1/package.json
- stack/rush-stack-compiler-3.2/package.json
- stack/rush-stack-compiler-3.3/package.json
This PR updates everything to build using the latest API Extractor 7 release candidate.
> Bump cyclic dependencies

- apps/api-documenter/src/documenters/OfficeYamlDocumenter.ts
- common/changes/@microsoft/api-documenter/AlexJ-Example_2019-04-16-00-12.json
This extra line prevents the example header from being caught up in any preceding markdown (such as bulleted lists).
> [API Documenter]  Add extra newline character to example header

- apps/api-documenter/src/documenters/MarkdownDocumenter.ts
- common/changes/@microsoft/api-documenter/octogonz-ad-fix-home_2019-04-27-22-20.json
Fix the "Home" link in the breadcrumb when viewing docs using GitHub's markdown renderer
> [api-documenter] Fix the "Home" link in the breadcrumb when viewed with GitHub

- apps/api-extractor/src/generators/ApiModelGenerator.ts
- apps/api-extractor/src/generators/ExcerptBuilder.ts
- common/changes/@microsoft/api-extractor/octogonz-ae-1249_2019-04-30-05-00.json
Fixes issue #1249 
@natalieethell could you test this and confirm that (1) the broken signatures are fixed, and (2) no other signatures appear to be broken?  (You could simply diff your before/after .api.json files.)  Thanks!
> [api-extractor] Fix issue where API signatures were sometimes truncated

- apps/api-extractor/src/collector/MessageRouter.ts
- common/changes/@microsoft/api-extractor/octogonz-ae-issue1258_2019-05-05-18-43.json
Fixes #1258
Fix an issue where `ExtractorResult.warningCount` was not incremented for messages handled by `IExtractorInvokeOptions.messageCallback`.
> [api-extractor] Fix an issue where ExtractorResult.warningCount was sometimes not incremented

- .vscode/settings.json
- apps/api-extractor/src/analyzer/AstSymbolTable.ts
- apps/api-extractor/src/analyzer/ExportAnalyzer.ts
- apps/api-extractor/src/analyzer/TypeScriptHelpers.ts
- apps/api-extractor/src/analyzer/TypeScriptInternals.ts
- build-tests/api-extractor-test-01/dist/api-extractor-test-01-beta.d.ts
- build-tests/api-extractor-test-01/dist/api-extractor-test-01-public.d.ts
- build-tests/api-extractor-test-01/dist/api-extractor-test-01.d.ts
- build-tests/api-extractor-test-01/etc/api-extractor-test-01.api.md
- build-tests/api-extractor-test-01/src/EcmaScriptSymbols.ts
- common/changes/@microsoft/api-extractor/supportSymbolMembers_2019-05-29-22-28.json
This changes how we determine the `localName` of an `AstSymbol` in the following cases:
1. When the underlying TypeScript `Symbol` is a well-known ECMAScript symbol (i.e. it's `name` property is something like `__@iterator`).
2. When the underlying TypeScript `Symbol` is a late-bound name for a TypeScript `unique symbol`. In this case, `api-extractor` incorrectly reports these as `"__computed"`.
For case (1), we now extract the well-known symbol name (i.e. `iterator`) and report the name as something like `[Symbol.iterator]`.
For case (2), we will resolve the late-bound symbol (via `ts.TypeChecker.getSymbolAtLocation`), allow these late-bound symbols to pass through the checks in `AstSymbolTable._fetchAstSymbol`, and compute the name from the expression of the computed property.
Fixes …
> [api-extractor] Improved support for symbolic properties and methods

- apps/api-extractor-model/src/model/ApiConstructor.ts
- apps/api-extractor/src/generators/ApiModelGenerator.ts
- build-tests/api-documenter-test/etc/api-documenter-test.api.json
- common/changes/@microsoft/api-extractor-model/octogonz-ae-ctor-cannot-be-static_2019-06-02-21-52.json
- common/changes/@microsoft/api-extractor/octogonz-ae-ctor-cannot-be-static_2019-06-02-21-52.json
- common/reviews/api/api-extractor-model.api.md
This PR fixes a minor oversight where API Extractor modeled class constructors as being possibly static, even though this [can never occur](https://basarat.gitbooks.io/typescript/docs/tips/staticConstructor.html) in the TypeScript language.
Although this is technically a breaking API change, the change itself is somewhat trivial, and the affected API is very unlikely to be used by any tool other than API Extractor itself.  The .api.json file format also is changed, but the affected JSON field is mostly informational and not used during deserialization.  Thus, I'm marking this as a SemVer PATCH change.
@iclanton
> [api-extractor] Remove ApiConstructor.isStatic, since TypeScript constructors cannot be static

- apps/rush-lib/src/cli/actions/VersionAction.ts
- apps/rush-lib/src/logic/PublishGit.ts
- common/changes/@microsoft/rush/master_2019-06-06-23-07.json
When running `rush version --bump -b master` the ending git commands may fail if master changed in the meantime. 
It should instead `git fetch` before running the `git checkout master` to update refs.
This fixes #1318
> [rush] Fix git process in rush version action

- apps/api-extractor/src/api/CompilerState.ts
- common/changes/@microsoft/api-extractor/octogonz-fix-issue-1304_2019-06-26-15-32.json
> [api-extractor]  Fix issue where "typescriptCompilerFolder" did not work with TypeScript 3.4

- apps/rush-lib/src/logic/PackageJsonUpdater.ts
- common/changes/@microsoft/rush/ianc-fix-rush-add_2019-07-03-03-03.json
- common/changes/@microsoft/rush/ianc-fix-rush-add_2019-07-03-03-07.json
This also fixes an issue where the package manager may not be installed when `rush add` is invoked.
This fixes https://github.com/microsoft/web-build-tools/issues/1138.
> [rush] Fix an issue where "rush add" erroneously believes ensureConsistentVersions is unset.

- apps/api-extractor/src/api/Extractor.ts
- apps/api-extractor/src/cli/RunAction.ts
- common/changes/@microsoft/api-extractor/octogonz-ae-clarify-docs_2019-07-12-01-08.json
The `--typescript-compiler-folder` option configures where to find the compiler's system typings. (The current docs incorrectly imply that it causes that compiler engine to be invoked.)
> [api-extractor] Clarify the "--typescript-compiler-folder" docs

- apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts
- apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
- apps/rush-lib/src/logic/test/shrinkwrapFile/pnpm-lock.yaml
- common/changes/@microsoft/rush/sachinjoseph-fix1392_2019-07-17-04-50.json
Fix #1392 "rush install not working on pnpm 3.5" by getting the temporary project dependency key from the shrinkwrap.
> [rush] Fix #1392  "rush install not working on pnpm 3.5" by getting the  temporary project dependency key from the shrinkwrap

- apps/rush-lib/package.json
- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/utilities/Utilities.ts
- common/changes/@microsoft/rush/ianc-rush-path-casing_2019-07-26-05-52.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
Currently, if you run Rush in a console where the working directory's casing doesn't match the casing on disk (for example `c:\code\myrepo` is the cwd, but the actual path is `C:\code\myrepo`), symlinks to installed dependencies can get incorrect casing.
This causes problems when tools (like the TypeScript compiler and Webpack) reference a module in an installed dependency once with the incorrectly-cased path and again with the correct path in the same compilation run. Both tools have functionality to prevent referencing the same file twice with different casing, which can cause builds to fail.
Here's an example of such a failure from Webpack. Notice that one path contains a `D:/` and another contains a `d:/`:
```
D:/repo/common/temp/node_modules/.registry.npmjs.org/css-loader/0.28.11/node …
```
> [rush] Add logic to normalize the casing of paths that Rush uses.

- apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
- common/changes/@microsoft/rush/sachinjoseph-fix1418_2019-07-26-07-48.json
Do not terminate rush execution if a temp project lacks an entry in the PNPM shrinkwrap. Instead, allow the program to continue so that PNPM can update the outdated shrinkwrap.
> [rush] Do not terminate rush execution if a temp project lacks an entry in the PNPM shrinkwrap

- apps/rush-lib/assets/rush-init/common/config/rush/common-versions.json
- apps/rush-lib/assets/rush-init/common/config/rush/pnpmfile.js
- apps/rush-lib/assets/rush-init/rush.json
- common/changes/@microsoft/rush/octogonz-improve-rushjson-docs_2019-07-30-20-21.json
@abirmingham [recently had trouble](https://gitter.im/web-build-tools/web-build-tools?at=5d406c7e8aab922429eaae74) where a change to `preferredVersions` did not take effect because of running `rush update` instead of `rush update --full`.  Clarify the docs.
> [rush] Clarify that "rush update --full" should be run when changing certain settings

- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/logic/TaskSelector.ts
- apps/rush-lib/src/logic/taskRunner/ProjectTask.ts
- apps/rush-lib/src/logic/taskRunner/TaskCollection.ts
- apps/rush-lib/src/logic/taskRunner/TaskRunner.ts
- apps/rush-lib/src/logic/taskRunner/test/TaskCollection.test.ts
- apps/rush-lib/src/logic/taskRunner/test/TaskRunner.test.ts
- apps/rush-lib/src/logic/taskRunner/test/__snapshots__/TaskCollection.test.ts.snap
- apps/rush-lib/src/logic/taskRunner/test/__snapshots__/TaskRunner.test.ts.snap
- common/changes/@microsoft/rush/dependency-graph_2019-07-26-21-14.json
* Split TaskRunner and decouple it from TaskSelector
* Compute the project build command before execution
With these changes, TaskSelector can be called to get the list of build tasks without executing them. Plan is to expose these as an api for rush-buildxl next.
> [rush] Refactor build action to allow generating build graph statically

- apps/api-documenter/src/documenters/YamlDocumenter.ts
- build-tests/api-documenter-test/etc/yaml/api-documenter-test.yml
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/docbaseclass.yml
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/docclass1.yml
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/docenum.yml
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/generic.yml
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/idocinterface1.yml
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/idocinterface2.yml
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/idocinterface3.yml
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/idocinterface4.yml
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/idocinterface5.yml
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/idocinterface6.yml
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/systemevent.yml
- build-tests/api-documenter-test/etc/yaml/toc.yml
- common/changes/@microsoft/api-documenter/octogonz-ad-new-yaml-uids_2019-08-08-05-42.json
Update **api-documenter** to generate DocFX UIDs using use @rbuckton's new [DeclarationReference](https://github.com/microsoft/tsdoc/blob/master/tsdoc/src/beta/DeclarationReference.grammarkdown) syntax.  
Fixes https://github.com/microsoft/web-build-tools/issues/1252
Fixes https://github.com/microsoft/web-build-tools/issues/1052
@Vitalius1 @AlexJerabek @natalieethell Could you test this on your DocFX projects and make sure that (1) nothing is broken and (2) the above issues are fixed?
(I will tackle the filename/URL naming in a subsequent PR, because I'm realizing the solution for that problem is slightly different.)
Huge thanks to @rbuckton for designing the new UIDs! 😊🎉
> [api-documenter] Generate DocFX UIDs using new DeclarationReference algorithm

- common/changes/@microsoft/eslint-config-scalable-ts/octogonz-eslint_2019-08-15-01-29.json
- common/config/azure-pipelines/templates/buildAndPublish.yaml
- common/config/rush/common-versions.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- libraries/eslint-config-scalable-ts/index.js
- libraries/eslint-config-scalable-ts/package.json
- libraries/eslint-config-scalable-ts/patch-eslint6.js
- libraries/eslint-config-scalable-ts/react.js
- rush.json
This spring Palantir [announced](https://medium.com/palantir/tslint-in-2019-1a144c2317a9) that they are deprecating TSLint, and instead joining forces to integrate TypeScript linting into ESLint.  This is part of a general effort to enhance ESLint to support parsers for other languages.  As of ESLint 6 and `@typescript-eslint/eslint-plugin` 2.0.0, the implementation now seems to be mature enough for adoption.
This PR is an initial TypeScript rule set for ESLint, based on my earlier conversations with @iclanton.  It follows the spirit of the TSLint rule set for Rush Stack / GCB, but represents a complete ground-up audit of all the rules:
- I started with the union of: "recommended" rules from (1) ESLint for JavaScript, (2) the typescript-eslint plugin, (3) the Prettier plugin, and (4) the …
> [eslint-config-scalable-ts] Initial draft

- apps/rush-lib/src/logic/ChangeFiles.ts
- apps/rush-lib/src/logic/test/ChangeFiles.test.ts
- common/changes/@microsoft/rush/master_2019-08-15-16-25.json
Fixed an issue where a recent change to validate change files in a branch is `hotfixChangeEnabled` was in fact rejecting *all* changes because it was checking the wrong fields from the JSON.
Added a unit test to verify the 'negative' case of hotfix validation, and fixed the validation step.
> Fix validation of "hotfix" changes

- common/changes/@microsoft/eslint-config-scalable-ts/octogonz-ecst-react-rules_2019-08-21-21-17.json
- libraries/eslint-config-scalable-ts/react.js
Enable:
- **react/no-deprecated**:  Don't allow usage of deprecated React APIs
- **react/no-unescaped-entities**:  Catch some common mistakes
- **react/self-closing-comp**:  Require `<div />` instead of `<div></div>`.  Prettier previously implemented this, but removed it due to [a conflict with format-on-save](https://github.com/prettier/prettier/pull/6240)
> [eslint-config-scalable-ts] Enable some more React rules

- apps/rush-lib/src/logic/TaskSelector.ts
- apps/rush-lib/src/logic/taskRunner/TaskCollection.ts
- common/changes/@microsoft/rush/ianc-faster-collect-deps_2019-08-21-08-47.json
Running `rush [re]build` on repo with a large number of projects, or running `rush [re]build --to project-with-lots-of-dependencies` or `rush [re]build --from project-with-lots-of-dependents` can cause the process to stall for a long time before starting the actual build. If the dependency graph has a lot of intertwined dependencies, rush will end up doing a lot of repeated computations to determine dependencies/dependents (for `--to`/`--from`) and to ensure there are no cyclic dependencies.
This PR prevents those repeated computations.
> [rush] Task selection optimizations for repos with a large number of projects.

- common/changes/@microsoft/eslint-config-scalable-ts/octogonz-ecst-upgrade-plugin_2019-09-03-22-31.json
- common/config/rush/pnpm-lock.yaml
- libraries/eslint-config-scalable-ts/package.json
This upgrade fixes an incompatibility with the latest TypeScript compiler.  It also includes the fix for https://github.com/typescript-eslint/typescript-eslint/issues/788
> [eslint-config-scalable-ts] Upgrade @typescript-eslint/eslint-plugin

- common/changes/@microsoft/eslint-config-scalable-ts/octogonz-ecst-fix-array-type_2019-09-04-01-11.json
- libraries/eslint-config-scalable-ts/index.js
This fix will help to unblock https://github.com/microsoft/web-build-tools/pull/1496
> [eslint-config-scalable-ts] Fix rule that broke compatibility with older TypeScript versions

- apps/rush-lib/src/cli/actions/PublishAction.ts
- apps/rush-lib/src/cli/actions/VersionAction.ts
- common/changes/@microsoft/rush/sachinjoseph-fix669_2019-07-12-19-04.json
For "rush publish" and "rush version", change the path spec for git add to include everything from the root directory. This addresses https://github.com/microsoft/web-build-tools/issues/669.
> [rush] For "rush publish" and "rush version", change the path spec for 'git add' to include everything from the root directory. This addresses #669.

- apps/rush-lib/src/cli/actions/PublishAction.ts
- common/changes/@microsoft/rush/master_2019-09-09-18-25.json
Resolving an issue where publish would fail when using `--pack` and `--apply-git-tags-on-pack` if the git tag already existed. Now skipping tags for packages that are already published using the same check as non-pack publish flow.
> [rush-lib] Fixing issue in publishing when using --pack and --apply-git-tags-on-pack

- apps/api-documenter/src/documenters/OfficeYamlDocumenter.ts
- common/changes/@microsoft/api-documenter/AlexJ-YAML_2019-09-11-16-31.json
PR #1337 changed the format of UIDs. We currently parse out the package name in the OfficeYamlDocumenter. The syntax changed from `excel.Excel.foo` to `excel!Excel.foo`, so the regex needs to changed accordingly.
> [api-documenter] Adjusting package name parser in OfficeYamlDocumenter

- apps/rush-lib/src/logic/InstallManager.ts
- common/changes/@microsoft/rush/sachinjoseph-dontDeletePnpmStoreForInstallRetry_2019-08-27-17-25.json
`pnpm-store` is managed by PNPM internally, so leave it as is for the retry. This also ensures that packages that have already been downloaded need not be downloaded again, thereby potentially increasing the chances of a successful install. If the installation fails again, `rush purge` may be used to clear the `common/temp` folder.
> [rush] Don't delete pnpm store for rush install retry

- common/changes/@microsoft/ts-command-line/ianc-fix-argparse-types_2019-09-24-02-26.json
- libraries/ts-command-line/package.json
This fixes https://github.com/microsoft/web-build-tools/issues/1539.
> [ts-command-line] Add a missing dependency to ts-command-line.

- apps/api-documenter/src/documenters/MarkdownDocumenter.ts
- build-tests/api-documenter-test/etc/markdown/api-documenter-test.docclass1.md
- common/changes/@microsoft/api-documenter/master_2019-10-05-23-26.json
This commit changes the markdown documenter output logic, so that the remarks section appears on the top of the page for classes, interfaces, packages and namespaces. See https://github.com/microsoft/rushstack/issues/1550
> render remarks at page start for class, interface, package and namespace

- apps/rush-lib/src/logic/InstallManager.ts
- common/changes/@microsoft/rush/octogonz-rush-prefer-frozen-shrinkwrap_2019-10-08-23-10.json
In [Gitter chatroom](https://gitter.im/rushstack/rushstack?at=5d9bee8fb385bf2cc6919ece), @sadsa reported:
> After running `rush update` after updating PNPM to 4.0.0-7, I get 
> ```ERROR  Unknown option 'prefer-frozen-shrinkwrap'```
> [rush] Fix PNPM 4 incompatibility with --no-prefer-frozen-shrinkwrap

- common/changes/@microsoft/ts-command-line/keco-choice-alternatives-length_2019-10-17-23-12.json
- libraries/ts-command-line/src/CommandLineParameter.ts
Fixes an issue where an error is thrown if the supplied alternative values array contains only a single value. This scenario is supported in the schema.
> Fix CommandLineChoiceParameter error when alternatives array contains a single value

- apps/rush-lib/src/api/RushConfigurationProject.ts
- apps/rush-lib/src/logic/pnpm/PnpmProjectDependencyManifest.ts
- common/changes/@microsoft/rush/danade-fixUnmetPeerDependencyDuringLink_2019-10-24-21-48.json
- common/reviews/api/rush-lib.api.md
Fix a bug reported in #1589 by only writing to the console when strictPeerDependencies is false
> Fix unmet peer dependency error when strictPeerDependencies is false

- apps/api-extractor-model/src/mixins/ApiItemContainerMixin.ts
- common/changes/@microsoft/api-extractor-model/patch-1_2019-10-21-09-12.json
Clarified the error message by specifying which name and containerKey are already in use.
> [api-extractor] Clarified the error message

- common/changes/@microsoft/node-core-library/octogonz-tsdoc-eslint-plugin_2019-11-09-06-20.json
- common/changes/@rushstack/eslint-config/octogonz-tsdoc-eslint-plugin_2019-11-09-06-04.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- libraries/node-core-library/.eslintrc.js
- libraries/node-core-library/src/LockFile.ts
- stack/eslint-config/index.js
- stack/eslint-config/package.json
Update `@rushstack/eslint-config` to include @bafolts's new [eslint-plugin-tsdoc](https://www.npmjs.com/package/eslint-plugin-tsdoc) for validating TSDoc comments.
The configuration will initially be "opt-in" until we've tested it more exhaustively.
> [eslint-config] Add eslint-plugin-tsdoc

- .vscode/settings.json
- apps/api-documenter/src/documenters/DocumenterConfig.ts
- apps/api-documenter/src/documenters/IConfigFile.ts
- apps/api-documenter/src/documenters/MarkdownDocumenter.ts
- apps/api-documenter/src/schemas/api-documenter-template.json
- apps/api-documenter/src/schemas/api-documenter.schema.json
- apps/api-extractor/src/analyzer/PackageMetadataManager.ts
- apps/api-extractor/src/analyzer/Span.ts
- apps/api-extractor/src/analyzer/test/PackageMetadataManager.test.ts
- apps/api-extractor/src/api/Extractor.ts
- apps/api-extractor/src/api/ExtractorConfig.ts
- apps/api-extractor/src/api/IConfigFile.ts
- apps/api-extractor/src/generators/ApiReportGenerator.ts
- apps/api-extractor/src/generators/DtsRollupGenerator.ts
- apps/api-extractor/src/schemas/api-extractor-defaults.json
- apps/api-extractor/src/schemas/api-extractor-template.json
- apps/api-extractor/src/schemas/api-extractor.schema.json
- build-tests/api-documenter-test/config/api-documenter.json
- build-tests/api-documenter-test/config/api-extractor.json
- common/changes/@microsoft/api-documenter/os-default-eol_2019-11-12-23-24.json
- common/changes/@microsoft/api-extractor/os-default-eol_2019-11-12-22-09.json
- common/changes/@microsoft/node-core-library/os-default-eol_2019-11-12-22-09.json
- common/reviews/api/api-extractor.api.md
- common/reviews/api/node-core-library.api.md
- libraries/node-core-library/src/FileSystem.ts
- libraries/node-core-library/src/JsonFile.ts
- libraries/node-core-library/src/Text.ts
- Add a `newlineKind` option, which determines the type of newline used in all generated files. Options are `crlf` (default), `lf`, and (new) `os`. Fixes #1366.
- Trim trailing spaces from API rollup files, to prevent spurious diffs if the file is ever edited manually and the user has their editor configured to trim trailing spaces.
- Change some regexes which were checking for `[\r\n]` to check for `\r?\n` instead, so that any replacement is only applied once per actual newline.
Same as API Extractor.
- Add `NewlineKind.OsDefault` (and related conversion methods) to use the default newline kind for the operating system, as determined by `os.EOL`. This is always opt-in.
- Fix some doc comments
Fix the VS Code settings to exclude generated files in all subfolders and use commented JSON …
> Make API Extractor newlines configurable; add support for OS-default newlines

- apps/rush-lib/src/cli/actions/PublishAction.ts
- common/changes/@microsoft/rush/master_2019-11-20-02-32.json
Removing the `--registry` check when using `--pack`, since some pack flows will run `npm run view`, which requires the registry component.
> Removing check for --registry when using --pack

- apps/api-documenter/src/documenters/MarkdownDocumenter.ts
- apps/api-extractor-model/src/aedoc/AedocDefinitions.ts
- build-tests/api-documenter-test/etc/api-documenter-test.api.json
- build-tests/api-documenter-test/etc/markdown/api-documenter-test.docclass1.examplefunction.md
- build-tests/api-documenter-test/src/DocClass1.ts
- common/changes/@microsoft/api-documenter/throws_2019-11-19-15-40.json
- common/changes/@microsoft/api-extractor-model/throws_2019-11-19-15-40.json
Fixes #1631.
Note: I originally added a `@throws` line to one of the interfaces callables, and spent quite some time debugging why this didn't cause any change. I then realized that interface callables are not documented?
> [api-extractor]: Add support for `@throws`

- apps/rush-lib/src/cli/actions/PublishAction.ts
- apps/rush-lib/src/logic/PublishGit.ts
- common/changes/@microsoft/rush/master_2019-11-22-21-16.json
Resolving an issue where git tags would not be applied when using `--pack --apply-git-tags-on-pack` and using `publish --include-all`.
The issue was, publish was checking if a package was already published before adding a tag. In the `publish --include-all` flow, rush publishes and then goes to add the tag, so the package reads as published and the tag is not applied. 
This check has been moved to checking whether not a tag already exists locally via a new utility method in `PublishGit.ts`.
> [rush] Fix applying git tags when using --pack --apply-git-tags-on-pack and using publish --include-all

- apps/api-extractor-model/src/model/ModelReferenceResolver.ts
- apps/api-extractor/src/analyzer/AstReferenceResolver.ts
- apps/api-extractor/src/collector/Collector.ts
- apps/api-extractor/src/generators/ApiModelGenerator.ts
- build-tests/api-documenter-test/etc/api-documenter-test.api.json
- build-tests/api-documenter-test/etc/markdown/api-documenter-test.docclass1.md
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/docclass1.yml
- build-tests/api-documenter-test/src/DocClass1.ts
- common/changes/@microsoft/api-extractor-model/octogonz-ae-function-selectors_2019-12-03-02-10.json
- common/changes/@microsoft/api-extractor/octogonz-ae-function-selectors_2019-12-03-02-10.json
Fixes https://github.com/microsoft/rushstack/issues/1240
Suppose you have an overloaded method like this:
```ts
export class MyClass {
/** Overload 1 */
exampleFunction(a: string, b: string): string;
/** Overload 2 */
exampleFunction(x: number): number;
// Implementation
public exampleFunction(x: number | string, y?: string): string | number {
return x;
}
}
```
This PR enable the `@link` tag to reference this function, by specifying the overload index.  For example:
```ts
/** See {@link (MyClass.exampleFunction:2)} for details */
export class Y {
}
```
NOTE: In the future, we are planning to change the syntax for declaration references with `@link` .  See https://github.com/microsoft/rushstack/issues/1240#issuecomment-554845029 for details.
> [api-extractor] Implement support for @link to reference function overloads

- .gitattributes
- README.md
- apps/rush-lib/assets/rush-init/[dot]gitattributes
- common/changes/@microsoft/rush-stack/octogonz-update-urls_2019-12-05-20-58.json
- common/changes/@microsoft/rush/octogonz-update-urls_2019-12-05-20-58.json
- stack/rush-stack/README.md
When we recently renamed `web-build-tools` --> `rushstack`, we missed some files.
Fixes https://github.com/microsoft/rushstack/issues/1654
> Fix some old URLs that referenced web-build-tools

- apps/rush-lib/src/logic/taskRunner/TaskRunner.ts
- apps/rush-lib/src/logic/taskRunner/test/__snapshots__/TaskRunner.test.ts.snap
- common/changes/@microsoft/rush/bbenoist-print-task-run_2019-12-19-14-21.json
As my test command does not build anything nor requires any sort of build to be called, the following output "is very offensive to me" ™️ ( 🤡):
```
$ rush test
. . .
[my-project] failed to build!
. . .
Error: Project(s) failed to build
```
I've made the changes so that the output now is:
```text
$ rush build
. . .
[my-project] failed!
. . .
Error: Project(s) failed
```
> Don't use the build verb when printing task failures

- common/changes/@microsoft/load-themed-styles/es6_2019-12-17-05-40.json
- libraries/load-themed-styles/package.json
Fixes #1292
Simply adds a package.json entry for load-theme-styles to make esm friendly bundlers happy
> [load-theme-styles] Add es6 "module" entry in package.json

- build-tests/node-library-build-eslint-test/.vscode/launch.json
- build-tests/node-library-build-eslint-test/package.json
- build-tests/node-library-build-eslint-test/tsconfig.json
- common/changes/@rushstack/eslint-plugin/octogonz-no-untyped-underscore_2020-01-08-03-37.json
- common/config/rush/common-versions.json
- common/config/rush/pnpm-lock.yaml
- repo-scripts/repo-toolbox/src/start.ts
- stack/eslint-plugin/README.md
- stack/eslint-plugin/src/index.ts
- stack/eslint-plugin/src/no-null.ts
- stack/eslint-plugin/src/no-untyped-underscore.ts
This is an opt-in rule for TypeScript code that needs to access legacy JavaScript libraries that have not been migrated to TypeScript yet.
It prevents TypeScript code from accessing legacy JavaScript members whose name has an underscore prefix.
The following patterns are considered problems when `@rushstack/no-untyped-underscore` is enabled:
```ts
let x: any;
x._privateMember = 123;  // error
let x: { [key: string]: number };
x._privateMember = 123;  // error
```
The following patterns are NOT considered problems:
```ts
let x: { _privateMember: any };
x._privateMember = 123;  // okay because _privateMember is declared by x's type
enum E {
_PrivateMember
}
let e: E._PrivateMember = E._PrivateMember; // okay because _PrivateMember is declared by E
```
CC @jparker-hbo
> [eslint-plugin] Add a new ESLint rule "@rushstack/no-untyped-underscore"

- common/changes/@microsoft/load-themed-styles/notype_2020-01-07-01-47.json
- libraries/load-themed-styles/src/index.ts
This PR accompanies https://github.com/microsoft/rushstack/issues/1673 by removing the type=text/css attribute from generated style tags. This is to reduce HTML validation errors in client pages (details in issue) & align with the [WHATWG ](https://html.spec.whatwg.org/multipage/obsolete.html#obsolete-but-conforming-features:attr-style-type)/ [Mozilla ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style)docs.
> [load-themed-styles] removing text/css type from style element

- common/changes/@microsoft/gulp-core-build-sass/keco-autoprefixer_2020-01-15-19-15.json
- common/config/rush/pnpm-lock.yaml
- core-build/gulp-core-build-sass/package.json
- core-build/gulp-core-build-sass/src/SassTask.ts
Bumps `autoprefixer` to `~9.7.4` to include bug fixes for various vendor specific issues in CSS.
Modified `browsers` arg to use `overrideBrowsersList` introduced in `autoprefixer@9.6`.
Release notes for `autoprefixer`: https://github.com/postcss/autoprefixer/releases
> Bump autoprefixer to ~9.7.4

- common/changes/@rushstack/eslint-config/octogonz-bump-eslint-plugin-tsdoc_2020-01-21-21-30.json
- common/config/rush/pnpm-lock.yaml
- stack/eslint-config/package.json
Upgrade the `eslint-plugin-tsdoc` package.  (These changes only affect **.eslintrc.js** configurations that have opted-in for the `tsdoc/syntax` rule.)
- JSON comments are now allowed in the **tsdoc.json** config file
- A cache is used to avoid repeatedly reloading the **tsdoc.json** config file
> [eslint-config] Upgrade eslint-plugin-tsdoc

- apps/rush-lib/assets/rush-init/rush.json
- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/cli/actions/ChangeAction.ts
- apps/rush-lib/src/schemas/rush.schema.json
- apps/rush-lib/src/utilities/VersionControl.ts
- common/changes/@microsoft/rush/add-git-properties_2020-01-20-16-47.json
- common/reviews/api/rush-lib.api.md
I've been looking through sources and accidentally understood that moving this constanted variables to configuration will take me around 20 minutes, so why not.
This can be useful for a lot of people.
> [rush] Make default branch and origin name configurable

- apps/rush-lib/src/utilities/Utilities.ts
- common/changes/@microsoft/rush/ianc-fix-rushx_2020-01-26-01-59.json
The `rushx` command in Rush 5.19.1 currently reports errors on every command. This PR fixes that.
> [rush] Fix an issue with error reporting in executeLifecycleCommand.

- apps/rush-lib/src/logic/PublishGit.ts
- common/changes/@microsoft/rush/master_2020-01-27-23-00.json
Resolving an issue with rush publishing when git tags are applied. Rush's `PublishUtilities` automatically add quotes around all shell arguments, which is not reflected in the `DRYRUN` output. The quotes added around the quotes will unqoute the `-m` arg to the `git tag` command, which will result in the message reading as too separate arguments.
> [rush] Fix for rush publish / git tagging "too many args" or "Failed to resolve 'v<version>' as a valid ref"

- apps/rush-lib/src/cli/actions/PublishAction.ts
- common/changes/@microsoft/rush/danade-fixBrokenInit_2020-02-12-02-01.json
`rush init` was broken by attempting to access RushConfiguration in the constructor of the publish action. I've moved the initialization into the run() method to initialize when the action is actually run.
> Move RushConfiguration access in action to unblock Init

- apps/rush-lib/src/logic/EventHooksManager.ts
- common/changes/@microsoft/rush/fix-event-hook-fail-color_2020-02-14-12-22.json
This PR adds a yellow coloring when an event hook fails.
It has been discussed on #1745
> [rush-lib] Adds yellow output on event hook fail

- common/changes/@microsoft/rush-stack-compiler-2.4/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@microsoft/rush-stack-compiler-2.7/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@microsoft/rush-stack-compiler-2.8/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@microsoft/rush-stack-compiler-2.9/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@microsoft/rush-stack-compiler-3.0/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@microsoft/rush-stack-compiler-3.1/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@microsoft/rush-stack-compiler-3.2/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@microsoft/rush-stack-compiler-3.3/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@microsoft/rush-stack-compiler-3.4/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@microsoft/rush-stack-compiler-3.5/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@microsoft/rush-stack-compiler-3.6/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@microsoft/rush-stack-compiler-3.7/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@microsoft/rush/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/changes/@rushstack/ts-command-line/keco-bump-tslint-contrib_2020-04-01-02-47.json
- common/config/rush/pnpm-lock.yaml
- stack/rush-stack-compiler-2.4/package.json
- stack/rush-stack-compiler-2.7/package.json
- stack/rush-stack-compiler-2.8/package.json
- stack/rush-stack-compiler-2.9/package.json
- stack/rush-stack-compiler-3.0/package.json
- stack/rush-stack-compiler-3.1/package.json
- stack/rush-stack-compiler-3.2/package.json
- stack/rush-stack-compiler-3.3/package.json
- stack/rush-stack-compiler-3.4/package.json
- stack/rush-stack-compiler-3.5/package.json
- stack/rush-stack-compiler-3.6/package.json
- stack/rush-stack-compiler-3.7/package.json
Although `tslint` is deprecated, some downstream repos have not yet been migrated to `eslint`. We'd like to bump `tslint-microsoft-contrib@6.2.0` namely to include the following rule fix: https://github.com/microsoft/tslint-microsoft-contrib/issues/813. Currently, I'm pinning the version using `pnpmfile.js` in the downstream repo.
cc: @dennisjsyi
> Bump tslint-microsoft-contrib to ~6.2.0 to include react-this-binding-issue rule fix

- common/changes/@rushstack/eslint-config/octogonz-clarify-ban-types-message_2020-04-06-23-51.json
- stack/eslint-config/index.js
**Old message:**
```
src/index.ts(7,22): error @typescript-eslint/ban-types: Don't use 'Object' as a type. Use Record<string, any> instead
```
This advice produces other errors about the `any` type.
**New message:**
```
src/index.ts(7,22): error @typescript-eslint/ban-types: Don't use 'Object' as a type. Use 'object' instead, or else define a proper TypeScript type
```
@manderso-hbo
> [eslint-config] Improve error message for "ban-types" rule

- apps/rush-lib/src/scripts/install-run.ts
- common/changes/@microsoft/rush/patch-1_2020-04-11-10-11.json
Hi,
in some certain minimalistic build environments, `@microsoft/rush` can't installed because the command line tool `which` is not available. 
```
Installing @microsoft/rush...
Error: Unable to install package: Error: Unable to determine the path to the NPM tool: Error: Command failed: which npm
/bin/sh: which: command not found
```
While we could fix this issue by our own by just installing `which` I would like to improve this cool project a little bit.
In shell scripting it's preferred to use `command -v` instead `which` because the first one is a POSIX shell built-in. It looks like `childProcess.execSync` already opens a shell internally, we could use just the built-in helpers instead an external small utility. 
Related resources:
* …
> [rush-lib] Use `command` instead of `which`

- common/changes/@rushstack/eslint-config/octogonz-ncl-fs_2020-05-27-04-09.json
- common/changes/@rushstack/node-core-library/octogonz-ncl-fs_2020-05-27-04-09.json
- common/changes/@rushstack/node-core-library/octogonz-ncl-fs_2020-05-27-04-10.json
- common/reviews/api/node-core-library.api.md
- libraries/node-core-library/src/FileSystem.ts
- libraries/node-core-library/src/index.ts
- stack/eslint-config/index.js
This PR also adds an `FileSystemStats` alias. And relaxes a lint rule that was too strict.
> [node-core-library] Add FileSystem.readLink() API

- common/changes/@microsoft/rush-stack-compiler-2.4/octogonz-rsc-es2017_2020-05-27-05-35.json
- common/changes/@microsoft/rush-stack-compiler-2.7/octogonz-rsc-es2017_2020-05-27-05-35.json
- common/changes/@microsoft/rush-stack-compiler-2.8/octogonz-rsc-es2017_2020-05-27-05-35.json
- common/changes/@microsoft/rush-stack-compiler-2.9/octogonz-rsc-es2017_2020-05-27-05-35.json
- common/changes/@microsoft/rush-stack-compiler-3.0/octogonz-rsc-es2017_2020-05-27-05-35.json
- common/changes/@microsoft/rush-stack-compiler-3.1/octogonz-rsc-es2017_2020-05-27-05-35.json
- common/changes/@microsoft/rush-stack-compiler-3.2/octogonz-rsc-es2017_2020-05-27-05-35.json
- common/changes/@microsoft/rush-stack-compiler-3.3/octogonz-rsc-es2017_2020-05-27-05-35.json
- common/changes/@microsoft/rush-stack-compiler-3.4/octogonz-rsc-es2017_2020-05-27-05-35.json
- common/changes/@microsoft/rush-stack-compiler-3.5/octogonz-rsc-es2017_2020-05-27-05-35.json
- common/changes/@microsoft/rush-stack-compiler-3.6/octogonz-rsc-es2017_2020-05-27-05-35.json
- common/changes/@microsoft/rush-stack-compiler-3.7/octogonz-rsc-es2017_2020-05-27-05-35.json
- common/changes/@rushstack/node-core-library/octogonz-rsc-es2017_2020-05-27-05-35.json
- libraries/node-core-library/src/FileSystem.ts
- stack/rush-stack-compiler-2.4/includes/tsconfig-node.json
- stack/rush-stack-compiler-2.7/includes/tsconfig-node.json
- stack/rush-stack-compiler-2.8/includes/tsconfig-node.json
- stack/rush-stack-compiler-2.9/includes/tsconfig-node.json
- stack/rush-stack-compiler-3.0/includes/tsconfig-node.json
- stack/rush-stack-compiler-3.1/includes/tsconfig-node.json
- stack/rush-stack-compiler-3.2/includes/tsconfig-node.json
- stack/rush-stack-compiler-3.3/includes/tsconfig-node.json
- stack/rush-stack-compiler-3.4/includes/tsconfig-node.json
- stack/rush-stack-compiler-3.5/includes/tsconfig-node.json
- stack/rush-stack-compiler-3.6/includes/tsconfig-node.json
- stack/rush-stack-compiler-3.7/includes/tsconfig-node.json
This PR updates **tsconfig-node.json** to target `es2017` (supported by Node 8).  This is recommended by the TypeScript wiki here:
https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
Transpiling for `es2017` enables native `async`/`await`.  When using Node 12, this produces complete call stacks like this:
```
caught: Error: oops!
at C:\Git\rushstack2\libraries\node-core-library\lib\FileSystem.js:465:19
at async Function._wrapExceptionAsync (C:\Git\rushstack2\libraries\node-core-library\lib\FileSystem.js:715:20)
at async test2 (C:\Git\rushstack2\apps\api-extractor\lib\start.js:7:12)
at async test (C:\Git\rushstack2\apps\api-extractor\lib\start.js:10:12)
```
This PR also adds the `async` keyword to the FileSystem APIs, which adds them to the callstack like this:
```
caught: …
```
> [rush-stack-compiler] Update tsconfig-node.json to target es2017

- common/changes/@rushstack/node-core-library/octogonz-ncl-copyfiles_2020-05-29-05-13.json
- common/reviews/api/node-core-library.api.md
- libraries/node-core-library/src/FileSystem.ts
- libraries/node-core-library/src/index.ts
This adds an API for recursively copying files. It was motivated by PR https://github.com/microsoft/rushstack/pull/1898 which does this:
https://github.com/microsoft/rushstack/blob/de1443cb43d9d08ce6017499a30e2d33050b288a/apps/rush-lib/src/logic/deploy/DeployManager.ts#L159-L175
I also added some validation to clarify that `FileSystem.copyFile()` was never intended to work with folders.  Previously if a folder was specified, it would have recursively copied it, which is counterintuitive.
> [node-core-library] Add a FileSystem.copyFiles() API

- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- common/changes/@microsoft/rush/octogonz-tsc-description-fix_2020-05-31-07-46.json
- common/changes/@rushstack/ts-command-line/octogonz-tsc-description-fix_2020-05-31-07-46.json
- libraries/ts-command-line/src/parameters/BaseClasses.ts
- libraries/ts-command-line/src/providers/CommandLineParameterProvider.ts
- libraries/ts-command-line/src/test/CommandLineParameter.test.ts
- libraries/ts-command-line/src/test/__snapshots__/CommandLineParameter.test.ts.snap
This sentence was missing the word "be":
*"This parameter may alternatively specified via the ______ environment variable."*
Also the code that appends a period before this sentence did not consider sentences that end with a quoted word.
> [ts-command-line] Fix a typo in the supplementary notes

- apps/rush-lib/src/logic/deploy/DeployManager.ts
- common/changes/@microsoft/rush/fix-optionalDependencies-required-for-deploy_2020-06-02-13-21.json
Fixes #1908
note: note sure if the pre-existing ` if (!resolvedDependency) {` would still be required for different use-cases/tool combo's, so kept both on purpose.
Feel free to remove in an edit if not required.
> [rush] deploy step, try/catch resolve.sync to allow optional dependencies to pass

- apps/rush-lib/src/logic/PublishGit.ts
- common/changes/@microsoft/rush/octogonz-rush-version-no-verify_2020-06-11-04-52.json
Fixes this error during publishing:
```
* EXECUTING: git add :/**/CHANGELOG.json 
warning: LF will be replaced by CRLF in apps/rush/CHANGELOG.json.
The file will have its original line endings in your working directory
* EXECUTING: git add :/**/CHANGELOG.md 
warning: LF will be replaced by CRLF in apps/rush/CHANGELOG.md.
The file will have its original line endings in your working directory
* EXECUTING: git commit -m Deleting change files and updating change logs for package updates. 
fatal: cannot run .git/hooks/pre-commit: No such file or directory
ERROR: The command failed with exit code 1
##[error]Bash exited with code '1'.
Finishing: Rush Version
```
> [rush[ Add "--no-verify" for commits performed by "rush version"

- apps/rush-lib/src/logic/InstallManager.ts
- common/changes/@microsoft/rush/octogonz-git-hooks-linux_2020-06-11-05-20.json
- common/git-hooks/commit-msg.sample
- rush.json
This PR also upgrades us to Rush 5.25.1
> [rush] Ensure Git hook scripts use LF newlines

- apps/api-extractor/src/analyzer/AstSymbolTable.ts
- apps/api-extractor/src/analyzer/ExportAnalyzer.ts
- apps/api-extractor/src/collector/Collector.ts
- apps/api-extractor/src/generators/ApiModelGenerator.ts
- apps/api-extractor/src/generators/DeclarationReferenceGenerator.ts
- build-tests/api-extractor-scenarios/etc/test-outputs/bundledPackages/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/bundledPackages/api-extractor-scenarios.api.md
- build-tests/api-extractor-scenarios/etc/test-outputs/bundledPackages/rollup.d.ts
- build-tests/api-extractor-scenarios/src/bundledPackages/index.ts
- common/changes/@microsoft/api-extractor/octogonz-ae-issue1933_2020-06-15-21-49.json
Fixes https://github.com/microsoft/rushstack/issues/1933
> [api-extractor] Fix missing documentation hyperlinks when using the "bundledPackages" setting

- apps/api-documenter/src/documenters/MarkdownDocumenter.ts
- build-tests/api-documenter-test/etc/markdown/api-documenter-test.docclass1.md
- build-tests/api-documenter-test/etc/markdown/api-documenter-test.idocinterface2.md
- common/changes/@microsoft/api-documenter/octogonz-ad-heritage-types_2020-06-19-22-14.json
Fixes https://github.com/microsoft/rushstack/issues/1944
> [api-documenter] Show "extends" and "implements" links for class/interface APIs

- common/changes/@rushstack/eslint-config/octogonz-eslint-config-react-lambdas_2020-06-25-06-06.json
- stack/eslint-config/index.js
`variableDeclarationIgnoreFunction` is a recent feature for the [`@typescript-eslint/typedef` rule](https://github.com/typescript-eslint/typescript-eslint/blob/v3.3.0/packages/eslint-plugin/docs/rules/typedef.md).  It allows us to eliminate a redundant type declaration when binding `this` for event handlers.
> [eslint-config] Enable variableDeclarationIgnoreFunction

- common/config/azure-pipelines/ci.yaml
- rush.json
The build failures look like this:
```
@microsoft/rush-stack-compiler-3.6 (16.27 seconds)
(node:5079) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The build failed because a task wrote output to stderr.
```
The problem seems to be that `require("domain")` [is now deprecated](https://stackoverflow.com/questions/58784689/node-error-using-a-domain-property-in-makecallback-is-deprecated).  But some of our dependencies are using it.
The solution is probably to figure out how to upgrade those dependencies.
Until then, we can disable Node 14 to avoid breaking CI builds.
> Temporarily disable Node 14, which is causing CI builds to fail

- apps/api-extractor/src/api/CompilerState.ts
- apps/api-extractor/src/collector/MessageRouter.ts
- common/changes/@microsoft/api-extractor/octogonz-ae-diagnostic-formatting_2020-07-03-05-20.json
Fix an issue with newer TypeScript release, where an error is supposed to look like this:
```
Warning: node_modules/@uifabric/merge-styles/lib/concatStyleSets.d.ts:12:248 - (TS2344) Type 'TStyleSet1 & TStyleSet2' does not satisfy the constraint 'IStyleSet<TStyleSet1 & TStyleSet2>'.
Type 'TStyleSet1 & TStyleSet2' is not assignable to type '{ subComponentStyles?: { [P in keyof (TStyleSet1 & TStyleSet2)["subComponentStyles"]]: IStyleFunctionOrObject<any, IStyleSet<any>>; } | undefined; }'.
Types of property 'subComponentStyles' are incompatible.
Type '({ [P in keyof TStyleSet1["subComponentStyles"]]: IStyleFunctionOrObject<any, IStyleSet<any>>; } & { [P in keyof TStyleSet2["subComponentStyles"]]: IStyleFunctionOrObject<...>; }) | undefined' is not assignable to type '{ [P in keyof …
```
> [api-extractor] Fix an issue where chained compiler diagnostic messages were formatted incorrectly

- apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
- apps/rush-lib/src/logic/test/ShrinkwrapFile.test.ts
- common/changes/@microsoft/rush/fix-github-pnpm-shrinkwrap-error_2020-07-03-04-30.json
closes #1984
I updated the regex to match URLs that begin with an `@` symbol to support the new URL format for tarball packages added in `pnpm v5.x` here: https://github.com/pnpm/pnpm/pull/2620
I also updated the unit tests to confirm it works as expected.
> [rush] fix: allow URLs to start with @ prefix to support new pnpm tarball URL format

- apps/heft/build.js
The `build.js` script was failing when invoked using the Bash shell.
Interesting that our CI did not catch this, since it uses Linux, but it failed on my local Linux box.
> [heft] Fix build.js error on Mac/Linux

- apps/rush-lib/package.json
- apps/rush-lib/src/cli/actions/DeployAction.ts
- apps/rush-lib/src/logic/deploy/DeployManager.ts
- common/changes/@microsoft/rush/fix-1982_2020-07-08-17-13.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
I’ve implemented most of what was recommended in the issue, but I’m not sure where to write the tests. 
I also haven’t implemented this for the `script` linking. I want to make sure I’m headed in the right direction.
Closes #1982
> [rush] Copy over package binaries during deploy

- common/changes/@rushstack/module-minifier-plugin/dmichon-module-minifier-typings_2020-07-14-21-01.json
- common/reviews/api/module-minifier-plugin.api.md
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.types.ts
`@types/webpack` does not expose `webpack.compilation.RequestShortener`, which was referenced within `ModuleMinifierPlugin.types.ts` and therefore rolled up into the public API surface. It was internally extended to facilitate its usage within the plugin, but this breaks for official consumers of the plugin.
> [Module Minifier Plugin] Fix invalid reference in API extractor emitted types

- apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
- common/changes/@microsoft/rush/fixWorkspaceInstallSkip_2020-07-15-23-04.json
Fixes https://github.com/microsoft/rushstack/issues/2030
> [rush] Consider package.json files in calculation to determine if install should be skipped in workspaces

- common/changes/@rushstack/module-minifier-plugin/dmichon-compress_2020-07-17-00-27.json
- common/reviews/api/module-minifier-plugin.api.md
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.ts
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.types.ts
- webpack/module-minifier-plugin/src/RehydrateAsset.ts
- webpack/module-minifier-plugin/src/terser/MinifySingleFile.ts
- webpack/module-minifier-plugin/src/test/RehydrateAsset.test.ts
Support routing external modules via marking the identifiers as "reserved" to Terser during the initial minification process, then following up after rehydration by converting the `__WEBPACK_EXTERNAL_MODULE_*` identifiers to more compact identifiers.
> [Module Minifier Plugin] Add support for external modules

- common/changes/@rushstack/module-minifier-plugin/dmichon-optional-peer_2020-07-22-22-30.json
- common/reviews/api/module-minifier-plugin.api.md
- webpack/module-minifier-plugin/package.json
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.types.ts
Move `@types/webpack` to optional peer dependency.
Fix base type of `IExtendedModule` to only be based on `webpack.compilation.Module`, not `webpack.Module`, since the latter is the webpack configuration "module" section, which is completely irrelevant.
> [Module Minifier Plugin] Make @types/webpack peer dependency optional

- .gitignore
- apps/heft/src/plugins/JestPlugin/JestPlugin.ts
- apps/heft/src/plugins/JestPlugin/JestTypeScriptDataFile.ts
- apps/heft/src/plugins/JestPlugin/jest-build-transform.ts
- apps/heft/src/plugins/JsonConfigurationLoaders/JsonConfigurationFilesPluginBase.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptPlugin.ts
- apps/heft/src/schemas/typescript.schema.json
- apps/heft/src/stages/BuildStage.ts
- apps/heft/src/templates/typescript.json
- build-tests/heft-webpack-basic-test/.heft/clean.json
- build-tests/heft-webpack-basic-test/.heft/typescript.json
- build-tests/heft-webpack-basic-test/tsconfig.json
- build-tests/heft-webpack-basic-test/webpack.config.js
- build-tests/heft-webpack-everything-test/.heft/clean.json
- build-tests/heft-webpack-everything-test/.heft/typescript.json
- build-tests/heft-webpack-everything-test/package.json
- common/changes/@rushstack/heft/octogonz-heft-jest-with-webpack2_2020-08-03-00-27.json
- common/changes/@rushstack/node-core-library/octogonz-heft-jest-with-webpack2_2020-08-03-06-31.json
- common/reviews/api/heft.api.md
- common/reviews/api/node-core-library.api.md
- libraries/node-core-library/src/JsonFile.ts
- libraries/node-core-library/src/test/JsonFile.test.ts
- libraries/node-core-library/src/test/__snapshots__/JsonFile.test.ts.snap
This builds upon PR https://github.com/microsoft/rushstack/pull/2064 to make Jest work better with Webpack.
When TypeScript is emitting multiple output folders (e.g. `commonjs` for Jest and `esnext` for Webpack), this PR provides a way to tell Jest which folder to consume.  The actual processing happens inside the **jest-build-transform.js** script, which cannot access the normal Heft context.  Therefore the TypeScript stage stores the `emitFolderPathForJest` path in a temporary file **.heft/build-cache/jest-typescript-data.json**, which the transform reads.
_Note: Ideally `JestPlugin` should have the job of writing **jest-typescript-data.json**, but currently there is no easy way for `JestPlugin` to access the TypeScript configuration.  (We can improve that as part of the design …
> [heft] Add new "emitFolderPathForJest" setting in typescript.json

- apps/rush-lib/src/api/RushConfiguration.ts
- common/changes/@microsoft/rush/master_2020-08-07-16-19.json
Mac OS creates .DS_Store hidden files to track metadata for the Finder application.  Rush was complaining about those files.
@ARamachaHBO
> [rush] Fix for "An unrecognized file .DS_Store was found in the Rush config folder"

- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- apps/heft/src/plugins/TypeScriptPlugin/internalTypings/TypeScriptInternals.ts
- common/changes/@rushstack/heft/octogonz-heft-issue-2086_2020-08-10-05-47.json
Fixes https://github.com/microsoft/rushstack/issues/2086
The problem is that Heft was redirecting the **tsconfig.json** `"outDir"` setting in order to write files into `./.heft/build-cache/lib` instead of `./lib`, but this causes the source maps to have a relative path with an extra `../..`.
I solved it by preserving the real  `"outDir"`, and instead performing the mapping later inside the `writeFileCallback()` for `ts.Program.emit()`.
CC @iclanton
> [heft] Fix source map paths

- apps/rush-lib/src/cli/RushXCommandLine.ts
- apps/rush-lib/src/cli/test/Cli.test.ts
- apps/rush-lib/src/cli/test/repo/rushx-project/build.js
- apps/rush-lib/src/cli/test/repo/rushx-project/package.json
- apps/rush-lib/src/startx.ts
- common/changes/@microsoft/rush/octogonz-better-rushx_2020-08-12-07-58.json
Fixes https://github.com/microsoft/rushstack/issues/1232
Consider this script:
**package.json**
```js
. . .
"scripts": {
"build": "rm -f lib && node ./build.js"
}
. . .
```
Suppose that you invoke this command:
```
$ rushx build a b c --production
```
BEFORE this PR, the shell would execute: `rm -f lib && node ./build.js`
AFTER this PR, the shell will execute: `rm -f lib && node ./build.js a b c --production`
Ideally we want a different design, where `rushx` has full syntax validation and `--help` for every parameter.  But until that ideal is realized, this PR lets people pass subcommands to their shell scripts similar to how NPM and Yarn do.
> [rush] Fix an issue where "rushx" did not pass additional parameters to the shell script

- apps/heft/package.json
- apps/heft/src/cli/actions/BuildAction.ts
- apps/heft/src/cli/actions/TestAction.ts
- apps/heft/src/plugins/JestPlugin/JestPlugin.ts
- apps/heft/src/plugins/JestPlugin/jest-build-transform.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- common/changes/@rushstack/heft/octogonz-jest-source-maps_2020-08-13-01-48.json
- common/changes/@rushstack/heft/octogonz-jest-source-maps_2020-08-13-04-10.json
- common/changes/@rushstack/heft/octogonz-jest-source-maps_2020-08-13-04-12.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
Several Jest fixes
- Incorrect source maps
- `heft test --clean watch` error 
- Spurious `"The transpiler output folder does not exist"` error
Fixes https://github.com/microsoft/rushstack/issues/2078
> [Heft] Fix an issue with incorrect sourcemaps for Jest

- apps/heft/.vscode/launch.json
- apps/heft/src/plugins/JestPlugin/jest-build-transform.ts
- apps/heft/src/plugins/TypeScriptPlugin/EmitFilesPatch.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- common/changes/@rushstack/heft/octogonz-jest-transform-race_2020-08-13-08-47.json
- common/changes/@rushstack/heft/octogonz-jest-transform-race_2020-08-13-08-50.json
- common/changes/@rushstack/heft/octogonz-jest-transform-race_2020-08-13-08-51.json
- Fix a race condition where .js files were sometimes read by Jest before they were written by TypeScript
- Disable the build cache in watch mode
- Add support for `additionalModuleKindsToEmit` in watch mode
> [Heft] Improve TypeScript/Jest interaction in watch mode

- common/changes/@rushstack/module-minifier-plugin/dmichon-concat-start_2020-08-14-23-10.json
- webpack/module-minifier-plugin/config/jest.config.json
- webpack/module-minifier-plugin/src/RehydrateAsset.ts
- webpack/module-minifier-plugin/src/test/RehydrateAsset.test.ts
When `useConcat` is enabled during asset rehydration, but there are ids between 0 and `minId`, the array is improperly constructed. Specifically, the leading elements are omitted completely, resulting in a shift to all ids in the array.
> [Module Minifier Plugin] Fix issue with missing module ids at start of array

- apps/rush-lib/src/scripts/install-run.ts
- common/changes/@microsoft/rush/master_2020-08-13-00-46.json
We've observed an interesting bug on some Windows systems where the current approach leads to the environment having _two_ path variables declared, differing only in case (``PATH`` and ``Path``). 
This appears to cause various downstream issues, such as some (but not all) ``git`` commands failing; see #2097 
I can't claim to understand this fully, but leaving it to NodeJS to handle the OS-dependent details around case-sensitivity/insensitivity of environment variables appears to do the trick!
> [rush] install-run.js should set PATH correctly on Windows

- apps/heft/src/cli/actions/TestAction.ts
- common/changes/@rushstack/debug-certificate-manager/ianc-heft-notest_2020-08-20-06-44.json
- common/changes/@rushstack/heft/ianc-heft-notest_2020-08-20-06-44.json
- common/changes/@rushstack/package-deps-hash/ianc-heft-notest_2020-08-20-06-44.json
- common/changes/@rushstack/stream-collator/ianc-heft-notest_2020-08-20-06-44.json
- common/changes/@rushstack/ts-command-line/ianc-heft-notest_2020-08-20-06-44.json
- common/reviews/api/ts-command-line.api.md
- libraries/debug-certificate-manager/config/jest.config.json
- libraries/debug-certificate-manager/config/jest.json
- libraries/package-deps-hash/config/jest.config.json
- libraries/package-deps-hash/config/jest.json
- libraries/rushell/config/jest.config.json
- libraries/rushell/config/jest.json
- libraries/stream-collator/config/jest.config.json
- libraries/stream-collator/config/jest.json
- libraries/ts-command-line/config/jest.config.json
- libraries/ts-command-line/config/jest.json
- libraries/ts-command-line/src/parameters/BaseClasses.ts
- libraries/ts-command-line/src/parameters/CommandLineDefinition.ts
- libraries/ts-command-line/src/providers/CommandLineParameterProvider.ts
- libraries/ts-command-line/src/providers/CommandLineParser.ts
- libraries/ts-command-line/src/providers/DynamicCommandLineAction.ts
- libraries/ts-command-line/src/test/ActionlessParser.test.ts
- libraries/ts-command-line/src/test/CommandLineParameter.test.ts
- libraries/ts-command-line/src/test/CommandLineParser.test.ts
- libraries/ts-command-line/src/test/CommandLineRemainder.test.ts
- libraries/ts-command-line/src/test/DynamicCommandLineParser.test.ts
- libraries/ts-command-line/src/test/__snapshots__/CommandLineParameter.test.ts.snap
This change also includes support for an `undocumentedSynonyms` option for parameters.
> [heft] Add the --notest parameter back to heft test, omitted from documentation.

- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- common/changes/@microsoft/rush/sachinjoseph-lazyLoadLocalProjects_2020-08-19-18-36.json
- common/reviews/api/rush-lib.api.md
This further improves Rush startup times, especially on large monorepos with hundreds of projects.
> [rush] Load and validate local projects lazily

- apps/rush-lib/src/logic/deploy/DeployManager.ts
- common/changes/@microsoft/rush/octogonz-rush-deploy-2121_2020-08-20-17-47.json
Fixes https://github.com/microsoft/rushstack/issues/2121
> [rush] Fix "already exists" error for "rush deploy" command

- common/changes/@rushstack/eslint-plugin/octogonz-jest-eslint_2020-08-23-00-51.json
- stack/eslint-plugin/README.md
- stack/eslint-plugin/src/hoist-jest-mock.test.ts
- stack/eslint-plugin/src/hoist-jest-mock.ts
- stack/eslint-plugin/src/hoistJestMockPatterns.ts
- stack/eslint-plugin/src/index.ts
- stack/eslint-plugin/src/matchTree.test.ts
- stack/eslint-plugin/src/matchTree.ts
- stack/eslint-plugin/src/no-new-null.test.ts
This ESLint rule catches a common mistake when using Heft's Jest transform.
See [README.md](https://github.com/microsoft/rushstack/blob/octogonz/jest-eslint/stack/eslint-plugin/README.md) for docs.
> [eslint-plugin] Add a new rule @rushstack/hoist-jest-mock

- common/changes/@rushstack/package-deps-hash/bewegger-package-deps-ignore-del-files-untracked_2020-08-21-13-10.json
- libraries/package-deps-hash/src/getPackageDeps.ts
If I modify a file, stage it, and delete it, I won't be able to create a hash using `getPackageDeps`. This PR removes any file from hash consideration when it is marked as deleted in the working tree or is deleted and staged with no additional changes in the working tree.
Here's a repro with the current implementation:
```sh
$ echo "console.log('Hello world')" > foo.js
$ git add foo.js
$ rm foo.js
$ git status -s -u
AD foo.js
$ node -e 'console.log(require("@rushstack/package-deps-hash").getPackageDeps())'
~/git/rushstack/libraries/package-deps-hash/lib/getPackageDeps.js:132
throw new Error(`git hash-object exited with status ${result.status}: ${result.stderr}`);
^
Error: git hash-object exited with status 128: fatal: Cannot open '~/dev/package-deps-hash-removed-in-unstaged/foo.js': No …
```
> [package-deps-hash] Do not hash files that are deleted in working tree

- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/logic/TaskSelector.ts
- apps/rush-lib/src/logic/taskRunner/BaseBuilder.ts
- apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts
- apps/rush-lib/src/logic/taskRunner/Task.ts
- apps/rush-lib/src/logic/taskRunner/TaskCollection.ts
- apps/rush-lib/src/logic/taskRunner/TaskRunner.ts
- apps/rush-lib/src/logic/taskRunner/test/MockBuilder.ts
- apps/rush-lib/src/logic/taskRunner/test/ProjectTask.test.ts
- apps/rush-lib/src/logic/taskRunner/test/TaskCollection.test.ts
- apps/rush-lib/src/logic/taskRunner/test/TaskRunner.test.ts
- common/changes/@microsoft/rush/octogonz-rush-task-runner-refactor_2020-09-04-00-53.json
This is some preliminary refactoring that gets things in better shape for my fix for https://github.com/microsoft/rushstack/issues/2135
The main changes:
- ITask becomes a class Task
- ITaskDefinition becomes a class BaseBuilder
- ProjectTask renames to ProjectBuilder
This eliminates the weirdness where ProjectTask implemented ITaskDefinition but got casted to ITask and then had undeclared properties added to its objects.
> This is a pure refactoring PR that should not affect the behavior of Rush at all.
> [Rush] Refactor the TaskRunner

- apps/heft/package.json
- apps/heft/src/cli/HeftToolsCommandLineParser.ts
- apps/heft/src/cli/actions/HeftActionBase.ts
- apps/heft/src/stages/BuildStage.ts
- apps/heft/src/utilities/Constants.ts
- common/changes/@rushstack/heft/ianc-fix-some-parameter-issues_2020-09-04-23-15.json
- common/changes/@rushstack/heft/ianc-fix-some-parameter-issues_2020-09-04-23-16.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
The `--max-old-space-size` parameter's value was never read, and the `--plugin` parameter was parsed after plugins were initialized. This PR reads the former, and adds a special parser for the latter to get its value before the rest of the CLI is parsed.
> [heft] Fix issues with the --plugin and --max-old-space-size parameters.

- common/changes/@rushstack/module-minifier-plugin/dmichon-fix-duplicate-modules_2020-09-02-01-10.json
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.ts
Fixes a bug in which if a chunk somehow contained duplicate module ids they would render invalid code.
> [module-minifier-plugin] Fix duplicate modules during render

- apps/heft/src/pluginFramework/PluginManager.ts
- common/changes/@rushstack/heft/benpapp-FixPluginNameErrorTypo_2020-09-08-23-39.json
fix typo in an error message to read that plugins must define a \"pluginName\" property, rather than the former \"displayName\" property
> [heft] fix plugin name error typo

- apps/heft/src/cli/actions/TestAction.ts
- apps/heft/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/heft/src/plugins/JestPlugin/JestPlugin.ts
- apps/heft/src/stages/TestStage.ts
- common/changes/@rushstack/heft/max-workers-cli_2020-09-07-17-39.json
- common/reviews/api/heft.api.md
For CI environments, I couldn't find a way to change the `maxWorkers` configuration value for Jest using an environment variable. The best I've come up with so far is to change the `maxWorkers` config option, but that requires the max workers config to be the same everywhere.
Since a CI environment might be more / less powerful than a local development machine, or one person's machine might be more / less powerful than the other, I think it makes sense to forward that Jest CLI option through the Heft CLI.
That way, I can just update my build script inside CI to pass `--maxWorkers` as something else, and have the default value inside the configuration something sensible for local development environments.
I noticed the CLI options for testing could potentially apply to more than just Jest …
> [heft] feat: add --max-workers CLI option for jest

- apps/rush-lib/src/logic/ChangelogGenerator.ts
- common/changes/@microsoft/rush/pr-2165_2020-09-09-03-10.json
Prettier formatter defaults to underscore instead of single-asterisk.
To avoid back and forth between generated markdown and formatted output,
default to prettier default in this small matter.
> [rush] Use underscore for italic markdown text

- common/changes/@rushstack/localization-plugin/halfnibble-fix-loc-webpack-devserver_2020-09-11-17-40.json
- webpack/localization-plugin/src/LocalizationPlugin.ts
Webpack dev server will emit hot update chunks ending in 'hot-update.js', which conflict with the latest changes in the LocalizationPlugin. This attempts to address that.
> [localization-plugin] Handle webpack dev server hot update chunks.

- apps/heft/src/plugins/JestPlugin/JestTypeScriptDataFile.ts
- apps/heft/src/plugins/JestPlugin/jest-build-transform.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptPlugin.ts
- common/changes/@rushstack/heft/octogonz-skip-timestamp-check_2020-09-15-00-58.json
@D4N14L reported that jest-build-transform.js sometimes times out due to a timestamp issue. We can improve reliability of jest-build-transform.js by only comparing timestamps when `--watch` mode is enabled.
> [heft] Improve reliability of jest-build-transform.js

- apps/heft/includes/jest-shared.config.json
- common/changes/@rushstack/heft/octogonz-heft-console-log_2020-09-16-01-05.json
This code:
```js
describe('Example Test', () => {
it('Correctly tests stuff', () => {
console.log('Hello,\nworld!');
expect(true).toBeTruthy();
});
```
Was supposed to show this output:
```
START src\test\ExampleTest.test.ts
|  console.log| Hello,
|  console.log| world!
PASS src\test\ExampleTest.test.ts (duration: 0.419s, 3 passed, 0 failed)
```
...but this feature weirdly gets disabled if `verbose=true` in the Jest options.
> [heft] Fix an issue where console.log() didn't get interceped by the Jest reporter

- apps/rush-lib/src/api/EnvironmentConfiguration.ts
- apps/rush-lib/src/api/RushGlobalFolder.ts
- common/changes/@microsoft/rush/octogonz-rush-env-var-regression_2020-09-17-06-54.json
This is a regression from https://github.com/microsoft/rushstack/pull/2188 that we missed during testing because it only affects the VersionSelector front-end.
> [rush] Fix "The EnvironmentConfiguration must be initialized" issue

- apps/heft/src/pluginFramework/PluginManager.ts
- apps/heft/src/plugins/ApiExtractorPlugin/ApiExtractorPlugin.ts
- apps/heft/src/plugins/CopyStaticAssetsPlugin.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptPlugin.ts
- apps/heft/src/stages/CleanStage.ts
- apps/heft/src/utilities/fileSystem/CachedFileSystem.ts
- apps/heft/src/utilities/fileSystem/ExtendedFileSystem.ts
- common/changes/@rushstack/heft-config-file/ianc-fix-issue-with-config-resolution_2020-09-18-20-34.json
- common/changes/@rushstack/heft/ianc-fix-issue-with-config-resolution_2020-09-18-20-34.json
- common/changes/@rushstack/node-core-library/ianc-fix-issue-with-config-resolution_2020-09-18-20-34.json
- common/reviews/api/node-core-library.api.md
- libraries/heft-config-file/src/ConfigurationFile.ts
- libraries/node-core-library/src/FileSystem.ts
This change fixes a few issues:
- "extends" fields can now use module reference syntax instead of only relative path syntax.
- If an "extends" field pointed to a module that didn't exist, the error was silently ignored.
> [heft] Fix a few issues related to "extends" fields in config files.

- common/changes/@rushstack/eslint-config/octogonz-eslint-config-updates_2020-09-18-19-51.json
- common/changes/@rushstack/eslint-config/octogonz-eslint-config-updates_2020-09-18-19-52.json
- common/changes/@rushstack/eslint-config/octogonz-eslint-config-updates_2020-09-18-19-53.json
- stack/eslint-config/index.js
- `@typescript-eslint/array-type`:  This rule was awkward for certain expressions such as `Partial<Bar>[]` and `Array<[string, T[]]>`. We discussed fixing the rule implementation, but the consensus was that the benefits of this rule are dubious. It simply didn't seem worth the time investment to figure out how to handle those edge cases.
- `@typescript-eslint/no-use-before-define`:  A small option change (`functions: false`) which is explained in the comments.
- Add *.spec.ts file extension for tests, since this is also a commonly used convention
> [eslint-config] 3 minor fixes for lint rules

- apps/heft/src/utilities/HeftConfigFiles.ts
- common/changes/@rushstack/heft/ianc-fix-clean_2020-09-18-22-33.json
There is an issue with the way we detect if a path contains a glob pattern on Windows. Right now, we tell `heft-config-file` to resolve all of the paths listed in `clean.json`, which results in paths that look like `C:\repo\my-project\lib` on Windows. We detect if that path contains a glob pattern by seeing if it is changed by `globEscape`. Escaping that path gives us `C:\\repo\\my-project\\lib`, so `C:\repo\my-project\lib` then gets expanded as a glob pattern (that matches nothing).
> Fix an issue with "clean" on Windows.

- common/changes/@rushstack/eslint-plugin-security/octogonz-fix-dep_2020-09-19-04-25.json
- common/changes/@rushstack/eslint-plugin/octogonz-fix-dep_2020-09-19-04-25.json
- stack/eslint-plugin-security/package.json
- stack/eslint-plugin/package.json
A dependency was accidentally added to `devDependencies` instead of `dependencies`
> [eslint-plugin] Add missing dependency

- common/changes/@microsoft/rush/octogonz-stream-collator-fix_2020-09-20-05-19.json
- common/changes/@rushstack/stream-collator/octogonz-stream-collator-fix_2020-09-20-05-17.json
- libraries/stream-collator/src/StreamCollator.ts
I noticed that the `rush build` command sometimes stalled like this:
```
==[ @microsoft/rush-stack-compiler-3.5 ]=========================[ 20 of 97 ]==
"@microsoft/rush-stack-compiler-3.5" completed successfully in 18.52 seconds.
==[ @microsoft/rush-stack-compiler-3.0 ]=========================[ 21 of 97 ]==
"@microsoft/rush-stack-compiler-3.0" completed successfully in 18.31 seconds.
>>> PAUSE HERE <<<
==[ @microsoft/rush-stack-compiler-3.2 ]=========================[ 22 of 97 ]==
```
When we would expect the delay to happen like this:
```
==[ @microsoft/rush-stack-compiler-3.5 ]=========================[ 20 of 97 ]==
"@microsoft/rush-stack-compiler-3.5" completed successfully in 18.52 seconds.
==[ @microsoft/rush-stack-compiler-3.0 ]=========================[ 21 of 97 ]==
>>> PAUSE …
```
> [stream-collator] Fix issue that caused lagged output for "rush build"

- apps/rush-lib/src/cli/RushCommandLineParser.ts
- common/changes/@microsoft/rush/patch-1_2020-09-18-15-01.json
Fixes https://github.com/microsoft/rushstack/issues/2203
The check for `!process.exitCode` returned true when `process.exitCode` is `undefined`. This caused some commands to incorrectly exit with a success code when they should be failing.
Note: I created this PR from the GitHub UI after testing with a cloned copy, so I'm hoping tests will catch issues with it, if there are any. I've verified it manually by patching the code in a similar way by hand.
> [rush] Fix incorrect "successful" exit status code

- common/changes/@rushstack/terminal/dmichon-terminal-dep_2020-09-22-01-19.json
- libraries/terminal/package.json
Multiple files have a runtime, not just dev time dependency on @rushstack/node-core-library. Fixing the dependency to be a runtime dependency so that it can be successfully installed in pnpm/rush.
> [terminal] Fix dependency on @rushstack/node-core-library

- apps/heft/src/cli/HeftToolsCommandLineParser.ts
- common/changes/@rushstack/heft/octogonz-heft-help_2020-09-26-05-09.json
This fixes a regression introduced by PR #2168.
Commands like `heft build --help` printed incorrect help because the `_getPluginArgumentValues()` parser was handling `--help`.
> [heft] Fix an issue with the "--help" CLI parameter

- apps/heft/src/plugins/ApiExtractorPlugin/ApiExtractorRunner.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- apps/heft/src/plugins/TypeScriptPlugin/internalTypings/TypeScriptInternals.ts
- common/changes/@rushstack/heft/octogonz-heft-checks_2020-09-30-10-40.json
- common/changes/@rushstack/heft/octogonz-heft-checks_2020-09-30-10-50.json
- Reclassify TypeScript strict mode checks as warnings instead of errors
- Warn if API Extractor is too old
> [heft] Improve some warnings

- apps/heft/src/plugins/SassTypingsPlugin/SassTypingsGenerator.ts
- build-tests/heft-sass-test/src/utilities/relativeImport.sass
- common/changes/@rushstack/heft/halfnibble-fix-sass-typings_2020-10-09-01-25.json
We discovered relative paths were not resolved because Sass did not have the file path as context.
This fixes that issue and adds a test case.
> Support relative paths in @import and @use

- apps/rush-lib/src/cli/actions/VersionAction.ts
- common/changes/@microsoft/rush/danade-FixPackageJsonGlob_2020-10-09-21-22.json
Fixes #2249 by only including package.json updates in the glob used to add files to the generated git commit
> Fix glob to only include package.json updates when commiting version bump changes

- apps/heft/src/plugins/CopyStaticAssetsPlugin.ts
- common/changes/@rushstack/heft/halfnibble-fix-copy-static_2020-10-10-00-57.json
This will copy over static assets, like .scss files, into any additional folders specified by additionalModuleKindsToEmit.
For some reason, I had to add the eslint disable line. Not sure how the rule is being violated. 
Fixes #2251
> [heft] Include additionalModuleKindsToEmit in the copy-static-assets plugin

- apps/rush-lib/src/logic/base/BaseInstallManager.ts
- apps/rush-lib/src/logic/pnpm/PnpmProjectDependencyManifest.ts
- apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
- common/changes/@microsoft/rush/danade-FixUpdateBug_2020-10-16-20-41.json
Fixes #2288 by moving the post-install `rush link` outside of the scope of the check for `last-install.flag`. We were skipping running linking if the install was still valid, causing `rush unlink` to break installs with no hope of recovery by calling `rush install` or `rush update`. Another option was to delete the `last-install.flag` when `rush unlink` is run, but this would unnecessarily force the package manager to be called. One more option would be to run post-install regardless of `last-install.flag` (as this change does) but conditionally run `rush link` only if the `last-link.flag` file is older than `last-install.flag`. However, linking is a lightweight operation so I decided against over-complicating the check.
Additionally, this PR fixes a bug introduced by #2286 wherein a …
> [rush-lib] Run post-install step on every call to `rush install` or `rush update`

- apps/heft/src/index.ts
- apps/heft/src/plugins/Webpack/WebpackPlugin.ts
- apps/heft/src/stages/BuildStage.ts
- common/changes/@rushstack/heft/feat-webpack-task-supports-custom-dev-server-options_2020-10-15-03-18.json
- common/reviews/api/heft.api.md
- tutorials/heft-webpack-basic-tutorial/webpack.config.js
This MR adds functionality to support custom `devServer` options for the webpack task in heft.
> feat(heft): webpack task supports custom devServer options #2281

- README.md
For many years Rush has used a Gitter chatter room to provide tech support, however we've been hearing a lot of frustration about the user experience. For example Gitter's mobile notifications [do not work reliably](https://gitlab.com/gitlab-org/gitter/webapp/blob/2d5abfce277534080fae45e86c3da27ae1d04d49/docs/notifications.md#mobile-notifications), with no solution after years of waiting.  They eventually stopped supporting the mobile apps, investing in a PWA mobile website as an alternative.  Recently GitLab [sold Gitter to Element](https://blog.gitter.im/2020/09/30/gitter-element-acquisition/) who makes the Riot chat client, and announced a new roadmap to eventually replace the mobile apps with Element's client.  That could be very positive. However in the meantime, we're going to try …
> Replace Gitter link with Zulip

- common/changes/@rushstack/node-core-library/octogonz-fix-linux-colors_2020-10-27-04-43.json
- libraries/node-core-library/src/Terminal/AnsiEscape.ts
- libraries/node-core-library/src/Terminal/Colors.ts
- libraries/node-core-library/src/Terminal/Terminal.ts
Fix an issue where the TextAttribute.Bold ANSI escape was not rendered correctly by Linux.  It caused all subsequent text to be bold and underlined, even the shell prompt after the process had terminated.
> [node-core-library] Fix incorrect Terminal coloring on Linux

- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/cli/actions/VersionAction.ts
- common/changes/@microsoft/rush/fix-missing-add-on-version_2020-10-26-20-57.json
- common/reviews/api/rush-lib.api.md
When version policy is used, during the version process the version-policy configuration file gets updated with the latest version of the versioned policy, but that change is not added to the stage during the commit process.
This changes add the file to the stage along the package.json changes.
> [rush-lib] Fix bug on version process using version policy

- common/changes/@rushstack/eslint-plugin-packlets/octogonz-fix-packlet-issues_2020-10-27-05-08.json
- common/changes/@rushstack/eslint-plugin-packlets/octogonz-fix-packlet-issues_2020-10-27-05-12.json
- common/changes/@rushstack/eslint-plugin-packlets/octogonz-fix-packlet-issues_2020-10-27-05-13.json
- stack/eslint-plugin-packlets/src/DependencyAnalyzer.ts
- stack/eslint-plugin-packlets/src/PackletAnalyzer.ts
- stack/eslint-plugin-packlets/src/Path.ts
- stack/eslint-plugin-packlets/src/circular-deps.ts
- stack/eslint-plugin-packlets/src/mechanics.ts
- stack/eslint-plugin-packlets/src/test/Path.test.ts
Fix a couple issues reported by @victor-wm:
- An exception occurred if a source file was added to the `src/packlets` folder, not belonging to any packlet
- linting was sometimes not performed on MacOS, because Node.js `path.relative()` incorrectly assumes that every POSIX file system is case-sensitive
While testing these fixes, I also noticed this problem and fixed it as well:
- `@rushstack/packlets/circular-deps` did not detect certain types of circular dependencies
> [eslint-plugin-packlets] Fix several miscellaneous issues

- apps/rush-lib/src/cli/actions/BaseInstallAction.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/logic/EventHooksManager.ts
- common/changes/@microsoft/rush/dmichon-add-ignore-hooks_2020-10-14-23-17.json
Adds a new command line flag `--ignore-hooks` to all rush actions that does exactly what it says. Skips any configured `eventHooks` in `rush.json` during execution of the action. Example usage is when the actions are to perform telemetry for local dev installs and the commands are being invoked on a CI machine.
Edited: per feedback, switched from only `rush install` and `rush update` to all rush actions.
> [rush] Add `--ignore-hooks` command line flag to all rush actions

- apps/heft/README.md
- common/changes/@rushstack/heft/octogonz-heft-readme_2020-11-02-21-39.json
This PR removes the conspicuous 🚨 alert from the Heft README.  Although Heft has not yet reached its "1.0" milestone, it is already being used for production projects, and at this point its contracts are reasonably stable.
> [heft] Update README

- apps/rush-lib/src/cli/actions/VersionAction.ts
- common/changes/@microsoft/rush/fix-add-changes-working-dir_2020-11-03-16-46.json
When calling `rush version --bump` it fails with:
```
* EXECUTING: git add . (common/config/rush/version-policies.json)
ERROR: spawnSync /bin/sh ENOTDIR
```
This is caused by mixing up `workingDirectory` and `pathspec`.
> [rush-lib] Fix bug where version process is using a wrong `git.addChanges` signature

- common/config/rush/browser-approved-packages.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- tutorials/heft-webpack-basic-tutorial/package.json
- tutorials/heft-webpack-basic-tutorial/webpack.config.js
One possible solution for issue #2316
Configures the heft-webpack-basic-tutorial project to use [source-map-loader](https://www.npmjs.com/package/source-map-loader) to resolve the transitive closure of mappings from the .js files in ./dist to the .ts files in ./src
Note this falls apart if the project has a dependency on another rush project.
source-map-loader has a strong assumption that its webpack config is in a common ancestor folder of all the traversed source maps leading to the wrong relative paths being generated for pretty much all source files discovered.
using `devtool: 'eval-source-map'` helps unblock the above issue by embedding the source map in generated bundles so that they can always be found but still leaves some odd quirks. e.g browsing source files in Chrome reveals …
> Use source-map-loader to map back to .ts files in webpack tutorial

- apps/heft/src/plugins/ApiExtractorPlugin/ApiExtractorRunner.ts
- common/changes/@rushstack/heft/octogonz-heft-ae-message_2020-11-14-19-45.json
When invoked by Heft, API Extractor messages incorrectly printed the message category:
```
[api-extractor] Warning: src\Thing.ts:40:1 - (Extractor) "IThing" is exported by the package, but it is missing a release tag (@alpha, @beta, @public, or @internal)
```
This Heft should print the message ID the same as the API Extractor CLI:
```
[api-extractor] Warning: src\Thing.ts:40:1 - (ae-missing-release-tag) "IThing" is exported by the package, but it is missing a release tag (@alpha, @beta, @public, or @internal)
```
This makes it easy for people to search for an ID like `ae-missing-release-tag` in the documentation.
Confirmed that it fixed the problem for my repro.
> [heft] Display message ID when reporting API Extractor issues

- common/changes/@microsoft/api-extractor-model/octogonz-fix-changelog_2020-11-18-06-09.json
- common/changes/@microsoft/api-extractor/octogonz-fix-changelog_2020-11-18-06-09.json
Add a missing change log so that `api-extractor` and `api-extractor-model` get new versions published to support the optional properties feature.
> Add a missing changelog

- apps/api-documenter/src/documenters/MarkdownDocumenter.ts
- apps/api-extractor-model/src/index.ts
- apps/api-extractor-model/src/items/ApiPropertyItem.ts
- apps/api-extractor-model/src/mixins/ApiOptionalMixin.ts
- apps/api-extractor-model/src/model/ApiMethod.ts
- apps/api-extractor-model/src/model/ApiMethodSignature.ts
- apps/api-extractor/src/generators/ApiModelGenerator.ts
- build-tests/api-documenter-test/etc/api-documenter-test.api.json
- build-tests/api-documenter-test/etc/markdown/api-documenter-test.idocinterface7.md
- build-tests/api-extractor-scenarios/etc/test-outputs/apiItemKinds/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/bundledPackages/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/circularImport/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/circularImport2/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/docReferences/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/docReferences2/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/docReferences3/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/exportEquals/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/functionOverload/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/inconsistentReleaseTags/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/internationalCharacters/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/typeParameters/api-extractor-scenarios.api.json
- common/changes/@microsoft/api-documenter/octogonz-ae-more-optional-properties_2020-11-18-08-02.json
- common/changes/@microsoft/api-extractor-model/octogonz-ae-more-optional-properties_2020-11-18-08-02.json
- common/changes/@microsoft/api-extractor/octogonz-ae-more-optional-properties_2020-11-18-08-02.json
- common/reviews/api/api-extractor-model.api.md
The recent PR https://github.com/microsoft/rushstack/pull/2280 introduced an `isOptional` field for tracking API items that should be displayed as "(Optional)" in the documentation.  But it only applied to properties.
This PR generalizes the model so that all of these things are now documented as optional:
- interface methods
- interface properties
- class methods
- class properties
> [api-extractor] Generalize "isOptional" to describe both methods and properties

- common/changes/@microsoft/gulp-core-build/master_2020-11-25-06-11.json
- core-build/gulp-core-build/src/tasks/JestTask.ts
Related issue: https://github.com/microsoft/rushstack/issues/2367
About jest result data structure:
> [Gulp-core-build] Fail jest task when coverage fails

- apps/rush-lib/assets/rush-init/rush.json
- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/cli/actions/VersionAction.ts
- apps/rush-lib/src/schemas/rush.schema.json
- common/changes/@microsoft/rush/issue-2360-add-rush-version-commit-message_2020-11-22-22-01.json
- common/reviews/api/rush-lib.api.md
Issue #2360. Added variable commit message `changeLogUpdateCommitMessage` in rush.json -> gitPolicy for `rush version` like `versionBumpCommitMessage` 
At the moment, if I call the `rush version` in Azure Devops Pipeline, the message without [skip ci] will immediately commit and push to the Git. This causes re-build and may lead to build cycle if no additional check is done.
I have added the ability to edit this message by analogy with the `versionBumpCommitMessage`
**_Question_**
Do I need to add the parameter in `apps\rush-lib\assets\rush-init\rush.json`? Because when I add the parameter, I get a json validation error.
> [rush-lib] Added 'rush version' commit message to rush.json-> gitPolicy

- apps/heft/src/utilities/subprocess/SubprocessRunnerBase.ts
- apps/heft/src/utilities/subprocess/SubprocessTerminator.ts
- common/changes/@rushstack/heft/octogonz-heft-subprocess_2020-12-10-06-26.json
Fixes https://github.com/microsoft/rushstack/issues/2387
See issue for details.
Tested on Linux, Windows, and Mac.
Test cases:
- `heft build --watch` (TypeScriptBuilder)
- `heft test --watch` (Jest)
- `heft start` (webpack)
For each case, I pressed CTRL+C and then ran `ps` to check for a stray process.  I first confirmed whether the problem reproed, then (on Linux and Mac) confirmed that this patch fixes it.
> [heft] Fix an issue where child processes were sometimes not terminated with CTRL+C

- apps/heft/src/cli/actions/BuildAction.ts
- apps/heft/src/cli/actions/HeftActionBase.ts
- apps/heft/src/cli/actions/StartAction.ts
- apps/heft/src/cli/actions/TestAction.ts
- apps/heft/src/index.ts
- apps/heft/src/pluginFramework/PluginManager.ts
- apps/heft/src/plugins/CopyFilesPlugin.ts
- apps/heft/src/plugins/SassTypingsPlugin/SassTypingsPlugin.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptPlugin.ts
- apps/heft/src/plugins/Webpack/WebpackPlugin.ts
- apps/heft/src/stages/BuildStage.ts
- apps/heft/src/utilities/Async.ts
- apps/heft/src/utilities/Logging.ts
- common/changes/@rushstack/heft/ianc-heft-watch_2020-12-09-01-33.json
- common/reviews/api/heft.api.md
Right now, when `heft build --watch` is run, all build stages are kicked off simultaneously. This causes problems when downstream stages have dependencies on a "first emit" of upstream stages. For example, if the TypeScript compiler requires generated typings.
This change doesn't kick off the next stage until all of the plugins in the current stage resolve. In `--watch` mode, plugins are expected to stay active after resolving.
In the future, I'd like to formalize this better by having watch operations register themselves and potentially receive a cancellation token.
This change was tested by running `heft start`, `heft build --watch`, and `heft test --watch` in all of the tutorials projects. Everything behaved as expected.
> [heft] Delay build subsequent build stages until the current phase has notified that it is finished in --watch mode.

- apps/rush-lib/src/cli/RushCommandLineParser.ts
- apps/rush-lib/src/cli/actions/BaseInstallAction.ts
- apps/rush-lib/src/cli/actions/CheckAction.ts
- apps/rush-lib/src/cli/actions/InitAction.ts
- apps/rush-lib/src/cli/actions/PublishAction.ts
- apps/rush-lib/src/cli/actions/PurgeAction.ts
- apps/rush-lib/src/cli/actions/ScanAction.ts
- apps/rush-lib/src/cli/actions/UnlinkAction.ts
- apps/rush-lib/src/logic/base/BaseInstallManager.ts
- apps/rush-lib/src/logic/taskRunner/TaskRunner.ts
- apps/rush-lib/src/utilities/Utilities.ts
- apps/rush/src/RushVersionSelector.ts
- apps/rush/src/start.ts
- common/changes/@microsoft/rush/ianc-asyncify_2020-12-13-00-07.json
This simple PR converts the remaining old-style async code (`.then` and `.catch`) to `async`/`await`.
- Ran `rush update` with this build of `rush-lib` in a https://github.com/microsoft/rushstack/ repo on `master`
- Ran `rush build` with this build of `rush-lib` in a https://github.com/microsoft/rushstack/ repo on `master` 
- Ran `rush purge` with this build of `rush-lib` in a https://github.com/microsoft/rushstack/ repo on `master`
- Ran `rush install` with this build of `rush-lib` in a https://github.com/microsoft/rushstack/ repo on `master`
- Ran `rush rebuild` with this build of `rush-lib` in a https://github.com/microsoft/rushstack/ repo on `master` 
- Ran `rush unlink` with this build of `rush-lib` in a https://github.com/microsoft/rushstack/ repo on `master` 
- Error message, but …
> [rush] Convert remaining code in Rush to async/await

- apps/api-documenter/src/documenters/YamlDocumenter.ts
- apps/api-documenter/src/utils/ToSdpConvertHelper.ts
- apps/api-documenter/src/yaml/ISDPYamlFile.ts
- common/changes/@microsoft/api-documenter/sdp_2020-12-07-03-27.json
office team ts/js reference content use api-documenter tool to generate yaml for build system to build.
now, new build system released. need to update api-documenter to generate new content structure of yaml .
this is our feature:  https://dev.azure.com/ceapex/Engineering/_workitems/edit/244513
To reduce the maintaining effort for the legacy processor and unblock docfx v3 new pipeline onboarding,  this pr aims to switch to use SDP for ts/js reference content. 
TS schema: 
https://github.com/microsoft/templates.docs.msft/tree/master/ContentTemplate/schemas
files that name start with TS.
target repo: https://github.com/OfficeDev/office-scripts-docs-reference
1. build new api-documenter
2. download repo
2. rename docs/docs-ref-autogen to docs/docs-ref-autogen-backup
3. change …
> [api-documenter] generate sdp yaml instead of udp yaml

- apps/rush-lib/src/logic/buildCache/AzureStorageBuildCacheProvider.ts
- common/changes/@microsoft/rush/ianc-fix-sas_2020-12-25-00-37.json
This PR fixes a few issues with the way the Azure Storage SAS was generated. Namely:
- The parameter names must be the abbreviations listed [here](https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas)
- The container "write" permission is required for creating new blobs instead of the "create" permission
> [Rush] Fix an issue with generation of Azure Storage SAS.

- apps/rush-lib/src/api/BuildCacheConfiguration.ts
- apps/rush-lib/src/api/RushGlobalFolder.ts
- apps/rush-lib/src/api/RushUserConfiguration.ts
- apps/rush-lib/src/cli/actions/UpdateCloudCredentials.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/logic/CredentialCache.ts
- apps/rush-lib/src/logic/RushConstants.ts
- apps/rush-lib/src/logic/buildCache/AzureStorageBuildCacheProvider.ts
- apps/rush-lib/src/logic/buildCache/FileSystemBuildCacheProvider.ts
- apps/rush-lib/src/logic/buildCache/test/AzureStorageBuildCacheProvider.test.ts
- apps/rush-lib/src/schemas/rush-user-configuration.schema.json
- apps/rush-lib/src/schemas/rush-user-settings.schema.json
- apps/rush-lib/src/utilities/Utilities.ts
- common/changes/@microsoft/rush/ianc-user-config-file_2020-12-22-07-45.json
This is one of the TODO items listed in https://github.com/microsoft/rushstack/issues/2393#issuecomment-748699361
This change introduces an `~/.rushrc.json` file that allows a `"buildCacheFolder"` to be specified. If this is provided, the cache is stored in this location instead of in each repo's `/common/temp/build-cache` folder.
> [rush] Add support for specifying a system-wide build cache location.

- apps/rush-lib/src/api/BuildCacheConfiguration.ts
- apps/rush-lib/src/cli/actions/UpdateCloudCredentials.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/logic/buildCache/CacheEntryId.ts
- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- apps/rush-lib/src/logic/buildCache/test/CacheEntryId.test.ts
- apps/rush-lib/src/logic/buildCache/test/__snapshots__/CacheEntryId.test.ts.snap
- apps/rush-lib/src/schemas/build-cache.schema.json
- common/changes/@microsoft/rush/ianc-customize-cache-entry-names_2021-01-06-07-56.json
This PR introduces a `cacheEntryNamePattern` to `common/config/rush/build-cache.json` to allow the cache entry IDs to be configured.
This field allows for patterns containing alphanumeric characters, slashes, underscores, and hyphens and tokens `[hash]` (which is replaced with the project state hash), `[projectName]` (which is replaced with the project's package name), and `[projectName:normalized]` (which is replaced with the project's package name, but with `/` characters replaced with `+` characters).
> [rush] Allow the cache entry name to be configured.

- apps/rush-lib/src/logic/TaskSelector.ts
- common/changes/@microsoft/rush/ianc-fix-missing-command-error_2021-01-08-03-41.json
This is a mistake I made here: https://github.com/microsoft/rushstack/pull/2421
> [rush] Fix an issue where an empty (but not missing) script would always result in an error.

- common/changes/@microsoft/gulp-core-build-serve/keco-gulp4-compat_2021-01-12-20-30.json
- core-build/gulp-core-build-serve/src/ReloadTask.ts
- core-build/gulp-core-build-serve/src/ServeTask.ts
Gulp 4 throws an error at runtime for empty string as glob argument. This change resolves those errors.
```shell
[12:05:52] Starting 'serve-deprecated'...
[12:05:52] Starting gulp
[12:05:52] Starting subtask 'configure-sp-build-rig'...
[12:05:52] Finished subtask 'configure-sp-build-rig' after 11 ms    
[12:05:52] Starting subtask 'record-build-metadata'...
[12:05:52] Finished subtask 'record-build-metadata' after 290 μs    
[12:05:52] Starting subtask 'record-start-time-metadata'...
[12:05:52] Finished subtask 'record-start-time-metadata' after 273 μs
[12:05:52] Starting subtask 'spfx-serve'...
[12:05:52] [spfx-serve] To load your scripts, use this query string: ?debug=true&noredir=true&debugManifestsFile=https://localhost:4321/temp/manifests.js
[12:05:53] Starting server...
[12:05:53] …
```
> Gulp 4 compatibility: No longer pass empty string as glob argument for ServeTask and ReloadTask

- apps/rush-lib/assets/rush-init/rush.json
- common/changes/@microsoft/rush/update-init-template_2021-01-08-02-53.json
when `rush init` the default pnpm version is 4, this PR try to update to use the latest version of pnpm
> [rush-init] update template pnpm to latest version

- apps/heft/includes/jest-shared.config.json
- common/changes/@rushstack/heft/octogonz-jest-coverage-globs_2021-01-15-23-48.json
- common/changes/@rushstack/heft/octogonz-jest-coverage-globs_2021-01-21-02-07.json
- tutorials/heft-node-jest-tutorial/config/jest.config.json
We recently encountered two issues with Jest code coverage using Heft's **jest-shared.config.json**:
1. Code coverage was NOT being tracked for product code files (e.g. `src/Example.ts`) if they were not part of the transitive closure of files imported by `*.test.ts`.
2. Code coverage WAS being tracked for test helpers (e.g. `src/test/TestUtils.ts` or `src/__mocks__/ExampleClass.ts`)
Some people advocated that #2 may be a desirable behavior, because it identifies dead code in unit test files.  However in my opinion it also brings a couple downsides:
- It may skew the overall code coverage statistics (i.e. counting coverage of files that don't matter)
- Code coverage is notorious for annoying edge cases; it may be a nuisance to deal with this in non-shipping code
- Test helpers such as …
> [heft] Update jest-shared.config.json to specify "collectCoverageFrom"

- apps/rush-lib/src/logic/deploy/DeployArchiver.ts
- common/changes/@microsoft/rush/user-danade-FixZipPathing_2021-01-21-03-16.json
Zip files from `rush deploy` were created with the host machine's pathing format in mind. This fix converts backslashes to forward slashes prior to adding to the archive.
> [rush] Use forward slashes when creating deploy zip file for Unix compatibility

- apps/heft/src/plugins/Webpack/WebpackPlugin.ts
- common/changes/@rushstack/heft/ianc-fix-webpack-serve-issue_2021-01-22-05-14.json
There is an issue with the way `heft start` calls webpack. It causes the "bundle" step to resolve too quickly and move on to the post-build step before webpack has dropped files on disk.
We had been waiting for the first devserver request. This PR changes that behavior to wait until the webpack compilation's "done" hook fires.
This was tested in a SPFx project compilation that has complex post-build steps that rely on files to exist in "dist."
> Fix an issue with webpack in "heft start" mode where "bundle" would continue too quickly.

- apps/rush-lib/assets/rush-init/rush.json
- common/changes/@microsoft/rush/octogonz-upgrade-pnpm_2021-01-22-19-08.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- rush.json
From the [PNPM changelog](https://github.com/pnpm/pnpm/blob/main/packages/pnpm/CHANGELOG.md):
> ## 5.15.0
> 
> ### Minor Changes
> 
> - Allow to specify the shell target when configuring autocompletion with `pnpm install-completion`. For instance: `pnpm install-completion zsh`.
> - New option added: `enable-modules-dir`. When `false`, pnpm will not write any files to the modules directory (node_modules). This is useful for when the modules directory is mounted with filesystem in userspace (FUSE). There is an experimental CLI that allows to mount a modules directory with FUSE: [@pnpm/mount-modules](https://www.npmjs.com/package/@pnpm/mount-modules).
> 
> ### Patch Changes
> 
> - Fixed a performance regression that was caused by [#3032](https://github.com/pnpm/pnpm/pull/3032) and shipped in …
> Upgrade to PNPM 5.15.2

- apps/rush-lib/src/cli/actions/WriteBuildCacheAction.ts
- apps/rush-lib/src/logic/buildCache/FileSystemBuildCacheProvider.ts
- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- common/changes/@microsoft/rush/ianc-improve-write-build-cache-logging_2021-01-12-01-18.json
Logging messages for write-build-cache are not clear, especially in the case when caching isn't supported for a project.
This PR adds a `--verbose` flag to `write-build-cache`, and includes a logging message in the case that the project doesn't support caching.
> [rush] Improve logging for write-build-cache.

- apps/rush-lib/src/cli/actions/InstallAction.ts
- apps/rush-lib/src/cli/actions/UpdateAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/logic/PackageJsonUpdater.ts
- apps/rush-lib/src/logic/base/BaseInstallManager.ts
- apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
- common/changes/@microsoft/rush/from-flag_2021-01-13-20-47.json
My first real PR to rush, finally. ❤️ 
I added support for `--from`-based installs using `rush install`, currently there is only support for `--to`, and the change was trivial to make, following pnpm workspaces documentation here: https://pnpm.js.org/en/filtering#filter-lt-package_name-
Fixes #2434
In my org, we want to install/build/test only the changed projects in our CI, which we are accomplishing with the `--to` flag. However, we see that if we change a widely used package, we want to build and test all the dependents of that package when it gets changed, and publish those packages as well. Hence we have a need for the `--from` flag for `rush install`, a flag already present in the other rush commands we use around building things.
I created an alias called `testrush` locally on my …
> [rush] Add `--from` to `rush install`

- apps/rush-lib/assets/rush-init/rush.json
- apps/rush-lib/src/api/RushConfigurationProject.ts
- apps/rush-lib/src/cli/actions/PublishAction.ts
- apps/rush-lib/src/schemas/rush.schema.json
- common/changes/@microsoft/rush/feat-publish-folder_2020-12-16-21-26.json
- common/reviews/api/rush-lib.api.md
Add a new project configuration that allows to customize the folder that will be used during the `rush publish` process.
By default that configuration will be equal to the `projectFolder` value.
~~This implementation only works with pnpm workspace, the trick is to create a temporal project in the workspace for each project that will get published and uses the new `publishFolder` setting, run the publish command on the subfolder and then remove the temporal project.~~
~~This temporal projects are required because the packages being published must be part of the workspace and have the dependencies installed. Thanks to pnpm cache and linking, the process is really fast.~~
- Changed the settings for `@microsoft/api-documenter` to use the new `publishFolder` setting as `dist`
- Copy the …
> [rush-lib] Add publishFolder settings to project configuration

- apps/rush-lib/src/logic/installManager/RushInstallManager.ts
- common/changes/@microsoft/rush/octogonz-rush-install-issue-2460_2021-01-29-23-28.json
Fixes https://github.com/microsoft/rushstack/issues/2460
See issue for details.
I reproed this using the `rush-example` repo, then confirmed that my PR fixed the repro. 
I also confirmed that it fixes the real HBO repo where we originally encountered the problem.
I didn't test NPM/Yarn, but this code reuses the `shrinkwrapFile.getTempProjectNames()` collection that is already used by `_findOrphanedTempProjects()`, so it should be safe.
> [rush] "Cannot get dependency key for temp project" error during "rush install"

- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- common/changes/@microsoft/rush/ianc-fix-cache-check_2021-01-29-23-59.json
After a refactor, code that detects files that are both listed as cached build output and are tracked by git doesn't iterate over an array correctly.
This PR fixes the array iteration.
Tested on this repo by adding a file under `rush-lib/lib` to be tracked by git and running a cached build.
> [rush] Fix an issue where an array is incorrectly iterated over.

- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- apps/rush-lib/src/logic/taskRunner/TaskRunner.ts
- common/changes/@microsoft/rush/octogonz-rush-cache-messages_2021-02-05-02-25.json
Update some strings.
The wording of this console message was bugging me:
```
==[ @rushstack/eslint-plugin-security ]===========================[ 4 of 19 ]==
@rushstack/eslint-plugin-security was provided by cache.
==[ @rushstack/eslint-plugin-packlets ]===========================[ 5 of 19 ]==
@rushstack/eslint-plugin-packlets was provided by cache.
==[ @rushstack/eslint-config ]====================================[ 6 of 19 ]==
@rushstack/eslint-config was skipped.
==[ @rushstack/node-core-library ]================================[ 7 of 19 ]==
"@rushstack/node-core-library" completed successfully in 11.01 seconds.
```
Without an article, "was provided by cache" sounded cave manny.  :-)  
The revised message is:
```
==[ @rushstack/eslint-plugin-security ]===========================[ 4 of 19 …
```
> [rush] Update some console log messages

- apps/heft/src/startWithVersionSelector.ts
- apps/rundown/.vscode/launch.json
- apps/rundown/src/launcher.ts
- apps/rush-lib/src/logic/pnpm/PnpmfileShim.ts
- apps/rush-lib/src/scripts/create-links.ts
- apps/rush-lib/src/utilities/test/Npm.test.ts
- common/changes/@microsoft/rush/octogonz-rundown-fix_2021-02-09-23-58.json
- common/changes/@rushstack/heft/octogonz-rundown-fix_2021-02-10-00-08.json
- common/changes/@rushstack/node-core-library/octogonz-rundown-fix_2021-02-09-23-58.json
- common/changes/@rushstack/rundown/octogonz-rundown-fix_2021-02-09-23-58.json
- common/changes/@rushstack/rundown/octogonz-rundown-fix_2021-02-10-00-58.json
- common/changes/@rushstack/terminal/octogonz-rundown-fix_2021-02-09-23-58.json
- libraries/node-core-library/src/EnvironmentMap.ts
- libraries/node-core-library/src/test/EnvironmentMap.test.ts
- libraries/terminal/src/StdioWritable.ts
I didn't analyze it very closely, but it seems like this was a regression introduced when PR  #2237 enabled `esModuleInterop` in the rig.  The `import * from process` works correctly /except/ if you access static members of the `process` API.
The `esModuleInterop`  feature is a land mine because the compiler does not catch incorrect imports.  They simply fail at runtime.  Maybe we should make an ESLint rule to catch these mistakes.  
Confirmed that the `rundown` tool doesn't crash with this fix.
> [rundown] Fix an error "process.on() is not a function"

- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- common/changes/@microsoft/rush/disable-cache-during-watch_2021-02-11-19-45.json
Disables the build cache feature during after the initial build with `--watch` finishes. This is for the following reasons:
- Prevent Rush from deleting and recreating files by rehydrating from cache, which tends to break downstream file watchers, such as `webpack --watch`
- Avoid the CPU overhead of writing to the local build cache
- Avoid the disk usage of creating new local build cache entries every time a change occurs
Works by removing awareness of the build cache from the build process after the first build finishes.
Will reduce performance if the developer reverts to a prior build state during a `--watch` process, since this will now require a build instead of a cache hit.
`rush build --watch` on the `rushstack` repo, changing files in `package-deps-hash` and reverting said …
> [rush-lib] Disable build cache feature in `--watch` after initial build

- apps/rush-lib/assets/rush-init/common/config/rush/command-line.json
- apps/rush-lib/src/api/CommandLineJson.ts
- apps/rush-lib/src/cli/RushCommandLineParser.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/schemas/command-line.schema.json
- common/changes/@microsoft/rush/reconfigure-watch_2021-02-13-00-01.json
Since downstream file watchers (e.g. webpack, jest) have problems with watched files being deleted and recreated, and there is a common habit of having `npm run build` clean the output directories, requires that enabling "watch mode" is performed globally for a command, instead of being an addon to any existing command.
In `command-line.json`, specify `"watchForChanges": true` on a custom command of `"commandKind": "bulk"` to enable watch mode for the command.
Internal implementation of watch mode remains the same.
Modified `command-line.json` to temporarily declare "build" as a custom bulk command, with `"watchForChanges": true` and verified that this caused `rush build` to watch for changes.
> [rush] Change watch mode from the "--watch" CLI parameter to "watchForChanges": true in command-line.json

- apps/rush-lib/src/cli/SelectionParameterSet.ts
- apps/rush-lib/src/cli/actions/BaseRushAction.ts
- apps/rush-lib/src/cli/actions/InstallAction.ts
- apps/rush-lib/src/cli/actions/UpdateAction.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/logic/PackageJsonUpdater.ts
- apps/rush-lib/src/logic/base/BaseInstallManager.ts
- apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
- common/changes/@microsoft/rush/install-only_2021-02-14-08-13.json
Expands the set of selection parameters used by `rush install` to match those used by `rush build` and other bulk script actions.
See [selecting subsets of projects](https://rushjs.io/pages/developer/selecting_subsets/)
Factors out the selection parameters and selection logic into a separate `SelectionParameterSet` component, so that it can be used in both `BulkScriptAction` and `InstallAction`, whose common ancestor is shared by actions for which selection parameters are not applicable.
Adds the following command line parameters to `rush install`:
`--only`: Install only the declared dependencies of the specified project
`--impacted-by`: Install the dependencies of the specified project and all projects that depend on it. Same as what `--from` previously did. Unsafe. …
> [rush] Normalize selection CLI parameters for "rush install"

- apps/rush-lib/assets/rush-init/common/config/rush/command-line.json
- apps/rush-lib/src/api/CommandLineJson.ts
- apps/rush-lib/src/api/RushProjectConfiguration.ts
- apps/rush-lib/src/cli/RushCommandLineParser.ts
- apps/rush-lib/src/cli/actions/WriteBuildCacheAction.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/cli/test/repo/common/config/rush/experiments.json
- apps/rush-lib/src/logic/TaskSelector.ts
- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- apps/rush-lib/src/logic/taskRunner/BaseBuilder.ts
- apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts
- apps/rush-lib/src/logic/taskRunner/TaskRunner.ts
- apps/rush-lib/src/logic/taskRunner/test/TaskRunner.test.ts
- apps/rush-lib/src/schemas/command-line.schema.json
- apps/rush-lib/src/schemas/rush-project.schema.json
- common/changes/@microsoft/rush/ianc-more-cache-options_2021-02-15-00-57.json
- common/changes/@microsoft/rush/ianc-more-cache-options_2021-02-15-00-58.json
- common/changes/@microsoft/rush/ianc-more-cache-options_2021-02-15-00-59.json
This PR adds a `--disable-cache` CLI flag to bulk actions, adds a `"disableCache"` option to bulk commands in the `command-line.json` schema, and adds the following options to the `rush-project.json` schema:
```JS
{
"cacheOptions": {
"disableCache": true, // (defaults to false)
"optionsForCommands": [
{
"name": "<command name>",
"disableCache": true // (defaults to false)
}
]
}
}
```
> [rush] Add the ability to disable cache in certain scenarios.

- apps/rush-lib/assets/rush-init/common/config/rush/artifactory.json
- common/changes/@microsoft/rush/octogonz-rush-artifactory-error_2021-02-17-02-18.json
- common/config/rush/version-policies.json
After running `rush init`, an error is reported for the **artifactory.json** config file because the `registryUrl` field is "required" but not specified.  Artifactory is initially disabled, so the user shouldn't be expected to assign this setting.
Run `rush init` and confirm there is no error.
> [rush] Fix a minor issue with the "rush init" template

- apps/rush-lib/src/logic/NodeJsCompatibility.ts
- apps/rush/src/start.ts
- common/changes/@microsoft/rush/master_2021-02-13-03-35.json
We received feedback that some projects are still supporting Node.js 8.x, even though it officially reached end-of-life for support in December 2020.
PR #2406 changed Rush to reports a hard error and terminate for Node.js 8.x.  Some investigation shows that Node 10 didn't introduce any new APIs that are likely to cause compatibility issues for our code base.  So this PR reverts the version check to 8.9.0.   I also clarified the function names/comments to help us make this decision in the future.
I can't easily test this because in order to run the PR branch under Node 8, I need to run `rush install` with Node 8 (because of native dependencies I assume -- simply running `node rush-lib/lib/start.js` weirdly terminates with no error message).  But Rush and PNPM both require Node 10 …
> [rush] Enable support for Node.js 8.x again

- apps/rush-lib/src/logic/setup/SetupPackageRegistry.ts
- common/changes/@microsoft/rush/octogonz-rush-setup-npm7_2021-02-20-06-21.json
The `rush setup` command relies on the `--json` CLI parameter for NPM, which is currently broken in NPM 7.x.  (See [NPM issue #2740](https://bit.ly/3scrV1b))
With NPM 7.x we get output like this:
```
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
{
"error": {
"code": "E404",
"summary": "Not Found - GET https://registry.npmjs.org/@rushstack%2fnonexistent-package - Not found"
}
}
npm ERR! A complete log of this run can be found in:
```
...when we're supposed to get output like this:
```
{
"error": {
"code": "E404",
"summary": "Not Found - GET https://registry.npmjs.org/@rushstack%2fnonexistent-package - Not found"
}
}
```
The workaround is to search for the first line starting with `{` and the last line ending with `}` and parse that …
> [rush] Fix "rush setup" incompatibility with NPM 7.x

- apps/rush-lib/src/logic/pnpm/PnpmProjectDependencyManifest.ts
- common/changes/@microsoft/rush/user-danade-FixProjectDependencyManifest_2021-02-21-00-26.json
Fixes #2227 
After looking at the issue specified above, as well as the repro produced by @chengcyber (thank you!!), I determined that the bug was being caused by a chained peer dependency within Jest, eventually resulting in a dependency on ts-node 8.10.2 as specified on the Rush project that was attempting to be installed. The per project manifest generator (that produces `shrinkwrap-deps.json`) was crawling through peer dependencies to determine the version of the package actually consumed, so as to add the integrity hash to the shrinkwrap, however it couldn't find the required dependency because it was aquired through a chained peer dependency, which the generator did not expect, causing generation and thus linking to fail.
After thinking on it, I came to the conclusion that Rush …
> [rush] Remove Rush's own validation of the PNPM lockfile

- apps/rush-lib/src/logic/TaskSelector.ts
- common/changes/@microsoft/rush/fix-dependency-gaps_2021-02-23-01-55.json
Accounts for indirect dependency relationships between projects when running `rush build` with selection commands that exclude intervening dependencies.
Fixes #2507.
When adding dependency relationships in `TaskSelector`, dependencies on projects that are not part of the selection will now be expanded to their dependencies, etc.
Ran `rush build -o rush -o terminal` and verified that `@rushstack/terminal` now builds before `@microsoft/rush`.
> [rush] Fix dependency gaps

- apps/rush-lib/src/logic/buildCache/FileSystemBuildCacheProvider.ts
- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts
- apps/rush-lib/src/utilities/TarExecutable.ts
- common/changes/@microsoft/rush/ianc-faster-tar_2021-02-15-05-38.json
Currently, Rush uses the `tar` NPM package to create and extract cache entries. This works well, but isn't as fast as `tar` executable. This PR adds the ability to use `tar` if it is on the PATH.
I've tested this on two repos: this one (rushstack) and a large internal repo. Things work fine, and archives created with older versions of Rush are able to be read by Rush with these changes, and vise-versa.
For the rushstack repo, restoring from cache took 8.23 seconds before, and now takes 3.05 seconds. In the large internal repo, restoring from cache took 10 minutes and 51.1 seconds, and now takes 1 minute and 35 seconds.
> [rush] Improve cache read/write perf by attempting to use the "tar" binary.

- apps/rush-lib/src/cli/actions/WriteBuildCacheAction.ts
- apps/rush-lib/src/logic/PackageChangeAnalyzer.ts
- apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts
- common/changes/@microsoft/rush/ianc-fix-non-git-build_2021-02-25-23-11.json
Fixes https://github.com/microsoft/rushstack/issues/2505
There was an issue in `PackageChangeAnalyzer` where if Git wasn't present, it would report that the project contained no tracked files instead of returning `undefined`. This caused the incremental build feature and the build cache feature to believe that nothing was changed.
Tested by building this repo both with and without Git on the PATH.
> [rush] Fix an issue where Rush would fail to restore from cache but report success when Git isn't present.

- apps/heft/src/plugins/CopyStaticAssetsPlugin.ts
- apps/heft/src/schemas/anything.schema.json
- common/changes/@rushstack/heft/ianc-fix-output-dir_2021-03-02-06-50.json
Fixes https://github.com/microsoft/rushstack/issues/2513
We had "lib" hardcoded as the default output folder for the `CopyStaticAssetsPlugin`. This PR changes that to instead gets that folder from the `compilerOptions.outDir` property in `tsconfig.json`
Tested on this repo and on https://github.com/xc2/GithubIssues/tree/main/heft-issue-staticAssetsToCopy
> [heft] Remove the hardcoded "lib" static assets output folder name

- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- common/changes/@rushstack/heft/ianc-dont-run-ae-on-compiler-failure_2021-03-02-22-56.json
Fixes https://github.com/microsoft/rushstack/issues/2478
This changes the `TypeScriptBuilder` to throw an exception if the TypeScript compilation reports any errors.
Tested by following the repro steps in https://github.com/microsoft/rushstack/issues/2478.
> Fix an issue where build would continue even if TS reported errors.

- apps/rush-lib/src/logic/RepoStateFile.ts
- apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
- apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
- common/changes/@microsoft/rush/ianc-merge-conflict-repo-state_2021-03-07-03-36.json
- common/reviews/api/rush-lib.api.md
When the `preventManualShrinkwrapChanges` option in `rush.json` is turned on, the `repo-state.json` file contains a hash of the shrinkwrap file. Whenever a merge conflict is encountered in the shrinkwrap file, one is almost guaranteed to occur in `repo-state.json`. PNPM gracefully handles merge conflicts in the `pnpm-lock.yaml` file, and this PR adds that same graceful handling to `repo-state.json` when the user runs `rush update`.
This change detects a merge conflict marker in `repo-state.json` and marks the file as "not valid," but doesn't throw an exception if `rush update` is being run.
I intentionally caused a merge conflict in `repo-state.json` and ran `rush update` (with the changes in this PR) on that repo. I also tested that `rush install` and `rush update` still work as expected …
> [rush] Allow merge conflicts in repo-state.json to be automatically resolved.

- apps/rundown/src/Rundown.ts
- apps/rush-lib/package.json
- apps/rush-lib/src/api/BuildCacheConfiguration.ts
- apps/rush-lib/src/logic/buildCache/AmazonS3BuildCacheProvider.ts
- apps/rush-lib/src/logic/buildCache/AzureStorageBuildCacheProvider.ts
- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- apps/rush-lib/src/logic/buildCache/test/AmazonS3BuildCacheProvider.test.ts
- apps/rush-lib/src/logic/buildCache/test/__snapshots__/AmazonS3BuildCacheProvider.test.ts.snap
- apps/rush-lib/src/logic/taskRunner/BaseBuilder.ts
- apps/rush-lib/src/schemas/build-cache.schema.json
- apps/rush-lib/src/utilities/Utilities.ts
- apps/rush-lib/tsconfig.json
- common/changes/@microsoft/rush/aws-build-cache_2021-02-09-16-23.json
- common/changes/@rushstack/heft-node-rig/aws-build-cache_2021-02-09-16-23.json
- common/changes/@rushstack/module-minifier-plugin/aws-build-cache_2021-02-09-16-23.json
- common/changes/@rushstack/rundown/aws-build-cache_2021-02-09-16-23.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/pnpmfile.js
- common/config/rush/repo-state.json
- rigs/heft-node-rig/package.json
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.ts
- webpack/module-minifier-plugin/src/workerPool/WebpackWorker.ts
- webpack/module-minifier-plugin/src/workerPool/WorkerPool.ts
AWS adapter for #2393. Build output can be cached in and fetched from an S3 bucket.
Uses aws-sdk-js-v3, which has some unfortunate characteristics:
* It's not as big as v2, but still adds ~15 MB
* Supports browsers and React Native, bringing in some otherwise unnecessary dependencies in order to do so.
* * I've overridden the worst offenders in pnpmfile.js.
* * I've set `skipLibCheck` in tsconfig.json, to work around the fact that AWS SDK types are often a union of Node, DOM, and React Native types, while we only want to know about Node types.
* Relies on some TypeScript 4 features.
* * I've upgraded and made some minor fixes across the repo.
I haven't implemented the `--interactive` flag, except for providing a somewhat useful error message. I don't know of any flows (similar to the …
> [rush-lib] Add AWS support for build cache feature

- apps/rush-lib/package.json
- apps/rush-lib/src/logic/buildCache/AmazonS3BuildCacheProvider.ts
- common/changes/@microsoft/rush/octogonz-issue-2547_2021-03-12-01-37.json
- common/config/rush/version-policies.json
Mitigates https://github.com/microsoft/rushstack/issues/2547
The problematic dependency is eliminated.  The feature is still partially usable via the RUSH_BUILD_CACHE_WRITE_CREDENTIAL environment variable.
> [rush] Disable the AWS credential provider logic to mitigate a problematic peer dependency

- apps/rush-lib/assets/rush-init/common/config/rush/experiments.json
- apps/rush-lib/src/api/ExperimentsConfiguration.ts
- apps/rush-lib/src/logic/RepoStateFile.ts
- apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
- apps/rush-lib/src/schemas/experiments.schema.json
- common/changes/@microsoft/rush/reduce-importer-conflicts_2021-03-12-00-30.json
- common/reviews/api/rush-lib.api.md
The `preventManualShrinkwrapChanges` option for PNPM is useful for avoiding integrity problems in the pnpm-lock.yaml file in the event of bad merges, but it is more aggressive than it needs to be, in that it blocks both changes to the set of external package versions and to the set of references from each project. The latter is an area where developers generally know how to resolve merge conflicts correctly (it's the same as fixing them in package.json), and also accounts for a significant portion of the changes to pnpm-lock.yaml made during the course of normal developer activity (over 50% in our repos).
Adds an experiment `omitImportersFromPreventManualShrinkwrapChanges` that applies manual shrinkwrap change prevention only to the "packages" section of the lockfile, allowing the …
> [rush] Omit importers section from manual shrinkwrap change prevention (experiment)

- apps/rush-lib/src/logic/RepoStateFile.ts
- apps/rush-lib/src/logic/base/BaseShrinkwrapFile.ts
- apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
- apps/rush-lib/src/logic/policy/ShrinkwrapFilePolicy.ts
- common/changes/@microsoft/rush/fix-lockfile-importer-experiment_2021-03-16-20-08.json
The code path for the preventManualShrinkwrapChanges validation policy during "rush install" was missed when the experiment was originally added, so running "rush update" would not alter the lockfile or the repo-state.json file, but a subsequent "rush install" from a clean state would fail.
Refactors how the parameter is passed to ensure that it is consistent between the validator and the repo-state.json generation.
Ran "rush update" using the built version in another repo.
Ran "rush purge" in said repo.
Ran "rush install" in said repo, verified success.
Manually modified the "importers" section in the lockfile and a corresponding package.json
Ran "rush purge" in said repo.
Ran "rush install" in said repo, verified success.
> [rush] Fix `rush install` when omitImportersFromPreventManualShrinkwrapChanges is active

- common/changes/@rushstack/ts-command-line/patch-1_2021-03-16-18-54.json
- libraries/ts-command-line/README.md
According to https://github.com/microsoft/rushstack/issues/1287 the correct way to execute a command is to either provide nothing to `execute()` or call it with `process.argv.slice(2)`.
```
await commandLineParser.execute(process.argv);
```
resulted in
```
error: argument "<command>": Invalid choice: /Users/jakubkisielewski/WebstormProjects/cli/node_modules/.bin/ts-node (choose from [prepare])
```
while
```
await commandLineParser.execute();
```
executes the command just fine
> [ts-command-line] fix Dynamic Model example in docs

- apps/heft/src/plugins/CopyFilesPlugin.ts
- apps/heft/src/plugins/CopyStaticAssetsPlugin.ts
- common/changes/@rushstack/heft/ianc-fix-copy-watch_2021-03-17-01-17.json
There is an issue where `heft build --watch` will crash when a file listed as a static asset to copy to the "lib" folder(s) is edited. This issue was introduced when support for automatically detecting the "lib" folder specified as the `outDir` in `tsconfig.json` was added. That path has to be resolved relative to the `tsconfig.json` file that specifies it, which may be a file specified in an `"extends"` property.
This PR adds a `resolvedDestinationFolderPaths` property to the `CopyFilesPlugin` copy operation descriptor which is preemptively resolved to an absolute path.
Tested by building a large project containing .scss files both in `--watch` and not in `--watch` mode.
> [heft] Fix an issue where heft would crash when copying static assets in --watch mode.

- apps/rush-lib/src/logic/buildCache/AzureStorageBuildCacheProvider.ts
- common/changes/@microsoft/rush/ianc-check-if-blob-exists_2021-02-15-18-50.json
We have a CI job that populates our Azure Storage cache. It occasionally fails if two jobs run at the same time and both try to upload the same blob cache entry to Azure.
This change checks if the blob exists right before trying to upload. If the blob exists, we'll consider the upload "successful" because it would have been filled from cache if it had existed when the project's build started.
> [rush] Don't try to upload a cache entry to Azure Storage if it already exists.

- apps/rush-lib/src/logic/buildCache/AzureStorageBuildCacheProvider.ts
- common/changes/@microsoft/rush/ianc-handle-azure-409_2021-03-17-07-52.json
Azure Storage returns a 409 error code if two simultaneous modifications occur on the same blob. This PR adds graceful handling to that case.
We have a CI job that populates our build cache and occasionally two jobs run at the same time, populating the same cache entry, causing warnings (which fail our build). This PR handles that case and treats it as success.
Manually created a write conflict to ensure this is handled correctly.
> [rush] Handle a 'conflict' error from Azure Storage.

- apps/rush-lib/src/logic/policy/PolicyValidator.ts
- common/changes/@microsoft/rush/ianc-allow-pnpm-to-handle-merge-conflicts_2021-03-18-22-07.json
PNPM is able to gracefully handle merge conflict markers in the `pnpm-lock` file, but that functionality during `rush update` was recently broken.
This change disables shrinkwrap validation when `rush update` is run as the validation result doesn't matter if the shrinkwrap is going to change.
Tested by running `rush update` on a large repo with a merge conflict in the `pnpm-lock` file.
> [rush] Don't validate the shrinkwrap when running 'rush update'

- apps/heft/README.md
- apps/heft/package.json
- common/changes/@rushstack/heft/octogonz-heft-readme-update_2021-03-19-19-01.json
> [heft] Update README.md

- common/changes/@rushstack/debug-certificate-manager/user-halfnibble-fix-certutil-path_2021-03-25-02-39.json
- libraries/debug-certificate-manager/src/CertificateManager.ts
Fixes bug resolving the path of certutil.exe on Windows.
The `runAsync` method produces an array of output on Windows machines:
```
[
'C:\\Windows\\System32\\certutil.exe',
'\r\n'
]
```
Currently, when running `.toString()` on this array, a string with a comma character (`,`) is generated, which leads to the invalid path of:
```
'C:\\Windows\\System32\\certutil.exe,'
```
I wrote a little script in to test it on Windows. 
```typescript
import { Terminal, ConsoleTerminalProvider } from '@rushstack/node-core-library';
import { CertificateManager, ICertificate } from './CertificateManager';
const terminal: Terminal = new Terminal(new ConsoleTerminalProvider());
const certificateManager: CertificateManager = new CertificateManager();
// tslint-disable-next-line: no-debugger
debugger; …
```
> [debug-certificate-manager] Fixes bug resolving the path of certutil.exe on Windows.

- common/changes/@rushstack/typings-generator/master_2021-03-28-23-37.json
- libraries/typings-generator/src/TypingsGenerator.ts
centralizes the logic of ignoring into the function that does the typing generation so all calls to the function will respect the ignore paths, also lazy loads the ignore paths
fixes #2577
@octogonz (my first contribution hopefully simple enough to get merged! hope to contribute lots as we plan to use this tool heavily!)
> [heft] fix(typings): don't generate typings from watched file if it's ignored

- apps/rush-lib/src/cli/actions/PublishAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- common/changes/@microsoft/rush/publish-flag-doc_2021-03-28-08-39.json
I've updated the `--publish` flag description so that it reflects the fact that a repository is not necessarily hosted on npmjs.org.
Diff:
```text
-p, --publish         If this flag is specified, applied changes will be 
-                         published to npm.
+                         published to the NPM registry.
```
```text
rush build
```
<details>
<summary>Note 1</summary>
With a fresh repository, I wanted to test the code but `rush build -t rush` failed on my WSL2 instance.
Maybe that's because there is a missing dependency in the chain?
```text
$ rush build -t rush
Rush Multi-Project Build Tool 5.41.0 - https://rushjs.io
Node.js version is 14.16.0 (LTS)
Starting "rush build"
Executing a maximum of 16 simultaneous processes...
==[ @rushstack/tree-pattern …
```
> [rush-lib] Update rush publish -p flag description

- apps/heft/src/plugins/JestPlugin/JestPlugin.ts
- apps/heft/src/plugins/JestPlugin/JestTypeScriptDataFile.ts
- common/changes/@rushstack/heft/ianc-fix-heft-error-messages_2021-03-31-01-46.json
Fix an error message that mentions an old path.
We moved config files from the `.heft` folder to the `config` folder, but this error message still mentions the `.heft` folder. This fixes that error message.
N/A
> [Heft] Fix an error message.

- apps/rush-lib/src/logic/SetupChecks.ts
- common/changes/@microsoft/rush/octogonz-ado-phantom-workaround_2021-04-01-01-14.json
Our Azure DevOps build agents always print this warning:
```
Starting "rush install"
Warning: A phantom "node_modules" folder was found. This defeats Rush's
protection against NPM phantom dependencies and may cause confusing build
errors. It is recommended to delete this folder:
"/home/vsts/work/node_modules"
```
The Azure DevOps agent installs the [vso-task-lib](https://www.npmjs.com/package/vso-task-lib) package in a top-level folder such as `/home/vsts/work/node_modules/vso-task-lib`.
I suspect it was intentionally a phantom dependency, i.e. so that any script in any folder could import that package. 
Interestingly, there is no `/home/vsts/work/package.json` file; it must simply get unzipped in that location.
In any case, this NPM package is now deprecated.  And the warning creates a …
> [rush] Eliminate "phantom node_modules" warning on Azure DevOps build agents

- apps/heft/src/index.ts
- apps/heft/src/stages/BuildStage.ts
- common/changes/@rushstack/heft/ianc-add-post-compile-hook_2021-04-02-22-07.json
- common/reviews/api/heft.api.md
Adds an `afterCompile` hook to the `build` command's `compile` substage.
> [heft] Add an 'afterCompile' build hook.

- common/changes/@rushstack/eslint-config/patch-1_2021-03-05-21-34.json
- common/changes/@rushstack/eslint-plugin-packlets/patch-1_2021-03-01-00-35.json
- common/changes/@rushstack/eslint-plugin-security/patch-1_2021-03-05-21-34.json
- common/changes/@rushstack/eslint-plugin/patch-1_2021-03-05-21-34.json
- stack/eslint-config/package.json
- stack/eslint-plugin-packlets/package.json
- stack/eslint-plugin-security/package.json
- stack/eslint-plugin/package.json
This plugin doesn't currently work under strict dependency linkers such as Yarn's PnP, because it uses `@typescript-eslint/experimental-utils` without actually declaring it as a dependency.
It just happens to work under a `node_modules` setup because other packages depend on it (`@typescript-eslint/eslint-plugin` probably).
Fixes #2518.
A couple examples of where it's required:
https://github.com/microsoft/rushstack/blob/a3e697d93e8fa7ad54bd2eeb7b10e8181d3a70df/stack/eslint-plugin-packlets/src/mechanics.ts#L4-L5
https://github.com/microsoft/rushstack/blob/a3e697d93e8fa7ad54bd2eeb7b10e8181d3a70df/stack/eslint-plugin-packlets/src/circular-deps.ts#L7-L8
Used's Yarn's `packageExtensions` config feature to override this manually in my repo, and got it working under PnP strict mode. See …
> [eslint plugins] Fix unlisted dependency on `@typescript-eslint/experimental-utils`

- apps/rush-lib/src/cli/actions/PublishAction.ts
- common/changes/@microsoft/rush/octogonz-rush-semver-metadata-fix_2021-04-08-00-05.json
SemVer supports an obscure (and generally deprecated) feature where "build metadata" can be
appended to a version.  For example if our version is `1.2.3-beta.4+extra567`, then `+extra567` is the
build metadata part.  
These versions cause "rush publish" to fail even if everything has already been published successfully.
The error:
```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://xxxxx - forbidden
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
```
What's happening:
1. `rush publish` checks to see if the package `1.2.3-beta.4+extra567` is published
2. The registry reports it as `1.2.3-beta.4` which does not match `1.2.3-beta.4+extra567`
3. So Rush tries to publish it again. …
> [rush] Fix "rush publish" handling of verisons with a SemVer build metadata suffix

- apps/heft/src/cli/actions/CustomAction.ts
- apps/rush-lib/src/cli/actions/ChangeAction.ts
- build-tests/heft-action-plugin/src/index.ts
- common/changes/@microsoft/gulp-core-build-serve/master_2021-04-08-01-57.json
- common/changes/@microsoft/rush/master_2021-04-08-01-57.json
- common/changes/@rushstack/heft/master_2021-04-08-01-57.json
- common/changes/@rushstack/localization-plugin/master_2021-04-08-01-57.json
- common/reviews/api/heft.api.md
- core-build/gulp-core-build-serve/README.md
- webpack/localization-plugin/src/interfaces.ts
This fixes all found instances of the typo `paramter`
And replaces it with `parameter`
I chose this as a "minor" change since it's just a typo, but it will break everyone with custom heft actions. So it's kind of major?
Not tested. I just did a regex replace and built the monorepo.
> Fix parameter typo

- apps/api-extractor-model/README.md
- common/changes/@microsoft/api-extractor-model/patch-1_2021-04-08-05-41.json
Just a small README typo fix! :)
> [api-extractor-model] Fix typo in api-extractor-model README

- apps/rush-lib/src/logic/Git.ts
- apps/rush-lib/src/logic/test/Git.test.ts
- common/changes/@microsoft/rush/octogonz-rush-change-ssh_2021-04-08-05-21.json
- common/config/rush/version-policies.json
The `rush change` command prints this warning for users who authenticate to GitHub using [SSH authentication](https://stackoverflow.com/questions/11041729/why-does-github-recommend-https-over-ssh):
```
Starting "rush change"
Unable to find a git remote matching the repository URL 
(https://github.com/YourOrg/YourProject.git). Detected changes are likely to 
be incorrect.
The target branch is origin/master
```
The problem is that **rush.json** typically specifies the repository URL using HTTPS syntax:
**rush.json**
```js
"repository": {
/**
* The URL of this Git repository, used by "rush change" to determine the base branch for your PR.
*
* The "rush change" command needs to determine which files are affected by your PR diff.
* If you merged or cherry-picked commits from the master branch …
```
> [rush] Fix "rush change" warning when used with GitHub SSH authentication

- apps/rush-lib/src/logic/deploy/DeployManager.ts
- common/changes/@microsoft/rush/stekycz-2551-includeDevDependencies_2021-03-13-23-00.json
Fixes #2551
I have the following options (already described in the issue)
1. devDeps of the main project only?
2. devDeps of the main project and all additionalProjectsToInclude as well?
3. devDeps of all projects managed by rush?
4. devDeps of all projects in the repository? (I guess this is not an option because rush cannot work with other projects than managed.)
5. devDeps of all packages installed? (This is the current behavior.)
I have chosen the 3rd option because it is easy to make without more code changes and also makes sense to solve the issue. Option 1 seems too strict IMO and option 2 would require more code changes but might perform better.
I did not test it so far. I will do so after your confirmation the solution makes sense.
I will run the command `rush deploy` for a …
> [rush-lib] Fix "rush deploy" to include devDependencies for rush projects only

- common/changes/@rushstack/eslint-plugin-packlets/octogonz-eslint-plugins-packlets-ts4_2021-04-10-00-58.json
- stack/eslint-plugin-packlets/src/DependencyAnalyzer.ts
The `@rushstack/packlets/circular-deps` rule did not work correctly with TypeScript 4.2
Fixes https://github.com/microsoft/rushstack/issues/2591
The reason is that the `DependencyAnalyzer` relies on an internal compiler API which was redesigned in TypeScript 4.2.  See https://github.com/microsoft/rushstack/issues/2591 notes for details.
1. Confirmed that  `@rushstack/packlets/circular-deps` rule now correctly detects a circular reference with TypeScript 4.2.4
2. Confirmed that  `@rushstack/packlets/circular-deps` rule will works with TypeScript 3.9.9 that we used before
3. Confirmed that no problems are reported if there are no circular references
> [eslint-plugin-packlets] Fix an incompatibility with TypeScript 4.2

- common/changes/@rushstack/heft-webpack5-plugin/pr-webpack5-caching-fix_2021-04-14-21-57.json
- heft-plugins/heft-webpack5-plugin/src/WebpackPlugin.ts
@iclanton webpack compiler needs to be closed in webpack 5 in order to write it's persistent cache.
as per: https://github.com/webpack/webpack/issues/12345
and example here: https://github.com/webpack/webpack/blob/master/lib/webpack.js#L125
(tangent: would be cool for heft to potentially get into the incremental webpack build game now that webpack allows it. setting up the cache is fairly simple, but invalidating it takes some customization that would warrant discussion.)
> [heft] fix(webpack): fix an issue with webpack 5 where persistent cache isn't saved

- apps/rush-lib/src/logic/buildCache/AmazonS3/AmazonS3Client.ts
- apps/rush-lib/src/logic/buildCache/AmazonS3/test/AmazonS3Client.test.ts
- apps/rush-lib/src/logic/buildCache/AmazonS3/test/__snapshots__/AmazonS3Client.test.ts.snap
- common/changes/@microsoft/rush/s3_2021-04-15-21-04.json
Improve support for S3 storage when enabling the build cache (feature added as part of conversation in https://github.com/microsoft/rushstack/issues/2393).
- Allow S3 buckets outside the default (us-east-1) region in AWS
- Support temporary credentials (generated using an IAM Profile or sts:assume-role)
When an S3 bucket is created outside the default region, the URL generated for presigning includes a region suffix (for example, `mybucket.s3-us-west-1.amazonaws.com`).  If this isn't taken into account, the signed request will not be valid and the request will return a `403`.
When the user's credentials are temporary credentials (generated by assuming a role or using an assigned IAM Profile), you need _three_ pieces of information and not 2: the key, the secret, and the session token. …
> [rush-lib] Improve support for S3 storage for the buildCache

- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- apps/rush-lib/src/utilities/TarExecutable.ts
- common/changes/@microsoft/rush/ianc-tar-logging_2021-04-19-19-34.json
This will help to investigate https://github.com/microsoft/rushstack/issues/2622
This PR adds functionality to create a `<project-root>/.rush/build-cache-tar.log` file when the native `tar` is invoked with the following format:
```
Start time: Mon Apr 19 2021 13:06:40 GMT-0700 (Pacific Daylight Time)
Invoking "C:\WINDOWS\system32\tar.exe -x -f E:\rush-cache\d18105f7f83eb610b468be4e2421681f4a52e44d"
======= BEGIN PROCESS OUTPUT =======
<output from tar>
======== END PROCESS OUTPUT ========
Exited with code "0"
```
It also prints this file path as part of the "tar exited with code X" warning.
Built locally with normal and with invalid `tar` arguments.
> [rush] Print a log file to "<project-root>/.rush/build-cache-tar.log" when the native "tar" is invoked for debugging purposes.

- apps/rush-lib/src/logic/base/BaseInstallManager.ts
- apps/rush-lib/src/logic/base/BaseLinkManager.ts
- apps/rush-lib/src/logic/base/BaseShrinkwrapFile.ts
- apps/rush-lib/src/logic/installManager/InstallHelpers.ts
- apps/rush-lib/src/logic/installManager/RushInstallManager.ts
- apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
- apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts
- apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
- apps/rush-lib/src/logic/test/ShrinkwrapFile.test.ts
- apps/rush-lib/src/scripts/install-run.ts
- apps/rush-lib/src/utilities/Utilities.ts
- common/changes/@microsoft/rush/user-danade-pnpm6_2021-04-14-21-22.json
Adds support for PNPM 6 in Rush!
- Fixes #2601 by using new path format to exploded tarball for local dependency
- Removes `pnpm-lock.yaml` modification of tarball integrity hashes for local projects in non-workspaces PNPM installs and replaces it with validation prior to running PNPM install
- Removes `pnpm-lock.yaml` shrinkwrap churn optimization in favor of built-in shrinkwrap churn optimization in PNPM
- Fixes #2602 where a bug in Rush caused double-quotes to be added in the `pnpm-lock.yaml` in some scenarios
- Only attempts to delete `pnpm-workspace.yaml` once instead of for each local package
`pnpm-lock.yaml` modification by Rush has been something that we have been attempting to remove for some time. With PNPM 6 using a new `pnpm-lock.yaml` format, this felt like a good time to …
> [rush] Support PNPM 6 and Removal of pnpm-lock.yaml Rewriting

- apps/rush-lib/src/logic/PackageChangeAnalyzer.ts
- apps/rush-lib/src/logic/test/PackageChangeAnalyzer.test.ts
- apps/rush-lib/src/logic/test/__snapshots__/PackageChangeAnalyzer.test.ts.snap
- common/changes/@microsoft/rush/change-analyzer-tests_2021-04-20-05-45.json
In preparation for some future changes to `PackageChangeAnalyzer`, I've done some (very light) refactoring in the code and rewritten the unit tests to cover most of the functionality in the class.  The goal is to make it easier to prove that future changes don't break the existing API.
- For callers of `PackageChangeAnalyzer`, the only change in this PR is that _constructing_ a PackageChangeAnalyzer no longer immediately queries the state of git (file system).  The methods `getPackageDeps` and `getProjectStateHash` are now "lazy-load" instead of "eager-load".  This change makes the class easier to reason about and write unit tests for.
- Unit tests now cover the two primary responsibilities of this class (one is to produce the list of dependencies relevant for each project, the other to …
> [rush-lib] Reorganize unit tests for PackageChangeAnalyzer

- apps/heft/src/plugins/TypeScriptPlugin/EmitFilesPatch.ts
- common/changes/@rushstack/heft/ianc-dont-double-patch_2021-04-21-01-11.json
Currently, if a project has multiple tsconfig-*.json files in the root, and you run `heft --debug build`, an exception will be thrown saying that 'EmitFilesPatch.install() cannot be called without first uninstalling the existing patch'. This PR fixes that.
When the `--debug` parameter is used, the TypeScript builder is not run in a subprocess. When multiple TypeScript builders are run, they use the same loaded instance of TypeScript. Whichever one is invoked first will patch TypeScript's emitter first. The second will then try to patch TypeScript and throw an exception.
This change checks if the instance of TS is the instance that we already patched, and returns early in that case.
Tested by running `heft --debug build --watch` on a project with a `tsconfig.json` and a …
> [heft] Fix an issue where an exception is thrown when running multiple TypeScript compilations in --debug mode

- apps/rush-lib/src/logic/pnpm/PnpmWorkspaceFile.ts
- common/changes/@microsoft/rush/fix-workspace-deletion_2021-04-21-18-17.json
Ensures that `rush install` does not throw an error if the last local install contained projects that have since been deleted upstream, and the user pulls latest changes and runs `rush install`
Skips reading the existing common/temp/pnpm-workspace.yaml file when constructing what the content is expected to be. Diffing at write time is still applied.
Used the rush version to reinstall in rushstack.
> [rush] Fix `rush install` after workspace projects have been deleted upstream

- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/api/packageManager/PnpmPackageManager.ts
- apps/rush-lib/src/logic/RushConstants.ts
- apps/rush-lib/src/logic/base/BaseInstallManager.ts
- apps/rush-lib/src/logic/installManager/RushInstallManager.ts
- apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
- common/changes/@microsoft/rush/user-danade-FixPnpmfile_2021-04-21-22-03.json
In preparing to use PNPM 6, it was determined that the new `.pnpmfile.cjs` filename is required when copying in the pnpmfile or creating our own shim pnpmfile in workspaces. This change updates Rush to copy `.pnpmfile.cjs` for PNPM 6 and above, and continues to use `pnpmfile.js` for below. Fixes #2629 
Tested by performing install and validating that `pnpm-lock.yaml` changes are included and correct in PNPM 6-enabled monorepo.
> [rush] Fix Rush to use new .pnpmfile.cjs filename in PNPM 6

- apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
- common/changes/@microsoft/rush/user-danade-FixPnpmfileExt_2021-04-22-22-16.json
The client pnpmfile was being copied in with a bad extension, causing PNPM 6 installs to be broken after purge of the temp dir.
In a repo with PNPM 6 installed.
> [rush] Fix bad clientPnpmfile extension on PNPM 6

- apps/heft/includes/jest-shared.config.json
- apps/heft/src/plugins/JestPlugin/JestPlugin.ts
- apps/heft/src/plugins/JestPlugin/JestTypeScriptDataFile.ts
- apps/heft/src/plugins/JestPlugin/jest-build-transform.ts
- apps/heft/src/plugins/TypeScriptPlugin/EmitFilesPatch.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptPlugin.ts
- apps/heft/src/plugins/TypeScriptPlugin/internalTypings/TypeScriptInternals.ts
- apps/heft/src/schemas/typescript.schema.json
- apps/heft/src/templates/typescript.json
- build-tests/heft-jest-reporters-test/config/jest.config.json
- build-tests/heft-jest-reporters-test/config/typescript.json
- common/changes/@rushstack/heft/heft-js-extension-override_2021-03-03-00-05.json
Adds two TypeScript configuration options:
- `emitCjsExtensionForCommonJS`
- `emitMjsExtensionForESModule`
Example use case:
Compile commonjs to `lib/**/*.cjs`
Compile esm to `lib/**/*.js`
Have Jest look for `.cjs` first, so that you can refer to files via deep imports and not need to use alias mappings.
Also relevant to node 14, in that it makes assumptions about files based on the .cjs, .mjs, or .js extension.
Added to the heft-jest-reporters-test to emit commonjs at lib/**/*.cjs and have Jest look for .cjs extensions first when resolving modules.
Verified the presence of the expected .cjs output files alongside the .js ESM files.
> [heft] Support emitting compiled files using ".cjs" for commonjs, ".mjs" for ECMAScript Modules, etc., within a single output folder

- apps/rush-lib/src/logic/InstallManagerFactory.ts
- common/changes/@microsoft/rush/user-danade-AllowPrereleasePnpm_2021-04-23-19-07.json
Allow prerelease versions of PNPM to be used when `useWorkspaces` is enabled.
Manually in node by validating a prerelease version using the existing package version check.
> [rush] Allow prerelease versions of PNPM in workspaces

- apps/rush-lib/src/logic/buildCache/AzureStorageBuildCacheProvider.ts
- common/changes/@microsoft/rush/build-cache-errors_2021-04-23-18-49.json
There are some corner cases while using the rush build cache feature that result in unhelpful error messages.  Improve error messages displayed to the user so they have more immediate direction.  (This PR focuses on the Azure Storage Blob provider.)
The `RestError` that can be thrown when reading the cache is now formatted with the status code and error code, in addition to error-specific detail, for example:
```
// Old message
Error getting cache entry from Azure Storage: RestError
// New message
Error getting cache entry from Azure Storage: RestError 409 PublicAccessNotPermitted
You need to configure Azure Storage SAS credentials to access the build cache.
Update the credentials by running "rush update-cloud-credentials",
or provide a SAS in the RUSH_BUILD_CACHE_WRITE_CREDENTIAL …
```
> [rush-lib] Improve user error messages for common credential issues

- common/changes/@rushstack/heft-webpack5-plugin/pr-upgrade-webpack-5_2021-04-26-17-07.json
- common/config/rush/common-versions.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- heft-plugins/heft-webpack5-plugin/package.json
Upgrade Webpack 5
The latest webpack fixes a regression where modules couldn't be resolved when they contained a # in the path. This was throwing a warning when using the new webpack persistent cache and causing rush build to fail.
Ran build with no failures
Side Note: Would it be possible to read the webpack module from the rig if it exists instead of forcing a version?
> Upgrade webpack 5

- apps/rush-lib/src/scripts/install-run.ts
- common/changes/@microsoft/rush/fix-windows-support-install-scripts_2021-04-20-23-21.json
Currently all Rush commands that involve the `install-run` scripts fail on Windows when the project's absolute path has a space (" ") on it.
This is caused by a limitation of Node.js's `spawn` method that cannot execute a binary using a path with spaces on it. The limitation is known, and the recommended path is to execute the binary on shell mode and wrap the path in double quotes to allow Windows shell (CMD) properly resolve the path.
My changes involve the detection of the failing case (space on path + Windows OS) and only in that case use the shell mode + quotes wrapping on the path.
In this way we ensure that only the case with issue will change and use shell mode, Linux and MacOS does not work if the path gets wrapped in quotes.
I build the project and copy the resulting …
> [rush-lib] Fix issue on Windows with paths that contains spaces

- apps/rush-lib/src/logic/base/BaseShrinkwrapFile.ts
- apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
- apps/rush-lib/src/logic/npm/NpmShrinkwrapFile.ts
- apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
- apps/rush-lib/src/logic/pnpm/PnpmWorkspaceFile.ts
- apps/rush-lib/src/logic/yarn/YarnShrinkwrapFile.ts
- common/changes/@microsoft/rush/user-danade-BetterModificationCheck_2021-04-27-01-23.json
A couple issues with the install state check were encountered recently in Rush workspaces:
- When only deletions are performed in package.json, the check would errantly allow for skipping install because we would only validate that the packages in package.json are present (and compatible) in the lockfile
- Merge issues in git repos that allow non-binary merge that became apparent after fixing a bug that would incidentally force merge conflicts (#2610)
The method used to determine whether or not the shrinkwrap is up-to-date was made to provide the same functionality as PNPM, which can be found here: [https://github.com/pnpm/pnpm/blob/main/packages/lockfile-utils/src/satisfiesPackageManifest.ts](https://github.com/pnpm/pnpm/blob/main/packages/lockfile-utils/src/satisfiesPackageManifest.ts) …
> [Rush] Use simpler and more accurate check before skipping installs in workspaces

- common/changes/@rushstack/debug-certificate-manager/ianc-remove-where-from-dcm_2021-04-29-23-04.json
- libraries/debug-certificate-manager/src/CertificateManager.ts
Someone encountered the opposite of this issue https://github.com/microsoft/rushstack/pull/2571, where `Executable.spawn` attempted to call `C:\\Windows\\System32\\certmgr.exe\r\n`. This PR hands off looking up the path to `certmgr` entirely to `Executable.spawn`.
`Executable.spawn` effectively has a JS implementation of the `where` command on Windows, so the way `CertificateManager` was looking up the resolved path to `certmgr` was unnecessary, and was causing problems in certain situations. This PR removes the `where` lookup and instead just uses `Executable.spawn`.
Tested locally on Windows. `certmgr` is correctly found and invoked.
> [debug-certificate-manager] Fix an issue where calling certmgr on Windows can sometimes fail to look up the executable's path correctly.

- build-tests/web-library-build-test/src/test.sass
- common/changes/@microsoft/gulp-core-build-sass/keco-use-sass_2021-05-07-05-03.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- core-build/gulp-core-build-sass/package.json
- core-build/gulp-core-build-sass/src/SassTask.ts
Addresses #1666. `node-sass` has been deprecated and `dart-sass` via `sass` is the recommended replacement moving forward.
> Warning: LibSass and Node Sass are deprecated. While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto Dart Sass.
> https://github.com/sass/node-sass/blob/master/README.md#node-sass
This change will remove `node-sass`'s `node-gyp` `postInstall` scripts from `gulp-core-build-sass` which can cause issues with future Node releases. It will allow for the use of newer SASS features such as the [@use](https://sass-lang.com/documentation/at-rules/use) keyword by third-party developers.
Based on my grep, first-party …
> Replace deprecated node-sass with sass in gulp-core-build-sass

- apps/heft/src/plugins/TypeScriptPlugin/EmitFilesPatch.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- common/changes/@rushstack/heft/user-ianc-fix-sourcemaps_2021-05-11-19-50.json
Currently there is an issue with the `"sources"` parameter in `.js.map` files emitted to `lib` folders by Heft. This PR fixes the relative paths emitted to that parameter.
Currently, the output to `/build-tests/heft-node-everything-test/lib/index.js.map` looks like this:
```JSON
{
"version": 3,
"file": "index.js",
"sourceRoot": "",
"sources": ["../../../src/index.ts"],
"names": [],
"mappings": ";AAAA,4FAA4F;AAC5F,2DAA2D;;;AAE3D;;GAEG;AACH,MAAa,SAAS;CAAG,CAAC,kCAAkC;AAA5D,8BAAyB",
"sourcesContent": [
"// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.\r\n// See LICENSE in the project root for license information.\r\n\r\n/**\r\n * @public\r\n */\r\nexport class TestClass {} // tslint:disable-line:export-name\r\n"
]
}
```
Notice that the path …
> [heft] Fix the relative path in the "sources" parameter in .js.map files

- apps/heft/src/plugins/JestPlugin/jest-build-transform.ts
- common/changes/@rushstack/heft/ianc-fix-heft-jest-transform-issue_2021-05-13-01-18.json
If the `.js` files in `lib` (or `lib-commonjs`) are missing the `//# sourceMappingURL=...` comments, the `jest-build-transform` transformer will erroneously return only the encoded sourcemap instead of the JS code + the sourcemap.
Heft currently assumes that the JS files it loads for its Jest transformer end with a `//# sourceMappingURL=...` comment. If that comment is missing, the transformer will incorrectly split the compiled JS and return only the encoded sourcemap, leading to a very confusing error.
This fix injects the comment if one doesn't exist, in addition to handling the case where the comment does exist.
Tested by replacing the `jest-build-transform.js` script in a repro experiencing this problem.
> [heft] Fix an issue where Heft would return only the sourcemap if the compiled .js file is missing the sourceMappingURL comment.

- apps/rush-lib/src/api/RushProjectConfiguration.ts
- apps/rush-lib/src/cli/actions/WriteBuildCacheAction.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/logic/PackageChangeAnalyzer.ts
- apps/rush-lib/src/logic/ProjectWatcher.ts
- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- apps/rush-lib/src/logic/buildCache/test/ProjectBuildCache.test.ts
- apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts
- apps/rush-lib/src/logic/test/PackageChangeAnalyzer.test.ts
- apps/rush-lib/src/schemas/rush-project.schema.json
- common/changes/@microsoft/rush/t3_2021-04-28-14-31.json
Implementation of https://github.com/microsoft/rushstack/issues/2618.  The intent is to allow each project (in its `rush-project.json` file) to optionally specify glob patterns that should be ignored when calculating project state, which in turn, will allow those files to be ignored for the purposes of incremental build watching, cloud build cache hits, etc.
The new option is called `incrementalBuildIgnoredGlobs`, and is interpreted as a dot-ignore file.
PR needs a little cleanup, but it does work (tested locally on our monorepo here and does exactly what I was hoping).  Hoping to get feedback before I finish up the PR, to make sure this approach makes sense.
The new model of `ConfigurationFile`, which helps define riggable / extendable configuration files, is all `async`-based and takes …
> [rush-lib] Ignore specified files when calculating project state hash

- apps/rush-lib/src/cli/RushXCommandLine.ts
- apps/rush-lib/src/utilities/Utilities.ts
- common/changes/@microsoft/rush/octogonz-rush-issue2695_2021-05-14-22-10.json
Fixes #2695
The test CLI was:
```bash
$ rushx action a b "c&d"
```
I tried this on Windows+CMD.exe and Linux+Bash and confirmed that the invoked `process.argv` matches what we would get from `npm run`.
On Linux we can also do:
```bash
$ rushx action a b\" c
```
**Update:** My implementation uses `JSON.stringify()` based on NPM's implementation.  Originally I was using a method based on PNPM's implementation, but I found that `pnpm run` does not properly escape the second case.
> [rush] Fix an issue where "rushx" CLI parameters were not escaped properly

- common/changes/@rushstack/node-core-library/json-file-undefined_2021-05-13-21-25.json
- common/reviews/api/node-core-library.api.md
- libraries/node-core-library/src/JsonFile.ts
- libraries/node-core-library/src/test/JsonFile.test.ts
- libraries/node-core-library/src/test/__snapshots__/JsonFile.test.ts.snap
Adds a configuration option `ignoreUndefinedValues` to the JsonFile serialization APIs to make their behavior consistent with `JSON.stringify()` for the common case of setting values to be discarded as `undefined`. This is generally preferred because the `delete` operator is notoriously bad for performance.
The underlying APIs already drop keys with `undefined` values, the JsonFile class added an extra validation layer in front of serialization that turned this standard behavior into an error. Passing `ignoreUndefinedValues: true` in the options simply turns off this extra validation and defers to `JSON.stringify()` or `jju.stringify()`.
Added unit test cases for keys with `undefined` as their value and the `ignoreUndefinedValues: true` option.
Edited: `dropUndefinedValues` -> …
> [node-core-library] Add `ignoreUndefinedValues` option to JsonFile serialization APIs

- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- common/changes/@rushstack/heft/ianc-check-for-nested-output-folders_2021-05-21-19-24.json
Addresses an issue identified in https://github.com/microsoft/rushstack/issues/2704.
Currently Heft silently misbehaves if TypeScript is configured to emit two different module kinds to nested folders (i.e. - esnext to `lib` and CommonJS to `lib/cjs`). This PR adds a check for that scenario and emits an error when it is encountered.
Tested by changing the [`outFolderName`](https://github.com/microsoft/rushstack/blob/master/build-tests/heft-webpack4-everything-test/config/typescript.json#L33) in `heft-webpack4-everything-test` to `lib/commonjs` and `lib` and verifying that there is an error.
> [heft] Emit an error if two different TypeScript module kinds are to be emitted to nested folders.

- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptPlugin.ts
- apps/heft/src/stages/BuildStage.ts
- common/changes/@rushstack/heft/user-danade-PrepareForJestPlugin_2021-05-27-23-11.json
- common/config/rush/common-versions.json
- common/reviews/api/heft.api.md
Add Jest data to the `IBuildProperties`, such that the `JestPlugin` can be split out from the parent `@rushstack/heft` package and into it's own.
In attempting to split the `JestPlugin` out into it's own package, we will need to set some build properties that can be passed through the `HeftSession` into the plugin. Since the split-out `JestPlugin` will need to build using the `heft-node-rig`, which itself will _also_ depend on `JestPlugin` (to include in the default rig), we need to make both `heft` and `heft-node-rig` be cyclic dependencies of the new package. This change is being made in advance of those changes (along with a publish run of `heft`) in order to prepare to split JestPlugin out.
Build and validation in PR. Change is simply adding (not moving) data to a new place that is …
> Add Jest data sourced from Typescript into the build properties

- apps/heft/src/plugins/NodeServicePlugin.ts
- common/changes/@rushstack/heft/octogonz-heft-start-fix_2021-06-01-18-08.json
`heft start` should launch the service.
`heft build --watch` should NOT launch the service.
Tested using a local project that encountered this issue.
> [heft] Prevent NodeServicePlugin from running with "heft build --watch"

- apps/rush-lib/src/cli/RushXCommandLine.ts
- apps/rush-lib/src/cli/test/Cli.test.ts
- apps/rush-lib/src/cli/test/repo/rush.json
- apps/rush-lib/src/cli/test/repo/rushx-not-in-rush-project/build.js
- apps/rush-lib/src/cli/test/repo/rushx-not-in-rush-project/package.json
- common/changes/@microsoft/rush/feat-add-rushx-project-check_2021-05-26-03-12.json
add check before rushx 
Before 'rushx' is executed, check wether current project is one of the projects from rush.json
should fail in project which is not in rush.json
> [rush] The "rushx" command should warn if invoked in a leftover project folder

- apps/api-extractor/package.json
- apps/api-extractor/src/analyzer/AstSymbolTable.ts
- apps/api-extractor/src/analyzer/ExportAnalyzer.ts
- apps/api-extractor/src/analyzer/Span.ts
- apps/api-extractor/src/analyzer/TypeScriptHelpers.ts
- common/changes/@microsoft/api-extractor/octogonz-typescript-4.3_2021-06-03-21-12.json
- common/config/rush/common-versions.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
Add support for TypeScript 4.3
The `build-tests` projects build without issues.
A workaround was required for https://github.com/microsoft/TypeScript/issues/44422
> [api-extractor] Upgrade the TypeScript engine to 4.3

- apps/heft/src/plugins/CopyFilesPlugin.ts
- common/changes/@rushstack/heft/user-danade-DeprecateCopyFilesToMany_2021-06-04-18-11.json
- common/changes/@rushstack/node-core-library/user-danade-DeprecateCopyFilesToMany_2021-06-04-18-11.json
- common/reviews/api/node-core-library.api.md
- libraries/node-core-library/src/FileSystem.ts
- libraries/node-core-library/src/index.ts
Fixes #2724
An investigation performed by @octogonz in #2724 has led to the likely conclusion that reading/writing to multiple streams is likely the culprit causing 0-length files. Additionally, the API itself likely provided little real-world benefit given that it relies on the Node Stream APIs, while the actual file copy APIs use libuv. Given these, it seemed best to just remove the broken `copyFileToManyAsync` API and replace it with parallelized calls to `copyFileAsync` in the `CopyFilesPlugin`.
- Removed the `copyFileToManyAsync` API completely due to the broken state
- Replaced usage with a combination of `Async.forEachAsync` and `FileSystem.copyFileAsync` in `CopyFilesPlugin`.
Ran rebuild in projects using the plugin to confirm that the copy files plugin was continuing to copy …
> [node-core-library] Remove the copyFileToManyAsync API

- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptPlugin.ts
- apps/heft/src/stages/BuildStage.ts
- common/changes/@rushstack/heft/user-danade-AddIsTypescriptProperty_2021-06-04-18-38.json
- common/reviews/api/heft.api.md
Add `IBuildStageProperties.isTypeScriptProject` output property and populate in the `TypeScriptPlugin`. This will be used in #2721 to eventually f.ix (avoiding auto-resolve) #2711 (thanks @idahogurl !!) in a method consistent with @iclanton 's comment here: https://github.com/microsoft/rushstack/pull/2711#issuecomment-854080989
> [heft] Populate `IBuildStageProperties.isTypeScriptProject` in the `TypeScriptPlugin`

- common/changes/@rushstack/heft-jest-plugin/user-danade-ResolveJestProperties_2021-06-11-20-09.json
- heft-plugins/heft-jest-plugin/src/JestPlugin.ts
I missed one property (`testEnvironment`) in the Jest config mapping to modules. This change adds the property to the list of JsonPaths that need to be resolved within the settings file.
> [heft-jest-plugin] Include `testEnvironment` in list of resolved Jest config properties

- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- apps/rush-lib/src/utilities/TarExecutable.ts
- common/changes/@microsoft/rush/octogonz-build-cache-timestamps_2021-06-14-23-55.json
In the current implementation, when Rush restores output files from the build cache cache, the `tar` command preserves the original timestamp.  This is confusing for tools that compare timestamps to detect changes.
This PR ensures that the extracted files will have a current modification time.  (As a point of reference, Git always applies a current modification time for files restored from the Git history.)
Tested on Windows, which has he most primitive `tar` implementation.
I also tested the fallback JavaScript implementation that is used when the `tar` binary is unavailable.
CC @MickeyPhoenix
> [rush] Update the modification time for files restored from the build cache

- apps/rush-lib/src/logic/LinkManagerFactory.ts
- apps/rush-lib/src/logic/ShrinkwrapFileFactory.ts
- common/changes/@microsoft/rush/user-ianc-disable-allowUnreachableCode_2021-06-10-21-47.json
- common/changes/@rushstack/heft-node-rig/user-ianc-disable-allowUnreachableCode_2021-06-10-21-36.json
- common/changes/@rushstack/heft-web-rig/user-ianc-disable-allowUnreachableCode_2021-06-10-21-36.json
- rigs/heft-node-rig/profiles/default/tsconfig-base.json
- rigs/heft-web-rig/profiles/library/tsconfig-base.json
This PR disallows [unreachable code](https://www.typescriptlang.org/tsconfig#allowUnreachableCode) in the Heft rigs.
Built the repo.
> Disable allowUnreachableCode in tsconfig-base in the Heft rigs.

- apps/heft/src/plugins/TypeScriptPlugin/LinterBase.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptPlugin.ts
- common/changes/@rushstack/heft/ianc-remove-multiple-tsconfigs_2021-06-15-23-38.json
This PR removes the functionality that runs a TypeScript builder for `tsconfig-*.json` files, now supporting only `tsconfig.json`.
Built the repo.
> [heft] Remove the ability to run multiple TypeScript compilers in a project.

- apps/heft/src/plugins/NodeServicePlugin.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptPlugin.ts
- apps/heft/src/stages/BuildStage.ts
- common/changes/@rushstack/heft/ianc-update-ts-hooks_2021-06-16-00-12.json
- common/reviews/api/heft.api.md
This PR goes in after https://github.com/microsoft/rushstack/pull/2749.
This PR removes the `afterEachIteration` compilation substage hook and introduces a `afterRecompile` compilation substage hook that is called each time a compilation happens in `--watch` mode, except after the first time (when `afterCompile` is called).
The motivation for this change is to allow a plugin author to generate assets to be used by a bundle substage operation (like Webpack) that take assets generated by the TypeScript compiler as inputs. The plugin should tap the `afterCompile` hook to generate the assets (and block the bundle substage) and tap the `afterRecompile` to update them after each compilation run.
Built this repo. @MickeyPhoenix may want to test as well.
> [heft] Rework the compile-related hooks.

- common/changes/@rushstack/heft-jest-plugin/octogonz-heft-jest-regressions_2021-06-18-05-26.json
- common/changes/@rushstack/heft-jest-plugin/octogonz-heft-jest-regressions_2021-06-18-05-27.json
- heft-plugins/heft-jest-plugin/src/JestPlugin.ts
Fixes #2745
Heft 0.32.0 completely changes how **jest.config.json** gets resolved.  
- This PR fixes a problem where "testEnvironment" was incorrectly resolved as a module path
- To prevent rigged projects from needing a dependency on `"@rushstack/heft-jest-plugin`, it adds a special case for resolving paths like `"@rushstack/heft-jest-plugin/lib/exports/jest-global-setup.js"`
With these changes, plus PR #2760, I was finally able to  migrate our large monorepo to use the latest Heft.
CC @D4N14L @iclanton
> [heft] Fix some regressions involving jest.config.json resolution

- common/changes/@rushstack/eslint-plugin-packlets/patch-1_2021-06-21-23-56.json
- stack/eslint-plugin-packlets/README.md
Update `packlets-tutorial` after being moved to `rushstack-samples`
The link to `packlets-tutorial` was outdated.
**Old link:** https://github.com/microsoft/rushstack/tree/master/tutorials/packlets-tutorial
**New link:** https://github.com/microsoft/rushstack-samples/tree/main/other/packlets-tutorial
> [eslint-plugin-packlets] fix link in README.md

- apps/rush-lib/src/cli/SelectionParameterSet.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/logic/TaskSelector.ts
- common/changes/@microsoft/rush/fix-empty-selection_2021-06-24-23-05.json
If one or more selection parameters are specified, allow the set of matched projects to be empty.
Fixes #2756
Checks to see if any selection parameters are specified, and either return the full project set if none are specified, or the exact selection if one or more are specified.
Added a message when 0 projects are selected by the parameters.
Verified that running `rush build --to-except tree-pattern` selects 0 projects and does no work.
```
PS D:\rushstack> node .\apps\rush-lib\lib\start.js build -v --to-except tree-pattern
Rush Multi-Project Build Tool 5.47.0 (unmanaged) - https://rushjs.io
Node.js version is 12.22.1 (LTS)
Starting "rush build"
The command line selection parameters did not match any projects.
```
> [rush] Allow selection parameters to select 0 projects

- common/changes/@rushstack/heft-config-file/user-danade-ImprovedJestResolve_2021-06-25-21-53.json
- common/changes/@rushstack/heft-jest-plugin/user-danade-ImprovedJestResolve_2021-06-25-21-53.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- common/reviews/api/heft-config-file.api.md
- heft-plugins/heft-jest-plugin/package.json
- heft-plugins/heft-jest-plugin/src/JestPlugin.ts
- heft-plugins/heft-jest-plugin/src/test/JestPlugin.test.ts
- heft-plugins/heft-jest-plugin/src/test/project1/a/c/jest.config.json
- heft-plugins/heft-jest-plugin/src/test/project1/a/jest.config.json
- heft-plugins/heft-jest-plugin/src/test/project2/a/jest.config.json
- libraries/heft-config-file/src/ConfigurationFile.ts
Fixes #2745
- Improve module resolution for Jest configuration files loaded using `heft-jest-plugin` such that it more closely resembles how default Jest functions
- Add tokens to allow for referencing special directories in non-path (but still 'pathy') fields like `moduleNameMapper`
In using JSON configuration files that were resolved fully before passing to Jest, we introduced a few limitations. Namely:
- All modules being referenced _must_ be available in the package the configuration file is sourced from
- No auto-prefixing for certain Jest fields
- No runtime resolution of paths in non-module fields
Unfortunately, this meant that we had introduced a few regressions in comparison with default Jest that we do not want to get rid of. Specifically, a few features that are being added …
> [heft-jest-plugin] Improve module resolution for Jest configuration files

- common/changes/@rushstack/heft-jest-plugin/user-danade-FixJestTransformMerge_2021-06-30-18-55.json
- heft-plugins/heft-jest-plugin/src/JestPlugin.ts
Fix the pattern used to combine `moduleNameMapper` and `transform` Jest configuration fields and add documentation on why it was done this way.
When creating the Jest configuration from presets internally, Jest cares about the order of definition of the object properties for the `moduleNameMapper` and `transform` fields since it will execute them in the order they were defined, stopping after hitting the first applicable pattern. This change is done in this order to ensure that the extending properties are defined first.
For example, if the _extended_ Jest configuration contains a `"\\.(css|sass|scss)$"` transform but the _extending_ Jest configuration contains a `"\\.(css)$"` override transform, merging like this will ensure that the returned transforms are executed in the correct order: …
> [heft-jest-plugin] Fix merge pattern used to combine moduleNameMappers and transforms

- common/changes/@rushstack/ts-command-line/new-param-types_2021-06-18-05-24.json
- common/reviews/api/ts-command-line.api.md
- libraries/ts-command-line/src/index.ts
- libraries/ts-command-line/src/parameters/BaseClasses.ts
- libraries/ts-command-line/src/parameters/CommandLineChoiceListParameter.ts
- libraries/ts-command-line/src/parameters/CommandLineDefinition.ts
- libraries/ts-command-line/src/parameters/CommandLineIntegerListParameter.ts
- libraries/ts-command-line/src/parameters/EnvironmentVariableParser.ts
- libraries/ts-command-line/src/providers/CommandLineParameterProvider.ts
- libraries/ts-command-line/src/test/CommandLineParameter.test.ts
- libraries/ts-command-line/src/test/__snapshots__/CommandLineParameter.test.ts.snap
Mirror `StringList` parameter with `ChoiceList` and `IntegerList` parameter types.
I've pulled out the basics of parsing an environment variable as a list into a separate utility class, since it doesn't need access to any of the internals of a `Parameter`.  Other than that change, I didn't work too hard to avoid duplicate code for the different `-ListParameter` types -- there's probably more that could be DRY'd up at some point, maybe if additional List types are added in the future.
I followed the lead of the `StringList` type and did not allow `defaultValue` in the definitions of these new types, but I'm not sure I agree with this decision (I think there's no reason you can't have a default value, and if the arg is never set on the command line, then `values = [defaultValue]`.)  I can …
> [ts-command-line] Add ChoiceList and IntegerList parameters (fixes #2330)

- apps/rush-lib/assets/rush-init/common/config/rush/build-cache.json
- apps/rush-lib/src/schemas/build-cache.schema.json
- common/changes/@microsoft/rush/fix-build-cache-schema_2021-06-30-13-59.json
When using build-cache feature and set cacheEntryNamePattern with [normalized] token as comments, error occurred.
https://github.com/microsoft/rushstack/blob/448854a414f1402f221cbd01e26fbbdcb89f5a31/apps/rush-lib/src/logic/buildCache/CacheEntryId.ts#L77
It's seemed to be a spell mistake.
> [rush-lib] fix cacheEntryNamePattern description of [normalized] token should be [normalize]

- apps/rush-lib/package.json
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/logic/ProjectWatcher.ts
- common/changes/@microsoft/rush/remove-chokidar_2021-04-23-23-34.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
The `chokidar` package provides a bunch of signal normalization that is redundant for the watch capabilities of rush, because the actual set of changed files is used purely as a boolean signal that is then handed off to the `PackageChangeAnalyzer` to determine what actually changed.
We already use `PackageChangeAnalyzer` (which is powered by `git diff` and is very, very fast) to determine the answer to "what changed" between incremental builds; as such, we prefer to also leverage it for the diffing in the watch case for consistent behavior.
This PR removes `chokidar` and replaces it with native `fs.watch` calls (carefully scoped to only watch directories), such that we can get a basic "hey, something (anything) changed, go poke git" notification as simply as possible.
Local verification …
> [rush] Remove chokidar dependency

- apps/api-extractor/.vscode/launch.json
- apps/api-extractor/src/analyzer/Span.ts
- apps/api-extractor/src/generators/DtsRollupGenerator.ts
- build-tests/api-extractor-scenarios/etc/test-outputs/spanSorting/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/spanSorting/api-extractor-scenarios.api.md
- build-tests/api-extractor-scenarios/etc/test-outputs/spanSorting/rollup.d.ts
- build-tests/api-extractor-scenarios/src/spanSorting/index.ts
- common/changes/@microsoft/api-extractor/octogonz-ae-2797_2021-07-08-23-17.json
Fixes https://github.com/microsoft/rushstack/issues/2797
This syntax did not occur in any of the projects that I tested for PR #2796.  
I've added a build test to cover this case.
> [api-extractor] Fix "indentDocComment cannot be nested" error

- apps/rush-lib/src/cli/actions/ChangeAction.ts
- apps/rush-lib/src/cli/actions/WriteBuildCacheAction.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/index.ts
- apps/rush-lib/src/logic/Git.ts
- apps/rush-lib/src/logic/ProjectChangeAnalyzer.ts
- apps/rush-lib/src/logic/ProjectWatcher.ts
- apps/rush-lib/src/logic/TaskSelector.ts
- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- apps/rush-lib/src/logic/buildCache/test/ProjectBuildCache.test.ts
- apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts
- apps/rush-lib/src/logic/test/ProjectChangeAnalyzer.test.ts
- apps/rush-lib/src/logic/test/__snapshots__/ProjectChangeAnalyzer.test.ts.snap
- apps/rush-lib/src/utilities/Utilities.ts
- build-tests/rush-project-change-analyzer-test/.eslintrc.js
- build-tests/rush-project-change-analyzer-test/config/rig.json
- build-tests/rush-project-change-analyzer-test/package.json
- build-tests/rush-project-change-analyzer-test/src/start.ts
- build-tests/rush-project-change-analyzer-test/tsconfig.json
- common/changes/@microsoft/rush/ianc-expose-project-change-analyzer_2021-07-07-22-22.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- common/reviews/api/rush-lib.api.md
- rush.json
This change cleans up the API of `ProjectChangeAnalyzer` and exposes it from `@microsoft/rush-lib`. It also moves the changed project detection from `ChangeAction` to `ProjectChangeAnalyzer`.
This is useful code for working with a Rush repo, so instead of having API users reinvent it, it's useful to just provide it. For example, I'm working on a project to filter integration tests that are run by a service external to the build by the set of projects that are changed in a PR. The code that `rush change` uses to determine which projects where changed is ideal for this.
Tested the `rush change`, `rush change --verify`, and `rush build` actions locally to ensure they still work.
> [rush] Clean up and expose ProjectChangeAnalyzer from rush-lib.

- apps/rush-lib/src/cli/actions/ChangeAction.ts
- common/changes/@microsoft/rush/ianc-fix-no-fetch_2021-07-13-22-37.json
https://github.com/microsoft/rushstack/pull/2795 caused a regression where the `rush change` `--no-fetch` parameter causes a `git fetch`, and absence of that parameter doesn't fetch.
Tested `rush change` and `rush change -v` locally with and without the `--no-fetch` parameter.
> [rush] Fix the --no-fetch parameter

- apps/rush-lib/src/logic/ProjectChangeAnalyzer.ts
- apps/rush-lib/src/logic/test/ProjectChangeAnalyzer.test.ts
- common/changes/@microsoft/rush/user-danade-FixFilteredInstalls_2021-07-15-00-36.json
Filtered installs were broken due to attempting to load config files in dependencies while calculating incremental build state.
Calculating incremental build state is done by analyzing the world in the repo during initialization, and then proceeding only with the required data. This is done (partially) in an attempt to preserve perf when calculating this state. However, recent changes in #2643 caused this calculation to fail for filtered installs with the error message:
```
Error calculating incremental build state. Instead running full rebuild. Error: Cannot find module '<package A>' from '<path to some project>'
```
This is because it introduced loading of a config file in a project that has not been included in the filtered install. This change makes it so that the config file is only …
> [rush-lib] Fix incremental build state calculation during filtered installs

- common/changes/@rushstack/module-minifier-plugin/module-minifier-enhancements_2021-07-02-00-30.json
- common/reviews/api/module-minifier-plugin.api.md
- webpack/module-minifier-plugin/src/GenerateLicenseFileForAsset.ts
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.ts
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.types.ts
- webpack/module-minifier-plugin/src/NoopMinifier.ts
- webpack/module-minifier-plugin/src/ParallelCompiler.ts
- webpack/module-minifier-plugin/src/PortableMinifierIdsPlugin.ts
- webpack/module-minifier-plugin/src/WorkerPoolMinifier.ts
- webpack/module-minifier-plugin/src/terser/MinifySingleFile.ts
- webpack/module-minifier-plugin/src/test/MinifySingleFile.test.ts
- webpack/module-minifier-plugin/src/test/RehydrateAsset.test.ts
- webpack/module-minifier-plugin/src/test/__snapshots__/MinifySingleFile.test.ts.snap
- webpack/module-minifier-plugin/src/workerPool/WorkerPool.ts
- webpack/module-minifier-plugin/tsconfig.json
Separates responsibility for comment extraction from minification. This allows minifier implementations to be more flexible, as they can freely discard comments in all cases.
Added metadata for minified module sizes.
Removed comment extraction from the minifier and moved it to the initial parse phase.
Local build validation, unit tests.
> [module-minifier-plugin] Separate comment extraction from minification

- apps/rush-lib/src/cli/actions/ListAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- common/changes/@microsoft/rush/rush-list-selectors_2021-07-20-23-18.json
Enables the [project selection parameters](https://rushjs.io/pages/developer/selecting_subsets/) to be used by the `rush list` command, such that external programs can ask rush for a list of projects that match a specified selection.
Can be used to determine which projects would be affected by an equivalent build command, to list the net dependencies of a given project, etc.
The `-f` flag is no longer aliased to `--fullPath` due to a conflict with `--from`.
This will become particularly useful if the `--since` parameter is introduced, since it will allow other tools that want the output of that selection algorithm to delegate to `rush`.
Ran `rush list --to node-core-library` and similar commands locally and verified the output.
> [rush] Support project selection parameters in `rush list` command

- build-tests/localization-plugin-test-02/src/indexA.ts
- build-tests/localization-plugin-test-02/webpack.config.js
- common/changes/@rushstack/module-minifier-plugin/fix-minifier-comment-extraction_2021-07-22-21-47.json
- common/reviews/api/module-minifier-plugin.api.md
- webpack/module-minifier-plugin/src/GenerateLicenseFileForAsset.ts
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.ts
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.types.ts
- webpack/module-minifier-plugin/src/WorkerPoolMinifier.ts
Fixes faulty code in the license file generator that was causing a crash.
Comments were being stored as objects but expected to be strings, and was not caught during the build due to an `any` on the typings of the `factoryMeta` fields. Was not caught during the build tests because none of them had preserved comments in the source text.
Updated the code to unpack the objects back into the raw string form.
Added license comments to the localization-plugin-test-02 build test suite to validate that comment extraction works as expected. Updated the same test to leverage `WorkerPoolMinifier` instead of `SynchronousMinifier`.
Fixed incorrect configuration of the `WorkerPool` instance inside of `WorkerPoolMinifier` that resulted in use of it hanging the process.
Ran the new …
> [module-minifier-plugin] Fix comment file generation, WorkerPoolMinifier

- common/changes/@rushstack/debug-certificate-manager/ianc-update-node-forge_2021-07-27-21-50.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- libraries/debug-certificate-manager/package.json
- libraries/debug-certificate-manager/src/CertificateManager.ts
- libraries/debug-certificate-manager/src/exec.ts
There is a vulnerability flagged in `node-forge` versions before 0.10.0. This PR updates `node-forge` to `~0.10.0`. This change also updates `debug-certificate-manager` to lazy-load `node-forge`.
Tested by creating certificates in a heft project in another repo.
> [debug-certificate-manager] Update node-forge.

- apps/heft/src/utilities/subprocess/SubprocessLoggerManager.ts
- common/changes/@rushstack/heft/ianc-fix-error-case_2021-08-05-02-15.json
There is a bug (that should never be exposed to users) where a misleading error is thrown when a subprocess requesting a `ScopedLogger` throws an error.
Created an error condition and ensured the thrown error is correct.
> [heft] Fix an issue where a misleading error is thrown when a subprocess requesting a ScopedLogger throws.

- apps/rush-lib/package.json
- common/changes/@microsoft/rush/ianc-update-jszip_2021-08-10-22-48.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
Fixes https://github.com/microsoft/rushstack/issues/2836.
Tested by running `rush deploy` in another repo.
> [rush] Update JSZip.

- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- common/changes/@rushstack/heft-node-rig/lock-tsbuildinfo-path_2021-08-12-00-43.json
- common/changes/@rushstack/heft-web-rig/lock-tsbuildinfo-path_2021-08-12-00-43.json
- common/changes/@rushstack/heft/lock-tsbuildinfo-path_2021-08-12-00-43.json
- rigs/heft-node-rig/profiles/default/tsconfig-base.json
- rigs/heft-web-rig/profiles/library/tsconfig-base.json
Using the `tsBuildInfoFile` in tsconfig-base.json in rigs was resolving incorrectly. This PR restores it to being auto-generated inside of the Heft TypeScriptPlugin.
Uses the same algorithm as previously, but routed into the `temp/` folder instead of `.heft/build-cache`.
Local `rush build`, verified that projects have a build info file in the expected location.
> [heft] Restore generation of tsbuildinfo path to compensate for improper resolution semantics

- apps/heft/src/plugins/ApiExtractorPlugin/ApiExtractorRunner.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- apps/heft/src/utilities/subprocess/SubprocessRunnerBase.ts
- apps/heft/src/utilities/subprocess/startSubprocess.ts
- common/changes/@rushstack/heft/ianc-fix-subprocess-cwd_2021-08-12-06-51.json
There is currently an issue where if Heft is invoked in a console with incorrect casing in the CWD (for example, `c:\code\projectfolder` instead of `C:\code\projectfolder`), modules with incorrect properties will be passed to TSLint.
This change fixes the issue by explicitly setting the `cwd` property in the subprocess runner.
Tested with a console with an incorrectly-cased working directory.
> [heft] Ensure the CWD is set correctly for subprocesses.

- common/changes/@rushstack/heft-node-rig/rig-revert-incremental_2021-08-12-18-47.json
- common/changes/@rushstack/heft-web-rig/rig-revert-incremental_2021-08-12-18-47.json
- rigs/heft-node-rig/profiles/default/tsconfig-base.json
- rigs/heft-web-rig/profiles/library/tsconfig-base.json
Setting "incremental: true" in tsconfig requires setting `tsBuildInfoFile` in the config as well, but Heft is rewriting the value thereof. This PR removes the setting from the rig to ensure that the config is compatible with other tools that might read tsconfig.json.
An alternative would be to set the `tsBuildInfoFile` property, but we previously encountered issues with how the path resolves when this is specified in a rig.
Regular build of rushstack repo, since most projects in the repo use the rigs.
> [heft] Revert setting incremental: true in tsconfig-base.json

- apps/rush-lib/src/logic/taskRunner/BaseBuilder.ts
- apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts
- apps/rush-lib/src/logic/taskRunner/TaskRunner.ts
- apps/rush-lib/src/logic/taskRunner/test/MockBuilder.ts
- common/changes/@microsoft/rush/fix-rush-build-cache_2021-08-13-22-04.json
Partially undoes behavior changes of #2802. Allows `rush build` to read from the build cache for projects for which dependencies have been rebuilt, if applicable. Still ensures that `rush rebuild` does not read from the build cache.
Separates the `isIncrementalBuildAllowed` option in `ProjectBuilder` into two separate flags for the desired behaviors:
- `_isCacheReadAllowed` is set by being the command-level `isIncrementalBuildAllowed` flag, and controls if read from cache is permitted if a match is found.
- `isSkipAllowed` is initialized by the command-level `isIncrementalBuildAllowed` flag, but updated by `TaskRunner` in response to upstream projects being built, and controls if the project may be skipped if current package-deps match the most recent execution.
Ran local `node …
> [rush] Allow build cache reads downstream of built projects during `rush build`

- common/changes/@rushstack/module-minifier-plugin/module-minifier-mini-css-compat_2021-08-17-21-01.json
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.ts
- webpack/module-minifier-plugin/src/RehydrateAsset.ts
Configures the ModuleMinifierPlugin to ignore non-JavaScript modules/assets as appropriate.
If the asset being rendered does not use the JavaScript module template, leaves the rendered modules in place instead of replacing the content with a marker.
Used built version against a separate project with mini-css-extract-plugin in use.
> [module-minifier-plugin] Fix compatibility issue with mini-css-extract-plugin

- build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
- common/changes/@rushstack/heft-webpack5-plugin/bartvandenende-wm-webpack-dev-update_2021-08-24-16-18.json
- common/config/rush/.pnpmfile.cjs
- common/config/rush/common-versions.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- heft-plugins/heft-webpack5-plugin/package.json
- heft-plugins/heft-webpack5-plugin/src/WebpackPlugin.ts
This PR updates webpack-dev-server from 3.x to version 4.x to which brings official webpack 5.x support.
There are several breaking changes when migrating to webpack-dev-server 4.x, a full migration guide is available below:
https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md
```
Minimum supported Node.js version is `12.13.0`.
Minimum supported webpack version is `4.37.0`  (but we so recommend using 5 version).
Minimum compatible webpack-cli version is `4.7.0`.
```
To reduce the change impact this update has only been applied for the `heft-webpack5-plugin` plugin, though per above could in theory also be ported to heft-webpack4-plugin.
The usage of  webpack-dev-server 3.x was 'mostly' compatible with webpack 5.x , but there where a number of open issues that only …
> [heft-webpack5-plugin] Upgrade to webpack-dev-server 4.x

- apps/rush-lib/assets/rush-init/common/config/rush/experiments.json
- apps/rush-lib/src/api/ExperimentsConfiguration.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/logic/TaskSelector.ts
- apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts
- apps/rush-lib/src/logic/taskRunner/test/TaskRunner.test.ts
- apps/rush-lib/src/schemas/experiments.schema.json
- common/changes/@microsoft/rush/relm-cache_with_warnings_2021-07-31-18-49.json
- common/changes/@microsoft/rush/relm-cache_with_warnings_2021-08-22-20-34.json
- common/reviews/api/rush-lib.api.md
Fixes #2803
Update ProjectBuilder to persist `build-cache` when task status `SuccessWithWarning` and `allowWarningsInSuccessfulBuild: true` is set for the command
Now passing `allowWarningsInSuccessfulBuild` flag from `BulkScriptAction` down to `ProjectBuilder` and conditionally persisting the cache if enabled
Tested locally as there is limited test coverage around `ProjectBuilder` currently
> [rush] build-cache respects allowWarningsInSuccessfulBuild

- apps/api-documenter/src/markdown/MarkdownEmitter.ts
- common/changes/@microsoft/api-documenter/redundant-newline-in-fenced-code_2021-08-15-05-01.json
Fixes #2857
This PR delete redundant newline at end of fenced code in output of `api-documenter markdown`.
Use `writer.ensureNewLine()` instead of `writer.writeLine()` for write end of fenced code.
At first I simply removed the call of `writer.writeLine()`, but it affected the Signature section.
Prepare `.d.ts` which contains fenced code in doc comment.
E.g.
```typescript
/**
* @example
* ```typescript
* console.log(add(40, 2)) // => 42
* ```
*/
export function add(x: number, y: number): number;
```
Generate the markdown document for it.
The output changes from
<pre>
```typescript
console.log(add(40, 2)) // => 42
```
</pre>
to
<pre>
```typescript
console.log(add(40, 2)) // => 42
```
</pre>
> [api-documenter] Delete redundant newline from fenced code

- common/changes/@rushstack/heft-jest-plugin/user-danade-JestDisplayName_2021-09-01-00-38.json
- heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts
- heft-plugins/heft-jest-plugin/src/JestPlugin.ts
Set the Jest `displayName` to the package name that contains the tests being run by default, instead of requiring it to be specified in each `jest.config.json`.
Additionally, this PR adds fallback logic for calculating the test duration in the reporter if the Jest-provided value is not available.
Fixes #2848
The `displayName` field is intended to help differentiate between projects in Jest. While we use our own reporter instead of the built-in reporter and therefore do not use the displayName, it can be used in other reporters such as `jest-junit` to provide more context.
Additionally, the test duration value is not always available/provided by Jest, so we can perform a lightweight tracking of start and end times to provide our own duration.
Running a build and outputting the displayName …
> [heft-jest-plugin] Set Jest `displayName` to the package name by default and log test duration

- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- apps/heft/src/plugins/TypeScriptPlugin/internalTypings/TypeScriptInternals.ts
- apps/heft/src/utilities/fileSystem/TypeScriptCachedFileSystem.ts
- build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
- build-tests/install-test-workspace/workspace/typescript-newest-test/package.json
- common/changes/@rushstack/heft/master_2021-09-03-21-45.json
When building a project with Typescript 4.4 the typescript Heft plugin would fail with "Error: directoryExists is not a function". This PR fixes it by adding a missing directoryExists argument to the call to the Typescript internal `matchFiles` method.
Fixes https://github.com/microsoft/rushstack/issues/2878.
* Upgraded typescript-newest-test to Typescript 4.4.2. `install-test-workspace` was failing before this change
* Upgraded heft-node-everything-test to Typescript 4.4.2 locally. Had to remove `tslint-microsoft-contrib` from that project since it wasn't compatible with Typescript 4.4. After disabling tslint for that project it built fine.
> [heft] Fix building with Typescript 4.4 due to changed internal interface

- apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts
- common/changes/@microsoft/rush/build-cache-skip_2021-09-05-16-40.json
In order to better position _build caching_ as a new replacement for _build skipping_, this PR tweaks the project builder so that projects which can use the build cache do not also attempt to skip the build.  Once a Rush monorepo makes the jump to build caching, we can consider the whole monorepo "in cache mode" (with a few caveats).
Projects that disable build caching in their `rush-project.json`, or that haven't yet configured their output folders, can continue to use the "build skip" incremental build logic.
This change does prevent some unfortunate corner cases -- for example, if you attempt to restore from build cache and there's a corrupted cache entry, you end up with a deleted `lib` folder but nothing unpacked; then you delete the offending cache entry, but now it skips the build …
> [rush] Do not apply build caching and skipping to the same project

- common/changes/@rushstack/heft-config-file/user-danade-FixFalsyConfig_2021-09-08-08-02.json
- libraries/heft-config-file/src/ConfigurationFile.ts
- libraries/heft-config-file/src/test/ConfigurationFile.test.ts
- libraries/heft-config-file/src/test/simpleConfigFile/simpleConfigFile.json
- libraries/heft-config-file/src/test/simpleConfigFile/simpleConfigFile.schema.json
- libraries/heft-config-file/src/test/simpleConfigFileWithExtends/simpleConfigFileWithExtends.json
- libraries/heft-config-file/src/test/simpleConfigFileWithExtends/simpleConfigFileWithExtends.schema.json
Fix issue overwriting/replacing configuration properties using falsey values
While working in our Rush repo using Jest configuration files, I found that a boolean property was not being respected. Further investigation led to the cause being that a check was incorrectly equating falsey values with `undefined`. This bug leads to the inability to set a truthy value to a falsey value in an extending configuration file (ex, the inability to overwrite and set a value to `false` after previously being `true`).
Added a test first to validate that the issue was reproducible outside of our Rush repo, then made the fix to validate that the change resolves the issue.
> [heft-config-file] Fix issue preventing replacement of configuration properties using falsey values

- apps/rush-lib/package.json
- common/changes/@microsoft/rush/lock-node-fetch_2021-09-21-05-46.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
Version 2.6.3 of `node-fetch` made a breaking change to the encoding state of URLs that is incompatible with the expectations of `@azure/core-http` with regards to including SAS tokens in URLs. This locks the version used by Rush to 2.6.2 to avoid breaking customers who use the Azure cloud cache provider.
Verified locally that installing with node-fetch 2.6.2 does not reproduce the authentication error encountered during cloud cache writes. Fresh installs started failing ~7 hours ago, which lines up with when version 2.6.3 of node-fetch was released.
> Lock node-fetch to avoid breaking change in 2.6.3 version

- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptPlugin.ts
- common/changes/@rushstack/heft/fix-incremental-again_2021-09-21-20-53.json
Fixes incremental emit of TypeScript to only emit changed files.
TypeScript internally normalizes all directory separators to `/` so that it can use exact string comparisons to test for changes. However, it only applies this transformation to the `tsBuildInfoFile` value when serializing the tsBuildInfo JSON to disk. It expects the input in the tsconfig to have already been normalized.
As a result, constructing the path using `path.join()` on Windows produces an incorrect path that will always fail to match the serialized value.
Run:
```
heft build --verbose
heft build --verbose
```
Verify that the second time does not emit any files.
> [heft] Fix directory separators in generated tsBuildInfoFile

- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptPlugin.ts
- common/changes/@rushstack/heft/fix-typo_2021-09-22-01-27.json
Fixes an accidental typo in the metadata folder path introduced in #2919.
Tested via running @rushstack/heft on itself and confirming no unexpected output files.
> [heft] Fix typo in folder path

- apps/rush-lib/src/cli/actions/InstallAction.ts
- apps/rush-lib/src/cli/actions/UpdateAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/logic/PackageJsonUpdater.ts
- apps/rush-lib/src/logic/base/BaseInstallManager.ts
- common/changes/@microsoft/rush/feat-rush-install-check-only_2021-09-11-02-21.json
Add `--check-only` parameter to `rush install`
which fixes https://github.com/microsoft/rushstack/issues/2570
As per pete (https://github.com/microsoft/rushstack/issues/2570#issuecomment-809866637), a new flag parameter is added to `InstallAction`, it helps to only check the validatation before install, without install anything actually. Targeting the situation when user only want to check whether shrinkwrap file is update to date.
Local
> [rush] Feat rush install check only

- apps/rush-lib/src/logic/Autoinstaller.ts
- apps/rush/bin/rushx
- common/changes/@microsoft/rush/fix-autoinstaller-update_2021-09-14-17-35.json
Fixes #2905 
Copy `.npmrc` to the current working autoinstaller
Reinvoked `rush update-autoinstaller --name xxx` and all the dependencies installed correctly that private registry provides.
> [rush-lib] Fix the issue where update-autoinstaller does not use .npmrc

- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/logic/ChangelogGenerator.ts
- apps/rush-lib/src/logic/Git.ts
- apps/rush-lib/src/logic/PublishGit.ts
- apps/rush-lib/src/logic/PublishUtilities.ts
- apps/rush-lib/src/schemas/rush.schema.json
- common/changes/@microsoft/rush/feature-issue-2654_2021-09-02-15-24.json
- common/reviews/api/rush-lib.api.md
Add a new gitPolicy configuration to customize git tag separator.
Fixes #2654
`rush publish` using package name and version as tag name, which is fair enough. However, as we want to manage tags in a more visual way, the current separator `_` is not good for us to keep things organized.
If we use separator `/` between package name and version, we may have ability to keep all related tags in one directory for specific package.
Manually run `rush publish -a` in a rush managed repo which have open changes. And check the log to see if `gitPolicy.tagSeparator` in `rush.json` has effect on the tag names.
> [rush] Add ability to customize tag separator

- apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
- common/changes/@microsoft/rush/drieman-typoShinkwrap_2021-09-23-20-46.json
Fixed a simple typo where "shinkwrap" should have been "shrinkwrap".
Searched repo for the misspelled word (as noticed by a fellow dev from rush command output).  Fixed it.
Searched full repo for the misspelled string.  This did not turn up any additional hits, so the typo does not appear to be duplicated inside any unit tests, etc.  Ran `rush build --to rush-lib` which I assume runs associated unit tests (if any), and the process completed green without error.
> [rush-lib] Fix 'shinkwrap' typo

- apps/heft/src/plugins/CopyFilesPlugin.ts
- apps/heft/src/plugins/DeleteGlobsPlugin.ts
- apps/heft/src/plugins/RunScriptPlugin.ts
- apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
- apps/heft/src/utilities/HeftAsync.ts
- common/changes/@rushstack/heft/ianc-async-iterator_2021-09-23-19-45.json
- common/changes/@rushstack/node-core-library/ianc-async-iterator_2021-09-23-03-15.json
- common/reviews/api/node-core-library.api.md
- libraries/node-core-library/src/Async.ts
- libraries/node-core-library/src/test/Async.test.ts
Right now the `Async` functions can't take an iterator. This means that you can't directly call `Async.forEachAsync(new Set())`. This PR allows those functions to take any iterator or async iterator.
There are tests for `Async` that validate this. I've added tests to ensure that errors thrown by iterators are also handled.
> [node-core-library] Allow Async.mapAsync and Async.forEachAsync to take an iterator.

- apps/rush-lib/package.json
- apps/rush-lib/src/logic/pnpm/IPnpmfile.ts
- apps/rush-lib/src/logic/pnpm/PnpmfileShim.ts
- common/changes/@microsoft/rush/feat-pnpmfile-filter-log_2021-10-28-03-38.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
pnpm adds a new hook for filtering out info and warning logs from `pnpm@6.17.0`.
Adding `filterLog` in `PnpmfileShim`.
Local
> feat(rush): add new filterLog hook in pnpmfile shim

- common/changes/@rushstack/eslint-patch/asmundg-fix-pnmp-layout_2021-10-27-13-11.json
- stack/eslint-patch/src/modern-module-resolution.ts
When using package managers like pnpm and yarn pnp, which store packages
in a flat store and adds symlinks in node_modules, the real path of
package folders will have version numbers and disambiguating hashes in
them.
This means that naively looking at folder names when looking for eslint
patch targets won't work.
Instead, we use module resolution semantics to compare the path of
resolved patch targets to the current call stack. This lets us
unambiguously locate patch targets in our call stack without making
assumptions about disk layout.
Tested in internal repo with pnpm-style layout
* MacOS (case sensitive FS)
* eslint 8.1.0
* NodeJS 12/14/16
* eslint 7.32.0
* NodeJS 12/14/16
* Windows
* eslint 8.1.0
* NodeJS 12/14/16
* eslint 7.32.0
* NodeJS 12/14/16
Validated that config fails without …
> feat(eslint-patch): Find patch targets independently of disk layout

- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/cli/SelectionParameterSet.ts
- apps/rush-lib/src/cli/actions/BaseInstallAction.ts
- apps/rush-lib/src/cli/actions/ChangeAction.ts
- apps/rush-lib/src/cli/actions/InstallAction.ts
- apps/rush-lib/src/cli/actions/ListAction.ts
- apps/rush-lib/src/cli/actions/UpdateAction.ts
- apps/rush-lib/src/cli/actions/WriteBuildCacheAction.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/logic/ProjectChangeAnalyzer.ts
- apps/rush-lib/src/logic/ProjectWatcher.ts
- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- apps/rush-lib/src/logic/selectors/GitChangedProjectSelectorParser.ts
- apps/rush-lib/src/logic/selectors/ISelectorParser.ts
- apps/rush-lib/src/logic/selectors/NamedProjectSelectorParser.ts
- apps/rush-lib/src/logic/selectors/VersionPolicyProjectSelectorParser.ts
- apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts
- apps/rush-lib/src/logic/test/ProjectChangeAnalyzer.test.ts
- build-tests/rush-project-change-analyzer-test/src/start.ts
- common/changes/@microsoft/rush/git-repo-relative_2021-10-14-02-07.json
- common/changes/@rushstack/node-core-library/git-repo-relative_2021-10-14-02-07.json
- common/changes/@rushstack/package-deps-hash/git-repo-relative_2021-10-14-02-07.json
- common/reviews/api/package-deps-hash.api.md
- common/reviews/api/rush-lib.api.md
- libraries/node-core-library/src/Path.ts
- libraries/package-deps-hash/config/jest.config.json
- libraries/package-deps-hash/src/getRepoState.ts
- libraries/package-deps-hash/src/index.ts
- libraries/package-deps-hash/src/test/getRepoDeps.test.ts
~~Adds support for two new command-line selection parameters:~~
- ~~`--changed-since REF`: Selects all projects that have had committed or staged changes in the Git repository since revision REF, then performs the same expansion as `--from`, i.e. selects all consumers of those projects, and all dependencies required to build the resulting set.~~
- ~~`--changed-since-only REF`: Selects all projects that have had committed or staged changes in the Git repository since revision REF. No expansion is performed.~~
Revises the parser for command line selection parameters to accept values of the format `${protocol}:${specifier}`. If the input does not contain the character `:`, the protocol is inferred as `'name'`. Protocol handlers:
- `git:${REF}` - Find all projects that contain Git changes …
> [Rush] Add support for "git:" protocol in selection parameter values

- apps/api-documenter/src/documenters/MarkdownDocumenter.ts
- build-tests/api-documenter-test/etc/api-documenter-test.api.json
- build-tests/api-documenter-test/etc/markdown/api-documenter-test.docenum.md
- build-tests/api-documenter-test/etc/yaml/api-documenter-test/docenum.yml
- build-tests/api-documenter-test/src/DocEnums.ts
- common/changes/@microsoft/api-documenter/enelson-api-enum-link_2021-11-01-12-51.json
For markdown output, we write a single output page for an Enum, but not separate pages for Enum Members.
Correct generated links for Enum Members to point at their parent Enum page.
Fixes #2552.
_Note:_ I'm not that familiar with the YAML output; it looks like the YAML output is correct, based on the updated integration tests, but we can do a similar fix there if necessary.
- Updated `build-tests/api-documenter-test` integration test and validated output markdown was incorrect.
- Inserted fix and validated output markdown was correct.
> [api-documenter] Fix broken markdown links for enum members

- common/changes/@rushstack/eslint-config/user-danade-FixMixinDocs_2021-11-09-20-39.json
- common/changes/@rushstack/eslint-plugin-packlets/user-danade-FixMixinDocs_2021-11-09-20-39.json
- stack/eslint-config/README.md
- stack/eslint-plugin-packlets/README.md
Updates the import paths to ESLint mixin configurations to be to the actual path. Fixes #2997
> [eslint-config] Set README paths to mixins to correct paths

- apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
- common/changes/@microsoft/rush/stop-deleting-pnpm-store_2021-11-18-01-52.json
Stops deleting the pnpm store after max retries have been reached for a workspace install.
Breaking the pnpm store is a situation that in practice does not happen. The two most common causes of failed install are that the requested package does not exist in the registry (happens a lot when mirroring packages, or due to user error in package.json), or a network error on the machine. Neither situation is helped by deleting the local cache.
> [rush] Stop deleting pnpm store after failed workspace installs

- common/changes/@rushstack/heft-jest-plugin/user-danade-noderigtestenvironment_2021-11-30-18-37.json
- common/changes/@rushstack/heft-node-rig/user-danade-noderigtestenvironment_2021-11-30-18-31.json
- common/changes/@rushstack/heft-web-rig/user-danade-noderigtestenvironment_2021-11-30-18-37.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- heft-plugins/heft-jest-plugin/package.json
- rigs/heft-node-rig/package.json
- rigs/heft-node-rig/profiles/default/config/jest.config.json
- rigs/heft-web-rig/package.json
- rigs/heft-web-rig/profiles/library/config/jest.config.json
Consumers of the Node rig should now consume `jest-environment-node` instead of the default `jest-environment-jsdom`.
The `@rushstack/heft-node-rig` package had been using the default `testEnvironment` value for Jest, which (as of 25.x, the current version of Jest used by `@rushstack/heft-jest-plugin` at time of PR publish) defaults to `jest-environment-jsdom`. This is unexpected and can lead to issues with behaviour of code intended to work in browsers or in Node. Additionally, the `jest-environment-node` environment can provide significant performance improvements for Jest tests. This is the reason that `jest-environment-node` was made the default in Jest 27.x (see blog post here: https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults)
This PR also hardcodes the dependency on …
> [heft-node-rig] Use jest-environment-node for Jest

- apps/rush-lib/src/cli/scriptActions/GlobalScriptAction.ts
- common/changes/@microsoft/rush/fix-global-command-escaping_2021-12-01-00-30.json
Fixes https://github.com/microsoft/rushstack/issues/3027
Escapes quotemarks in args and wraps args containing spaces in quotemarks before passing them to the shell.
Tested with https://github.com/iclanton/rushstack/commit/44c1948519788c7b13b21939c5402473623ef2da and running `rush my-global-command --my-string "x \"y z"`
> [rush] Fix an issue where parameter values containing spaces aren't correctly passed to global commands.

- apps/rush-lib/src/cli/SelectionParameterSet.ts
- apps/rush-lib/src/cli/actions/ChangeAction.ts
- apps/rush-lib/src/cli/actions/ListAction.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/logic/ProjectChangeAnalyzer.ts
- apps/rush-lib/src/logic/selectors/GitChangedProjectSelectorParser.ts
- apps/rush-lib/src/logic/selectors/ISelectorParser.ts
- apps/rush-lib/src/logic/selectors/NamedProjectSelectorParser.ts
- apps/rush-lib/src/logic/selectors/VersionPolicyProjectSelectorParser.ts
- build-tests/rush-project-change-analyzer-test/src/start.ts
- common/changes/@microsoft/rush/rush-change-ignore-shrinkwrap_2021-12-01-09-55.json
- common/reviews/api/rush-lib.api.md
Fixes https://github.com/microsoft/rushstack/issues/3053 and https://github.com/microsoft/rushstack/issues/3054.
https://github.com/microsoft/rushstack/pull/2968 changed the project change detection logic to consider the shrinkwrap file and a `incrementalBuildIgnoredGlobs` field in `rush-project.json`. These are relevant for incremental build, but not for `rush change`. This PR restores some of the old behavior.
Tested with `rush change -v` in a repo with a shrinkwrap change after running `rush purge`.
> [rush] Fix issues with `rush change` and the new diffing behavior.

- common/changes/@rushstack/node-core-library/ncl-no-const-enums_2021-12-02-19-15.json
- common/reviews/api/node-core-library.api.md
- libraries/node-core-library/src/Constants.ts
- libraries/node-core-library/src/FileSystem.ts
- libraries/node-core-library/src/PosixModeBits.ts
- libraries/node-core-library/src/Text.ts
Addresses https://github.com/microsoft/rushstack/issues/3058.
This allows for compatibility with consumers writing code in JavaScript, or who use `isolatedModules` in TypeScript.
Build passes.
> [node-core-library] Eliminate const enums from node-core-library's public API.

- common/changes/@rushstack/package-deps-hash/use-merge-base_2021-12-08-22-09.json
- libraries/package-deps-hash/src/getRepoState.ts
Use the `--merge-base` flag when running change detection against a target branch, so that changes to the target branch since the point at which the current branch was forked are not included in the selection.
Fixes a regression introduced when changing from `git diff` to `git diff-index` for change detection.
Verified using a stale branch that only local changes in said branch were included, rather than changes to `master` since the branch was forked.
> [package-deps-hash] Use --merge-base flag when diffing against a target branch

- apps/api-extractor-model/src/items/ApiItem.ts
- apps/api-extractor-model/src/mixins/Excerpt.ts
- common/changes/@microsoft/api-extractor-model/master_2021-12-06-21-04.json
- common/reviews/api/api-extractor-model.api.md
When a typescript project is using [isolatedModules](https://www.typescriptlang.org/tsconfig#isolatedModules), referencing exported `const` enums  is not allowed.
Setting `isolatedModules` to `true` is recommended for projects transpiled with babel or [esbuild](https://esbuild.github.io/content-types/#isolated-modules). Unlike `tsc`, these tools evaluate files independently. Setting the `isolatedModules` flag e.g. forces developers to indicate whether they are exporting a type or value, since transpilers evaluating modules independently cannot infer this information.
However, the flag also alerts when a `const` enum is used. It seems that `tsc` evaluates `const enums` across modules and inlines the constants at compile. No `enum` object is created, which is problematic of independent …
> [api-extractor-model] Remove "const" keyword before enum to use with typescript isolatedModules

- apps/rush-lib/src/cli/SelectionParameterSet.ts
- apps/rush-lib/src/cli/actions/ChangeAction.ts
- apps/rush-lib/src/cli/actions/InstallAction.ts
- apps/rush-lib/src/cli/actions/ListAction.ts
- apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
- apps/rush-lib/src/logic/Git.ts
- apps/rush-lib/src/logic/ProjectChangeAnalyzer.ts
- apps/rush-lib/src/logic/RepoStateFile.ts
- apps/rush-lib/src/logic/ShrinkwrapFileFactory.ts
- apps/rush-lib/src/logic/npm/NpmShrinkwrapFile.ts
- apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts
- apps/rush-lib/src/logic/pnpm/PnpmProjectShrinkwrapFile.ts
- apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
- apps/rush-lib/src/logic/selectors/GitChangedProjectSelectorParser.ts
- apps/rush-lib/src/logic/selectors/ISelectorParser.ts
- apps/rush-lib/src/logic/yarn/YarnShrinkwrapFile.ts
- build-tests/rush-project-change-analyzer-test/src/start.ts
- common/changes/@microsoft/rush/lockfile-diff_2021-11-30-23-57.json
- common/reviews/api/rush-lib.api.md
When running a command like `rush list --only git:HEAD`, if the set of touched files includes the lockfile and the package manager is `pnpm`, compares the old and new lockfiles to determine affected projects instead of assuming that the change affects all projects.
Adds a `getFileContent` method to the `Git` wrapper to read the content of a file at a previous commit.
Adds a `loadFromString` API to the `ShrinkwrapFileFactory` and underlying package-manager-specific files.
Updates `ProjectChangeAnalyzer` to, upon seeing a lockfile modification, if the package manager is `pnpm` (since project shrinkwraps are not implemented for other package managers), load both the old and current lockfiles and compare the project shrinkwrap entries.
Adds a `hasChanged` method to the …
> [rush] Use lockfile diffing for more granular Git changed project detection

- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/api/test/RushConfiguration.test.ts
- apps/rush-lib/src/api/test/__snapshots__/RushConfiguration.test.ts.snap
- apps/rush-lib/src/api/test/repo/rush-pnpm-5.json
- apps/rush-lib/src/api/test/repo/rush-repository-url-urls.json
- apps/rush-lib/src/logic/Git.ts
- apps/rush-lib/src/schemas/rush.schema.json
- common/changes/@microsoft/rush/multiple-remote-urls_2021-12-09-00-43.json
- common/changes/@microsoft/rush/multiple-remote-urls_2021-12-09-00-44.json
- common/reviews/api/rush-lib.api.md
Allow multiple remote URLs to be specified in the rush.json repository.url field.
This change allows repositories that have multiple possible remote URLs to specify the `repository.url` field in `rush.json`. This is useful when a GitHub repository is changed and contributors still have clones using the old repo URL (i.e. - `github.com/microsoft/web-build-tools` to `github.com/microsoft/rushstack`) or in Azure DevOps repositories that have multiple allowed URLs (i.e. `myorg.visualstudio.com` vs `dev.azure.com/myorg`).
This is a breaking change in the `RushConfiguration` API.
Added a unit test case covering this.
> [rush] Allow multiple remote URLs to be specified in the rush.json repository.url field.

- apps/rush-lib/src/cli/actions/ListAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- common/changes/@microsoft/rush/list-simultaneous-processes_2021-12-15-20-29.json
Mark rush list as safe for simultaneous rush processes.
Ran locally.
> [rush] Mark rush list as safe for simultaneous rush processes.

- apps/rush-lib/src/logic/Git.ts
- common/changes/@microsoft/rush/git-version-check_2021-12-16-00-37.json
- common/changes/@rushstack/package-deps-hash/git-version-check_2021-12-15-23-18.json
- common/reviews/api/package-deps-hash.api.md
- libraries/package-deps-hash/src/getPackageDeps.ts
- libraries/package-deps-hash/src/getRepoState.ts
- libraries/package-deps-hash/src/index.ts
- libraries/package-deps-hash/src/test/getRepoState.test.ts
Currently if a user is using a git version older than 2.30.0, `rush version` will provide a confusing error message (it prints the `git diff-index --help` message). This change checks the git version if `git diff-index` exits with a nonzero exit code and informs the user if their git version is too old.
Installed git 2.29.0 and ran `rush change -v`.
> [package-deps-hash] Provide a more useful error message if the git version is too old.

- build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
- common/changes/@rushstack/eslint-config/user-danade-ReenableEslintPluginPromise_2021-12-22-02-33.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- eslint/eslint-config/package.json
- eslint/eslint-config/profile/_common.js
Now that the `eslint-plugin-promise` package has been updated to support ESLint 8 (see https://github.com/xjamundx/eslint-plugin-promise/issues/218), we can re-enable the rule that we consumed but disabled during adding of ESLint 8 support.
Rebuilding full project
> [eslint-config] Re-enable 'eslint-plugin-promise' rules

- apps/rush-lib/src/logic/Git.ts
- common/changes/@microsoft/rush/fix--3111_2021-12-24-15-33.json
Fixes #3111
Turns out an assumption about directory where `git` is running was incorrect.
Ran `install` in both rush and reproduction repo with `core.hooksPath` both set and unset.
> [rush] Fixes git hooks install error when rush is not at the git root

- apps/rush-lib/src/cli/scriptActions/BaseScriptAction.ts
- apps/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
- common/changes/@microsoft/rush/fix-phased-commands-params-issue_2021-12-30-03-59.json
The phased builds feature currently checks all flag parameters if they're set before adding or removing phases to run for those flags. This fails if the flag isn't associated with the command.
Tested by running `rush build` in the repo where the issue was discovered.
> [rush] Fix an issue where a flag paramter not associated with the build command will cause the build to fail.

- .gitattributes
- apps/rush-lib/src/cli/actions/InitAction.ts
- common/changes/@microsoft/rush/update-gitattributes_2021-12-25-21-22.json
- common/changes/@rushstack/heft-config-file/update-gitattributes_2021-12-27-04-40.json
- libraries/heft-config-file/src/test/__snapshots__/ConfigurationFile.test.ts.snap
- libraries/heft-config-file/src/test/errorCases/invalidJson/.gitattributes
Fixes https://github.com/microsoft/rushstack/issues/3095 
We will keep https://github.com/microsoft/rushstack/issues/1467 open until this change has been applied to all other Rush Stack projects.
This also gets rid of the `.gitattributes` overrides for text files.
Ran `rush init` on Windows and on Linux.
> [rush] Update "rush init" to write files with LF line endings instead of CRLF line endings on non-Windows OSes.

- apps/rush-lib/src/api/Rush.ts
- apps/rush-lib/src/api/RushPluginsConfiguration.ts
- apps/rush-lib/src/cli/RushCommandLineParser.ts
- apps/rush-lib/src/index.ts
- apps/rush-lib/src/pluginFramework/PluginLoader/AutoinstallerPluginLoader.ts
- apps/rush-lib/src/pluginFramework/PluginLoader/BuiltInPluginLoader.ts
- apps/rush-lib/src/pluginFramework/PluginLoader/PluginLoaderBase.ts
- apps/rush-lib/src/pluginFramework/PluginManager.ts
- apps/rush/.npmignore
- apps/rush/package.json
- apps/rush/src/start-dev-docs.ts
- apps/rush/src/start-dev.ts
- common/changes/@microsoft/rush/break-cyclic-dependency_2022-01-03-01-18.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- common/reviews/api/rush-lib.api.md
Proposed as an alternative to https://github.com/microsoft/rushstack/pull/3115.
This change adds a "start-dev" entrypoint in the `apps/rush` project to run Rush with the plugins inside the repo.
This change includes some refactors to the plugin manager and adds an internal `builtInPluginConfigurations` property to `ILaunchOptions` to allow the `@microsoft/rush` project to provide plugins to rush-lib.
Tested by running `node apps/rush/lib/start-dev build` in a repo that uses the Azure build cache.
> [rush] Add a start-dev entrypoint to Rush to include the plugins inside the repo.

- apps/rush-lib/src/api/CommandLineConfiguration.ts
- apps/rush-lib/src/api/test/CommandLineConfiguration.test.ts
- apps/rush-lib/src/api/test/__snapshots__/CommandLineConfiguration.test.ts.snap
- apps/rush-lib/src/cli/scriptActions/BaseScriptAction.ts
- apps/rush-lib/src/cli/scriptActions/GlobalScriptAction.ts
- apps/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
- apps/rush-lib/src/logic/ProjectTaskSelector.ts
- common/changes/@microsoft/rush/fix-parameter-phases_2022-01-04-10-48.json
There is a mistake in the current implementation of phase/parameter associations.
The design calls for parameters to be associated with commands. If a parameter is specified when a phased command is invoked, the parameter is passed only to the phases it is associated with. The current implementation implicitly associates parameters with all commands with phases they're directly or indirectly associated with, and their values are passed on to all phases.
Tested in https://github.com/elliot-nelson/rush-phased-builds-example and this repo.
> [rush] Fix an issue with parameter associations with phases.

- common/changes/@rushstack/heft-config-file/clean-up-test-newlines_2022-01-05-00-32.json
- libraries/heft-config-file/src/test/ConfigurationFile.test.ts
- libraries/heft-config-file/src/test/__snapshots__/ConfigurationFile.test.ts.snap
We recently changed the newlines in this repo's `.gitattributes` from always CRLF to use the Git config's defaults. This broke a test that has a snapshot of an error thrown when parsing an invalid JSON file. The test was updated, but now Windows users who have old clones of the repo that don't have re-normalized newlines are expecting the previous state of the test. This PR updates the test to normalize newlines in the invalid JSON file before it is parsed to ensure a consistent error message.
This PR also cleans up the test code.
Ran the test.
> [heft-config-file] Ensure newlines in an invalid JSON file are normalized before parsing.

- apps/api-documenter/src/cli/BaseAction.ts
- apps/api-documenter/src/utils/ToSdpConvertHelper.ts
- apps/heft/src/plugins/ProjectValidatorPlugin.ts
- apps/heft/src/utilities/fileSystem/TypeScriptCachedFileSystem.ts
- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/cli/actions/InitAction.ts
- apps/rush-lib/src/cli/actions/InitAutoinstallerAction.ts
- apps/rush-lib/src/logic/ProjectWatcher.ts
- apps/rush-lib/src/logic/SetupChecks.ts
- apps/rush-lib/src/logic/Telemetry.ts
- apps/rush-lib/src/logic/base/BaseInstallManager.ts
- apps/rush-lib/src/logic/base/BaseLinkManager.ts
- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- apps/rush-lib/src/logic/deploy/DeployArchiver.ts
- apps/rush-lib/src/logic/deploy/DeployManager.ts
- apps/rush-lib/src/utilities/AsyncRecycler.ts
- apps/rush-lib/src/utilities/Utilities.ts
- build-tests/api-extractor-scenarios/src/runScenarios.ts
- build-tests/install-test-workspace/build.js
- common/changes/@microsoft/api-documenter/readdir-with-types_2022-01-05-03-42.json
- common/changes/@microsoft/rush/readdir-with-types_2022-01-05-02-00.json
- common/changes/@rushstack/heft/readdir-with-types_2022-01-05-02-00.json
- common/changes/@rushstack/node-core-library/readdir-with-types_2022-01-05-02-00.json
- common/changes/@rushstack/node-core-library/readdir-with-types_2022-01-05-03-42.json
- common/reviews/api/node-core-library.api.md
- libraries/node-core-library/src/FileSystem.ts
- libraries/node-core-library/src/LockFile.ts
- libraries/node-core-library/src/index.ts
This PR exposes a `FileSystem` API that uses the `fs.readdir(path, { withFileTypes: true })` API.
This is now used in places that previously used the `withFileTypes: true` option in the repo.
> [node-core-library] Expose and consume a FileSystem.readFolderWithTypes and FileSystem.readFolderWithTypesAsync API

- apps/rush-lib/src/utilities/Utilities.ts
- common/changes/@microsoft/rush/feat-increase-maxBuffer_2021-12-21-03-55.json
The default `maxBuffer` 1MB is too small. 
we should increase to decrease the `ENOBUFS` error when executing git command. for example:
`rush build --from git:master` will throw `ENOBUFS` error when `pnpm-lock.yaml` is larger than 1MB. 
`rush build --from git:master` execute `git cat-file blob common/config/rush/pnpm-lock.yaml` command using `child_process.spawnSync`. because `pnpm-lock.yaml` is larger than 1MB so the `ENOBUFS` is throwed.
```
$ ls -alh common/config/rush/pnpm-lock.yaml
-rw-r--r--  1 feng  staff   1.9M Dec 21 11:22 common/config/rush/pnpm-lock.yaml
$ rush --debug build --from git:master
Rush Multi-Project Build Tool 5.58.0 - https://rushjs.io
Node.js version is 14.18.1 (LTS)
Trying to acquire lock for pnpm-6.10.0
Acquired lock for pnpm-6.10.0
Found pnpm version 6.10.0 in …
```
> [rush-lib] increase maxBuffer to 10mb when `executeCommand`

- build-tests/api-documenter-test/package.json
- build-tests/api-extractor-lib2-test/package.json
- build-tests/api-extractor-lib3-test/package.json
- build-tests/api-extractor-scenarios/package.json
- build-tests/api-extractor-test-01/package.json
- build-tests/api-extractor-test-03/package.json
- build-tests/heft-typescript-composite-test/package.json
- build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
Bump `@types/jest` to `27.4.0`, the current latest version.
Rebuild
> [chore] Bump @types/jest to 27.4.0

- apps/rush/src/start-dev.ts
- common/changes/@microsoft/rush/enelson-ismanagedfalse_2022-01-05-22-41.json
Force `isManaged` to `false` in the new `start-dev` entry point.
Before the big plugin refactor, if you wanted to hack on rushstack locally and test it against your own corporate monorepo, you would use the `apps/rush-lib/lib/start.js` entry point.
That entry point probably still works fine for people who have no cloud build cache, but if you're using the Azure or S3 cloud build cache plugins, this entry point doesn't work anymore.  So I think the new "default" entry point for local hacking is probably `apps/rush/lib/start-dev.js`.
Given that, and that this entry point doesn't have an external `bin` script, I think it should do what `rush-lib/lib/start.js` does and hard-code `isManaged` to `false`.  That way whenever you're running a local copy of this entry point you get the unmanaged …
> [rush] start-dev script should assume unmanaged

- apps/rush/src/RushCommandSelector.ts
- common/changes/@microsoft/rush/enelson-fix-builtin-option_2022-01-05-17-09.json
Fix a small issue discovered while attempting to run the new `lib/start-dev` script from another monorepo.
The `start-dev.js` script adds in the built-in plugins so that they'll be automatically loaded by PluginManager, but the options weren't being passed down all the way.  This caused issues when used in a repo other than rushstack.
- Tested locally both inside and outside rushstack.
> [rush] Pass down builtInPluginConfigurations

- apps/heft/README.md
- common/changes/@rushstack/debug-certificate-manager/fix-special-chars_2022-01-06-00-13.json
- common/changes/@rushstack/heft/fix-special-chars_2022-01-06-00-13.json
- libraries/debug-certificate-manager/src/CertificateManager.ts
VSCode called out a character ([here](https://github.com/microsoft/rushstack/blob/master/libraries/debug-certificate-manager/src/CertificateManager.ts#L426)) that is "ambiguous," which is an actual bug. I wrote a little script to replace those in a repo: https://gist.github.com/iclanton/6956d1a0e98737393d70c5d7f70484ec
This PR replaces them across the repo.
> Fix some instances of "confusable" characters.

- apps/rush-lib/src/api/RushProjectConfiguration.ts
- apps/rush-lib/src/api/test/RushProjectConfiguration.test.ts
- apps/rush-lib/src/api/test/jsonFiles/rush-project-base.json
- apps/rush-lib/src/api/test/jsonFiles/test-project-a/config/rush-project.json
- apps/rush-lib/src/api/test/jsonFiles/test-project-b/config/rush-project.json
- common/changes/@microsoft/rush/extend-phase-projectOutputFolderNames_2022-01-06-07-41.json
The `config/rush-project.json` file contains a `projectOutputFolderNames` property that is appended to when the config file extends another file containing that property. There is a similar property (the `projectOutputFolderNames` array) defined per phase in the items of the `phaseOptions` property, but this array doesn't currently support concatenation from a parent file. This change adds support for that.
Added a unit test.
> [rush] Merge the phase projectOutputFolderNames arrays in rush-project.json config files.

- .gitattributes
- apps/rush-lib/assets/rush-init/[dot]gitattributes
- apps/rush-lib/assets/rush-init/rush.json
- common/changes/@microsoft/rush/feat-pnpm-lock-conflict_2022-01-06-08-44.json
1. turn on `useWorkspaces` in `rush init` template.
2. set `pnpm-lock.yaml` merge driver to `text` in this repo and `rush init` template.
This was one of the topics discussed in October's Rush Hour. Everyone agreed that PNPM 6 lockfiles can be safely merged as text. Microsoft said they have been running this way for some time without any conflicts.
> feat(rush-lib): settings change for pnpm lockfile

- apps/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
- apps/rush-lib/src/logic/ProjectTaskSelector.ts
- common/changes/@microsoft/rush/fix-unsafe-selectors-in-phased-commands_2022-01-07-00-28.json
Fixes behavior of the unsafe `--only` `--impacted-by` and `--impacted-by-except` selection parameters with respect to the task selector. A regression was introduced during the phased command implementation that project dependencies were forcibly included.
Restores the filtering of the project graph to elide projects that are not included by the selection.
Verified `node ./apps/rush-lib/lib/start.js build -o module-minifier-plugin` selects exactly one project
> [rush-lib] Fix regression in bulk commands with unsafe selectors

- apps/rush-lib/src/logic/ProjectTaskSelector.ts
- common/changes/@microsoft/rush/fix-regular-build_2022-01-07-02-03.json
Previous fix broke `rush build` when not specifying `rush build -o` due to trying to add dependencies before the tasks were fully generated.
Registering dependencies requires the Task objects to have been created, therefore must run after the initial pass (or use a depth-first search, but that makes the code less readable).
node ./apps/rush-lib/lib/start.js build -v
node ./apps/rush-lib/lib/start.js build -v -o terminal -o rush-lib -o node-core-library
node ./apps/rush-lib/lib/start.js build -v -t rush-lib
node ./apps/rush-lib/lib/start.js build -v -i rush-lib
node ./apps/rush-lib/lib/start.js build -v -f node-core-library
> [rush-lib] Fix regression that completely broke "rush build"

- common/config/azure-pipelines/templates/build.yaml
In order to validate that the built assets can re-construct the build graph properly, we re-run build using the newly built assets. Rebuild is unnecessary since the goal is to validate the tasks were run in the correct order.
Build of this PR.
> [chore] Run build using rush-lib assets after initial rebuild

- apps/rush-lib/src/api/RushProjectConfiguration.ts
- apps/rush-lib/src/api/test/RushProjectConfiguration.test.ts
- apps/rush-lib/src/api/test/jsonFiles/rush-project-base.json
- apps/rush-lib/src/api/test/jsonFiles/test-project-a/config/rush-project.json
- apps/rush-lib/src/api/test/jsonFiles/test-project-b/config/rush-project.json
- apps/rush-lib/src/logic/taskExecution/ProjectTaskRunner.ts
- apps/rush-lib/src/schemas/anything.schema.json
- apps/rush-lib/src/schemas/rush-project.schema.json
- apps/rush/UPGRADING.md
- common/changes/@microsoft/rush/update-rush-project.json_2022-01-15-17-49.json
- common/config/azure-pipelines/templates/build.yaml
This PR updates the schema of `rush-project.json` to follow the proposal here: https://github.com/microsoft/rushstack/issues/2300#issuecomment-1012622369
Note that this change removes the validation step that ensures phases/operations are defined in the repo's `command-line.json`
https://github.com/elliot-nelson/rush-phased-builds-example/pull/7
> [rush] Update rush-project.json to follow new proposed schema.

- apps/rush-lib/src/logic/taskExecution/ProjectTaskRunner.ts
- common/changes/@microsoft/rush/fix-warningsInSuccessfulBuild_2022-01-18-16-07.json
Fixes https://github.com/microsoft/rushstack/issues/3165.
This was regressed in https://github.com/microsoft/rushstack/pull/3113
Ran `rush test` in https://github.com/gesiu/rush-warnings
> Fix the "allowWarningsInSuccessfulBuild" option in command-line.json

- apps/rush-lib/src/api/RushProjectConfiguration.ts
- common/changes/@microsoft/rush/fix-overlapping-paths-check_2022-01-18-20-35.json
This issue was found when testing Rush@5.60.0-rc.0. If a `rush-project.json` has matching lists of folders for `build` and `_phase:build` operations, validation will fail. This change checks for overlapping folders only among operations that will be invoked by a single command. For example, if `rush build` invokes `_phase:build` and `_phase:test`, and `_phase:build` and `_phase:lint` have overlapping output folders, there is no error because `_phase:build` and `_phase:lint` aren't invoked by the same command.
Confirmed https://github.com/microsoft/rushstack/pull/3144 is fixed, and introduced an issue in a phased repo to confirm the expected behavior.
> [rush] Only check for overlapping output folders within operations that will be invoked as part of the same command.

- common/changes/@rushstack/heft-node-rig/node-rig-dist_2022-01-20-23-06.json
- rigs/heft-node-rig/profiles/default/config/rush-project.json
This change includes `dist` in the list of cached folders for the "build" operations in Heft's Node rig. Our standard is to drop API Extractor rollups in the `dist` folder.
> [heft-node-rig] Include "dist" in the list of cached folders in heft-node-rig.

- common/changes/@rushstack/package-deps-hash/package-deps-fixes_2022-01-20-22-07.json
- common/changes/@rushstack/package-deps-hash/package-deps-fixes_2022-01-20-22-42.json
- common/changes/@rushstack/package-deps-hash/package-deps-fixes_2022-01-20-22-43.json
- libraries/package-deps-hash/src/getRepoState.ts
- libraries/package-deps-hash/src/test/getRepoState.test.ts
Fixes #3163 
Fixes #3109
Reduces the minimum version of Git required by `getRepoState` to `2.20.0` by removing `--merge-base` from `getRepoChanges` and documenting the behavior change.
Fixes a bug in `getRepoState` with regards to parsing the output of `git status`. Added unit tests for `parseGitStatus`.
New unit tests for `parseGitStatus` covering a range of statuses.
Verified that `node ./apps/rush-lib/lib/start.js build -o git:HEAD` correctly handles a file being renamed in the index.
> [package-deps-hash] Reduce minimum git version to 2.20.0, fix working tree state computation

- apps/rush-lib/src/api/CommandLineConfiguration.ts
- apps/rush-lib/src/pluginFramework/PluginLoader/PluginLoaderBase.ts
- common/changes/@microsoft/rush/fix-plugin-command-line_2022-01-14-07-23.json
Fixes https://github.com/microsoft/rushstack/issues/3155
Add a option named `disableDefaultBuildCommands` for `CommandLineConfiguration`, when plugin calls `CommandLineConfiguration` set up `disableDefaultBuildCommands` to true to avoid duplicate build command definitions.
Local
> [rush-lib] Fix plugin command line

- apps/rush-lib/src/api/CommandLineConfiguration.ts
- common/changes/@microsoft/rush/fix-build-rebuild-defaults_2022-01-21-00-40.json
Rush allows a repo maintainer to specify only the options that they specifically want to override in `common/config/rush/command-line.json` for the "build" and "rebuild" commands. This is broken if the maintainer wants to make build a phased command.
This change fixes population of the summary, description, and other default options for build and rebuild by allowing these to apply to both bulk and phased commands and by eliminating the options that aren't shared between the two from the defaults (all of which were already set to the defaults for a bulk command).
Tested by removing all but the `"commandKind"`, `"name"`, and `"phases"` options from `common/config/rush/command-line.json` in this branch: https://github.com/microsoft/rushstack/pull/3145
> [rush] Fix an issue with adding the default options to the build and rebuild commands.

- common/config/rush/experiments.json
- common/config/rush/repo-state.json
This cuts down on noise in the `repo-state.json` file.
> Enable the omitImportersFromPreventManualShrinkwrapChanges option.

- apps/rush-lib/src/logic/pnpm/PnpmProjectShrinkwrapFile.ts
- common/changes/@microsoft/rush/stekycz-bugfix-pnpm-git-diff_2022-01-21-14-08.json
Using PNPM and subset selection with git fails when new project is added in the diff commits.
I wanted to list affected projects by changes in my branch. The change was addition of a new project. Therefore, I wanted to use `rush list --impacted-by git:<hash>` command.  However, it failed with `Cannot get dependency key for temp project: <project_name>`.
Considerations:
1. The change should not (negatively) impact any other use cases.
2. I do not want to remove throwing the error because the error might be important in other use cases. Therefore, return `undefined` from `generateLegacyProjectShrinkwrapMap` is not possible.
3. I might be able to detect it in `ProjectChangeAnalyzer`, however, it would not fix it for other `hasChanges` calls.
4. It make sense to me to say the project has …
> [rush] Fix project change detection for new projects using PNPM

- apps/rush-lib/src/api/BuildCacheConfiguration.ts
- apps/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- common/changes/@microsoft/rush/local-cache-write-disable_2021-11-30-01-27.json
Modifies ProjectBuildCache to respect the `RUSH_BUILD_CACHE_WRITE_ALLOWED` environment variable globally, instead of being a per-provider setting. This means that setting it will disable writes to both the local cache and the cloud cache, if both apply.
If `process.env.RUSH_BUILD_CACHE_WRITE_ALLOWED === '0'`, no cache writes will be performed whatsoever. Expected to be of utility for CI machines where the local state is ephemeral and therefore constructing the local cache entry is wasted work.
Updates watch mode commands to disable build cache writes to improve performance and avoid flooding the cache.
Ran a local build without the environment variable and verified that cache write was performed.
Set the variable and ran a local build, verified that no cache write was performed.
Ran a …
> [rush] Allow disabling local cache writes, disable during watch mode

- README.md
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- rush-plugins/rush-serve-plugin/.eslintrc.js
- rush-plugins/rush-serve-plugin/.npmignore
- rush-plugins/rush-serve-plugin/LICENSE
- rush-plugins/rush-serve-plugin/README.md
- rush-plugins/rush-serve-plugin/config/jest.config.json
- rush-plugins/rush-serve-plugin/config/rig.json
- rush-plugins/rush-serve-plugin/package.json
- rush-plugins/rush-serve-plugin/src/index.ts
- rush-plugins/rush-serve-plugin/src/schemas/rush-serve.schema.json
- rush-plugins/rush-serve-plugin/src/test/Server.test.ts
- rush-plugins/rush-serve-plugin/tsconfig.json
- rush.json
Creates a new stub project for a Rush plugin that uses an `express` server to serve project outputs.
Empty project.
Verified that `rush build` still works. Plugin is not yet expected to do anything.
> [rush-serve-plugin] Add stub project for rush-serve-plugin

- apps/rush-lib/src/api/CommandLineConfiguration.ts
- common/changes/@microsoft/rush/fix-bulk-command-build-cache_2022-01-28-15-56.json
Build cache cannot be enabled for bulk build command.
If bulk build command is defined in 'command-line.json', build command's `disableBuildCache` property is always true.
reproduction step:
1. defined a bulk build command in `command-line.json`
```
{
"commands": [
{
"commandKind": "bulk",
"name": "build",
"allowWarningsInSuccessfulBuild": true,
"summary": "Build packages.",
"ignoreMissingScript": true,
"enableParallelism": true
}
]
}
```
2. enable `local-only` build cache(https://rushjs.io/pages/maintainer/build_cache/)
3. test build cache not work: because it is disabled
Test locally using my company's project which build cache cannot be enabled for bulk build command.
1. defined a bulk build command in `command-line.json`
```
{
"commands": [
{
"commandKind": "bulk",
"name": "build", …
```
> fix: build cache cannot be enabled for bulk build command

- apps/rush-lib/src/schemas/rush-plugin-manifest.schema.json
- common/changes/@microsoft/rush/build-cache-plugins-for-other-commands_2022-01-28-19-53.json
- rush-plugins/rush-amazon-s3-build-cache-plugin/rush-plugin-manifest.json
- rush-plugins/rush-azure-storage-build-cache-plugin/rush-plugin-manifest.json
Currently the build-in build cache plugins only work for the `build` and `rebuild` commands. Creating a custom command in `common/config/command-line.json` does not caching on Azure or S3, and Rush gives a confusing `ERROR: Unexpected cache provider: azure-blob-storage` error message.
This change updates the build-in cache provider plugins' manifest to consider them relevant for all commands.
Ran a custom phased command on a repo that has Azure Storage caching configured.
> [rush] Remove the command associations from the build-in cache provider commands.

- apps/rush/UPGRADING.md
This updates the property name in the UPGRADING.md guide to match the [corresponding schema](https://github.com/microsoft/rushstack/blob/master/apps/rush-lib/src/schemas/rush-project.schema.json#L27)
If using the property name currently present in the UPGRADING.md an operation fails with the following error:
```
JSON validation failed:
/drone/src/site-server/common/tools/api-documenter/config/rush-project.json
Error: #/ (For use with the Rush tool, this file...)
Additional properties not allowed: disableBuildCache
```
Due to the rush-project.json not validating against the schema.
I changed the property name in my own rush project after seeing the error, and the error no longer occurred.
> docs: Fix property name in rush-project.json to match schema

- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- apps/rush-lib/src/utilities/TarExecutable.ts
- common/changes/@microsoft/rush/optimize-tar_2021-11-09-22-50.json
- common/changes/@microsoft/rush/tar-stdin_2022-02-02-22-00.json
- common/changes/@microsoft/rush/tar-stdin_2022-02-02-22-27.json
- common/changes/@microsoft/rush/tar-stdin_2022-02-02-22-38.json
Passes input file paths via `stdin` instead of creating a temporary file.
Use multiple parallel async file system operations when scanning for symbolic links.
Create a separate log file for each phase in a project that writes to the build cache.
Modify local TAR generation to write to a temp file, then move it to the build cache, to ensure that the cache doesn't get polluted with partial entries.
Leverages`Async.forEachAsync` with a queue to scan output files.
Uses the tarball name as part of the log file path, so that each phase gets its own log file.
Logs the list of files to cache to the tar log.
Local Rush builds, writing to and reading from the build cache.
> [rush-lib] Optimizations for interacting with `tar` utility

- apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
- apps/rush-lib/src/logic/pnpm/test/PnpmShrinkwrapFile.test.ts
- common/changes/@microsoft/rush/fix-bitbucket-version-specifier_2022-02-03-19-37.json
Fixes https://github.com/microsoft/rushstack/issues/3189.
PNPM has introduced a new package specifier format for packages hosted as non-Github Git repositories. This update fixes parsing for that.
Created a repo with a single project, using PNPM `6.28.0`. Added a dependency with version `"ssh://git@bitbucket.org:atsikov-revo/rush-pnpm-test#master"`. Updated the `pnpm-lock.yaml` file to make that package's specifier `git@bitbucket.org+atsikov-revo/rush-pnpm-test/3466c37ef722d130d9bbcd14c72a89c409432d66`. Ran `rush purge` and `rush install`. Confirmed that this was broken before and works now.
> [rush] Include a new possible PNPM lockfile version specifier.

- apps/rush-lib/src/logic/Git.ts
- common/changes/@microsoft/rush/user-danade-FixDriveCasingGitHooks_2022-02-05-00-26.json
Node can sometimes be inconsistent with drive letter casing. The library we obtain the `.git` directory from can sometimes provide the incorrect drive letter casing when running on Windows, which breaks our comparison to the (correctly cased) path to the Rush repo. This check ensures that the drive letter casing from the library matches the true drive letter casing.
> [rush-lib] Fix git-hooks error when drive letter casing does not match

- apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
- common/changes/@microsoft/rush/fix-file-collector_2022-02-06-03-42.json
Currently, there is an issue with the algorithm that iterates through files that will be passed to `tar`. If there are fewer than 10 (the folder iteration concurrency) subfolders inside the folders that are to be cached, folders more than two levels deep will not be iterated through, so their files will not be cached. This happens because the iterator completes before any of the tertiary-level folders are added to the queue.
This PR fixes the issue by iterating through each folder level serially instead of trying to add all subfolders to the same queue. This can result in slightly less parallelism, but it will always capture all folders.
Tested on a project with four subfolders inside its `lib` folder and files more than three levels deep that produced cache entries that are missing …
> [rush] Fix an issue with folder iteration during caching.

- common/changes/@microsoft/rush/rush-sdk-webpack_2022-02-05-03-03.json
- common/config/rush/pnpm-lock.yaml
- libraries/rush-sdk/config/typescript.json
- libraries/rush-sdk/package.json
- libraries/rush-sdk/src/index.ts
- libraries/rush-sdk/src/test/script.test.ts
- libraries/rush-sdk/tsconfig.json
Currently `rush-sdk` can't be used in a project that has been bundled with Webpack.
This PR replaces instances of `require()` in `rush-sdk` with a call to a function that detects if we're executing inside a webpack bundle and calls a Webpack macro function that maps to the real `require` function instead of the built-in Webpack require (which errors in this case).
Tested by bundling a small tool that uses `rush-lib` via `rush-sdk` with Webpack 5 and executing the bundle.
> [rush] Add support for rush-sdk to be webpacked.

- apps/rush-lib/src/api/CommandLineConfiguration.ts
- apps/rush-lib/src/api/CommandLineJson.ts
- apps/rush-lib/src/cli/RushCommandLineParser.ts
- apps/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
- apps/rush-lib/src/logic/ProjectWatcher.ts
- apps/rush-lib/src/schemas/command-line.schema.json
- common/changes/@microsoft/rush/watch-phases_2022-01-24-22-18.json
Adds a new property `"watchOptions"` with a subproperty `"watchPhases"` to `"commandKind": "phased"` in `command-line.json`. If `watchOptions` is specified and `watchPhases` is non-empty, then after the initial command execution, the command will boot up a file watcher and, upon detecting changes, run the phases listed in `"watchPhases"` for all affected projects.
The prior `"watchForChanges": true` option for `"commandKind": "bulk"` is now implemented by setting `watchPhases` to `phases` during command translation and `alwaysWatch` to `true`, or an empty set if `false`.
This logic change now treats the watch mode portion of command execution as a separate step after the initial execution. Build cache writes are allowed during the initial execution (since it should run all projects and is …
> [rush-lib] Add `"watchOptions"` with `watchPhases` to "phased" command kind

- apps/rush-lib/src/logic/setup/KeyboardLoop.ts
- common/changes/@microsoft/rush/octogonz-rush-git-bash_2022-02-09-00-16.json
Fixes #3217
- I used Git Bash to reproduce the error from #3217, and then confirmed that it is fixed when `rush setup` is invoked using the code from this PR branch
- To test the case where the TTY is missing without Git Bash, I used Cmd.exe to invoke `rush setup < empty-file`
- I tested each of the 3 workarounds from the error message text
CC @elliot-nelson
> [rush] Fix an issue where "rush setup" reported a TypeError when invoked from Git Bash

- apps/api-documenter/src/documenters/OfficeYamlDocumenter.ts
- common/changes/@microsoft/api-documenter/AlexJ-OfficeDocumenter_2022-02-08-00-43.json
There's an override in the Office-specific DocFX YAML generator to add a link to API sets. This is done for each application, but PowerPoint was omitted from the initial list due to lack of support. This PR adds that option to reflect the current state of [PowerPoint API sets](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/powerpoint-api-requirement-sets).
This was tested in the [OfficeDev/office-js-docs-reference](https://github.com/OfficeDev/office-js-docs-reference) repo. This should be the only place using this version of ApiDocumenter.
> [api-documenter] Adding PowerPoint option to OfficeYamlDocumenter API set mapping

- apps/rush-lib/src/logic/test/PublishUtilities.test.ts
- common/changes/@microsoft/rush/ianc-improve-test-readability_2022-02-09-04-43.json
To produce a more useful diff in https://github.com/microsoft/rushstack/pull/3213, this PR makes the PublishUtilities test results more readable.
This changes a set of assertions that used to look like this:
```TypeScript
expect(allChanges.packageChanges.size).toEqual(5);
expect(allChanges.versionPolicyChanges.size).toEqual(0);
expect(allChanges.packageChanges.get('a')).not.toBeUndefined();
expect(allChanges.packageChanges.get('b')).not.toBeUndefined();
expect(allChanges.packageChanges.get('e')).not.toBeUndefined();
expect(allChanges.packageChanges.get('g')).not.toBeUndefined();
expect(allChanges.packageChanges.get('h')).not.toBeUndefined();
expect(allChanges.packageChanges.get('a')!.changeType).toEqual(ChangeType.patch);
expect(allChanges.packageChanges.get('b')!.changeType).toEqual(Chang …
```
> [rush] Improve the PublishUtilities test readability.

- apps/rush-lib/src/cli/actions/ChangeAction.ts
- common/changes/@microsoft/rush/rf-nested-rush-change-verify_2022-02-09-22-07.json
This command would fail before for nested Rush repos (Rush repos that aren't at the root of the git repo) even after adding changelogs -- the code gathering the changed projects worked properly but the code gathering the changelogs did not.  It was using a hardcoded `common/changes` path from the git repo root.  Instead we pull the resolved changes folder off the Rush configuration.
Not sure how to test this exactly but hoping the bug and fix are obvious to maintainers.
> [rush-lib] fix bug in `rush change --verify` for nested Rush repos

- build-tests/localization-plugin-test-02/webpack.config.js
- common/changes/@rushstack/module-minifier-plugin/async-import-compression_2022-01-19-00-28.json
- common/reviews/api/module-minifier-plugin.api.md
- webpack/module-minifier-plugin/src/AsyncImportCompressionPlugin.ts
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.ts
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.types.ts
- webpack/module-minifier-plugin/src/PortableMinifierIdsPlugin.ts
Adds an option `compressAsyncImports: true` to `ModuleMinifierPlugin` that, if specified, reduces the API call size of webpack async import expressions by combining all chunk imports and the final module import into a single call to the webpack runtime. Also creates a lookup table of frequently used chunk sets to further reduce code size.
Converts expressions like `Promise.resolve([__webpack_require__.e(1), __webpack_require__.e(2)]).then(__webpack_require__.bind(23))` to the more concise `__webpack_require__.ee([1,2 ], 23)`
Build test project `localization-plugin-test-02`
Linking inside a private repo with a large quantity of async imports.
> [module-minifier-plugin] Async import compression

- apps/rush-lib/src/cli/actions/PublishAction.ts
- apps/rush-lib/src/logic/PublishGit.ts
- apps/rush-lib/src/logic/test/PublishGit.test.ts
- common/changes/@microsoft/rush/fix-git-tagging_2022-02-09-23-28.json
Linked issue: https://github.com/microsoft/rushstack/issues/3222
These changes address the bug here (in part 4): https://github.com/microsoft/rushstack/issues/2536
This PR fixes how git tags are added after a `prerelease` is published.
If the publish command was: `rush publish --apply --publish --tag beta --prerelease-name beta`
The old git tag would be:
`projectName_projectVersion`
With this change the tag will be:
`projectName_projectVersion-beta`
This is a problem because it can cause conflicting git tags, which could cause pipelines to fail before they finish building.
> [rush-lib] Add publish command line arg tag to git tag

- common/changes/@microsoft/rush/remove-mjs_2022-02-11-03-37.json
- libraries/rush-sdk/config/typescript.json
- libraries/rush-sdk/package.json
Because of the way `rush-sdk` re-exports `rush-lib`, it is only possible to compile it to CommonJS. We shipped an ES-style file, but webpack doesn't know what to do with the `Object.defineProperty(exports, ...)` in an ES module.
> [rush] Remove the index.mjs export from rush-sdk.

- apps/rush-lib/src/utilities/AsyncRecycler.ts
- common/changes/@microsoft/rush/sachinjoseph-no-powershell-profile_2022-02-14-19-20.json
The AsyncRecycler task on Windows uses PowerShell to delete files, and PowerShell command by default loads the User Profile which usually does things like loading modules like PoshGit which are unnecessary for AsyncRecycler.
This PR prevents loading the PowerShell User Profile and hence prevents some unnecessary code from being run.
> [rush-lib] Don't load the PowerShell Profile for the AsyncRecycler task

- common/changes/@microsoft/load-themed-styles/load-themed-styles-no-tslib_2022-02-15-01-13.json
- common/config/rush/pnpm-lock.yaml
- common/config/rush/repo-state.json
- libraries/load-themed-styles/package.json
- libraries/load-themed-styles/tsconfig.json
https://github.com/microsoft/rushstack/pull/3204 added the `"importHelpers": true` property to the `tsconfig` in `heft-web-rig`, which was a breaking change. This change removes it from that project.
Built.
> Do not import helpers in load-themed-styles.

- common/changes/@rushstack/module-minifier-plugin/module-minifier-hash_2022-02-16-00-50.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- common/reviews/api/module-minifier-plugin.api.md
- webpack/module-minifier-plugin/README.md
- webpack/module-minifier-plugin/package.json
- webpack/module-minifier-plugin/src/LocalMinifier.ts
- webpack/module-minifier-plugin/src/MessagePortMinifier.ts
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.ts
- webpack/module-minifier-plugin/src/ModuleMinifierPlugin.types.ts
- webpack/module-minifier-plugin/src/NoopMinifier.ts
- webpack/module-minifier-plugin/src/ParallelCompiler.ts
- webpack/module-minifier-plugin/src/WorkerPoolMinifier.ts
Ensures that `@rushstack/module-minifier-plugin` is accounted for in the webpack chunk hash and compilation hash.
Includes the plugin version and all top-level options as part of the webpack chunk hash calculation. Added documentation about leveraging the webpack `output.hashSalt` field if necessary to change the hash for changes to, e.g. the minifier configuration, since that is out of the direct scope of information readily processable by this plugin.
Verified that the compilation hash changed with the updated plugin. Unfortunately the compilation and chunk hashes without the plugin appear to already be unstable (several runs yielded distinct hashes).
> [module-minifier-plugin] Update webpack hash calculations

- apps/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
- common/changes/@microsoft/rush/fix-watch-errors_2022-02-17-01-57.json
- common/config/rush/command-line.json
Fixes watch-mode commands behavior if the initial build encounters errors to still start watching for changes, since the typical use case is to run a build in watch mode and requiring the command to be initiated from a good state is counterproductive.
If a command is configured to watch, warnings or failures in the initial execution no longer terminate the action.
Defined a command `rush start` in the Rush Stack repo. The command performs an initial build using `_phase:build` and then enters watch mode, running both `_phase:build` and `_phase:test` on affected projects.
> [rush-lib] Continue on failure in watch mode commands

- apps/rush-lib/src/cli/actions/ChangeAction.ts
- common/changes/@microsoft/rush/fix-change-root_2022-02-22-21-43.json
Fixes #3247 
Fixes conversion of change file paths from relative to absolute.
Local runs of `rush change` to verify lack of regression.
> [rush-lib] Fix resolution of change file paths when rush.json is not at the Git root

- apps/rush-lib/src/api/CommandLineConfiguration.ts
- apps/rush-lib/src/cli/RushCommandLineParser.ts
- apps/rush-lib/src/cli/actions/BaseRushAction.ts
- apps/rush-lib/src/cli/scriptActions/GlobalScriptAction.ts
- apps/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
- apps/rush-lib/src/index.ts
- apps/rush-lib/src/logic/operations/test/OperationSelector.test.ts
- apps/rush-lib/src/pluginFramework/RushLifeCycle.ts
- common/changes/@microsoft/rush/new-rush-hooks_2022-02-25-22-08.json
- common/reviews/api/rush-lib.api.md
Adds Rush lifecycle hooks for global command and phased command execution. Allows to tap for all commands or by name.
Updates the Rush lifecycle hooks to pass the currently executing command object.
Split from #3225 .
Adds a `runAnyPhasedScriptCommand` hook that runs after `initialize` but before the more specific `runPhasedScriptCommand.for(commandName)` hook.
Adds a `runAnyGlobalScriptCommand` hook that runs after `initialize` but before the more specific `runGlobalScriptCommand.for(commandName)` hook.
Passes the currently executing command to the relevant hook, so that properties (and minimally the name) can be read by the plugin.
Waiting for #3245 before adding hooks to phased commands directly.
Verified that existing phased and global commands still work. Using the new hooks is for a …
> [rush-lib] Add hooks for phased/global commands

- apps/rush-lib/src/api/LastInstallFlag.ts
- apps/rush-lib/src/logic/Autoinstaller.ts
- common/changes/@microsoft/rush/enelson-lastinstall_2022-03-02-14-13.json
If the entire monorepo has been moved (that is, the root folder of the monorepo was renamed on disk), then on _Windows_, various links no longer work correctly.
As an example:
```console
cd Acme
rush prettify
cd ..
move Acme Acme2
cd Acme2
rush prettify
```
By tracking the absolute path of the `rush.json` folder in the last install state, this issue will automatically be detected.
Took the simplest route and updated both autoinstallers and common/temp flags.  In my testing so far, Linux and MacOS actually worked fine _without_ this flag, so technically we could wrap it in a platform check if we want.
(On the one hand, moving an entire monorepo around seems like a rare occurrence.  On the other hand, forcing rush install can be a 5+ minute ordeal in some monorepos, so I don't want to do it …
> [rush] Force reinstalls if the monorepo absolute path changes

- apps/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
- apps/rush-lib/src/logic/operations/AsyncOperationQueue.ts
- apps/rush-lib/src/logic/operations/IOperationRunner.ts
- apps/rush-lib/src/logic/operations/NullOperationRunner.ts
- apps/rush-lib/src/logic/operations/Operation.ts
- apps/rush-lib/src/logic/operations/OperationExecutionManager.ts
- apps/rush-lib/src/logic/operations/OperationExecutionRecord.ts
- apps/rush-lib/src/logic/operations/OperationSelector.ts
- apps/rush-lib/src/logic/operations/OperationStatus.ts
- apps/rush-lib/src/logic/operations/ShellOperationFactory.ts
- apps/rush-lib/src/logic/operations/ShellOperationRunner.ts
- apps/rush-lib/src/logic/operations/ShellOperationRunnerFactory.ts
- apps/rush-lib/src/logic/operations/test/AsyncOperationQueue.test.ts
- apps/rush-lib/src/logic/operations/test/MockOperationRunner.ts
- apps/rush-lib/src/logic/operations/test/OperationExecutionManager.test.ts
- apps/rush-lib/src/logic/operations/test/OperationSelector.test.ts
- apps/rush-lib/src/logic/operations/test/__snapshots__/OperationExecutionManager.test.ts.snap
- apps/rush-lib/src/logic/operations/test/__snapshots__/OperationSelector.test.ts.snap
- common/changes/@rushstack/heft/operation-execution-record_2022-02-10-02-09.json
Refactors internals of phased commands to prepare a cleaner public API surface for plugins that impact scheduling or provide custom operation runners.
Separates the concerns of `Operation`, which is a graph node while declaring what will be run, from `OperationExecutionRecord`, which is the runtime entity at execution time that includes the result state.
Local phased build executions.
> [rush-lib] Split out `OperationExecutionRecord` from `Operation`

- apps/rush-lib/src/logic/operations/OperationExecutionManager.ts
- common/changes/@microsoft/rush/fix-verbose-log_2022-03-09-23-38.json
Fixes a regression in the "Selected ${x} operations:" verbose log for phased commands.
Ensures that architectural no-ops in the operation graph are not displayed.
Ran `rush build -v -o rush-lib` and verified that only the operations pertaining to the `@microsoft/rush-lib` project were displayed.
> [rush-lib] Fix verbose logging for selected operations

- apps/api-documenter/src/cli/YamlAction.ts
- apps/api-documenter/src/documenters/YamlDocumenter.ts
- common/changes/@microsoft/api-documenter/master_2022-03-19-05-04.json
As mentioned by @rbuckton in  #3268, a Pull Request #2382 makes it impossible to use api-documenter along with DocFX 2.x. In other words, no one except of Microsoft can use it anymore. 
The reason is quite trivial - after api-documenter generates valid DocFX 2.x YAML files (UDP format), it converts them to a new SDP format supported only by DocFX 3.x. 
[    convertUDPYamlToSDP(outputFolder);
](https://github.com/microsoft/rushstack/blob/b03815b3a3c273972344ccebe55c36da7e59ac2f/apps/api-documenter/src/documenters/YamlDocumenter.ts#L117)
To solve this problem I have added a new flag for the `api-documenter yaml` command - `--yaml-format`, which allows for choosing whether to produce UDP or SDP YAML files.
Fixes #3268
I have added a flag `--yaml-format` which can used in this way: 
```
$ …
```
> [api-documenter] Added a CLI flag to choose between UDP and SDP YAML formats

- apps/rush-lib/src/logic/operations/ShellOperationRunner.ts
- common/changes/@microsoft/rush/fix-cache-write_2022-03-25-22-29.json
Fixes cache writes during build.
Fixes #3287 
The `ShellOperationRunner` (which is currently the only runner that supports the build cache) now defaults cache write eligibility to `true` instead of `false`. Disabling is handled via propagation from upstream operations.
Ran `rush build`.
Deleted the build cache.
Ran `node ./apps/rush-lib/lib/start.js build`
Ran `node ./apps/rush-lib/lib/start.js build` again and verified that the result came from the build cache
> [rush-lib] Fix cache write behavior

- apps/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/logic/operations/OperationExecutionManager.ts
- apps/rush-lib/src/logic/operations/test/OperationExecutionManager.test.ts
- apps/rush-lib/src/logic/operations/test/__snapshots__/OperationExecutionManager.test.ts.snap
- apps/rush-lib/src/utilities/Stopwatch.ts
- common/changes/@microsoft/rush/enelson-timeline-chart_2022-03-30-16-14.json
For rush bulk actions that support parallelism (like `build`), support an additional `--timeline` flag parameter that generates additional detail about the build timeline.
Although interesting locally, the primary goal is to add a single flag that can be used in CI environments so that monorepo administrators can easily compare the behavior of `rush build` on different machines, operating systems, with different project selector flags, etc.
Original output proposed in https://github.com/microsoft/rushstack/pull/3139, this one cleans it up and adjusts the naming post-phased-builds.
> In our monorepo, having a flag like this would be _very_ useful -- we're currently experimenting with different hardware for our builds and more details about how many CPUs we can effectively make use of, …
> [rush] Generate timeline chart on optional --timeline flag

- apps/rush-lib/src/api/Rush.ts
- apps/rush-lib/src/cli/RushCommandLineParser.ts
- apps/rush-lib/src/cli/actions/BaseRushAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/scripts/install-run-rush.ts
- apps/rush-lib/src/scripts/install-run.ts
- apps/rush-lib/src/utilities/Utilities.ts
- apps/rush/src/MinimalRushConfiguration.ts
- common/changes/@microsoft/rush/enelson-quiet_2022-03-21-16-19.json
Make support for `-q/--quiet` consistent for both direction execution and for `install-run-rush` scripts.
The goal is that whether you're running `rush`, `rushx`, or one of their `install-run` variants, you can specify `-q / --quiet` to suppress any startup output.
For `rushx`, the `install-run-rushx` script now honors the `-q/--quiet` flag in the same way as direct execution:
(In this example, script `"hello"` is defined as `"echo hello"`.)
```console
> rushx --quiet hello
hello
> node ../../common/scripts/install-run-rushx.js --quiet hello
hello
```
For `rush`, the `-q/--quiet` flag has been _added_ as a pre-command flag, similar to `-d/--debug`. It operates in the same way it does with rushx, which is to suppress all informational and diagnostic information printed at startup.
```
> …
```
> [rush] Make --quiet flags more consistent

- common/changes/@rushstack/localization-plugin/enelson-resx-data_2022-04-04-12-52.json
- webpack/localization-plugin/src/interfaces.ts
Wrap invalid HTML tag in backticks, so that it renders as a code snippet.
Writing unescaped (un-backticked) "tags" in TSdoc comments causes downstream processes (such as the docusaurus API build) to fail.
Detecting this at build time is still on the todo list (https://github.com/microsoft/rushstack/issues/2973), this PR just fixes the one-off issue.
- Confirmed that the `rushstack-websites` repo can build again.
> [localization-plugin] Fix a small tsdoc error

- apps/rush-lib/assets/rush-init/rush.json
- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/api/RushConfigurationProject.ts
- apps/rush-lib/src/cli/SelectionParameterSet.ts
- apps/rush-lib/src/logic/selectors/GitChangedProjectSelectorParser.ts
- apps/rush-lib/src/logic/selectors/ISelectorParser.ts
- apps/rush-lib/src/logic/selectors/NamedProjectSelectorParser.ts
- apps/rush-lib/src/logic/selectors/TagProjectSelectorParser.ts
- apps/rush-lib/src/schemas/rush.schema.json
- common/changes/@microsoft/rush/rush-tags_2022-03-28-20-28.json
- common/reviews/api/rush-lib.api.md
Fixes #1241
Adds a new array field `tags` to the JSON for a `project` in `rush.json`. This field is a set of identifiers that can be used with the standard set of selection parameters to select projects.
```json
"projects": [
{
"packageName": "a",
"projectFolder": "a",
"tags": ["foo", "bar"]
},
{
"packageName": "b",
"projectFolder": "b",
"tags": ["bar", "baz"]
},
]
```
`rush list --only tag:foo` selects `a`
`rush list --only tag:bar` selects `a` and `b`
`rush list --only tag:baz` selects `b`
This plugs into the existing extensible parser for scoped selector arguments, adding to the existing supported protocols:
- `name:PACKAGE_NAME` - select a project whose name matches `PACKAGE_NAME`. Implied for backwards compatibility if no protocol is specified
- `git:REVISION` - selects all projects …
> [rush-lib] Support tags in rush.json and selectors

- build-tests/rush-amazon-s3-build-cache-plugin-integration-test/.gitignore
- build-tests/rush-amazon-s3-build-cache-plugin-integration-test/README.md
- build-tests/rush-amazon-s3-build-cache-plugin-integration-test/package.json
- build-tests/rush-amazon-s3-build-cache-plugin-integration-test/src/startProxyServer.ts
- common/changes/@microsoft/rush/retry-cloud-cache-requests_2022-03-10-22-16.json
- common/config/rush/nonbrowser-approved-packages.json
- common/config/rush/pnpm-lock.yaml
- rush-plugins/rush-amazon-s3-build-cache-plugin/package.json
- rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts
- rush-plugins/rush-amazon-s3-build-cache-plugin/src/test/AmazonS3Client.test.ts
- rush-plugins/rush-amazon-s3-build-cache-plugin/src/test/__snapshots__/AmazonS3Client.test.ts.snap
Fixes #3198, transient S3 errors updating build cache causes CI to fail
Added one unit test with mocks to test that the retries are called.
Added support for starting a proxy server which will return 500 on every second request to test that the build-cache works when running rush build. This is documented in `build-tests/rush-amazon-s3-build-cache-plugin-integration-test/README.md`
> [rush-amazon-s3-build-cache-plugin] retry failed S3 requests with the same behavior as the the azure blob storage

- apps/rush-lib/src/cli/actions/CheckAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/logic/versionMismatch/VersionMismatchFinder.ts
- common/changes/@microsoft/rush/rush-check-summary_2022-04-05-04-33.json
Right now, in large repos, `rush check` may print a very long list of package names if a mismatching dependency version exists for a dependency listed by many projects.
This change updates that to something that looks like:
```
Starting "rush check"
@rushstack/heft
0.44.4
- preferred versions from common-versions.json
- projectA
- projectB
- projectC
- projectD
(and 623 others)
0.44.3
- @msstream/components-web-video
```
This behavior can be suppressed with a new `--verbose` flag passed to `rush check`. It cannot be suppressed when running `rush install` or `rush update`.
Tested by changing the version of `@rushstack/heft` for one project in a large repo.
> [rush] By default, truncate long lists of package names when running rush check.

- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/cli/actions/AddAction.ts
- apps/rush-lib/src/cli/actions/test/AddAction.test.ts
- apps/rush-lib/src/logic/PackageJsonUpdater.ts
- common/changes/@microsoft/rush/fix-rush-add_2022-04-05-03-20.json
- common/reviews/api/rush-lib.api.md
I noticed a few issues with the way `rush add` selects the version to use, so this PR tweaks the behavior a bit.
1. When determining the versions of a dependency that are present in a repo, Rush counted `peerDependencies` as regular dependencies. This doesn't make sense.
2. If there is a pinned version specified in `common-versions.json`, `rush add` didn't just use that. After this change, it will.
3. If a mismatch is detected, it doesn't list out which versions are already present. Now it does.
Tested by rerunning `rush add` in the repo and with the arguments I used when I initially noticed these quirks.
> [rush] Fix a few issues with the way "rush add" selects versions.

- apps/rush-lib/src/logic/base/BaseProjectShrinkwrapFile.ts
- apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
- common/changes/@microsoft/rush/fix-no-deps-edge-case_2022-04-06-08-41.json
If you run `rush init` in an empty folder, create a project without any dependencies, and run `rush update`, Rush crashes with a nasty:
```
ERROR: Cannot read property 'getProjectShrinkwrap' of undefined
```
If no projects in a workspace have dependencies, PNPM doesn't generate a lockfile. This PR handles that by generating empty (i.e. - `{}`) `project/.rush/temp/shrinkwrap-deps.json` files. This allows the repo to be usable.
Tested in a new repo with a single project with no dependencies.
> [rush] Fix an edge case where `rush update` fails in a repo with no dependencies.

- apps/api-extractor/src/generators/ExcerptBuilder.ts
- build-tests/api-documenter-test/etc/api-documenter-test.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/bundledPackages/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/exportImportedExternalDefault/api-extractor-scenarios.api.json
- build-tests/api-extractor-scenarios/etc/test-outputs/importType/api-extractor-scenarios.api.json
- common/changes/@microsoft/api-extractor/excerpt-tokens_2022-04-05-16-46.json
tokenRanges are capable of being off by one when the last token has a separator and this is shown when multiple interfaces are implemented for example. This happens when an additional excerptToken is created from a separator. Fixes: #3316
Going off of Pete's comment in Zulipchat we identified an edge case in the recursion for building excerptTokens when there is a separator on the last leaf node of the recursion tree, and keeping track of the last token having a separator will keep track of the state and address this scenario.
Tests in api-documenter/extractor that have their output changed by this changeset:
api-documenter-test.api.json implementsTokenRanges: Line 809
api-extractor-senarios: bundledPackages api.json: line 313 in the extendsTokenRange
api-extractor-senarios: importType …
> [API-Extractor] Potential fix for off-by-one separator index bug.

- apps/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
- apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
- apps/rush-lib/src/logic/operations/OperationExecutionManager.ts
- apps/rush-lib/src/logic/operations/test/OperationExecutionManager.test.ts
- apps/rush-lib/src/logic/operations/test/__snapshots__/OperationExecutionManager.test.ts.snap
- common/changes/@microsoft/rush/parallelism-flexibility_2022-03-06-20-41.json
Adds support for percentage values, see https://github.com/microsoft/rushstack/issues/3257
This is the first pull request I'm introducing in an effort to avoid draining resources of local developer machines.
Since developers still have to specify the --parallelism flag, my next idea would be to add some functionality that let's us use all cores minus 1. There's no specific issue for this yet.
Jest has support for percentage-values, so I figured this should be a welcome change for flexibility regardless. This code was also heavily inspired by jest's implementation, found here: https://github.com/facebook/jest/blob/e0b33b74b5afd738edc183858b5c34053cfc26dd/packages/jest-config/src/getMaxWorkers.ts#L29
I added a test that simply ensures that the generation won't fail. I found that creating a …
> [rush-lib] Added Parallelism percentage value support

- apps/rush/README.md
- common/changes/@microsoft/rush/enelson-api-links_2022-04-07-12-56.json
- libraries/rush-sdk/README.md
Fixes https://github.com/microsoft/rushstack/issues/3310.
Update links to the API Reference in README files.
> [rush] Fix links to API Reference docs

- apps/rush-lib/src/api/RushConfiguration.ts
- apps/rush-lib/src/cli/actions/AddAction.ts
- apps/rush-lib/src/cli/actions/test/AddAction.test.ts
- apps/rush-lib/src/logic/DependencyAnalyzer.ts
- apps/rush-lib/src/logic/PackageJsonUpdater.ts
- apps/rush-lib/src/logic/test/DependencyAnalyzer.test.ts
- apps/rush-lib/src/logic/test/DependencyAnalyzerTestRepos/allowed-alternatives/a/package.json
- apps/rush-lib/src/logic/test/DependencyAnalyzerTestRepos/allowed-alternatives/b/package.json
- apps/rush-lib/src/logic/test/DependencyAnalyzerTestRepos/allowed-alternatives/common/config/rush/common-versions.json
- apps/rush-lib/src/logic/test/DependencyAnalyzerTestRepos/allowed-alternatives/rush.json
- apps/rush-lib/src/logic/test/DependencyAnalyzerTestRepos/no-allowed-alternatives-with-inconsistent-versions/a/package.json
- apps/rush-lib/src/logic/test/DependencyAnalyzerTestRepos/no-allowed-alternatives-with-inconsistent-versions/b/package.json
- apps/rush-lib/src/logic/test/DependencyAnalyzerTestRepos/no-allowed-alternatives-with-inconsistent-versions/rush.json
- apps/rush-lib/src/logic/test/DependencyAnalyzerTestRepos/no-allowed-alternatives/a/package.json
- apps/rush-lib/src/logic/test/DependencyAnalyzerTestRepos/no-allowed-alternatives/b/package.json
- apps/rush-lib/src/logic/test/DependencyAnalyzerTestRepos/no-allowed-alternatives/rush.json
- common/changes/@microsoft/rush/clean-up-dependency-analysis_2022-04-06-05-54.json
- common/reviews/api/rush-lib.api.md
This a refactor suggested in https://github.com/microsoft/rushstack/pull/3314#discussion_r843197891
> [rush] Split dependency analysis out from RushConfiguration.

- common/changes/@microsoft/rush/expose-azure-authentication_2022-04-08-00-06.json
- common/reviews/api/rush-azure-storage-build-cache-plugin.api.md
- rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureStorageAuthentication.ts
- rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureStorageBuildCacheProvider.ts
- rush-plugins/rush-azure-storage-build-cache-plugin/src/RushAzureStorageBuildCachePlugin.ts
- rush-plugins/rush-azure-storage-build-cache-plugin/src/index.ts
- rush-plugins/rush-azure-storage-build-cache-plugin/src/test/AzureStorageBuildCacheProvider.test.ts
Expose APIs for managing Azure credentials from @rushstack/rush-azure-storage-build-cache-plugin.
These APIs are useful for reusing Rush's credential caching features for things like deployment to Azure.
> [rush] Expose APIs for interacting with Azure credentials.
