common/changes/dzearing-perf-updates_2016-11-02-18-22.json
common/npm-shrinkwrap.json
common/temp_modules/npmx-gulp-core-build-karma/package.json
common/temp_modules/npmx-gulp-core-build-mocha/package.json
common/temp_modules/npmx-gulp-core-build-sass/package.json
common/temp_modules/npmx-gulp-core-build-serve/package.json
common/temp_modules/npmx-gulp-core-build-typescript/package.json
common/temp_modules/npmx-gulp-core-build-webpack/package.json
common/temp_modules/npmx-node-library-build/package.json
common/temp_modules/npmx-test-web-library-build/package.json
common/temp_modules/npmx-web-library-build/package.json
gulp-core-build-karma/src/KarmaTask.ts
gulp-core-build-serve/src/ServeTask.ts
gulp-core-build-serve/src/TrustCertTask.ts
gulp-core-build-serve/src/UntrustCertTask.ts
gulp-core-build-typescript/package.json
gulp-core-build-typescript/src/TSLintTask.ts
gulp-core-build-typescript/src/TypeScriptTask.ts
gulp-core-build-webpack/src/WebpackTask.ts

This reduces how much we import by default on startup. On my fast macbook, it took the startup for a web-library-build project down from 3+ seconds to about 564ms.

Improvements to gulp startup time.

---

common/changes/master_2016-11-02-03-21.json
gulp-core-build/src/tasks/CopyTask.ts
web-library-build/src/index.ts

Make web-library-build export the tasks it defines.

Make web-library-build export the tasks it defines.

---

common/changes/nickpape-fix-libamd_2016-11-09-22-50.json
gulp-core-build-typescript/src/TypeScriptTask.ts

Fixes a bg causing Lib AMD to not compile

Fixes LibAMD

---

.gitignore
.vscode/launch.json
common/changes/dzearing-hash-fix_2016-11-15-01-41.json
npmx.json
package-deps-hash/src/getPackageDeps.ts
package-deps-hash/src/tests/getPackageDeps.test.ts
package.json

Added extra test case to validate.

Fixing package-deps-hash bug parsing multiple changed files in repo.

---

common/changes/nickpape-inject-ts-compiler-config_2016-12-09-19-45.json
gulp-core-build-typescript/src/TypeScriptTask.ts
gulp-core-build-typescript/src/index.ts

Allow us to inject compiler options and also control where the files get written.

Allow us to inject compiler options and also control where the files get written

---

common/changes/typescript-21_2016-12-13-20-38.json
common/npm-shrinkwrap.json
common/temp_modules/npmx-gulp-core-build-karma/package.json
common/temp_modules/npmx-gulp-core-build-mocha/package.json
common/temp_modules/npmx-gulp-core-build-sass/package.json
common/temp_modules/npmx-gulp-core-build-serve/package.json
common/temp_modules/npmx-gulp-core-build-typescript/package.json
common/temp_modules/npmx-gulp-core-build-webpack/package.json
common/temp_modules/npmx-gulp-core-build/package.json
common/temp_modules/npmx-node-library-build/package.json
common/temp_modules/npmx-package-deps-hash/package.json
common/temp_modules/npmx-web-library-build/package.json
gulp-core-build-karma/package.json
gulp-core-build-mocha/package.json
gulp-core-build-sass/package.json
gulp-core-build-serve/package.json
gulp-core-build-typescript/gulpfile.js
gulp-core-build-typescript/package.json
gulp-core-build-typescript/src/TSLintTask.ts
gulp-core-build-typescript/src/TypeScriptTask.ts
gulp-core-build-webpack/package.json
gulp-core-build/package.json
node-library-build/package.json
package-deps-hash/package.json
web-library-build/package.json

This change brings in TypeScript 2.1 and TSLint 4.0.0.

Upgrade to TypeScript 2.1 and TSLint 4.0

---

gulp-core-build-karma/package.json
gulp-core-build-mocha/package.json
gulp-core-build-sass/package.json
gulp-core-build-serve/package.json
gulp-core-build-typescript/package.json
gulp-core-build-webpack/package.json
gulp-core-build/package.json
node-library-build/package.json
web-library-build/package.json

The CI is failing since 2.1.0 package was already published. Updating to reflect reality.

Update version numbers to reflect reality

---

.travis.yml

Make sure people do not forget about adding change file in their pull requests.

Check change file at the beginning of the build.

---

common/changes/nickpape-fix-bug-in-karma_2017-02-01-01-38.json
common/reviews/api/gulp-core-build-webpack.api.ts
common/reviews/api/node-library-build.api.ts
common/reviews/api/web-library-build.api.ts
gulp-core-build-karma/src/KarmaTask.ts

* Also update the API files (which I forgot to do in a PR where I bypassed the build due to the issues Travis is experiencing.

Fixes issue in karma where the tests.js would not be written if the temp/ folder didn't exist

---

common/npm-shrinkwrap.json
common/reviews/api/api-extractor.api.ts
common/reviews/api/gulp-core-build.api.ts
common/temp_modules/rush-gulp-core-build-karma/package.json
common/temp_modules/rush-gulp-core-build-mocha/package.json
common/temp_modules/rush-gulp-core-build-sass/package.json
common/temp_modules/rush-gulp-core-build-serve/package.json
common/temp_modules/rush-gulp-core-build-typescript/package.json
common/temp_modules/rush-gulp-core-build-webpack/package.json
common/temp_modules/rush-node-library-build/package.json
common/temp_modules/rush-test-web-library-build/package.json
common/temp_modules/rush-web-library-build/package.json

The cyclicDependencyProjects should now be building with Danny's fixes

Upgrade api-extractor

---

common/changes/nickpape-export-log_2017-02-08-00-36.json
common/reviews/api/gulp-core-build.api.ts
common/reviews/api/node-library-build.api.ts
common/reviews/api/package-deps-hash.api.ts
common/reviews/api/test-web-library-build.api.ts
common/reviews/api/web-library-build.api.ts
gulp-core-build/src/index.ts
gulp-core-build/src/logging.ts

It is a useful helper function that should be exported for now, since several consuming projects are using it.

Ensure the log() function is exported

---

common/npm-shrinkwrap.json
common/temp_modules/rush-gulp-core-build/package.json

To help reduce how bad the cyclic dependency gets.

Rush generate after publish

---

common/changes/nickpape-no-err-on-help_2017-02-09-00-37.json
gulp-core-build/src/index.ts

With the `-h` flag in yargs or ts-command-line

Don't try to watch process exit if we are getting command line help

---

api-extractor/src/DocItemLoader.ts
common/changes/dagaeta-api-extractor-error-message_2017-02-16-21-28.json

- Changed apostrophe to backtick

Fixed Api-Extractor warning message 

---

common/changes/nickpape-rush-should-generate-common_2017-02-17-21-12.json
rush/rush-lib/src/data/RushConfiguration.ts
rush/rush/src/actions/InstallAction.ts

Improve error messages when it appears rush generate needs to be run

---

common/changes/restore-tslint_2017-03-02-20-29.json
web-library-build/src/index.ts

Restore tslint in web-library-build gulp build

Restore tslint in web-library-build gulp build

---

test-web-library-build/config/pre-copy.json
test-web-library-build/gulpfile.js
test-web-library-build/pre-copy-test.ts
test-web-library-build/preCopyTest.ts
test-web-library-build/src/pre-copy-test.ts
test-web-library-build/src/preCopyTest.ts
test-web-library-build/src/test.ts

Fix tslint errors in test project

Fix tslint errors in test project

---

.vscode/settings.json
api-extractor/src/ApiDefinitionReference.ts
api-extractor/src/DocElementParser.ts
api-extractor/src/DocItemLoader.ts
api-extractor/src/ExternalApiHelper.ts
api-extractor/src/Extractor.ts
api-extractor/src/IDocElement.ts
api-extractor/src/IDocItem.ts
api-extractor/src/ResolvedApiItem.ts
api-extractor/src/TestFileComparer.ts
api-extractor/src/definitions/ApiDocumentation.ts
api-extractor/src/definitions/ApiItem.ts
api-extractor/src/definitions/ApiPackage.ts
api-extractor/src/generators/ApiFileGenerator.ts
api-extractor/src/generators/ApiJsonFile.ts
common/changes/nickpape-revert-gcb_2017-03-20-03-42.json
common/npm-shrinkwrap.json
common/temp_modules/rush-gulp-core-build-sass/package.json
common/temp_modules/rush-gulp-core-build-typescript/package.json
common/temp_modules/rush-node-library-build/package.json
common/temp_modules/rush-web-library-build/package.json
gulp-core-build-sass/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/web-build-tools/139)

Revert previous change causing breakage in SPFx core scenario

---

rush/rush/src/actions/PublishAction.ts
rush/rush/src/utilities/PrereleaseToken.ts
rush/rush/src/utilities/PublishUtilities.ts
rush/rush/src/utilities/test/PublishUtilities.test.ts

Suffix is different from pre-release. Adding a suffix only appends the suffix to existing versions and does not bump up versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/web-build-tools/143)

Support add suffix to version.

---

rush/rush/src/actions/InstallAction.ts

Rush install should look at npm-shrinkwrap when determining if a new install is required
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/web-build-tools/144)

Rush install should look at npm-shrinkwrap when determining if a new install is required

---

common/temp_modules/rush-gulp-core-build-karma/package.json
common/temp_modules/rush-gulp-core-build-mocha/package.json
common/temp_modules/rush-gulp-core-build-sass/package.json
common/temp_modules/rush-gulp-core-build-serve/package.json
common/temp_modules/rush-gulp-core-build-typescript/package.json
common/temp_modules/rush-gulp-core-build-webpack/package.json
common/temp_modules/rush-node-library-build/package.json
common/temp_modules/rush-package-deps-hash/package.json
common/temp_modules/rush-rush-lib/package.json
common/temp_modules/rush-rush/package.json
common/temp_modules/rush-test-web-library-build/package.json
common/temp_modules/rush-web-library-build/package.json
rush/rush-lib/package.json
rush/rush-lib/src/index.ts
rush/rush-lib/src/utilities/Npm.ts
rush/rush-lib/src/utilities/test/Npm.test.ts
rush/rush/package.json
rush/rush/src/actions/PublishAction.ts

Publishing should not just check the latest version, instead it should check all existing versions before publishing to avoid conflict.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/web-build-tools/146)

Detect published versions for packages before publishing.

---

rush/rush/src/utilities/PublishUtilities.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/web-build-tools/149)

Fix a bug where not all project versions get updated for pre-release.

---

README.md
apps/rush-lib/README.md
apps/rush/README.md
common/changes/pgonzal-node-core-library_2017-05-12-06-58.json
common/npm-shrinkwrap.json
common/package.json
common/reviews/api/node-core-library.api.ts
common/temp_modules/rush-node-core-library/package.json
libraries/api-extractor/README.md
libraries/node-core-library/.npmignore
libraries/node-core-library/LICENSE
libraries/node-core-library/README.md
libraries/node-core-library/config/api-extractor.json
libraries/node-core-library/gulpfile.js
libraries/node-core-library/package.json
libraries/node-core-library/src/JsonFile.ts
libraries/node-core-library/src/index.ts
libraries/node-core-library/tsconfig.json
libraries/node-core-library/typings/jju/jju.d.ts
libraries/node-core-library/typings/tsd.d.ts
rush.json

Set up the new project skeleton.  The actual content will be added in a separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/web-build-tools/180)

Initial setup for @microsoft/node-core-library

---

apps/rush-lib/CHANGELOG.json
apps/rush-lib/CHANGELOG.md
apps/rush-lib/package.json
apps/rush-lib/src/RushConstants.ts
apps/rush/CHANGELOG.json
apps/rush/CHANGELOG.md
apps/rush/README.md
apps/rush/package.json
apps/rush/src/actions/CheckAction.ts

These are just some minor documentation fixes.

Publish Rush 3.0.2 with some minor fixes

---

apps/rush-lib/src/RushConstants.ts
apps/rush/src/actions/RebuildAction.ts
apps/rush/src/taskRunner/ProjectBuildTask.ts
apps/rush/src/utilities/PackageChangeAnalyzer.ts
apps/rush/src/utilities/test/PackageChangeAnalyzer.test.ts
common/reviews/api/rush-lib.api.ts

Rush: if a file outside of a project changes, build should rebuild all projects

---

apps/rush/src/taskRunner/ProjectBuildTask.ts

Only write package-deps if they are non-null

Only write package-deps if they are non-null

---

apps/rush/src/taskRunner/ProjectBuildTask.ts

Dont add things to the args list if it is undefined

Unbreak empty string build command

---

rush.json

To avoid a bug in publishing action in v3.0.1.

Use latest rush version 3.0.7 for this repo.

---

apps/rush-lib/src/rush-schema.json
apps/rush-lib/src/utilities/Utilities.ts
apps/rush/src/actions/RushCommandLineParser.ts
common/reviews/api/rush-lib.api.ts

Add preRushInstall, postRushInstall, preRushBuild event to rush-schema.
Add common/temp/node_modules/.bin to the environment variable PATH.
Make Utilities.executeShellCommand throw if command fails.

A couple of bug fixes.

---

apps/rush-lib/src/utilities/Utilities.ts
apps/rush/src/taskRunner/ProjectBuildTask.ts
common/reviews/api/rush-lib.api.ts

This fixes many many issues with invoking scripts.

Make ProjectBuildTask use the shell script execution command

---

common/changes/@microsoft/api-extractor/pgonzal-api-extractor-beta_2017-06-13-02-39.json
common/reviews/api/api-extractor.api.ts
libraries/api-extractor/src/ApiItemVisitor.ts
libraries/api-extractor/src/generators/ApiJsonGenerator.ts
libraries/api-extractor/src/generators/test/ApiFileGenerator.test.ts
libraries/api-extractor/src/generators/test/ApiJsonGenerator.test.ts
libraries/api-extractor/testInputs/example1/example1-output.api.ts
libraries/api-extractor/testInputs/example1/example1-output.json
libraries/api-extractor/testInputs/example1/folder/ApiTagTests.ts
libraries/api-extractor/testInputs/example1/index.ts
libraries/api-extractor/testInputs/example2/example2-output.api.ts
libraries/api-extractor/testInputs/example2/example2-output.json
libraries/api-extractor/testInputs/example2/src/MyDocumentedClass.ts

- Updated the ApiItemVisitor configuration so that \@beta items are now included
- Added more unit tests to cover this scenario

api-extractor should include @beta items in the *.api.json file

---

common/changes/@microsoft/gulp-core-build-typescript/nickpape-allow-target-override-typescript_2017-06-15-20-04.json
core-build/gulp-core-build-typescript/src/TypeScriptTask.ts

Allow TypeScript target to be overridden

---

apps/rush-lib/CHANGELOG.json
apps/rush-lib/CHANGELOG.md
apps/rush-lib/package.json
apps/rush/CHANGELOG.json
apps/rush/CHANGELOG.md
apps/rush/package.json

Manually bump versions and update change logs.

Publish rush 3.0.11

---

apps/rush/src/taskRunner/ProjectBuildTask.ts

Fix a misleading error message.

Fix wrong error message.

---

common/changes/@microsoft/load-themed-styles/zhiliu-BatchStylesLoading_2017-07-17-21-29.json
libraries/load-themed-styles/src/index.ts

add the capability to allow batching of the styles and load them together for perf optimization

load styles in batch

---

apps/rush/src/utilities/InstallManager.ts

Right now it is skipping optional dependencies of "NPM", not of the package we are working on!

Move the no-optional to the correct place

---

common/changes/@microsoft/api-extractor/pgonzal-span_2017-08-10-01-08.json
libraries/api-extractor/src/DebugRun.ts
libraries/api-extractor/src/IndentedWriter.ts
libraries/api-extractor/src/generators/Span.ts
libraries/api-extractor/src/generators/test/Span.test.ts
libraries/api-extractor/testInputs/SpanTest1-Expected.txt
libraries/api-extractor/testInputs/SpanTest2-Expected.ts

This is the first set of changes being peeled off from the *.d.ts prototype.  The Span class is a helper that allows us to rewrite TypeScript source code without having to understand every aspect of the AST structure.

Introduce "Span" class for upcoming *.d.ts generator

---

libraries/api-documenter/src/DocumentationNode.ts
libraries/api-documenter/src/Documenter.ts
libraries/api-documenter/src/Domifier.ts
libraries/api-documenter/src/MarkdownPageRenderer.ts
libraries/api-documenter/src/RenderingHelpers.ts
libraries/api-documenter/src/SimpleDom.ts
libraries/api-documenter/src/test/ExpectedOutput.md
libraries/api-documenter/src/test/MarkdownPageRenderer.test.ts

- Introduce DocumentationNode to track hierarchy
- Fix a bug with unnecessary "" being emitted
- Implement breadcrumb
Example output is online here: https://microsoft.github.io/web-build-tools/api/

Add breadcrumb for api-documenter

---

common/changes/@microsoft/api-extractor/pgonzal-yaml-documenter6_2017-09-08-23-58.json
common/reviews/api/api-extractor.api.ts
libraries/api-extractor/src/api/ApiItem.ts
libraries/api-extractor/src/generators/ApiFileGenerator.ts
libraries/api-extractor/src/generators/ApiJsonGenerator.ts
libraries/api-extractor/src/generators/AstItemVisitor.ts
libraries/api-extractor/testInputs/example1/example1-output.json
libraries/api-extractor/testInputs/example3/example3-output.json
libraries/api-extractor/testInputs/example4/example4-output.json

This resolves #292 (Functions and Methods doesn't get their params)

Fix an issue where the *.api.json files were sometimes missing function parameters

---

common/changes/@microsoft/gulp-core-build-karma/ianc-upgrade-istanbul-instrumenter_2017-10-24-19-57.json
common/config/rush/npm-shrinkwrap.json
core-build/gulp-core-build-karma/package.json

Upgrade the istanbul instrumenter loader to be compatible with es6+ module formats.

---

common/changes/@microsoft/gulp-core-build/nickpape-fix-toast-error_2017-10-30-20-36.json
core-build/gulp-core-build/src/index.ts

Fixes https://github.com/SharePoint/sp-dev-fx-webparts/issues/297 and https://github.com/SharePoint/sp-dev-docs/issues/912

Fix an issue when displaying toasts for build failures

---

apps/rush-lib/src/cli/taskRunner/ProjectBuildTask.ts

Small fixes for Rush4

---

.pullapprove.yml
common/reviews/api/node-library-build.api.ts
common/reviews/api/web-library-build.api.ts

Update api.ts files

---

apps/rush-lib/CHANGELOG.json
apps/rush-lib/CHANGELOG.md
apps/rush-lib/package.json
apps/rush/CHANGELOG.json
apps/rush/CHANGELOG.md
apps/rush/package.json

* Bump rush in preparation for a new publish

Rush 4.1.0

---

apps/rush-lib/src/cli/utilities/InstallManager.ts

I thought this was not supported, but it is supposed to be.
https://github.com/pnpm/pnpm/issues/460
https://github.com/pnpm/pnpm/pull/783

PNPM apparently does support --no-optional

---

apps/rush-lib/CHANGELOG.json
apps/rush-lib/CHANGELOG.md
apps/rush-lib/package.json
apps/rush/CHANGELOG.json
apps/rush/CHANGELOG.md
apps/rush/package.json
common/config/rush/shrinkwrap.yaml

Publishing a new release of **rush** and **rush-lib**

Publish Rush 4.2.0

---

apps/api-extractor/package.json
common/changes/@microsoft/api-extractor/nickpape-bump-node-library-build_2018-01-22-21-05.json
common/changes/@microsoft/gulp-core-build-karma/nickpape-bump-node-library-build_2018-01-22-21-05.json
common/changes/@microsoft/gulp-core-build-mocha/nickpape-bump-node-library-build_2018-01-22-21-05.json
common/changes/@microsoft/gulp-core-build-sass/nickpape-bump-node-library-build_2018-01-22-21-05.json
common/changes/@microsoft/gulp-core-build-serve/nickpape-bump-node-library-build_2018-01-22-21-05.json
common/changes/@microsoft/gulp-core-build-typescript/nickpape-bump-node-library-build_2018-01-22-21-05.json
common/changes/@microsoft/gulp-core-build-webpack/nickpape-bump-node-library-build_2018-01-22-21-05.json
common/changes/@microsoft/gulp-core-build/nickpape-bump-node-library-build_2018-01-22-21-05.json
common/changes/@microsoft/node-core-library/nickpape-bump-node-library-build_2018-01-22-21-05.json
common/changes/@microsoft/ts-command-line/nickpape-bump-node-library-build_2018-01-22-21-05.json
common/config/rush/shrinkwrap.yaml
core-build/gulp-core-build-karma/package.json
core-build/gulp-core-build-mocha/package.json
core-build/gulp-core-build-sass/package.json
core-build/gulp-core-build-serve/package.json
core-build/gulp-core-build-typescript/package.json
core-build/gulp-core-build-webpack/package.json
core-build/gulp-core-build/package.json
libraries/node-core-library/package.json
libraries/ts-command-line/package.json

Bump it to pick up changes around handling of stderr

Bump node-library-build

---

apps/rush-lib/src/cli/logic/PublishUtilities.ts
apps/rush-lib/src/cli/logic/test/ChangeManager.test.ts
apps/rush-lib/src/cli/logic/test/PublishUtilities.test.ts
apps/rush-lib/src/cli/logic/test/orderedChanges/change1.json
apps/rush-lib/src/cli/logic/test/orderedChanges/change2.json
common/changes/@microsoft/rush/qz2017-version_bug_2018-01-26-00-33.json

Fix bugs in rush version increase algorithm on how to handle cyclic dependencies.

Fix bugs in rush version increase algorithm on how to handle cyclic dependencies.

---

apps/api-extractor/package.json
common/changes/@microsoft/api-extractor/pgonzal-bump-cyclics_2018-02-17-03-14.json
common/changes/@microsoft/gulp-core-build-karma/pgonzal-bump-cyclics_2018-02-17-03-14.json
common/changes/@microsoft/gulp-core-build-mocha/pgonzal-bump-cyclics_2018-02-17-03-14.json
common/changes/@microsoft/gulp-core-build-sass/pgonzal-bump-cyclics_2018-02-17-03-14.json
common/changes/@microsoft/gulp-core-build-serve/pgonzal-bump-cyclics_2018-02-17-03-14.json
common/changes/@microsoft/gulp-core-build-typescript/pgonzal-bump-cyclics_2018-02-17-03-14.json
common/changes/@microsoft/gulp-core-build-webpack/pgonzal-bump-cyclics_2018-02-17-03-14.json
common/changes/@microsoft/gulp-core-build/pgonzal-bump-cyclics_2018-02-17-03-14.json
common/changes/@microsoft/node-core-library/pgonzal-bump-cyclics_2018-02-17-03-14.json
common/changes/@microsoft/ts-command-line/pgonzal-bump-cyclics_2018-02-17-03-14.json
common/config/rush/shrinkwrap.yaml
core-build/gulp-core-build-karma/package.json
core-build/gulp-core-build-mocha/package.json
core-build/gulp-core-build-sass/package.json
core-build/gulp-core-build-serve/package.json
core-build/gulp-core-build-typescript/package.json
core-build/gulp-core-build-webpack/package.json
core-build/gulp-core-build/package.json
libraries/node-core-library/package.json
libraries/ts-command-line/package.json
rush.json

Upgrade the cyclic dependencies in **web-build-tools** to upgrade to the latest API Extractor.

Bump cyclic dependencies

---

apps/rush-lib/src/cli/logic/PackageChangeAnalyzer.ts
common/changes/@microsoft/node-core-library/pgonzal-path-api_2018-02-21-02-19.json
common/changes/@microsoft/rush/pgonzal-path-api_2018-02-21-03-01.json
common/reviews/api/node-core-library.api.ts
libraries/node-core-library/src/Path.ts
libraries/node-core-library/src/index.ts
libraries/node-core-library/src/test/Path.test.ts

Add a new utility to **node-core-library**

Add Path.isUnder() API

---

common/changes/@microsoft/gulp-core-build-karma/upgrade-webpack-3_2018-04-04-22-11.json
common/changes/@microsoft/gulp-core-build-webpack/upgrade-webpack-3_2018-04-04-22-11.json
common/changes/@microsoft/loader-load-themed-styles/upgrade-webpack-3_2018-04-04-22-28.json
common/changes/@microsoft/resolve-chunk-plugin/upgrade-webpack-3_2018-04-04-22-28.json
common/changes/@microsoft/set-webpack-public-path-plugin/upgrade-webpack-3_2018-04-04-22-28.json
common/config/rush/shrinkwrap.yaml
core-build/gulp-core-build-karma/package.json
core-build/gulp-core-build-webpack/package.json
webpack/loader-load-themed-styles/package.json
webpack/resolve-chunk-plugin/package.json
webpack/set-webpack-public-path-plugin/package.json

webpack@~3.11.0 includes a fix for an out-of-memory issue; see:
https://github.com/webpack/webpack/issues/5992
https://github.com/webpack/webpack/pull/5997

Upgrade webpack to ~3.11.0

---

common/config/rush/version-policies.json

We will start publishing regular prerelease builds of Rush

Configure internal publishing for Rush

---

apps/api-extractor/src/extractor/api-extractor.schema.json
common/changes/@microsoft/api-extractor/qz2017-more_params_2018-04-18-17-40.json
common/changes/@microsoft/gulp-core-build-typescript/qz2017-more_params_2018-04-18-17-40.json
core-build/gulp-core-build-typescript/src/ApiExtractorTask.ts
core-build/gulp-core-build-typescript/src/schemas/api-extractor.schema.json

Expose three more Api extractor config parameters in gcb typescript.
Fix typos in api-extractor config comments.

[gulp-core-build-typescript] Expose more API Extractor config options

---

apps/rush-lib/src/cli/logic/InstallManager.ts
apps/rush-lib/src/utilities/AsyncRecycler.ts
common/changes/@microsoft/rush/pgonzal-rush-recycler-long-paths_2018-04-21-01-16.json

This issue was causing our CI lab machines to run out of disk sometimes.

[rush] Fix an issue with the rush-recycler not being emptied when it exceeded MAX_PATH

---

apps/rush-lib/src/utilities/Utilities.ts
common/changes/@microsoft/rush/pgonzal-fix-rush-installer_2018-05-02-21-29.json

Fix a minor regression from PR #632

[rush] Fix regression when installing package manager

---

rush.json

This includes the fix for the recent regression.

Upgrade to Rush 5.0.0-dev.13

---

apps/rush-lib/src/RushConstants.ts
apps/rush-lib/src/cli/actions/PurgeAction.ts
apps/rush-lib/src/cli/actions/RushCommandLineParser.ts
apps/rush-lib/src/cli/logic/InstallManager.ts
apps/rush-lib/src/cli/logic/PurgeManager.ts
apps/rush-lib/src/data/RushConfiguration.ts
apps/rush-lib/src/utilities/AsyncRecycler.ts
common/changes/@microsoft/rush/pgonzal-rush-purge_2018-05-05-00-40.json
common/reviews/api/rush-lib.api.ts

This adds a "rush purge" command for cleaning up temporary files.  The upcoming "rush update" PR will simplify the installation algorithm by no longer intermixing purging with installation.

[rush] Add new command "rush purge"

---

apps/rush-lib/src/cli/actions/BaseRushAction.ts
apps/rush-lib/src/cli/actions/CustomRushAction.ts
apps/rush-lib/src/cli/taskRunner/TaskRunner.ts
common/changes/@microsoft/rush/pgonzal-rush-release-testing_2018-05-10-00-10.json

As part of our effort to reduce regressions, I went back and manually reviewed all the changes we made since we started the "5.0.0-dev.1" series of releases.  This PR has a couple minor fixes.

[rush] Fix some minor issues found during testing

---

rush.json

This is the latest stable release of the dev branch.

Upgrade to Rush 5.0.0-dev.17

---

apps/rush-lib/src/data/RushConfiguration.ts
common/changes/@microsoft/rush/pgonzal-rush-preinstall-filename_2018-05-15-02-45.json

Add a missing slash to a path name

[rush]  Add missing slash for tempShrinkwrapPreinstallFilename

---

apps/api-documenter/src/yaml/OfficeYamlDocumenter.ts
common/changes/@microsoft/api-documenter/darrenmart-officeyamldocumenter-apiset-links_2018-05-17-15-51.json

Updates to API Set URL resolution logic.

Darrenmart officeyamldocumenter apiset links

---

rush.json

Upgrade to PNPM 2.0.0

---

apps/rush-lib/package.json
apps/rush-lib/src/RushConstants.ts
apps/rush-lib/src/cli/actions/BaseInstallAction.ts
apps/rush-lib/src/cli/actions/CommandLineMigrationAdvisor.ts
apps/rush-lib/src/cli/actions/CustomRushAction.ts
apps/rush-lib/src/cli/actions/RushCommandLineParser.ts
apps/rush-lib/src/cli/logic/InstallManager.ts
apps/rush-lib/src/cli/logic/SetupChecks.ts
apps/rush-lib/src/utilities/Utilities.ts
apps/rush/README.md
apps/rush/package.json
common/changes/@microsoft/rush/pgonzal-rush-fixes_2018-06-01-00-55.json
rush.json

- Improve the migration message
- Update the web site URL
- Check for PNPM versions that are too old

[rush] Fix some miscellaneous issues in preparation for Rush 5

---

common/changes/@microsoft/loader-load-themed-styles/patch-1_2018-06-05-18-33.json
webpack/loader-load-themed-styles/src/LoadThemedStylesLoader.ts

The getter had the same comment as the setter :)

[load-themed-styles] Update TSDoc for loadedThemedStylesPath getter

---

apps/rush-lib/src/logic/PublishUtilities.ts
apps/rush-lib/src/logic/VersionManager.ts
common/changes/@microsoft/rush/acoates-updatepeers_2018-06-15-21-32.json

Update peerDependencies when bumping package versions

---

rush.json

This fixes the [statistics reporting issue](https://github.com/pnpm/pnpm/issues/1233) which was a minor annoyance

Upgrade to PNPM 2.6.2 

---

common/changes/@microsoft/node-core-library/bugfix--705_2018-06-20-23-30.json
libraries/node-core-library/src/LockFile.ts
libraries/node-core-library/src/test/LockFile.test.ts

fixes #705
Copy of https://github.com/Microsoft/web-build-tools/pull/707, but with branch renamed and a change file.

LockFile: process start time compatibility

---

common/changes/@microsoft/package-deps-hash/ianc-rename-support-in-package-deps-hash_2018-07-11-19-43.json
libraries/package-deps-hash/src/getPackageDeps.ts

Fixing an issue where package-deps-hash didn't correctly handle staged renames.

---

common/changes/@microsoft/node-core-library/pgonzal-ncl-jest_2018-07-18-18-48.json
libraries/node-core-library/config/jest.json
libraries/node-core-library/package.json
libraries/node-core-library/src/test/JsonSchema.test.ts
libraries/node-core-library/src/test/LockFile.test.ts
libraries/node-core-library/src/test/PackageJsonLookup.test.ts
libraries/node-core-library/src/test/PackageName.test.ts
libraries/node-core-library/src/test/Path.test.ts
libraries/node-core-library/src/test/ProtectableMap.test.ts
libraries/node-core-library/src/test/Text.test.ts
libraries/node-core-library/tsconfig.json

Convert the unit tests to use Jest instead of Mocha

[node-core-library] Convert tests to use Jest

---

apps/rush-lib/src/scripts/install-run.ts
common/changes/@microsoft/gulp-core-build-typescript/nickpape-fix-issue-invoking-node_2018-07-24-22-33.json
common/changes/@microsoft/rush/nickpape-fix-issue-invoking-node_2018-07-24-22-33.json
core-build/gulp-core-build-typescript/src/miniTasks/BaseCmdTask.ts

Partially fixes https://github.com/Microsoft/web-build-tools/issues/759

Fix issue where BaseCmdTask was invoking the wrong version of Node.js

---

apps/rush-lib/src/cli/actions/BaseInstallAction.ts
apps/rush-lib/src/logic/GitPolicy.ts
common/changes/@microsoft/rush/pgonzal-fix-rush-message_2018-08-18-01-10.json

This was a minor regression from a recent refactoring

[rush] Fix indentation of Rush policy message

---

common/changes/@microsoft/node-core-library/pgonzal-rushell-execute2_2018-08-21-22-34.json
common/changes/@microsoft/node-core-library/pgonzal-rushell-execute2_2018-08-21-22-35.json
common/reviews/api/rushell.api.ts
libraries/node-core-library/src/Executable.ts
libraries/rushell/package.json
libraries/rushell/src/AstNode.ts
libraries/rushell/src/Parser.ts
libraries/rushell/src/Rushell.ts
libraries/rushell/src/TextRange.ts
libraries/rushell/src/Tokenizer.ts
libraries/rushell/src/index.ts
libraries/rushell/src/test/Parser.test.ts
libraries/rushell/src/test/Rushell.test.ts
libraries/rushell/src/test/__snapshots__/Parser.test.ts.snap

This is some more incremental work on the basic script interpreter functionality for Rushell.

[rushell] Add basic script evaluator that can spawn new processes

---

apps/api-extractor/package.json
common/changes/@microsoft/api-extractor/pgonzal-bump-cyclics_2018-10-07-06-26.json
common/changes/@microsoft/gulp-core-build-mocha/pgonzal-bump-cyclics_2018-10-07-06-26.json
common/changes/@microsoft/gulp-core-build-typescript/pgonzal-bump-cyclics_2018-10-07-06-26.json
common/changes/@microsoft/gulp-core-build/pgonzal-bump-cyclics_2018-10-07-06-26.json
common/changes/@microsoft/node-core-library/pgonzal-bump-cyclics_2018-10-07-06-26.json
common/changes/@microsoft/rush-stack/pgonzal-bump-cyclics_2018-10-07-06-26.json
common/changes/@microsoft/ts-command-line/pgonzal-bump-cyclics_2018-10-07-06-26.json
common/config/rush/shrinkwrap.yaml
core-build/gulp-core-build-mocha/package.json
core-build/gulp-core-build-typescript/package.json
core-build/gulp-core-build/package.json
libraries/node-core-library/package.json
libraries/ts-command-line/package.json
stack/rush-stack/package.json

Update everything to use API Extractor 6

Bump cyclic dependencies for API Extractor 6

---

apps/api-extractor/package.json
apps/api-extractor/src/aedoc/ApiDocumentation.ts
apps/api-extractor/src/ast/AstNamespace.ts
apps/api-extractor/src/cli/RunAction.ts
apps/api-extractor/src/generators/ApiFileGenerator.ts
common/changes/@microsoft/api-extractor/pgonzal-ae-namespace-fix_2018-10-12-01-58.json
common/changes/@microsoft/api-extractor/pgonzal-ae-namespace-fix_2018-10-12-01-59.json
common/changes/@microsoft/api-extractor/pgonzal-ae-namespace-fix_2018-10-17-14-29.json
common/config/rush/shrinkwrap.yaml
rush.json

This fixes an issue encountered with https://github.com/OfficeDev/office-ui-fabric-react/pull/6645

[api-extractor] Fix a regression where errors were sometimes reported incorrectly for namespaces

---

apps/api-extractor/package.json
common/changes/@microsoft/api-extractor/pgonzal-upgrade-tsdoc_2018-10-25-08-30.json
common/config/rush/shrinkwrap.yaml
rush.json

This was a TSDoc issue.  Fixed by upgrading to **\@microsoft/tsdoc** 0.9.3.
Fixes https://github.com/Microsoft/web-build-tools/issues/901

[api-extractor] Fix issue where docs sometimes show `[object Object]` instead of text

---

common/changes/@microsoft/gulp-core-build-typescript/pgonzal-rsc-cyclic-bug_2018-11-01-20-48.json
common/changes/@microsoft/rush-stack-compiler/pgonzal-rsc-cyclic-bug_2018-11-01-20-48.json
core-build/gulp-core-build-typescript/src/RSCTask.ts
stack/rush-stack-compiler/tsconfig.json
stack/rush-stack-compiler/tslint.json

This fixes a regression from PR https://github.com/Microsoft/web-build-tools/pull/919

[rush-stack] Fix a regression where @microsoft/rush-stack-compiler could not compile itself

---

.pullapprove.yml

Remove qz2017 as an approver as this config is breaking PullApprove (and she is no longer with the company).

Remove qz2017 from approvers

---

apps/api-extractor/src/analyzer/Span.ts
apps/api-extractor/src/analyzer/TypeScriptHelpers.ts
apps/api-extractor/src/generators/DtsRollupGenerator.ts
build-tests/api-extractor-test-01/dist/beta/api-extractor-test-01.d.ts
build-tests/api-extractor-test-01/dist/internal/api-extractor-test-01.d.ts
build-tests/api-extractor-test-01/dist/public/api-extractor-test-01.d.ts
build-tests/api-extractor-test-01/etc/api-extractor-test-01.api.ts
build-tests/api-extractor-test-01/src/index.ts
build-tests/api-extractor-test-01/src/variableDeclarations.ts
common/changes/@microsoft/api-extractor/pgonzal-issue976_2018-12-05-01-05.json

[api-extractor] Fix an issue where .d.ts trimming did not properly handle variable declarations

---

apps/api-extractor/src/analyzer/AstModule.ts
apps/api-extractor/src/analyzer/AstSymbolTable.ts
apps/api-extractor/src/analyzer/ExportAnalyzer.ts
apps/api-extractor/src/collector/Collector.ts
build-tests/api-documenter-test/etc/api-documenter-test.api.json
build-tests/api-extractor-scenarios/build-config.json
build-tests/api-extractor-scenarios/etc/test-outputs/apiItemKinds/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/etc/test-outputs/circularImport1/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/etc/test-outputs/circularImport1/api-extractor-scenarios.api.ts
build-tests/api-extractor-scenarios/etc/test-outputs/circularImport1/rollup.d.ts
build-tests/api-extractor-scenarios/etc/test-outputs/circularImport2/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/etc/test-outputs/circularImport2/api-extractor-scenarios.api.ts
build-tests/api-extractor-scenarios/etc/test-outputs/circularImport2/rollup.d.ts
build-tests/api-extractor-scenarios/etc/test-outputs/defaultExportOfEntryPoint1/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/etc/test-outputs/defaultExportOfEntryPoint2/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/etc/test-outputs/defaultExportOfEntryPoint3/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/etc/test-outputs/defaultExportOfEntryPoint4/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/etc/test-outputs/exportDuplicate1/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/etc/test-outputs/exportImportedExternal/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/etc/test-outputs/exportStar1/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/etc/test-outputs/exportStar2/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/etc/test-outputs/exportStar3/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/src/circularImport1/IFile.ts
build-tests/api-extractor-scenarios/src/circularImport1/IFolder.ts
build-tests/api-extractor-scenarios/src/circularImport1/index.ts
build-tests/api-extractor-scenarios/src/circularImport2/IFile.ts
build-tests/api-extractor-scenarios/src/circularImport2/IFolder.ts
build-tests/api-extractor-scenarios/src/circularImport2/index.ts
common/changes/@microsoft/api-extractor/pgonzal-ae-circular-imports_2019-01-17-11-13.json

Fixes issue https://github.com/Microsoft/web-build-tools/issues/1033

[api-extractor] Improve "export * from" to support cyclic references

---

apps/rush-lib/src/api/RushConfiguration.ts
apps/rush-lib/src/index.ts
apps/rush-lib/src/logic/InstallManager.ts
apps/rush-lib/src/schemas/rush.schema.json
common/changes/@microsoft/rush/add-ignore-engines-file-config_2019-02-06-23-29.json
common/reviews/api/rush-lib.api.ts

Opening this PR for discussion and a possible direction towards #1083. Thanks for your consideration.
TODO:
* Add tests.
* I'm not sure if this change actually works yet, wasn't sure how I could test this locally.
Refs #1083
Spinoff from #1084

[rush] Add support for Yarn options with the --ignore-engines flag

---

apps/api-documenter/CHANGELOG.json
apps/api-documenter/package.json
apps/api-extractor/package.json
build-tests/api-documenter-test/package.json
build-tests/api-extractor-lib1-test/package.json
build-tests/api-extractor-lib2-test/package.json
build-tests/api-extractor-lib3-test/package.json
build-tests/api-extractor-scenarios/package.json
build-tests/api-extractor-test-01/package.json
build-tests/api-extractor-test-02/package.json
build-tests/api-extractor-test-04/package.json
core-build/gulp-core-build-typescript/CHANGELOG.json
core-build/gulp-core-build-typescript/package.json
stack/rush-stack-compiler-2.4/CHANGELOG.json
stack/rush-stack-compiler-2.4/package.json
stack/rush-stack-compiler-2.7/CHANGELOG.json
stack/rush-stack-compiler-2.7/package.json
stack/rush-stack-compiler-2.9/CHANGELOG.json
stack/rush-stack-compiler-2.9/package.json
stack/rush-stack-compiler-3.0/CHANGELOG.json
stack/rush-stack-compiler-3.0/package.json
stack/rush-stack-compiler-3.1/CHANGELOG.json
stack/rush-stack-compiler-3.1/package.json
stack/rush-stack-compiler-3.2/CHANGELOG.json
stack/rush-stack-compiler-3.2/package.json
stack/rush-stack-compiler-3.3/CHANGELOG.json
stack/rush-stack-compiler-3.3/package.json

Second half of changes from PR #1111

[api-extractor] (Part 2) Rollback incorrectly published version 8.0.0 -> 7.0.19

---

common/changes/@microsoft/gulp-core-build-serve/master_2019-03-05-05-33.json
core-build/gulp-core-build-serve/src/TrustCertTask.ts
core-build/gulp-core-build-serve/src/UntrustCertTask.ts
core-build/gulp-core-build-serve/src/certificates.ts
core-build/gulp-core-build-serve/src/sudoSync.ts

When removing default exports this line was missed.

Fix broken require

---

apps/api-documenter/package.json
apps/rush-lib/package.json
apps/rush-lib/src/api/test/repo/project1/package.json
apps/rush-lib/src/api/test/repo/project2/package.json
apps/rush/src/test/sandbox/legacy-repo/project/package.json
apps/rush/src/test/sandbox/repo/project/package.json
common/changes/@microsoft/api-documenter/octogonz-security-warnings_2019-04-25-16-31.json
common/changes/@microsoft/rush/octogonz-security-warnings_2019-04-25-16-31.json
common/config/rush/pnpm-lock.yaml

Fixes https://github.com/Microsoft/web-build-tools/issues/1245

Upgrade some packages to fix security warnings

---

apps/rush-lib/assets/rush-init/common/config/rush/command-line.json
common/changes/@microsoft/rush/command_line_action_colon_2019-05-03-21-06.json
common/changes/@microsoft/ts-command-line/command_line_action_colon_2019-05-03-21-06.json
libraries/ts-command-line/src/CommandLineAction.ts
libraries/ts-command-line/src/test/CommandLineParameter.test.ts
libraries/ts-command-line/src/test/CommandLineParser.test.ts
libraries/ts-command-line/src/test/DynamicCommandLineParser.test.ts
libraries/ts-command-line/src/test/__snapshots__/CommandLineParameter.test.ts.snap

[rush] Allow colons in command line action names

---

apps/api-extractor/src/api/ExtractorConfig.ts
apps/api-extractor/src/api/IConfigFile.ts
apps/api-extractor/src/collector/Collector.ts
apps/api-extractor/src/generators/DtsRollupGenerator.ts
apps/api-extractor/src/schemas/api-extractor-defaults.json
apps/api-extractor/src/schemas/api-extractor-template.json
apps/api-extractor/src/schemas/api-extractor.schema.json
common/changes/@microsoft/api-extractor/octogonz-ae-issue1261_2019-05-05-19-26.json
common/reviews/api/api-extractor.api.md

Fixes https://github.com/Microsoft/web-build-tools/issues/1261

[api-extractor] Add a new setting "omitTrimmingComments"

---

apps/rush-lib/src/logic/taskRunner/ITask.ts
apps/rush-lib/src/logic/taskRunner/ProjectTask.ts
apps/rush-lib/src/logic/taskRunner/TaskRunner.ts
apps/rush-lib/src/logic/taskRunner/test/TaskRunner.test.ts
common/changes/@microsoft/rush/octogonz-rush-issue1282_2019-05-19-19-55.json

[rush] Fix an issue where "rush build" ignored changes for projects with an empty build script

---

apps/rush-lib/src/cli/actions/AddAction.ts
common/changes/@microsoft/rush/octogonz-fix-typo_2019-05-26-23-55.json

@hugmoro fixed the website docs in PR https://github.com/microsoft/rushjs.io-website/pull/31
But we also need to update the tool itself.  ;-P

[rush] Fix typo in command-line help for "rush add"

---

common/changes/@microsoft/ts-command-line/octogonz-tsc-fix-broken-link_2019-05-27-03-57.json
libraries/ts-command-line/README.md

Fixes https://github.com/microsoft/web-build-tools/issues/1285

[ts-command-link] Fix broken link in README.md

---

common/changes/@microsoft/api-documenter/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/api-extractor-model/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/api-extractor/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/gulp-core-build-sass/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/gulp-core-build-serve/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/gulp-core-build-typescript/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/gulp-core-build-webpack/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/load-themed-styles/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/loader-load-themed-styles/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/loader-raw-script/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/loader-set-webpack-public-path/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/node-library-build/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/package-deps-hash/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/resolve-chunk-plugin/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/rush-stack-compiler-2.4/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/rush-stack-compiler-2.7/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/rush-stack-compiler-2.8/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/rush-stack-compiler-2.9/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/rush-stack-compiler-3.0/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/rush-stack-compiler-3.1/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/rush-stack-compiler-3.2/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/rush-stack-compiler-3.3/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/rush-stack-compiler-3.4/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/rush-stack/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/rush/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/set-webpack-public-path-plugin/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/stream-collator/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/ts-command-line/patch-2_2019-06-11-21-15.json
common/changes/@microsoft/web-library-build/patch-2_2019-06-11-21-15.json
libraries/ts-command-line/README.md

`app.execute();`
Corrected the call to app.execute() in index.ts
See the issue here.
https://github.com/microsoft/web-build-tools/issues/1287

Updated typo for the index.ts example.

---

apps/rush-lib/src/utilities/VersionControl.ts
common/changes/@microsoft/rush/ianc-fix-rush-change_2019-07-02-22-59.json

This is a fix for https://github.com/microsoft/web-build-tools/issues/1177

[rush] Fix an issue where rush change will detect unrelated changes.

---

apps/api-extractor/src/api/CompilerState.ts
common/changes/@microsoft/api-extractor/octogonz-ae-issue1310_2019-07-05-04-27.json

Fixes https://github.com/microsoft/web-build-tools/issues/1310

[api-extractor] Fix a problem analyzing .d.ts files found in the same folder as the .ts file

---

apps/rush-lib/src/logic/PackageJsonUpdater.ts
common/changes/@microsoft/rush/ianc-fix-rush-add_2019-07-03-03-03.json
common/changes/@microsoft/rush/ianc-fix-rush-add_2019-07-03-03-07.json

Reverts microsoft/web-build-tools#1362
Un-reverting this to see a cleaner diff on https://github.com/microsoft/web-build-tools/pull/1363

Revert "Revert "[rush] Fix an issue where "rush add" erroneously believes ensureConsistentVersions is unset.""

---

.github/ISSUE_TEMPLATE/issue-template.md

Remove Issue template as name and other unnecessary options

remove unnecessary info

---

apps/rush-lib/src/logic/EventHooksManager.ts
common/changes/@microsoft/rush/ianc-fix-rush-events_2019-07-17-23-30.json

This addresses https://github.com/microsoft/web-build-tools/issues/1352

[rush] Change the working directory for event hooks to the rush.json directory.

---

common/changes/@microsoft/ts-command-line/apc-command-numbers_2019-08-08-18-33.json
libraries/ts-command-line/src/CommandLineAction.ts

[rush] allow command name to use numbers

---

apps/rush-lib/src/scripts/install-run-rush.ts
common/changes/@microsoft/rush/install-run-version_2019-07-31-21-56.json

install-run doesn't respect RUSH_PREVIEW_VERSION environment variable

---

apps/rush-lib/src/scripts/install-run.ts
common/changes/@microsoft/rush/intall-run-temp_2019-07-31-21-34.json

[rush] install-run doesn't respect RUSH_TEMP_FOLDER environment variable

---

apps/rush-lib/src/logic/StandardScriptUpdater.ts
common/changes/@microsoft/rush/script-updater-rushx_2019-08-22-22-52.json

Looks like we missed this in #1440

[rush] Teach StandardScriptUpdater to update install-run-rushx.js

---

apps/api-extractor/src/api/ExtractorConfig.ts
common/changes/@microsoft/api-extractor/fix-pass-in-manifest-object_2019-10-03-01-05.json

[api-extractor] Fix handling of packageJson option

---

common/changes/@microsoft/gulp-core-build-webpack/jowedeki-multi-compiler_2019-10-03-08-58.json
common/reviews/api/gulp-core-build-webpack.api.md
core-build/gulp-core-build-webpack/src/WebpackTask.ts

Add ability to pass array of webpack configs

---

common/changes/@microsoft/package-deps-hash/ianc-command-length-issue_2019-10-10-22-39.json
common/changes/@microsoft/rush/ianc-command-length-issue_2019-10-10-22-39.json
libraries/package-deps-hash/package.json
libraries/package-deps-hash/src/getPackageDeps.ts

Fixes https://github.com/microsoft/rushstack/issues/1579

[rush] Fix an issue where "rush build" will fail because a git command can be too long.

---

README.md
common/changes/@rushstack/eslint-config/octogonz-rename-eslint-config_2019-10-13-04-33.json
common/changes/@rushstack/eslint-config/octogonz-rename-eslint-config_2019-10-13-04-39.json
common/config/rush/pnpm-lock.yaml
rush.json
stack/eslint-config/CHANGELOG.json
stack/eslint-config/CHANGELOG.md
stack/eslint-config/README.md
stack/eslint-config/index.js
stack/eslint-config/package.json
stack/eslint-config/patch-eslint6.js
stack/eslint-config/react.js

Seems that nobody can ever remember the name `eslint-config-scalable-ts`. 🤭
And `@rushstack` means scalable TypeScript.

Rename "@microsoft/eslint-config-scalable-ts" to be "@rushstack/eslint-config"

---

apps/rush-lib/src/logic/PackageJsonUpdater.ts
common/changes/@microsoft/rush/yarn-rush-add_2019-10-13-20-03.json

[rush] Add rush add support for yarn

---

apps/api-extractor-model/src/mixins/ApiItemContainerMixin.ts
apps/api-extractor/src/collector/MessageRouter.ts
apps/rush-lib/src/logic/taskRunner/TaskCollection.ts
common/changes/@microsoft/api-extractor-model/octogonz-stable-sort_2019-11-02-20-23.json
common/changes/@microsoft/api-extractor/octogonz-stable-sort_2019-11-02-20-23.json
common/changes/@microsoft/node-core-library/octogonz-stable-sort_2019-11-02-20-23.json
common/changes/@microsoft/rush/octogonz-stable-sort_2019-11-02-20-23.json
common/config/rush/nonbrowser-approved-packages.json
common/config/rush/pnpm-lock.yaml
common/reviews/api/node-core-library.api.md
libraries/node-core-library/package.json
libraries/node-core-library/src/LegacyAdapters.ts
libraries/node-core-library/src/Sort.ts

Fixes https://github.com/microsoft/rushstack/issues/1552

[api-extractor] Fix inconsistent sorting of APIs on older NodeJS versions

---

apps/api-extractor-model/package.json
apps/rush-lib/package.json
build-tests/web-library-build-test/package.json
common/changes/@microsoft/api-extractor-model/octogonz-misc-fixes_2019-11-07-16-25.json
common/changes/@microsoft/gulp-core-build-mocha/octogonz-misc-fixes_2019-11-07-16-25.json
common/changes/@microsoft/gulp-core-build-typescript/octogonz-misc-fixes_2019-11-07-16-25.json
common/changes/@microsoft/gulp-core-build/octogonz-misc-fixes_2019-11-07-16-25.json
common/changes/@microsoft/resolve-chunk-plugin/octogonz-misc-fixes_2019-11-07-16-25.json
common/changes/@microsoft/rush/octogonz-misc-fixes_2019-11-07-16-25.json
common/config/rush/nonbrowser-approved-packages.json
core-build/gulp-core-build-mocha/package.json
core-build/gulp-core-build-typescript/package.json
core-build/gulp-core-build/package.json
core-build/gulp-core-build/src/tasks/JestTask.ts
webpack/resolve-chunk-plugin/package.json

The changes required to get our repo building with the new `implicitlyPreferredVersions=false`  feature from PR https://github.com/microsoft/rushstack/pull/1618

Update repo to work with implicitlyPreferredVersions=false

---

apps/rush-lib/assets/rush-init/common/config/rush/common-versions.json
apps/rush-lib/src/api/CommonVersionsConfiguration.ts
apps/rush-lib/src/logic/InstallManager.ts
apps/rush-lib/src/schemas/common-versions.schema.json
common/changes/@microsoft/rush/octogonz-no-implicitly-preferred-versions_2019-11-07-05-34.json
common/reviews/api/rush-lib.api.md

Fixes #1415
See [these notes](https://github.com/microsoft/rushstack/issues/1415#issuecomment-524168914) for motivation behind this change.

[rush] Add new setting "implicitlyPreferredVersions" for common-versions.json

---

apps/rush-lib/assets/rush-init/common/config/rush/common-versions.json
apps/rush-lib/src/api/CommonVersionsConfiguration.ts
apps/rush-lib/src/logic/InstallManager.ts
apps/rush-lib/src/logic/pnpm/PnpmProjectDependencyManifest.ts
apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
common/changes/@microsoft/rush/octogonz-rush-optional-peer-deps_2019-11-12-21-54.json

Fixes https://github.com/microsoft/rushstack/issues/1621

[rush] Improve shrinkwrap-deps.json logic to support optional peer dependencies

---

apps/api-extractor/src/api/ExtractorConfig.ts
common/changes/@microsoft/api-extractor/octogonz-ae-newlines-fix_2019-11-20-03-46.json
common/changes/@microsoft/gulp-core-build-webpack/octogonz-ae-newlines-fix_2019-11-20-04-21.json
common/changes/@microsoft/gulp-core-build-webpack/octogonz-ae-newlines-fix_2019-11-20-05-21.json
common/changes/@microsoft/loader-load-themed-styles/octogonz-ae-newlines-fix_2019-11-20-04-21.json
common/changes/@microsoft/resolve-chunk-plugin/octogonz-ae-newlines-fix_2019-11-20-04-21.json
common/changes/@microsoft/set-webpack-public-path-plugin/octogonz-ae-newlines-fix_2019-11-20-04-21.json
common/config/rush/common-versions.json
common/config/rush/pnpm-lock.yaml
core-build/gulp-core-build-webpack/package.json
core-build/gulp-core-build-webpack/src/webpack.config.ts
webpack/loader-load-themed-styles/package.json
webpack/resolve-chunk-plugin/package.json
webpack/set-webpack-public-path-plugin/package.json

This fixes a minor issue introduced with https://github.com/microsoft/rushstack/pull/1626

[api-extractor] Fix an issue where the newlineKind setting wasn't being applied correctly

---

apps/rush-lib/src/logic/taskRunner/test/TaskRunner.test.ts
apps/rush-lib/src/logic/taskRunner/test/__snapshots__/TaskRunner.test.ts.snap
common/changes/@microsoft/rush/octogonz-fix-rush-lib-test_2019-12-03-03-07.json

The Jest snapshot included a timing value `0.00 seconds` that was nonzero on slow machines

[rush-lib] Fix unit test that was failing intermittently

---

apps/api-extractor/src/generators/DeclarationReferenceGenerator.ts
common/changes/@microsoft/api-extractor/octogonz-ae-issue-1652_2020-01-09-01-47.json

Fixes https://github.com/microsoft/rushstack/issues/1652
Repro included with that issue.
@acalvo

[api-extractor] Fix an error "Cannot read property 'externalModuleIndicator' of undefined"

---

common/changes/@rushstack/eslint-plugin/no-nulls-allow-more-conditionals_2020-01-16-14-51.json
stack/eslint-plugin/src/no-null.ts

[eslint-plugin] Allow null with == and != conditionals in no-null rule

---

apps/rush-lib/src/api/PackageJsonEditor.ts
apps/rush-lib/src/logic/PublishUtilities.ts
apps/rush-lib/src/logic/VersionManager.ts
common/changes/@microsoft/rush/ianc-stable-package-change_2020-01-24-00-47.json

Addresses this: https://github.com/microsoft/rushstack/issues/1701

[rush] [WIP] Update package.json files in-place.

---

apps/rush-lib/assets/rush-init/common/config/rush/command-line.json
apps/rush-lib/src/api/CommandLineJson.ts
apps/rush-lib/src/cli/scriptActions/BaseScriptAction.ts
apps/rush-lib/src/schemas/command-line.schema.json
common/changes/@microsoft/rush/octogonz-rush-required-params_2020-03-05-02-59.json

Fixes https://github.com/microsoft/rushstack/issues/1762

[rush] Add a new command-line.json setting "required"

---

apps/rush-lib/src/logic/taskRunner/ProjectTask.ts
common/changes/@microsoft/rush/zhas-delete-redundant-rush-rebuild-output_2020-03-27-19-31.json

This PR aims to fix the issue: #1733

[rush] Clean up some unhelpful incremental build logging messages.

---

apps/api-documenter/package.json
apps/api-extractor-model/package.json
apps/api-extractor/package.json
common/changes/@microsoft/api-documenter/octogonz-upgrade-tsdoc_2020-03-27-23-25.json
common/changes/@microsoft/api-extractor-model/octogonz-upgrade-tsdoc_2020-03-27-23-25.json
common/changes/@microsoft/api-extractor/octogonz-upgrade-tsdoc_2020-03-27-23-25.json
common/changes/@rushstack/eslint-config/octogonz-upgrade-tsdoc_2020-03-27-23-25.json
common/changes/@rushstack/localization-plugin/octogonz-upgrade-tsdoc_2020-03-27-23-25.json
common/changes/@rushstack/typings-generator/octogonz-upgrade-tsdoc_2020-03-27-23-25.json
common/config/rush/pnpm-lock.yaml
libraries/typings-generator/package.json
repo-scripts/doc-plugin-rush-stack/package.json
stack/eslint-config/package.json
webpack/localization-plugin/package.json

Fixes https://github.com/microsoft/rushstack/issues/1792
Also updates `@rushstack/eslint-config` with the fix for https://github.com/microsoft/tsdoc/pull/212

Upgrade TSDoc library

---

apps/rush-lib/src/logic/InstallManager.ts
common/changes/@microsoft/rush/sunilsurana-issue-1834_2020-04-21-12-32.json

Fix for [Issue-1834](https://github.com/microsoft/rushstack/issues/1834)

[rush] Add common-versions.json file in potentially changed file list.

---

apps/api-documenter/src/documenters/YamlDocumenter.ts
build-tests/api-documenter-test/etc/yaml/api-documenter-test/docclass1.yml
common/changes/@microsoft/api-documenter/fix1840_2020-04-23-03-15.json

Fix link emit for xref containing #

---

apps/rush-lib/assets/rush-init/rush.json
apps/rush-lib/src/api/CommonVersionsConfiguration.ts
apps/rush-lib/src/api/PackageNameParsers.ts
apps/rush-lib/src/api/RushConfiguration.ts
apps/rush-lib/src/api/RushConfigurationProject.ts
apps/rush-lib/src/cli/actions/AddAction.ts
apps/rush-lib/src/logic/ApprovedPackagesChecker.ts
apps/rush-lib/src/logic/base/BaseShrinkwrapFile.ts
apps/rush-lib/src/logic/npm/NpmLinkManager.ts
apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts
apps/rush-lib/src/logic/yarn/YarnShrinkwrapFile.ts
apps/rush-lib/src/schemas/rush.schema.json
common/changes/@microsoft/rush/octogonz-rush-mostly-standard_2020-05-20-06-40.json
common/changes/@rushstack/node-core-library/octogonz-rush-mostly-standard_2020-05-20-06-40.json
common/reviews/api/node-core-library.api.md
common/reviews/api/rush-lib.api.md
libraries/node-core-library/src/PackageName.ts
libraries/node-core-library/src/index.ts

Fixes https://github.com/microsoft/rushstack/issues/1860

[rush] Add "allowMostlyStandardPackageNames" setting in rush.json

---

apps/rush-lib/src/scripts/install-run.ts
common/changes/@microsoft/rush/clean-install-folder-windows_2020-05-20-20-42.json

- Windows does not allow renaming a directory to an existing directory
- Fixes #1878

[rush] Do not create "install-run" folder before rename

---

apps/rush-lib/src/logic/NodeJsCompatibility.ts
common/changes/@microsoft/rush/aeisenberg-node-version_2020-05-29-16-56.json

[Rush] Update UPCOMING_NODE_LTS_VERSION

---

apps/rush-lib/src/logic/deploy/DeployManager.ts
common/changes/@microsoft/rush/octogonz-rush-depoy-default_2020-06-02-02-46.json
common/config/rush/version-policies.json

Reported by @devin-fee-ah in https://github.com/microsoft/rushstack/issues/1906#issuecomment-637215407

[rush] Fix incorrect default for "linkCreation" setting for "rush deploy"

---

apps/rush-lib/src/logic/deploy/DeployManager.ts
common/changes/@microsoft/rush/octogonz-rush-deploy-issue1910_2020-06-04-22-21.json

Fixes https://github.com/microsoft/rushstack/issues/1910

[rush-deploy] Fix an issue where "rush deploy" sometimes created incorrect symlinks on Mac OS

---

apps/rush-lib/src/scripts/install-run.ts
common/changes/@microsoft/rush/master_2020-06-05-18-36.json

Fixes #1917 
I'm not sure, though, how to write a regression test for this.

fix(rush): install-run.js is not able to find its own .bin in PATH

---

.gitignore
.prettierignore
apps/rush-lib/assets/rush-init/common/config/rush/common-versions.json
apps/rush-lib/assets/rush-init/common/config/rush/pnpmfile.js
apps/rush-lib/assets/rush-init/common/git-hooks/commit-msg.sample
apps/rush-lib/assets/rush-init/rush.json
apps/rush-lib/src/cli/actions/InitAction.ts
apps/rush-lib/src/logic/InstallManager.ts
apps/rush-lib/src/logic/pnpm/PnpmLinkManager.ts
common/autoinstallers/rush-prettier/package.json
common/autoinstallers/rush-prettier/pnpm-lock.yaml
common/changes/@microsoft/rush/octogonz-rush-prettier-hook_2020-06-11-00-17.json
common/changes/@microsoft/rush/octogonz-rush-prettier-hook_2020-06-11-01-21.json
common/changes/@microsoft/rush/octogonz-rush-prettier-hook_2020-06-11-02-10.json
common/config/rush/command-line.json
common/config/rush/experiments.json
common/config/rush/version-policies.json
common/git-hooks/pre-commit
common/scripts/install-run-rush.js
common/scripts/install-run.js
rush.json

I also upgraded Rush in this PR. The meaningful code review starts from 0a28615
And I fixed some miscellaneous minor Rush issues encountered during testing.

Enable Git hook for Prettier

---

common/config/azure-pipelines/ci.yaml
rush.json

This reverts commit 486a60d249cc0674075afb807bbbfaf17a08201a.

Drop support for Node 8.

---

apps/rush-lib/src/logic/deploy/DeployManager.ts
apps/rush-lib/src/logic/deploy/PnpmfileConfiguration.ts
common/changes/@microsoft/rush/octogonz-rush-deploy-pnpmfile_2020-06-20-04-00.json
rush.json

Fixes https://github.com/microsoft/rushstack/issues/1941

[rush] Improve "rush deploy" to apply pnpmfile.js when calculating dependencies

---

apps/rush-lib/assets/rush-init/common/config/rush/[dot]npmrc
apps/rush-lib/assets/rush-init/common/config/rush/[dot]npmrc-publish
apps/rush-lib/src/cli/actions/InitAction.ts
apps/rush-lib/src/cli/actions/PublishAction.ts
apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
apps/rush-lib/src/scripts/install-run.ts
apps/rush-lib/src/utilities/Utilities.ts
common/changes/@microsoft/rush/octogonz-npmrc-publish-docs_2020-06-23-06-56.json
common/changes/@microsoft/rush/octogonz-npmrc-publish-docs_2020-06-23-06-57.json

Fixes https://github.com/microsoft/rushstack/issues/1951

[rush] Add a "rush init" template for .npmrc-publish

---

apps/api-extractor/CHANGELOG.json
apps/api-extractor/CHANGELOG.md
apps/rush/CHANGELOG.json
apps/rush/CHANGELOG.md
libraries/typings-generator/package.json
webpack/localization-plugin/package.json

`github.com/Microsoft` -> `github.com/microsoft`

Fix capitalization of GitHub org

---

apps/rush-lib/assets/rush-init-deploy/scenario-template.json
apps/rush-lib/src/logic/deploy/DeployArchiver.ts
apps/rush-lib/src/logic/deploy/DeployManager.ts
apps/rush-lib/src/logic/deploy/DeployScenarioConfiguration.ts
apps/rush-lib/src/logic/deploy/Utils.ts
apps/rush-lib/src/schemas/deploy-scenario.schema.json
common/changes/@microsoft/rush/feat-1978_2020-07-13-14-37.json

[rush] Implement support for selecting a subset of dependencies to deploy

---

apps/heft/src/cli/HeftToolsCommandLineParser.ts
apps/heft/src/cli/actions/BuildAction.ts
apps/heft/src/cli/actions/CleanAction.ts
apps/heft/src/cli/actions/DevDeployAction.ts
apps/heft/src/cli/actions/HeftActionBase.ts
apps/heft/src/cli/actions/StartAction.ts
apps/heft/src/cli/actions/TestAction.ts
apps/heft/src/index.ts
apps/heft/src/pluginFramework/HeftSession.ts
apps/heft/src/plugins/ActionConfigurationLoaders/ActionConfigurationFilesPluginBase.ts
apps/heft/src/plugins/ApiExtractorPlugin/ApiExtractorPlugin.ts
apps/heft/src/plugins/CleanPlugin.ts
apps/heft/src/plugins/CopyStaticAssetsPlugin.ts
apps/heft/src/plugins/JestPlugin/JestPlugin.ts
apps/heft/src/plugins/PackageJsonConfigurationPlugin.ts
apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
apps/heft/src/plugins/TypeScriptPlugin/TypeScriptPlugin.ts
apps/heft/src/plugins/Webpack/BasicConfigureWebpackPlugin.ts
apps/heft/src/plugins/Webpack/WebpackPlugin.ts
apps/heft/src/stages/BuildStage.ts
apps/heft/src/stages/CleanStage.ts
apps/heft/src/stages/DevDeployStage.ts
apps/heft/src/stages/StageBase.ts
apps/heft/src/stages/TestStage.ts
apps/heft/src/utilities/Logging.ts
common/changes/@rushstack/heft/ianc-heft-action-refactor_2020-07-17-20-37.json
common/reviews/api/heft.api.md

This PR moves the Clean, Test, and Build stages into their own operations, separate from the CLI actions.

[Heft] Extract stage execution from CLI actions.

---

apps/heft/src/plugins/Webpack/WebpackPlugin.ts
common/changes/@rushstack/heft/ianc-webpack-errors_2020-07-30-05-56.json

This PR fixes https://github.com/microsoft/rushstack/issues/2032.

[heft] Emit errors and warnings from webpack.

---

apps/api-extractor/package.json
common/changes/@microsoft/api-extractor/patch-1_2020-08-12-18-25.json
common/changes/@rushstack/typings-generator/patch-1_2020-08-12-18-25.json
libraries/typings-generator/package.json

Basically, i forgot the name of this project, and went to search npm for "dts bundle" and it didn't show up, so this should help with that. bless my github stars for being able to find it again.

Add some keywords to improve discoverability

---

apps/rush-lib/src/cli/actions/DeployAction.ts
common/changes/@microsoft/rush/octogonz-rush-deploy-simultaneous_2020-08-20-17-53.json

Fixes https://github.com/microsoft/rushstack/issues/2125

[rush] Allow multiple simultaneous invocations of "rush deploy"

---

apps/api-extractor-model/src/model/ModelReferenceResolver.ts
common/changes/@microsoft/api-extractor-model/octogonz-ae-2152_2020-09-04-22-08.json

[api-documenter] Fix error "Converting circular structure to JSON"

---

rush.json

🎈 Let's try out the new `rush build` output!

Upgrade to Rush version 5.34.0-pr2172.0

---

common/changes/@rushstack/eslint-config/octogonz-eslint-config-deps_2020-09-22-05-31.json
stack/eslint-config/.npmignore
stack/eslint-config/CHANGELOG.json
stack/eslint-config/index.js
stack/eslint-config/react.js

The .npmignore file needed to be updated with the newly introduced file paths

[eslint-config] Add some files missing from npmignore

---

apps/rush-lib/assets/rush-init/common/config/rush/command-line.json
common/changes/@microsoft/rush/pr-paynecodes-2255_2020-10-02-19-10.json

PR as requested here: https://gitter.im/rushstack/rushstack?at=5f761a7adaf8227643aed679

Add documentation for incremental option for bulk custom commands

---

apps/rush-lib/src/cli/actions/ScanAction.ts
common/changes/@microsoft/rush/octogonz-rush-scan_2020-10-30-02-31.json

Fixes https://github.com/microsoft/rushstack/issues/2322

[rush] Fix a "rush scan" regression

---

apps/heft/src/plugins/JestPlugin/JestPlugin.ts
common/changes/@rushstack/heft/deadjestcode_2020-11-10-07-02.json

Remove dead code from Heft-Jest that was missed in [prior PR](https://github.com/microsoft/rushstack/pull/2290)

[heft] Chore: Remove dead code from Heft-Jest

---

apps/heft/src/schemas/heft.schema.json
apps/heft/src/templates/heft.json
common/changes/@rushstack/heft/octogonz-heft-schema_2020-11-11-21-46.json

Code comments are not allowed in a JSON schema file.
CC @D4N14L @iclanton

[heft] Remove JSON schema comments

---

common/changes/@rushstack/typings-generator/halfnibble-keep-typings-dir-watch_2021-01-06-00-13.json
libraries/typings-generator/src/TypingsGenerator.ts

Instead of ensuring an empty folder when generating typings in watch mode, just ensure the folder exists.
This is to prevent typings being erased after preCompile and while TSC is compiling in the compile phase. 
Very carefully.

[typings-generator] Keep typings folder during run watch

---

apps/rush-lib/assets/rush-init/rush.json
apps/rush-lib/src/logic/NodeJsCompatibility.ts
common/changes/@microsoft/rush/allow-node-lts-14_2021-01-12-20-14.json
common/config/azure-pipelines/ci.yaml
rush.json

I noticed that Node 14 LTS wasn't allowed in the rushstack monorepo, and I assume we support LTS in the monorepo.
I just added `|| 14` because that'll work for any minor/patch under version 14.
Ran rush update and rush build after, seems to work! :+1:

[rush] Allow node LTS version 14 in the monorepo

---

apps/rush-lib/src/cli/actions/InstallAction.ts
apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
apps/rush-lib/src/logic/LookupByPath.ts
common/changes/@microsoft/rush/ianc-improve-write-build-cache-logging_2021-01-12-01-18.json
common/changes/@microsoft/rush/master_2021-01-28-02-28.json
common/changes/@microsoft/rush/octogonz-publish-rush_2021-01-29-23-44.json
common/config/rush/version-policies.json
tutorials/heft-node-jest-tutorial/src/guide/01-automatic-mock.test.ts

Fix some issues I encountered while testing Rush.  Prepare to publish a MINOR release.

[rush] Prepare to publish a minor release

---

common/changes/@rushstack/node-core-library/octogonz-rush-setup-prereqs_2021-02-04-06-01.json
common/changes/@rushstack/node-core-library/octogonz-rush-setup-prereqs_2021-02-04-06-02.json
common/reviews/api/node-core-library.api.md
libraries/node-core-library/src/EnvironmentMap.ts
libraries/node-core-library/src/Executable.ts
libraries/node-core-library/src/index.ts
libraries/node-core-library/src/test/EnvironmentMap.test.ts
libraries/node-core-library/src/test/Executable.test.ts

These APIs are required by the upcoming `rush setup` feature.  I've split them into a separate PR to facilitate review.
Tested with the `rush setup` branch;  I'll post that PR tomorrow.

[node-core-library] Add some new APIs

---

apps/api-documenter/src/utils/ToSdpConvertHelper.ts
apps/api-documenter/src/yaml/ISDPYamlFile.ts
apps/api-extractor/src/analyzer/ExportAnalyzer.ts
apps/heft/src/cli/actions/CustomAction.ts
apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
apps/heft/src/stages/BuildStage.ts
apps/heft/src/utilities/CoreConfigFiles.ts
apps/heft/src/utilities/subprocess/SubprocessLoggerManager.ts
apps/heft/src/utilities/subprocess/SubprocessRunnerBase.ts
apps/rush-lib/src/api/RushProjectConfiguration.ts
apps/rush-lib/src/logic/PackageJsonUpdater.ts
common/autoinstallers/rush-prettier/package.json
common/autoinstallers/rush-prettier/pnpm-lock.yaml
common/changes/@microsoft/api-documenter/octogonz-upgrade-rush_2021-02-05-02-16.json
common/changes/@microsoft/api-extractor/octogonz-upgrade-rush_2021-02-05-02-16.json
common/changes/@microsoft/rush/octogonz-upgrade-rush_2021-02-05-02-16.json
common/changes/@rushstack/heft-config-file/octogonz-upgrade-rush_2021-02-05-02-16.json
common/changes/@rushstack/heft/octogonz-upgrade-rush_2021-02-05-02-16.json
common/changes/@rushstack/module-minifier-plugin/octogonz-upgrade-rush_2021-02-05-02-16.json
common/config/rush/command-line.json
common/config/rush/experiments.json
libraries/heft-config-file/src/ConfigurationFile.ts
libraries/heft-config-file/src/test/ConfigurationFile.test.ts
rush.json
webpack/module-minifier-plugin/src/ModuleMinifierPlugin.ts

This lets us use the new `--to-except` parameter. :-)

Upgrade Rush and Prettier

---

common/changes/@rushstack/rig-package/octogonz-rig-package-deps_2021-03-03-22-20.json
libraries/rig-package/package.json

`@types/node` should be a devDependency, not a regular dependency.

[rig-package] Eliminate extra dependency

---

apps/rush-lib/src/utilities/WebClient.ts
common/changes/@microsoft/rush/fix-query-published_2021-02-22-08-59.json

~Add a 10s timeout when `_queryIfReleaseIsPublishedAsync`~
Edit: After update upstream code, I see fetch is encapsulated into `webClient`. So, adding a default 10s timeout for `webClient` now. It should be better to add a default timeout for other web requests as well.
In our CI, I run into an issue `rush install` stuck forever.
the code:
```
node common/scripts/install-run-rush.js install
```
it hangs forever (like 1 day...) at `Finished creating temporary modules (0.68 seconds)`
After digging deep, I found rush invokes `_queryIfReleaseIsPublishedAsync` after preparing temp folder. this function query whether rush version is published from official npm registry. It seems to me sometime our CI system has some network issues  when connecting with official npm registry. it leads to stuck …

[rush] Fix query published

---

apps/api-documenter/src/utils/ToSdpConvertHelper.ts
apps/api-documenter/src/yaml/ISDPYamlFile.ts
build-tests/api-documenter-test/etc/yaml/api-documenter-test/docclass1.yml
common/changes/@microsoft/api-documenter/sdp_2021-03-26-03-03.json

from previous change, #2382
I have added the udp to sdp swicher.
from the UI side,
I need to split events and properties.
see the test file changes.

[api-documenter] change sdp yaml format

---

apps/heft/src/plugins/TypeScriptPlugin/EmitFilesPatch.ts
apps/heft/src/plugins/TypeScriptPlugin/TypeScriptBuilder.ts
common/changes/@rushstack/heft-node-rig/incremental-ts_2021-04-15-01-30.json
common/changes/@rushstack/heft-web-rig/incremental-ts_2021-04-15-01-30.json
common/changes/@rushstack/heft/incremental-ts_2021-04-15-01-30.json
rigs/heft-node-rig/profiles/default/tsconfig-base.json
rigs/heft-web-rig/profiles/library/tsconfig-base.json

When adding support for older versions of TypeScript, diagnostics and emit were accidentally redirected to being the responsibility of the inner program (which does not support incremental) instead of the BuilderProgram.
Fixes to prefer the BuilderProgram if defined. Also touches up other parts of the code and makes setting `noEmitOnError: false` explicit in the base rigs.
Also ensures that emit diagnostics from the incremental compilation are included in the diagnostic output.
Validated that building `@rushstack/rush-lib` multiple times in a row with no changes yields check, transform, print, and emit times of 0 ms.

Fix incremental TypeScript compilation in Heft

---

rush.json

Upgrading to see if I can repro issue https://github.com/microsoft/rushstack/issues/2619

Upgrade to Rush 5.44.0

---

apps/api-documenter/package.json
apps/api-extractor-model/package.json
apps/api-extractor/package.json
apps/api-extractor/src/api/ConsoleMessageId.ts
apps/api-extractor/src/api/Extractor.ts
apps/api-extractor/src/api/ExtractorConfig.ts
apps/api-extractor/src/collector/MessageRouter.ts
build-tests/api-documenter-test/config/api-extractor.json
build-tests/api-documenter-test/etc/api-documenter-test.api.json
build-tests/api-documenter-test/tsdoc.json
common/changes/@microsoft/api-documenter/octogonz-ae-tsdoc-file-fixes_2021-04-19-22-10.json
common/changes/@microsoft/api-documenter/users-nirice-custom-tags_2020-06-20-06-28.json
common/changes/@microsoft/api-extractor-model/octogonz-ae-tsdoc-file-fixes_2021-04-19-22-10.json
common/changes/@microsoft/api-extractor-model/users-nirice-custom-tags_2020-06-20-06-28.json
common/changes/@microsoft/api-extractor/octogonz-ae-tsdoc-file-fixes_2021-04-17-19-13.json
common/changes/@microsoft/api-extractor/users-nirice-custom-tags_2020-06-20-06-28.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
common/reviews/api/api-extractor.api.md
repo-scripts/doc-plugin-rush-stack/package.json
rush.json

The PR contains some fixes for issues found while preparing to publish PR 1950
- Add a verbose message `Using custom TSDoc config from my-project/tsdoc.json`
- Fix an issue where the `ExtractorConfig.tsdocConfiguration` was incorrectly serialized by `MessageRouter.buildJsonDumpObject()`
- Add a property  `ExtractorConfig.tsdocConfigFile` which remembers the file paths that were loaded
Most of my testing was using the [api-documenter-test](https://github.com/microsoft/rushstack/tree/master/build-tests/api-documenter-test) project which has a custom **tsdoc.json** file.

[api-extractor] Improve diagnostics for tsdoc.json file

---

apps/rush-lib/src/cli/actions/BaseInstallAction.ts
apps/rush-lib/src/logic/PackageJsonUpdater.ts
apps/rush-lib/src/logic/base/BaseInstallManager.ts
apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
common/changes/@microsoft/rush/ianc-clean-up-install-code_2021-04-28-21-49.json

Clean up some code related to hashing the shrinkwrap.
This PR includes some minor refactors to the code around hashing the shrinkwrap state.
Tested by running `rush update` against a repo that uses the shinkwrap hash.

[rush] Clean up some code in the install manager.

---

apps/rush-lib/src/logic/buildCache/AmazonS3/AmazonS3Client.ts
apps/rush-lib/src/logic/buildCache/AmazonS3/test/__snapshots__/AmazonS3Client.test.ts.snap
common/changes/@microsoft/rush/fix-s3-credentials_2021-04-29-05-23.json

As reported in the zulipchat: a regression was introduced in https://github.com/microsoft/rushstack/pull/2614 that broke the signature generation for S3 requests (the header name signature delimiter was `,` instead of `;`).  Update the code and snapshots to correct.
(As the PR template suggests... `Pushing additional commits with "small" fixes often invalidates testing.` 😢 )
N/A (this fix is for the S3 option of the experimental cloud build cache feature).
- Manually confirmed that _before_ #2614, could get/set from cache correctly; _afterwards_, received AWS Error 400.
- Manually confirmed that after this PR, could get/set from cache correctly again.

[rush-lib] Fix a regression in the S3 cloud build cache provider

---

apps/rush-lib/src/logic/taskRunner/ProjectBuilder.ts
common/changes/@microsoft/rush/octogonz-build-cache-fix_2021-05-04-19-16.json
common/config/rush/version-policies.json

Fixes a regression in Rush 5.46.0 where one of the code paths did not correctly apply the new `buildCacheEnabled` setting.
Confirmed that it fixed this issue in a repo that was upgraded to use Rush 5.46.0.

[rush] Fix issue with buildCacheEnabled setting

---

apps/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
common/changes/@microsoft/rush/fix-workspace-install-manager_2021-05-11-10-27.json

It seems to me a logic mistake in `WorkspaceInstallManager#canSkipInstall`.
`potentiallyChangedFiles` is an array of string, but for now after check the existence of `pnpmWorkspaceFilename`, only push a undefined to `potentiallyChangedFiles`

fix(rush-lib): treat pnpmWorkspacefile as potentially changed file

---

apps/rush-lib/src/utilities/TarExecutable.ts
common/changes/@microsoft/rush/octogonz-rush-issue-2622_2021-05-14-04-10.json

Fixes https://github.com/microsoft/rushstack/issues/2622
- Reproduced the error deterministically (see #2622 for details)
- Confirmed that this change fixes the problem

[rush] Fix build cache warning: "tar" exited with code 1

---

apps/rush-lib/assets/rush-init/rush.json
common/changes/@microsoft/rush/octogonz-pnpm-6.7.1_2021-06-08-01-43.json
rush.json

I got burned by this https://github.com/pnpm/pnpm/issues/3453 which is unfixed with `"pnpmVersion": "6.3.0"`

[rush] Upgrade the "rush init" template to specify the latest PNPM version

---

apps/heft/UPGRADING.md
common/changes/@rushstack/heft/octogonz-heft-upgrading-docs_2021-06-10-23-50.json

We're preparing to release https://github.com/microsoft/rushstack/pull/2721
To view the formatted Markdown:  [UPGRADING.md](https://github.com/microsoft/rushstack/blob/octogonz/heft-upgrading-docs/apps/heft/UPGRADING.md)

[heft] Improve UPGRADING.md note

---

common/changes/@rushstack/heft-jest-plugin/octogonz-clean-up-api-docs_2021-06-11-23-45.json
common/changes/@rushstack/heft-webpack4-plugin/octogonz-clean-up-api-docs_2021-06-11-23-45.json
common/changes/@rushstack/heft-webpack5-plugin/octogonz-clean-up-api-docs_2021-06-11-23-45.json
heft-plugins/heft-jest-plugin/config/api-extractor.json
heft-plugins/heft-webpack4-plugin/config/api-extractor.json
heft-plugins/heft-webpack5-plugin/config/api-extractor.json

These packages do not have meaningful API documentation.  
I regenerated the website docs in https://github.com/microsoft/rushstack.io-website/commit/0d6d76b4d230ffd0db08beecc6e76d46ea00cb99

Disable API docs for plugin packages

---

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
common/changes/@rushstack/heft-jest-plugin/octogonz-mitigate-issue2754_2021-06-16-18-26.json
heft-plugins/heft-jest-plugin/package.json

This is a temporary workaround for https://github.com/microsoft/rushstack/issues/2754
(We still need to fix the root cause.)

[heft] Temporary workaround for issue #2754

---

apps/heft/src/cli/actions/TestAction.ts
apps/heft/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
common/changes/@rushstack/heft-webpack4-plugin/octogonz-mitigate-issue2759_2021-06-18-01-57.json
common/changes/@rushstack/heft-webpack5-plugin/octogonz-mitigate-issue2759_2021-06-18-01-57.json
common/changes/@rushstack/heft/octogonz-mitigate-issue2759_2021-06-17-23-23.json
heft-plugins/heft-webpack4-plugin/package.json
heft-plugins/heft-webpack5-plugin/package.json

Temporary workaround for https://github.com/microsoft/rushstack/issues/2759
Tested on a project that had this problem

[heft] Temporary workaround for #2759

---

apps/rush-lib/assets/rush-init/common/config/rush/command-line.json
apps/rush-lib/src/schemas/command-line.schema.json
common/changes/@microsoft/rush/octogonz-rush-command-line-schema_2021-07-06-19-11.json

The "disableBuildCache" setting could not be specified in **command-line.json** due to a JSON schema issue.
I encountered this problem while upgrading the https://github.com/microsoft/rush-example repo.  I confirmed that this PR fixes the issue.

[rush] Fix problem with command-line.schema.json

---

common/changes/@rushstack/heft-webpack4-plugin/ianc-lazy-load-webpack_2021-07-27-22-11.json
common/changes/@rushstack/heft-webpack5-plugin/ianc-lazy-load-webpack_2021-07-27-22-11.json
common/reviews/api/heft-webpack4-plugin.api.md
common/reviews/api/heft-webpack5-plugin.api.md
heft-plugins/heft-webpack4-plugin/src/WebpackConfigurationLoader.ts
heft-plugins/heft-webpack4-plugin/src/WebpackPlugin.ts
heft-plugins/heft-webpack4-plugin/src/shared.ts
heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts
heft-plugins/heft-webpack5-plugin/src/WebpackPlugin.ts
heft-plugins/heft-webpack5-plugin/src/shared.ts

Change webpack to be lazy-loaded to speed up Heft's boot time.
Building some SPFx packages with Heft and webpack.

[heft+webpack] Lazy-load webpack in the heft plugins.

---

apps/heft/src/cli/actions/HeftActionBase.ts
apps/heft/src/metrics/MetricsCollector.ts
common/changes/@rushstack/heft/benpapp-addErrorToMetricsCollector_2021-09-20-22-50.json
common/reviews/api/heft.api.md

There is currently no information given to the MetricsCollector about whether a given action was a success. This PR sends a boolean through the MetricsData indicating whether errors were encountered during the action
The encounteredErrors boolean is added to MetricsData as part of the properties which can be read by a plugin, and the encounteredErrors bool is passed through from the similarly-named variable in HeftActionBase
Received the new data in a package set up to use the PR branch and was able to see the data reflected in telemetry.

[heft] add encounteredErrors to metrics collector data

---

apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts
apps/rush-lib/src/logic/TaskSelector.ts
common/changes/@microsoft/rush/ianc-rename-an-interface_2021-10-03-07-22.json

Simple refactor, this PR renames an interface to follow convention.

[rush] Rename an interface to follow convention.

---

common/changes/@rushstack/set-webpack-public-path-plugin/clean-up-set-webpack-public-path-plugin_2021-11-11-00-47.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
common/reviews/api/set-webpack-public-path-plugin.api.md
webpack/set-webpack-public-path-plugin/config/api-extractor.json
webpack/set-webpack-public-path-plugin/package.json
webpack/set-webpack-public-path-plugin/src/SetPublicPathPlugin.ts

This is just some cleanup, especially removing the "webpack4" and "webpack5" from the typings.

[set-webpack-public-path-plugin] Some typings cleanup.

---

common/changes/@rushstack/module-minifier-plugin/fix-docs-issue_2021-11-13-00-41.json
webpack/module-minifier-plugin/README.md

This fixes a minor syntax mistake in the README.

[module-minifier-plugin] Fix a minor mistake in docs.

---

common/changes/@rushstack/module-minifier-plugin/export-reserved-words_2021-11-22-21-36.json
common/reviews/api/module-minifier-plugin.api.md
webpack/module-minifier-plugin/src/MinifiedIdentifier.ts
webpack/module-minifier-plugin/src/index.ts

Exports the list of javascript reserved words from the `@rushstack/module-minifier-plugin` package.

[module-minifier-plugin] Export the list of javascript reserved words.

---

rush-plugins/rush-amazon-s3-build-cache-plugin/.npmignore
rush-plugins/rush-azure-storage-build-cache-plugin/.npmignore

After publishing, the `@microsoft/rush@5.57.0-dev.1` test release encountered a failure due to a missing file:
```
rush prettify --mode=fix --staged
Rush Multi-Project Build Tool 5.57.0-dev.1 - https://rushjs.io
Node.js version is 14.17.0 (LTS)
ERROR: Manifest for rush plugin package @rushstack/rush-amazon-s3-build-cache-plugin not found.
Please run 'rush update' first.
```
CC @iclanton @chengcyber

[rush] Add missing exclusions for rush-plugin-manifest.json

---

apps/rush-lib/assets/rush-init/common/config/rush/rush-plugins.json
apps/rush-lib/src/schemas/rush-plugin-manifest.schema.json
common/changes/@microsoft/rush/chore-rush-plugin-schema_2021-12-01-05-41.json
rush-plugins/rush-amazon-s3-build-cache-plugin/rush-plugin-manifest.json
rush-plugins/rush-azure-storage-build-cache-plugin/rush-plugin-manifest.json

Set `$schema` property in Rush plugin related json files
https://developer.microsoft.com/json-schemas/rush/v5/rush-plugins.schema.json
https://developer.microsoft.com/json-schemas/rush/v5/rush-plugin-manifest.schema.json
Local

[rush] rush plugin schema

---

apps/rush-lib/package.json
common/changes/@microsoft/rush/put-publishOnlyDependencies-back_2021-12-03-02-31.json
common/config/azure-pipelines/npm-publish-rush.yaml
common/config/azure-pipelines/templates/publish.yaml

Update the `rush-lib` `package.json` immediately before `rush publish` runs instead of before `rush version` runs.

Fix an issue with the Rush publish pipeline.

---

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
rush.json

It's out! 🥳
We'll announce it at Rush Hour today.

Upgrade to Rush 5.57.0

---

apps/rush-lib/package.json
common/changes/@microsoft/rush/update-z-schema_2021-12-09-20-10.json
common/changes/@rushstack/node-core-library/update-z-schema_2021-12-09-20-10.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
libraries/node-core-library/package.json
libraries/node-core-library/src/test/JsonSchema.test.ts
libraries/node-core-library/src/test/__snapshots__/JsonSchema.test.ts.snap

Addresses https://github.com/microsoft/rushstack/issues/3018.
Built the repo. All tests pass and all scenarios work.

Update `z-schema` to 5.0.2.

---

apps/rush/CHANGELOG.json
apps/rush/CHANGELOG.md

During the review of PR #2968 the CLI design was changed, but we forgot to update the changelog entry.
@dmichon-msft

[rush] Fix incorrect changelog

---

apps/rush-lib/src/api/RushProjectConfiguration.ts
common/changes/@microsoft/rush/update-error-mesage-wording_2022-01-19-03-45.json

Tweaks to error messages that I missed from https://github.com/microsoft/rushstack/pull/3168.

[rush] Minor tweaks to error message wording.

---

apps/rush-lib/src/api/RushProjectConfiguration.ts
apps/rush/README.md
common/changes/@microsoft/rush/upgrading-links_2022-01-20-01-28.json

Addresses the points in https://github.com/microsoft/rushstack/issues/3172#issue-1108491748
Companion to https://github.com/microsoft/rushjs.io-website/pull/119

[rush] Include links to UPGRADING.md

---

apps/api-documenter/src/documenters/YamlDocumenter.ts
apps/api-documenter/src/utils/ToSdpConvertHelper.ts
build-tests/api-documenter-test/etc/yaml/api-documenter-test.yml
build-tests/api-documenter-test/etc/yaml/api-documenter-test/exampleduplicatetypealias.yml
build-tests/api-documenter-test/etc/yaml/api-documenter-test/exampletypealias.yml
build-tests/api-documenter-test/etc/yaml/api-documenter-test/exampleuniontypealias.yml
build-tests/api-documenter-test/etc/yaml/api-documenter-test/generictypealias.yml
build-tests/api-documenter-test/etc/yaml/api-documenter-test/typealias.yml
build-tests/api-documenter-test/etc/yaml/toc.yml
common/changes/@microsoft/api-documenter/AlexJ-TypeTest2_2022-01-12-19-47.json

This change makes the YamlDocumenter output type alias documentation that aligns with the DocFX yaml schema. [Here's a sample of the yaml accepted by the schema](https://github.com/MicrosoftDocs/azure-docs-sdk-node/blob/main/docs-ref-autogen/@azure/ai-text-analytics/StringIndexType.yml). [Here's a sample of docs built from this change (internal MSFT staging site)](https://review.docs.microsoft.com/en-us/javascript/api/excel?branch=AlexJ-RSTest&view=excel-js-preview#typeAliases).
Fixes #2567. 
I'm unclear why this was not initially supported by api-documenter. If there are other endpoints relying on type aliases not being generated, then this change could pose problems.
The changes were tested with the Office JavaScript APIs. Here's the …

[api-documenter] Add Yaml Documenter support for type aliases

---

apps/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
apps/rush-lib/src/utilities/TarExecutable.ts
common/changes/@microsoft/rush/fix-issue-with-git-bash-tar_2022-01-21-01-34.json

Fixes https://github.com/microsoft/rushstack/issues/3158
Tested on Git Bash.

[rush] Fix an issue where the TAR exectuable on the Git Bash PATH does not handle Windows paths correctly.

---

apps/rush-lib/package.json
build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
common/changes/@microsoft/rush/bugfix-CVE-2022-0235_2022-01-26-11-55.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
rush-plugins/rush-amazon-s3-build-cache-plugin/package.json

Address [CVE 2022-0235](https://www.whitesourcesoftware.com/vulnerability-database/CVE-2022-0235), by updating node-fetch version to 2.6.7
Rebuild

updating node-fetch to 2.6.7

---

apps/rush-lib/package.json
common/changes/@microsoft/rush/user-apc-bump-tar_2022-02-01-01-06.json
common/config/rush/pnpm-lock.yaml

Bumping tab to 5.0.10, as a minimum version used for rush-lib to bring in a security fix. 
Bumping tab to 5.0.10, as a minimum version used for rush-lib to bring in a security fix.
Build

[rush] Bump tar to 5.0.10

---

apps/rush-lib/src/cli/actions/AddAction.ts
apps/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap
common/changes/@microsoft/rush/typo-rush-add_2022-02-19-12-52.json
common/changes/@rushstack/ts-command-line/typo-rush-add_2022-02-19-12-52.json
libraries/ts-command-line/src/test/TabCompleteAction.test.ts

fix typo "rush upgrade" -> "rush update" in rush add command description

[rush-lib] fix typo "rush upgrade" -> "rush update"

---

apps/rush-lib/src/logic/base/BasePackage.ts
common/changes/@microsoft/rush/master_2022-03-07-17-19.json

Allow installation of aliased packages by using installedName. Fixes #2331
When installing aliased packages rush would exit with `ERROR: Child already exists`
When using the correct name attribute for adding packages everything works as expected.
Local Repo which errored before is now installable.

[rush-lib] Allow installation of aliased packages by using installedName

---

common/changes/@rushstack/eslint-config/fix-packagejson-path_2022-03-15-18-29.json
common/changes/@rushstack/eslint-patch/fix-packagejson-path_2022-03-15-18-29.json
common/changes/@rushstack/eslint-plugin-packlets/fix-packagejson-path_2022-03-15-18-29.json
common/changes/@rushstack/eslint-plugin-security/fix-packagejson-path_2022-03-15-18-29.json
common/changes/@rushstack/eslint-plugin/fix-packagejson-path_2022-03-15-18-29.json
eslint/eslint-config/package.json
eslint/eslint-patch/package.json
eslint/eslint-plugin-packlets/package.json
eslint/eslint-plugin-security/package.json
eslint/eslint-plugin/package.json

Fixes https://github.com/microsoft/rushstack/issues/3273

Fix directory fields in package.json

---

apps/rush-lib/README.md
common/changes/@microsoft/rush/patch-1_2022-03-16-08-35.json

Fixes broken links for the rush-lib documentation and api reference.

[rush-lib]: update readme, fix broken links

---

apps/rush-lib/src/logic/ChangeFiles.ts
common/changes/@microsoft/rush/typoChangeV_2022-04-03-10-07.json

[rush] Fix a typo in output of `rush change -v`

---

apps/api-documenter/src/documenters/OfficeYamlDocumenter.ts
build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
common/changes/@microsoft/api-documenter/AlexJ-OfficeDocumenterReqSetLinks_2022-03-25-20-33.json

The Office.js requirement set URLs are changing. Rather than having the links created by this tool hit the redirects, we want to generate the actual URLs.

[api-documenter] Change requirement set links for OfficeYamlDocumenter

---

apps/api-extractor/src/api/Extractor.ts
apps/api-extractor/src/api/ExtractorConfig.ts
apps/api-extractor/src/api/IConfigFile.ts
apps/api-extractor/src/generators/DtsRollupGenerator.ts
apps/api-extractor/src/schemas/api-extractor-defaults.json
apps/api-extractor/src/schemas/api-extractor-template.json
apps/api-extractor/src/schemas/api-extractor.schema.json
build-tests/api-extractor-scenarios/src/functionOverload/config/api-extractor-overrides.json
build-tests/api-extractor-test-01/config/api-extractor.json
build-tests/api-extractor-test-02/config/api-extractor.json
build-tests/api-extractor-test-04/config/api-extractor.json
build-tests/heft-node-everything-test/config/api-extractor.json
common/changes/@microsoft/api-extractor/api-extractor-alpha_2022-04-12-20-34.json
common/reviews/api/api-extractor.api.md

Addresses https://github.com/microsoft/rushstack/issues/3295.
Added this option to the test projects.

[api-extractor] Add support for an alphaTrimmedFilePath.

---

common/changes/@microsoft/rush/remove-xstitch_2022-05-06-20-19.json
common/reviews/api/rush-lib.api.md
libraries/rush-lib/src/api/CommonVersionsConfiguration.ts
libraries/rush-lib/src/api/test/CommonVersionsConfiguration.test.ts
libraries/rush-lib/src/api/test/jsonFiles/common-versions.json
libraries/rush-lib/src/logic/versionMismatch/VersionMismatchFinder.ts
libraries/rush-lib/src/logic/versionMismatch/VersionMismatchFinderCommonVersions.ts
libraries/rush-lib/src/schemas/common-versions.schema.json

This property was added to support another tool that never ended up being finished and has since been tombstoned.

[rush] Remove xstitchPreferredVersions.

---

common/changes/@microsoft/rush/tags-in-git-list_2022-05-09-18-50.json
libraries/rush-lib/src/cli/actions/ListAction.ts
libraries/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap

Fixes https://github.com/microsoft/rushstack/issues/3399.
Tested in two repos (one that has tags, and one that doesn't).

[rush] Include tags in the 'rush list' output.

---

common/changes/@microsoft/rush/better-undefined-handling_2022-05-09-23-06.json
libraries/rush-lib/src/cli/actions/ListAction.ts

Addresses an issue identified here: https://github.com/microsoft/rushstack/issues/3399#issuecomment-1121570195

[rush] Handle undefined values in 'rush list'.

---

README.md

Fixes broken link in README to "API reference"

Fixed API reference link

---

build-tests/localization-plugin-test-03/src/indexB.ts
build-tests/localization-plugin-test-03/src/strings7.resjson
build-tests/localization-plugin-test-03/webpack.config.js
common/changes/@rushstack/localization-plugin/resjson_2022-05-23-22-47.json
webpack/localization-plugin/README.md
webpack/localization-plugin/src/LocFileTypingsGenerator.ts
webpack/localization-plugin/src/WebpackConfigurationUpdater.ts
webpack/localization-plugin/src/interfaces.ts
webpack/localization-plugin/src/utilities/Constants.ts
webpack/localization-plugin/src/utilities/LocFileParser.ts

This PR adds support for `.resjson` to the loc plugin and adds a test case.

[localization plugin] Add support for .resjson files

---

common/changes/@rushstack/heft-webpack4-plugin/selarkin-issue-3463_2022-06-13-19-32.json
heft-plugins/heft-webpack4-plugin/package.json

add peer dependency for webpack 4 types

---

common/changes/@rushstack/eslint-patch/patch-1_2022-06-27-22-55.json
eslint/eslint-patch/README.md

Updates the eslint-patch README to note that ESLint version 8 is supported.
Also fixes an error in the URL for the CHANGELOG.
The CHANGELOG for this package indicates it supports ESLint 8. However, the README didn't mention this.
Doc-only change.

[doc] update eslint-patch README with v8 support

---

common/reviews/api/api-extractor-model.api.md
libraries/api-extractor-model/src/mixins/IFindApiItemsResult.ts

We still have some [open discussion](https://github.com/microsoft/rushstack/pull/3469/files#diff-f0516a1941ffe40f35eb325cb731d6d3af1663276d61824a4a6da636d91d278e) about this API.

Mark FindApiItemsMessageId as "@beta"

---

common/changes/@microsoft/rush/octogonz-rush-add-help_2022-08-12-02-00.json
libraries/rush-lib/src/cli/actions/AddAction.ts
libraries/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap

This addresses the issue originally reported via https://github.com/microsoft/rushjs.io-website/pull/120

[rush] Small correction for "rush add" CLI help

---

common/changes/@microsoft/rush/octogonz-rush-doc-updates_2022-08-22-19-10.json
libraries/rush-lib/assets/rush-init/common/config/rush/artifactory.json
libraries/rush-lib/assets/rush-init/common/config/rush/build-cache.json
libraries/rush-lib/assets/rush-init/common/config/rush/rush-plugins.json
libraries/rush-lib/assets/rush-init/rush.json
libraries/rush-lib/assets/website-only/rush-plugin-manifest.json
libraries/rush-lib/assets/website-only/rush-project.json
libraries/rush-lib/src/api/EnvironmentConfiguration.ts
libraries/rush-lib/src/schemas/rush-project.schema.json

Some minor improvements, as part of https://github.com/microsoft/rushstack-websites/pull/91

[rush-lib] Update config file documentation

---

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
common/changes/@microsoft/rush/feat-changelog-validate_2022-08-26-06-42.json
common/changes/@microsoft/rush/octogonz-fix-rush-example_2022-08-11-20-55.json
common/changes/@microsoft/rush/octogonz-rush-doc-updates_2022-08-22-19-10.json
common/changes/@microsoft/rush/octogonz-rush-trivia_2022-08-29-20-24.json
common/changes/@microsoft/rush/watch-perf_2022-08-12-22-50.json
common/reviews/api/rush-lib.api.md
libraries/rush-lib/src/api/CommandLineConfiguration.ts
libraries/rush-lib/src/api/CommandLineJson.ts
libraries/rush-lib/src/api/RushConfigurationProject.ts
libraries/rush-lib/src/cli/RushCommandLineParser.ts
libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
libraries/rush-lib/src/logic/ProjectWatcher.ts
libraries/rush-lib/src/logic/Telemetry.ts
libraries/rush-lib/src/logic/test/Telemetry.test.ts
libraries/rush-lib/src/schemas/command-line.schema.json

Some miscellaneous cleanups
CC @dmichon-msft @hanksterhan

Prepare to publish Rush 5.77.0

---

common/changes/@microsoft/rush/remove-git-example-gender_2022-09-25-13-46.json
libraries/rush-lib/assets/rush-init/rush.json
libraries/rush-lib/src/logic/policy/GitEmailPolicy.ts
rush.json

Removes an unnecessary use of the male gender (and of a male-gendered honorific) in the git config example.
Solved the problem by changing the example to a gender neutral `"Example Name <name@example.com>"`
Manual testing.
Set my local git config to something that did not match the regex in rush.json (with `git config --local user.email "does-not-match@foo.com"`) and then ran `rush install` to see that the new message was correct.

[rush-lib] remove gender from git config example

---

apps/api-extractor/package.json
apps/heft/package.json
build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
common/changes/@microsoft/api-extractor-model/bump-cyclics_2022-10-03-23-27.json
common/changes/@microsoft/api-extractor/bump-cyclics_2022-10-03-23-27.json
common/changes/@rushstack/eslint-patch/bump-cyclics_2022-10-03-23-27.json
common/changes/@rushstack/eslint-plugin-packlets/bump-cyclics_2022-10-03-23-27.json
common/changes/@rushstack/eslint-plugin-security/bump-cyclics_2022-10-03-23-27.json
common/changes/@rushstack/eslint-plugin/bump-cyclics_2022-10-03-23-27.json
common/changes/@rushstack/heft-config-file/bump-cyclics_2022-10-03-23-27.json
common/changes/@rushstack/heft/bump-cyclics_2022-10-03-23-27.json
common/changes/@rushstack/node-core-library/bump-cyclics_2022-10-03-23-27.json
common/changes/@rushstack/rig-package/bump-cyclics_2022-10-03-23-27.json
common/changes/@rushstack/tree-pattern/bump-cyclics_2022-10-03-23-27.json
common/changes/@rushstack/ts-command-line/bump-cyclics_2022-10-03-23-27.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
eslint/eslint-patch/package.json
eslint/eslint-plugin-packlets/package.json
eslint/eslint-plugin-security/package.json
eslint/eslint-plugin/package.json
libraries/api-extractor-model/package.json
libraries/heft-config-file/package.json
libraries/node-core-library/package.json
libraries/rig-package/package.json
libraries/tree-pattern/package.json
libraries/ts-command-line/package.json
rush.json

Upgrade cyclic dependencies
Upgrade cyclic dependencies for the rushstack repository
Full test run

Bump cyclics

---

common/changes/@rushstack/eslint-plugin-packlets/patch-2_2022-10-08-22-39.json
eslint/eslint-plugin-packlets/README.md

The README file for eslint-plugin-packlets has a broken link to a CHANGELOG file. This PR fixes it.
See changes.
I click the link, now it’s working.

[eslint-plugin-packlets] Fix broken link in README file

---

apps/api-extractor/src/generators/DeclarationReferenceGenerator.ts
build-tests/api-extractor-scenarios/etc/referenceTokens/api-extractor-scenarios.api.json
build-tests/api-extractor-scenarios/etc/referenceTokens/api-extractor-scenarios.api.md
build-tests/api-extractor-scenarios/etc/referenceTokens/rollup.d.ts
build-tests/api-extractor-scenarios/src/referenceTokens/index.ts
common/changes/@microsoft/api-extractor/3629-fix_2022-09-14-19-34.json

Fixes #3629
The code that checks whether a node is in an expression context was incomplete, an expression also appears inside object's computed property. 
Tested manually, against an example repository described in #3629 , the issue is solved with the changes in this PR.

[api-extractor] fix references from computed properties

---

apps/api-documenter/package.json
apps/api-extractor/package.json
common/changes/@microsoft/api-documenter/issue-3710_2022-10-19-22-21.json
common/changes/@microsoft/api-extractor-model/issue-3710_2022-10-19-22-21.json
common/changes/@microsoft/api-extractor/issue-3710_2022-10-19-22-21.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
libraries/api-extractor-model/package.json
repo-scripts/doc-plugin-rush-stack/package.json

[api-extractor] Bump @microsoft/tsdoc dependency version

---

common/changes/@microsoft/rush/octogonz-rush-init-fix_2022-11-08-03-24.json
libraries/rush-lib/assets/rush-init/common/config/rush/pnpm-config.json
libraries/rush-lib/src/cli/actions/InitAction.ts

I encountered this problem while upgrading the https://github.com/microsoft/rush-example repo.
Rush 5.79.0 introduced a new config file **pnpm-config.json**, however the `rush init` command does not create this config file because it was not added to the template list.
Tested locally to confirm the issue is fixed.

[rush] Fix a regression where "rush init" did not create pnpm-config.json

---

common/changes/@microsoft/rush/feat-supportMoreParameterKindInPlugin_2022-11-07-11-35.json
libraries/rush-lib/src/api/CommandLineConfiguration.ts
libraries/rush-lib/src/api/CommandLineJson.ts
libraries/rush-lib/src/cli/scriptActions/BaseScriptAction.ts
libraries/rush-lib/src/cli/test/RushPluginCommandLineParameters.test.ts
libraries/rush-lib/src/cli/test/pluginCommandLineParametersRepo/common/autoinstallers/plugins/package.json
libraries/rush-lib/src/cli/test/pluginCommandLineParametersRepo/common/autoinstallers/plugins/rush-plugins/rush-command-parameters-plugin/rush-command-parameters-plugin/command-line.json
libraries/rush-lib/src/cli/test/pluginCommandLineParametersRepo/common/autoinstallers/plugins/rush-plugins/rush-command-parameters-plugin/rush-plugin-manifest.json
libraries/rush-lib/src/cli/test/pluginCommandLineParametersRepo/common/config/rush/rush-plugins.json
libraries/rush-lib/src/cli/test/pluginCommandLineParametersRepo/rush-command-parameters-plugin/index.js
libraries/rush-lib/src/cli/test/pluginCommandLineParametersRepo/rush-command-parameters-plugin/package.json
libraries/rush-lib/src/cli/test/pluginCommandLineParametersRepo/rush-command-parameters-plugin/rush-plugin-manifest.json
libraries/rush-lib/src/cli/test/pluginCommandLineParametersRepo/rush.json
libraries/rush-lib/src/schemas/command-line.schema.json

Support more parameterKind in rush plugin's `command-line.json`, which are already implemented in '@rushstack/ts-command-line'
Support using these "parameterKind" (***integer*** / ***integerList*** / ***stringList*** / ***choiceList***) in plugin's `command-line.json`
Added one unit test for new "parameterKind"

[@microsoft/rush-lib] feat: support more parameterKind in rush plugin

---

common/changes/@microsoft/rush/chore-add_usage_example_for_new_parameterKind_2022-11-11-10-00.json
common/config/rush/version-policies.json
libraries/rush-lib/assets/rush-init/common/config/rush/command-line.json

Add usage example  for newly added "parameterKind" in rush init template
Add integer, integer list, string list, choice list usage examples in rush init template
Don't need to be tested.

chore: add usage example of new parameterKind in "command-line.json"

---

common/changes/@microsoft/rush/cleanup_2022-11-22-22-43.json
common/reviews/api/rush-lib.api.md
libraries/rush-lib/src/api/LastInstallFlag.ts
libraries/rush-lib/src/index.ts

Minor cleanup from https://github.com/microsoft/rushstack/pull/3778

[rush] Minor cleanup related to PR #3778

---

common/changes/@microsoft/rush/cache-metadata_2022-11-23-22-58.json
common/changes/@microsoft/rush/cache-metadata_2022-11-23-23-00.json
common/changes/@microsoft/rush/cache-metadata_2022-11-23-23-16.json
common/reviews/api/rush-azure-storage-build-cache-plugin.api.md
common/reviews/api/rush-lib.api.md
libraries/rush-lib/src/logic/CredentialCache.ts
libraries/rush-lib/src/logic/test/CredentialCache.test.ts
libraries/rush-lib/src/schemas/credentials.schema.json
rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3BuildCacheProvider.ts
rush-plugins/rush-amazon-s3-build-cache-plugin/src/test/__snapshots__/AmazonS3BuildCacheProvider.test.ts.snap
rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureAuthenticationBase.ts
rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureStorageBuildCacheProvider.ts
rush-plugins/rush-azure-storage-build-cache-plugin/src/test/__snapshots__/AzureStorageBuildCacheProvider.test.ts.snap

Adds a metadata field to credentials.
This is a breaking API change, but this API is likely not used by partners yet.

[rush] Add a credentialMetadata field.

---

common/changes/@microsoft/rush/feat-report-telemetry-data-for-GlobalScriptAction_2022-12-02-04-40.json
libraries/rush-lib/src/cli/scriptActions/GlobalScriptAction.ts

Add telemetry logout for global script actions

[rush] add telemetry logout for global script actions

---

common/changes/@microsoft/rush/clean-up-imports_2022-12-08-07-34.json
common/reviews/api/rush-lib.api.md
libraries/rush-lib/src/api/ChangeFile.ts
libraries/rush-lib/src/api/Rush.ts
libraries/rush-lib/src/api/RushProjectConfiguration.ts
libraries/rush-lib/src/logic/DependencySpecifier.ts
libraries/rush-lib/src/logic/Git.ts
libraries/rush-lib/src/logic/deploy/DeployArchiver.ts
libraries/rush-lib/src/logic/npm/NpmLinkManager.ts
libraries/rush-lib/src/logic/npm/NpmPackage.ts
libraries/rush-lib/src/logic/pnpm/IPnpmfile.ts
libraries/rush-lib/src/logic/pnpm/PnpmLinkManager.ts
libraries/rush-lib/src/logic/pnpm/PnpmfileShim.ts
libraries/rush-lib/src/pluginFramework/PluginManager.ts

Clean up some imports and file references.
`rush install`. This tests `pnpmfileShim` and the loading of dependencies.

[rush] Clean up some imports and file references.

---

common/changes/@rushstack/node-core-library/import-improvements_2022-12-09-01-38.json
common/changes/@rushstack/node-core-library/import-improvements_2022-12-09-01-39.json
libraries/node-core-library/src/Import.ts
libraries/node-core-library/src/test/Import.test.ts
libraries/node-core-library/src/test/__snapshots__/Import.test.ts.snap

Addresses the feedback in this comment: https://github.com/microsoft/rushstack/pull/2095/files#r478033549

[node-core-library] Improve performance of Import.resovlePackage.

---

apps/trace-import/README.md
apps/trace-import/src/TraceImportCommandLineParser.ts
apps/trace-import/src/traceImport.ts
common/changes/@rushstack/trace-import/octogonz-trace-import-fixes_2022-12-10-01-37.json
common/changes/@rushstack/trace-import/octogonz-trace-import-fixes_2022-12-10-01-38.json

- Fix relative file resolution
- Rename CLI parameter `-r` to `-t`
- Update docs
Tested manually

[trace-import] Rename CLI parameter, fix some minor issues

---

common/changes/@microsoft/rush/update-jszip_2023-01-18-19-27.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
libraries/rush-lib/package.json

Fixes https://github.com/microsoft/rushstack/issues/3899

[rush] Update JSZip to 3.8.0.

---

common/changes/@microsoft/rush/fix-create-scripts_2023-01-18-19-47.json
libraries/rush-lib/src/logic/deploy/DeployManager.ts
libraries/rush-lib/src/utilities/PathConstants.ts
libraries/rush-lib/webpack.config.js

Fixes https://github.com/microsoft/rushstack/issues/3889

[rush] Fix missing create-scripts.js file.

---

apps/lockfile-explorer-web/src/components/ConnectionModal/index.tsx
apps/lockfile-explorer/package.json
apps/lockfile-explorer/src/init.ts
apps/lockfile-explorer/src/start.ts
common/changes/@microsoft/rush/octogonz-lfx-polish_2023-01-21-01-15.json
common/changes/@rushstack/lockfile-explorer/octogonz-lfx-polish_2023-01-21-01-02.json
common/changes/@rushstack/lockfile-explorer/octogonz-lfx-polish_2023-01-21-01-03.json
libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts

This is some minor polish in preparation for the Lockfile Explorer 1.0 release.
Tested locally.
I'm working on the documentation website separately.
@william2958

[lockfile-explorer] Add "lfx" command alias and improve some messages

---

apps/lockfile-explorer-web/src/containers/PackageJsonViewer/index.tsx
apps/lockfile-explorer-web/src/containers/SelectedEntryPreview/styles.scss
common/reviews/api/rush-themed-ui.api.md
libraries/rush-themed-ui/src/components/Button/styles.scss
libraries/rush-themed-ui/src/components/Tabs/index.tsx

Tweaks for some lfx styles & fixed tab component
Tested manually

feat: tweak styles of lockfile explorer

---

apps/lockfile-explorer-web/src/containers/LockfileViewer/index.tsx
apps/lockfile-explorer-web/src/containers/PackageJsonViewer/index.tsx
apps/lockfile-explorer-web/src/containers/PackageJsonViewer/styles.scss
apps/lockfile-explorer-web/src/parsing/LockfileEntry.ts
apps/lockfile-explorer-web/src/parsing/readLockfile.ts
apps/lockfile-explorer-web/src/parsing/test/compareSpec.test.ts
apps/lockfile-explorer-web/src/types/IPackageJson.ts

This PR includes a few tweaks for the v1.0 release of the Lockfile Explorer:
- Display versions for projects
- Display the full project path if there are duplicate folder names in the monorepo

[Lockfile Explorer] tweaks for v1 release

---

apps/lockfile-explorer-web/src/containers/LogoPanel/index.tsx
apps/lockfile-explorer/README.md
apps/lockfile-explorer/src/start.ts
common/changes/@rushstack/lockfile-explorer/octogonz-lfx-1.0_2023-01-25-02-17.json

Bump the version to 1.0 and update README.md

[lockfile-explorer] 1.0 release

---

apps/lockfile-explorer-web/src/containers/LockfileEntryDetailsView/styles.scss
apps/lockfile-explorer-web/src/containers/PackageJsonViewer/styles.scss
apps/lockfile-explorer-web/src/containers/SelectedEntryPreview/styles.scss

This PR refactors the CSS layout of the center column of the Lockfile Explorer to be more responsive, and better display the information. The changes are:
The top panel in the center column (Selected entry details) is now dynamic and will take up as much space as needed by the content
The package json panel will take up 1/2 of the available height after other fixed height panels are added (with a minimum of 400px)
The Dependencies and Influencers panel will take up the remaining 1/2 of the available height (with a minimum of 400px)
Dependency inspector and Peer information both take up as much height as necessary as the content requires.
If the center column requires more height than is available by 100vh, it will simply become scrollable.
Tested Manually

[Lockfile Explorer] Re-write center column to be more responsive

---

apps/api-extractor/package.json
apps/heft/package.json
build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
common/changes/@microsoft/api-extractor-model/octogonz-bump-decoupled_2023-01-28-02-57.json
common/changes/@microsoft/api-extractor/octogonz-bump-decoupled_2023-01-28-02-57.json
common/changes/@microsoft/webpack5-load-themed-styles-loader/octogonz-bump-decoupled_2023-01-28-02-57.json
common/changes/@rushstack/eslint-patch/octogonz-bump-decoupled_2023-01-28-02-57.json
common/changes/@rushstack/eslint-plugin-packlets/octogonz-bump-decoupled_2023-01-28-02-57.json
common/changes/@rushstack/eslint-plugin-security/octogonz-bump-decoupled_2023-01-28-02-57.json
common/changes/@rushstack/eslint-plugin/octogonz-bump-decoupled_2023-01-28-02-57.json
common/changes/@rushstack/heft-config-file/octogonz-bump-decoupled_2023-01-28-02-57.json
common/changes/@rushstack/heft/octogonz-bump-decoupled_2023-01-28-02-57.json
common/changes/@rushstack/node-core-library/octogonz-bump-decoupled_2023-01-28-02-57.json
common/changes/@rushstack/rig-package/octogonz-bump-decoupled_2023-01-28-02-57.json
common/changes/@rushstack/tree-pattern/octogonz-bump-decoupled_2023-01-28-02-57.json
common/changes/@rushstack/ts-command-line/octogonz-bump-decoupled_2023-01-28-02-57.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
eslint/eslint-patch/package.json
eslint/eslint-plugin-packlets/package.json
eslint/eslint-plugin-security/package.json
eslint/eslint-plugin/package.json
libraries/api-extractor-model/package.json
libraries/heft-config-file/package.json
libraries/node-core-library/package.json
libraries/rig-package/package.json
libraries/tree-pattern/package.json
libraries/ts-command-line/package.json
webpack/webpack5-load-themed-styles-loader/package.json
webpack/webpack5-load-themed-styles-loader/src/test/LoadThemedStylesLoader.test.ts

(Formerly called "cyclic dependencies")

Bump decoupled dependencies

---

common/changes/@rushstack/eslint-config/patch-1_2023-02-09-19-45.json
eslint/eslint-config/profile/_common.js

This rule has been deprecated in favor of the equivalent, better named parameter-properties rule. as per https://typescript-eslint.io/rules/no-parameter-properties/
no-parameter-properties
Disallow the use of parameter properties in class constructors.
DEPRECATED
This rule has been deprecated in favour of the equivalent, better named [parameter-properties](https://typescript-eslint.io/rules/parameter-properties) rule.
Parameter properties can be confusing to those new to TypeScript as they are less explicit than other ways of declaring and initializing class members.
fix: #3956 [eslint-config] Rule @typescript-eslint/no-parameter-properties is deprecated in favour of the equivalent, parameter-properties

[eslint-config] Update deprecated rule.

---

common/changes/@rushstack/heft-webpack5-plugin/users-chhol-heft-webpack-check-for-valid-files-types_2023-03-08-18-11.json
heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts

fixes #3988
This PR adds a function to gather any valid webpack config file (.js, .mjs, .cjs) rather than using the hardcoded values. I considered integrating this with existing methods but wasn't sure if that would be preferred.
I have not tested it yet, opening this draft to figure out the best method of ensuring this works without introducing breaking changes.

[heft-webpack5-plugin]update WebpackConfigurationLoader to support any valid webpack config file name

---

common/changes/@microsoft/rush/fix-upstream-phase_2022-11-16-08-22.json
common/reviews/api/rush-lib.api.md
libraries/rush-lib/src/api/CommandLineConfiguration.ts
libraries/rush-lib/src/cli/RushCommandLineParser.ts
libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
libraries/rush-lib/src/logic/operations/PhasedOperationPlugin.ts
libraries/rush-lib/src/logic/operations/test/PhasedOperationPlugin.test.ts
libraries/rush-lib/src/logic/operations/test/ShellOperationRunnerPlugin.test.ts
libraries/rush-lib/src/pluginFramework/PhasedCommandHooks.ts

Fixes #3753 
I will add originalPhase property to know original phase.
The property name may have better one.
Use https://github.com/microsoft/rushstack/issues/3753 repro steps

[rush-lib] Fix phase command to respect upstream

---

common/changes/@microsoft/rush/more-explicit-rush-sdk-filtering_2023-03-30-19-36.json
libraries/rush-sdk/.npmignore

Follow-up to https://github.com/microsoft/rushstack/pull/4038

[rush] Explicitly filter out generate-stubs.

---

.github/workflows/file-doc-tickets.yml

Use the new RUSHSTACK_WEBSITES_PR_TOKEN secret.

---

common/changes/@microsoft/rush/fix-rush-serve-version_2023-04-27-16-52.json
rush-plugins/rush-http-build-cache-plugin/package.json
rush-plugins/rush-serve-plugin/package.json

Fix the versions of rush-serve-plugin and rush-http-build-cache-plugin.

---

common/changes/@rushstack/node-core-library/escapeRegexp_2023-04-29-10-49.json
common/changes/@rushstack/package-extractor/escapeRegexp_2023-04-29-10-49.json
common/changes/@rushstack/set-webpack-public-path-plugin/escapeRegexp_2023-04-29-10-49.json
common/changes/@rushstack/webpack4-localization-plugin/escapeRegexp_2023-04-29-10-49.json
common/config/rush/pnpm-lock.yaml
common/reviews/api/node-core-library.api.md
libraries/node-core-library/src/Terminal/PrefixProxyTerminalProvider.ts
libraries/node-core-library/src/Text.ts
libraries/node-core-library/src/test/Text.test.ts
libraries/package-extractor/src/Utils.ts
webpack/set-webpack-public-path-plugin/package.json
webpack/set-webpack-public-path-plugin/src/SetPublicPathPlugin.ts
webpack/webpack4-localization-plugin/package.json
webpack/webpack4-localization-plugin/src/AssetProcessor.ts
webpack/webpack4-localization-plugin/src/WebpackConfigurationUpdater.ts
webpack/webpack4-localization-plugin/src/utilities/Constants.ts

Expose a `Text.escapeRegExp` function to escape regexp special characters.
Included a unit test.
None.

[node-core-library] Expose a Text.escapeRegExp function to escape regexp special characters.

---

common/changes/@microsoft/rush/rename-experiment_2023-05-02-11-01.json
common/reviews/api/rush-lib.api.md
libraries/rush-lib/assets/rush-init/common/config/rush/experiments.json
libraries/rush-lib/src/api/ExperimentsConfiguration.ts
libraries/rush-lib/src/logic/policy/EnvironmentPolicy.ts
libraries/rush-lib/src/schemas/experiments.schema.json

Follow-up to https://github.com/microsoft/rushstack/pull/4093

[rush] Rename the forbidPhantomResolvableNodeModuleFolders experiment to forbidPhantomResolvableNodeModulesFolders.

---

common/changes/@microsoft/rush/bundle-create-links-script_2023-04-30-13-18.json
common/changes/@rushstack/package-extractor/bundle-create-links-script_2023-04-30-13-18.json
common/config/rush/pnpm-lock.yaml
libraries/package-extractor/config/heft.json
libraries/package-extractor/config/typescript.json
libraries/package-extractor/package.json
libraries/package-extractor/src/PathConstants.ts
libraries/package-extractor/webpack.config.js
libraries/rush-lib/src/cli/actions/DeployAction.ts

This is a follow-up to https://github.com/microsoft/rushstack/pull/4064.
This needs some more testing.

[package-exractor] Bundle the create-links script to ensure any imports that are added in the future don't cause issues.

---

apps/api-extractor/package.json
apps/heft/package.json
build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
common/changes/@microsoft/api-extractor-model/bump-cyclics_2023-05-22-06-43.json
common/changes/@microsoft/api-extractor/bump-cyclics_2023-05-22-06-43.json
common/changes/@rushstack/eslint-patch/bump-cyclics_2023-05-22-06-43.json
common/changes/@rushstack/eslint-plugin-packlets/bump-cyclics_2023-05-22-06-43.json
common/changes/@rushstack/eslint-plugin-security/bump-cyclics_2023-05-22-06-43.json
common/changes/@rushstack/eslint-plugin/bump-cyclics_2023-05-22-06-43.json
common/changes/@rushstack/heft-config-file/bump-cyclics_2023-05-22-06-43.json
common/changes/@rushstack/heft/bump-cyclics_2023-05-22-06-43.json
common/changes/@rushstack/node-core-library/bump-cyclics_2023-05-22-06-43.json
common/changes/@rushstack/rig-package/bump-cyclics_2023-05-22-06-43.json
common/changes/@rushstack/tree-pattern/bump-cyclics_2023-05-22-06-43.json
common/changes/@rushstack/ts-command-line/bump-cyclics_2023-05-22-06-43.json
common/config/rush/pnpm-config.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
eslint/eslint-patch/package.json
eslint/eslint-plugin-packlets/package.json
eslint/eslint-plugin-security/package.json
eslint/eslint-plugin/package.json
libraries/api-extractor-model/package.json
libraries/heft-config-file/package.json
libraries/node-core-library/package.json
libraries/rig-package/package.json
libraries/tree-pattern/package.json
libraries/ts-command-line/package.json

Follow-up to https://github.com/microsoft/rushstack/pull/4103

Bump cyclics.

---

common/changes/@microsoft/rush/feat-log-for-build-cache_2023-05-23-11-22.json
libraries/rush-lib/src/logic/operations/OperationMetadataManager.ts
libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts

Fixes https://github.com/microsoft/rushstack/issues/4102 https://github.com/microsoft/rushstack/issues/4117
Use a separate terminal for logging cache subsystem. Log for build cache only displayed in terminal instead of appending to all.log
terminal: 
log file:
Tested in a local monorepo.

Feat log for build cache

---

common/changes/@rushstack/heft-lint-plugin/octogonz-heft-lint-plugin-fix_2023-06-05-20-17.json
heft-plugins/heft-lint-plugin/src/Eslint.ts

Heft 0.51.0 prints this error when invoking ESLint and collecting timings (e.g. `--verbose`):
```
Encountered 1 error
[build:lint] The create() function for rule '@typescript-eslint/typedef' did not return an object.
```
Fixes #4160
The `_patchTimer()` invokes a callback function to measure execution time, but neglected to pass along its return value.
I patched the **ESLint.js** file in a branch that reproduced the error, and confirmed that the error is fixed.

[heft-lint-plugin] Fix regression: "The create() function for rule ___ did not return an object."

---

apps/lockfile-explorer-web/src/containers/LockfileEntryDetailsView/index.tsx

lockfile-explorer-web  support view dependency version
Now you can view the version of the current dependency declared in direct references, making it easier to analyze the impact of declared version ranges on installed dependencies.
- Start lockfile-explorer-web normally.
- In the lockfile-explorer panel, you can see the version declaration of each dependency in the directly referenced package.
> Now you can see in the panel the version of the dependency declaration directly referenced in it.

[lockfile-explorer] support view dependency version

---

apps/api-documenter/src/cli/MarkdownAction.ts
common/changes/@microsoft/api-documenter/main_2023-04-04-16-09.json

Fixing https://github.com/microsoft/rushstack/issues/4048
Fixes #4048 
I tested in my repository by using `newLineKind: 'lf'` as the config. This is the only thing I have tested
1. `npm link` in `app/api-documenter`
2. In my local app run `npm link @microsoft/api-documenter`
3. Made my changes on my fork
4. Created the `api-documenter.json` file with the line endings config in my project
5. `$ cd /path/to/matteematt/rushstack && rush rebuild && cd - && npm run api`
6. Observe the markdown generated uses LF line endings now
Committed

[api-documenter] Read config when generating markdown files

---

common/changes/@microsoft/rush/fix-rush-test_2023-06-12-22-22.json
libraries/rush-lib/src/logic/test/ShrinkwrapFile.test.ts

Fixes an issue with a mock being reset instead of cleared.
Ran unit tests.

[rush] Fix an issue where a test was writing to the filesystem.

---

LICENSE

Resolves https://github.com/microsoft/rushstack/issues/4151

Include a root-level license file.

---

common/changes/@microsoft/rush/test-pnpm-shrinkwrap-file_2023-06-23-08-39.json
libraries/rush-lib/config/heft.json
libraries/rush-lib/src/logic/pnpm/test/PnpmShrinkwrapFile.test.ts
libraries/rush-lib/src/logic/pnpm/test/repo/apps/foo/package.json
libraries/rush-lib/src/logic/pnpm/test/repo/rush.json
libraries/rush-lib/src/logic/pnpm/test/yamlFiles/pnpm-lock-v5/modified.yaml
libraries/rush-lib/src/logic/pnpm/test/yamlFiles/pnpm-lock-v5/not-modified.yaml
libraries/rush-lib/src/logic/pnpm/test/yamlFiles/pnpm-lock-v6/modified.yaml
libraries/rush-lib/src/logic/pnpm/test/yamlFiles/pnpm-lock-v6/not-modified.yaml

Add a test for `PnpmShrinkwrapFile#isWorkspaceProjectModifiedAsync`
Test the function works well with pnpm lockfile major version 5 and 6.
No

[rush] Test pnpm shrinkwrap file

---

common/changes/@rushstack/heft-typescript-plugin/main_2023-07-03-11-37.json
heft-plugins/heft-typescript-plugin/src/TypeScriptPlugin.ts

[heft][typescript-plugin] fix "project" not working

---

apps/heft/README.md
common/changes/@rushstack/heft/octogonz-heft-readme-updates_2023-07-12-06-59.json

Improve some wording in README.md based on feedback from @dmichon-msft and @D4N14L 
This syncs with https://github.com/microsoft/rushstack-websites/pull/184

[heft] Update README.md

---

common/changes/@microsoft/rush-lib/fix-pre-push-hook_2023-07-20-21-26.json
common/changes/@microsoft/rush/fix-pre-push-hook_2023-07-20-21-26.json
libraries/rush-lib/src/logic/base/BaseInstallManager.ts

Git `pre-push` hook will stop pushing if script return failure, however because git-lfs support causing `pre-push` to never exit with error.
The `set -e` will immediately exit with error if any command exit with error 
fixes #4248

[@microsoft/rush-lib] Git 'pre-push' hooks didn't handle error correctly

---

build-tests/rush-lib-declaration-paths-test/scripts/createSrc.js
libraries/rush-lib/scripts/copyEmptyModules.js

fix: use strict

---

common/changes/@microsoft/rush/chore-add_deploy_configurations_2023-08-24-07-48.json
libraries/rush-lib/src/cli/actions/DeployAction.ts
libraries/rush-lib/src/logic/deploy/DeployScenarioConfiguration.ts
libraries/rush-lib/src/schemas/deploy-scenario.schema.json

Add dependencySettings field to Rush deploy.json configurations. This will allow developers to customize how third party dependencies are processed when running `rush deploy` 
Related PR https://github.com/microsoft/rushstack/pull/4255 cc @D4N14L 
Tested locally
Schema for deploy.json has been updated and need to be updated.

[rush] Surface dependencySettings on the deploy.json configuration

---

common/changes/@microsoft/rush/octogonz-rush-init-cobuild-regression_2023-09-04-18-24.json
common/config/rush/version-policies.json
common/reviews/api/rush-lib.api.md
libraries/rush-lib/src/api/CobuildConfiguration.ts
libraries/rush-lib/src/logic/cobuild/CobuildLock.ts

Fixes https://github.com/microsoft/rushstack/issues/4307
- Repro and fix confirmed by upgrading https://github.com/microsoft/rush-example
None
@chengcyber @iclanton

[rush] Fix an issue where "rush init" created a cobuild.json causing errors

---

rush.json

Update pnpm from 8.7.0 to 8.7.6
This build.
None.

chore: pnpm@8.7.6

---

build-tests/eslint-8-test/.eslintrc.js
build-tests/eslint-8-test/package.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json

Update missed project to consume ESLint configuration from the local rig.
Local build
N/A

[build-tests] Update new project to extend from rig eslint config

---

common/changes/@microsoft/rush/main_2023-10-02-19-05.json
common/config/rush/version-policies.json
libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts
libraries/rush-lib/src/cli/actions/BaseInstallAction.ts
libraries/rush-lib/src/cli/actions/PurgeAction.ts
libraries/rush-lib/src/logic/PackageJsonUpdater.ts
libraries/rush-lib/src/logic/PurgeManager.ts
libraries/rush-lib/src/logic/installManager/doBasicInstallAsync.ts
libraries/rush-lib/src/utilities/AsyncRecycler.ts

Fixes https://github.com/microsoft/rushstack/issues/4334
A folder enumeration step did not handle the case when the folder did not exist.
Tested using the repro steps from the linked issue.

[rush] Fix an issue with rush purge on Linux.

---

common/changes/@rushstack/node-core-library/more-heap-tests_2023-10-02-19-17.json
libraries/node-core-library/src/test/MinimumHeap.test.ts

Adds more unit tests for MinimumHeap.
Validates that no duplication is occurring and no values are being dropped.
Tests across a range of heap sizes.
Running said unit tests.
None.

[node-core-library] Add more heap tests

---

common/changes/@microsoft/rush/more-safe-color-for-testing_2023-10-06-19-03.json
libraries/rush-lib/src/api/CustomTipsConfiguration.ts
libraries/rush-lib/src/api/test/CustomTipsConfiguration.test.ts

Follow-up to https://github.com/microsoft/rushstack/pull/4363. Specifically, https://github.com/microsoft/rushstack/pull/4363/commits/4a5f1e76f566e2f0902de34d5e6443481c6d7174

[rush] Only enable colors in CustomTipsConfiguration.test.ts.

---

common/changes/@microsoft/rush/octogonz-rush-hooks-fix_2023-10-06-22-52.json
common/reviews/api/rush-lib.api.md
libraries/rush-lib/src/api/Rush.ts
libraries/rush-lib/src/cli/RushXCommandLine.ts
libraries/rush-lib/src/cli/test/RushXCommandLine.test.ts
libraries/rush-lib/src/utilities/Utilities.ts

Prepare to publish a Rush release:
1. Fix a bug that @nebosite found where `RUSH_INVOKED_ARGS` was not getting passed through
2. Simplify the `RushXCommandLine.launchRushX()` signature to ensure no options are lost along the way

[rush] Cleanup a couple issues with rushx hooks

---

common/config/rush/artifactory.json
common/config/rush/build-cache.json
common/config/rush/cobuild.json
common/config/rush/custom-tips.json
common/config/rush/experiments.json
common/config/rush/pnpm-config.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
rush.json

Let's test the new Rush release:
- Upgrade to Rush 5.109.1
- Resync the config files with their templates

Upgrade to Rush 5.109.1

---

common/changes/@microsoft/rush/dmyers-log-cache-key_2023-10-16-21-38.json
libraries/rush-lib/src/logic/buildCache/ProjectBuildCache.ts

We've found it helpful to be able to identify the cached asset when debugging production issues with our rush-managed monorepo. Doing so upon successful storage & retrieval gives us (and now, other rush maintainers) the ability to identify that the asset was correctly stored.
- Solved by logging the cache key at verbose level 
- Considered doing so within the success message, but chose verbose (so as not to add additional noise where it may not be needed) 
- Looking at output of rush install upon changed code.

[rush-lib] Log Cache Key when successfully/retrieving storing cached build in cloud storage

---

common/changes/@microsoft/rush/sanjaiyan-async-concurrent_2023-10-20-07-32.json
libraries/rush-lib/scripts/copyEmptyModules.js

Hi, this PR aims to bring performance improvements by running asynchronous code concurrently using `Promise.all`. This approach not only enhances the overall speed and efficiency of the code but also allows for better resource utilization, reduced latency, and improved scalability.

[rush-lib] Enhancing Performance with Concurrent Execution using `Promise.all` ✈

---

common/changes/@microsoft/rush/update-azure-identity_2023-11-27-23-06.json
common/config/rush/pnpm-lock.yaml
common/config/rush/repo-state.json
rush-plugins/rush-azure-storage-build-cache-plugin/package.json

Fixes https://github.com/microsoft/rushstack/issues/4418
Tested by reading and writing from a private Azure Storage container using interactive login.

[rush] Update the @azure/* dependencies.

---

common/changes/@rushstack/eslint-patch/fix-4454-bulk-suppression-in-polyrepo_2023-12-13-21-38.json
eslint/eslint-patch/src/eslint-bulk-suppressions/bulk-suppressions-patch.ts

In a polyrepo, the eslintrc file will usually be in the root directory of the git repository, however `findEslintrcDirectory` will stop as soon as it has reached the `GitRootPath`. Changing this to check if we're outside/above the root path resolves this issue.
Please see #4454 for more details and a reproduction
Tested against the reproduction case in #4454

fix(eslint-patch): fix bulk suppression eslintrc detection in polyrepo

---

common/changes/@microsoft/rush/chao-support-injected-settings_2023-12-13-18-48.json
common/changes/@rushstack/node-core-library/chao-support-injected-settings_2023-12-13-18-48.json
common/reviews/api/node-core-library.api.md
common/reviews/api/rush-lib.api.md
libraries/node-core-library/src/IPackageJson.ts
libraries/node-core-library/src/index.ts
libraries/rush-lib/src/api/PackageJsonEditor.ts
libraries/rush-lib/src/index.ts
libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
libraries/rush-sdk/src/test/__snapshots__/script.test.ts.snap

This PR fixes #4452
I added some additional logic for `shrinkwrapIsUpToDate`
If `dependenciesMeta` settings are different between `package.json` and `pnpm-lock.yaml`, then `shrinkwrapIsUpToDate` return false.
Manually tested with a sample rush repo.

[rush-lib] Fix an issue where rush update can not handle dependenciesMeta in pnpm 

---

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
common/scripts/install-run.js
rush.json

Rush 5.113.0 includes a big chunk of architecture plumbing for the upcoming Rush subspaces feature. Let's dogfood it to make sure there's no regressions! 😇

Upgrade to Rush 5.113.0

---

common/changes/@microsoft/rush/will-subspace-patch-2_2024-01-31-08-39.json
libraries/rush-lib/src/cli/actions/BaseInstallAction.ts
libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts

Additional fixes for the subspaces feature.

[rush] Minor fixes for subspaces

---

build-tests-samples/heft-storybook-react-tutorial-app/config/rush-project.json
build-tests-samples/heft-storybook-react-tutorial-app/package.json
build-tests/api-extractor-d-mts-test/config/rush-project.json
common/changes/@rushstack/eslint-config/fix-caching_2024-01-31-21-18.json
eslint/eslint-config/config/rush-project.json

Update some projects' `rush-project.json` files to fix the build cache.

Fix caching in a few projects.

---

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
common/config/rush/subspaces.json
rush.json

This release included some important fixes.
@iclanton

Upgrade to Rush 5.113.4

---

apps/heft/src/pluginFramework/HeftPluginHost.ts
common/changes/@microsoft/rush/prettify_2024-02-17-07-11.json
common/changes/@rushstack/heft-config-file/prettify_2024-02-17-07-11.json
common/changes/@rushstack/heft/prettify_2024-02-17-07-11.json
common/changes/@rushstack/terminal/prettify_2024-02-17-07-11.json
libraries/heft-config-file/src/test/ConfigurationFile.test.ts
libraries/rush-lib/src/logic/buildCache/FileSystemBuildCacheProvider.ts
libraries/rush-lib/src/logic/test/Telemetry.test.ts
libraries/rush-lib/src/pluginFramework/RushSession.ts
libraries/rush-lib/src/utilities/CollatedTerminalProvider.ts
libraries/terminal/src/test/Colorize.test.ts

Prettify the repo.

---

common/changes/@rushstack/node-core-library/ncl-major-bump_2024-02-17-18-39.json
common/changes/@rushstack/node-core-library/ncl-major-bump_2024-02-17-18-40.json
common/reviews/api/node-core-library.api.md
libraries/node-core-library/src/Async.ts
libraries/node-core-library/src/FileSystem.ts
libraries/node-core-library/src/LegacyAdapters.ts
libraries/node-core-library/src/MinimumHeap.ts

As we're doing a major bump of `@rushstack/node-core-library`, this PR takes the opportunity to clean up the API a bit.
Ran build.
API docs need to be updated.

[node-core-library] Graduate a few beta APIs and remove a few deprecated APIs.

---

common/changes/@microsoft/rush/octogonz-rush-init_2024-02-19-21-40.json
libraries/rush-lib/assets/rush-init/common/config/rush/experiments.json

Found during testing -- let's make this `rush init` setting consistent with the others.

[rush] Fix an experiments.json default

---

common/changes/@microsoft/rush/chao-fix-bugs_2024-02-21-22-28.json
libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts

1. `this.rushConfiguration.tempShrinkwrapFilename` is deprecated, replace it with `subspace.getTempShrinkwrapFilename()`
2. Fix a path mismatch in Windows OS 
Manually tested on both Mac and Windows

Replace deprecated function, and fix a path bug in Windows OS

---

common/changes/@rushstack/node-core-library/sleep-0_2024-02-28-19-54.json
common/changes/@rushstack/operation-graph/sleep-0_2024-02-28-19-54.json
libraries/node-core-library/src/test/Async.test.ts
libraries/operation-graph/src/test/OperationExecutionManager.test.ts
libraries/operation-graph/src/test/WorkQueue.test.ts

This change supersedes https://github.com/microsoft/rushstack/pull/4495, doing what was suggested in https://github.com/microsoft/rushstack/pull/4495#issuecomment-1912547744

Update 1ms sleeps in tests to 0ms

---

common/changes/@microsoft/rush/octogonz-missing-cache-docs_2024-02-28-22-58.json
common/config/rush/version-policies.json
libraries/rush-lib/assets/rush-init/common/config/rush/build-cache.json
libraries/rush-lib/src/api/BuildCacheConfiguration.ts
libraries/rush-lib/src/logic/buildCache/CacheEntryId.ts

[rush] Add missing build-cache.json docs

---

common/changes/@microsoft/rush/will-subspace-patch-7_2024-03-06-22-06.json
common/reviews/api/rush-lib.api.md
libraries/rush-lib/src/api/SubspacesConfiguration.ts
libraries/rush-lib/src/cli/actions/BaseInstallAction.ts
libraries/rush-lib/src/logic/base/BaseInstallManager.ts

This PR adds filtered installs for subspaces. For example when installing to a project in a subspace, and there are dependencies in other subspaces, installations in those other subspaces will now use filtering to avoid installing for the entire subspace.
This PR also removes the need for a global-pnpmfile environment variable, instead directly adding the temp folder path to the generated temp .npmrc file.

[rush] Add filtered installs for subspaces

---

common/changes/@microsoft/rush/will-subspace-patch-8_2024-03-07-22-37.json
common/docs/rfcs/rfc-4230-rush-subspaces.md
libraries/rush-lib/assets/rush-init/common/config/rush/[dot]npmrc-global
libraries/rush-lib/src/cli/actions/PublishAction.ts
libraries/rush-lib/src/logic/Autoinstaller.ts
libraries/rush-lib/src/logic/base/BaseInstallManager.ts
libraries/rush-lib/src/logic/setup/SetupPackageRegistry.ts
libraries/rush-lib/src/scripts/install-run.ts
libraries/rush-lib/src/utilities/Utilities.ts
libraries/rush-lib/src/utilities/npmrcUtilities.ts

This MR adds the option to specify lines to be prepended and/or appended to the .npmrc file when it is synced via the Utilities.syncNpmrc function from the source to target folder. It also cleans up the syncNpmrc function parameter list by moving the parameters into an option object.
This is so that global npmrc lines can be added before subspace npmrc lines, allowing for subspace level configuration overrides. This MR also adds the global npmrc file to rush init.

Add ability to configure where global npmrc lines are added

---

common/changes/@microsoft/rush/will-subspace-migration-patch-9_2024-03-09-00-21.json
libraries/rush-lib/src/utilities/npmrcUtilities.ts

Hotfix a bug introduced with the last PR https://github.com/microsoft/rushstack/pull/4573 where the syncNpmrc function was getting incorrectly called with the folder path instead of the file path.

[rush] Fixes .npmrc lookup bug introduced in syncNpmrc

---

common/changes/@microsoft/rush/will-subspace-patch-11_2024-03-19-23-44.json
common/reviews/api/rush-lib.api.md
libraries/rush-lib/src/logic/RushConstants.ts
libraries/rush-lib/src/logic/base/BaseLinkManager.ts
libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts

This creates symlinks for hoisted dependencies in a package's node_modules folder if splitWorkspaceCompatibility is set to true. This is for projects that are migrating away from the split workspace model, where they may have hoisted dependencies in their local project folder, which are now moved to the temp folder under the subspace workspace format.

[rush-lib] Hoist dependencies for projects moving away from split workspaces

---

common/changes/@microsoft/rush/chao-fix-bugs_2024-03-22-04-12.json
libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
libraries/rush-lib/src/logic/pnpm/SubspaceGlobalPnpmfileShim.ts

Some path operation in Windows OS is not correct, and will cause install error when enable subspace feature. We can convert the path to Linux style to fix the issue. 
Manually tested in a Windows Machine

[rush-lib] Fix bugs related to path operation in Windows OS for subspace feature

---

common/changes/@microsoft/rush/will-subspace-patch-12_2024-03-25-22-12.json
libraries/rush-lib/src/api/Subspace.ts
libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
libraries/rush-lib/src/utilities/Utilities.ts

This warns the user if they have .npmrc files or .pnpmfile.cjs files after migrating to subspaces and are using splitWorkspaceCompatibility. Also fixes a minor bug where if a package lists no dependencies and still tries to hoist dependencies, rush update no longer crashes because it cannot find a .modules.yaml file in the node_modules folder.

Add warnings for subspaces that have npmrc or pnpmfile.cjs files

---

build-tests/eslint-bulk-suppressions-test/build.js

`eslint-bulk-suppressions-test` was occasionally failing with an error message like:
[ci.yml #2690](https://github.com/microsoft/rushstack/actions/runs/8440004809/job/23115926327)
```
==[ eslint-bulk-suppressions-test (build) ]====================[ 274 of 284 ]==
Invoking: node build.js --production
-- Running eslint-bulk-suppressions for eslint@8.7.0 in client --
STDOUT:
STDERR:
@rushstack/eslint-bulk: Error finding patch path: Command failed: eslint --stdin --config .eslintrc.js
'nt.js" --stdin --config .eslintrc.js' is not recognized as an internal or external command,
operable program or batch file.
-----------------------------------------------------------------
-- Running eslint-bulk-suppressions for eslint@8.23.1 in client --
STDOUT:
STDERR:
@rushstack/eslint-bulk: Error finding …
```

Workaround for occasional failures of eslint-bulk-suppressions-test

---

common/changes/@microsoft/rush/fix-publish_2024-03-28-19-28.json
common/config/azure-pipelines/npm-publish.yaml

Republish rush.

---

common/changes/@rushstack/heft-typescript-plugin/graceful-worker-exit_2024-03-28-22-00.json
common/changes/@rushstack/module-minifier/graceful-worker-exit_2024-03-28-22-00.json

Changes the bump type for #4613 
Minor instead of patch.
No code change.
None

[workers] Minor instead of patch bump

---

apps/lockfile-explorer/package.json
common/changes/@microsoft/rush/bump-express_2024-03-31-22-37.json
common/changes/@rushstack/lockfile-explorer/bump-express_2024-03-31-22-37.json
common/config/subspaces/default/pnpm-lock.yaml
common/config/subspaces/default/repo-state.json
rush-plugins/rush-serve-plugin/package.json

Supersedes:
- https://github.com/microsoft/rushstack/pull/4603
- https://github.com/microsoft/rushstack/pull/4604
Ran `rush start` with the updated plugin, ran `rushx serve` in `lockfile-exploer`.
None.

Bump Express.

---

common/changes/@microsoft/rush/chao-improve-transitive-injected-install_2024-04-04-22-21.json
libraries/rush-lib/src/logic/pnpm/SubspacePnpmfileConfiguration.ts

This PR adds some improvements to the PR https://github.com/microsoft/rushstack/pull/4583, which relates to PNPM injected install feature for Rush Subspace. 
When a package gets installed in the injected way then every workspace:* dependency of that package also gets injected.
Here, the transitive injected dependency should only apply to dependencies and optional dependencies fields in the `package.json`, not include the devDependencies

[rush-lib] handle optional dependencies in transitive injected install

---

common/changes/@microsoft/rush/chao-upgrade-pnpm-sync_2024-04-10-18-15.json
common/config/subspaces/default/pnpm-lock.yaml
common/config/subspaces/default/repo-state.json
libraries/rush-lib/package.json
libraries/rush-lib/src/utilities/PnpmSyncUtilities.ts

Update `pnpm-sync-lib` to version 0.2.2. 
Here is a list of noticeable changes:
1. Add a version field in .pnpm-sync.json. [Link](https://github.com/tiktok/pnpm-sync/pull/23) 
2. Use PNPM's logic to process `depPathToFilename`, to ensure compatibility with PNPM. [Link](https://github.com/tiktok/pnpm-sync/pull/24)
3. Improve filename path format on Windows OS. 
Manually tested with Rushstack repo locally.

[rush-lib] Update dependency: pnpm-sync-lib@0.2.2

---

common/changes/@microsoft/rush/will-subspace-patch-15_2024-04-13-16-51.json
libraries/rush-lib/src/api/Subspace.ts
libraries/rush-lib/src/logic/DependencyAnalyzer.ts
libraries/rush-lib/src/logic/PackageJsonUpdater.ts
libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts

This MR fixes the following issues related to subspaces
- "rush add -p <package>" now correctly ensures consistent versions only in the affected subspaces
- Rush can now correctly determine when the installation is outdated when subspaces is enabled
- Rush looks for the correct pnpmfile-subspace.cjs file for outdated files

Fix an issue with the canSkipInstall function with subspaces

---

common/changes/@microsoft/rush/main_2024-04-15-00-02.json
libraries/rush-lib/src/logic/DependencyAnalyzer.ts
libraries/rush-lib/src/logic/PackageJsonUpdater.ts

Hotfix for rush install issue with subspaces

---

common/changes/@microsoft/rush/upgrade-node-tar_2024-04-15-08-30.json
common/config/subspaces/default/pnpm-lock.yaml
common/config/subspaces/default/repo-state.json
libraries/rush-lib/package.json

Please check https://github.com/microsoft/rushstack/issues/4645

[rush] Bump tar to 6.2.1 to fix CVE-2024-28863

---

common/changes/@microsoft/rush/chao-fix-pnpm-sync-with-build-cache_2024-04-15-20-30.json
common/scripts/install-run-rush-pnpm.js
common/scripts/install-run-rush.js
common/scripts/install-run-rushx.js
common/scripts/install-run.js
libraries/rush-lib/src/logic/operations/PnpmSyncCopyOperationPlugin.ts
rush.json

Fix a issue for `pnpm-sync copy`. When restoring a build from build cache server, the `pnpm-sync copy` should not be skipped. 
Manually tested with Rushstack repo locally.

[rush-lib] `pnpm-sync copy` should not be skipped when a build is restored from build cache

---

common/changes/@microsoft/rush/will-subspace-patch-19_2024-04-16-15-14.json
libraries/rush-lib/src/cli/actions/DeployAction.ts
libraries/rush-lib/src/logic/base/BaseLinkManager.ts
libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
libraries/rush-lib/src/utilities/Utilities.ts

This MR fixes an issue where broken symlinks were not being correctly deleted, and also fixes an issue where rush deploy does not work with subspaces

Hotfix for rush deploy and subspace compatibility

---

common/changes/@microsoft/rush/chao-support-rush-pnpm_2024-04-23-20-22.json
libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts

Currently, if a repo is enabled with subspace feature, the `rush-pnpm` command is no longer working. It complains that `Error: The PNPM workspace file has not been generated`. 
This is due to that in subspace, we moved the `common/temp` folder as well as the `pnpm-workspace.yaml` file location. 
This PR is to address this issue. Users now will be able to input the subspace name when calling the `rush-pnpm` command, like `rush-pnpm --subspace <subspace_name>`. The command will use the `default` subspace if it is not provided. 
Manually tested with Rushstack repo locally.

[rush-lib] Support rush-pnpm for subspace feature

---

common/changes/@microsoft/rush/fix-skip-install-check_2024-04-26-10-46.json
common/reviews/api/rush-lib.api.md
libraries/rush-lib/src/api/Subspace.ts
libraries/rush-lib/src/logic/base/BaseInstallManager.ts

BaseInstallManager-canSkipInstall check need to check pnpm-config.json file also
self tested on local repo

[rush] canSkipInstall() should also consider the pnpm-config.json file

---

common/changes/@microsoft/rush/will-hotfix-install-flag-await_2024-05-07-21-49.json
libraries/rush-lib/src/logic/Autoinstaller.ts
libraries/rush-lib/src/logic/installManager/InstallHelpers.ts

[rush] Fix missing await on async call

---

common/changes/@microsoft/rush/chao-fix_2024-05-09-23-55.json
common/config/rush/version-policies.json
common/config/subspaces/default/pnpm-lock.yaml
common/config/subspaces/default/repo-state.json
libraries/rush-lib/package.json
libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts

1. Upgrade pnpm-sync-lib
2. Fix an edge case that integrity could be none in `_disallowInsecureSha1`
Manually tested with the Rushstack repo locally.

[rush-lib] Upgrade pnpm-sync-lib and fix an edge case that integrity could be none in _disallowInsecureSha1 logic

---

.github/workflows/ci.yml
common/changes/@microsoft/rush/fix-rush-install-followups_2024-05-14-23-49.json
libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts
libraries/rush-lib/src/cli/actions/BaseInstallAction.ts
libraries/rush-lib/src/cli/actions/InstallAction.ts
libraries/rush-lib/src/cli/actions/UpdateAction.ts
libraries/rush-lib/src/cli/parsing/SelectionParameterSet.ts
libraries/rush-lib/src/logic/PackageJsonUpdater.ts
libraries/rush-lib/src/logic/base/BaseInstallManager.ts
libraries/rush-lib/src/logic/base/BaseInstallManagerTypes.ts
libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
libraries/rush-lib/src/logic/installManager/doBasicInstallAsync.ts

#4701 was set to autocomplete and went in before being fully reviewed. This PR contains followups to that PR.
No substantial code changes were made.
None.

[rush] Followups to #4701.

---

common/changes/@microsoft/rush/cleanup-after-4707_2024-05-15-04-50.json
libraries/rush-lib/src/cli/actions/BaseInstallAction.ts
libraries/rush-lib/src/cli/parsing/SelectionParameterSet.ts

Some minor code cleanup after #4707.

[rush] Minor code cleanup.

---

common/changes/@microsoft/rush/chao-update-pnpm-sync_2024-05-20-22-56.json
common/config/subspaces/default/pnpm-lock.yaml
common/config/subspaces/default/repo-state.json
libraries/rush-lib/package.json

Update `pnpm-sync-lib` version to 0.2.6.  See this [PR for more details](https://github.com/tiktok/pnpm-sync/pull/33)
In this version, we fixed an issue in `alwaysInjectDependenciesFromOtherSubspaces` logic.
Before, we check the injected settings in the package.json to tell if a dependency is injected or not. However, in `alwaysInjectDependenciesFromOtherSubspaces` case, user no need to set injected settings in package.json for these dependencies. So this check logic is no longer accurate. It will lead an issue that `pnpm-sync.json` is not generated for these dependencies.
So, now, we check the version representation in `pnpm-lock.yaml` to see if it is started with `file:`, if yes, then it is a injected dependency.

[rush-lib] Change the logic of how to check if a dependency is an injected dependency

---

common/changes/@rushstack/node-core-library/include-packagejson-files_2024-05-27-23-22.json
common/reviews/api/node-core-library.api.md
libraries/node-core-library/CHANGELOG.json
libraries/node-core-library/CHANGELOG.md
libraries/node-core-library/src/IPackageJson.ts

Include typings for the "files" package.json field.
N/A
API docs need to be updated.

[node-core-library] Include typings for the "files" package.json field.

---

apps/api-documenter/package.json
apps/api-extractor/package.json
common/changes/@microsoft/api-documenter/main_2024-05-28-21-54.json
common/changes/@microsoft/api-extractor-model/main_2024-05-28-21-54.json
common/changes/@microsoft/api-extractor/main_2024-05-28-21-54.json
common/changes/@rushstack/eslint-config/main_2024-05-28-21-54.json
common/config/subspaces/default/pnpm-lock.yaml
common/config/subspaces/default/repo-state.json
eslint/eslint-config/package.json
libraries/api-extractor-model/package.json
repo-scripts/doc-plugin-rush-stack/package.json

Bumps TSDoc dependencies.
Built.
None.

Bump TSDoc dependencies.

---

common/changes/@microsoft/rush/will-subspace-patch-29_2024-06-03-22-54.json
libraries/rush-lib/src/cli/test/Cli.test.ts
libraries/rush-lib/src/schemas/common-versions.schema.json

[rush] Update common-versions schema to include ensureConsistentVersions

---

common/changes/@microsoft/rush/adrian-did-user-selected-any-project_2024-06-12-08-24.json
libraries/rush-lib/src/cli/parsing/SelectionParameterSet.ts

didUserSelectAnything() should also take the _fromProject property into account.

[rush]didUserSelectAnything() should also take the _fromProject property into account.

---

common/changes/@microsoft/rush/qun-sha1_2024-05-30-16-44.json
libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts

Provide more hints to the user to help them understand where to fix the issue

[rush] Display to the user subspace name where the error occurred

---

common/changes/@microsoft/rush/will-make-consistent_2024-06-17-19-59.json
libraries/rush-lib/src/logic/PackageJsonUpdater.ts

This addresses the issue #4789 where running `rush add -p <package_name> --make-consistent` will update the package.json files of projects outside the current subspace.

[rush] Scope --make-consistent when adding projects to subspace

---

common/changes/@microsoft/rush/bump-azure-identity_2024-06-16-21-03.json
common/config/subspaces/default/pnpm-lock.yaml
common/config/subspaces/default/repo-state.json
rush-plugins/rush-azure-storage-build-cache-plugin/package.json

Fixes https://github.com/microsoft/rushstack/issues/4785
Tested with interactive auth.
None.

[rush] Bump @azure/identity.

---

common/changes/@microsoft/rush/will-analysis-by-subspace_2024-06-20-23-18.json
common/config/subspaces/build-tests-subspace/repo-state.json
libraries/rush-lib/src/logic/DependencyAnalyzer.ts

This fixes an issue where the DependencyAnalyzer will re-use the same analysis for different subspaces.

Refactor DependencyAnalyzer to handle multiple subspaces

---

common/changes/@microsoft/rush/fix-rush-plugin-file-permission_2024-06-21-04-34.json
common/config/subspaces/build-tests-subspace/repo-state.json
libraries/rush-lib/src/pluginFramework/PluginLoader/AutoinstallerPluginLoader.ts
rush.json

Consolidate rush plugins files permission to 644 (UserWrite & AllRead)
I got a user feedback that the `rush-plugin-manifest.json` and `command-line.json` has inconsistent file permission locally. 
By doing this, running `rush update` changes the permissions of these file back and forth, and it's pretty annoying.
This PR consolidates the file permissions for rush plugins to 644(UserWrite & AllRead)
Local
No

[rush] Consolidate rush plugin files permission

---

common/changes/@microsoft/webpack5-load-themed-styles-loader/octogonz-lfx-pause-publishing_2024-06-24-22-26.json
common/config/subspaces/default/repo-state.json
rush.json
webpack/webpack5-load-themed-styles-loader/src/test/LoadThemedStylesLoader.test.ts

I'm investigating some issues from the last PR.

[lockfile-explorer] Temporarily suspend publishing

---

common/config/subspaces/build-tests-subspace/repo-state.json
rush.json

Update rush version to 5.129.6. This should greatly reduce the conflicts caused by `packageJsonInjectedDependenciesHash`.
You can learn more in these two PRs: https://github.com/microsoft/rushstack/pull/4809, https://github.com/microsoft/rushstack/pull/4806

chore: update rush version

---

common/changes/@microsoft/rush/chao-upgrade-pnpm-sync_2024-06-29-01-02.json
common/config/subspaces/build-tests-subspace/pnpm-lock.yaml
common/config/subspaces/build-tests-subspace/repo-state.json
common/config/subspaces/default/pnpm-lock.yaml
common/config/subspaces/default/repo-state.json
libraries/rush-lib/package.json

In some cases, when PNPM install injected dependencies, it will create necessary node_modules/.bin folder in PNPM store.
We will need to keep it as it is as delete them is not a safe action for now.
Learn more: https://github.com/tiktok/pnpm-sync/pull/36

[rush] Upgrade pnpm-sync-lib

---

common/config/subspaces/build-tests-subspace/common-versions.json
common/config/subspaces/default/common-versions.json
rush.json

We just published a [batch of fixes](https://github.com/microsoft/rushstack/blob/main/apps/rush/CHANGELOG.md#51297). Let's dogfood them.

Upgrade to Rush 5.129.7

---

rush.json

Bump rush to 5.135.0-pr4927.1.

---

common/changes/@microsoft/rush/fix-deploy_2024-10-22-04-03.json
common/changes/@microsoft/rush/support-pnpm-ignore-optional-dependencies_2024-10-13-01-04.json

Update changelog messages in preparation for a Rush version bump

[rush] Prepare for publish with updated changelog messages

---

build-tests/api-extractor-scenarios/package.json
common/config/rush/browser-approved-packages.json
common/config/subspaces/default/pnpm-lock.yaml

Minor repo cleanup.

---

common/config/rush/version-policies.json

Make the next release of Rush a minor bump.

---

rush.json

Bump Rush to 5.143.0-pr5009.1.

---

.github/workflows/ci.yml

Follow-up to https://github.com/microsoft/rushstack/pull/5038

Remove Windows+Node 18 from the validation matrix.

---

common/config/rush/version-policies.json

Prepare to publish a PATCH release of Rush

---

common/changes/@microsoft/rush/chore-remove-useless-field_2025-02-16-09-52.json
common/reviews/api/rush-lib.api.md
libraries/rush-lib/src/logic/RushConstants.ts

The `rushAlertsStateFilename` field is no longer in use, so let's remove it to avoid causing any confusion.

[rush-lib] remove useless field "rushAlertsStateFilename"

---

build-tests/api-documenter-scenarios/config/heft.json
build-tests/api-documenter-scenarios/config/typescript.json

Follow-up to https://github.com/microsoft/rushstack/pull/5124.

Mitigate a potential race condition.

---

common/config/rush/version-policies.json

Make the next release of Rush a minor version

---

common/reviews/api/rush-buildxl-graph-plugin.api.md
rush-plugins/rush-buildxl-graph-plugin/rush-plugin-manifest.json
rush-plugins/rush-buildxl-graph-plugin/src/DropBuildGraphPlugin.ts
rush-plugins/rush-buildxl-graph-plugin/src/GraphProcessor.ts
rush-plugins/rush-buildxl-graph-plugin/src/index.ts
rush-plugins/rush-buildxl-graph-plugin/src/schemas/rush-buildxl-graph-plugin.schema.json

This package is still under development.

[rush] Add a few new features to the Rush BXL graph plugin.

---

.github/copilot-instructions.md
.trae/project_rules.md

Follow the same pattern as [.cursor/rules/rush.mdc](https://github.com/microsoft/rushstack/blob/main/.cursor/rules/rush.mdc) for Cursor

Add context files for Trae and GitHub Copilot

---

common/changes/@rushstack/eslint-plugin/bump-versions-follow-up_2025-07-08-01-08.json
eslint/eslint-plugin/src/no-untyped-underscore.ts
rigs/decoupled-local-node-rig/profiles/default/includes/eslint/flat/patch/custom-config-package-names.js
rigs/decoupled-local-node-rig/profiles/default/includes/eslint/flat/patch/modern-module-resolution.js

Follow-ups to #5271.

---

rush.json

Bump Rush.

---

.devcontainer/devcontainer.json

Fallback to default container settings

---

common/changes/@microsoft/rush/fix-extensions-hash_2025-10-03-20-27.json
common/config/rush/version-policies.json
libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts

[rush] Follow-up to #5395
