microsoft/rushstack

apps/rush-lib/src/pluginFramework/PluginManager.ts, apps/rush/src/start-dev.ts, common/changes/@microsoft/rush/rush-azure-interactive-auth-plugin_2022-04-04-21-31.json, common/reviews/api/rush-azure-storage-build-cache-plugin.api.md, rush-plugins/rush-azure-storage-build-cache-plugin/rush-plugin-manifest.json, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureStorageAuthentication.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/RushAzureInteractiveAuthPlugin.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/schemas/azure-interactive-auth.schema.json
Adds a separately callable plugin to the `@rushstack/rush-azure-storage-build-cache-plugin` that can be used to refresh Azure credentials at the start of a rush command. Expected usage is to prompt a user immediately if authentication is required to a dev-deployment storage account or similar.
Leverages the existing infrastructure in the plugin to perform an interactive auth prompt, but as a separately named plugin. Configuration for the storage account is read from the plugin configuration.
Until such time as the Azure Storage build cache plugin is removed from the default install (Rush 6 release), this plugin is enabled by default but doesn't take any action unless a config file is provided.
Configured the plugin in the repo and bound it to the `rush build` action temporarily. Verified …
=> [rush-azure-storage-build-cache-plugin] Add plugin for Azure authentication prompt

common/config/azure-pipelines/npm-publish-rush.yaml, common/config/azure-pipelines/npm-publish.yaml, common/config/azure-pipelines/templates/bump-versions.yaml, common/config/azure-pipelines/templates/publish.yaml
Because the repo now contains a Rush plugin that isn't part of the Rush lockstepped version policy, publishing of Rush needs to bump all versions (both Rush packages and non-Rush packages) before publishing anything to ensure the plugin gets the right version of rush-sdk when published.
=> Bump versions before running publish.

common/changes/@microsoft/rush/fix-install-run-rush-help_2022-04-12-02-24.json, libraries/rush-lib/src/scripts/install-run-rush.ts
`install-run-rush --help` currently throws an exception and does not install Rush. This broke one of rush-sdk's scenarios.
This fix adds a special case for the `-h` and `--help` flags.
Ran `install-run-rush --help` and confirmed that it installs rush-lib.
=> [rush] Fix install-run-rush --help.

common/changes/@rushstack/rush-serve-plugin/fix-serve-publish_2022-04-12-20-15.json, rush-plugins/rush-serve-plugin/.npmignore
Updates the tarball contents to include the `rush-plugin-manifest.json` file.
See above
Verified content of running `pnpm pack` locally.
=> [rush-serve-plugin] Include missing manifest in publish

common/changes/@rushstack/eslint-patch/main_2022-04-11-10-57.json, eslint/eslint-patch/src/usage.ts
Adds a blank `export = {}` to the `eslint-patch` entry point to allow other tools (specifically Vite) to automatically determine this is Common JS.
Fixes #3343
Adding a blank export provides enough information for Vite to determine this is indeed CommonJS.
This entry point is only used to throw an error to warn the user not to directly import the package. No breaking change. No performance impacts.
Re-built my project with Vite, the warning mentioned in #3343 was no longer output.
Imported the package directly, and validated the usage error was still thrown as expected.
=> [eslint-patch] fix: add empty export for module type detection

common/changes/@microsoft/rush/unassociated-parameters_2022-04-19-20-28.json, libraries/rush-lib/src/api/CommandLineConfiguration.ts, libraries/rush-lib/src/api/test/CommandLineConfiguration.test.ts
Allows custom parameters to be associated with a phased custom command without being required to also be associated with a phase. This supports the scenario in which a parameter is meant for use by a Rush plugin but is not associated with any particular phase.
Unit test case.
=> [rush-lib] Relax association for custom parameters

common/changes/@microsoft/rush/un-deprecate-packageJson_2022-04-25-01-53.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/RushConfigurationProject.ts
This removes the `@deprecated` label from `RushConfigurationProject`'s `packageJson` property. This is a useful property for tools integrating with `rush-lib`.
=> [rush] Un-deprecate RushConfigurationProject.packageJson.

common/changes/@microsoft/rush/empty-script_2022-04-24-22-20.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/OperationStatus.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunnerPlugin.ts
Right now, projects with an empty script are reported as "from cache" after their operations 'complete.' This is misleading. This PR adds a separate status to specifically report that no work was performed for these projects.
Ran `rush build` in a repo that has projects with empty scripts.
=> [rush] Split 'NO OP' into its own status, distinct from 'FROM CACHE'

common/changes/@rushstack/heft-jest-plugin/enelson-default-jest_2022-04-21-15-15.json, heft-plugins/heft-jest-plugin/UPGRADING.md, heft-plugins/heft-jest-plugin/includes/jest-shared.config.json
Enable `"clearMocks": true` in the shared jest config for `heft-jest-plugin`.
Fixes #3325.
I think this is a bare minimum setting and appropriate for the shared config.
If you have a project without this setting, it is _possible_ you could upgrade `heft-jest-plugin` and have to fix some unit tests, so `patch` doesn't seem appropriate (I picked `minor` for this case).
Full rebuild of Rush passes successfully.
=> [heft-jest-plugin] Enable clearMocks in shared jest config

common/changes/@rushstack/rush-serve-plugin/serve-missing-dependency_2022-04-26-00-35.json, common/config/rush/pnpm-lock.yaml, rush-plugins/rush-serve-plugin/package.json
Fixes a missing runtime dependency in @rushstack/rush-serve-plugin on @rushstack/heft-config-file
The dependency is needed to read rush-project-serve.json from projects.
Had been using a runtime workaround in consuming packages.
=> [rush-serve-plugin] Fix missing runtime dependency

common/changes/@microsoft/rush/disable-skip-if-cache_2022-04-27-19-57.json, libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts
Fixes #3311 
Disables the legacy skip behavior if the build cache is enabled.
Local builds.
=> [rush-lib] Disable legacy skip if build cache enabled

common/changes/@microsoft/rush/fix-json-flag_2022-05-03-21-15.json, libraries/rush-lib/src/api/test/__snapshots__/CommandLineConfiguration.test.ts.snap, libraries/rush-lib/src/cli/RushCommandLineParser.ts, libraries/rush-lib/src/cli/actions/InitAutoinstallerAction.ts, libraries/rush-lib/src/cli/actions/UpdateAutoinstallerAction.ts, libraries/rush-lib/src/cli/scriptActions/GlobalScriptAction.ts, libraries/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap, libraries/rush-lib/src/logic/Autoinstaller.ts, libraries/rush-lib/src/logic/installManager/InstallHelpers.ts, libraries/rush-lib/src/pluginFramework/PluginLoader/AutoinstallerPluginLoader.ts, libraries/rush-lib/src/pluginFramework/PluginManager.ts
The plugin autoinstallation prints to the console by default. This change suppresses that output using the same heuristics that suppresses the banner.
Tested in the repo where I initially observed this.
=> [rush] Fix an issue where "rush list --json" prints non-json output in a repo that uses rush plugins with autoinstallers.

common/changes/@rushstack/set-webpack-public-path-plugin/user-ianc-fix-set-public-path_2022-05-04-02-21.json, common/config/rush/pnpm-lock.yaml, webpack/set-webpack-public-path-plugin/package.json
The current release of `@rushstack/set-webpack-public-path-plugin` is broken because `@rushstack/webpack-plugin-utilities` is declared as a devDependency instead of a normal dependency. This PR moves it.
=> Fix release of set-webpack-public-path-plugin.

apps/api-extractor/src/analyzer/TypeScriptInternals.ts, common/changes/@microsoft/api-extractor/users-chhol-update-api-for-getDiagnosticsProducingTypeChecker_2022-05-04-21-31.json
This PR is intended to (hopefully) provide a backwards compatible solution for incoming breaking changes in typescript's internals as of v4.7.0 (currently in beta). This PR closes https://github.com/microsoft/rushstack/issues/3349. 
API-Extractor relies on Typescript internals to function, and those internals have been changed with this PR for the upcoming minor version of Typescript: https://github.com/microsoft/TypeScript/pull/36747/files.
This change checks the validity of either API and should execute based on one being available. I tended towards keeping things less verbose to keep from requiring multiple nested if statements, etc. One place this is apparent is the error thrown. Rather than trying to track down which instance is missing, it seemed that providing a note that either is …
=> [api-extractor]: update getGlobalVariableAnalyzer to support changes to typescript internals in v4.7

common/changes/@microsoft/rush/install-option_2022-05-02-21-50.json, libraries/rush-lib/src/api/CommandLineConfiguration.ts, libraries/rush-lib/src/api/CommandLineJson.ts, libraries/rush-lib/src/cli/RushCommandLineParser.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/installManager/doBasicInstallAsync.ts, libraries/rush-lib/src/schemas/command-line.schema.json
Allows phased commands to opt into performing a `rush install` prior to execution.
Adds a new section `installOptions` to phased command definitions. The section contains one option `alwaysInstall: boolean`. If set to `true`, the command will always invoke a full `rush install` (which may detect that nothing needs to be done) prior to execution. If set to `false`, then the command provides an `--install` CLI parameter to perform the installation but does not do so by default.
Locally added the option to `rush start`, tested with `alwaysInstall: false` and verified that `--install` was available and worked as intended. Tested with `alwaysInstall: true` and verified that `--install` was not available and the installation occurred automatically.
=> [rush-lib] Allow phased commands to install prior to execution if requested

common/changes/@microsoft/rush/finer-watch-tasks_2022-05-04-00-03.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/ProjectWatcher.ts, libraries/rush-lib/src/logic/operations/Operation.ts, libraries/rush-lib/src/logic/operations/PhasedOperationPlugin.ts, libraries/rush-lib/src/logic/operations/test/PhasedOperationPlugin.test.ts, libraries/rush-lib/src/logic/operations/test/__snapshots__/PhasedOperationPlugin.test.ts.snap, libraries/rush-lib/src/pluginFramework/PhasedCommandHooks.ts
Refines the project watcher and scheduling engine for phased commands to schedule only the operations that would be impacted by the detected change.
If `command-line.json` defines at least on phase with no dependencies for a watch mode phased command, that phase will now only be run for projects that directly contain changes.
Previously the projects with changes and all of their consumers would run all defined watch phases in response to a change.
Added unit test.
Verified behavior of `rush start` in various scenarios.
Temporarily defined an extra phase in `rush start` with no dependencies and verified behavior of the phase in response to changes.
=> [rush-lib] Only schedule operations impacted by detected changes

common/changes/@microsoft/rush/fix-post-install-hook_2022-05-06-14-56.json, libraries/rush-lib/src/cli/actions/BaseInstallAction.ts
This moves executing the `postRushInstall` hook to after telemetry is written and flushed.
It also changes the logic to run the hook even on a failure. If this would be a breaking change maybe we should add a new hook that is specifically used for reading telemetry files?
fixes #3400
Tested locally in another project using `node <snip>/rushstack/libraries/rush-lib/lib/start.js --debug update`, and it worked.
=> [rush] always run `postRushInstall`, and run after writing telemetry

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@microsoft/rush/fix-pnpmNoStrictPeerDependenciesOption_2022-05-07-09-46.json, libraries/rush-lib/src/api/RushConfiguration.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/schemas/rush.schema.json
In version 7.0.0, PNPM changed default value for parameter `--strict-peer-dependencies` from `false` to `true`.
Problem: Rush does not behave correctly with `pnpmOptions.strictPeerDependencies` set to false in `rush.json` as then argument `--no-strict-peer-dependencies` is not passed to the call of PNPM if PNPM is used in version >= 7.0.0. As a result, our monorepo could not been built anymore even though we have set `pnpmOptions.strictPeerDependencies` to `false`.
Solution: Ensure that Rush adds argument `--no-strict-peer-dependencies` to the call of PNPM if `pnpmOptions.strictPeerDependencies` is set to false and PNPM >= 7.0.0 is used. Argument `--strict-peer-dependencies` is added if `pnpmOptions.strictPeerDependencies` is set to true and PNPM < 7.0.0 is used.
I tested it with the same …
=> [rush] Fix `--strict-peer-dependencies` for PNPM >= 7.0.0

common/changes/@rushstack/node-core-library/fix-async-concurrency_2022-05-10-00-46.json, libraries/node-core-library/src/Async.ts
Fix a bug where `Async.forEachAsync` operating on an async iterable would exceed the max concurrency specified in the options.
The state of "waiting for iterator to return" was not tracked as a concurrent operation, so more instances of the waiter function could be paused at the iterator than the maximum concurrency specified in the original call.
Affects concurrency of `rush build`. Validated that after the fix was applied that max concurrency of a highly-cached build was capped at the number of CPU cores.
=> [node-core-library] Fix Async.forEachAsync concurrency

common/changes/@microsoft/rush/after-execute-operations-hook_2022-05-09-21-26.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/index.ts, libraries/rush-lib/src/logic/operations/ConsoleTimelinePlugin.ts, libraries/rush-lib/src/logic/operations/IOperationExecutionResult.ts, libraries/rush-lib/src/logic/operations/OperationError.ts, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/OperationExecutionRecord.ts, libraries/rush-lib/src/logic/operations/OperationResultSummarizerPlugin.ts, libraries/rush-lib/src/logic/operations/test/OperationExecutionManager.test.ts, libraries/rush-lib/src/logic/operations/test/__snapshots__/OperationExecutionManager.test.ts.snap, libraries/rush-lib/src/pluginFramework/PhasedCommandHooks.ts, libraries/rush-lib/src/utilities/CollatedTerminalProvider.ts, libraries/rush-lib/src/utilities/Stopwatch.ts
Adds a new `afterExecuteOperations` hook to phased command execution. Uses the new hook to power the `--timeline` flag and to print the default result summary.
Adds a new `afterExecuteOperations` hook that provides the results of all executed commands and the overall execution result.
Refactors support for `--timeline` into a `ConsoleTimelinePlugin` that uses the new hook.
Refactors the default results summary into an `OperationResultSummaryPlugin` that uses the new hook.
Note that the timeline rendering has been migrated to be between the individual operation logs and the overall summary, so that failures are still the most immediate visible result at the end of command execution.
Fixes a bug in `Async` that allowed unbounded parallelism in async iterables.
Modifies `MockWritable` in …
=> [rush] After execute operations hook

common/changes/@microsoft/rush/workspace-versions-pnpmfile_2022-05-12-19-50.json, libraries/rush-lib/src/logic/pnpm/IPnpmfile.ts, libraries/rush-lib/src/logic/pnpm/PnpmfileConfiguration.ts
Exports a mapping of all workspace packages to their current versions to the pnpmfile shim.
Having the list of all packages that are part of the workspace and their latest versions can be useful for detecting external packages that refer back to workspace packages, and/or identifying if the package currently being examined is a workspace package (since local `package.json`s might not require changes).
Ran an install and verified the contents of the `common/temp/pnpmfileSettings.json`.
=> [rush] Export list of workspace packages to pnpmfile

common/changes/@microsoft/rush/phased-telemetry_2022-05-12-23-49.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/Telemetry.ts
Enables writing telemetry to disk and via the `flushTelemetry` hook for all phased commands, not just the default `build` and `rebuild`.
Telemetry will be written after the initial run and after all watch-mode reruns, with the following additional metadata:
```ts
interface IPhasedCommandTelemetry {
isInitial: boolean;
isWatch: boolean;
countAll: number;
countSuccess: number;
countSuccessWithWarnings: number;
countFailure: number;
countBlocked: number;
countFromCache: number;
countSkipped: number;
countNoOp: number;
}
```
Local runs with telemetry enabled.
=> [rush] Write telemetry in all phased commands

apps/api-extractor/src/api/ExtractorMessageId.ts, apps/api-extractor/src/collector/Collector.ts, apps/api-extractor/src/schemas/api-extractor-defaults.json, common/changes/@microsoft/api-extractor/better-ts-file-error_2022-04-10-00-42.json, common/reviews/api/api-extractor.api.md
A first stab at addressing https://github.com/microsoft/rushstack/issues/3328.
* Note that I decided to throw an error here instead of within `CompilerState.ts` (which is the earliest point we could throw an error) to make debugging easier for developers.
* Happy to bike-shed the error message itself a bit. I want to make sure it's clear for developers.
* We don't need to check if `this.program.getRootFileNames()` has any non-`.d.ts` files because there's earlier logic that filters these files out (see `CompilerState._generateFilePathsForAnalysis`).
I manually added some non-`.d.ts` files to the files that API Extractor processes and validated that that this error was thrown. Is it easy to add a test that verifies that API Extractor throws an error under certain situations? If not, then …
=> [api-extractor] Throw an error if API Extractor attempts to process non-.d.ts files

common/changes/@rushstack/heft-dev-cert-plugin/thelarkinn-issue-3421_2022-05-17-01-29.json, common/changes/@rushstack/heft-webpack5-plugin/thelarkinn-issue-3421_2022-05-17-00-30.json, heft-plugins/heft-dev-cert-plugin/src/DevCertPlugin.ts, heft-plugins/heft-webpack5-plugin/src/WebpackPlugin.ts
Fixes #3421 
(one part of it)
This PR removes deprecation warnings thrown by webpack-dev-server when using the webpack-5-rig. This PR provides support for the DevCertPlugin to allow it to use both webpack-dev-server v3 and v4 API's.  
I ran both the heft-webpack5-everything-test and heft-webpack4-everything-test and ensured that both dev servers launched successfully without any errors or deprecation warnings. (They both leverage the DevCertPlugin)
=> fixed usage of deprecated webpack-dev-server api

apps/api-extractor/src/analyzer/ExportAnalyzer.ts, apps/api-extractor/src/analyzer/TypeScriptInternals.ts, common/changes/@microsoft/api-extractor/users-chhol-fix-getResolvedModule-params_2022-05-25-17-20.json
…ypescript can resolve accurately
With the addition of `Node16` and `nodenext`, Typescript now requires the mode to be passed in order to accurately resolve modules. This PR adds support for `mode` thanks to the help of @DanielRosenwasser and does so in a way that returns undefined gracefully in case the fn isn't supported in older versions.
This resolves #3433.
1. Add a third param to getResolvedModule for `mode`
2. Create a new function `getModeForUsageLocation` which maps to the TS equivalent
3. Update all callers to gracefully look for the right mode and return undefined if necessary
Tested locally with Typescript 4.7.2 and the error is gone, API Extractor succeeds.
=> [API Extractor] Add missing required parameter for getResolvedModule to ensure that modules can resolve accurately with Node16/nodenext support

rush.json
It appears that PR https://github.com/microsoft/rushstack/pull/3428 was meant to publish a different major version of `@rushstack/module-minifier-plugin`.
However it has inadvertently created a new public NPM package:  https://www.npmjs.com/package/@rushstack/webpack5-module-minifier-plugin
And it also somehow broke the regular Rush publishing job:
[buildId=935](https://dev.azure.com/RushStack/GitHubProjects/_build/results?buildId=9352&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=36cda829-0688-5024-61b7-a8d0dbb1db49)
````
Invoking "rush publish --apply --publish --include-all --target-branch main --add-commit-details --set-access-level public"
---------------------------------------------------------------------------------------------------------------------------
Rush …
```
=> Temporarily disable publishing of "@rushstack/module-minifier-plugin"

common/config/azure-pipelines/npm-publish-rush.yaml
PR https://github.com/microsoft/rushstack/pull/3460 was trying to work around a publishing pipeline failure by disabling publishing of  `"@rushstack/module-minifier-plugin"`.  We need to disable the corresponding CI step as well.
=> Temporarily disable publishing of "module-minifier-plugin" (CI part)

common/changes/@rushstack/localization-utilities/localization-plugin-5_2022-06-07-01-12.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, common/reviews/api/localization-utilities.api.md, libraries/localization-utilities/package.json, libraries/localization-utilities/src/LocFileParser.ts, libraries/localization-utilities/src/Pseudolocalization.ts, libraries/localization-utilities/src/index.ts, libraries/localization-utilities/src/interfaces.ts, libraries/localization-utilities/src/parsers/parseLocJson.ts, libraries/localization-utilities/src/parsers/parseResJson.ts, libraries/localization-utilities/src/parsers/test/__snapshots__/parseLocJson.test.ts.snap, libraries/localization-utilities/src/parsers/test/__snapshots__/parseResJson.test.ts.snap, libraries/localization-utilities/src/parsers/test/parseLocJson.test.ts, libraries/localization-utilities/src/parsers/test/parseResJson.test.ts, libraries/localization-utilities/src/test/Pseudolocalization.test.ts, libraries/localization-utilities/src/test/__snapshots__/Pseudolocalization.test.ts.snap, libraries/localization-utilities/tsconfig.json
Removes the dependency on `decache` in favor of leveraging `vm.runInNewContext` to run each pseudolocalizer in its own context.
Exposes the resjson and loc.json parsers directly, in addition to the current code path through a highly opinionated dispatcher. The motivation being to allow webpack loaders to use the parsers on arbitrary content or on output of other custom loaders.
New unit tests
Usage in upcoming webpack 5 localization plugin
=> [localization-utilities] Expose parsers directly

apps/api-extractor/src/schemas/api-extractor-template.json, common/changes/@microsoft/api-extractor/patch-1_2022-06-13-19-22.json
.api.md file is generated in `temp` folder by default, not `etc`
`.api.md` file is generated in `temp` folder by default, not `etc`
N/A
I just ran api-extractor with default configuration and it created the report file in `temp` folder.
=> fix(template): fix wrongly documented default path for reportFolder

build-tests-samples/heft-serverless-stack-tutorial/tsconfig.json, build-tests-samples/heft-storybook-react-tutorial-storykit/package.json, common/changes/@microsoft/loader-load-themed-styles/disable-hoisting_2022-06-16-01-20.json, common/changes/@rushstack/hashed-folder-copy-plugin/disable-hoisting_2022-06-16-01-20.json, common/changes/@rushstack/heft-jest-plugin/disable-hoisting_2022-06-16-01-20.json, common/changes/@rushstack/heft-webpack4-plugin/disable-hoisting_2022-06-16-01-20.json, common/changes/@rushstack/localization-plugin/disable-hoisting_2022-06-16-01-20.json, common/changes/@rushstack/set-webpack-public-path-plugin/disable-hoisting_2022-06-16-01-20.json, common/changes/@rushstack/tree-pattern/disable-hoisting_2022-06-16-01-20.json, common/config/rush/.npmrc, common/config/rush/.pnpmfile.cjs, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, heft-plugins/heft-jest-plugin/src/JestPlugin.ts, heft-plugins/heft-webpack4-plugin/package.json, libraries/tree-pattern/package.json, webpack/hashed-folder-copy-plugin/package.json, webpack/loader-load-themed-styles/package.json, webpack/localization-plugin/package.json, webpack/module-minifier-plugin/package.json, webpack/set-webpack-public-path-plugin/package.json
Ensures that packages and external dependencies do not have phantom dependencies at build time. Any dependency not expressly declared in package.json (or corrected via pnpmfile) will not be available to projects.
Updates dependency footprints to ensure that all projects successfully build and execute in the presence of maximum installation strictness.
rush update --full --purge
rush retest --verbose
=> Disable hoisting for installs in the rushstack repository

common/changes/@microsoft/rush/build-cache-no-settings_2022-06-22-18-30.json, libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts
Fixes #3490
If no entry is provided for a given operation in `operationSettings`, assumes the build cache is disabled for that operation, rather than assuming caching is enabled with no outputs.
Removed the entry from heft-jest-plugin temporarily, ran a build and verified the warning message.
=> [rush-lib] Disable build cache for operations with no operationSettings

common/changes/@rushstack/ts-command-line/user-danade-Synonyms2_2022-06-15-22-36.json, common/reviews/api/ts-command-line.api.md, libraries/ts-command-line/src/index.ts, libraries/ts-command-line/src/parameters/BaseClasses.ts, libraries/ts-command-line/src/parameters/CommandLineDefinition.ts, libraries/ts-command-line/src/providers/CommandLineParameterProvider.ts, libraries/ts-command-line/src/providers/CommandLineParser.ts, libraries/ts-command-line/src/test/CommandLineParser.test.ts, libraries/ts-command-line/src/test/CommandLineRemainder.test.ts, libraries/ts-command-line/src/test/ConflictingCommandLineParser.test.ts, libraries/ts-command-line/src/test/__snapshots__/ConflictingCommandLineParser.test.ts.snap
Adds support for parameter scopes to ts-command-line parameters.
Parameter scopes allow a parameter to be mapped to both it's provided `longName` as well as a scope-prefixed synonym of the form `--<scope>:<longName>`. This allows for multiple parameters with the same `longName` to be specified, as long as they belong to different scopes. In this scenario, the parameters will _only_ be registered under the scope-prefixed name, avoiding parameter conflicts. This is particularly useful for dynamically-populated command-line parameters.
For example, if parameter `--parameter` is specified with scope `scope1`, and another `--parameter` is specified with scope `scope2`, then the parameter will be available on the command line as `--scope1:parameter` and `--scope2:parameter`.
The feature is …
=> [ts-command-line] Add support for parameter scopes

build-tests/localization-plugin-test-03/webpack.config.js, common/changes/@rushstack/heft-sass-plugin/typings-generator-outputs_2022-06-25-00-38.json, common/changes/@rushstack/localization-utilities/typings-generator-outputs_2022-06-25-00-31.json, common/changes/@rushstack/localization-utilities/typings-generator-outputs_2022-06-25-00-38.json, common/changes/@rushstack/typings-generator/typings-generator-outputs_2022-06-25-00-31.json, common/changes/@rushstack/typings-generator/typings-generator-outputs_2022-06-25-00-38.json, common/changes/@rushstack/webpack4-localization-plugin/typings-generator-outputs_2022-06-25-00-44.json, common/reviews/api/localization-utilities.api.md, common/reviews/api/typings-generator.api.md, common/reviews/api/webpack4-localization-plugin.api.md, heft-plugins/heft-sass-plugin/src/SassTypingsGenerator.ts, heft-plugins/heft-sass-plugin/src/SassTypingsPlugin.ts, heft-plugins/heft-sass-plugin/src/schemas/heft-sass-plugin.schema.json, heft-plugins/heft-sass-plugin/src/schemas/templates/sass.json, libraries/localization-utilities/src/TypingsGenerator.ts, libraries/typings-generator/src/TypingsGenerator.ts, libraries/typings-generator/src/index.ts, webpack/localization-plugin-4/src/LocalizationPlugin.ts, webpack/localization-plugin-4/src/interfaces.ts
Allows typings to be output to additional folders.
Added a test case in `localization-plugin-test-03`.
=> [typings-generator] Allow typings to be output to secondary folders.

common/changes/@microsoft/rush/set_default_max-install-attempts_to_1_2022-06-26-12-16.json, libraries/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap, libraries/rush-lib/src/logic/RushConstants.ts
Right now, rush update by default retries 3 times before failing. That is problematic, as most of the time it fails, it fails for a good reason that won't go away when retrying (e.g. missing peerDeps or mismatching versions).
Fixes #3482 
I reduced the max install attempts to 1.
There's a snapshot test that changed.
=> [rush-lib] Set default max install attempts to 1

apps/api-extractor/src/api/ExtractorConfig.ts, common/changes/@microsoft/api-extractor/user-danade-ApiExtractorConfigLoad_2022-06-15-22-45.json, common/reviews/api/api-extractor.api.md
Allow for loading the `ExtractorConfig` without validating existence of target typings.
There are some scenarios where loading up the API-Extractor configuration is required prior to the existence of the typings files that API Extractor sources from (such as obtaining output folder paths and ensuring they are empty). This PR adds the option `ignoreMissingConfigTargets` which can be passed into the `ExtractorConfig` options at load time to avoid validating the existence of the target files.
Forked off of PR https://github.com/microsoft/rushstack/pull/3468 where it was tested extensively against the rest of the Rushstack monorepo.
=> [api-extractor] Allow for loading the `ExtractorConfig` without validating existence of target typings

common/changes/@microsoft/loader-load-themed-styles/selarkin-correct-loader-load-theme-styles-hoisting_2022-06-28-02-07.json, webpack/loader-load-themed-styles/package.json
Similar to PR #3474, 
loader-load-theme-styles seems to be still causing hoisting issues in node_modules. Any dependency not expressly declared in package.json (or corrected via pnpmfile) will not be available to projects.
=> correct loader load theme styles hoisting

common/changes/@rushstack/webpack5-localization-plugin/localization-plugin-portable-resolution_2022-06-27-21-45.json, webpack/localization-plugin-5/src/LocalizationPlugin.ts
Ensures that the snapshot tests for the webpack 5 localization plugin work when running on Windows.
Modifies the path normalization algorithm to use POSIX path resolution if the value of the webpack `context` is a POSIX absolute path (i.e. starts with `/`).
Ran unit tests on Windows.
PR build runs unit tests on Linux.
=> [localization-plugin-5] Fix unit tests on Windows

apps/heft/src/stages/BuildStage.ts, common/changes/@rushstack/heft/fix-locales-parameter-quirk_2022-07-02-23-57.json
When I changed the `--locale` parameter to a string list parameter, I didn't only set the `locales` build property if the parameter was actually specified. This made updating dependent plugins somewhat confusing, as one could no longer just check if `locales` was `undefined` to see that none had been specified.
This PR changes that back to be more similar to how it worked before by setting an array of locales in the `locales` property iff locales were actually specified on the CLI.
=> [heft] Fix an issue with the --locale parameter.

common/changes/@microsoft/rush/separate-repo-analysis_2022-07-03-23-08.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/ProjectChangeAnalyzer.ts
Currently, running `rush build --to rush-lib` in this repo prints a log that looks like this (annotations added):
```
Rush Multi-Project Build Tool 5.75.0 - https://rushjs.io
Node.js version is 14.19.1 (LTS)
Found configuration in E:\code\rushstack8\rush.json
Starting "rush build"
Executing a maximum of 8 simultaneous processes...
==[ @rushstack/tree-pattern (build) ]=============================[ 1 of 23 ]==
<< ABOUT A 1 SECOND WAIT >>
"@rushstack/tree-pattern (build)" was restored from the build cache.
==[ @rushstack/eslint-patch (build) ]=============================[ 2 of 23 ]==
"@rushstack/eslint-patch (build)" was restored from the build cache.
==[ @rushstack/eslint-plugin-security (build) ]===================[ 3 of 23 ]==
"@rushstack/eslint-plugin-security (build)" was restored …
```
=> [rush] Separate the initial repo analysis from the first project's build.

apps/api-extractor/src/api/IConfigFile.ts, apps/api-extractor/src/schemas/api-extractor-template.json, common/changes/@microsoft/api-extractor/api-extractor-docs_2022-07-06-23-04.json
Moved all top-level settings to the same place in `api-extractor-template.json` and associated interfaces.
See associated https://github.com/microsoft/api-extractor.com-website/pull/49.
=> Update `api-extractor-template.json` and reorder some property signatures.

common/changes/@microsoft/rush/enelson-should-publish_2022-07-10-04-59.json, libraries/rush-lib/src/api/RushConfigurationProject.ts
More than once now, we've had a situation where a developer creates a new published library or tool in the monorepo, everything is reviewed and merged successfully, and then later that day the publishing pipeline fails -- because the new package has `shouldPublish: true`, but the `package.json` file (due to copy/paste fail) has `private: true`.
If Rush validated this immediately, the way it does several other fields in `rush.json`/`package.json`, it would be detectable before the PR is merged.
Followed basic pattern for existing validations inside the constructor.
I think this implementation fits the bill pretty well _if you use rush to publish as designed_.
This change could be a regression for users that use `shouldPublish: true` to activate rush changefile / changelog use cases, but …
=> [rush] Add validation for "shouldPublish" / "private: true"

build-tests/localization-plugin-test-01/package.json, build-tests/localization-plugin-test-02/package.json, build-tests/localization-plugin-test-03/package.json, common/changes/@rushstack/heft-dev-cert-plugin/bump-webpack-dev-server_2022-07-12-23-31.json, common/changes/@rushstack/heft-webpack4-plugin/bump-webpack-dev-server_2022-07-12-23-31.json, common/changes/@rushstack/heft-webpack5-plugin/bump-webpack-dev-server_2022-07-12-23-31.json, common/changes/@rushstack/rush-serve-plugin/bump-webpack-dev-server_2022-07-12-23-31.json, common/config/rush/.pnpmfile.cjs, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, heft-plugins/heft-dev-cert-plugin/package.json, heft-plugins/heft-dev-cert-plugin/src/webpack-dev-middleware-workaround.d.ts, heft-plugins/heft-webpack4-plugin/package.json, heft-plugins/heft-webpack4-plugin/src/WebpackPlugin.ts, heft-plugins/heft-webpack4-plugin/src/shared.ts, heft-plugins/heft-webpack5-plugin/package.json, rush-plugins/rush-serve-plugin/package.json
Upgrades to webpack-dev-server 4.9.3 in all 3 heft plugins to use a uniform version.
Upgrades express to 4.18.1 to match the version used by webpack-dev-server.
Local run of build-tests/heft-webpack4-everything-test in start mode.
=> Upgrade to webpack-dev-server@4.9.3

common/changes/@rushstack/debug-certificate-manager/upgrade-node-forge_2022-07-13-18-09.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, libraries/debug-certificate-manager/package.json
Upgrades the dependency on `node-forge` from `0.10.0` to `1.3.1` in `@rushstack/debug-certificate-manager`.
See above.
Untrusted and retrusted the dev cert using the dev cert plugin.
=> Upgrade node-forge to 1.3.1

common/changes/@microsoft/api-extractor-model/inheritance-docs-fixes_2022-07-20-21-52.json, common/reviews/api/api-extractor-model.api.md, libraries/api-extractor-model/src/mixins/ApiItemContainerMixin.ts, libraries/api-extractor-model/src/mixins/IFindApiItemsResult.ts
This PR is a follow-up to https://github.com/microsoft/rushstack/pull/3469 to improve `IFindApiItemsMessage` and fix two minor bugs with `findMembersWithInheritance`.
* Took a stab at addressing some of @octogonz's feedback left on https://github.com/microsoft/rushstack/pull/3469 post-merge re `IFindApiItemsMessage` messages.
* Graduated `IFindApiItemsMessageId` from `@beta` --> `@public`.
* **Bug fix:** Previously, when `findMembersWithInheritance` was run on a non-class/interface, it would return just the immediate members but then report an "unsupported kind" message. This was decided to not quite make sense per the conversation at https://github.com/microsoft/rushstack/pull/3469#discussion_r925967431. Thus, now when `findMembersWithInheritance` is run on a non-class/interface, it …
=> [api-extractor-model] Improve `IFindApiItemsMessage` and fix two minor bugs with `findMembersWithInheritance`

common/changes/@rushstack/webpack5-module-minifier-plugin/module-minifier-5-types_2022-07-27-00-57.json, webpack/module-minifier-plugin-5/package.json
Fixes the target of the `typings` field in `@rushstack/webpack5-module-minifier-plugin`.
Update required after the package publish target changed.
Local build.
=> [webpack5-module-minifier-plugin] Fix typings field

common/changes/@rushstack/node-core-library/runWithRetriesAsync_2022-08-01-01-22.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/Async.ts, libraries/node-core-library/src/index.ts, libraries/node-core-library/src/test/Async.test.ts, libraries/node-core-library/src/test/__snapshots__/Async.test.ts.snap
This is useful for operations that may fail occasionally like network requests or deletion of files/folders that may be locked by something like an editor.
=> [node-core-library] Add an Async.runWithRetriesAsync API to run and a retry an async function that may intermittently fail.

common/config/azure-pipelines/ci.yaml, rush.json
Node 12 is out of support, so this repo doesn't need to keep testing it.
=> Drop Node 12 support from this repo.

common/changes/@microsoft/rush/feng-set-ignore-compatibility-db-true-when-installation_2022-08-04-09-37.json, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/test/BaseInstallManager.test.ts, libraries/rush-lib/src/logic/test/ignoreCompatibilityDb/rush1.json, libraries/rush-lib/src/logic/test/ignoreCompatibilityDb/rush2.json, libraries/rush-lib/src/logic/test/ignoreCompatibilityDb/rush3.json
Background
When using different versions of pnpm to install in TTFE Monorepo. There are unwanted package changes in lockfile. The reason is that pnpm bundled @yarnpkg/package-extensions, which mysteriously installs unrelated packages.
Related issue:
[PNPM mysteriously installs unrelated packages · Issue #5132 · pnpm/pnpm (github.com)](https://github.com/pnpm/pnpm/issues/5132)
Zoltan, added a new "ignore-compatibility-db" settings to disable this behaviour 6.34.0 and 7.9.0-0
For Rush.js side, we do the following things:
"rush install/update" should always set "ignore-compatibility-db=true". It's unconditional because Rush's recommended way to use compatibility db would be to copy+paste the settings to "pnpm.packageExtensions" or "pnpmfile.cjs". (The rules must be stored in Git rather than …
=> [rush-lib] Fix Set ignore-compatibility-db=true when rush installation

common/changes/@microsoft/rush/feng-set-ignore-compatibility-db-true-when-installation_2022-08-08-05-48.json, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/test/BaseInstallManager.test.ts
Background
When using different versions of pnpm to install in TTFE Monorepo. There are unwanted package changes in lockfile. The reason is that pnpm bundled @yarnpkg/package-extensions, which mysteriously installs unrelated packages.
Related issue:
https://github.com/pnpm/pnpm/issues/5132
Zoltan, added a new "ignore-compatibility-db" settings to disable this behaviour 6.34.0 and 7.9.0-0
For Rush.js side, we do the following things:
"rush install/update" should always set "config.ignoreCompatibilityDb". Because Pnpm only support "ignore-compatibility-db" in .npmrc.  It's unconditional because Rush's recommended way to use compatibility db would be to copy+paste the settings to "pnpm.packageExtensions" or "pnpmfile.cjs". (The rules must be stored in Git rather than installed via NPM).
Rush …
=> [rush-lib] Fix Set config.ignoreCompatibilityDb when rush installation

common/changes/@microsoft/rush/watch-perf_2022-08-12-22-50.json, libraries/rush-lib/src/api/CommandLineConfiguration.ts, libraries/rush-lib/src/api/CommandLineJson.ts, libraries/rush-lib/src/cli/RushCommandLineParser.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/ProjectChangeAnalyzer.ts, libraries/rush-lib/src/schemas/command-line.schema.json
Makes the debounce timeout after detecting file changes in watch mode configurable via `command-line.json` on a per-command basis. Default value is 1 second.
Adds a configuration value `debounceMilliseconds` in the `watchOptions` section of phased commands. This value (default `1000`) sets how long after the last detected file system event the watcher will wait before starting a build. If another file system event fires during the timeout, the timer gets reset.
Configured the `rush start` command in `rushstack` to have a higher timeout (10 seconds) and verified the latency. Then tested with a lower timeout (100 milliseconds) and verified the quicker response.
=> [rush] Allow configuration of watch debounce timeout

common/changes/@rushstack/node-core-library/fix-2070_2022-07-28-18-09.json, libraries/node-core-library/src/PackageJsonLookup.ts, libraries/node-core-library/src/test/PackageJsonLookup.test.ts, libraries/node-core-library/src/test/test-data/example-subdir-package-no-name/package.json, libraries/node-core-library/src/test/test-data/example-subdir-package-no-name/src/ExampleFile.txt, libraries/node-core-library/src/test/test-data/example-subdir-package-no-name/src/package.json
Fixes #2070 
PackageJsonLookup is erroneously presuming that all package.json files include a `"name"` field, and will complain when attempting to load a package.json file that does not include that field.
In the [npm docs on the file format](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#name), it's quite clear that the name+version requirements only apply to published packages:
> If you don't plan to publish your package, the name and version fields are optional.
This means that when e.g. a third-party dependency follows the guidance given for the `"type"` field in the [Node.js documentation](https://nodejs.org/api/packages.html#type), it's not possible to successfully run api-extractor.
To fix this, each package.json file is loaded during lookup before returning it as …
=> [node-core-libary] Update `PackageJsonLookup` to only resolve to `package.json` files that contain a `"name"` field.

common/changes/@microsoft/rush/octogonz-stricter-project-tag-names_2022-08-20-00-01.json, libraries/rush-lib/assets/rush-init/rush.json, libraries/rush-lib/src/api/RushConfigurationProject.ts, libraries/rush-lib/src/schemas/rush.schema.json
PR https://github.com/microsoft/rushstack/pull/3300 recently introduced support for project tags.  However the syntax for tag names is not strict enough.
**The old RegExp:** `"^[A-Za-z0-9_@/.$-]+$"`
This allows syntaxes such as:
```
rush build --to tag:.
rush build --to tag:@
rush build --to tag://
rush build --to tag:CrAzYcAsE
rush build --to tag:--cli-case
rush build --to tag:camelCase
rush build --to tag:$PATH
```
This is bad experience for users:
- If I'm defining my first tag in **rush.json**, what should it look like?  `MY_TAG`? `myTag`? `MyTag`? `my-tag`? We're not too opinionated about which syntax to choose for our monorepo, but we do want a ***consistent*** syntax everywhere.  The unopinionated RegExp pushes this design problem onto me as a user. My team has to discuss it and …
=> [rush-lib] Stricter syntax for Rush project tag names

apps/api-extractor/src/collector/MessageRouter.ts, common/changes/@microsoft/api-extractor-model/node-default-target_2022-08-22-22-10.json, common/changes/@microsoft/api-extractor/node-default-target_2022-08-22-22-10.json, common/changes/@rushstack/node-core-library/node-default-target_2022-08-22-22-10.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, common/reviews/api/node-core-library.api.md, libraries/api-extractor-model/src/mixins/ApiItemContainerMixin.ts, libraries/node-core-library/package.json, libraries/node-core-library/src/LegacyAdapters.ts, libraries/node-core-library/src/Sort.ts
Reroutes `LegacyAdapters.sortStable` to always call `Array.prototype.sort`, since node 12 and below are EOL and all currently maintained LTS versions use stable sorting.
Disables the node version check to remove the dependency on `semver` and `timsort`.
Unit tests.
=> [node-core-library] Remove node < 11 sort

common/changes/@microsoft/rush/package-json-validation_2022-07-28-22-42.json, common/changes/@rushstack/node-core-library/package-json-validation_2022-07-28-22-42.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/JsonFile.ts, libraries/node-core-library/src/index.ts, libraries/rush-lib/src/api/RushConfigurationProject.ts
This PR seeks to solve 2 issues:
- rush repo components' package.json version not in semver format fails when listed as a dependency with `workspace:*` in another project - https://github.com/microsoft/rushstack/issues/2678
- when running `rush update` and there are parsing errors in a component's package.json, pnpm does not provide stderr/stdio feedback - only exit code 1, which is not descriptive to the user. The `rush update` error message is `ERROR: Error: The command failed with exit code 1`
- The component version is manually checked for being in semver format after `package.json` is loaded.
- Package.json parsing of rush repos' subprojects' validates strict JSON format - no comments, syntactically correct.
- building a project containing 2 components A and B, where A imports B's …
=> [rush-lib] components package.json JSON format validation & version adherence to semver validation

common/changes/@microsoft/rush/enhanced-telemetry_2022-08-23-22-57.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/index.ts, libraries/rush-lib/src/logic/Telemetry.ts, libraries/rush-lib/src/logic/test/Telemetry.test.ts, libraries/rush-lib/src/utilities/Utilities.ts
Adds additional information to the standard rush telemetry files, namely detailed machine architecture info (core count, OS, CPU model, RAM), and the operation graph.
Carve out from #3589 to separate concerns.
Example output from `rush retest -t eslint-plugin`:
```json
[
{
"name": "retest",
"durationInSeconds": 14.688612599968911,
"result": "Succeeded",
"extraData": {
"command_from": "false",
"command_impactedBy": "false",
"command_impactedByExcept": "false",
"command_only": "false",
"command_to": "true",
"command_toExcept": "false",
"command_fromVersionPolicy": "false",
"command_toVersionPolicy": "false",
"--timeline": "false",
"--to": "eslint-plugin",
"--to-except": "",
"--from": "",
"--only": "",
"--impacted-by": "",
"--impacted-by-except": "",
"--to-version-policy": "", …
```
=> [rush-lib] Enhance telemetry with individual operation times, graph, and machine info

common/changes/@microsoft/rush/thelarkinn-issue-3598_2022-08-25-16-14.json, libraries/rush-lib/src/logic/PackageJsonUpdater.ts
Fixes #3598 
This PR Updates doRushAddAsync to include mismatches (to be updated) that come from a VersionMismatchFinderCommonVersions instance instead of just VersionMismatchFinderProject instances. 
This allows users to use `rush add -p someproject --make-consistent` and include common-versions.json as a file to be updated when there are mismatches inside of preferredVersions.   
* Add a version of `somepackage` inside of common-versions.json / preferredVersions
* Run `rush add -p somepackage --make-consistent` for a later version of the package than specified in common-versions
* Ensure that common-versions.json was updated after running the command
=> [rush] Ensure common-versions file gets updated from rush add

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@rushstack/eslint-plugin-security/issue-3567_2022-08-30-01-25.json, common/changes/@rushstack/eslint-plugin/issue-3567_2022-08-30-01-25.json, common/config/rush/.npmrc, eslint/eslint-plugin-security/src/no-unsafe-regexp.test.ts, eslint/eslint-plugin-security/tsconfig.json, eslint/eslint-plugin/src/hoist-jest-mock.test.ts, eslint/eslint-plugin/src/no-new-null.test.ts, eslint/eslint-plugin/src/typedef-var.test.ts, rush.json
=> use pnpm 7.x

common/changes/@microsoft/rush/will-rush-add-nested-package_2022-08-26-22-10.json, common/changes/@rushstack/node-core-library/will-rush-add-nested-package_2022-08-30-21-35.json, libraries/node-core-library/config/heft.json, libraries/node-core-library/src/test/LockFile.test.ts, libraries/rush-lib/src/api/RushConfiguration.ts
This loop in the `tryGetProjectForPath()` function assumes that a project folder cannot be nested under another project folder. In special cases it is possible for this to happen and if it does, depending on the order the root level project may be selected instead of the intended nested project.
Packages are now sorted in decreasing length of their paths so nested packages are now located before root level packages.
Manually tested on the TikTok monorepo, resolves the issue that was originally discovered.
=> [rush-lib] Fix issue with adding packages to nested project

common/changes/@rushstack/heft-jest-plugin/user-danade-DisableJestCacheEnvVar_2022-08-30-23-52.json, heft-plugins/heft-jest-plugin/includes/jestScriptTransformerPatch.js
Hides the disabling of Jest cache read/writes behind an environment variable, to avoid touching the Jest install unless explicitly requested. Follow-on PR for #3606
=> [heft-jest-plugin] Hide disabling Jest cache behind an environment variable

common/changes/@microsoft/rush/verify-store-integrity_2022-08-31-01-09.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/EnvironmentConfiguration.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
Adds an environment variable `RUSH_PNPM_VERIFY_STORE_INTEGRITY` that can be used to enable or disable PNPM's store integrity verification checks during the installation process.
Reasons to disable are for performance, or if you are deliberately tampering with your local PNPM store for test purposes.
Local runs in a test repository.
=> [rush-lib] Add RUSH_PNPM_VERIFY_STORE_INTEGRITY environment variable

common/changes/@microsoft/rush/before-install-hook_2022-09-02-23-03.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/actions/InstallAction.ts, libraries/rush-lib/src/cli/actions/UpdateAction.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/pluginFramework/RushLifeCycle.ts
Adds a new top-level hook "beforeInstall" to the Rush plugin SDK. This hook is invoked between the Rush install setup checks and when it actually invokes the package manager.
This hook can be used to, for example, impose additional validation of the inputs to the package manager, such as bounding the maximum number of versions of a package in `common-versions.json` or similar.
Local runs of `rush install`
=> [rush-lib] Add "beforeInstall" hook

.gitignore, common/changes/@microsoft/rush/octogonz-gitignore-intellij_2022-09-12-22-50.json, libraries/rush-lib/assets/rush-init/[dot]gitignore
This work was split off from PR https://github.com/microsoft/rushstack/pull/3602
Properly tracking IntelliJ project settings in Git requires a [fairly complex](https://github.com/github/gitignore/blob/main/Global/JetBrains.gitignore) `.gitignore` recipe based on [the JetBrains docs](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839).
However, [this thread](https://t.co/8T3C5Dejjo) makes a reasonable case that `.idea` and `*.iml` can be completely ignored in a typical Git repository, unless the developers specifically want to do work to support shared templates.
Thus I agree with the @fwienber's approach from PR https://github.com/microsoft/rushstack/pull/3602.  And furthermore, I think it's a helpful default for the `rush init` template.
=> Update the .gitignore template to ignore files generated by IntelliJ IDEA

common/changes/@microsoft/rush/fix-parallelism-percentage_2022-09-12-23-51.json, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts
Currently passing a percentage to the `--parallelism` sets max parallelism to `NaN`, which is treated as `Infinity`.
Fixes the parser to set it to a finite number of cores.
Parser was using the wrong parsed value in the calculation.
Local run of `rush build -v -p 99%`, confirmed received n-1 cores. Passed other percentage values and confirmed the corresponding core count.
=> [rush-lib] Fix parallelism percentage parsing

common/changes/@rushstack/eslint-patch/eslint-patch-fallback_2022-09-14-07-30.json, eslint/eslint-patch/src/modern-module-resolution.ts
Projects that rely on eslint's original behaviour may break if `eslint-patch` is introduced as a dependency anywhere in its dependency tree. Projects build atop [Create React App](https://github.com/facebook/create-react-app) for example (the most recent major release adds `eslint-patch` as a dependency).
This change prevents such projects from breaking.
As an example of a configuration that would break, consider this `.eslintc` that is shared between two or more projects:
```yaml
extends:
- plugin:mocha/recommended
plugins:
- mocha
```
Assuming each project has an eslintrc file that extends this one, you could then run eslint (separately installed in each project) and eslint would load the mocha plugin installed for each project.
I doubt this change will cause issues for many projects, …
=> [eslint-patch] Use original resolver if patched resolver fails.

common/changes/@microsoft/rush/update-azure-identity_2022-09-15-00-22.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, common/reviews/api/rush-azure-storage-build-cache-plugin.api.md, rush-plugins/rush-azure-storage-build-cache-plugin/package.json, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureStorageAuthentication.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureStorageBuildCacheProvider.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/RushAzureInteractiveAuthPlugin.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/RushAzureStorageBuildCachePlugin.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/index.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/test/AzureStorageBuildCacheProvider.test.ts
This PR updates the `@azure/` packages in `rush-azure-storage-build-cache-plugin` to remove a hardcoded GUID.
[Version `1.2.0`](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/CHANGELOG.md#changes-since-the-latest-12-beta) of the `@azure/identity` changed the constructor for the `DeviceCodeCredential` class to make the Client ID optional. Previously, it was required.
https://github.com/microsoft/rushstack/pull/2647 introduced this GUID when we downgraded to version `1.0.0` of `@azure/identity` to remove a dependency on `keytar`. Now that version `2.0.0` has been released, we can upgrade and remove hardcoded data.
Tested in a Rush repo that uses authenticated Azure Storage.
=> [rush] Update the @azure/identity and @azure/storage-blob packages to remove a hardcoded GUID.

common/changes/@microsoft/rush/will-fix-last-install-flag_2022-09-13-21-16.json, libraries/rush-lib/src/logic/Autoinstaller.ts
Fixes #2987 
(summary from issue)
The problem is that Rush tracks installation status using the file common/autoinstallers/rush-prettier/.rush/temp/last-install.flag; as long as this file appears up to date, Rush will assume that the node_modules folder is in good shape.
👉 This conflicts with commonplace intuition that node_modules folders are always safe to delete.
We now use a similar outdated check to the install check in [BaseInstallManager.ts](https://github.com/microsoft/rushstack/blob/3516f99350aea88245a9d40fa1e82d3069e92c06/apps/rush-lib/src/logic/base/BaseInstallManager.ts#L285-L289) to detect if the node_modules folder is outdated or missing
Manually tested with steps provided in the issue
=> [rush] Fix last install flag not updating autoinstallers

common/changes/@microsoft/rush/fix-repo-state_2022-09-23-01-42.json, common/changes/@rushstack/package-deps-hash/fix-repo-state_2022-09-23-01-39.json, libraries/package-deps-hash/src/getRepoState.ts, libraries/rush-lib/src/logic/Git.ts
Fixes detection of a Git repository in `@microsoft/rush-lib` when the current working directory is not in the Rush workspace.
Fixes `getRepoState` when the current working directory is not in the Git working tree.
Modifies the call in `Git.ts` to pass in `rushConfiguration.rushJsonFolder` as the starting directory for locating the Git repository.
Modifies `getRepoState` to correctly set the working directory when invoking `git hash-object`. 
Invoked `PackageChangeAnalyzer` against a Rush repository when the current working directory was outside the repository.
=> [rush][package-deps-hash] Fix Git operations when cwd is in the Rush repo

apps/heft/src/operations/runners/LifecycleOperationRunner.ts, apps/heft/src/pluginFramework/HeftLifecycle.ts, apps/heft/src/pluginFramework/HeftPhaseSession.ts, apps/heft/src/pluginFramework/InternalHeftSession.ts
Fixes loading of lifecycle plugins in Heft.
Loading a lifecycle plugin would fail due to attempting to parse out the plugin parameters before the CLI had been fully initialized. This change defers loading of the plugin parameters until the plugins themselves are being loaded and applied, since the parameters are not required until then.
Tested locally in external repo via symlinked node_modules folder.
=> [prerelease][heft] Fix loading of lifecycle plugins

common/changes/@microsoft/rush/node-tar-cleanup_2022-09-26-20-33.json, libraries/rush-lib/src/logic/buildCache/ProjectBuildCache.ts
Fallback to the node implementation of `tar` in practice seems to only occur when the tarball is invalid, unless the `tar` is not on `PATH`. This results in restoring from corrupt cache entries and producing an invalid build result.
This PR removes the fallback to node `tar`.
Fixes #3454
Fixes #2827
Completely disables fallback path to node implementation of `tar`. Updates logged warning to suggest ensuring that `tar` is on `PATH` or setting `RUSH_TAR_EXECUTABLE_PATH` to point to `tar` in the event that the binary cannot be found.
This is the normal state for most builds.
=> [rush] Remove node tar fallback

common/changes/@rushstack/heft-config-file/heft-config-file-schema-object_2022-09-27-21-34.json, common/reviews/api/heft-config-file.api.md, libraries/heft-config-file/src/ConfigurationFile.ts, libraries/heft-config-file/src/index.ts, libraries/heft-config-file/src/test/ConfigurationFile.test.ts, libraries/heft-config-file/src/test/__snapshots__/ConfigurationFile.test.ts.snap
Adds a constructor option to the `ConfigurationFile` object to allow a schema object instead of the path to a schema file to be passed in. This allows a project that uses `ConfigurationFile` to be webpacked.
Added a unit test.
=> [heft-config-file] Allow a schema object to be passed to the ConfigurationFile constructor instead of the path to a schema file.

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@microsoft/rush/fix-rush-test-on-windows_2022-09-27-21-44.json, libraries/rush-lib/src/api/test/RushConfiguration.test.ts
There is a test in `rush-lib` that relies on the existence of a forward slash. This PR fixes that.
=> [rush] Fix a rush-lib test on Windows.

common/changes/@microsoft/loader-load-themed-styles/remove-namedExport_2022-09-28-01-13.json, webpack/loader-load-themed-styles/README.md, webpack/loader-load-themed-styles/src/LoadThemedStylesLoader.ts, webpack/loader-load-themed-styles/src/test/LoadThemedStylesLoader.test.ts
This option isn't used and will be superseded by ES6 support soon.
=> [loader-load-themed-styles] Remove the namedExport option.

common/changes/@microsoft/rush/feat-operation-metadata_2022-09-26-12-16.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/index.ts, libraries/rush-lib/src/logic/Telemetry.ts, libraries/rush-lib/src/logic/buildCache/ProjectBuildCache.ts, libraries/rush-lib/src/logic/operations/IOperationExecutionResult.ts, libraries/rush-lib/src/logic/operations/IOperationRunner.ts, libraries/rush-lib/src/logic/operations/OperationExecutionRecord.ts, libraries/rush-lib/src/logic/operations/OperationStateFile.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts, libraries/rush-lib/src/utilities/Stopwatch.ts
This PR makes Rush.js restores the duration of the same operation without cache hit and log `durationInSecondsWithoutCache` in operationResult
1. When operation doesn't hit cache, Rush.js creates a `.rush/temp/operation/<identifier>/state.json` which contains `durationInSecondsWithoutCache`.
2. Set the state.json in Step 1 as an additional output file when create project build cache tarball.
3. When operation hit cache, read the restored state.json and set `durationInSecondsWithoutCache` as one of the property of operationResult
Test with local build cache in rushstack repo steps:
1. Enable telemetry by setting up `"telemetryEnabled": true` in rush.json
2. Run `rm -rf common/temp/build-cache`
3. Run `node rush-lib/lib/start.js build -v --to tree-pattern`
a. …
=> [rush] restore the duration of the same operation without cache hit as telemetry data

common/changes/@microsoft/rush/move-parallelism-parse_2022-09-30-22-57.json, libraries/rush-lib/src/cli/actions/BaseInstallAction.ts, libraries/rush-lib/src/cli/actions/InstallAction.ts, libraries/rush-lib/src/cli/actions/ListAction.ts, libraries/rush-lib/src/cli/parsing/ParseParallelism.ts, libraries/rush-lib/src/cli/parsing/SelectionParameterSet.ts, libraries/rush-lib/src/cli/parsing/test/ParseParallelism.test.ts, libraries/rush-lib/src/cli/parsing/test/__snapshots__/ParseParallelism.test.ts.snap, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/test/OperationExecutionManager.test.ts
Move the parsing of the `parallelism` parameter out of `OperationExecutionManager` and into a dedicated parsing function. Moves responsibility for invoking the parsing function to `PhasedScriptAction`, since CLI parsing is not the responsibility of the execution engine.
General cleanup.
Moved unit tests.
Manual invocation of `rush build` with parallelism parameter values.
=> [rush] Move parallelism parsing to cli

common/changes/@microsoft/rush/shallow-clone-error-message_2022-10-03-19-56.json, libraries/rush-lib/src/logic/Git.ts
Addresses https://github.com/microsoft/rushstack/issues/3663.
This change adds an error message when Rush tries to find the merge base during an operation like `rush change` and can't find the merge base. Currently, Rush gives the cryptic
```
ERROR: The command failed with exit code 1
```
message. With this change, the error message will read
```
Unable to determine merge base for branch "<BRANCH NAME>". This can occur if the current clone is a shallow clone. If this clone is running in a CI pipeline, check your pipeline settings to ensure that the clone depth includes the expected merge base. If this clone is running locally, consider running "git fetch --deepen".
```
Tested on a shallow clone.
=> [rush] Add a more useful error message in cases when a merge base for rush change cannot be determined.

common/changes/@microsoft/rush/install-run-lockfile_2022-10-04-00-27.json, libraries/rush-lib/src/scripts/install-run-rush.ts, libraries/rush-lib/src/scripts/install-run.ts
Provides the ability to invoke `install-run.js` and `install-run-rush.js` with a lockfile for stable CI installation.
Set `INSTALL_RUN_LOCKFILE_PATH` for the general `install-run.js` script, or `INSTALL_RUN_RUSH_LOCKFILE_PATH` to scope specifically to `install-run-rush.js`.
Code was used previously to pin a known good version of `node-fetch`.
=> [rush] Support passing a lockfile to install-run

common/changes/@rushstack/rush-serve-plugin/serve-file_2022-10-03-22-06.json, rush-plugins/rush-serve-plugin/src/RushProjectServeConfigFile.ts, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts, rush-plugins/rush-serve-plugin/src/schemas/rush-project-serve.schema.json
Extends `rush-project-serve.json` configuration to allow serving a specific file, not just entire directories.
Use the `projectRelativeFile` field instead of `projectRelativeFolder` to serve a file instead of a directory. A primary use case is to configure some entry point page to be served from `/` (root).
Used a local repository and configured a file to be served from root.
=> [rush-serve-plugin] Allow serving single files

common/changes/@microsoft/rush/pnpm-config-environment_2022-10-06-21-55.json, libraries/rush-lib/src/logic/pnpm/test/PnpmOptionsConfiguration.test.ts, libraries/rush-lib/src/logic/pnpm/test/jsonFiles/pnpm-config-overrides.json, libraries/rush-lib/src/schemas/pnpm-config.schema.json
Adds the missing `environmentVariables` entry to the schema for `pnpm-config.json`, so that it can be used when transcribing from an existing `rush.json` `pnpmOptions` field.
The code path to use the field already exists, it was simply missing from the schema and therefore failing schema validation.
Added unit test coverage of extracting the value from `pnpm-config.json`.
=> [rush] environmentVariables in pnpm-config schema

common/autoinstallers/rush-prettier/package.json, common/autoinstallers/rush-prettier/pnpm-lock.yaml, common/changes/@microsoft/rush/validate-change-type_2022-10-09-02-51.json, common/changes/@rushstack/webpack4-module-minifier-plugin/validate-change-type_2022-10-09-21-55.json, libraries/rush-lib/src/logic/PublishUtilities.ts, libraries/rush-lib/src/logic/buildCache/ProjectBuildCache.ts, libraries/rush-lib/src/logic/pnpm/PnpmOptionsConfiguration.ts, webpack/webpack4-module-minifier-plugin/src/ModuleMinifierPlugin.ts
We recently discovered an issue in Rush where a changefile with a missing or malformed "type" property would cause `rush version` to produce an invalid `changelog.json`, which will fail to parse.
Adding schema validation to the step that loads the changefiles proved difficult because `rush version` writes and then reads and deletes a changefile that does not conform to the schema. This is a stopgap measure until version bumping and publishing is redesigned.
Tested by running `rush version --bump --version-policy rush` on this repo on branches both with and without malformed changefiles.
=> [rush] Validate the change type in changefiles during publishing.

common/changes/@microsoft/rush/project-watcher-undefined_2022-10-10-18-23.json, libraries/rush-lib/src/logic/ProjectWatcher.ts
Gracefully handle the scenario when a project contains no Git tracked files in the ProjectWatcher or Git information is not available.
Fixes #3686 
Removes the non-null assertions and replaces with explicit handling of either old or new project tracked files being `undefined`.
=> [rush] Handle ProjectWatcher edge case

build-tests/heft-sass-test/src/ExampleApp.tsx, build-tests/heft-sass-test/src/stylesAltSyntax.global.scss, common/changes/@rushstack/heft-sass-plugin/sass-non-module_2022-10-11-22-35.json, common/changes/@rushstack/node-core-library/sass-non-module_2022-10-11-22-24.json, heft-plugins/heft-sass-plugin/src/SassProcessor.ts, heft-plugins/heft-sass-plugin/src/schemas/heft-sass-plugin.schema.json, libraries/node-core-library/src/Sort.ts
Adds a new property to the `heft-sass-plugin` configuration called `nonModuleFileExtensions`. Input files that end in these extensions (and do not match a more specific extension from `fileExtensions`, which are the file extensions for SCSS modules) will be treated as non-module SCSS files: the CSS modules transform will be skipped and the typings will not contain any names.
Also fixed a bug encountered in `Sort.sortMapKeys` wherein the comparer was run between the first element of the collection and `undefined`.
Added test case to `heft-sass-test` for a file with `.global.scss` as the file extension. Validated that the typings for it don't have any names.
=> [heft-sass-plugin] Support non-module SCSS files via "nonModuleFileExtensions"

.github/workflows/ci.yml, apps/api-extractor/src/generators/ApiModelGenerator.ts, build-tests/api-extractor-scenarios/etc/referenceTokens/api-extractor-scenarios.api.json, common/changes/@microsoft/api-extractor/fix-path-regression_2022-10-17-02-48.json
There is currently an issue where the `fileUrlPath` gets populated with something that looks like `../E:\\code\\rushstack\\build-tests\\api-extractor-scenarios\\src\\apiItemKinds\\classes.ts` on Windows. This is probably due to a recent change in the TypeScript compiler's behavior.
This PR fixes this using the platform default `path.relative` behavior and then explicitly converting slashes in the path.
Built and made sure that the `*.api.json` files produed by `api-extractor-scenarios` matched the old behavior.
=> [api-extractor] Fix an issue with the 'fileUrlPath' on Windows.

build-tests/heft-webpack5-everything-test/webpack.dev.config.js, common/changes/@rushstack/debug-certificate-manager/serve-cert-subjects_2022-10-04-22-25.json, common/changes/@rushstack/debug-certificate-manager/serve-cert-subjects_2022-10-24-21-40.json, common/changes/@rushstack/heft-dev-cert-plugin/serve-cert-subjects_2022-10-13-23-30.json, common/changes/@rushstack/heft-webpack4-plugin/serve-cert-subjects_2022-10-24-22-29.json, common/changes/@rushstack/heft-webpack5-plugin/serve-cert-subjects_2022-10-24-22-29.json, common/changes/@rushstack/rush-serve-plugin/serve-cert-subjects_2022-10-13-23-30.json, common/reviews/api/debug-certificate-manager.api.md, heft-plugins/heft-dev-cert-plugin/src/DevCertPlugin.ts, heft-plugins/heft-webpack4-plugin/src/WebpackPlugin.ts, heft-plugins/heft-webpack5-plugin/src/WebpackPlugin.ts, libraries/debug-certificate-manager/src/CertificateManager.ts, libraries/debug-certificate-manager/src/CertificateStore.ts, libraries/debug-certificate-manager/src/index.ts, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts
Changes the certificate manager to generate two certificates: a trusted CA certificate, and a separate TLS certificate signed by that trusted CA certificate.
Adds critical constraints to both the CA certificate and the TLS end entity certificate to restrict their usage to only the intended purposes.
Modifies the tools that consume the TLS certificates to extract the `subjectAltNames` extension and use the values contained within to set the allowed host fields for TLS servers.
The private key for the CA certificate gets deleted immediately after being used to sign the TLS certificate, to prevent the CA from being used to sign other certificates.
Used the `heft-webpack5-everything-test` build test in serve mode.
=> [certificate-manager] Revise self-signed TLS certificate generation and usage

build-tests/heft-sass-test/src/ExampleApp.tsx, build-tests/heft-sass-test/src/_forwardSyntaxStyles.scss, build-tests/heft-sass-test/src/styles.sass, build-tests/heft-sass-test/src/stylesUseAltSyntax.scss, build-tests/heft-sass-test/src/stylesUseSyntax.sass, build-tests/heft-sass-test/src/utilities/configurableModule.sass, build-tests/heft-sass-test/src/utilities/useSyntaxRelativeImport.sass, common/changes/@rushstack/heft-sass-plugin/replace-sass-implementation-for-heft-sass-plugin_2022-10-21-20-09.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, heft-plugins/heft-sass-plugin/package.json, heft-plugins/heft-sass-plugin/src/SassProcessor.ts
This PR updates sass transpiler to dart-sass.
- Update SassProcessor to use compileStringAsync of dart sass to transpile sass files.
- Update heft-sass-tests to test new `@use` syntax of sass.
- Checked that heft-sass-test builds and renders normally.
- Changed `@import` to `@use` in styles.sass file and checked that the sass code is converted to css well.
=> [heft-sass-plugin] Replace sass implementation to dart sass

common/changes/@rushstack/heft-jest-plugin/enelson-heft-jest-cache_2022-10-30-12-13.json, heft-plugins/heft-jest-plugin/config/rush-project.json
Enable build caching for heft-jest-plugin (via rush-project).
This project wasn't using the rig, because it would cause a circular dependency, but we can still use the same build cache settings.
- Tested locally for build & test.
=> [rush] Turn on build cache for heft-jest-plugin

common/changes/@rushstack/debug-certificate-manager/debug-cert-remove-import-lazy_2022-11-02-23-51.json, libraries/debug-certificate-manager/src/CertificateManager.ts
Removes usage of `Import.lazy` in favor of a standard `await import()` call so that `@rushstack/debug-certificate-manager` may be bundled.
Local builds using the tool.
=> [certificate-manager] Remove Import.lazy

common/changes/@rushstack/ts-command-line/user-danade-OptionalOnDefineUnscopedParameters_2022-11-08-00-20.json, common/reviews/api/ts-command-line.api.md, libraries/ts-command-line/src/providers/ScopedCommandLineAction.ts
A recent change allowed for `CommandLineAction.onDefineParameters` to not be specified on the implementing class. This change implements the same change, but with the equivalent `ScopedCommandLineAction.onDefineUnscopedParameters` method.
=> [ts-command-line] Make `onDefineUnscopedParameters` non-abstract and optional, mirroring `onDefineParameters`

common/changes/@microsoft/rush/enelson-setupaction_2022-11-09-19-52.json, libraries/rush-lib/src/cli/actions/BaseRushAction.ts
If you publish rush plugins to a private NPM registry, then use them, you need to download them in an autoinstaller.
But, if a new user doesn't have credentials for the private NPM registry yet, they need to use `rush setup` (if configured), which blows up because the plugins can't be downloaded.
This PR adds `setup` to the list of magic actions that do not fail on plugin errors.
- Add `setup` to the pre-existing list of actions.
- Tested locally in our repo -- with this change, the error message is still printed above, but it then continues on and asks to setup the credentials interactively.
=> [rush] "rush setup" should work even if plugins can't be loaded

common/changes/@microsoft/rush/enelson-credentialtype_2022-11-10-03-49.json, libraries/rush-lib/assets/rush-init/common/config/rush/artifactory.json, libraries/rush-lib/src/logic/setup/ArtifactoryConfiguration.ts, libraries/rush-lib/src/logic/setup/SetupPackageRegistry.ts, libraries/rush-lib/src/schemas/artifactory.schema.json
Add a new option, `credentialType`, to the artifactory setup schema for the `rush setup` command.
Today, the default behavior of `rush setup` is to ask for the jFrog user's API token, and then trade it in for an NPM password. This is a good default, as the API token can have all kinds of unrelated scopes and privileges on many different jFrog registries, whereas the password that we get after "trading it in" is scoped just to the NPM registry we are talking with.
However, in some cases, a monorepo maintainer might prefer that all users use their _API tokens_ instead of their NPM password (especially if the developers are also using that token for access to other jFrog registries as well).
- Tested new option locally with both the `password`, `authToken`, and missing (not defined) options.
=> [rush] Rush setup can use "_authToken" instead of "_password"

common/changes/@rushstack/debug-certificate-manager/cert-fixes_2022-11-11-23-28.json, common/changes/@rushstack/heft-dev-cert-plugin/cert-fixes_2022-11-11-23-28.json, common/changes/@rushstack/rush-serve-plugin/cert-fixes_2022-11-11-23-28.json, heft-plugins/heft-dev-cert-plugin/src/DevCertPlugin.ts, libraries/debug-certificate-manager/src/CertificateManager.ts, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts
Updates consumers of debug-certificate-manager to serve the CA certificate in addition to the TLS certificate.
Updates debug-certificate-manager to mark the X.509 `issuerAltName` extension as non-critical, since Firefox doesn't understand it.
Local debugging with newly generated certs in various browsers. Chrome, Edge, Firefox.
=> Fix regression with localhost certificates

common/changes/@microsoft/rush/enelson-autoinstaller_2022-11-12-03-19.json, libraries/rush-lib/src/logic/Autoinstaller.ts
If an error occurs while autoinstaller is prepared, a lockfile is left behind, which makes updating autoinstallers a little more annoying.
This is specifically an issue for your "rush-plugins" autoinstaller, if you have one, because every time you run "update-autoinstaller" you'll leave a lockfile behind, which you can then accidentally commit with your other files. 
> Reviewer tip: review with [whitespace off](https://github.com/microsoft/rushstack/pull/3746/files?w=1).
- Ensure that if an error occurs (e.g. pnpm generates an error), the lockfile is still deleted.
- Touched `package.json` in a local `rush-plugins` autoinstaller and ran `rush update-autoinstaller` on it, confirmed no lockfile was left behind.
=> [rush] Ensure autoinstaller lockfile is deleted

common/changes/@microsoft/rush/fix-build-cache-submodules_2022-11-15-04-53.json, common/changes/@rushstack/package-deps-hash/fix-build-cache-submodules_2022-11-15-04-53.json, libraries/package-deps-hash/src/getRepoState.ts, libraries/package-deps-hash/src/test/getRepoState.test.ts
Closes https://github.com/microsoft/rushstack/issues/1711
1. Analyzing state no more complain about submodule paths
2. File hashs under git submodule paths are taken into consideration when calculating build cache id
1. get all submodule paths by `git submodule status`
2. get file hashs under all submodule paths by `git submodule foreach git --no-optional-locks ls-tree -r --full-name HEAD`
3. apply file hashs under all submodule paths to repo state.
Tested in this repo: https://github.com/chengcyber/rush-build-cache-submodule-demo
=> [rush] get file hashs under git submodule paths when calculating build cache id

common/changes/@rushstack/heft-dev-cert-plugin/user-danade-FixWebpackStart_2022-11-14-20-23.json, heft-plugins/heft-dev-cert-plugin/src/DevCertPlugin.ts
Mismatched hostnames supplied to the Webpack devserver can cause auto-refresh to stop working in some scenarios. This fix ensures that the value is correctly set in the Webpack configuration.
Locally ran start mode.
=> [dev-cert-plugin] Fix Webpack auto-refresh issues caused by mismatched hostname

common/changes/@microsoft/rush/enelson-customfields_2022-10-24-00-56.json, libraries/rush-lib/src/api/ChangeManagement.ts, libraries/rush-lib/src/api/Changelog.ts, libraries/rush-lib/src/logic/ChangelogGenerator.ts, libraries/rush-lib/src/logic/test/ChangelogGenerator.test.ts, libraries/rush-lib/src/schemas/change-file.schema.json, libraries/rush-lib/src/schemas/changelog.schema.json
This is my suggested implementation of "custom field support" (related to https://github.com/microsoft/rushstack/issues/3707).
In this PR, base Rush allows custom fields in change files, and copies them over into generated changelogs. There's no way in base Rush to end up having these fields added _to_ your change files, but different programs could add them directly into the file, or a Rush plugin (not yet implemented) could inject them during `rush change`.
Pretty straightforward - schema updates, a couple new fields, and a line in the changelog generator. No changes needed to the `rush change` action as part of this PR.
- New unit test for changelog behavior
- Ensured rush change still works properly (new customFields property is optional)
=> Rush: allow customFields in change files and change logs

common/changes/@rushstack/debug-certificate-manager/cert-validity-period_2022-11-16-21-58.json, libraries/debug-certificate-manager/src/CertificateManager.ts
Shortens the default validity period for certificates generated by `@rushstack/debug-certificate-manager` to ~~30~~ 365 days to avoid browsers complaining about unacceptably long validity periods. Adds validation during `ensureCertificateAsync` that the existing certificate's validity period includes now.
Validates the `notBefore` and `notAfter` fields in addition to all the other current checks.
Local testing in `heft-webpack5-everything-test`.
Edit: Revised validity period from 30 days to 365 days.
=> [certificate-manager] Shorter validity period

heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts, heft-plugins/heft-typescript-plugin/src/TypeScriptPlugin.ts, heft-plugins/heft-typescript-plugin/src/internalTypings/TypeScriptInternals.ts
Adds use of the `runIncremental` hook in `@rushstack/heft-typescript-plugin`.
Uses `oldProgram` and source file caching to get incremental rebuild, whether the `incremental` tsconfig setting is used or not.
Builds are faster if `incremental` is set, since less type-checking happens.
Single file changes (if not deep in the graph) can execute in <100ms for the TypeScript portion now.
Running heft in watch mode in `rush-lib` and in `heft-node-everything-test`. Changed file, monitored performance and output files.
=> [heft-typescript-plugin] Fix incremental watch mode

apps/heft/UPGRADING.md, heft-plugins/heft-api-extractor-plugin/src/ApiExtractorPlugin.ts
- Update `@rushstack/api-extractor-plugin` to disable during watch mode
- Update UPGRADING.md in `@rushstack/heft` for information on prerelease Heft migration
=> [api-extractor-plugin] Disable API Extractor when in watch mode + UPGRADING.md

common/changes/@microsoft/rush/fix-build-cache-submodule_2022-11-17-04-33.json, common/changes/@rushstack/package-deps-hash/fix-build-cache-submodule_2022-11-17-04-33.json, libraries/package-deps-hash/src/getRepoState.ts, libraries/package-deps-hash/src/test/getRepoDeps.test.ts, libraries/package-deps-hash/src/test/getRepoState.test.ts
Fixes https://github.com/microsoft/rushstack/issues/3750
Refactor the logic in `getRepoState`:
1. Detecting git submodule by checking the existence of `.gitmodule` file
2. Recursively invoking `getRepoState` instead of running `git submodule foreach` command
Run `rush build -o heft-web-rig` on MacOS 12 and Windows 10
- MacOS: `Analyzing repo state... DONE (0.31 seconds)`
- Windows: `Analyzing repo state... DONE (0.46 seconds)`
=> [rush] fix performance regression from supporting git submodules

apps/lockfile-explorer/config/heft.json, common/changes/@rushstack/lockfile-explorer/octogonz-lfx-bundling-fix_2022-11-18-05-20.json
The `--production` build mode generates `dist/*.css` files which were not included in the published package.
Reproed the problem by publishing locally, then confirmed that this PR fixes it.
=> [lockfile-explorer] Fix an issue where --production assets were excluded from release

common/changes/@microsoft/rush/enelson-setup-prompts_2022-11-19-01-21.json, libraries/rush-lib/assets/rush-init/common/config/rush/artifactory.json, libraries/rush-lib/src/logic/setup/SetupPackageRegistry.ts, libraries/rush-lib/src/schemas/artifactory.schema.json
- Give monorepo maintainers a little more control over the "rush setup" flow.
If you've heavily customized the informational instruction messages for your "rush setup" flow, you can end up with some mismatches in terminology between the instructions and the prompt messages. This change ensures that pretty much all of the happy-path flow can be customized by the maintainer.
- Confirmed works out-of-box in local monorepo
- Confirmed customized user name and API key messages work in local monorepo
=> [rush] Allow maintainer to customize "rush setup" prompt messages

common/changes/@microsoft/rush/feature-ui-filter-prompt_2022-11-04-21-07.json, common/config/rush/browser-approved-packages.json, common/config/rush/nonbrowser-approved-packages.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, libraries/rush-lib/package.json, libraries/rush-lib/src/cli/actions/UpgradeInteractiveAction.ts, libraries/rush-lib/src/logic/InteractiveUpgrader.ts, libraries/rush-lib/src/utilities/InteractiveUpgradeUI.ts, libraries/rush-lib/src/utilities/prompts/SearchListPrompt.ts
This PR introduces project filtering feature as a part of the `upgrade-interactive` UI. 
By default a user will now be able to type after running `upgrade-interactive` to filter from the list of projects in their monorepo. 
In addition the PR also expands the default list height/pageSize to 12 for the prompt so you can see more projects before infinite scrolling begins.
The PR also adds missing licenses and attribution links.
=> [rush-lib] Add project filtering to upgrade-interactive ui

apps/lockfile-explorer-web/src/containers/LockfileViewer/index.tsx, apps/lockfile-explorer-web/src/containers/LockfileViewer/styles.scss
- Small quality-of-life improvement for the Filter bar.
- The `"search"` input type adds some built-in browser behaviors:
- Pressing ESC key while in field will clear the field and leave cursor ready to type
- Clicking browser-provided "clear" icon will clear the field and leave cursor ready to type
- Small modernization tweaks (placeholder text instead of label, padding increase, subtle rounded corner) 
Tested in Chrome and Safari on MacOS.
=> [lockfile-explorer] Use a search input field for the filter bar

common/changes/@microsoft/rush/enelson-env-vars_2022-11-19-18-14.json, libraries/rush-lib/src/api/RushProjectConfiguration.ts, libraries/rush-lib/src/logic/buildCache/ProjectBuildCache.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts, libraries/rush-lib/src/schemas/rush-project.schema.json
Allow maintainers to configure `dependsOnEnvVars` property, per-operation, in the `rush-project.json` configuration file.
Any variables configured this way have their keys and values included in the build cache hash.
Fixes #3730.
In the linked issue one suggestion is `cachingEnvVariables`, but I think this doesn't make it clear enough that it is an "input" to the build operation. But, for (future-redesign-of-rush-project-json-reasons), I think it's useful to reserve the word "input" only for _files that live inside the project folder and are tracked by git_.
`dependsOnEnvVars` is intended to align with "depends on other phases", "depends on other projects", and (perhaps in future) "depends on additional files outside this folder" -- anything the operation "depends" on becomes part of its …
=> [rush] Configure operation "dependsOnEnvVars" setting

common/changes/@microsoft/rush/enelson-tar-exec-bug_2022-11-25-15-11.json, libraries/rush-lib/src/utilities/TarExecutable.ts
When under load (for example, restoring multiple very large projects from build cache at the same time), the `TarExecutable` module can accidentally call `FileWriter.write` after `FileWriter.close` has already been called on the log file.
Instead of using the `exit` event, we can use [the close event](https://nodejs.org/api/child_process.html#event-close) (which triggers after the process has exited and all of its streams have been closed), which guarantees no more stdio will come through the pipe.
In `TarExecutable`, we set up event handlers for `stdout` and `stderr` data, and then write that output to the opened log file. If the process is doing a lot of asynchronous I/O, one of these callbacks (for a request to do a synchronous write to the log file) can back up to the point that one …
=> [rush] bug fix: TarExecutable module tries to write to closed file

apps/rush/CHANGELOG.json
This changelog message says that rush _change_ user prompts are customizable, but actually it is rush _setup_ user prompts.
(Oops.)
- Patching changelog source, which should automatically update the markdown during the next publish.
=> [rush] Tweak an incorrect changelog message

common/changes/@rushstack/heft-serverless-stack-plugin/fkjellberg-sst-fix_2022-11-29-17-39.json, heft-plugins/heft-serverless-stack-plugin/src/ServerlessStackPlugin.ts
The entry point used by `heft-serverless-stack-plugin` to spawn Serverless-Stack changed from `bin/scripts.js` to `bin/scripts.mjs`in the v1.2.0 release. This PR adds support for both entry points and thus makes the plugin to work with all existing releases of Serverless-Stack.
The change was tested in a separate repo by manually patching the plugin and running `rushx start` to deploy and start the Serverless-Stack application on AWS.
=> [heft-serverless-stack-plugin] Add support for Serverless-Stack 1.2.0 and later versions

common/changes/@microsoft/rush/updateNpmCheck_2022-11-29-19-46.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, libraries/rush-lib/package.json
A simple version bump. From what I saw in the dependency's repo they didn't actually make a breaking change to their public surface for `6.x`
Ran the full `rush test` suite. I don't think there's any new tests that need to be added since no logic was changed.
=> [rush-lib] Upgrade `npm-check` dependency to `6.0.1`

common/changes/@microsoft/rush/enelson-artifactoryjson_2022-11-30-21-03.json, libraries/rush-lib/assets/rush-init/common/config/rush/artifactory.json
- Fix typo
The recently added "apiKeyPrompt" property was incorrectly copy+pasted in the template file comments.
- N/A
=> [rush] Fix a typo in template artifactory.json

common/changes/@microsoft/rush/enelson-debounce_2022-11-30-20-17.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/RushCommandLineParser.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/RushConstants.ts, libraries/rush-lib/src/schemas/command-line.schema.json
Surface the "default watch mode debounce value" by mentioning it in the schema and moving it to the `RushConstants` list.
- Make the default value a rush constant and refer to it rather than inlining it.
- Mention the current default value in the schema (typically this would be mirrored in a configuration file comment but this functionality is so new it is not yet documented anywhere but the schema).
- Build passes
- Watch mode in local monorepo works as expected
=> [rush] Add default value for watchDebounceMs to the schema

common/changes/@rushstack/heft-webpack4-plugin/webpack-nested-errors_2022-12-01-21-37.json, common/changes/@rushstack/heft-webpack5-plugin/webpack-nested-errors_2022-12-01-21-37.json, heft-plugins/heft-webpack4-plugin/src/WebpackPlugin.ts, heft-plugins/heft-webpack5-plugin/src/WebpackPlugin.ts
Ensures that logging from webpack includes errors and warnings that originate in webpack child compiler instances.
The stats `hasErrors()` function includes errors from child compilations, but these errors don't get propagated into the top level `errors` or `warnings` arrays. This PR updates the Heft logger to also enumerate errors and warnings in all child compilations.
Debugger validation of the location of nested errors.
=> [heft-webpack] Log nested errors/warnings

common/changes/@microsoft/rush/enelson-nodeversion_2022-12-01-11-34.json, common/changes/@rushstack/terminal/enelson-nodeversion_2022-12-01-11-34.json, libraries/rush-lib/assets/rush-init/rush.json, libraries/rush-lib/src/api/RushConfiguration.ts, libraries/rush-lib/src/cli/RushCommandLineParser.ts, libraries/rush-lib/src/logic/operations/ConsoleTimelinePlugin.ts, libraries/rush-lib/src/logic/operations/test/OperationExecutionManager.test.ts, libraries/rush-lib/src/logic/operations/test/__snapshots__/OperationExecutionManager.test.ts.snap, libraries/rush-lib/src/schemas/rush.schema.json, libraries/terminal/src/PrintUtilities.ts, libraries/terminal/src/test/PrintUtilities.test.ts, libraries/terminal/src/test/__snapshots__/PrintUtilities.test.ts.snap
Adds an additional Rush configuration property, which provides additional instructions to the user if their node version is not supported by the monorepo.
Fixes #3405.
The change to Rush was very straightforward, but getting the message formatting properly took some experimentation.
My test case involves a long, pre-formatted message...
```js
{
"nodeSupportedVersionInstructions": "**NOTE**: For the best developer experience, use the node version specified in the\nmonorepo's .nvmrc file. The easiest way to do this is to update your default nvm\nversion and then re-run the script script:\n\n    nvm use 16.15.0\n    nvm alias default 16.15.0\n    common/scripts/setup.sh\n",
}
```
And the intent is for this message to be displayed exactly as formatted...
To achieve this some additional tweaks …
=> [rush] Customize instructions if node version is unsupported

common/changes/@microsoft/rush/simpler-schema-imports_2022-12-05-08-35.json, libraries/rush-lib/src/api/ApprovedPackagesConfiguration.ts, libraries/rush-lib/src/api/BuildCacheConfiguration.ts, libraries/rush-lib/src/api/CommandLineConfiguration.ts, libraries/rush-lib/src/api/CommonVersionsConfiguration.ts, libraries/rush-lib/src/api/ExperimentsConfiguration.ts, libraries/rush-lib/src/api/RushConfiguration.ts, libraries/rush-lib/src/api/RushPluginsConfiguration.ts, libraries/rush-lib/src/api/RushUserConfiguration.ts, libraries/rush-lib/src/api/VersionPolicyConfiguration.ts, libraries/rush-lib/src/logic/ChangeFiles.ts, libraries/rush-lib/src/logic/ChangelogGenerator.ts, libraries/rush-lib/src/logic/CredentialCache.ts, libraries/rush-lib/src/logic/RepoStateFile.ts, libraries/rush-lib/src/logic/deploy/DeployScenarioConfiguration.ts, libraries/rush-lib/src/logic/pnpm/PnpmOptionsConfiguration.ts, libraries/rush-lib/src/logic/setup/ArtifactoryConfiguration.ts, libraries/rush-lib/src/pluginFramework/PluginLoader/PluginLoaderBase.ts, libraries/rush-lib/tsconfig.json
This PR replaces all of the `JsonSchema.fromFile` instances with `JsonSchema.fromLoadedObject` in `rush-lib`. This improves bundleability of `rush-lib`.
=> [rush] Simplify JSON Schema loading.

.github/PULL_REQUEST_TEMPLATE.md
Update PULL_REQUEST_TEMPLATE.md based on [this Zulip discussion](https://rushstack.zulipchat.com/#narrow/stream/279883-contributor-helpline/topic/Getting.20started.20with.20the.20stack/near/314554132).
PR authors can't always do the work to fix the documentation, but they can at least help identify what work needs to be done, so we don't overlook this.
=> Add "Impacted documentation" section to PULL_REQUEST_TEMPLATE.md

common/changes/@microsoft/rush/webpack-rush-lib_2022-12-08-09-01.json, common/config/rush/nonbrowser-approved-packages.json, common/config/rush/pnpm-config.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, libraries/rush-lib/.npmignore, libraries/rush-lib/config/heft.json, libraries/rush-lib/config/typescript.json, libraries/rush-lib/package.json, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts, libraries/rush-lib/src/cli/actions/BaseAddAndRemoveAction.ts, libraries/rush-lib/src/cli/actions/BaseInstallAction.ts, libraries/rush-lib/src/cli/actions/DeployAction.ts, libraries/rush-lib/src/cli/actions/LinkAction.ts, libraries/rush-lib/src/cli/actions/UpgradeInteractiveAction.ts, libraries/rush-lib/src/cli/actions/VersionAction.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/InstallManagerFactory.ts, libraries/rush-lib/src/logic/PackageJsonUpdater.ts, libraries/rush-lib/src/logic/pnpm/PnpmfileShim.ts, libraries/rush-lib/src/scripts/install-run-rush.ts, libraries/rush-lib/src/scripts/install-run-rushx.ts, libraries/rush-lib/src/scripts/install-run.ts, libraries/rush-lib/src/utilities/PathConstants.ts, libraries/rush-lib/src/utilities/Utilities.ts, libraries/rush-lib/src/utilities/npmrcUtilities.ts, libraries/rush-lib/tsconfig.json, libraries/rush-lib/webpack.config.js
This PR includes a bundled copy of `rush-lib` in that project's `dist` folder.
This significantly improves the initialization time of `rush-lib`. Here are some metrics:
```
$ node -e "(() => { const start = Date.now(); require('./lib/index') ; const time = Date.now() - start; console.log('time: ' + time + 'ms');})()"
time: 1146ms
$ node -e "(() => { const start = Date.now(); require('./dist/rush-lib') ; const time = Date.now() - start; console.log('time: ' + time + 'ms');})()"
time: 757ms
```
Note that only the files local to `rush-lib` are bundled. Everything else is externalized.
Tested `rush init`, `rush install`, `rush update`, `rush build`, and `rush upgrade-interactive`. All work as expected.
This probably warrants some mention in documentation.
=> [rush] Ship a webpacked version of rush-lib.

common/changes/@microsoft/rush/enelson-strict_2022-12-08-18-21.json, libraries/rush-lib/src/logic/base/BaseInstallManager.ts
For a brief period (PNPM 7.0 - PNPM 7.13.5), the `strictPeerDependencies` setting was on by default in PNPM, and Rush's code changed to reflect this.
Now that the default has flipped back, Rush's handling of the flag is incorrect.
We discussed this in https://github.com/pnpm/pnpm/issues/5766 but PNPM said the change was intentional.  In the future, Rush should not rely on default values of important PNPM settings because the defaults can change in a PATCH release of PNPM.
- Rush now passes an explicit on or off command-line flag for strictPeerDependencies regardless of PNPM version.
- Tested pnpm 6.35.1, 7.13.0 and 7.17.1
N/A
=> [rush] Fix strictPeerDependencies in latest PNPM 7

common/changes/@microsoft/rush/feat-pnpm-cache-store-dir_2022-12-08-07-42.json, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts
This PR closes https://github.com/microsoft/rushstack/issues/3804
When pnpm, pnpmVersion >= 6.10.0, pnpmStore: "local", specifying `cache-dir` and `state-dir` to `store-dir` during pnpm install.
Tested in rushstack repo
=> [rush] cacheDir and stateDir to storePath during pnpm install if pnpmStore is local

common/changes/@microsoft/rush/fix-child-class-property_2022-12-09-05-51.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/LastInstallFlag.ts, libraries/rush-lib/src/api/LastLinkFlag.ts, libraries/rush-lib/src/api/test/LastInstallFlag.test.ts, libraries/rush-lib/src/api/test/LastLinkFlag.test.ts
I saw there is a refactoring to eliminate useless getter by https://github.com/microsoft/rushstack/pull/3809
However, i found an issue in `LastLinkFlag.path`. This PR fixes it. I carefully reviewed PR 3809, and this is the only issue.
In current main branch, LastInstallFlag set `this.path` by `this.flagName`
while, LastLinkFlag set `this.path` by `this.flagName` by extending LastInstallFlag
Actually, this won't work. Here is a minimal demo of this kind of class usage.
Add a test for LastLinkFlag
Before:
After this PR:
test passed
=> [rush] fix lastLinkFlag path

apps/lockfile-explorer/src/start.ts, common/changes/@rushstack/lockfile-explorer/fix-pnpmfile-not-exists_2022-12-16-13-45.json
Fixed https://github.com/microsoft/rushstack/issues/3841
=> fix(lockfile-explorer): not throw Error in node when pnpmfile not found

common/changes/@rushstack/webpack5-localization-plugin/issue-3858_2022-12-20-04-53.json, common/reviews/api/webpack5-localization-plugin.api.md, webpack/webpack5-localization-plugin/src/LocalizationPlugin.ts
Fixes #3858 
This PR updates updates `LocalizationPlugin._stringKeys` to `LocalizationPlugin.stringKeys` and making it a public property. This aligns its capabilities with its webpack 4 plugin counterpart. 
Since this was already a private property, this should only be a SemVer minor operation and I've specified as such in the change file.
=> [webpack5-localization-plugin] Make `LocalizationPlugin._stringKeys` a public property

common/changes/@microsoft/rush/improve-expired-credentials-experience_2022-12-21-18-33.json, common/changes/@microsoft/rush/improve-expired-credentials-experience_2022-12-21-18-34.json, common/reviews/api/rush-azure-storage-build-cache-plugin.api.md, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureAuthenticationBase.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureStorageBuildCacheProvider.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/index.ts
Currently, if a user has expired build cache credentials and attempts run a cached operation in a Rush repo, the operation will error. This change instead prints a warning and attempts to continue without credentials.
See the example screenshots below from user with expired credentials for a repo with cache backed by Azure Storage that allows anonymous access.
Before:
After:
Tested in the above mentioned repo.
=> [rush] Improve the experience during a rush operation when the cached credentials have expired.

common/changes/@microsoft/rush/move-rush-lib-types_2022-12-21-07-16.json, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts, libraries/rush-lib/src/cli/actions/AddAction.ts, libraries/rush-lib/src/cli/actions/BaseAddAndRemoveAction.ts, libraries/rush-lib/src/cli/actions/BaseInstallAction.ts, libraries/rush-lib/src/cli/actions/InstallAction.ts, libraries/rush-lib/src/cli/actions/RemoveAction.ts, libraries/rush-lib/src/cli/actions/UpdateAction.ts, libraries/rush-lib/src/cli/actions/test/AddAction.test.ts, libraries/rush-lib/src/cli/actions/test/RemoveAction.test.ts, libraries/rush-lib/src/logic/InstallManagerFactory.ts, libraries/rush-lib/src/logic/PackageJsonUpdater.ts, libraries/rush-lib/src/logic/PackageJsonUpdaterTypes.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/base/BaseInstallManagerTypes.ts, libraries/rush-lib/src/logic/installManager/RushInstallManager.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/logic/test/BaseInstallManager.test.ts
This is required by https://github.com/microsoft/rushstack/pull/3840
=> Extract some types exported from async-loaded that are referenced in sync-loaded modules into their own files.

common/changes/@microsoft/webpack5-load-themed-styles-loader/feature-include-webpack-peer-deps_2023-01-11-04-41.json, webpack/webpack5-load-themed-styles-loader/package.json
This PR makes webpack@5 an optional peer dependency for this loader. The types explicitly depend on webpack@5's types from its package.
=> [webpack5-load-themed-styles-loader] make webpack optional peer

common/changes/@microsoft/rush/stekycz-install-run-rush-pnpm_2023-01-05-09-13.json, libraries/rush-lib/src/logic/StandardScriptUpdater.ts, libraries/rush-lib/src/scripts/install-run-rush-pnpm.ts, libraries/rush-lib/src/scripts/install-run-rush.ts, libraries/rush-lib/src/utilities/PathConstants.ts, libraries/rush-lib/webpack.config.js
Fixes #3851
The solution completely solves the issue.
I did not test this code but I have tested the script updated manually in my other private repo.
It would be nice to mention it in [Enabling CI builds](https://rushjs.io/pages/maintainer/enabling_ci_builds/#install-run-rushjs-for-bootstrapping-rush). However, `install-run-rushx.js` is not there as well. The same probably applies to [Config files](https://rushjs.io/pages/advanced/config_files/#temporary-files-created-by-rush).
=> [rush] Add install-run-rush-pnpm.js script

apps/api-extractor/src/analyzer/TypeScriptInternals.ts, common/changes/@microsoft/api-extractor/check-flags_2023-01-16-22-41.json
As of https://github.com/microsoft/TypeScript/pull/51880, the internal property `checkFlags` is no longer defined on Symbol directly, but on `symbol.links`. This causes api-extractor to fail when used with TS 5.0.
Rather than trying to figure out if we should use links, just use `ts.getCheckFlags`, which has been around since at least TypeScript 2.3. (It'd be better if internals weren't used at all, of course.)
Patched api-extractor in a project's node_modules with this change, and saw that it worked.
No updated docs.
=> [api-extractor] Use ts.getCheckFlags to fix TS 5.0

common/changes/@microsoft/rush/repo-state-performance_2022-12-10-00-54.json, common/changes/@rushstack/package-deps-hash/repo-state-performance_2022-12-10-00-54.json, common/reviews/api/package-deps-hash.api.md, common/reviews/api/rush-lib.api.md, libraries/package-deps-hash/src/getRepoState.ts, libraries/package-deps-hash/src/index.ts, libraries/package-deps-hash/src/test/__snapshots__/getRepoDeps.test.ts.snap, libraries/package-deps-hash/src/test/getRepoDeps.test.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/cli/test/RushCommandLineParser.test.ts, libraries/rush-lib/src/logic/ProjectChangeAnalyzer.ts, libraries/rush-lib/src/logic/test/ProjectChangeAnalyzer.test.ts
Prototypes parallelizing as many of the Git calls involved in calculating the state used by `ProjectChangeAnalyzer` as possible.
Parallelizes the following operations:
- `git ls-tree HEAD` for the state of the committed tree
- `git status` for the working tree state
- `git hash-object` on the project shrinkwrap files
The following operation still needs to run serially:
- `git hash-object` for changed files in the working tree, though it can use the same process invocation and delay passing the filenames on stdin
Reduces time for initializing `ProjectChangeAnalyzer` on my Windows dev box for the rushstack repository from 0.5 seconds to 0.3 seconds.
Reduces time for initializing `ProjectChangeAnalyzer` on my Windows dev box for an internal repository from 2.2 seconds to 1.5 seconds.
Related …
=> [package-deps-hash] Parallelize getRepoState

common/changes/@microsoft/rush/fix-create-scripts_2023-01-22-03-09.json, libraries/rush-lib/src/utilities/PathConstants.ts
The `export` for the "scripts" folder name was accidentally removed from `pathConstants.ts`, causing the scripts to get compiled into an "undefined" folder.
This puts the export back.
Confirmed that the folder structure is as expected and that `rush install` works.
=> [rush] Fix an issue where scripts were compiled into the wrong folder name.

common/changes/@rushstack/package-deps-hash/octogonz-fix-build-break_2023-01-22-19-58.json, libraries/package-deps-hash/src/test/getRepoDeps.test.ts
Some Jest tests were failing nondeterministically, so I temporarily disabled them.
Reenabling these tests is tracked by https://github.com/microsoft/rushstack/issues/3913
=> Fix build break

common/changes/@microsoft/rush/stekycz-git-hooks-exec_2023-01-05-10-36.json, libraries/rush-lib/src/logic/base/BaseInstallManager.ts
Fixes #3816
I change copy of the script to create a new script from inlined template. The template might be another file but I chose simple solution now because the script is very simple. I can move it to a template file if needed but I would need guidance to where the file should be placed and what templating should be leveraged to hardcode specific values.
I am trying to keep the script universal to work even the directory of the repo is renamed. That is why I do not use absolute paths and I detect the script directory.
I am not sure how to test these changes from the branch. However, I use the pattern of executing another script in one of my private repos.
The [Git Hooks](https://rushjs.io/pages/maintainer/git_hooks/) documentation might need an update.
=> [rush] Create custom git hooks instead of copy

common/changes/@rushstack/package-deps-hash/package-deps-bug_2023-01-23-21-55.json, libraries/package-deps-hash/src/getRepoState.ts, libraries/package-deps-hash/src/test/__snapshots__/getRepoDeps.test.ts.snap, libraries/package-deps-hash/src/test/getRepoDeps.test.ts
Fixes #3913 .
Fixed a bug in `parseGitHashObject` in which it would return a bogus entry `[undefined, '']` if no file paths were requested to be hashed.
Added unit tests specific to `parseGitHashObject`.
None
=> [package-deps-hash] Fix getRepoStateAsync

common/changes/@microsoft/rush/fix-rush-add_2023-01-25-06-56.json, common/config/rush/version-policies.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/PackageJsonEditor.ts, libraries/rush-lib/src/api/RushConfigurationProject.ts, libraries/rush-lib/src/api/SaveCallbackPackageJsonEditor.ts, libraries/rush-lib/src/api/test/RushConfiguration.test.ts, libraries/rush-lib/src/api/test/__snapshots__/RushConfiguration.test.ts.snap
Right now, if you run `rush add -p <some package that's new to the repo>`, the [`non`]`browser-approved-packages.json` file isn't updated.
This happens because after the `packageJsonEditor` saves the file, it doesn't update the `packageJson` `RushConfigurationProject` property with the new `package.json` contents. This PR fixes that.
Added a unit test, and ran `rush add -p @radix-ui/react-dialog` in a repo that isn't already using `@radix-ui/react-dialog`.
=> [rush] Fix an issue where 'rush add' does not update the approved packages files.

common/changes/@microsoft/rush/user-danade-RevertGitHooksCHange_2023-01-26-00-13.json, libraries/rush-lib/src/logic/base/BaseInstallManager.ts
This reverts changes brought in by https://github.com/microsoft/rushstack/pull/3873
Reverts the change due to a few issues encountered when attempting to integrate into our own repository:
- Linux-based issues caused by not `chmod -x`-ing the scripts commited to the common/git-hooks, causing permissions errors when running hooks on Linux-based devices
- Issues with compatibility with `git lfs`, causing the error `This should be run through Git's pre-push hook.  Run 'git lfs update' to install it.` even when running through the pre-push hook
It just seems like this change requires a bit more time to bake/test, so for now, going to revert.
CC @stekycz
=> [rush] Revert creation of custom git hooks

common/changes/@rushstack/module-minifier/terser-version-hash_2023-01-24-19-28.json, libraries/module-minifier/src/LocalMinifier.ts, libraries/module-minifier/src/WorkerPoolMinifier.ts, libraries/module-minifier/src/test/LocalMinifier.test.ts, libraries/module-minifier/src/test/WorkerPoolMinifier.test.ts, libraries/module-minifier/src/test/__snapshots__/LocalMinifier.test.ts.snap, libraries/module-minifier/src/test/__snapshots__/WorkerPoolMinifier.test.ts.snap
Includes the version string from the installed version of `terser` in the config hash for `@rushstack/module-minifier` for the minifier implementations that use `terser`.
Added to both `LocalMinifier` and `WorkerPoolMinifier`.
Added unit tests for the config hash strings.
=> [module-minifier] Include terser version in config hash

build-tests/heft-sass-test/config/sass.json, build-tests/heft-sass-test/webpack.config.js, common/changes/@rushstack/heft-sass-plugin/preserveSCSSExtension_2023-01-30-20-48.json, heft-plugins/heft-sass-plugin/src/SassProcessor.ts, heft-plugins/heft-sass-plugin/src/schemas/heft-sass-plugin.schema.json, heft-plugins/heft-sass-plugin/src/templates/sass.json
Adds a new option `preserveSCSSExtension` to `@rushstack/heft-sass-plugin` that, if set, will reuse the `.scss` extension when emitting compiled CSS.
When the option is `false`, the emitted extension for `.scss` source files is `.scss.css`. When the option is true, it is `.scss`. This means that Webpack configurations will need to specify a loader for `.scss`, which may be `sass-loader`, but the input will still be valid CSS without any SCSS features.
The motivation here is to make switching to precompiled CSS backwards compatible with external packages that expect the imports in a given package to resolve to an exact matching filename, without adding any extra extensions.
Local build test (build-tests/heft-sass-test).
Validated emitted file paths, and that pointing Webpack at the .scss …
=> [heft-sass] Add preserveSCSSExtension option

build-tests/hashed-folder-copy-plugin-webpack4-test/webpack.config.js, common/changes/@rushstack/hashed-folder-copy-plugin/hashed-copy-salt_2023-02-01-02-58.json, webpack/hashed-folder-copy-plugin/src/HashedFolderCopyPlugin.ts
Includes the value of the webpack configuration option `output.hashSalt` in the computed hash for the copied folder.
The value of the `hashSalt`, if defined, is applied to the hash before hashing folder content.
Applied the property with different values in `build-tests/hashed-folder-copy-plugin-webpack4-test` and `build-tests/hashed-folder-copy-plugin-webpack5-test` and validated that the output hash was impacted in a stable manner.
None, currently.
=> [hashed-folder-copy-plugin] Respect output.hashSalt

common/changes/@rushstack/rush-serve-plugin/serve-global-dir_2023-02-02-23-52.json, rush-plugins/rush-serve-plugin/src/RushProjectServeConfigFile.ts, rush-plugins/rush-serve-plugin/src/RushServePlugin.ts, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts, rush-plugins/rush-serve-plugin/src/schemas/rush-serve-plugin-options.schema.json
Adds a field `globalRouting` to the plugin config for `rush-serve-plugin`, to enable Rush workspaces to serve assets that are owned by the entire workspace (or plugins) rather than specific projects within said workspace.
Workspace level routing rules come from the plugin's options file, rather than files in individual projects. Expected use case is if a Rush plugin writes files that it wants served, that the plugin config can be used to specify a location, regardless of what projects are in scope of the Rush command.
Copied into another repository and tested in place with a workspace config.
Documented in the schema. Will need an init template added eventually.
=> [rush-serve-plugin] Add workspace-level routing

common/changes/@rushstack/module-minifier/node-peerdep-wildcard_2023-02-04-23-42.json, common/changes/@rushstack/node-core-library/node-peerdep-wildcard_2023-02-04-23-42.json, common/changes/@rushstack/terminal/node-peerdep-wildcard_2023-02-04-23-42.json, common/changes/@rushstack/typings-generator/node-peerdep-wildcard_2023-02-04-23-42.json, common/changes/@rushstack/webpack4-localization-plugin/node-peerdep-wildcard_2023-02-04-23-42.json, common/changes/@rushstack/webpack4-module-minifier-plugin/node-peerdep-wildcard_2023-02-04-23-42.json, common/changes/@rushstack/webpack5-localization-plugin/node-peerdep-wildcard_2023-02-04-23-42.json, common/changes/@rushstack/webpack5-module-minifier-plugin/node-peerdep-wildcard_2023-02-04-23-42.json, common/changes/@rushstack/worker-pool/node-peerdep-wildcard_2023-02-04-23-42.json, libraries/module-minifier/package.json, libraries/node-core-library/package.json, libraries/terminal/package.json, libraries/typings-generator/package.json, libraries/worker-pool/package.json, webpack/webpack4-localization-plugin/package.json, webpack/webpack4-module-minifier-plugin/package.json, webpack/webpack5-localization-plugin/package.json, webpack/webpack5-module-minifier-plugin/package.json
This is in response to issues many people have been reporting after we moved `@types/node` from a regular dependency to a peer dependency.
Design discussion here: [Zulip: Unmet peer dependencies in @rushstack/node-core-library](https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/Unmet.20peer.20dependencies.20in.20.40rushstack.2Fnode-core-library/near/325049326)
Fixes #3946
=> Change the peer dependency selector on @types/node to a wildcard.

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, build-tests/install-test-workspace/workspace/pnpm-workspace.yaml, build-tests/install-test-workspace/workspace/rush-lib-test/package.json, build-tests/install-test-workspace/workspace/rush-lib-test/src/start.ts, build-tests/install-test-workspace/workspace/rush-lib-test/tsconfig.json
1. Show how to access internal APIs from rush-lib
2. Validate that it compiles using a real install (instead of `workspace:*` linking)
=> [rush-lib] Add an install-test-workspace project validating imports of internal APIs

common/changes/@microsoft/rush/feature-skip-unused-checks_2023-02-03-22-49.json, libraries/rush-lib/src/logic/InteractiveUpgrader.ts
This PR removes the automatic `depcheck` feature from npm-check when calling `upgrade-interactive`. 
Currently today this provides some poor UI visualizations while npm-check is fetching registry data for a long list of packages. 
Now only a spinner will appear with "Checking for package updates" appears.
=> [rush-lib] Disable automatic depcheck when running `upgrade-interactive`

common/changes/@microsoft/rush/fix-worktrees_2023-02-08-02-59.json, libraries/rush-lib/src/logic/ProjectChangeAnalyzer.ts
Fixes #3962 
Regression was introduced by #3756.
Validation that `git rev-parse --showtoplevel` returns the correct working tree root in a multi-worktree environment.
Comparison with a prior Rush version.
None.
=> [rush] Fix support for multi-worktree environments

common/changes/@microsoft/rush/recycler-fixes_2023-02-01-22-45.json, libraries/rush-lib/src/utilities/AsyncRecycler.ts
On Windows, when running inside of VSCode, it is common to encounter errors that look like:
```
ERROR: Error: Error: EPERM: operation not permitted, symlink
'D:\test-repo\common\temp\node_modules\.pnpm\my-package@0.0.1\node_modules\my-package\'
->
'D:\test-repo\common\temp\rush-recycler\node_modules_1675288481011\.pnpm\my-package@0.0.1\node_modules\my-package'
Often this is caused by a file lock from a process like the virus scanner.
```
This PR addresses this issue.
The most unexpected part of the above mentioned error is that the operation being performed is `symlink` in the middle of purging the `common/temp/node_modules` folder. Hooking up a debugger showed that `FileSystem.move`, in its call to `require('fs-extra').moveSync` was internally routing down a code path that performs a …
=> [rush] Fix EPERM in AsyncRecycler

.devcontainer/devcontainer.json, .devcontainer/setGitConfigUserName.js, .devcontainer/setup.sh, build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
Add customized default .devcontainer with rust and node toolchains only. This should considerably speed up the setup of a codespace as the default from github dev container was also including python, ruby, go, java, etc. 
Partially addresses many of the boxes in #3965 
Additionally in this PR the build-test folder lockfile got bumped running a full test build, so I'll also commit that change here since it is a small and inconsequential change.
=> Setup default dev container for rushstack with Rust and Node (v16) toolchains.

common/changes/@microsoft/rush/feat-build-cache-log_2023-01-11-16-25.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/index.ts, libraries/rush-lib/src/logic/operations/IOperationRunner.ts, libraries/rush-lib/src/logic/operations/OperationExecutionRecord.ts, libraries/rush-lib/src/logic/operations/OperationMetadataManager.ts, libraries/rush-lib/src/logic/operations/OperationStateFile.ts, libraries/rush-lib/src/logic/operations/ProjectLogWritable.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts
This PR add a feature: restoring operation log files when cache hit
Introduce a new "OperationMetadataManager"
1. when a task successful without cache, save the log files into `.rush/temp/operation/<identifier>/all.log` and `.rush/temp/operation/<identifier>/error.log`.
2. when a task successful with cache hit, append the `all.log` file content to current operation log and copy the error log if exists.
Tested in rushstack and a repo without phase commands.
1. Save the log file
2. Append the cached log content to current log
Nope
=> [rush] Restore log files when cache hit

common/changes/@microsoft/rush/azure-auth-remove-sdk_2023-02-09-21-41.json, common/reviews/api/rush-azure-storage-build-cache-plugin.api.md, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureAuthenticationBase.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureStorageAuthentication.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureStorageBuildCacheProvider.ts
Removes the runtime dependency on @rushstack/rush-sdk from the AzureStorageAuthentication class so that it can be loaded in isolation.
Moved the `credentialUpdateCommandForLogging` field to be a constructor parameter instead of an abstract field, and stopped providing a default value in `AzureStorageAuthentication`, so that it no longer imports `@rushstack/rush-sdk`.
Local build + unit test.
None.
=> [rush-azure-storage-plugin] Remove rush-sdk dependency from AzureStorageAuthentication

common/changes/@rushstack/package-deps-hash/no-ahead-behind_2023-02-22-22-11.json, libraries/package-deps-hash/src/getRepoState.ts
Ensures that the call to `git status` does not perform git maintenance tasks or issue network calls.
Sets the `maintenance.auto` config option to `false` while running the `git status` command to ensure maintenance tasks do not run and passes the `--no-ahead-behind` flag to ensure that it does not query the remote.
Local rush build with built copy.
None.
=> [package-deps-hash] Limit unexpected Git work

common/changes/@rushstack/debug-certificate-manager/fix-certificate-expiration_2023-03-02-23-52.json, libraries/debug-certificate-manager/src/CertificateManager.ts
Fixes a bug in which certificates were being generated with a longer-than-expected validity period and therefore failing browsers' maximum validity period checks.
Ensures that the `notAfter` date is completely specified, rather than using whatever default value was provided by `node-forge` and altering the UTCDate field.
Adds a validation step on the expiration date to ensure that the certifiate doesn't exceed the maximum validity allowed by common browsers.
Manual execution of heft-webpack5-everything-test after deleting local certificate:
```
Subject: localhost
Issuer: rushstack-certificate-manager.localhost
Expires on: Mar 1, 2024
Current date: Mar 2, 2023
```
None
=> [debug-certificate-manager] Fix cert expiration

common/changes/@microsoft/rush/remove-pnpm-store-purge_2023-03-06-19-22.json, libraries/rush-lib/src/logic/installManager/RushInstallManager.ts
Fixes https://github.com/microsoft/rushstack/issues/3996
The PNPM store is pretty stable at this point, and `rush purge` will still delete a local store.
=> [rush] Do not delete the local pnpm store after all install attempts has failed.

.github/workflows/file-doc-tickets.yml
This is a suggested improvement to the CI/CD workflow for the `rushstack` repo. This GitHub Actions workflow will automatically file documentation tickets on the `rushstack-websites` repo whenever a pull request is merged that contains non-whitespace, non-comment content under the **Impacted documentation** header.
Based on some contributor feedback, @octogonz recently added a section where we could ask the contributor if there's any doc pages that the PR would impact. This is valuable information, but right now it's up to a contributor or maintainer to remember this section was filled in.
This change takes the information entered by the contributor and files a "doc ticket"; this doc ticket can then be closed by a doc PR (either by the contributor or by a maintainer). Since the doc ticket …
=> [repo] File automatic doc tickets to the rushstack-websites repo

common/changes/@microsoft/rush/fix-update-autoinstaller_2023-03-14-02-58.json, libraries/rush-lib/src/cli/RushCommandLineParser.ts, libraries/rush-lib/src/cli/actions/InitAutoinstallerAction.ts, libraries/rush-lib/src/cli/actions/UpdateAutoinstallerAction.ts, libraries/rush-lib/src/cli/scriptActions/GlobalScriptAction.ts, libraries/rush-lib/src/logic/Autoinstaller.ts, libraries/rush-lib/src/pluginFramework/PluginLoader/AutoinstallerPluginLoader.ts, libraries/rush-lib/src/pluginFramework/PluginManager.ts
There is an issue with `rush update-autoinstaller` where it doesn't ensure the package manager is installed before trying to invoke it in the autoinstaller's folder. This PR fixes that and ensure that the autoinstaller updater uses the same `RushGlobalFolder` as other installers.
Ran `rush purge` and then `rush update-autoinstaller` in a test repo with a change to an autoinstalled package.
=> [rush] Fix an issue with running 'rush update-autoinstaller'.

common/changes/@microsoft/rush/feat-periodically-send-operation-state_2023-03-17-02-07.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/OperationExecutionRecord.ts, libraries/rush-lib/src/pluginFramework/PhasedCommandHooks.ts
Exposing executionRecords in PhasedScriptsAction allows users to observe the execution process
As a member of the monorepo infrastructure team, there will be many compilations in progress at the same time, 
I hope to be able to collect the real-time status of the rush execution command. If I can get the real-time status in the hooks of rushLifeCycle, I can observe the start and end times of all project compilation in a task, and then send it to the data server to build a dashboard that can view the execution status in real time
```
rushSession.hooks.runAnyPhasedCommand.tap(PLUGIN_NAME, (phase: ReadonlyMap<Operation, IOperationExecutionResult>) => {
phase.hooks.beforeExecuteOperations.tapPromise(PLUGIN_NAME, async (records) => {
// all operation records
}); …
```
=> [rush] Exposing executionRecords in PhasedScriptsAction allows users to observe the execution process

common/changes/@microsoft/rush/extend-lookup-by-path_2023-03-14-17-57.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/index.ts, libraries/rush-lib/src/logic/LookupByPath.ts, libraries/rush-lib/src/logic/test/LookupByPath.test.ts
Enhances the `LookupByPath` helper class with a method `findChildPathAndIndex` that returns both the matched entry and the index at which the remainder of the query path starts.
Useful for `ProjectChangeAnalyzer` when routing files to projects, to get the remaining path relative to the project.
None
=> [rush-lib] Extend LookupByPath to return index of remaining path

common/changes/@rushstack/debug-certificate-manager/refresh-too-long-lived-certs_2023-03-03-03-27.json, libraries/debug-certificate-manager/src/CertificateManager.ts
Related to https://github.com/microsoft/rushstack/pull/3997, this PR will force certificates with a validity period longer than the allowed period to be refreshed.
=> [debug-certificate-manager] Force certificates with a validity period longer than 365 days to be refreshed.

common/changes/@microsoft/rush/main_2023-03-22-19-25.json, libraries/rush-lib/src/cli/actions/UpdateAutoinstallerAction.ts, libraries/rush-lib/src/logic/Autoinstaller.ts
I recently fixed another issue with `rush update-autoinstaller` where it would fail if the package manager wasn't already installed (https://github.com/microsoft/rushstack/pull/4009). This introduced a regression where Rush would attempt to install autoinstallers with `--frozen-lockfile` before updating them, which doesn't work if their dependencies change.
This PR fixes that issue by explicitly installing the package manager during the autoinstaller's update function instead.
Tested in a repo that was failing to update the autoinstaller before.
=> [rush] Fix an issue with update-autoinstaller.

.github/workflows/file-doc-tickets.yml
If a PR's description is empty, the `event.pull_request.body` property in the doc pipeline is `null`. See example here: https://github.com/microsoft/rushstack/actions/runs/4494179393/jobs/7906337595
This PR handles that case.
=> Fix an issue with the 'File Doc Tickets' pipeline.

common/changes/@microsoft/rush/feature-rush-event-hook-output_2023-03-21-07-43.json, common/changes/@microsoft/rush/feature-rush-event-hook-output_2023-03-23-06-10.json, common/config/rush/experiments.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/assets/rush-init/common/config/rush/experiments.json, libraries/rush-lib/src/api/ExperimentsConfiguration.ts, libraries/rush-lib/src/logic/EventHooksManager.ts, libraries/rush-lib/src/schemas/experiments.schema.json
The problem: currently, rush does not show any output from scripts defined within hooks like `postRushInstall ` by default. This is an issue because it prevents users from seeing any meaningful logs or progress from their scripts. This is more of a pain point when the scripts are long-running and may create the illusion of hanging.
The fix: we should enable event hook scripts outputs by default, since they are fully controlled by users, and they shouldn't be hidden behind `verbose` or `debug` flag, as it would create unwanted noise from other steps when enabled and hinder the flexibility of user extension points. 
The only change is to let user script to handle output for event hooks.
Fixes #553
- test default experiments.json file
- `rush init`
- verify …
=> [rush-lib] enable event hook scripts output by default

common/changes/@microsoft/rush/clean-up-rush-sdk-shipped-files_2023-03-30-18-55.json, libraries/rush-sdk/.npmignore
rush-sdk currently ships typings, sourcemaps, and the shim generator script under its `lib-shim` folder. These aren't useful to a consumer of the package.
=> [rush] Stop shipping everything except for index.js under lib-shim in rush-sdk.

common/changes/@microsoft/rush/fix-rush-sdk-loading-issue_2023-03-30-19-19.json, libraries/rush-lib/src/utilities/SetRushLibPath.ts
Fix an issue where rush-sdk would fail to load if it was invoked from inside a Rush process where the version selector's version doesn't match the currently-executing rush-lib version.
The `@microsoft/rush` package loads the version of `@microsoft/rush-lib` that it was shipped with, which sets the `_RUSH_LIB_PATH` env variable to the entrypoint of that copy (and version) of `rush-lib`. If the version selector logic in `@microsoft/rush` then determines that the repo that it's executing in wants a different version of `rush-lib`, and loads that, the `_RUSH_LIB_PATH` is currently not updated to point to the correct version of `rush-lib`.
If something executing inside that Rush process (like a build tool) then loads `rush-sdk`, it will get the wrong version of `rush-lib` and potentially not …
=> [rush] Fix an issue where rush-sdk sometimes fails to load if the globally installed Rush package is too old

common/changes/@microsoft/rush/enelson-fix-lock_2023-04-01-14-57.json, libraries/rush-lib/src/cli/actions/test/removeRepo/.gitignore
Running `heft test` locally on Mac/Linux always creates a temp lock file in the removeRepo test folder.
This is because it is missing a gitignore entry for `common/temp`, like the other test repo folders have.
- Add `.gitignore` file.
- Tested locally, lock file is ignored
=> [rush] Tiny test fix: removeRepo rush lock file

common/changes/@rushstack/heft-webpack5-plugin/thelarkinn-issue-4053_2023-04-10-18-19.json, heft-plugins/heft-webpack5-plugin/package.json
=> Bump webpack@5 peerDependency in sync with normal webpack dependency. 

common/changes/@rushstack/debug-certificate-manager/cert-subjects_2023-04-13-22-22.json, libraries/debug-certificate-manager/src/CertificateManager.ts
For some reason, clicking on links to `https://localhost:1123` (or whatever port), opens `https://127.0.0.1:1123` in the browser, which then fails the certificate check. This PR updates the default certificate subjects to include `127.0.0.1` as one of the entries, alongside the `rushstack.localhost` option.
Updates the default list of certificate subjectAltNames. Modifies the certificate validator to consider a certificate missing requested names as invalid.
Local run.
None that I know of, currently.
=> [debug-cert-manager] Add more default subjects

build-tests-samples/heft-webpack-basic-tutorial/package.json, build-tests/hashed-folder-copy-plugin-webpack5-test/package.json, build-tests/heft-webpack5-everything-test/package.json, build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@microsoft/rush/main_2023-04-19-18-11.json, common/changes/@microsoft/webpack5-load-themed-styles-loader/main_2023-04-19-18-11.json, common/changes/@rushstack/heft-dev-cert-plugin/main_2023-04-19-18-11.json, common/changes/@rushstack/heft-web-rig/main_2023-04-19-18-11.json, common/changes/@rushstack/heft-webpack5-plugin/main_2023-04-19-18-11.json, common/changes/@rushstack/webpack-embedded-dependencies-plugin/main_2023-04-19-18-11.json, common/changes/@rushstack/webpack-plugin-utilities/main_2023-04-19-18-11.json, common/changes/@rushstack/webpack-preserve-dynamic-require-plugin/main_2023-04-19-18-11.json, common/changes/@rushstack/webpack5-localization-plugin/main_2023-04-19-18-11.json, common/changes/@rushstack/webpack5-module-minifier-plugin/main_2023-04-19-18-11.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, heft-plugins/heft-dev-cert-plugin/package.json, heft-plugins/heft-webpack5-plugin/package.json, libraries/rush-lib/package.json, rigs/heft-web-rig/package.json, webpack/preserve-dynamic-require-plugin/package.json, webpack/webpack-deep-imports-plugin/package.json, webpack/webpack-embedded-dependencies-plugin/package.json, webpack/webpack-plugin-utilities/package.json, webpack/webpack5-load-themed-styles-loader/package.json, webpack/webpack5-load-themed-styles-loader/src/test/__snapshots__/LoadThemedStylesLoader.test.ts.snap, webpack/webpack5-localization-plugin/package.json, webpack/webpack5-module-minifier-plugin/package.json
Bumps all deps using webpack 5 to latest webpack 5.80.0.
webpack 5.80.0 release notes: https://github.com/webpack/webpack/releases/tag/v5.80.0
=> Update webpack@5 version to 5.80.0

common/changes/@microsoft/rush/rush-version-performance_2023-04-20-20-57.json, libraries/rush-lib/src/logic/PublishUtilities.ts
Improves the performance of `rush version --bump` for monorepos that use the `workspace:` protocol to specify local dependencies by around 50% by preventing unused `semver.satisfies` checks from executing.
Flips the order of a conditional so that the cheap condition evaluates first.
Before:
After:
Running `rush version --bump` on a repository with a large number of pending changes.
Not a behavior change, so none.
=> [rush-lib] Improve performance of 'rush version --bump'

common/changes/@microsoft/rush/rush-version-workspace-perf_2023-04-20-22-52.json, libraries/rush-lib/src/logic/PublishUtilities.ts
Fixes a performance bug in `rush version` when projects use the `workspace:*` dependency version specifier. Reduces time spent in `_updateDownstreamDependency` to a negligible portion of the total runtime.
Fixes #4067
Doesn't actually change the overall algorithm, but allows the early return to work as expected.
Reduced the number of times the `_updateDownstreamDependency` branch that would call `semver.satisfies` is called from 80450952 to 8589 in a test run.
None.
=> [rush] Fix rush version `workspace:*` perf

common/changes/@microsoft/rush/fix-look-by-path_2023-04-25-09-41.json, libraries/rush-lib/src/logic/LookupByPath.ts, libraries/rush-lib/src/logic/test/LookupByPath.test.ts
Fixes the logic of prefix match in `LookupByPath` when the last segment of project folder is a single character.
I am testing build cache in a demo Rush.js monorepo with several projects, the rush.json is like
```json
"projects": [
{
"packageName": "a",
"projectFolder": "projects/a"
},
{
"packageName": "b",
"projectFolder": "projects/b"
},
// ...
]
```
However, when i run `rush build` with build cache enabled. I found there is a issue to calculate the correct cache id. After dive into the code, it seems there is an edge case when prefix matching with each project folders.
Actual behaviour:
When creating the lookup tree with `projects/a`, it now ignores the trailing character a. The path tree would be like
```
{
value: undefined,
children: { // It's a map, use object here to show idea. …
```
=> Fix look by path

apps/api-documenter/src/documenters/OfficeYamlDocumenter.ts, common/changes/@microsoft/api-documenter/AlexJ-TSJS_2023-04-17-23-03.json
PR #3932 allowed for markdown bold and italics to be emitted. The overrides in the Office-specific implementation are not longer necessary. Additionally, the distinction the Office-specific documenter was drawing for TS versus JS examples isn't relevant with ES6 JavaScript, so all examples are now labelled as TypeScript. This matches the DocFX API signature labeling as well 
Local build tests and in the [Office Scripts reference repo](https://github.com/OfficeDev/office-scripts-docs-reference/compare/main...AlexJ-RSTest).
None
=> [api-documenter] OfficeYamlDocumenter: Simplify example labelling and remove unnecessary asterisk protection

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, build-tests/install-test-workspace/workspace/package.json, libraries/package-extractor/package.json
Fixes the build script for `@rushstack/package-extractor` to be compatible with `heft@next`.
Fixes the `install-test-workspace` project.
Local build.
=> [heft-rc] Fix build scripts

common/changes/@rushstack/package-extractor/user-danade-FixExtractorTypings_2023-04-28-18-56.json, libraries/package-extractor/package.json
Fix package extractor typings. The current package.json references the legacy name of the package. Updated package.json to reference the correct typings.
=> [package-extractor] Fix `typings` field in @rushstack/package-extractor package.json

common/changes/@rushstack/node-core-library/user-danade-TerminalWritableStream_2023-04-28-20-46.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/Terminal/TerminalWritable.ts, libraries/node-core-library/src/Terminal/test/TerminalWritable.test.ts, libraries/node-core-library/src/Terminal/test/__snapshots__/TerminalWritable.test.ts.snap, libraries/node-core-library/src/index.ts
Adds a new class `TerminalWritable` to `@rushstack/node-core-library` which allows for creating a `Writable` stream that pipes all written chunks out to the provided `ITerminal`.
Added tests and validated output snapshots. Another implementation of this has been used internally for a while now.
New API added to `@rushstack/node-core-library`
=> [node-core-library] Add TerminalWritable Adapter

common/changes/@microsoft/rush/enelson-http-cache-2_2023-04-19-17-43.json, rush-plugins/rush-http-build-cache-plugin/src/HttpBuildCacheProvider.test.ts, rush-plugins/rush-http-build-cache-plugin/src/HttpBuildCacheProvider.ts
Add basic HTTP retry logic to the http build cache plugin.
It might be nice to have configurable retry attempts and timeout values, but a basic implementation with a few retries is a must-have just to weather inevitable transient 503s (for example, from a backing S3 storage or similar service).
This PR adds built-in retries, up to 3 attempts with ~2.5 second delay, to the http build cache plugin.
=> [rush] Add basic retry logic to http build cache plugin

build-tests/install-test-workspace/workspace/rush-sdk-test/src/start.ts, common/changes/@microsoft/rush/check-for-phantom-node-modules-folders_2023-05-01-22-07.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/assets/rush-init/common/config/rush/experiments.json, libraries/rush-lib/src/api/ExperimentsConfiguration.ts, libraries/rush-lib/src/cli/actions/BaseInstallAction.ts, libraries/rush-lib/src/cli/actions/InstallAction.ts, libraries/rush-lib/src/cli/actions/PublishAction.ts, libraries/rush-lib/src/cli/actions/UpdateAction.ts, libraries/rush-lib/src/cli/actions/VersionAction.ts, libraries/rush-lib/src/logic/Git.ts, libraries/rush-lib/src/logic/RushConstants.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/base/BaseInstallManagerTypes.ts, libraries/rush-lib/src/logic/policy/EnvironmentPolicy.ts, libraries/rush-lib/src/logic/policy/GitEmailPolicy.ts, libraries/rush-lib/src/logic/policy/PolicyValidator.ts, libraries/rush-lib/src/logic/policy/RushPolicy.ts, libraries/rush-lib/src/logic/policy/ShrinkwrapFilePolicy.ts, libraries/rush-lib/src/schemas/experiments.schema.json
Adds a policy that checks for phantom `node_modules` folders that are resolvable from inside the repo. This does not check inside folders between project folders and the repo root.
Created the issue and confirmed that it creates an error.
Will need to be added to experiments configuration docs.
=> [rush] Add a "forbidPhantomResolvableNodeModuleFolders" experiment that forbids node_modules folders in the repo root and in parent folders.

common/changes/@microsoft/api-extractor-model/octogonz-fix-overloadindex-docs_2023-05-03-18-30.json, libraries/api-extractor-model/src/mixins/ApiParameterListMixin.ts
This problem was identified in https://github.com/microsoft/tsdoc/pull/346
Clarify that `overloadIndex` counts from `1`, as does TSDoc's `DocMemberSelector`.
=> [api-extractor] Fix incorrect documentation for ApiParameterListMixin.overloadIndex

build-tests/localization-plugin-test-02/src/indexA.ts, build-tests/localization-plugin-test-02/webpack.config.js, common/changes/@rushstack/webpack4-module-minifier-plugin/fix-async-import-compression_2023-05-03-18-25.json, webpack/webpack4-module-minifier-plugin/src/AsyncImportCompressionPlugin.ts
Fixes an crash in `@rushstack/webpack4-module-minifier-plugin` when `compressAsyncImports: true` and some imports target modules that have been excluded from the compilation.
Updates code that rewrites async imports to verify that the target of the import is part of the module graph first.
Updated `build-tests/localization-plugin-test-02` to include an import of an ignored module.
None.
=> [module-minifier-plugin] Fix import compression

common/changes/@rushstack/module-minifier/bump-terser_2023-05-04-00-05.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, libraries/module-minifier/package.json
Reverts to the previous minimum version of `terser`, `5.9.0` but lets the version float.
Existing unit tests validate the current installed version.
None.
=> [module-minifier] Use terser@^5.9.0

common/changes/@rushstack/package-extractor/user-danade-ExportMetadataFileType_2023-05-04-22-11.json, common/reviews/api/package-extractor.api.md, libraries/package-extractor/src/PackageExtractor.ts, libraries/package-extractor/src/SymlinkAnalyzer.ts, libraries/package-extractor/src/index.ts
Exports typings for the `extractor-metadata.json` file that is produced when exporting a package. Additionally, this change will add a new field `projectName` to the generated `extractor-metadata.json` file.
=> [package-extractor] Expose extractor-metadata.json file type and include `projectName` in output

common/changes/@microsoft/rush/cleaner-cache-support_2023-04-30-13-02.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/BuildCacheConfiguration.ts, libraries/rush-lib/src/pluginFramework/RushSession.ts, rush-plugins/rush-amazon-s3-build-cache-plugin/src/RushAmazonS3BuildCachePlugin.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/RushAzureStorageBuildCachePlugin.ts, rush-plugins/rush-http-build-cache-plugin/src/RushHttpBuildCachePlugin.ts, rush-plugins/rush-http-build-cache-plugin/src/test/HttpBuildCacheProvider.test.ts
This is a follow-up to https://github.com/microsoft/rushstack/pull/3976.
Tested by running a build in a repo that uses the Azure Storage cache provider.
The custom cache provider docs may need to be updated.
=> [rush] Update the RushSession.registerCloudBuildCacheProviderFactory API to allow a cache provider's factory function to return a promise.

build-tests/heft-webpack4-everything-test/tsconfig.json, common/changes/@rushstack/heft-lint-plugin/heft-rc-fix-double-lint_2023-05-08-21-08.json, common/changes/@rushstack/heft-typescript-plugin/heft-rc-fix-double-lint_2023-05-08-21-08.json, heft-plugins/heft-lint-plugin/src/Eslint.ts, heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts
Fixes a bug in which the lint plugin would get invoked twice for a project that sets `"incremental": true` in `tsconfig.json`.
Removes a duplicate invocation of the `emitChangedFilesCallback` function in the single-project incremental build code path.
Adds coverage of the single-project incremental build code path to the `build-tests` projects via `heft-webpack4-everything-test` (by setting `"incremental": true` in `tsconfig.json`).
Updates the linter logging behavior to sort rule timings by descending duration, rather than the previous behavior of not having any particular pattern.
Manual invocation of `npm run build -- --verbose` in `heft-webpack4-everything-test` and monitoring the log.
None.
=> [heft-next] Fix double invocation of linter

common/changes/@microsoft/rush/tweak-log-verbosity_2023-05-09-21-24.json, libraries/rush-lib/src/logic/ProjectWatcher.ts
Reduce watch status updates to a single line with interactive clearing and rewriting.
Local run of `apps/rush/lib/start-dev.js start`.
None
=> [rush] Single-line watch status

common/changes/@rushstack/heft-sass-plugin/sass-embedded_2023-05-10-20-37.json, common/config/rush/nonbrowser-approved-packages.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, heft-plugins/heft-sass-plugin/README.md, heft-plugins/heft-sass-plugin/package.json, heft-plugins/heft-sass-plugin/src/SassProcessor.ts
Switch from `sass` to `sass-embedded` for improved SASS compiler performance.
The `sass` package is the Dart implementation of the SASS compiler transpiled to JavaScript
The `sass-embedded` package is the Dart implementation of the SASS compiler packaged as a native executable communicating via IPC.
The JavaScript transpilation contains various constructs that perform extremely poorly in JavaScript.
Full retest run.
Readme for heft-sass-plugin.
=> [heft-sass] Switch to sass-embedded

common/changes/@rushstack/node-core-library/dynamic-prefix_2023-05-11-21-15.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/Terminal/PrefixProxyTerminalProvider.ts, libraries/node-core-library/src/Terminal/test/PrefixProxyTerminalProvider.test.ts, libraries/node-core-library/src/Terminal/test/__snapshots__/PrefixProxyTerminalProvider.test.ts.snap, libraries/node-core-library/src/index.ts
This PR adds an option to `PrefixProxyTerminalProvider` called `getPrefix` which takes a function that returns a string to dynamically generate the prefix. This can be used for prefixing logging lines with timestamps.
Included a unit test.
=> [node-core-library] Add an option to the PrefixProxyTerminalProvider to create a dynamic prefix.

heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts
Ensures that the watchOptions section of tsconfig gets forwarded to the watchCompilerHost.
Running under debugger with a project configured with `watchOptions` in tsconfig.
None
=> [heft-typescript@next] Forward watch options

common/changes/@microsoft/rush/silent-noops_2023-05-11-22-50.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/CommandLineConfiguration.ts, libraries/rush-lib/src/api/CommandLineJson.ts, libraries/rush-lib/src/index.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunnerPlugin.ts, libraries/rush-lib/src/schemas/command-line.schema.json
Adds the ability to silence logging from phases that aren't defined in a given project.
Adds a new configuration option `missingScriptBehavior` to phase definitions in `command-line.json`.
Current allowed values:
`error` - Throws an error if not defined, as `ignoreMissingScript: false` (which it replaces) (default)
`log` - Logs a no-op if not defined, as `ignoreMissingScript: true` (which it replaces)
`silent` - Does not log at all if not defined. Net new behavior.
Enabled in the local rushstack repository for `_phase:test` and validated that `rush test -v` no longer logged any no-ops for `_phase:test`.
Docs around command-line.json regarding phase definitions.
=> [rush] Add ability to silence noops in the logs

.vscode/launch.json, build-tests/heft-typescript-composite-test/src/indexA.ts, build-tests/heft-typescript-composite-test/src/indexB.ts, build-tests/heft-typescript-composite-test/tsconfig-base.json, build-tests/heft-webpack4-everything-test/config/typescript.json, build-tests/heft-webpack4-everything-test/package.json, build-tests/heft-webpack4-everything-test/src/indexA.ts, build-tests/heft-webpack4-everything-test/src/indexB.ts, build-tests/heft-webpack4-everything-test/tsconfig.json, common/reviews/api/heft-typescript-plugin.api.md, heft-plugins/heft-typescript-plugin/src/TranspilerWorker.ts, heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts, heft-plugins/heft-typescript-plugin/src/TypeScriptPlugin.ts, heft-plugins/heft-typescript-plugin/src/configureProgramForMultiEmit.ts, heft-plugins/heft-typescript-plugin/src/internalTypings/TypeScriptInternals.ts, heft-plugins/heft-typescript-plugin/src/schemas/typescript.schema.json, heft-plugins/heft-typescript-plugin/src/types.ts, heft-plugins/heft-typescript-plugin/tsconfig.json
Adds a new option in `typescript.json`, `useTranspilerWorker`, that if `true`, and the tsconfig has `isolatedModules: true`, will split transpilation into a worker thread and run it in parallel with the type checker.
If opted in and the tsconfig is compatible, will start a worker thread and hand it the list of changed source files and the emit options. Multi-emit then occurs only in the worker, since declaration files are only emitted for the primary module kind.
Local runs on projects in various configurations. Still needs more testing against large projects with `isolatedModules: true` to determine if the performance is significantly improved.
Verified in both watch and non-watch mode.
Verified using project references.
Documentation for `typescript.json`.
=> [heft-typescript@next] Add "useTranspilerWorker" option

common/changes/@rushstack/debug-certificate-manager/cert-fixes_2023-05-08-22-16.json, common/reviews/api/debug-certificate-manager.api.md, libraries/debug-certificate-manager/src/CertificateManager.ts
Adds an environment variable `DISABLE_DEV_CERT_GENERATION` that can be set to `1` on the machine to cause all calls to generate a new dev certificate to be an error. This is most relevant to GitHub codespaces, where the certificate needs to be kept in sync with a certificate on the client machine to successfully connect.
Removes `rushstack.localhost` from this list of required `subjectAltNames` again to avoid forcing certificate regeneration.
Switches `127.0.0.1` to be properly flagged in the X.509 certificate as an IP Address, rather than a DNS name.
Local run.
Validated that `https://127.0.0.1:8080` now has a secure connection to `npm start` in `heft-webpack5-everything-test`.
None, currently.
=> [debug-cert] Add env, fix IP address

common/changes/@microsoft/rush/feature-custom-hooks-log-telemetry_2023-05-23-19-53.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/pluginFramework/PhasedCommandHooks.ts
Exposes a _beforeLog_ hook that can be used to modify the telemetry object before it gets written in the temporary telemetry folder. This allows plugin writers to add custom fields in the telemetry.
Manual tests where a custom Rush plugin was created and attached to the _beforeLog_ hook to add more data to the telemetry payload.
=> [rush-lib] Expose beforeLog hook to augment/modify telemetry logs

common/changes/@rushstack/node-core-library/json-file-redundant-encode_2023-05-26-23-54.json, libraries/node-core-library/src/JsonFile.ts
Removes a useless `Buffer -> String -> Buffer` conversion during `JsonFile.save` and `JsonFile.saveAsync`.
For large JSON files this can save a decent chunk of time during serialization.
Locally used JsonFile.save and JsonFile.saveAsync to write files and validated the output is correctly encoded.
None
=> [node-core-library] Remove extra JsonFile encode

common/changes/@microsoft/rush/rush-boot-parse-perf_2023-05-30-17-40.json, libraries/rush-lib/src/api/RushConfigurationProject.ts
Since `package.json` files are required by NodeJS to be strict JSON, switches parsing in `RushConfigurationProject` from `jju.parse` to `JSON.parse` to improve performance.
Compared CPU profiles of with and without the change when running `rush list`. With the change reduced the time spent initializing `RushConfigurationProject` instances by roughly 50%.
Not a behavior change, so none.
=> [rush] Use JSON.parse for package.json

heft-plugins/heft-typescript-plugin/src/TranspilerWorker.ts, heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts, heft-plugins/heft-typescript-plugin/src/types.ts
Slight performance tuning of the transpiler worker (enabled by `useTranspilerWorker: true` in `typescript.json` when `isolatedModules: true` in `tsconfig`).
Passes the already-loaded source file text via postMessage instead of re-reading from disk.
Running the built compiler against a fairly large internal project that has these options enabled and collecting CPU profiles.
None, currently.
=> [heft-typescript@next] Tune transpiler worker

heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts
Optimize the cleanup of the worker process.
Remove the `TypeScriptCachedFileSystem`, since TypeScript does caching internally.
Removes up to half a second of dead time from expressly waiting for the worker to exit.
Instead include error/exit handlers in the individual transpile callbacks. If the worker exits with non-zero after all pending transpiles have already finished, we don't really care.
Removes unneeded code in the form of the caching file system. TypeScript's internal fs wrapper already does caching.
Local runs.
None.
=> [heft-typescript@next] More transpile tuning

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, heft-plugins/heft-typescript-plugin/src/TranspilerWorker.ts, heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts
Fixes the support for emitting TypeScript output with alternate file extensions.
The `writeFile` callback must be passed to `program.emit()` in order for extension renaming to work, as currently written.
The `heft-jest-reporters-test` project tests this scenario.
None, since the internals of the TypeScriptBuilder are not part of the public API.
=> [heft-typescript@next] Fix typescript alternate extension emit

heft-plugins/heft-typescript-plugin/src/TranspilerWorker.ts
If `verbatimModuleSyntax` is not enabled, the type checker needs to be run to determine which imports are used, or else the transpiler will produce invalid output.
Updates the set of options used in the case when `verbatimModuleSyntax` is disabled.
Using the `heft-jest-reporters-test` project with the worker manually enabled and various tsconfig options.
None, other than that it should be noted that `useTranspilerWorker` should really only be enabled if `verbatimModuleSyntax` and `isolatedModules` are both `true`. If the latter is false, it does nothing; if the former is false, it might not save any appreciable amount of time.
On inspection, even without the optimal fast path, it can still be faster to use the worker, just not as fast as it could be.
=> [heft-typescript] Trade perf for correctness in transpile worker

apps/heft/UPGRADING.md, heft-plugins/heft-api-extractor-plugin/package.json, heft-plugins/heft-lint-plugin/package.json, heft-plugins/heft-typescript-plugin/package.json
Reverts the net-new heft plugin packages to 0.0.0, to publish as 0.1.0.
Fixes version references in @rushstack/heft/UPGRADING.md
N/A
None
=> [heft-next] Fix versions in docs and new plugins

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@rushstack/heft-sass-plugin/bump-sass-embedded_2023-06-01-23-38.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, heft-plugins/heft-sass-plugin/package.json
Upgrade sass-embedded to ~1.62.0 for various fixes and to source the binary from the npm feed.
rush test -v
None
=> [heft-sass] Bump sass embedded to ~1.62.0

common/changes/@microsoft/rush/issue_1335_2023-06-02-20-54.json, common/config/rush/version-policies.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/assets/rush-init/common/config/rush/version-policies.json, libraries/rush-lib/src/api/VersionPolicy.ts, libraries/rush-lib/src/api/test/VersionPolicy.test.ts, libraries/rush-lib/src/cli/actions/VersionAction.ts, libraries/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap, libraries/rush-lib/src/logic/PublishUtilities.ts, libraries/rush-lib/src/schemas/version-policies.schema.json
Remove references to preminor and release in code, documentation, and tests.
Fixes #1335
=> [rush-lib] remove redundant or broken references to preminor and release

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@rushstack/heft-typescript-plugin/typescript-resolve-config_2023-06-05-20-48.json, heft-plugins/heft-typescript-plugin/src/TypeScriptPlugin.ts
Switches back to using `path.resolve` instead of raw string concatenation for resolving the path to `tsconfig` file.
Fixes #4159 
Local runs of the heft-typescript-composite-test and other projects, though was unable to reproduce the original bug.
None.
=> [heft-typescript] Switch back to path.resolve for tsconfig resolution

build-tests-samples/heft-storybook-react-tutorial/config/jest.config.json, build-tests/heft-minimal-rig-test/profiles/default/config/jest.config.json, build-tests/heft-sass-test/config/jest.config.json, build-tests/heft-webpack4-everything-test/config/jest.config.json, build-tests/heft-webpack5-everything-test/config/jest.config.json, common/changes/@rushstack/heft-jest-plugin/jest-config-fork_2023-06-06-01-55.json, common/changes/@rushstack/heft-node-rig/jest-config-fork_2023-06-06-01-55.json, common/changes/@rushstack/heft-web-rig/jest-config-fork_2023-06-06-01-55.json, heft-plugins/heft-jest-plugin/includes/jest-shared.config.json, heft-plugins/heft-jest-plugin/includes/jest-web.config.json, rigs/heft-node-rig/profiles/default/config/jest.config.json, rigs/heft-web-rig/profiles/app/config/jest.config.json, rigs/heft-web-rig/profiles/library/config/jest.config.json
Adds a new base config for web projects.
Updates "customExportConditions" field for web and node projects.
Node projects will now use `["require", "node"]`.
Web projects will use `["require", "node", "umd"]`, because `"browser"` tends to return ESM, and Jest is configured to run CommonJS.
`rush test -v`
Matching behavior used in external repos that consume the rigs.
Any docs about the base config.
=> [heft-jest] Add customExportConditions, web config

common/changes/@microsoft/rush/pr-4167_2023-06-06-09-30.json, libraries/rush-lib/src/api/RushConfiguration.ts
=> [rush-lib] fix typo on `startingFolder`

common/changes/@microsoft/rush/silence-cache-logging-in-quiet-mode_2023-06-06-22-17.json, common/changes/@microsoft/rush/silence-cache-logging-in-quiet-mode_2023-06-06-22-19.json, libraries/rush-lib/src/logic/operations/ProjectLogWritable.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts
This fixes a regression where cache logs were always written to stdout. It also creates `*cache.log` files for that data.
Ran `rush build` in a repo with caching enabled.
=> [rush] Silence cache logs in quiet mode and write cache logs to a `*.cache.log` file.

common/changes/@rushstack/eslint-patch/eslint-patch-4172-fix-import-path_2023-06-07-15-09.json, eslint/eslint-patch/src/modern-module-resolution.ts
fixes #4172 
using `prettier-eslint` with the `nextjs` eslint module fails due to the module path loading. 
the error being thrown is `TypeError [ERR_INVALID_ARG_VALUE]` so in the catch where `isModuleResolutionError` is checked it returns false (different error type) and it never reaches trying to load the module via `relativePath`.
the solution [listed in this issue](https://github.com/prettier/prettier-eslint-cli/issues/434#issuecomment-1207331852) works perfectly. 
this PR fixes the issue by introducing another error checker `isInvalidImporterPath` looking for this type of error. if either `isModuleResolutionError` or `isInvalidImporterPath` are true then it will use the `relativePath`.
fully backwards compatible by simply introducing an additional branch of logic. 
ran …
=> [eslint-patch] add check for invalid module path to fallback to relative path when loading eslint modules for nextjs

apps/heft/src/plugins/NodeServicePlugin.ts, apps/heft/src/schemas/heft-legacy.schema.json, apps/heft/src/utilities/CoreConfigFiles.ts, apps/heft/tsconfig.json, common/changes/@rushstack/heft/user-danade-CheckLegacyHeft_2023-06-07-22-48.json
Provides a more useful error message when encountering a Heft configuration that matches the legacy format.
Fixes #4175
```text
PS D:\Work\rushstack3\libraries\rush-lib> node .\node_modules\@rushstack\heft\bin\heft build
Error: This project's Heft configuration appears to be using an outdated schema.
Heft 0.51.0 introduced a major breaking change for Heft configuration files. Your project appears to be using the older file format.  You will need to migrate your project to the new format. Follow these instructions: https://rushstack.io/link/heft-0.51
```
Locally using a Heft configuration that matched the legacy schema.
Needs link to be updated to be actual documentation.
=> [heft] Provide a more helpful error message when using legacy Heft configurations

common/changes/@rushstack/heft-typescript-plugin/typescript-solution-error_2023-06-08-20-38.json, heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts
The TypeScript compiler implicitly sets `noEmitOnError: true` when invoked in solution mode. This PR ensures that Heft enters an error state if the compiler does not emit outputs, so that subsequent build steps do not get processed.
In both watch and non-watch solution mode, if one or more warnings are encountered, also emits an informative error directing the user to fix the warnings to be able to continue, and why.
Using the heft-typescript-composite-test project, modified source code of the leaf tsconfig project to have a warning and validated that it enters the error state, both in watch mode and normal build mode.
Sample output:
```
[build:typescript] Warning: build-tests/heft-typescript-composite-test/src/test/ExampleTest.test.ts:12:9 - (TS6133) 'x' is declared but its value is …
```
=> [heft-typescript] Force emit an error if warnings are encountered in solution mode

apps/heft/.npmignore, apps/heft/UPGRADING.md, apps/heft/heft-plugin.json, apps/heft/src/configuration/HeftPluginConfiguration.ts, apps/heft/src/configuration/HeftPluginDefinition.ts, apps/heft/src/pluginFramework/HeftLifecycle.ts, apps/heft/src/pluginFramework/HeftTask.ts, apps/heft/src/plugins/RunScriptPlugin.ts, apps/heft/src/schemas/heft.schema.json, apps/heft/src/utilities/CoreConfigFiles.ts, apps/lockfile-explorer-web/config/heft.json, apps/lockfile-explorer/config/heft.json, build-tests/heft-copy-files-test/config/heft.json, build-tests/heft-fastify-test/config/heft.json, build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, build-tests/rush-lib-declaration-paths-test/config/heft.json, common/changes/@microsoft/rush/user-danade-RemoveTaskEvents_2023-06-08-06-44.json, common/changes/@rushstack/hashed-folder-copy-plugin/user-danade-RemoveTaskEvents_2023-06-08-06-44.json, common/changes/@rushstack/heft-node-rig/user-danade-RemoveTaskEvents_2023-06-08-06-44.json, common/changes/@rushstack/heft/user-danade-RemoveTaskEvents_2023-06-08-06-44.json, common/changes/@rushstack/lockfile-explorer/user-danade-RemoveTaskEvents_2023-06-08-06-44.json, libraries/rush-lib/config/heft.json, libraries/rush-sdk/config/heft.json, rigs/heft-node-rig/profiles/default/config/heft.json, webpack/hashed-folder-copy-plugin/config/heft.json
This PR removes the `taskEvent` option from tasks in heft.json, and replaces it with referencing the `@rushstack/heft` package plugins directly. It also allows for self-referencing of plugin packages.
The `taskEvent` API was duplicative and unnecessary when plugins provided by Heft could be provided by simply referencing the `@rushstack/heft` package directly as with any other plugin package. Additionally, this change also allows for the `pluginPackage` field to reference the owning package. This will allow for loading plugins specified within the same package that defines the configuration.
Plugin name mappings for previously-existing task events are:
- `copyFiles` -> `copy-files-plugin`
- `deleteFiles` -> `delete-files-plugin`
- `runScript` -> `run-script-plugin`
- `nodeService` -> …
=> [heft] Remove `taskEvent` configuration and replace it with directly-referenced plugins

common/changes/@rushstack/heft-jest-plugin/drieman-rushTestPathIgnorePatterns_2023-06-09-04-49.json, heft-plugins/heft-jest-plugin/heft-plugin.json, heft-plugins/heft-jest-plugin/src/JestPlugin.ts
Users sometimes need to run "all tests except..."
For example, one might have both unit tests and integration tests in the same project (even mixed in the same folders) and could need an exclusion pattern to run only the unit tests, or run only the integration tests.
Jest accepts the "testPathIgnorePatterns" CLI argument to support this but Heft-jest-plugin was not piping such an argument through.  This PR adds that missing support.
I simply followed the pattern of the existing similar "testPathPattern", to add the new "--test-path-ignore-patterns" argument which maps to the "testPathIgnorePatterns" Jest argument.
This is the second take at pushing the same feature due to major change conflicts accumulated while the original PR was waiting to merge.
After building, in my rushstack …
=> [heft-jest-plugin] Add --test-path-ignore-patterns CLI option.

apps/heft/CHANGELOG.json, common/changes/@rushstack/heft/main_2023-06-09-16-37.json
Heft's **CHANGELOG.md** was missing the `(BREAKING CHANGE)` identifier, which is particularly confusing since we've been using SemVer MINOR bumps for breaking changes while the major version number is `0`.
=> [heft] Clarify CHANGELOG.md

common/changes/@rushstack/set-webpack-public-path-plugin/remove-webpack-peerdep_2023-06-10-02-14.json, webpack/set-webpack-public-path-plugin/package.json, webpack/set-webpack-public-path-plugin/src/SetPublicPathPlugin.ts
`@rushstack/set-webpack-public-path-plugin` doesn't support Webpack 5. This PR removes the peerDependency on webpack 5 (because it will never do anything with Webpack 5) and changes the Webpack 5 warning into an error.
N/A
=> [set-webpack-public-path-plugin] Emit an error on Webpack 5 instead of a warning and remove the optional peerDependency on Webpack.

common/changes/@microsoft/rush/s3-build-cache-read-aws-creds_2023-06-02-00-43.json, rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3BuildCacheProvider.ts, rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Client.ts, rush-plugins/rush-amazon-s3-build-cache-plugin/src/AmazonS3Credentials.ts, rush-plugins/rush-amazon-s3-build-cache-plugin/src/index.ts, rush-plugins/rush-amazon-s3-build-cache-plugin/src/test/AmazonS3Client.test.ts, rush-plugins/rush-amazon-s3-build-cache-plugin/src/test/AmazonS3Credentials.test.ts
- check for existence of commonly used environment variables `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN`
- add unit tests for new function as well as existing function for `RUSH_BUILD_CACHE_CREDENTIAL`
- resolve #4115
Added a function for reading `AWS` vars that easily falls back to the Rush build cache env var if they aren't present. Refactored existing credential parsing (extracted out to module) to aid in unit testing. I considered importing https://github.com/aws/aws-sdk-js-v3/tree/main/packages/credential-provider-node but could not figure out build issues once added, it's possible they don't support TypeScript 5 yet. The `fromEnv` provider they export is essentially what I added here and it a trivial amount of code.
1. Assumed AWS IAM role using `aws sts …
=> [rush-amazon-s3-build-cache-plugin] Read credentials from common AWS_* env vars

common/changes/@microsoft/rush/main_2023-02-23-17-02.json, libraries/rush-lib/src/cli/actions/AddAction.ts, libraries/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap, libraries/rush-lib/src/logic/PackageJsonUpdater.ts, libraries/rush-lib/src/logic/PackageJsonUpdaterTypes.ts, libraries/rush-lib/src/npm-check-typings.d.ts
Add `--peer` flag to `rush add` command to add peerDepependencies to package.json
Fixes #1456
Invoked `rush add` with `--peer <packageName>` and confirmed that package was added successfully to package.json.
Also tested successfully with additional parameter `--exact` after the first command.
https://rushjs.io/pages/commands/rush_add/
=> [rush-lib] Support --peer flag for rush add command

apps/heft/src/configuration/HeftPluginDefinition.ts, apps/heft/src/pluginFramework/HeftParameterManager.ts, apps/heft/src/schemas/heft-plugin.schema.json, common/changes/@rushstack/heft-jest-plugin/user-danade-AmbiguousParameters_2023-06-12-18-40.json, common/changes/@rushstack/heft/user-danade-AmbiguousParameters_2023-06-12-18-40.json, common/changes/@rushstack/ts-command-line/user-danade-AmbiguousParameters_2023-06-12-18-40.json, common/reviews/api/ts-command-line.api.md, heft-plugins/heft-jest-plugin/heft-plugin.json, libraries/ts-command-line/src/parameters/BaseClasses.ts, libraries/ts-command-line/src/providers/CommandLineParameterProvider.ts, libraries/ts-command-line/src/providers/ScopedCommandLineAction.ts, libraries/ts-command-line/src/test/AmbiguousCommandLineParser.test.ts, libraries/ts-command-line/src/test/ConflictingCommandLineParser.test.ts, libraries/ts-command-line/src/test/__snapshots__/AmbiguousCommandLineParser.test.ts.snap
Before the upgrade to Heft, short-names were supported in Heft plugin custom parameters. This support was removed during the Heft upgrade to simplify handling of conflicting parameter names. This PR adds the support for short-names back to Heft, and enables the previously-used `-u` and `-t` short-names in `@rushstack/heft-jest-plugin`. Additionally, better handling of ambiguous parameter names was added to `@rushstack/ts-command-line` to support this feature.
`@rushstack/ts-command-line` now supports better reporting of ambiguous parameters, removing the need to limit Heft plugins to long-names only. The behavior is as follows:
- Ambiguous short-names are entirely disabled, because short-names cannot be deduped by using a scope. If an ambiguous short-name is provided, an error message …
=> [heft] Add support for short names to Heft plugins and provide better handling of ambiguous parameters

apps/heft/src/pluginFramework/HeftLifecycleSession.ts, apps/heft/src/pluginFramework/HeftTaskSession.ts, common/changes/@rushstack/heft/remove-deprecated-property_2023-06-13-03-22.json, common/reviews/api/heft.api.md
Follow-up to https://github.com/microsoft/rushstack/pull/4194#pullrequestreview-1476171281.
N/A
=> [heft] Remove the deprecated `cacheFolderPath` property from the session object

apps/heft/src/pluginFramework/logging/MockScopedLogger.ts, common/changes/@rushstack/heft-webpack4-plugin/heft-webpack-config-fallback_2023-06-13-21-07.json, common/changes/@rushstack/heft-webpack5-plugin/heft-webpack-config-fallback_2023-06-13-21-07.json, common/changes/@rushstack/heft/heft-webpack-config-fallback_2023-06-13-21-07.json, common/reviews/api/heft-webpack4-plugin.api.md, common/reviews/api/heft-webpack5-plugin.api.md, heft-plugins/heft-webpack4-plugin/src/Webpack4Plugin.ts, heft-plugins/heft-webpack4-plugin/src/WebpackConfigurationLoader.test.ts, heft-plugins/heft-webpack4-plugin/src/WebpackConfigurationLoader.ts, heft-plugins/heft-webpack4-plugin/src/index.ts, heft-plugins/heft-webpack4-plugin/src/shared.ts, heft-plugins/heft-webpack4-plugin/tsconfig.json, heft-plugins/heft-webpack5-plugin/src/Webpack5Plugin.ts, heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.test.ts, heft-plugins/heft-webpack5-plugin/src/WebpackConfigurationLoader.ts, heft-plugins/heft-webpack5-plugin/src/index.ts, heft-plugins/heft-webpack5-plugin/src/shared.ts, heft-plugins/heft-webpack5-plugin/tsconfig.json
Gives other Heft plugins that use the accessors from `@rushstack/heft-webpack4-plugin` and `@rushstack/heft-webpack5-plugin` the ability to define fallback behavior for the `onLoadConfiguration` accessor hook.
Previously, a plugin could either completely override the webpack config file via the `onLoadConfiguration` accessor hook, or, provided that a webpack config file was present and returned a value, use the `onConfigure` hook to modify a result.
This PR moves the loading of the webpack config file into the `onLoadConfiguration` hook at stage `STAGE_LOAD_LOCAL_CONFIG` so that plugins have the option to provide a default config in the absence of the config file, but have the config file take precedence.
Added unit tests to both plugin for the config loader pipeline.
Only the accessor …
=> [heft-webpack] Support config fallback via hook

common/changes/@microsoft/rush/git-hook-passthrough_2023-06-14-16-10.json, libraries/rush-lib/src/logic/base/BaseInstallManager.ts
New delegate git hook scripts do not pass through the args that git normally passes to commit hooks.
This ensures that all args are passed through.
Fixes #4200
Manually changed the commit hook delegate scripts in a test repo to mirror this change. Confirmed that this did then pass through the arguments from git.
=> [rush-lib] Git hook arg passthrough

common/changes/@microsoft/rush/fix-log-double-open_2023-06-14-18-49.json, libraries/rush-lib/src/logic/operations/ProjectLogWritable.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts
An issue was recently introduced where, in a project without phased builds, but with cache enabled, we'd try to open the `<projectName>.build.log` file twice. This PR makes the log always `<projectName>.<operationName>.log` and the cache always `<projectName>.<operationName>.cache.log`.
Fixes https://github.com/microsoft/rushstack/issues/4199
Tested against https://github.com/MsBeiBei/ANADI
=> [rush] Fix an issue where Rush would attempt to open a project's log file for writing twice.

common/changes/@rushstack/eslint-patch/eslint-patch-invalid-importer-path_2023-06-14-21-56.json, eslint/eslint-patch/src/modern-module-resolution.ts
adds the fix from #4174 to the ESLint 7.x || 8.x block 
during the previous patch the logic was moved to the 6.x block. it is safe to leave there but the original intent (to fix the bug that prompted the patch) was for it to be in the 7.x || 8.x block
ran `prettier-eslint` using the patch and it was fixed
none
=> [eslint-patch] add invalid importer path test to ESLint 7.x || 8.x block

common/changes/@rushstack/package-extractor/user-danade-PackageExtractorPatterns_2023-06-16-18-46.json, common/config/rush/pnpm-config.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, common/reviews/api/package-extractor.api.md, libraries/package-extractor/package.json, libraries/package-extractor/src/PackageExtractor.ts
When searching for all source files to be included in an extraction of a package, allow for providing `patternsToInclude` and `patternsToExclude` to limit which files get included from the local project.
Locally using various provided patterns.
=> [package-extractor] Allow for `patternsToInclude` and `patternsToExclude` to filter project files

apps/api-extractor/src/api/ExtractorConfig.ts, apps/heft/src/configuration/HeftConfiguration.ts, apps/heft/src/configuration/RigPackageResolver.ts, apps/heft/src/utilities/CoreConfigFiles.ts, build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@microsoft/api-extractor/IRigConfig_2023-06-19-22-00.json, common/changes/@rushstack/heft-config-file/IRigConfig_2023-06-19-22-00.json, common/changes/@rushstack/heft/IRigConfig_2023-06-19-22-00.json, common/changes/@rushstack/rig-package/IRigConfig_2023-06-19-22-00.json, common/reviews/api/api-extractor.api.md, common/reviews/api/heft-config-file.api.md, common/reviews/api/heft.api.md, common/reviews/api/rig-package.api.md, libraries/heft-config-file/src/ConfigurationFile.ts, libraries/rig-package/src/RigConfig.ts, libraries/rig-package/src/index.ts
Similar to `Terminal` vs `ITerminal`, this PR is creating an `IRigConfig` interface to be used in APIs to avoid issues with mismatched versions of `@rushstack/rig-package`.
Built.
The `IRigConfig` interface needs to be added to the API docs.
=> [rig-package] Expose an `IRigConfig` interface and use it in consuming projects' APIs.

common/changes/@rushstack/package-extractor/user-danade-FixPackageExtractorFilter_2023-06-26-21-41.json, libraries/package-extractor/src/PackageExtractor.ts
Package extractor allows for providing filters to modify the list of files to extract. However, because the file system traversal analyzes both folders and files, patterns that specified a subfolder of a non-matching parent folder would not be traversed and would be excluded from the generated extraction. This change ensures that all folders are traversed and only files are matched against the filters.
For example, if `patternsToInclude` is `src/**/*`, files within the `src` folder would not actually be collected, since `src` does not match the pattern `src/**/*` itself, even though the files and folders within do match.
Tested locally against the project that the issue was encountered in.
=> [package-extractor] Fix package extractor filter for subdirectories of non-matching folders

common/changes/@microsoft/rush/rush-lib-build-cleanup_2023-07-01-00-45.json, libraries/rush-lib/scripts/copyEmptyModules.js
Optimizing out a few syscalls during the customized build process for rush-lib.
Replaces the call to `ensureFolderAsync` with the `ensureFolderExists` argument to `writeFileAsync`.
Replaces the call to `copyFileAsync` with an explicit read + write to remove 2 redundant stat calls per file.
Fixes an inaccurate comment.
Analysis of strace output generated in rush-lib with the following command:
`strace -e t=%file -f -ttt -o strace.log node ./node_modules/@rushstack/heft/lib/start.js run --only build -- --clean`
None
=> [rush-lib] Minor build cleanup

common/changes/@rushstack/node-core-library/user-danade-FixSelfReferenceResolving_2023-07-05-22-43.json, libraries/node-core-library/src/Import.ts, libraries/node-core-library/src/test/Import.test.ts
The `Import.resolvePackage*` and `Import.resolveModule*` methods currently resolve the returned path without determining the real path to the package IFF using self-referencing and the path was found to exist. This causes the resolved but non-real path to be returned. This is unexpected, since these methods will resolve to the real-path in all other successful resolution scenarios.
This change fixes this issue and ensures that the real-path to the self-referenced module or package is returned.
Fixes #4221
- Added unit tests
- Verified locally
- Verified against issue specified in #4221
=> [node-core-library] Resolve self-referencing modules and packages to their real-path

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@rushstack/heft-typescript-plugin/fix-typescript-error_2023-07-11-21-40.json, heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts
Ensures that the "Typescript encountered X warnings and is configured to build project references" error message only is displayed when `buildProjectReferences` is `true`. This error message is only supposed to occur when using the `createSolutionBuilder` APIs in the TypeScript compiler, because when using those APIs, the compiler implicitly enables the `noEmitOnError` behavior.
Added a missing check to the condition for emitting the error.
None
=> [heft-typescript] Fix unexpected warning to error promotion

apps/api-extractor/src/api/ExtractorConfig.ts, common/changes/@microsoft/api-extractor/main_2023-03-20-14-36.json
TypeScript supports emitting and loading typings with `.d.cts` and `.d.mts` file extensions. We published a package which uses these extensions for its typings file, but it broke our api-extractor usage so we applied this patch.
This was the only place I found that specifically hard-coded the `.d.ts` requirement.
Sorry I don't have time to dig into how you're doing testing in this repo.
I don't think this affects any docs, or needs to be explicitly document itself.
=> [api-extractor] support .d.mts and .d.cts files

apps/heft/src/pluginFramework/HeftLifecycleSession.ts, apps/heft/src/pluginFramework/HeftTaskSession.ts, common/changes/@rushstack/heft/octogonz-tsdoc-fix_2023-07-12-06-06.json
@dmichon-msft this syntax was breaking the API website MDX because an unquoted `<pluginName>` is interpreted as an HTML tag.
=> [heft] Fix some incorrect TSDoc

apps/heft/src/cli/HeftActionRunner.ts, apps/heft/src/cli/actions/CleanAction.ts, apps/heft/src/operations/runners/LifecycleOperationRunner.ts, apps/heft/src/operations/runners/PhaseOperationRunner.ts, apps/heft/src/operations/runners/TaskOperationRunner.ts, apps/heft/src/pluginFramework/HeftLifecycle.ts, apps/heft/src/pluginFramework/HeftPluginHost.ts, apps/heft/src/plugins/CopyFilesPlugin.ts, apps/heft/src/plugins/DeleteFilesPlugin.ts, common/changes/@rushstack/heft/user-danade-WatchModeClean_2023-07-12-21-17.json
This PR does two things:
- Moves lifecycle cleaning to it's own operation, instead of piggybacking on the existing `start` lifecycle operation
- Adds support for the `--clean` flag in `heft *-watch` commands
Fixes #4228
Cleaning in watch mode is now performed only during the first-pass of the watch-mode operations. Once the clean has been completed, the clean will be ignored until the command is restarted. This allows starting from a fresh state during watch mode
Tested locally using `heft build`, `heft build --clean`, `heft build-watch` and `heft build-watch --clean`
Docs may need to be updated to indicate that `--clean` is now possible in watch mode.
=> [Heft] Reorganize lifecycle operation runner and support watch-mode cleaning

common/changes/@rushstack/heft-lint-plugin/lint-handle-malformed-file_2023-07-14-01-40.json, heft-plugins/heft-lint-plugin/src/LinterBase.ts
Handle the scenario where the lint cache file exists but is not valid JSON by treating it the same as when no cache file is present, rather than throwing.
Deliberately corrupted the cache file and ran an incremental build. Confirmed (when running with --verbose) that it detected the malformed cache file, and ran all rules on all files.
None
=> [heft-lint-plugin] Handle malformed cache

.vscode/launch.json, build-tests/heft-sass-test/config/heft.json, build-tests/heft-sass-test/config/rush-project.json, build-tests/heft-sass-test/config/sass.json, build-tests/heft-sass-test/src/ignored1.scss, build-tests/heft-sass-test/src/ignored2.scss, common/changes/@rushstack/heft-sass-plugin/fix-excludefiles_2023-07-16-15-18.json, heft-plugins/heft-sass-plugin/src/SassProcessor.ts
Fixes https://github.com/microsoft/rushstack/issues/3417
Updated the `excludeFiles` `config/sass.json` configuration option to map to a normalized value for the `globsToIgnore` option for the `@rushstack/typings-generator` package.
Introduced a test in `/build-tests/heft-sass-test`.
=> [heft-sass-plugin] Fix the 'excludeFiles' configuration option.

common/changes/@rushstack/webpack4-module-minifier-plugin/fix-module-minifier-length_2023-07-18-20-30.json, common/changes/@rushstack/webpack5-module-minifier-plugin/fix-module-minifier-length_2023-07-18-20-30.json, webpack/webpack4-module-minifier-plugin/src/RehydrateAsset.ts, webpack/webpack5-module-minifier-plugin/src/RehydrateAsset.ts, webpack/webpack5-module-minifier-plugin/src/test/AmdExternals.test.ts, webpack/webpack5-module-minifier-plugin/src/test/__snapshots__/AmdExternals.test.ts.snap
Ensures that the metadata about rendered positions and lengths of modules is accurately in character code counts, not UTF-8 bytes.
Needed to switch from Source.size() (which is in bytes) to Source.source().length.
Inspection of emitted snapshots.
None
=> [webpack-module-minifier] Fix units for rendered positions

.gitignore, build-tests-samples/heft-storybook-react-tutorial/config/heft.json, build-tests-samples/heft-storybook-react-tutorial/package.json, common/changes/@rushstack/heft-storybook-plugin/user-danade-StorybookProcess_2023-07-19-06-03.json, heft-plugins/heft-storybook-plugin/src/StorybookPlugin.ts
Runs Storybook as a forked Node process.
Running Storybook as a forked Node process provides us a few advantages over the existing approach:
- Storybook is executed directly as it expects to be run
- Avoids the overhead of loading the module synchronously
- Provides the ability to tweak the CLI args passed to Storybook without tweaking the process.argv of the Heft process
- Encapsulates of the stdout and stderr streams of Storybook, which allows for piping the output through an `ITerminal`
- Allows for forwarding all stderr output from the forked process to the Heft stdout, since all output is written to stderr in Storybook
- Potential performance improvements sourced from running Storybook as a separate process
Running the `heft-storybook-react-tutorial` project build
=> [heft-storybook-plugin] Run Storybook as a forked Node process

common/changes/@rushstack/heft-jest-plugin/fix-jest-environment-dep_2023-07-30-03-41.json, heft-plugins/heft-jest-plugin/package.json
`heft-jest-plugin` currently declares `testEnvironment` properties (`jest-environment-jsdom` for Web and `jest-environment-node` for Node), but isn't able to resolve those packages because they're devDependencies, meaning that a consumer extending that built-in Jest configs needs to declare its own dependency on one of those and re-declare a `testEnvironment` property.
This PR adds an optional peerDependency on those two packages, allowing a consumer (either a project or a rig) to just declare a dependency on the `jest-environment-` package.
=> [heft-jest-plugin] Make `jest-environment-jsdom` and `jest-environment-node` optional peerDependencies.

common/changes/@microsoft/rush/enelson-prepublish_2023-07-31-17-14.json, libraries/rush-lib/scripts/plugins-prepublish.js
The internal plugin `rush-http-build-cache-plugin` was added to the list of internal plugins, but not added to the prepublish script.
This PR should correctly bundle the plugin with Rush, similar to Azure and Amazon plugins.
- Update prepublish script
N/A
=> [rush] Bundle rush-http-build-cache-plugin

common/changes/@microsoft/rush/pnpmv8_2023-07-24-21-56.json, libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
This fixes an issue of incorrect package id when aliased package dependency is used.
It's possible to have package dependencies aliased like below:
```json
"@_ts/min": "npm:typescript@~4.2.4",
"@_ts/max": "npm:typescript@latest",
```
in pnpm-lock.yaml (v7), they are stored as
```yaml
dependencies:
'@_ts/max': /typescript/5.1.6
'@_ts/min': /typescript/4.2.4
```
Current logic returns package id of `/@ts/max@/typescript/5.1.6`, which is incorrect.
This PR returns the version string if it has a leading `"/"` already.
`rush update` is broken in our repo https://github.com/Azure/azure-sdk-for-js when using the latest rush stack.  With the change in this PR it is working again. I have checked all our dependencies and found no other cases of version having a leading `"/"` than the above one .
N/A
=> [rush-lib] Add support for npm aliases in `PnpmShrinkwrapFile._getPackageId`

common/changes/@microsoft/rush/improve-pnpm-shrinkwrap-modified_2023-07-25-12-11.json, libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts, libraries/rush-lib/src/logic/pnpm/test/PnpmShrinkwrapFile.test.ts, libraries/rush-lib/src/logic/pnpm/test/repo/apps/bar/package.json, libraries/rush-lib/src/logic/pnpm/test/repo/rush2.json, libraries/rush-lib/src/logic/pnpm/test/yamlFiles/pnpm-lock-v5/overrides-not-modified.yaml, libraries/rush-lib/src/logic/pnpm/test/yamlFiles/pnpm-lock-v6/inconsistent-dep-devDep.yaml, libraries/rush-lib/src/logic/pnpm/test/yamlFiles/pnpm-lock-v6/overrides-not-modified.yaml
Improve accuracy of detecting pnpm shrinkwrap modified
With `pnpm.overrides`, the version in package.json is different from the specifier in pnpm lockfile. This MR changes the logic to compare the overrided version with specifier in lockfile when necessary.
There is a chance that one package declared both in `dependencies` and `devDependencies` with inconsistent versions (absurd). This MR ignores the version in devDependencies when detecting for pnpm lockfile v6
NOTE: when detecting pnpm lockfile v5, the implementation iterates `specifiers` in lockfile where dev dependencies' versions never show up.
Test cases are added
No
=> [rush] Improve accuracy of detecting pnpm shrinkwrap is modified

common/changes/@rushstack/package-extractor/main_2023-08-04-01-56.json, common/config/rush/nonbrowser-approved-packages.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, common/reviews/api/package-extractor.api.md, libraries/package-extractor/src/PackageExtractor.ts, vscode-extensions/rush-vscode-extension/.gitignore, vscode-extensions/rush-vscode-extension/.npmignore, vscode-extensions/rush-vscode-extension/config/heft.json, vscode-extensions/rush-vscode-extension/package.json, vscode-extensions/rush-vscode-extension/src/scripts/generate-vscodeignore.ts, vscode-extensions/rush-vscode-extension/webpack.config.js
The `.vscodeignore` file does not follow the same semantics as `.npmignore`. This change generates a `.vscodeignore` file during build that explicitly lists all files that should be included in the package. As of this PR, that `.vscodeignore` file looks like:
```
**
!LICENSE
!dist/extension.js
!lib/extension.d.ts
!lib/extension.js
!lib/logic/RushCommandWebViewPanel.d.ts
!lib/logic/RushCommandWebViewPanel.js
!lib/logic/RushWorkspace.d.ts
!lib/logic/RushWorkspace.js
!lib/logic/logger.d.ts
!lib/logic/logger.js
!lib/providers/RushCommandsProvider.d.ts
!lib/providers/RushCommandsProvider.js
!lib/providers/RushProjectsProvider.d.ts
!lib/providers/RushProjectsProvider.js
!lib/providers/TaskProvider.d.ts
!lib/providers/TaskProvider.js
!package.json
!resources/rushstack.png …
```
=> [extension] Generate a .vscodeignore dynamically.

common/changes/@microsoft/rush/raihle-patch-4256_2023-08-03-15-04.json, libraries/rush-lib/src/scripts/install-run.ts
Resolves #4256
Fixes install-run.js behavior when there is only one version that matches the version query, or when the registry returns versions out of order.
As discussed in the issue, I added logic to sort the returned version numbers. There is no handling for pre-releases, but registries should only return them when they exactly match the query, meaning sorting is unnecessary.
This should not break backwards compatibility.
There may be some performance impact in cases where there are very many matching versions, but this is not exactly a hot code-path.
I compiled the script (`rush build --to @microsoft/rush-lib`) and then ran it (`node common/scripts/install-run.js ...`) with a few example packages.
This change should not impact documentation
=> [rush-lib] Improve version resolution logic in install-run.js

common/changes/@rushstack/typings-generator/typings-generator-read-file_2023-08-03-21-57.json, common/reviews/api/typings-generator.api.md, libraries/typings-generator/README.md, libraries/typings-generator/src/StringValuesTypingsGenerator.ts, libraries/typings-generator/src/TypingsGenerator.ts, libraries/typings-generator/src/index.ts
Adds the ability for consumers of `TypingsGenerator` to customize how files are read. Possible use cases include:
- Skipping reading files altogether, such as when generating .d.ts files that don't depend on the file content
- Reading from somewhere other than the file system
- Reading files as `Buffer` rather than `string`, or with alternate encoding
Figuring out the options interfaces for backwards compatibility was the toughest part of making this work. The `readFile` property needs to be optional if its return type is `string`, and required otherwise.
Local build.
Lab build.
Manual validation that the `readFile` property is required if the type of `fileContents` is not `string`.
Docs for TypingsGenerator.
=> [typings-generator] Support custom readFile

common/changes/@rushstack/eslint-patch/eslint-flat-config-support_2023-08-07-03-59.json, eslint/eslint-patch/src/modern-module-resolution.ts
Fixes a bug where VS Code's eslint extension + eslint-patch confuse each other
If all of the following apply to you:
- You're using VS Code with the eslint extension from Microsoft
- One of your eslint packages uses eslint-patch
- You're using the new flat config eslint has
- You've followed the instructions for the VS Code eslint extension and set `"eslint.experimental.useFlatConfig": true` in your VS Code settings (required, otherwise you get an error)
Eslint still won't work inside VS Code. This MR fixes that.
1. VS Code's eslint extension [uses `eslint/use-at-your-own-risk`](https://github.com/microsoft/vscode-eslint/blob/release/2.4.2/server/src/eslint.ts#L872) when you turn on flat config
2. eslint's `use-at-your-own-risk` [maps to …
=> fix(eslint-patch): fix for VS Code eslint extension with flat config enabled

common/changes/@microsoft/rush/rush-serve-compression_2023-08-08-18-20.json, common/config/rush/browser-approved-packages.json, common/config/rush/nonbrowser-approved-packages.json, common/config/rush/pnpm-config.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, rush-plugins/rush-serve-plugin/README.md, rush-plugins/rush-serve-plugin/package.json, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts, rush-plugins/rush-serve-plugin/tsconfig.json
Updates the rush-serve-plugin to support the following additional capabilities:
- HTTP/2
- GZip or Deflate compression of responses
- CORS Preflight Requests
- Access-Control-Allow-Private-Network (https://developer.chrome.com/blog/private-network-access-preflight/)
Leverages various existing middelware to support these features.
Local run of the server.
Only the docs for the plugin.
=> [rush-serve-plugin] Support cors, compression, http2

.github/workflows/ci.yml, common/changes/@microsoft/rush/fix-paths-changes-paths_2023-08-11-08-09.json, common/config/rush/version-policies.json, libraries/rush-lib/src/logic/ChangeFiles.ts
`rush-lib`'s unit tests are currently failing on Windows after https://github.com/microsoft/rushstack/pull/4264. This PR fixes the introduced issue and adds a Windows PR pipeline.
Ran `heft test` in `rush-lib` on Windows.
=> [rush] Fix an issue where changefiles would not be correctly discovered when running on Windows and add a Windows run.

.github/workflows/ci.yml, .gitignore, common/changes/@microsoft/rush/octogonz-node-18_2023-08-11-18-49.json, common/changes/@microsoft/rush/octogonz-node-18_2023-08-11-18-50.json, common/changes/@microsoft/rush/octogonz-node-18_2023-08-11-18-51.json, common/changes/@rushstack/heft-webpack4-plugin/octogonz-node-18_2023-08-11-18-32.json, heft-plugins/heft-webpack4-plugin/src/Webpack4Plugin.ts, libraries/rush-lib/assets/rush-init/[dot]gitignore, libraries/rush-lib/assets/rush-init/rush.json, libraries/rush-lib/src/logic/NodeJsCompatibility.ts, rush.json
Node 18 has been LTS since 2022-10-25, but our CI pipelines have not been building it because of incompatibility with Webpack 4.
- `heft-webpack4-plugin` now prints a warning if Node 18 is used without the `NODE_OPTIONS=--openssl-legacy-provider` workaround
- Enable this workaround in our CI pipelines
- Update `NodeJsCompatibility.ts` to specify 18 as the new LTS
- Upgrade rush.json to use PNPM 7.33.5
- I noticed that `autoinstaller.lock` sometimes appears in my Git diff view, so I've added `*.lock` to .gitignore and synced up the `rush init` template
@TheLarkInn @iclanton
=> Update our CI pipelines to include Node 18

common/changes/@microsoft/rush/fix-rush-scan_2023-08-11-01-24.json, libraries/rush-lib/src/cli/actions/ScanAction.ts
Fix a edge case when scanning package name with dot
Assuming the project imports `lodash.get`. Now the log is 
```
Starting "rush scan"
Possible phantom dependencies - these seem to be imported but aren't listed in package.json:
lodash         // <--- lodash instead of lodash.get
```
This PR fixes the log to print correct package name
```
Starting "rush scan"
Possible phantom dependencies - these seem to be imported but aren't listed in package.json:
lodash.get
```
Test it in a local repo by adding a line `import get from 'lodash.get'` to `src/index.ts`
No
=> [rush] rush scan package name with dot

common/changes/@microsoft/rush/shrinkwrap-only_2023-08-15-01-41.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/assets/rush-init/common/config/rush/experiments.json, libraries/rush-lib/src/api/ExperimentsConfiguration.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/base/BaseInstallManagerTypes.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/schemas/experiments.schema.json
Adds a new experiment flag "usePnpmLockfileOnlyThenFrozenLockfileForRushUpdate" that causes two separate invocations of `pnpm install` when running `rush update`: the first with `--lockfile-only`, and the second with `--frozen-lockfile`. This is intended to support repositories that leverage the `afterAllResolved` hook in `.pnpmfile.cjs` to alter the shape of the lockfile following dependency resolution.
Addresses an issue wherein rewriting the lockfile during `afterAllResolved` would result in broken symbolic links.
Running `rush update` against the local version and validating that `pnpm install` was invoked twice, the first time with `--lockfile-only --prefer-frozen-lockfile` and the second with `--frozen-lockfile`.
Only the experiment flag. Or guidance for when using the …
=> [rush] Support splitting `rush update` into "update lockfile" and "install from lockfile"

common/changes/@microsoft/rush/pnpm8-non-workspace-alias_2023-08-15-08-06.json, libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts, libraries/rush-lib/src/logic/pnpm/test/PnpmShrinkwrapFile.test.ts
Fixes https://github.com/microsoft/rushstack/issues/4274
There is an issue with the way `parsePnpmDependencyKey` in `PnpmShrinkwrapFile.ts` parses package aliases in repos that don't use workspaces. A partial V6 `pnpm-lock-yaml` file in such a repo looks like this:
```YAML
lockfileVersion: '6.1'
settings:
autoInstallPeers: true
excludeLinksFromLockfile: false
dependencies:
'@_ts/max':
specifier: npm:typescript@latest
version: /typescript@5.1.6
packages:
/typescript@5.1.6:
resolution: {integrity: sha512-zaWCozRZ6DLEWAWFrVDz1H6FVXzUSfTy5FUMWsQlU8Ym5JP9eO4xkTIROFCQvhQf61z6O/G6ugw3SgAnvvm+HA==}
engines: {node: '>=14.17'}
hasBin: true
dev: false
file:projects/project3.tgz:
resolution: {integrity: sha512-JzgaFd56J57GFwjddbjJr1tMBOUZrnjWGEs2OOEfjOG6F2201KOIod7kdBfwOsJf7yHrpEHqx8T7Khm21YsxVg==, …
```
=> [rush] Fix an issue where a pnpm-lock file would fail to parse if a project used a package alias in a repo using pnpm 8.

common/changes/@microsoft/rush/rush-serve-http1_2023-08-15-17-50.json, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts
Fixes an infinite recursion when a connection to the `@rushstack/rush-serve-plugin` was initiated using HTTP/1.
Updates the implementation of the `_headers` and `_implicitHeader` properties to only be overridden when using HTTP/2.
Used the updated server and made network requests to it.
None.
=> [rush-serve] Fix back-compat with HTTP/1

common/changes/@rushstack/terminal/octogonz-text-rewriter-transform_2023-08-24-04-44.json, libraries/terminal/src/TextRewriterTransform.ts, libraries/terminal/src/test/TextRewriterTransform.test.ts, libraries/terminal/src/test/__snapshots__/TextRewriterTransform.test.ts.snap
Fix a typo in the `onClose()` method for `TextRewriterTransform`.
I noticed this problem while helping to debug PR https://github.com/microsoft/rushstack/pull/3949.
The code is obviously wrong, but the effect is generally only noticeable in edge cases where the last line is of STDOUT is incomplete.
I added a unit test and confirmed that the edge case is fixed.
@iclanton @chengcyber
=> [terminal] Fix a minor logic issue for TextRewriterTransform cleanup

common/changes/@microsoft/rush/octogonz-update-autoinstaller-fix_2023-08-29-20-22.json, common/changes/@microsoft/rush/octogonz-update-autoinstaller-fix_2023-08-29-20-23.json, libraries/rush-lib/src/logic/Autoinstaller.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts
While trying to resolve https://github.com/microsoft/rushstack-websites/pull/193, I encountered a problem where `rush update-autoinstaller` was not performing a full upgrade, because it does not implement `rush install`'s workaround for https://github.com/pnpm/pnpm/issues/1890.
`rush update-autoinstaller`  tries to force a clean reinstall by deleting `pnpm-lock.yaml`, but PNPM has an unusual behavior where it tries to recover the deleted file using a backup copy from the `node_modules` folder. (Other package managers don't do that, but [the issue notes ](https://github.com/pnpm/pnpm/issues/1890) explains an obscure use case that justifies it.)  Rush works around this problem by deleting the backup file as well, but `rush update-autoinstaller` is missing that logic.
I also fixed a minor …
=> [rush] Fix issue where "rush update-autoinstaller" doesn't perform a full upgrade

common/changes/@microsoft/rush/run-before-install_2023-09-01-20-06.json, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/schemas/command-line.schema.json
Adds the `disableBuildCache` option to the schema for phased commands (it is already present for bulk commands). Setting this flag opts out of both the build cache and the legacy skip logic.
Also adds an internal property `_runsBeforeInstall` on `PhasedScriptAction`. Intended use case is for, e.g., #4229
Temporarily set up a custom command with the flag enabled and disabled and stepped through in the debugger to validate the code paths.
Docs for `command-line.json` for phased commands.
@chengcyber
=> [rush] Support "disableBuildCache" option in phased command schema

.github/workflows/ci.yml, build-tests-samples/heft-storybook-react-tutorial-storykit/package.json, build-tests-samples/heft-storybook-react-tutorial/package.json, build-tests-samples/heft-storybook-react-tutorial/webpack.config.js, build-tests/hashed-folder-copy-plugin-webpack4-test/package.json, build-tests/heft-sass-test/package.json, build-tests/heft-sass-test/webpack.config.js, build-tests/heft-webpack4-everything-test/package.json, build-tests/localization-plugin-test-01/package.json, build-tests/localization-plugin-test-02/package.json, build-tests/localization-plugin-test-03/package.json, build-tests/localization-plugin-test-03/webpack.config.js, build-tests/set-webpack-public-path-plugin-webpack4-test/package.json, build-tests/set-webpack-public-path-plugin-webpack4-test/webpack.config.js, common/changes/@rushstack/hashed-folder-copy-plugin/update-webpack_2023-09-06-21-11.json, common/changes/@rushstack/heft-webpack4-plugin/update-webpack_2023-09-06-21-11.json, common/changes/@rushstack/webpack4-localization-plugin/update-webpack_2023-09-06-21-11.json, common/changes/@rushstack/webpack4-module-minifier-plugin/update-webpack_2023-09-06-21-11.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, heft-plugins/heft-webpack4-plugin/package.json, heft-plugins/heft-webpack4-plugin/src/Webpack4Plugin.ts, webpack/hashed-folder-copy-plugin/package.json, webpack/webpack4-localization-plugin/package.json, webpack/webpack4-module-minifier-plugin/package.json
Original fix is here: https://github.com/webpack/webpack/pull/17628.
This PR also removes the `NODE_OPTIONS=--openssl-legacy-provider` env var and the warning about the `--openssl-legacy-provider` option in `@rushstack/heft-webpack4-plugin`.
=> Update Webpack dependencies to 4.47.0, which supports Node 18.

common/changes/@microsoft/rush/overlapping-unused-phases_2023-09-07-23-43.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/RushProjectConfiguration.ts, libraries/rush-lib/src/api/test/RushProjectConfiguration.test.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/operations/IOperationRunner.ts, libraries/rush-lib/src/logic/operations/NullOperationRunner.ts, libraries/rush-lib/src/logic/operations/ValidateOperationsPlugin.ts
This allows for an edge case where a Rush command runs multiple phases that projects may use one of and that cache the same folders. For example `_phase:build` and `_phase:tool-build` that take different arguments..
This change moves the `rush-project.json` validation out of the function that loads those files and introduces a `ValidateOperationsPlugin` that performs validation during the `beforeExecuteOperations` hook, after the operation graph has been generated. It sorts operations into projects, ignoring no-op operations, and each project's set of phases.
Tested in a repo with overlapping `_phase:build` and `_phase:tool-build`, and validated that a project that defines both still produces an error.
=> [rush] Allow overlapping phase outputs if both phases won't be executed by the project.

common/changes/@microsoft/rush/build-cache-watch_2023-09-07-22-33.json, common/changes/@microsoft/rush/build-cache-watch_2023-09-08-01-36.json, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/operations/CacheableOperationPlugin.ts
Fixes a bug in which project versions were incorrectly calculated in watch mode rebuilds.
Disables build cache writes when running in watch mode.
The instance of `ICreateOperationsContext` passed to the `beforeExecuteOperations` hook was incorrectly pinned to the initial version, rather than being invoked with the incremental instance.
Local run of `rush start`, validated cache miss on rerun when changing inputs.
Only the note that build cache writes don't occur during watch mode rebuilds (for performance reasons).
=> [rush] Fix interactions between the build cache and watch mode

common/changes/@microsoft/rush/rename-PnpmStoreOptions_2023-09-11-00-45.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/index.ts, libraries/rush-lib/src/logic/pnpm/PnpmOptionsConfiguration.ts
Renaming the `PnpmStoreOptions` type to `PnpmStoreLocation` because it isn't an options object.
=> [rush] Rename the PnpmStoreOptions type to PnpmStoreLocation.

common/changes/@rushstack/debug-certificate-manager/patch-2_2023-09-12-15-44.json, libraries/debug-certificate-manager/src/CertificateManager.ts
Fixes three issues in Certificate Manager:
1. `certutil.exe` appears to not write to stderr when it fails, so we should also log stdout.
2. Writing this as an error doesn't make sense, since this is an optional step (note the warning in the location where this is called). It is causing SPFx to detect this is a total task failure.
3. We are not awaiting the result of this call, so the above warning is not appearing.
See: https://github.com/SharePoint/sp-dev-docs/issues/9201#issuecomment-1715957297
This was tested by making these changes directly to installed versions of `@rushstack/debug-certificate-manager` inside a sample SPFx project.
N/A
=> CertificateManager issues when CertUtil fails to set friendly name

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@microsoft/rush/jiawen-expose-more-ids_2023-09-14-02-29.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/CustomTipsConfiguration.ts
In previous MR #4292, we support custom tips for pnpm-printed messages. 
In this MR we simply expose more IDs. The matching logic is based on pnpm's error code documents (https://pnpm.io/next/errors).
=> feat(rush-lib): Expose more tip IDs

common/changes/@rushstack/heft-jest-plugin/add-jest-log-heap-usage_2023-09-12-12-20.json, heft-plugins/heft-jest-plugin/heft-plugin.json, heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts, heft-plugins/heft-jest-plugin/src/JestPlugin.ts
This PR brings a new flag `--log-heap-usage`, and a corresponding change to the Reporter to show the heap usage for each test.
Jest logHeapUsage documentation is [here](https://jestjs.io/docs/cli#--logheapusage)
Useful to debug memory leaks. 
Manual testing.
Comments in the code and `rush change` json are provided.
=> [heft-jest-plugin] Add logHeapUsage

common/changes/@microsoft/rush/rush-serve-socket_2023-09-14-20-17.json, common/changes/@microsoft/rush/rush-serve-socket_2023-09-14-20-58.json, common/config/rush/nonbrowser-approved-packages.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/logic/operations/AsyncOperationQueue.ts, libraries/rush-lib/src/logic/operations/ConsoleTimelinePlugin.ts, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/OperationExecutionRecord.ts, libraries/rush-lib/src/logic/operations/OperationStatus.ts, libraries/rush-lib/src/logic/operations/test/AsyncOperationQueue.test.ts, rush-plugins/rush-serve-plugin/README.md, rush-plugins/rush-serve-plugin/package.json, rush-plugins/rush-serve-plugin/src/RushServePlugin.ts, rush-plugins/rush-serve-plugin/src/api.types.ts, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts, rush-plugins/rush-serve-plugin/src/schemas/rush-serve-plugin-options.schema.json
Adds a new configuration option `buildStatusWebSocketPath` to `@rushstack/rush-serve-plugin` that, when configured, enables a secure web socket server at `wss://localhost:${port}${buildStatusWebSocketPath}`.
A client can connect a `WebSocket` at the aforementioned path to receive information about the status of the current watch-mode build command.
Upon connecting a `WebSocket` to the server, the plugin will send a `sync` message that lists all current operations and their statuses, the overall status of the build, and some metadata about the current session (the name of the command, the machine the command is running on).
Whenever the status of one or more operations in the build graph changes, a `status-change` message will be sent with the new states of the affected operations.
Upon …
=> [rush-serve-plugin] Add build status monitoring via WebSocket

common/changes/@microsoft/rush/user-bharatmiddha-project-watcher-pause_2023-09-14-02-19.json, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/ProjectWatcher.ts
Add functionality to pause the project watcher when running `rush start`.
Added keyboard hook to listen for key presses. If `w` is pressed, toggle pause/resume. If `b` is pressed and the project watcher is paused, build once (by resuming then pausing again).
Tested by running `node ./apps/rush/lib/start-dev.js start ` in this repo
=> [rush-lib] add pause functionality to PhasedScriptAction

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@microsoft/rush/rush-lib-cleanup_2023-09-18-00-38.json, common/changes/@microsoft/rush/rush-lib-cleanup_2023-09-18-01-55.json, common/changes/@microsoft/rush/rush-lib-cleanup_2023-09-18-01-57.json, common/changes/@rushstack/terminal/rush-lib-cleanup_2023-09-18-00-44.json, common/changes/@rushstack/terminal/rush-lib-cleanup_2023-09-18-00-45.json, common/changes/@rushstack/terminal/rush-lib-cleanup_2023-09-18-00-46.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, common/reviews/api/rush-lib.api.md, common/reviews/api/terminal.api.md, libraries/rush-lib/assets/rush-init/common/config/rush/custom-tips.json, libraries/rush-lib/src/api/CustomTipsConfiguration.ts, libraries/rush-lib/src/api/test/CustomTipsConfiguration.test.ts, libraries/rush-lib/src/api/test/__snapshots__/CustomTipsConfiguration.test.ts.snap, libraries/rush-lib/src/api/test/repo/common/config/rush/custom-tips.json, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/schemas/custom-tips.schema.json, libraries/rush-lib/src/utilities/Utilities.ts, libraries/terminal/package.json, libraries/terminal/src/PrintUtilities.ts, libraries/terminal/src/test/PrintUtilities.test.ts, libraries/terminal/src/test/__snapshots__/PrintUtilities.test.ts.snap
This changes a few things:
- Removes fields from the `custom-tips.json` schema that had been removed in https://github.com/microsoft/rushstack/pull/4292
- Adds functionality to the `PrintUtilities.wrapWords` function to accept a line prefix, and use that in the new custom tips formatting.
- Fixes an issue where pnpm's installation progress line wasn't reprinted on a TTY console when there aren't any custom tips specified. Note that this is still an issue when there are custom tips, which needs more investigation.
Added more unit tests for `PrintUtilities` and tested custom tips in a small test repo.
=> [rush] Cleanup to the handling of PNPM custom tips.

apps/api-documenter/src/documenters/DocumenterConfig.ts, apps/api-documenter/src/documenters/YamlDocumenter.ts, apps/api-documenter/tsconfig.json, apps/api-extractor/src/api/ExtractorConfig.ts, apps/api-extractor/tsconfig.json, apps/heft/src/configuration/HeftPluginConfiguration.ts, common/changes/@microsoft/api-documenter/load-schema-via-import_2023-06-08-00-07.json, common/changes/@microsoft/api-extractor/load-schema-via-import_2023-06-08-00-07.json, common/changes/@microsoft/rush/load-schema-via-import_2023-06-08-00-07.json, common/changes/@rushstack/heft-api-extractor-plugin/load-schema-via-import_2023-06-08-00-07.json, common/changes/@rushstack/heft-jest-plugin/load-schema-via-import_2023-06-08-00-07.json, common/changes/@rushstack/heft-sass-plugin/load-schema-via-import_2023-06-08-00-07.json, common/changes/@rushstack/heft-typescript-plugin/load-schema-via-import_2023-06-08-00-07.json, common/changes/@rushstack/heft/load-schema-via-import_2023-06-08-00-07.json, common/changes/@rushstack/localization-utilities/load-schema-via-import_2023-06-08-00-07.json, heft-plugins/heft-api-extractor-plugin/src/ApiExtractorPlugin.ts, heft-plugins/heft-api-extractor-plugin/tsconfig.json, heft-plugins/heft-jest-plugin/src/JestPlugin.ts, heft-plugins/heft-jest-plugin/tsconfig.json, heft-plugins/heft-sass-plugin/src/SassPlugin.ts, heft-plugins/heft-sass-plugin/tsconfig.json, heft-plugins/heft-typescript-plugin/src/TypeScriptPlugin.ts, heft-plugins/heft-typescript-plugin/tsconfig.json, libraries/localization-utilities/src/parsers/parseLocJson.ts, libraries/localization-utilities/tsconfig.json, rush-plugins/rush-serve-plugin/src/RushProjectServeConfigFile.ts, rush-plugins/rush-serve-plugin/tsconfig.json
Load (almost) all schemas via import.
Removes path generation from schema schema references, isntead loading them via `import`s.
Built.
=> Load schemas via import.

common/changes/@microsoft/rush/fix-tty_2023-09-19-10-01.json, common/config/rush/version-policies.json, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
This change adds a `--reporter default` parameter to the args passed to pnpm if Rush is running in an environment with a TTY stdout. This fixes an issue where, when the pnpm output is being monitored to match custom tips, pnpm will detect a non-TTY stdout stream and use the `append-only` reporter. This reporter doesn't incrementally update the installation progress line, and instead repeatedly reprints that line down the console.
 
Docs on that parameter: https://pnpm.io/cli/install#--reportername
Tested in a repo with a nonexistent dependency and a `TIP_PNPM_NO_MATCHING_VERSION` custom tip defined.
=> [rush] Fix pnpm's install status printing when pnpm custom tips are defined.

common/changes/@microsoft/rush/pnpm-config-init_2023-09-20-15-37.json, libraries/rush-lib/assets/rush-init/common/config/rush/pnpm-config.json, libraries/rush-lib/src/logic/pnpm/PnpmOptionsConfiguration.ts
This is a bit of work we missed in #4316
Confirmed the `rush init` output is correct JSON.
@g-chao
=> [rush] Add "resolutionMode" to "rush init" template

apps/heft/src/operations/runners/PhaseOperationRunner.ts, apps/heft/src/pluginFramework/HeftTaskSession.ts, build-tests/heft-parameter-plugin-test/src/test/customParameter.test.ts, build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@rushstack/heft/heft-temp-folder-pattern_2023-09-20-00-47.json
Changes the naming convention for Heft's task temp folders from `<phase>.<task>` to `<phase>/<task>` so that the Rush build cache (or other tools interested in caching) can select a single well-formed folder to capture the entire phase's temp output.
Ensures that folders named `temp/<phase>.*` get cleaned.
Local build.
Any documentation concerning the temp folder path.
=> [heft] (BREAKING CHANGE) Put temp folders for tasks in parent for phase

common/changes/@microsoft/rush/main_2023-09-21-22-56.json, libraries/rush-lib/src/logic/operations/AsyncOperationQueue.ts, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/test/OperationExecutionManager.test.ts
Fixes a bug in which an operation failing does not block its consumers.
Fallout from adding the "Waiting" state to the operation graph. The code to cascade "blocked" status checked the wrong state, and there wasn't a test case.
Added unit test coverage.
None
=> [rush] Fix failures not blocking

common/changes/@microsoft/rush/pnpm-install-filter_2023-09-20-18-04.json, libraries/rush-lib/src/api/RushConfiguration.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts
Fixes #4285 
Sets the `dedupe-peer-dependents=false` option when passing filter arguments and installing with `--frozen-lockfile`.
Created a second git worktree and used the modified version of rush to run `rush install --to @rushstack/heft`:
```
Running "pnpm install" in /workspaces/rushstack-2/common/temp
Scope: 14 of 130 workspace projects
Lockfile is up to date, resolution step is skipped
.                                        | +507 +++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading registry.npmjs.org/typescript/5.0.4: 7.05 MB/7.05 MB, done
Progress: resolved 507, reused 0, downloaded 497, added 507, done
Done in 2.8s
```
None.
=> [rush] Fix filtered installs in pnpm@8

common/changes/@microsoft/rush/watch-mode-option_2023-09-23-03-02.json, libraries/rush-lib/src/logic/ProjectWatcher.ts
Make project watcher pause status and keybinds message show as part of watch status.
Before: `Watch Status: No changes detected to tracked files.`
After: `[WATCHING] Watch Status: No changes detected to tracked files. Press <w> to pause.`
Tested by running `node ../rushstack/apps/rush/lib/start-dev.js start`, making changes, toggling watch mode.
=> [rush-lib] Make the project watcher status and keyboard commands message more visible

common/changes/@rushstack/operation-graph/heft-watch-waiting_2023-09-25-22-14.json, libraries/operation-graph/src/Operation.ts
Fixes a build break in watch mode caused by the introduction of the OperationStatus.Waiting status value.
Also adds a compile-time exhaustiveness check to the offending switch-case statement.
Manual invocation of `heft test-watch` and changes to files.
Need to add unit tests for the watch mode flow, will investigate after this PR, since it is fixing a critical break and that would delay it.
None.
=> [heft] Fix watch mode

common/changes/@rushstack/operation-graph/operation-execution-test_2023-09-25-23-44.json, libraries/operation-graph/src/test/OperationExecutionManager.test.ts, libraries/operation-graph/src/test/__snapshots__/OperationExecutionManager.test.ts.snap
Adds unit test coverage for OperationExecutionManager.
Covers basic tree execution and the requestRun callback.
Ran said newly added tests.
None.
=> [operation-graph] Add execution tests

common/changes/@rushstack/eslint-patch/main_2023-09-26-06-27.json, eslint/eslint-patch/README.md, eslint/eslint-patch/custom-config-package-names.js
Follow-up to https://github.com/microsoft/rushstack/pull/4353.
=> [eslint-patch] Include a missing file and update the docs for @rushstack/eslint-patch.

apps/heft/src/cli/HeftActionRunner.ts, apps/heft/src/cli/actions/CleanAction.ts, common/changes/@rushstack/heft/fix-heft-clean_2023-09-26-20-16.json
Fixes https://github.com/microsoft/rushstack/issues/4351
`heft clean` was directly constructing an `AbortSignal` object via `new AbortSignal()`, which isn't allowed. This change refactors the code used in `HeftActionRunner` to construct the `AbortSignal` to also be used by `heft clean`.
Tested in this repo and in the repro provided in https://github.com/microsoft/rushstack/issues/4351.
=> [heft] Fix an issue where 'heft clean' crashes.

common/changes/@microsoft/rush/use-process-interactivity-when-being-in-tty_2023-09-28-12-51.json, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
Hello, this follows up the issue #4364 I opened where the project watcher would fail when the process is not started in interactive mode (i.e: no TTY). This is linked to a nice feature that was introduced in `5.107.0`.
In our own toolchain, we usually spawn Rush commands as child processes and most of the time we only want to pipe the output between processes, meaning that processes are spawned with no interactivity purposes. In that specific case, we are not able to do so and forced to inherit stdin to prevent the error from happening. 
About the fix, this is pretty straightforward, this just ensures that the TTY API + keyboard event listeners are only registered when the process is in TTY mode itself.
On our own Rush monorepo where the bug was discovered.
None, this is the desired …
=> [rush] Fix project watcher crash when the started process is not in TTY mode

common/changes/@rushstack/node-core-library/async-priority-queue_2023-09-27-19-06.json, common/changes/@rushstack/operation-graph/async-priority-queue_2023-09-27-19-07.json, common/reviews/api/node-core-library.api.md, common/reviews/api/operation-graph.api.md, libraries/node-core-library/src/Async.ts, libraries/node-core-library/src/MinimumHeap.ts, libraries/node-core-library/src/index.ts, libraries/node-core-library/src/test/MinimumHeap.test.ts, libraries/operation-graph/src/Operation.ts, libraries/operation-graph/src/OperationExecutionManager.ts, libraries/operation-graph/src/WorkQueue.ts, libraries/operation-graph/src/test/OperationExecutionManager.test.ts, libraries/operation-graph/src/test/WorkQueue.test.ts, libraries/operation-graph/src/test/__snapshots__/OperationExecutionManager.test.ts.snap
Updates the work scheduler in Heft to respect the passed in parallelism constraint for task execution.
Adds an implementation of a min heap to `@rushstack/node-core-library` with accompanying unit tests.
Uses said min heap and wraps it in a queue structure that iterates items until aborted.
Added unit tests for the min heap.
Added unit tests for the work queue.
Added unit tests to OperationExecutionManager that validate concurrency and priority.
Ran all build+test in the @rushstack repository, since this code is used by Heft.
API docs for @rushstack/node-core-library and @rushstack/operation-graph.
=> [operation-graph] Enforce concurrency limits

apps/api-documenter/src/documenters/MarkdownDocumenter.ts, apps/api-documenter/src/documenters/YamlDocumenter.ts, apps/api-extractor/src/generators/ApiModelGenerator.ts, common/changes/@microsoft/api-documenter/patch-1_2023-09-20-22-22.json, common/changes/@microsoft/api-extractor/patch-1_2023-09-20-22-22.json
It is useful for `@alpha` items to appear in metadata and generated documentation. The system currently unconditionally strips all `@alpha` items out.
I don't know how important it is to preserve existing behavior. If it is, perhaps this should be configurable somehow? Any feedback / suggestions would be appreciated.
I posted a question in the chatroom about this but have not yet heard back. I'll link to this PR from there as well.
=> Don't strip out `@alpha` items from generated reports

common/changes/@rushstack/package-extractor/user-danade-FixAdditionalFolderToCopy_2023-09-29-19-40.json, libraries/package-extractor/src/PackageExtractor.ts, libraries/package-extractor/src/test/PackageExtractor.test.ts
During the refactor to the `@rushstack/package-extractor` a change in behavior was accidentally introduced where the `folderToCopy` field was not included in the generated archive. Fixes #4371 
The `folderToCopy` field is now treated as if it were just another folder being traversed during extraction. The folder is explicitly mapped to the root of the target output folder/archive, just as previously spec'd.
Added a test to ensure that the copy operation behaves as it had previously.
=> [package-extractor] Ensure that the `folderToCopy` option is included in generated archives

README.md, build-tests/eslint-7-11-test/.eslintrc.js, build-tests/eslint-7-11-test/README.md, build-tests/eslint-7-11-test/config/rig.json, build-tests/eslint-7-11-test/package.json, build-tests/eslint-7-11-test/src/index.ts, build-tests/eslint-7-11-test/tsconfig.json, build-tests/eslint-7-7-test/.eslintrc.js, build-tests/eslint-7-7-test/README.md, build-tests/eslint-7-7-test/config/rig.json, build-tests/eslint-7-7-test/package.json, build-tests/eslint-7-7-test/src/index.ts, build-tests/eslint-7-7-test/tsconfig.json, build-tests/eslint-7-test/.eslintrc.js, build-tests/eslint-8-test/.eslintrc.js, common/changes/@rushstack/eslint-patch/user-danade-FixEslint7_2023-09-30-04-21.json, common/changes/@rushstack/tree-pattern/user-danade-FixEslint7_2023-09-30-04-21.json, common/config/rush/common-versions.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, eslint/eslint-patch/src/_patch-base.ts, libraries/tree-pattern/package.json, rush.json
Changes made in #4353 introduced compatibility issues with a specific range of ESLint 7 versions. This was caused by two different issues:
- a change in the logic which was an attempt to improve the speed of resolution of the required modules, and
- the `naming` module being moved from the standard `eslint` package to the `@eslint/eslintrc` package in 7.8.0, before the larger change to move the `config-array-factory` module there as well in 7.12.0.
This change fixes both issues, and adds new test projects for `eslint@7.7.0` and `eslint@7.11.0` to ensure that this issue does not arise again.
Fixes #4368
Added new test projects and confirmed that the patch is correctly consumed.
=> [eslint-patch] Fix patch compatibility with ESLint >=7.0.0 and <7.12.0

common/changes/@microsoft/rush/octogonz-rush-ancient-version_2023-10-04-23-03.json, libraries/rush-lib/src/logic/NodeJsCompatibility.ts
When invoked from Node.js 14.17.0 or earlier, recent releases of Rush now crash with the error shown below. Node 14 is no longer supported, but the problem is that ***our users don't know that,*** because the crash happens before Rush's incompatibility warnings get printed. As a result, our on-call was receiving support tickets from users confused by this error.
This is a regression caused by [PR #7](https://github.com/chengcyber/rushstack/pull/7/files#diff-f9234ed7851357be3cadb4d45ecbcf8253e90bfec1f8205fad71cd811cf5a565) which got merged into the Cobuilds PR.  It introduced an import with the `node:` prefix which is apparently a relatively new feature in Node.js:
```ts
import path from 'node:path';
```
I notice that some other plugins are now also using this syntax: …
=> [rush] Increase oldest usable Node.js version from 8.9.0 -> 14.18.0

common/changes/@microsoft/rush/chao-auto-install-peers_2023-10-03-20-48.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/assets/rush-init/common/config/rush/pnpm-config.json, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/pnpm/PnpmOptionsConfiguration.ts, libraries/rush-lib/src/schemas/pnpm-config.schema.json
PNPM8 changes the default value for `auto-install-peers` setting. It is default to true in
[PNPM8](https://pnpm.io/npmrc#auto-install-peers)
In this PR, we want to provide a option inside `pnpm-config.json` to let user overwrite `auto-install-peers` setting easily.
If user set auto-install-peers in `pnpm-config.json` only, use the value in `pnpm-config.json`
If user set auto-install-peers in `pnpm-config.json` and `.npmrc`, use the value in `pnpm-config.json`, and output a warning message
If user set auto-install-peers in `.npmrc` only, do nothing, let pnpm handle it
If user does not set auto-install-peers in both `pnpm-config.json` and `.npmrc`, rush will default it to `false`
Manually tested on rush-example repo. 
N/A
=> [rush-lib] Add autoInstallPeers in pnpm-config

apps/rush/CHANGELOG.json, apps/rush/CHANGELOG.md, common/changes/@microsoft/rush/octogonz-fix-rush-init_2023-10-07-00-46.json, common/config/rush/version-policies.json, libraries/rush-lib/assets/rush-init/rush.json
After running `rush init`, the resulting repository failed to build because of incorrect capitalization of `preRushX` and `preRushX`.
=> [rush] Fix typo in rush.json template

build-tests/install-test-workspace/build.js, build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
This is a temporary workaround for the PNPM problem discussed here:
https://github.com/pnpm/pnpm/issues/6778#issuecomment-1762418094
=> Workaround for issue where "install-test-workspace" sometimes freezes during "rush build"

common/changes/@microsoft/rush/main_2023-10-16-22-02.json, rush-plugins/rush-http-build-cache-plugin/src/HttpBuildCacheProvider.ts, rush-plugins/rush-http-build-cache-plugin/src/RushHttpBuildCachePlugin.ts, rush-plugins/rush-http-build-cache-plugin/src/test/HttpBuildCacheProvider.test.ts
The CWD may be set incorrectly when running `rush update-cloud-credentials --interactive` command with the `http` build cache provider configured.
Tested in a repo with this issue.
=> [rush] Fix an issue with the CWD of the http build cache provider's token handler script.

common/changes/@microsoft/rush/allow-skip-if-cache-disabled_2023-10-18-21-58.json, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
Ensure that if the build cache is configured, but the `buildCacheEnabled` flag is set to `false`, that the legacy skip detection logic is allowed to occur.
Fixes #4394 
The build cache (and thereby cobuilds) plugin will now only be applied if the build cache is both configured and enabled.
Temporarily changed `buildCacheEnabled` to `false` in `common/config/rush/build-cache.json` and verified that skip detection occurred when running `rush build`.
Any docs on build cache vs. skip.
=> [rush] Allow skip if cache configured but disabled

build-tests/heft-jest-reporters-test/config/jest.config.json, common/changes/@rushstack/heft-jest-plugin/octogonz-jest-console-log_2023-10-20-19-18.json, common/changes/@rushstack/heft-jest-plugin/octogonz-jest-console-log_2023-10-20-23-29.json, heft-plugins/heft-jest-plugin/src/JestPlugin.ts
**The problem:** When debugging code, it's common practice to add `console.log()` in various files to monitor variable states, while also interactively stepping through breakpoints in the VS Code debugger.  This experience is broken for unit tests, because Jest reroutes `console.log()` to a special handler that only prints the output after the test has completed.
Why would Jest do that?  The ideal model seems something like:
- When debugging tests, `console.log()` should print to the interactive console
- For a normal build, `console.log()` should fail the build, because nobody wants thousands of lines of noisy unit test output in their CI logs
However, perhaps this restriction was too difficult to enforce. Probably many projects will call `console.log()` as part of their normal …
=> [heft] "heft --debug test" and "heft test --verbose" should enable Jest's verbose mode

common/changes/@microsoft/rush/dmyers-shrinkwrap-filename_2023-10-18-19-31.json, libraries/rush-lib/src/api/RushConfiguration.ts
When using a rush-managed project with pnpm, occasionally, there are problems with the shrinkwrap file. The log message goes like `The shrinkwrap file is out of date. You need to run "rush update".` When working with yarn, there is a hard-coded hint as to _what_ the shrinkwrap file is: `The shrinkwrap file (yarn.lock) is out of date. You need to run "rush update".`
Since we have access to the name of the shrinkwrap file, I'm suggesting that we change to implementation to use that so that all package managers include a hint as to what shrinkwrap file it's talking about.
(covered above)
I tested this by running tests and manually reviewing in a pnpm and a yarn codebase.
=> [rush-lib] Use configured shrinkwrapFilename for logging shrinkwrapFilePhrase

common/changes/@rushstack/heft-jest-plugin/add-node-env-config-to-heft-jest-plugin_2023-09-26-12-02.json, heft-plugins/heft-jest-plugin/src/JestPlugin.ts, heft-plugins/heft-jest-plugin/src/schemas/heft-jest-plugin.schema.json, heft-plugins/heft-jest-plugin/src/test/JestPlugin.test.ts
Set the `NODE_ENV` env variable to test if not already set to something and a new test
Fixes #2420
When people migrate from jest to heft-jest this is often the pinpoint since jest sets this automatically https://jestjs.io/docs/environment-variables#node_env
We should respect this so people don't get discouraged because of a missing env variable.
A new test is added
We should update this https://heft.rushstack.io/pages/configs/environment_vars/#docusaurus_skipToContent_fallback
=> [heft-jest-plugin] set NODE_ENV if not already set

common/changes/@microsoft/rush/user-danade-FixConcurrency_2023-10-27-21-34.json, libraries/rush-lib/scripts/copyEmptyModules.js
Recent change #4401 added concurrent path traversal to the buildscript used by rush-lib. This however would allow for ballooning of the concurrency since it doesn't use the `AsyncQueue` class. This PR addresses this issue.
Tested locally by building rush-lib and confirming output.
=> [rush-lib] Fix concurrency of rush-lib build script

build-tests/hashed-folder-copy-plugin-webpack5-test/src/index.ts, common/changes/@rushstack/hashed-folder-copy-plugin/fix-windows-issue_2023-10-30-22-29.json, webpack/hashed-folder-copy-plugin/src/HashedFolderDependency.ts
Fix an issue where globbing assets from a NPM package would fail on Windows.
We used `path.posix.resolve`, which doesn't give a valid result if the second argument is a fully-qualified Windows path.
Added a test in the `hashed-folder-copy-plugin-webpack5-test` project.
None.
=> Fix an issue where globbing assets from a NPM package would fail on Windows.

apps/api-extractor/build-tests.cmd, apps/api-extractor/src/generators/ApiReportGenerator.ts, common/changes/@microsoft/api-extractor/octogonz-ae-undocumented-fix_2023-10-13-23-13.json, rush.json
Fix an edge case from PR https://github.com/microsoft/rushstack/pull/4370
Manually created a test project that reproduces the bug reported in https://github.com/microsoft/rushstack/pull/4370#issuecomment-1760606108 then confirmed it is fixed.
Rebuilt the entire Rush Stack monorepo using my PR build of `api-extractor`, confirmed that no existing API reports have any changes.
=> [api-extractor] Fix an issue where "ae-undocumented" was incorrectly reported for private members

common/changes/@rushstack/package-extractor/user-danade-FixExcludedLinks_2023-11-16-00-36.json, libraries/package-extractor/src/PackageExtractor.ts, libraries/package-extractor/src/SymlinkAnalyzer.ts
This change ensures that links to paths outside of the source directory are excluded if the path to the link is excluded explicitly using either of `patternsToInclude` or `patternsToExclude` options. Fixes #4421
Tested using repro provided in source issue.
=> [package-extractor] Ignore links to paths outside the source directory if explicitly excluded

common/changes/@microsoft/rush/feat-skip-build-with-warning-status_2023-09-20-06-34.json, common/config/rush/experiments.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/ExperimentsConfiguration.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/operations/LegacySkipPlugin.ts, libraries/rush-lib/src/schemas/experiments.schema.json
The problem: currently a build operation with warning is not allowed to use the incremental build (build skipping) feature. Consequently, the `package-deps_build.json` is not saved to disk which prevents further change detection in future runs. Preventing this is understandably a good default for discouraging build with warning, however, there are cases in which frameworks like Angular write to stderr for logs, which creates the warning. This make even newly generated projects non-skippable by default.
Just like the existing `buildCacheWithAllowWarningsInSuccessfulBuild` flag, it would be great to provide this flexibility to projects that conciously accept the risk or is hard to alter the default behaviours.
The proposed change:
- add a flag to support skipping build with status `sucess …
=> [rush-lib] Add experiment flag to allow skipping build with warning

common/changes/@microsoft/rush/main_2023-11-29-08-31.json, common/config/rush/version-policies.json, common/reviews/api/rush-azure-storage-build-cache-plugin.api.md, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureAuthenticationBase.ts
Allow custom options to be passed to the device code credential constructor. This allows the same base class to be used to query against Azure Key Vaults.
Tested in a repo that does Key Vault authentication.
=> [rush] Allow the device code credential options to be extended in subclasses Azure authentication subclasses.

common/changes/@microsoft/rush/bring-back-preminor_2023-12-11-22-59.json, common/config/rush/version-policies.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/assets/rush-init/common/config/rush/version-policies.json, libraries/rush-lib/src/api/VersionPolicy.ts, libraries/rush-lib/src/api/test/VersionPolicy.test.ts, libraries/rush-lib/src/cli/actions/VersionAction.ts, libraries/rush-lib/src/cli/test/__snapshots__/CommandLineHelp.test.ts.snap, libraries/rush-lib/src/logic/PublishUtilities.ts, libraries/rush-lib/src/schemas/version-policies.schema.json
Partially reverts https://github.com/microsoft/rushstack/pull/4157. Fixes https://github.com/microsoft/rushstack/issues/4445
The unit test is brought back.
This page needs to be updated: https://rushjs.io/pages/configs/version-policies_json/#:~:text=nextBump%22%3A%20%22prerelease
=> [rush] Bring back the erroneously removed 'preminor' bump type for lockstepped packages.

common/changes/@microsoft/rush/main_2023-12-11-23-29.json, common/changes/@rushstack/package-extractor/main_2023-12-11-23-28.json, libraries/package-extractor/src/PackageExtractor.ts, libraries/package-extractor/src/test/PackageExtractor.test.ts
Fixes https://github.com/microsoft/rushstack/issues/4444. This issue was introduced with this fix: https://github.com/microsoft/rushstack/pull/4373
Contrary to the documentation, the `folderToCopy` option was calling `path.dirname` on the folder's path and appending that to the target folder path. That step is removed in this PR.
Updated the unit test.
None.
=> [package-extractor] Fix an issue with the 'folderToCopy' option.

common/changes/@microsoft/rush/main_2023-12-23-05-43.json, libraries/rush-lib/assets/rush-init/common/config/rush/experiments.json, libraries/rush-lib/src/api/ExperimentsConfiguration.ts
We forgot to add `buildSkipWithAllowWarningsInSuccessfulBuild` to the **experiments.json** template
=> [rush] Update "rush init" template to document missing experiment

common/changes/@rushstack/node-core-library/json5-update_2023-12-28-07-24.json, libraries/node-core-library/src/JsonFile.ts, libraries/node-core-library/src/test/JsonFile.test.ts, libraries/node-core-library/src/test/__snapshots__/JsonFile.test.ts.snap
Fixes https://github.com/microsoft/rushstack/issues/4461
Updates the `updateString` function to use `json5` syntax instead of `cjson`, which will behave the same as `cjson` unless the existing string uses JSON5-specific constructs (trailing commas, unquoted properties, ...).
None.
=> [node-core-library] Update the `JsonFile` API to better preserve the formatting of an existing JSON file while stringifying.

common/changes/@rushstack/heft-typescript-plugin/heft-typescript-dts-map-fix_2024-01-02-21-31.json, heft-plugins/heft-typescript-plugin/src/configureProgramForMultiEmit.ts
Fixes #4224
Fixes #4470 
`Program#emit` contains an additional parameter `forceDtsEmit` that is not in the published types, and is passed during shape signature computation. Heft was not forwarding this parameter when overriding the program, resulting in behavior changes.
Local repro of the issue in #4224. Running `heft-webpack5-everything-test` in watch mode and changing `class ChunkClass` in `ChunkClass.ts` to `class Chunk Class`.
None
=> [heft-typescript] Fix updateShapeSignature break

common/changes/@microsoft/rush/ipc_2024-01-04-01-26.json, libraries/rush-lib/src/utilities/Utilities.ts
Updates the Utilities helper methods for creating child processes with an option to also establish a Node IPC channel.
This PR is setup work to allow Rush to communicate with tools that support the IPC protocol defined in [`@rushstack/operation-graph/src/protocol.types.ts`](https://github.com/microsoft/rushstack/blob/4c355757c50031ae4935e9f774cc02a95b571783/libraries/operation-graph/src/protocol.types.ts)
Regular build usage to ensure it did not regress.
None, since this is an internal API.
=> [rush] Support IPC in Utilities helper

common/changes/@rushstack/set-webpack-public-path-plugin/guard-error_2024-01-18-04-38.json, webpack/set-webpack-public-path-plugin/src/SetPublicPathCurrentScriptPlugin.ts, webpack/set-webpack-public-path-plugin/src/test/__snapshots__/SetPublicPathCurrentScriptPlugin.test.ts.snap, webpack/set-webpack-public-path-plugin/src/test/__snapshots__/SetPublicPathPlugin.test.ts.snap, webpack/set-webpack-public-path-plugin/src/test/testBase.ts
Guards the unsupported library error in a check of if the public path is actually used.
Added a test case.
None.
=> [set-webpack-public-path-plugin] Only emit an error about unsupported library types if the public path is actually used.

common/changes/@rushstack/node-core-library/user-danade-FixProcessList_2024-01-23-18-56.json, libraries/node-core-library/src/Executable.ts, libraries/node-core-library/src/test/Executable.test.ts
Fix parsing of the process name when using `Executable.getProcessInfoBy*` methods
On MacOS, the default `ps` command behavior truncates the process name from the `ps` command output. This PR instructs `ps` to display using the "wide" format, and specifies the command name last. This ensures that the output is not truncated regardless of how long the process name is.
Tested by running on a Mac and an Ubuntu machine to ensure cross-compatibility of the changes.
=> [node-core-library] Fix parsing of process name on MacOS

.gitignore, README.md, build-tests-samples/heft-storybook-react-tutorial-app/README.md, build-tests-samples/heft-storybook-react-tutorial-app/config/heft.json, build-tests-samples/heft-storybook-react-tutorial-app/package.json, build-tests-samples/heft-storybook-react-tutorial/config/heft.json, build-tests-samples/heft-storybook-react-tutorial/package.json, common/changes/@rushstack/heft-storybook-plugin/bartvandenende-wm-storybook-improvements_2024-01-03-11-53.json, common/changes/@rushstack/node-core-library/bartvandenende-wm-storybook-improvements_2024-01-22-13-23.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, common/reviews/api/node-core-library.api.md, heft-plugins/heft-storybook-plugin/src/StorybookPlugin.ts, heft-plugins/heft-storybook-plugin/src/schemas/storybook.schema.json, libraries/node-core-library/src/IPackageJson.ts, rush.json
This PR adds support for storybook 7, HMR and provides new plugin configuration options
**Storybook 7**
Ensures the heft storybook plugin is compatible with both Storybook 6 and 7. The latest storybook 7 includes a new CLI package and commands to serve and start a build:
> SB6.x framework packages shipped binaries called `start-storybook` and `build-storybook`. In SB7.0, we've removed these binaries and replaced them with new commands in Storybook's CLI: `storybook dev` and `storybook build`.
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#start-storybook--build-storybook-binaries-removed
_breaking changes on the below plugin option_
`startupModulePath` and `staticBuildModulePath` are removed in favour of a simplified model of the below design as proposed by @octogonz : …
=> [heft-storybook-plugin] Add support for storybook 7, HMR and provide new plugin configuration options

common/changes/@rushstack/eslint-bulk/octogonz-pr4490-feedback_2024-01-24-20-37.json, common/changes/@rushstack/eslint-patch/octogonz-pr4490-feedback_2024-01-24-20-37.json, eslint/eslint-bulk/README.md, eslint/eslint-patch/README.md
PR feedback from https://github.com/microsoft/rushstack/pull/4490
=> [eslint-patch] Some minor documentation updates

common/changes/@rushstack/hashed-folder-copy-plugin/fix-hashed-folder-copy-plugin-windows_2024-01-25-19-47.json, webpack/hashed-folder-copy-plugin/src/HashedFolderDependency.ts, webpack/hashed-folder-copy-plugin/src/test/HashedFolderCopyPlugin.test.ts
There is an issue where the glob pattern doesn't match anything when a build is running on Windows on the non-default drive. This is because the glob path base is constructed with `path.posix.resolve`, which drops the drive letter.
Tested on Windows on the non-default drive.
None.
=> [hashed-folder-copy-webpack-plugin] Fix hashed-folder-copy-plugin on Windows.

common/changes/@microsoft/rush/will-subspace-patch-1_2024-01-31-03-00.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/assets/rush-init/common/config/rush/subspaces.json, libraries/rush-lib/src/api/RushConfiguration.ts, libraries/rush-lib/src/api/SubspacesConfiguration.ts, libraries/rush-lib/src/cli/actions/BaseInstallAction.ts, libraries/rush-lib/src/cli/actions/InitAction.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/schemas/subspaces.schema.json
This PR includes some basic patches to fix some subspace functionality.
=> [rush] Patch for subspaces feature

build-tests/install-test-workspace/build.js, build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml
Currently `install-test-workspace` can end up with a poisoned cache in the pnpm store. This puts the pnpm store in the project's temp folder.
=> Clean up install-test-workspace and put the store in ./temp

common/changes/@microsoft/rush/main_2024-01-31-21-44.json, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
This is a regression that was introduced in https://github.com/microsoft/rushstack/pull/4453.
The `shrinkwrapIsUpToDate` is currently being set to whether the last project in `rush.json`'s project list's `dependenciesMeta` matches what's in the lockfile and ignores other checks. This PR includes the other checks.
Tested locally.
None.
=> [rush] Fix an issue with pnpm-lock.yaml not getting synced back.

common/changes/@microsoft/rush/clean-up-dependenciesmeta_2024-01-31-22-12.json, common/changes/@microsoft/rush/clean-up-dependenciesmeta_2024-01-31-22-22.json, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
Refactors the dependenciesMeta validation code.
This eliminates a second loop and an unnecessary check.
Tested by adding and removing dependenciesMeta in a local project and running `rush update`.
None.
=> [rush] Clean up the dependenciesMeta verification code.

common/changes/@rushstack/eslint-plugin/feat-typedef-var-as-const_2024-02-05-18-53.json, eslint/eslint-plugin/src/test/typedef-var.test.ts, eslint/eslint-plugin/src/typedef-var.ts
Closes #4446 
Added support for `const x = 1 as const` instead of forcing the developer to add a type annotation.
In addition, added a missing test for the "happy flow" of writing `const x: number = 1;`
=> [eslint-plugin]: Allow using `as const` in `typedef-var`

apps/api-extractor/src/generators/ApiModelGenerator.ts, build-tests/api-extractor-scenarios/etc/defaultExportOfEntryPoint2/api-extractor-scenarios.api.json, build-tests/api-extractor-scenarios/etc/spanSorting/api-extractor-scenarios.api.json, common/changes/@microsoft/api-extractor/bartvandenende-wm-api-extractor-arrow-func_2024-02-06-14-12.json
Classify arrow functions as function kind in the doc model exports.
Related issue ticket https://github.com/microsoft/rushstack/issues/1629
The current behaviour of api-extractor is to classify arrow functions as `variable` kind. Even though syntactically correct, semantically (for documentation & usage purposes) this doesn't make any sense - and worse - it invalidates any documentation effort in the docstrings related to parameter descriptions, return types etc. 
This PR modifies the doc-model generation to identify arrow functions in the variable declarations and processes them as function kinds instead.
Example code
```typescript
/**
* Demo log function
* @param message - log message
* @public
*/
export const log = (message: string): void => {console.log(message)}
```
**doc model …
=> [api-extractor] Classify arrow functions as function kind in the doc model exports.

common/changes/@rushstack/node-core-library/feature-lockfile-handle-failure-gracefully_2024-01-29-14-13.json, common/changes/@rushstack/node-core-library/feature-lockfile-handle-failure-gracefully_2024-01-29-21-11.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/FileWriter.ts, libraries/node-core-library/src/LockFile.ts, libraries/node-core-library/src/index.ts, libraries/node-core-library/src/test/LockFile.test.ts
Fixes #4491
See https://github.com/microsoft/rushstack/pull/4497#issuecomment-1918189321
There are two fixes in this PR:
1. Fixed the root cause of the unexpected ENOENT error
2. Added `getStatistics` method to `FileWriter` [as requested](https://github.com/microsoft/rushstack/pull/4497#discussion_r1470058232)
I’ve added a corresponding test case to LockFile tests suite
=> [node-core-library] Gracefully handle irregular LockFile.tryAcquire fail on macOS/Linux

common/changes/@rushstack/webpack5-localization-plugin/hash-salt_2024-02-10-00-58.json, webpack/webpack5-localization-plugin/src/test/MixedAsync.test.ts, webpack/webpack5-localization-plugin/src/test/__snapshots__/MixedAsync.test.ts.snap, webpack/webpack5-localization-plugin/src/trueHashes.ts
Includes a hash salt in hash calculation if one is provided.
Included a unit test.
=> [webpack5-localization-plugin] Add support for output.hashSalt.

common/changes/@rushstack/webpack5-localization-plugin/export-truehashplugin_2024-02-10-01-08.json, common/reviews/api/webpack5-localization-plugin.api.md, webpack/webpack5-localization-plugin/src/TrueHashPlugin.ts, webpack/webpack5-localization-plugin/src/index.ts, webpack/webpack5-localization-plugin/src/test/LocalizedRuntimeTestBase.ts, webpack/webpack5-localization-plugin/src/test/NonHashedNonLocalizedAssets.test.ts
Export a plugin that does realContentHashes without validating the localization plugin's options.
Tests already existed.
=> [webpack5-localization-plugin] Export a plugin that does realContentHashes without validating the localization plugin's options.

common/changes/@rushstack/heft-storybook-plugin/fix-storybook-plugin-static-builds_2024-02-11-20-39.json, common/changes/@rushstack/heft-storybook-plugin/fix-storybook-plugin-static-builds_2024-02-11-20-40.json, heft-plugins/heft-storybook-plugin/src/StorybookPlugin.ts, heft-plugins/heft-storybook-plugin/src/schemas/storybook.schema.json
Due to the guard around the isServeMode check in the webpack configuration taps the webpack build is only disabled when running in serve mode
This means that when doing a static storybook build it does both the webpack and storybook webpack builds when the `--storybook` cli flag is used
This changes the discarding of the webpack configuration to happen always when `--storybook` is present so static storybook builds don't double up the webpack builds, Fixes #4289 
While I'm here I added a configuration option for passing the `--webpack-stats-json` flag to Storybook to emit the webpack stats file which is required for usage with Chromatic's Turbosnap feature
Applied the changes as a patch to our monorepo and ran a full chromatic run, doing static builds for all storybooks (with …
=> fix(heft-storybook-plugin): not cancelling webpack build during storybook static build

common/changes/@microsoft/rush/chao-enable-pnpm-sync_2024-02-16-23-54.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts, libraries/rush-lib/src/logic/RushConstants.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts
Create a pnpm-patches constant.
N/A
None.
=> [rush] Create a pnpm-patches constant.

common/changes/@rushstack/webpack5-localization-plugin/stricter-js-detection_2024-02-10-07-30.json, webpack/webpack5-localization-plugin/src/LocalizationPlugin.ts, webpack/webpack5-localization-plugin/src/trueHashes.ts, webpack/webpack5-localization-plugin/src/utilities/chunkUtilities.ts
This PR adds logic to filter out non-JS chunks from processing.
Tested in a repo that generates some non-JS chunks.
=> [webpack5-localization-plugin] Filter out non-JS chunks.

apps/heft/package.json, apps/lockfile-explorer-web/package.json, build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@microsoft/rush/octogonz-fix-package-deps_2024-02-20-21-19.json, common/changes/@rushstack/heft/octogonz-fix-package-deps_2024-02-20-21-19.json, common/changes/@rushstack/heft/octogonz-fix-package-deps_2024-02-20-21-20.json, common/changes/@rushstack/node-core-library/octogonz-fix-package-deps_2024-02-20-21-19.json, common/changes/@rushstack/terminal/octogonz-fix-package-deps_2024-02-20-21-19.json, common/config/rush/pnpm-lock.yaml, libraries/node-core-library/package.json, libraries/rush-lib/src/cli/actions/ScanAction.ts, libraries/terminal/package.json
Fixes https://github.com/microsoft/rushstack/issues/4525
Fix this error that will occur sometimes when invoking Heft, Rush, or any other library that depends on the updated `@rushstack/terminal` after PR https://github.com/microsoft/rushstack/pull/3176
```
Error: Cannot find module 'colors/safe'
Require stack:
- /workspaces/the-wireguard-effect/node_modules/.pnpm/@rushstack+terminal@0.8.0_@types+node@20.11.19/node_modules/@rushstack/terminal/lib/ConsoleTerminalProvider.js
- /workspaces/the-wireguard-effect/node_modules/.pnpm/@rushstack+terminal@0.8.0_@types+node@20.11.19/node_modules/@rushstack/terminal/lib/index.js
```
=> [terminal] Fix a phantom dependency on "colors"

.vscode/launch.json, build-tests/heft-webpack5-everything-test/package.json, common/changes/@microsoft/rush/heft-server_2023-09-07-21-59.json, common/changes/@microsoft/rush/rush-ipc_2024-01-18-21-16.json, common/changes/@rushstack/operation-graph/rush-ipc_2024-01-20-00-49.json, common/config/rush/experiments.json, common/config/rush/pnpm-lock.yaml, common/config/rush/version-policies.json, common/reviews/api/rush-lib.api.md, libraries/operation-graph/src/OperationExecutionManager.ts, libraries/operation-graph/src/WatchLoop.ts, libraries/rush-lib/assets/rush-init/common/config/rush/experiments.json, libraries/rush-lib/package.json, libraries/rush-lib/src/api/ExperimentsConfiguration.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/ProjectWatcher.ts, libraries/rush-lib/src/logic/operations/IOperationRunner.ts, libraries/rush-lib/src/logic/operations/IPCOperationRunner.ts, libraries/rush-lib/src/logic/operations/IPCOperationRunnerPlugin.ts, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/OperationExecutionRecord.ts, libraries/rush-lib/src/logic/operations/ProjectLogWritable.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunnerPlugin.ts, libraries/rush-lib/src/pluginFramework/PhasedCommandHooks.ts, libraries/rush-lib/src/schemas/experiments.schema.json, libraries/rush-lib/src/utilities/Utilities.ts
Adds the ability for Rush to communicate with long-lived child build processes via the IPC protocol from `@rushstack/operation-graph`.
Adds a new experiment `useIPCScriptsInWatchMode`. When this flag is enabled and Rush is running in watch mode, it will check for npm scripts named `_phase:<phase-name>:ipc`, and if found, use them instead of the normal invocation of `_phase:<phase-name>`. When doing so, it will provide an IPC channel to the child process and expect the child to outlive the current build pass.
For watch-enabled commands, when opted into the experiment, adds a flag `--no-ipc` that disables the behavior for the current execution.
Updates the watcher prompt with new functionality:
- Press `i` to invalidate all projects and force a rebuild.
- Press `x` to shut down all IPC …
=> [rush] Add opt-in ability to use IPC in watch mode

common/changes/@microsoft/rush/fix-workspace-publish_2024-02-22-01-55.json, libraries/rush-lib/src/logic/PublishUtilities.ts, libraries/rush-lib/src/logic/test/PublishUtilities.test.ts
Fixes an issue where `rush version --bump` replaced `workspace:~` or `workspace:^` in `package.json` dependencies with `workspace:~${current}` or `workspace:^${current}`.
Rush will now retain the wildcard specifier as-is in `package.json` but reflect the publish-time value in the changelog.
These publish as `~${current}` and `^${current}` respectively.
Added unit tests for preserving the values.
=> Fix `workspace:~` and `workspace:^` in version bump

common/changes/@microsoft/rush/rush-schema-changes_2024-02-22-21-30.json, libraries/rush-lib/src/api/RushConfigurationProject.ts, libraries/rush-lib/src/api/test/RushConfigurationProject.test.ts, libraries/rush-lib/src/api/test/__snapshots__/RushConfigurationProject.test.ts.snap
Fixes #4506
Ensures that the values in `projectFolder` and `publishFolder` for each project entry in `rush.json` do not contain backslashes, are normalized POSIX relative paths, and do not end in a trailing slash.
Added unit tests for the validator.
Manually tested by temporarily making rush.json invalid.
Docs on the values of `projectFolder` and `publishFolder`.
=> [rush] Validate "projectFolder" and "publishFolder"

build-tests/install-test-workspace/workspace/common/pnpm-lock.yaml, common/changes/@rushstack/terminal/use-supports-color_2024-02-23-18-24.json, common/changes/@rushstack/terminal/use-supports-color_2024-02-24-17-12.json, common/config/rush/nonbrowser-approved-packages.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, common/reviews/api/terminal.api.md, libraries/terminal/package.json, libraries/terminal/src/Colorize.ts, libraries/terminal/src/ConsoleTerminalProvider.ts, libraries/terminal/src/test/AnsiEscape.test.ts
This PR finishes out the colors/Colorize/Terminal work. This resolves https://github.com/microsoft/rushstack/issues/3147.
Ran on a console that supports color with and without the `FORCE_COLOR=0` env var, and in CI.
None.
=> [Terminal] Replace 'colors' with 'supports-color'.

apps/api-extractor/src/api/ConsoleMessageId.ts, apps/api-extractor/src/api/ExtractorLogLevel.ts, apps/api-extractor/src/api/ExtractorMessage.ts, apps/api-extractor/src/api/ExtractorMessageId.ts, common/changes/@microsoft/api-extractor/remove-const-enum_2024-02-24-20-35.json, common/reviews/api/api-extractor.api.md
When a typescript project is using [isolatedModules](https://www.typescriptlang.org/tsconfig#isolatedModules), referencing exported const enums is not allowed.
Setting isolatedModules to true is recommended for projects transpiled with babel or [esbuild](https://esbuild.github.io/content-types/#isolated-modules). Unlike tsc, these tools evaluate files independently. Setting the isolatedModules flag e.g. forces developers to indicate whether they are exporting a type or value, since transpilers evaluating modules independently cannot infer this information.
However, the flag also alerts when a const enum is used. It seems that tsc evaluates const enums across modules and inlines the constants at compile. No enum object is created, which is problematic of independent transpilation.
I found …
=> [api-extractor] Remove "const" keyword before enum to use with typescript isolatedModules

apps/api-documenter/src/cli/YamlAction.ts, apps/api-documenter/src/documenters/YamlDocumenter.ts, apps/rundown/src/cli/BaseReportAction.ts, apps/rundown/src/cli/InspectAction.ts, apps/rundown/src/cli/SnapshotAction.ts, apps/trace-import/src/TraceImportCommandLineParser.ts, build-tests/ts-command-line-test/src/PushAction.ts, common/changes/@microsoft/api-documenter/ts-command-line-tweaks_2024-02-28-05-44.json, common/changes/@microsoft/rush/ts-command-line-tweaks_2024-02-28-05-44.json, common/changes/@rushstack/rundown/ts-command-line-tweaks_2024-02-28-05-44.json, common/changes/@rushstack/trace-import/ts-command-line-tweaks_2024-02-28-05-44.json, common/changes/@rushstack/ts-command-line/ts-command-line-tweaks_2024-02-28-05-26.json, common/changes/@rushstack/ts-command-line/ts-command-line-tweaks_2024-02-28-05-30.json, common/reviews/api/ts-command-line.api.md, libraries/rush-lib/src/cli/actions/InitAutoinstallerAction.ts, libraries/rush-lib/src/cli/actions/InitDeployAction.ts, libraries/rush-lib/src/cli/actions/UpdateAutoinstallerAction.ts, libraries/ts-command-line/src/index.ts, libraries/ts-command-line/src/parameters/CommandLineChoiceListParameter.ts, libraries/ts-command-line/src/parameters/CommandLineChoiceParameter.ts, libraries/ts-command-line/src/parameters/CommandLineDefinition.ts, libraries/ts-command-line/src/parameters/CommandLineIntegerParameter.ts, libraries/ts-command-line/src/parameters/CommandLineStringParameter.ts, libraries/ts-command-line/src/providers/CommandLineParameterProvider.ts
This PR makes to minor changes to ts-command-line's types:
- Choice and choice list parameters can now take a type argument to provide more specificity for the alternatives' types.
- There is now an overload for the `define___Parameter` functions when the `{ required: true }` option is passed which returns a new type with a non-nullable `value` property. This avoids needing a non-null assertion when the required value is used.
Updated consuming projects to use these new types.
API docs will need to be updated.
=> [ts-command-line] Improve API typings

common/changes/@microsoft/rush/will-subspace-patch-4_2024-02-27-22-23.json, libraries/rush-lib/src/logic/ProjectChangeAnalyzer.ts
Currently in the rush build step, when subspaces is enabled and you are trying to build to a single project, rush will incorrectly try to validate every project in the monorepo as opposed to the subspace you are installing for.
When building for a particular subspace, the project change analyzer tries to determine if every project in the monorepo has a valid installation shrinkwrap, however this will not be the case for subspaces as subspaces can be partially installed. This skips that validation check if subspaces is enabled.
Manually Tested:
In a monorepo with subspaces installed and has multiple subspaces A and B, for example.
If we only install dependencies for subspace A, and try to run `rush build -t <project_in_subspace_A>`, it will fail as it thinks subspace B has not been …
=> [rush] Fix rush build for subspaces

common/changes/@rushstack/ts-command-line/user-danade-RemoveEnvironmentVariableRestrictions_2024-02-29-01-44.json, common/reviews/api/ts-command-line.api.md, libraries/ts-command-line/src/parameters/BaseClasses.ts, libraries/ts-command-line/src/parameters/CommandLineDefinition.ts
This PR removes the naming restrictions on the environment variable names provided to parameters. While well-intentioned, it is sometimes not within the control of the developer as to which casing or format an environment variable name takes. Since variable naming is fundamentally limited by the platform, we should rely on the platform to determine if the environment variable specified maps to the target variable.
This PR.
=> [ts-command-line] Allow bypassing naming restrictions on environment variable names provided to parameters

common/changes/@rushstack/ts-command-line/more-ts-command-line-cleanup_2024-03-02-00-30.json, common/reviews/api/ts-command-line.api.md, libraries/ts-command-line/src/index.ts, libraries/ts-command-line/src/parameters/BaseClasses.ts, libraries/ts-command-line/src/parameters/CommandLineChoiceListParameter.ts, libraries/ts-command-line/src/parameters/CommandLineChoiceParameter.ts, libraries/ts-command-line/src/parameters/CommandLineFlagParameter.ts, libraries/ts-command-line/src/parameters/CommandLineIntegerListParameter.ts, libraries/ts-command-line/src/parameters/CommandLineIntegerParameter.ts, libraries/ts-command-line/src/parameters/CommandLineStringListParameter.ts, libraries/ts-command-line/src/parameters/CommandLineStringParameter.ts, libraries/ts-command-line/src/providers/AliasCommandLineAction.ts, libraries/ts-command-line/src/providers/CommandLineParameterProvider.ts, libraries/ts-command-line/src/providers/ScopedCommandLineAction.ts, libraries/ts-command-line/src/providers/TabCompletionAction.ts, libraries/ts-command-line/src/test/CommandLineParameter.test.ts, libraries/ts-command-line/src/test/__snapshots__/CommandLineParameter.test.ts.snap
This PR eliminates the need for casts when filtering on the parameter's type.
Unit tests pass.
API docs will need to be updated.
=> [ts-command-line] More ts-command-line API cleanup.

apps/api-documenter/src/cli/YamlAction.ts, apps/trace-import/src/TraceImportCommandLineParser.ts, build-tests/ts-command-line-test/src/PushAction.ts, common/changes/@microsoft/api-documenter/user-ianc-default-values-required_2024-03-02-01-27.json, common/changes/@microsoft/rush/user-ianc-default-values-required_2024-03-02-01-27.json, common/changes/@rushstack/trace-import/user-ianc-default-values-required_2024-03-02-01-27.json, common/changes/@rushstack/ts-command-line/user-ianc-default-values-required_2024-03-02-01-27.json, common/changes/@rushstack/ts-command-line/user-ianc-default-values-required_2024-03-02-01-45.json, common/reviews/api/ts-command-line.api.md, libraries/rush-lib/src/cli/actions/BaseInstallAction.ts, libraries/ts-command-line/src/parameters/CommandLineChoiceParameter.ts, libraries/ts-command-line/src/parameters/CommandLineIntegerParameter.ts, libraries/ts-command-line/src/parameters/CommandLineStringParameter.ts, libraries/ts-command-line/src/providers/CommandLineParameterProvider.ts, libraries/ts-command-line/src/providers/TabCompletionAction.ts
Update the return type of `defineChoiceParameter`, `defineIntegerParameter`, and `defineStringParameter` respectively when the `defaultValue` option is provided to return `IRequiredCommandLineChoiceParameter`, `IRequiredCommandLineIntegerParameter`, and `IRequiredCommandLineStringParameter` respectively, as the value will definitely be defined in these cases.
Updated downstream projects.
API docs need to be updated.
=> [ts-command-line] Return the "required" variants of the parameter types when define calls include the `defaultValue` option.

common/changes/@rushstack/ts-command-line/fix-nonstandard-env-var-names_2024-03-03-11-46.json, libraries/ts-command-line/src/parameters/BaseClasses.ts
A mistake was made with the introduction of the `allowNonStandardEnvironmentVariableNames` option, where the property on the parameter class was never initialized, so the property never took effect. This PR fixes that.
Patched the package in another repo.
None.
=> [ts-command-line] Fix an issue with allowNonStandardEnvironmentVariableNames parameter option

common/changes/@microsoft/rush/patch-sync-fix_2024-03-04-04-39.json, libraries/rush-lib/src/logic/base/BaseInstallManager.ts
There is currently an issue where if a patch is removed from `common/pnpm-patches` after `rush install` had already been run on a machine with that patch present, pnpm would try to continue applying the patch.
This PR fixes that issue by deleting the `common/temp/patches` folder if `common/pnpm-patches` doesn't exist, and deleting items from `common/temp/patches` if they no longer exist in `common/pnpm-patches`.
Tested by running `rush install` in a repo with a patch, deleting the patch, and rerunning `rush install` and observing the output.
=> [rush] Fix an issue where deleted patches weren't deleted from `common/temp/patches`.

common/changes/@microsoft/rush/pnpm-patch-commit-instructions_2024-03-04-05-46.json, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts, libraries/rush-lib/src/utilities/Utilities.ts
Right now, if you run `rush-pnpm patch <pkg>@<version>`, you'll get output that looks like this:
```
Found configuration in E:\code\rushstack13\rush.json
You can now edit the following folder: <tempdir>/8262c8522370c3b357b23864fc45a0d2
Once you're done with your changes, run "pnpm patch-commit <tempdir>/8262c8522370c3b357b23864fc45a0d2"
```
Notice that the instructions are incorrect: running `pnpm patch-commit <tempdir>/8262c8522370c3b357b23864fc45a0d2` won't work as expected.
This PR intercepts pnpm's output and replaces `pnpm patch-commit` with `rush-pnpm patch-commit`, so the output becomes:
```
Found configuration in E:\code\rushstack13\rush.json
You can now edit the following folder: <tempdir>/8262c8522370c3b357b23864fc45a0d2
Once you're done with your changes, run "rush-pnpm …
```
=> [rush] Update the `rush-pnpm patch` output to reference `rush-pnpm patch-commit` instead of `pnpm patch-commit`

apps/heft/src/cli/HeftActionRunner.ts, apps/heft/src/metrics/MetricsCollector.ts, common/changes/@rushstack/heft/heft-telemetry-fix_2024-03-02-01-06.json, common/reviews/api/heft.api.md
Updates the set of available timing metrics available to Heft plugins for organizations to analyze their build processes. These metrics are not sent anywhere by default and collection is left up to the repository manager. The metrics are:
- `taskTotalExecutionMs` is the time spent on user-defined tasks in `heft.json` for the most recent execution. This is the metric for measuring the performance of the underlying build steps for a project.
- `bootDurationMs` is the time spent dealing with Heft itself, before the start of the initial (or only if not in watch mode) `taskTotalExecutionMs` metric. This metric tracks overhead that does not perform useful work for the end user.
- `totalUptimeMs` is the total time that the Heft process has been running as of the end of the most recent execution. …
=> [heft] Update timing metrics

common/changes/@microsoft/rush/fix-cobuild-build-cache_2024-03-05-17-28.json, libraries/rush-lib/src/logic/operations/CacheableOperationPlugin.ts
Fixes #4558.
We're been running into an issue intermittently where linting errors were getting put into the build cache in CI. This caused issues as running the CI a second time would cause the build to pass and if that code got to main, developer machines would pull that code from the build cache and get warnings for untouched code. This fix changes how cobuilds assign cacheIds to builds to separate `Success` from `SuccessWithWarnings` unless the user explicitly enables `allowWarningsOnSuccess`.
As I explain above, we've had a couple of issues with the build cache accepting builds that had warnings and then passing in later runs of the CI. Those build artifacts then get pulled into developer machines and start breaking if the developer were to run `rush rebuild`. We took an initial look …
=> [build-cache] Update how cobuilds cache builds that succeed with warnings

apps/heft/src/cli/actions/CleanAction.ts, common/changes/@rushstack/heft/patch-1_2024-03-14-12-44.json
When run `heft clean`, it will always throw `Internal Error: MetricsCollector has not been initialized with setStartTime() yet`.
This only just requires call setStartTime() function before it record the time metrics.
=> [heft] Fix MetricsCollector has not been initialized with setStartTime() yet when run clean

build-tests/heft-webpack5-everything-test/package.json, build-tests/heft-webpack5-everything-test/webpack.config.js, common/changes/@rushstack/module-minifier/support-terser-options_2024-03-14-19-27.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, libraries/module-minifier/src/MinifySingleFile.ts
In the outputs of the ModuleMinifierPlugin, the (chunks) and (modules) assets listed in the sources array of source maps have been missing from the sourceContents array, either popluating as 'null', entries missing from the end of the array, or with the array missing entirely. I'm not sure how long this has gone on for, but a likely candidate would be a change in terser. This leads to bugs with debugging in the browser where stepping through code would often lead to blank sources not being able to load files. 
By enabling the terser source map option "includeSources: true", the listed chunks now have their contents present in the  source maps output of the module minifier. This is one option among many in [terser's SourceMapsOptions property …
=> [module-minifier] Fix missing sourceContents in Source Maps

apps/api-documenter/src/markdown/CustomMarkdownEmitter.ts, apps/api-documenter/src/markdown/MarkdownEmitter.ts, apps/api-documenter/src/markdown/test/__snapshots__/CustomMarkdownEmitter.test.ts.snap, common/changes/@microsoft/api-documenter/main_2024-03-14-17-16.json
This would fix #2950.
Currently, tables in generated Markdown do not work with multiline comments.
This PR changes over to HTML tables (which also work in Markdown and are in fact more standardized).
As a result, a lot of "emit different things in tables" code can be removed.
As an example of a broken generated table, see the end of the "Classes" table [in this markdown file](https://github.com/apollographql/apollo-client-nextjs/blob/1e64d9ba9680d50ac35a1178bef1cf612aa130dd/docs/client-react-streaming.md)
Generating the code with this PR instead will result in [this diff](https://github.com/apollographql/apollo-client-nextjs/pull/240/commits/247d226a3f7ac58bd72bd2370e1f46b86ba41357) and as you can see [here](https://github.com/apollographql/apollo-client-nextjs/blob/247d226a3f7ac58bd72bd23 …
=> [api-documenter] Emit HTML tags for tables instead of Markdown code.

common/changes/@microsoft/rush/interactive-browser-auth_2024-03-20-02-21.json, common/reviews/api/rush-azure-storage-build-cache-plugin.api.md, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureAuthenticationBase.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureStorageAuthentication.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/RushAzureInteractiveAuthPlugin.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/index.ts
Add support for interactive browser auth. Defaults to device code auth.
Copy pasting the device code token gets pretty annoying when using codesapces/devcontainers. This change adds support for interactive browser login flow that creates a popup browser window which completes with a local server callback.
=> [rush-azure-storage-build-cache-plugin] Add support for interactive browser auth.

common/changes/@microsoft/rush/chao-subspace-fix_2024-03-16-05-55.json, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/logic/pnpm/IPnpmfile.ts, libraries/rush-lib/src/logic/pnpm/SubspaceGlobalPnpmfileShim.ts, libraries/rush-lib/src/logic/pnpm/SubspacePnpmfileConfiguration.ts
This PR is to support [PNPM injected installation](https://pnpm.io/package_json#dependenciesmeta) in Rush subspace feature
Let's say we have two subspaces (S1, S2) in a Rush Monorepo, and set up is like this:
- subspace S1 / lockfile L1 contains project A and B
- subspace S2 / lockfile L2 contains project C and D
- A has an injected workspace:* dependency on C
- B has a non-injected workspace:* dependency on C
- C has a non-injected workspace:* dependency on D
Here, we have two cases:
1. A has an injected workspace:* dependency on C, the dependency graph is like A -> (injected) C ->(no-injected) D
In this case, we think If a package gets installed in the injected way then every workspace:* dependency of that package also gets injected.
Why? Recall the injected install definition from …
=> [rush-lib] Support PNPM injected install feature for Rush Subspace

common/changes/@microsoft/rush/chao-fix-bugs_2024-03-23-00-16.json, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
When enabling subspace, we need to use `subspace.getSubspaceTempFolder()` to get temp folder.
Manually tested
N/A
=> [rush-lib] Fix a issue where get temp folder is not correct for subspace case

common/changes/@microsoft/rush/chao-refactor-pnpm-sync-log-message_2024-03-21-20-16.json, common/config/rush/pnpm-lock.yaml, common/config/rush/repo-state.json, libraries/rush-lib/package.json, libraries/rush-lib/src/cli/RushCommandLineParser.ts, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts, libraries/rush-lib/src/cli/RushXCommandLine.ts, libraries/rush-lib/src/cli/actions/BaseInstallAction.ts, libraries/rush-lib/src/cli/actions/InstallAction.ts, libraries/rush-lib/src/cli/actions/UpdateAction.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/PackageJsonUpdater.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/base/BaseInstallManagerTypes.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/logic/installManager/doBasicInstallAsync.ts, libraries/rush-lib/src/logic/operations/PnpmSyncCopyOperationPlugin.ts, libraries/rush-lib/src/logic/test/BaseInstallManager.test.ts, libraries/rush-lib/src/utilities/PnpmSyncUtilities.ts
`pnpm-sync-lib` now have a logMessage API which allow us to customize the log message printing behavior. Check [here](https://github.com/tiktok/pnpm-sync/pull/15) to see how it implemented.
So, on Rush side, we can use this API to preventing unexpected log message and customize the log message format. 
Generally, there will be four types of message coming from `pnpm-sync-lib`, there are `'info' | 'warning' | 'error' | 'verbose'`.
1. Normally, we will only print out `info` message. 
2. `error` and `warning` will be printed if there are errors or warnings. 
3. The `verbose` will be printed out if we pass `--debug` or `--vebose` flag to the rush commands.
The `pnpm-sync-lib` also provides operation metadata in the API, so if don't want the message content from `pnpm-sync-lib`, we can utilize …
=> [rush-lib] Use pnpm-sync-lib logging APIs to customize the log message for pnpm-sync operations.

common/changes/@microsoft/rush/will-subspace-patch-13_2024-03-27-04-28.json, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
This adds symlinks for local workspace projects in the temp/<subspace_name>/node_modules folder, for the cases where certain packages try to directly look for packages that are locally linked within the node_modules folder. This feature is used when subspaces and splitWorkspaceCompatibility is enabled.
// If the splitWorkspaceCompatibility is enabled for subspaces, create symlinks to mimic the behaviour
// of having the node_modules folder created directly in the project folder. This requires symlinking two categories:
// 1) Symlink any packages that are declared to be publicly hoisted, such as by using public-hoist-pattern in .npmrc.
//    This creates a symlink from <project_folder>/node_modules/<dependency> -> temp/<subspace_name>/node_modules/<dependency>
// 2) Symlink any workspace …
=> Add symlinks for workspace projects for subspaces

common/changes/@rushstack/eslint-patch/fix-bulk-suppression-prune_2024-03-27-19-05.json, eslint/eslint-patch/src/eslint-bulk-suppressions/bulk-suppressions-file.ts, eslint/eslint-patch/src/eslint-bulk-suppressions/bulk-suppressions-patch.ts, eslint/eslint-patch/src/eslint-bulk-suppressions/cli/prune.ts
There is currently an issue with `eslint-bulk prune` where it doesn't do anything if there are no files to lint in the CWD. The call to eslint has a hardcoded `.` for the linting pattern.
This change collects all of the files mentioned in the existing `.eslint-bulk-suppresions.json` file and explicitly passes those filenames to ESLint.
Tested in a project with thousands of files containing suppressions.
None.
=> [eslint-patch] Fix issues with eslint-bulk prune.

common/changes/@rushstack/eslint-patch/eslint-bulk-issues_2024-03-28-17-06.json, common/changes/@rushstack/eslint-patch/eslint-bulk-issues_2024-03-28-17-35.json, eslint/eslint-patch/src/eslint-bulk-suppressions/bulk-suppressions-file.ts, eslint/eslint-patch/src/eslint-bulk-suppressions/bulk-suppressions-patch.ts, eslint/eslint-patch/src/eslint-bulk-suppressions/cli/prune.ts
This PR fixes two issues with `eslint-bulk prune`:
- Currently the `prune` action causes the tool to crash if files that previously contained suppressions had been deleted. This is now fixed
- Updates the `prune` action logic to delete the `.eslint-bulk-suppressions.json` file if all previously-suppresses issues have been resolved.
 
Tested by:
1. creating a TS file with eslint issues
2. introducing eslint issues in an existing file
3. running `eslint-bulk suppress --all src`
4. deleting the new file
5. running `eslint-bulk prune` and observing that the suppressions were trimmed only from that file
6. reverting the changes to the existing file
7. running `eslint-bulk prune` and observing that the bulk suppressions file is deleted
Probably none.
=> [eslint-patch] Fix a few minor issues with `eslint-bulk prune`.

common/changes/@rushstack/heft-typescript-plugin/graceful-worker-exit_2024-03-28-22-00.json, common/changes/@rushstack/module-minifier/graceful-worker-exit_2024-03-28-22-00.json, common/changes/@rushstack/worker-pool/graceful-worker-exit_2024-03-28-22-00.json, heft-plugins/heft-typescript-plugin/src/TranspilerWorker.ts, libraries/module-minifier/src/MinifierWorker.ts, libraries/worker-pool/src/WorkerPool.ts
Updates various workers to properly clean up their ports instead of using `process.exit(0)`
Minifier worker (used in the module minifier plugins)
Transpiler worker (heft-typescript-plugin)
Updated WorkerPool to use `once` instead of `on` for monitoring the exit event.
Local repeated runs of the build test projects that use these components.
None
=> Gracefully exit from workers instead of using process.exit(0)

common/changes/@rushstack/eslint-patch/user-ianc-fix-pruning-issue_2024-03-29-04-53.json, common/changes/@rushstack/eslint-patch/user-ianc-fix-pruning-issue_2024-03-29-05-11.json, eslint/eslint-patch/src/eslint-bulk-suppressions/bulk-suppressions-file.ts, eslint/eslint-patch/src/eslint-bulk-suppressions/cli/prune.ts, eslint/eslint-patch/src/eslint-bulk-suppressions/cli/runEslint.ts
`eslint-bulk prune` currently fails if no suppressions file exists, or if the file is empty. This PR updates the tool to instead delete the file.
1. Introduced an eslint issue
2. Ran `eslint-bulk suppress --all src`
3. Fixed the issue and deleted the issue in the suppression file
4. Ran `eslint-bulk prune`
None.
=> [eslint-patch] Fix an issue where 'eslint-bulk prune' crashes if there aren't any suppressions.

common/changes/@microsoft/rush/refactor-createOperations-hook_2024-03-26-21-41.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/index.ts, libraries/rush-lib/src/logic/operations/CacheableOperationPlugin.ts, libraries/rush-lib/src/logic/operations/LegacySkipPlugin.ts, libraries/rush-lib/src/pluginFramework/PhasedCommandHooks.ts, libraries/rush-lib/src/pluginFramework/RushLifeCycle.ts
Refactor `PhasedScriptAction` to run repo analysis after initial operation creation.
This removes the `projectChangeAnalyzer` property from the context passed to `createOperations`.
Ran `rush build` with the change in the rushstack repo and observed that projects came from cache.
API docs will need to be updated.
=> [rush] Run repo analysis after initial operation creation.

common/changes/@microsoft/rush/octogonz-common-scripts-copyright_2024-04-05-04-44.json, libraries/rush-lib/src/logic/StandardScriptUpdater.ts
PR https://github.com/microsoft/rushstack/pull/4348 changed the copyright notice that appears in `common/scripts/*.js` to say:
**new text**
```
// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See LICENSE in the project root for license information.
```
...instead of...
**old text**
```
// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See the @microsoft/rush package's LICENSE file for license information.
```
This text is misleading -- what is the "project root" for **install-run.js**?
This PR restores an appropriate copyright notice.
@iclanton
=> [rush] Clarify the copyright notice in common/scripts/*.js

common/changes/@microsoft/rush/fix-rush-lib-imporve-tryFindRushJsonLocation_2024-04-07-03-22.json, libraries/rush-lib/src/api/RushConfiguration.ts
Remove the arbitrary numbers in "tryFindRushJsonLocation" and use a specific way to reliably detect when reaching the root on NTFS vs Unix filesystems
=> [rush] fix: refactor tryFindRushJsonLocation && remove arbitrary numbers in loop

common/changes/@rushstack/eslint-bulk/more-robust-eslint-resolve_2024-04-09-16-56.json, eslint/eslint-bulk/src/start.ts
Right now, eslint-bulk assumes eslint is installed globally. This may or may not be the case, and the globally installed version may or may not match the version expected to be used by the local package. If the globally installed version does not match the version installed for the local package, running `eslint-bulk` can produce this error:
```
@rushstack/eslint-bulk: Error finding patch path: Command failed: eslint --stdin --config .eslintrc.js
Oops! Something went wrong! :(
ESLint: 9.0.0
Error: Failed to patch ESLint because the calling module was not recognized.
If you are using a newer ESLint version that may be unsupported, please create a GitHub issue:
https://github.com/microsoft/rushstack/issues
at Object.<anonymous> (<path>/@rushstack/eslint-patch/lib/_patch-base.js:167:19)
at …
```
=> [eslint-bulk] Attempt to resolve eslint as a dependency of the current project before falling back to a globally-installed copy.

common/changes/@rushstack/node-core-library/writev-async_2024-04-09-20-30.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/FileSystem.ts, libraries/node-core-library/src/index.ts, libraries/node-core-library/src/test/writeBuffersToFile.test.ts
Adds two new methods to the `FileSystem` API for efficient writing of bulk binary data:
- `writeBuffersToFile`
- `writeBuffersToFileAsync`
These APIs take as their content parameter an `Iterable<Uint8Array>` (which means they accept, e.g. `Buffer[]`) and write them in sequence to the target file. This allows for a couple of use cases that `FileSystem.writeFile` does not cover:
- Can write more than `Buffer.constants.MAX_LENGTH` (4GiB on 64-bit, 2GiB on 32-bit) to a file.
- If the file is being constructed by concatenating multiple chunks from separate sources, avoid the overhead of allocating a single buffer to store the result and copying in the chunks
Used Node REPL to allocate several Uint8Array instances and fill them with random values, then round trip them to disk and confirm that …
=> [node-core-library] Add writeBuffersToFile and writeBuffersToFileAsync to FileSystem

common/changes/@microsoft/rush/will-subspace-patch-14_2024-04-09-18-21.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/RushConfiguration.ts, libraries/rush-lib/src/logic/DependencyAnalyzer.ts, libraries/rush-lib/src/logic/installManager/RushInstallManager.ts, libraries/rush-lib/src/logic/pnpm/PnpmfileConfiguration.ts
This MR fixes an edge case where the subspace is not being passed when the implicit versions are being loaded.
=> Add support for implicit versions within subspaces

common/changes/@microsoft/rush/include-missing-space_2024-04-10-16-32.json, libraries/rush-lib/src/logic/PackageJsonUpdater.ts
Include a missing space in a logging message printed when running 'rush add'.
N/A
None.
=> [rush] Include a missing space in a logging message printed when running 'rush add'.

common/changes/@microsoft/rush/improve-decoupled-local-dependencies-hint_2024-04-09-23-26.json, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
Improve the error message when semantic version is used for a monorepo package.
When switching the version for a monorepo package from "workspace:*" to "x.y.z", rush complains 
```
"<project>" depends on package "<package_name>" (<package_version>) which exists within the workspace. Run "rush udpate" to update workspace reference for this package.
```
However, when it's intentional to make the package install from remote npm registry, the prorper way is to declare the package as a local decoupled dependency in rush.json.
This PR adds more message hints users about the "localDecoupledDependencies" property in project definition. The error message after would be
```
"<project>" depends on package "<package_name>" (<package_version>) which exists within the workspace. Run "rush udpate" to …
```
=> Improve decoupled local dependencies hint

common/changes/@microsoft/rush/fix-spawnsync-windows_2024-04-11-22-28.json, libraries/rush-lib/src/scripts/install-run.ts
Adapt to Node.js [security release](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2), which disallows .bat and .cmd file spawning without enabling the shell option. As @dmichon-msft notes below, Rush invokes npm bin stubs which are `.CMD` files on Windows.
Fixes #4636 
Add `shell: true` to `child_process.spawnSync` options when running in Windows, and ensure any path or binstub invoked is formatted appropriately.
On both MacOS and Windows:
- Before any changes, reproduced the issue on Windows locally.
- Changes were made in rushstack repo and rebuilt. 
- Ran `node ./libraries/rush-lib/dist/scripts/run-rush-install.js install` and `node ./libraries/rush-lib/dist/scripts/run-rush-install.js rebuild` successfully.
- On Windows, initially encountered the above path …
=> [rush] child_process.spawnSync on windows must set shell: true when targeting a .cmd file 

common/changes/@microsoft/rush/will-subspace-patch-20_2024-04-17-21-20.json, common/changes/@microsoft/rush/will-subspace-patch-21_2024-04-17-21-26.json, libraries/rush-lib/src/logic/PackageJsonUpdater.ts
Currently running `rush add -p <package_name>` results in every project being updated in a subspace. This fixes the issue.
=> Fix rush add -p affecting all subspace projects

common/changes/@microsoft/rush/main_2024-04-17-09-38.json, common/changes/@rushstack/package-extractor/main_2024-04-17-09-38.json, common/reviews/api/package-extractor.api.md, libraries/package-extractor/src/PackageExtractor.ts, libraries/package-extractor/src/index.ts, libraries/rush-lib/src/cli/actions/DeployAction.ts
Fix issue that can't extract projects dependencies correctly if there exist multiple subspaces.
Now only subspace that for entry project will be passed to package extractor, but if there are multiple projects belongs to different subspaces, dependencies in other subspaces can't be extract correctly. 
Tested with in-house production project.
Also there is an example that shows what the file structure will be like after this PR merged.
Here is the example subspace repo https://github.com/william2958/rush-subspace-demo 
The internal API for PackageExtractor has been changed to support multiple subspaces
=> fix: support subspace in package-extractor

common/changes/@microsoft/rush/ado-codespaces-auth_2024-04-18-03-55.json, common/reviews/api/rush-azure-storage-build-cache-plugin.api.md, rush-plugins/rush-azure-storage-build-cache-plugin/src/AdoCodespacesAuthCredential.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureAuthenticationBase.ts
- Add support for auth via [microsoft/ado-codespaces-auth](https://github.com/microsoft/ado-codespaces-auth) vscode extension
- Add support for login flow failover
Add new AdoCodespacesAuthCredential with returns TokenCredential compatible with other Credentials from `@azure/identity`.
Add option to failover to other loginFlow types. Defaults to `AdoCodespacesAuth` -> `InteractiveBrowser` -> `DeviceCode`
=> [rush-azure-storage-build-cache-plugin] Add support for auth via microsoft/ado-codespaces-auth vscode extension

common/changes/@microsoft/rush/kenrick-skip-merge-base_2024-03-21-02-17.json, libraries/rush-lib/src/logic/Git.ts, libraries/rush-lib/src/logic/ProjectChangeAnalyzer.ts, libraries/rush-lib/src/logic/test/Git.test.ts
Fixes #4589 
In `libraries/rush-lib/src/logic/ProjectChangeAnalyzer.ts`, I added a logic to skip determining merge base if the given "targetBranchName" is already a git commit hash
I tested the local build against my own repro in #4589 and it works as expected. However I'd like some advise too on how to write test for this change.
N/A
=> [rush] Skip determining merge base if given git hash

apps/lockfile-explorer-web/src/parsing/LockfileEntry.ts, apps/lockfile-explorer-web/src/parsing/readLockfile.ts, apps/lockfile-explorer-web/src/parsing/test/lockfile.test.ts, apps/lockfile-explorer-web/src/parsing/test/testLockfile.ts, apps/lockfile-explorer/src/commandLine.ts, apps/lockfile-explorer/src/init.ts, apps/lockfile-explorer/src/start.ts, apps/lockfile-explorer/src/state/index.ts, common/changes/@rushstack/lockfile-explorer/main_2024-04-26-06-56.json
Currently, if a repo is enabled with subspace feature, the lockfile-explorer command is no longer working. It complains that Error: [Error: File does not exist
This is due to that in subspace, we moved the common/temp folder as well as the pnpm-workspace.yaml file location.
This PR is to address this issue. Users now will be able to input the subspace name when calling the  lockfile-explorer command, like lockfile-explorer --subspace <subspace_name>. The command will use the default subspace if it is not provided.
Manually tested with Rushstack repo locally.
=> Support lockfile-explorer for subspace feature

common/changes/@microsoft/rush/feat-secure-sha1-subspace_2024-04-30-21-46.json, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/base/BaseShrinkwrapFile.ts, libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
This PR makes the "disallowInsecureSha1" policy to be subspace-level.
Previously, the whole policy is enabled by the pnpm-config.json in the default subspace. This PR reads the pnpm-config.json from each subspace when validating the "pnpm-lock.yaml"
Local
=> feat: make disallowInsecureSha1 support subspace

common/changes/@microsoft/rush/sennyeya-weighted-graph_2024-05-01-22-51.json, common/changes/@rushstack/node-core-library/sennyeya-weighted-graph_2024-05-01-22-51.json, common/changes/@rushstack/node-core-library/sennyeya-weighted-graph_2024-05-03-22-13.json, common/reviews/api/node-core-library.api.md, common/reviews/api/rush-lib.api.md, libraries/node-core-library/src/Async.ts, libraries/node-core-library/src/index.ts, libraries/node-core-library/src/test/Async.test.ts, libraries/rush-lib/src/api/RushProjectConfiguration.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/operations/AsyncOperationQueue.ts, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/WeightedOperationPlugin.ts, libraries/rush-lib/src/logic/operations/test/AsyncOperationQueue.test.ts, libraries/rush-lib/src/schemas/rush-project.schema.json
Followup to #4092. The goal of this PR is to allow rush users to define the weight of an operation, this is especially useful for operations that do not take a fair share of the available concurrency (either CPU or memory). Examples include jest's `max-workers` or other CPU intensive tasks, as well as memory intensive tasks where you may want to only run one heavy task without parallelism but you don't want to drop the overall rush parallelism.
This code is very similar to David's original PR, with a few modifications
1. the implementation is now very similar to Async.forEachAsync()
2. Operation weight can only be whole numbers.
3. A new WeightedOperationPlugin that adds the weight to the operation and validates that the weight is in fact a whole number and >= 0.
There was some original …
=> feat(rush,node-core-library): allow weighted async concurrency

common/changes/@microsoft/rush/chore-error-packageJSON-filename_2024-05-03-12-11.json, libraries/rush-lib/src/api/RushConfigurationProject.ts
Given out the filename of the local projects package.json file where the error occured during rush command
=> Given out the filename of the local projects package.json file where the error occured during rush command

common/changes/@microsoft/rush/user-ianc-fix-tab-completion_2024-05-08-05-43.json, common/changes/@rushstack/ts-command-line/user-ianc-fix-tab-completion_2024-05-08-05-43.json, libraries/ts-command-line/src/providers/TabCompletionAction.ts, libraries/ts-command-line/src/test/TabCompleteAction.test.ts
Fixes https://github.com/microsoft/rushstack/issues/4649.
The tab completion action misidentified a command that ended with a space as partial-word completion, and the unit tests did not test this correctly. This PR specifically handles the case where the tab completion request ends with whitespace.
Stopped trimming the command passed in unit tests and confirmed that they work correctly.
None.
=> [ts-command-line] Fix an issue where tab completions wouldn't fill values correctly.

common/changes/@microsoft/rush/sennyeya-weighting-bug-fix_2024-05-08-13-35.json, libraries/rush-lib/src/logic/operations/AsyncOperationQueue.ts
Followup to #4672 
Having a weight of 0 for UNASSIGNED_OPERATION was causing a build up of objects for the instance that was waiting. This quickly causes a GC error, locally I can trigger it in 30 seconds, in our CI it's about 2 mins.
I tried to upgrade our cobuild instance this morning and ran into this issue. Monkeypatching the weight to 1 locally fixes the issue. 
This is caused by the weight of 0 being an immediate execution, UNASSIGNED_OPERATIONs must have an actual weight so the process is stuck waiting for some time.
Tested this in our internal rush instance, I also tested this with the cobuild test project by setting the timeout in the `build.js` script to a long interval (2000 seconds). The instance that is waiting will throw a GC error pretty quickly.
With this change, the …
=> bug(rush-lib,operation-weighting): UNASSIGNED_OPERATION causing memory leak

.github/workflows/ci.yml, common/changes/@microsoft/rush/chao-fix-install_2024-05-08-18-07.json, common/config/azure-pipelines/templates/build.yaml, libraries/rush-lib/src/api/LastInstallFlag.ts
Fix a issue where rush install/update can not detect pnpm-sync.json is out of date
=> [rush-lib] Fix a issue where rush install/update can not detect pnpm-sync.json is out of date

common/changes/@microsoft/rush/octogonz-publish-rush-5.122.0_2024-05-08-18-04.json, common/config/azure-pipelines/templates/build.yaml, common/config/azure-pipelines/vscode-extension-publish.yaml, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/PnpmSyncCopyOperationPlugin.ts, libraries/rush-lib/src/utilities/PnpmSyncUtilities.ts
The publishing pipeline was failing with this error:
The publishing pipeline seems actually incorrect:  It makes sense that the Rush CI would try rebuilding/reinstalling itself using the current branch to see if the CI passes, because ultimately we discard the output.  Whereas when publishing to NPM, the correctness of the build output is very important.  But this "test" is effectively upgrading Rush in-place without any review, and the output of that test is what gets published to NPM.  It's probably safe in most cases, but in principle it seems not a good practice.  Thus, I have removed this pipeline step entirely.
I also improved the error message format and fixed a problem where the error message was getting printed twice.
The new error looks like this:
Manually edited …
=> [rush] Fix publishing pipeline to publish Rush 5.124.0

common/changes/@microsoft/rush/sennyeya-weighted-operation-reentry_2024-05-08-23-55.json, common/changes/@rushstack/node-core-library/sennyeya-weighted-operation-reentry_2024-05-08-23-55.json, libraries/node-core-library/src/Async.ts, libraries/node-core-library/src/test/Async.test.ts, libraries/rush-lib/src/logic/operations/AsyncOperationQueue.ts, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/OperationExecutionRecord.ts, libraries/rush-lib/src/logic/operations/WeightedOperationPlugin.ts
Followup to #4672. This PR fixes 2 bugs that I found while trying to integrate this with our CI,
1. operation weight isn't passed correctly to the execution record.
2. operation weight wasn't being respected if operations were queued at the same time.
(a,b,c all have operation weight 10)
The existing `AsyncQueueManager` requires the `forEachAsync` implementation to be reentrant and to have multiple waiting iterators. Moving to a weighted operation model requires the `forEachAsync` to lock when pulling off an item from the iterator as we don't know the operation weight until after we pop the item. To correct this difference, I updated `AsyncQueueManager` to explicitly reassign operations when marking the operation as complete or after handling a remote executing operation. 
This may affect …
=> fix(node-core-library): iterator weighting isn't fully respected by `Async#forEachAsync`

common/changes/@rushstack/eslint-bulk/fix-eslint-bulk-escaping_2024-05-10-07-41.json, eslint/eslint-bulk/src/start.ts
Fixes #4691.
This change runs a resolved eslint with `spawnSync` instead of `execSync`, and wrap the eslintrc path in quotes.
Built the `eslint-bulk-suppressions-test` project in a clone of this repo with a space in the path.
=> [eslint-bulk] Fix #4691.

common/changes/@microsoft/rush/will-pnpmfile-reset_2024-05-10-19-46.json, libraries/rush-lib/src/logic/pnpm/PnpmfileConfiguration.ts, libraries/rush-lib/src/logic/pnpm/PnpmfileShim.ts
This MR fixes an issue where the PnpmfileShim carries cached state between subsequent subspace installs. 
Currently if the project graph looks like this:
projectA depends on projectB
projectA -> subspaceA
projectB -> subspaceB
and you run `rush install -t projectA`, rush will incorrectly run subspaceB's pnpmfile when installing for subspaceA.
This fixes the issue by clearing the state in the pnpmfile.
=> [rush] Add a reset function to the pnpmfile to allow for clearing state

apps/lockfile-explorer/src/commandLine.test.ts, apps/lockfile-explorer/src/start.ts, common/changes/@rushstack/lockfile-explorer/fix-lockfile-explorer-cli_2024-05-15-07-23.json
This is a bugfix for `lockfile-explorer --help` not exiting with 0 code.
Added a `.test.ts` for the args parser, but not covering exitCode (it's a global status belong the `start.ts` which is harder to be tested).
No doc to be updated as it's a bugfix.
=> [lockfile-explorer] fix: exit with 0 for `lockfile-explorer --help`

common/changes/@microsoft/rush/fix-completed-count_2024-05-15-21-45.json, common/changes/@microsoft/rush/fix-completed-count_2024-05-15-22-44.json, common/changes/@rushstack/terminal/fix-completed-count_2024-05-15-22-44.json, common/reviews/api/terminal.api.md, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/OperationExecutionRecord.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts, libraries/terminal/src/StdioSummarizer.ts
Adds more information to Rush's error reporting in phased commands, and ensures that more error messages are included in the summary view.
- If a child operation process is killed via a signal (e.g. SIGTERM), and exits with a non-zero exit code, report the signal as well as the exit code. This comes up if, e.g., the process is killed by the OS due to lack of RAM.
- If an `afterExecuteOperation` handler throws an error, ensure that any existing error from the original process is reported to the `OperationExecutionRecord`'s `Terminal` instance and `StdioSummarizer`.
- Ensure that the final error from an `Operation` is reported to the `OperationExecutionRecord`'s Terminal instance and `StdioSummarizer`.
Unfortunately the error logging from pnpm-sync-lib still violates this contract, since it …
=> [rush] Improve error reporting

common/changes/@microsoft/rush/chao-fix-edge-case_2024-05-16-00-22.json, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
When there is no any dependencies in a `package.json`, the `pnpm install` will only generate the `pnpm-lock.yaml`, but not `.pnpm` folder. 
Add existence check for `pnpm-lock.yaml` file and `.pnpm` folder before calling pnpm-sync APIs
Tested with Rushstack repos manually. 
N/A
=> [rush-lib] Fix an edge case for pnpm-sync where .pnpm folder is not exist but it is still a valid pnpm install

common/changes/@rushstack/ts-command-line/ts-command-line-recommendation-updates_2024-05-15-20-16.json, common/reviews/api/ts-command-line.api.md, libraries/ts-command-line/README.md, libraries/ts-command-line/src/providers/CommandLineParameterProvider.ts, libraries/ts-command-line/src/providers/ScopedCommandLineAction.ts, libraries/ts-command-line/src/test/ActionlessParser.test.ts, libraries/ts-command-line/src/test/AliasedCommandLineAction.test.ts, libraries/ts-command-line/src/test/CommandLineParser.test.ts, libraries/ts-command-line/src/test/ConflictingCommandLineParser.test.ts, libraries/ts-command-line/src/test/ScopedCommandLineAction.test.ts
See https://github.com/microsoft/rushstack/issues/4708#issuecomment-2113363426.
This PR marks `onDefineParameters` as `@deprecated` because it causes issues when targeting >=es2022.
@D4N14L - This is probably still an issue for scoped parameters.
Updated tests.
README and API docs need to be republished.
=> [ts-command-line] Deprecate onDefineParameters.

common/changes/@rushstack/eslint-patch/main_2024-05-16-16-05.json, eslint/eslint-patch/src/_patch-base.ts
I've attempted to update `eslint-patch` to work with ESLint v9. 
Fixes https://github.com/microsoft/rushstack/issues/4635
I believe the only thing preventing this from working in ESLint was the strict version checks, so loosened those checks to include ESLint v9.
I have no idea how to test this, but I wanted to get the ball rolling. I could not find any documentation related to testing and this package did not have an `npm test` script. I was hoping someone could walk me through the testing process.
I did not find any documentation related to version number.
=> [eslint-patch] Update for v9

common/config/rush/custom-tips.json, common/config/rush/pnpm-config.json, rush.json
In [this thread](https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/How.20to.20update.20the.20'pnpm-lock.2Eyaml'.20for.20subspaces.3F/near/439165113) @bartvandenende-wm  reported that `rush update` wasn't processing all subspaces.
Seems to be fixed by upgrading.
CC @william2958
=> Upgrade to Rush 5.124.6

common/changes/@rushstack/heft-sass-plugin/main_2024-05-20-08-33.json, common/changes/@rushstack/heft-sass-plugin/main_2024-05-20-08-35.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json, heft-plugins/heft-sass-plugin/package.json, heft-plugins/heft-sass-plugin/src/SassProcessor.ts
This PR bumps `sass-embedded` to make use of a new parameter provided to the `findFileUrl` callback. This parameter provides the context from which a file is being resolved, allowing a correct resolution algorithm to be employed. This PR also implements that algorithm. With this change, `@import` and `@use` rules in dependency scss files work correctly, even if the project being built doesn't have a direct dependency on the package that the rule resolves to.
Tested in a large repo that previously had this issue.
None.
=> [heft-sass-plugin] Upgrade sass-embedded and fix indirect dependency resolution in import and use rules.

common/changes/@rushstack/node-core-library/main_2024-05-21-02-47.json, common/changes/@rushstack/node-core-library/remove-Async.sleep_2024-05-21-03-05.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/Async.ts, libraries/node-core-library/src/Constants.ts
Removes `Async.sleep`, which is deprecated, for the upcoming major bump.
N/A
API docs will need to be updated.
=> [node-core-library] Clean up a few things from node-core-library in preparation for a major bump.

build-tests/eslint-bulk-suppressions-test/build.js
The output from this test is showing up in PR reviews, which is distracting. This PR suppresses this output unless the tool fails.
Built.
None.
=> Suppress output from eslint-bulk-suppressions-test.

apps/heft/src/plugins/NodeServicePlugin.ts, apps/heft/src/utilities/GitUtilities.ts, apps/rundown/src/Rundown.ts, apps/rundown/src/launcher.ts, common/changes/@microsoft/rush/octogonz-node-exit_2024-05-17-19-20.json, common/changes/@rushstack/debug-certificate-manager/octogonz-node-exit_2024-05-22-00-36.json, common/changes/@rushstack/heft-storybook-plugin/octogonz-node-exit_2024-05-17-19-17.json, common/changes/@rushstack/heft/octogonz-node-exit_2024-05-17-19-17.json, common/changes/@rushstack/node-core-library/octogonz-node-exit_2024-05-17-19-17.json, common/changes/@rushstack/package-deps-hash/octogonz-node-exit_2024-05-17-19-17.json, common/changes/@rushstack/rundown/octogonz-node-exit_2024-05-17-19-17.json, heft-plugins/heft-storybook-plugin/src/StorybookPlugin.ts, libraries/debug-certificate-manager/src/CertificateManager.ts, libraries/debug-certificate-manager/src/runCommand.ts, libraries/node-core-library/src/Executable.ts, libraries/node-core-library/src/SubprocessTerminator.ts, libraries/package-deps-hash/src/getRepoState.ts, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts, libraries/rush-lib/src/logic/operations/IPCOperationRunner.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts, libraries/rush-lib/src/utilities/Utilities.ts, repo-scripts/repo-toolbox/src/BumpCyclicsAction.ts
Following up from PR https://github.com/microsoft/rushstack/pull/4711, I audited the Rush Stack code base to look for any other invocations that might be affected by the same issue.
That PR did not trigger publishing of Rush, so I've also included a `rush change` file to publish a Rush release.
In this [lengthy Zulip chat](https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/.E2.9C.94.20.5Brush.5D.20.22git.20status.22.20malfunctions.20when.20using.20WSL/near/438313904) we investigated a Rush build cache failure on Windows Subsystem for Linux (WSL) that turned out to be a race condition in the way that `child_process.on('exit')` was handled.
The sequence of events is like this:
- `child_process.on('data')` is being used to collect STDERR and STDOUT
- …
=> Fix more instances of the child_process.on('exit') race condition

common/changes/@microsoft/rush/will-subspaces-patch-26_2024-05-20-22-22.json, libraries/rush-lib/src/api/RushConfiguration.ts, libraries/rush-lib/src/api/Subspace.ts, libraries/rush-lib/src/api/packageManager/PnpmPackageManager.ts, libraries/rush-lib/src/logic/pnpm/SubspacePnpmfileConfiguration.ts
Design note: https://github.com/microsoft/rushstack/issues/4720
This MR renames the subspace level pnpmfile to ".pnpmfile.cjs" from ".pnpmfile-subspace.cjs", as we are no longer allowing a rush level ".pnpmfile.cjs" file to exist.
This MR also checks if a ".npmrc" file exists globally, and throws an error if it does, prompting the user to use the ".npmrc-global" file instead. It also throws an error if the ".pnpmfile.cjs" file exists at the rush config level.
This affects the documentation listed here: https://rushjs.io/pages/advanced/subspaces/
=> [rush] Rename subspace pnpmfile to .pnpmfile.cjs from .pnpmfile-subspace.cjs

common/changes/@rushstack/node-core-library/fix-issue-with-json-schema_2024-05-23-22-26.json, common/changes/@rushstack/node-core-library/fix-issue-with-json-schema_2024-05-23-22-27.json, libraries/node-core-library/src/JsonFile.ts, libraries/node-core-library/src/test/JsonFile.test.ts, libraries/node-core-library/src/test/JsonSchema.test.ts, libraries/node-core-library/src/test/__snapshots__/JsonFile.test.ts.snap, libraries/node-core-library/src/test/test-data/test-schema-draft-04.json, libraries/node-core-library/src/test/test-data/test-schema-draft-07.json, libraries/node-core-library/src/test/test-data/test-schema-nested.json, libraries/node-core-library/src/test/test-data/test-schema.json, libraries/node-core-library/src/test/test-data/test-valid.json
With the upgrade to use `ajv` for JSON schema validation, we accidentally introduced a regression where using the `"uniqueItems": true` option in a schema for an array with items that are objects causes an exception to be thrown when calling `JsonFile.loadAndValidate`. This is because the `jju` parses JSON files by default does not populate the functions from `Object.prototype` on parsed JSON objects and `ajv` uses `a.valueOf() === b.valueOf()` as part of its deep comparison of objects (via the `fast-deep-equal` package). The `valueOf` function isn't populated on objects, so this function call fails.
This PR adds the `reserved_keys: 'replace'` `jju` parse option to populate these functions. This also allows parsing of objects with these properties. This introduces an edge case where a …
=> [node-core-library] Include support for parsing JSON files with object keys that are reserved words and fix an issue with JSON schema validation.

common/changes/@microsoft/rush/fix-missing-script-behavior_2024-05-29-05-08.json, libraries/rush-lib/src/logic/operations/ShellOperationRunnerPlugin.ts
This regression was introduced by https://github.com/microsoft/rushstack/pull/4652. After that change, a missing and an empty script are both treated as a missing script. This PR fixes that.
Tested in a repo with a repro.
None.
=> [rush] Fix an issue where if `missingScriptBehavior` is set to `"error"` and a script is present and empty, an error would be thrown.

common/changes/@microsoft/rush/rush-init-updates_2024-05-29-04-01.json, common/changes/@microsoft/rush/rush-init-updates_2024-05-29-04-02.json, common/changes/@microsoft/rush/rush-init-updates_2024-05-29-04-03.json, libraries/rush-lib/assets/rush-init/[dot]gitignore, libraries/rush-lib/assets/rush-init/rush.json
- Updates the node supported version range to the LTS and current versions
- Updates the pnpm version to the latest version of pnpm v8
- Adds some toolchain intermediate folders and files to the gitignore.
=> [rush] Updates to the rush init template.

common/changes/@microsoft/rush/fix-ajv-warning_2024-05-29-19-03.json, libraries/rush-lib/src/schemas/deploy-scenario.schema.json
I think this crept in with the AJV refactor #4714. The schema was invalid, setting `minItems` on a string is a no-op. I'm assuming it was intended to sit on the array itself.
We started seeing this in CI after upgrading to 5.125.0 when running `rush deploy`.
I created a new empty`deploy.json` file in this repo. It will fail validation, but the string mode error checking is what I'm looking for.
Using `rush deploy`
```
Loading deployment scenario: /Users/aramis.sennyey/Projects/rushstack/common/config/rush/deploy.json
strict mode: missing type "array" for keyword "minItems" at "#/properties/deploymentProjectNames/items" (strictTypes)
ERROR: JSON validation failed:
/Users/aramis.sennyey/Projects/rushstack/common/config/rush/deploy.json
Error: #
must have required property …
```
=> [rush]: fix JSON schema definition for `deploy.json`

common/changes/@microsoft/rush/main_2024-05-29-07-33.json, libraries/rush-lib/src/logic/operations/CacheableOperationPlugin.ts, libraries/rush-lib/src/logic/operations/OperationExecutionRecord.ts, libraries/rush-lib/src/logic/operations/ProjectLogWritable.ts
This PR includes a general refactor of how log files are generated. In addition to that, it changes a few things: 
- The "legacy" logs that were placed in the root of the project folder are no longer deleted.
- All `.log` files are now dropped in the project `rush-logs` folder.
- The chunked log files are now dropped in the project `.rush/temp/chunked-rush-logs` folder.
Ran in this repo.
None.
=> [rush] Clean up and refactor operation logging.

apps/rush/src/RushVersionSelector.ts, common/changes/@microsoft/rush/main_2023-09-24-06-11.json, libraries/rush-lib/config/jest.config.json, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts, libraries/rush-lib/src/cli/actions/ChangeAction.ts, libraries/rush-lib/src/cli/actions/PublishAction.ts, libraries/rush-lib/src/cli/actions/VersionAction.ts, libraries/rush-lib/src/cli/test/Cli.test.ts, libraries/rush-lib/src/cli/test/RushCommandLineParser.test.ts, libraries/rush-lib/src/cli/test/RushCommandLineParserFailureCases.test.ts, libraries/rush-lib/src/cli/test/TestUtils.ts, libraries/rush-lib/src/logic/Autoinstaller.ts, libraries/rush-lib/src/logic/Git.ts, libraries/rush-lib/src/logic/PackageJsonUpdater.ts, libraries/rush-lib/src/logic/ProjectChangeAnalyzer.ts, libraries/rush-lib/src/logic/PublishGit.ts, libraries/rush-lib/src/logic/PublishUtilities.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/installManager/InstallHelpers.ts, libraries/rush-lib/src/logic/installManager/RushInstallManager.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/logic/policy/GitEmailPolicy.ts, libraries/rush-lib/src/logic/policy/PolicyValidator.ts, libraries/rush-lib/src/logic/test/Git.test.ts, libraries/rush-lib/src/logic/test/PublishGit.test.ts, libraries/rush-lib/src/utilities/Npm.ts, libraries/rush-lib/src/utilities/Utilities.ts, libraries/rush-lib/src/utilities/test/Npm.test.ts, libraries/rush-lib/src/utilities/test/global-teardown.ts
This PR refactors the `executeCommand` and related functions to be async. This is in preparation for some follow-up work to merge `executeCommandAndProcessOutputWithRetryAsync` into the `executeCommandAsync` function.
This change needs some more testing.
=> [rush] Update the functionality that runs external lifecycle processes to be async.

common/changes/@microsoft/rush/clustering-fixes_2024-05-29-16-51.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/RushProjectConfiguration.ts, libraries/rush-lib/src/logic/operations/BuildPlanPlugin.ts, libraries/rush-lib/src/logic/operations/CacheableOperationPlugin.ts
This PR is a followup to #4652 and #4660.
1. It addresses the case where a no-op operation may not have a `rush-project.json` file (and may not want one in order to prevent build cache clustering).
2. It fixes the cluster ID to use operation name instead of phase name, which is important for sharding and other operations that may use the same phase name for multiple operations.
Tested in the sharded-repo for cobuilds and in my company's monorepo. 
For sharding clustering, before this change all sharded operations are built on the same machine, and after it, they are able to be picked up. For operations that are _not_ no-ops, it performs the same checks (has `rush-project.json`, `disableBuildCacheForOperation`, etc).
None.
=> [rush]: fix operation clustering for shards and no-ops

common/changes/@microsoft/rush/remove-unnecessary-condition_2024-06-06-18-39.json, libraries/rush-lib/src/logic/operations/LegacySkipPlugin.ts
This is a follow-up to https://github.com/microsoft/rushstack/pull/4763#discussion_r1628476617
=> [rush] Remove unnecessary condition in the logic for skipping operations when build cache is disabled

common/changes/@rushstack/heft-webpack5-plugin/webpack5-watch-options_2024-06-07-01-16.json, common/reviews/api/heft-webpack5-plugin.api.md, heft-plugins/heft-webpack5-plugin/src/Webpack5Plugin.ts, heft-plugins/heft-webpack5-plugin/src/shared.ts
Adds a new accessor hook `onGetWatchOptions` to the `heft-webpack5-plugin`. The motivation is to give users of the plugin an avenue to specify watch exclusions to Webpack's watcher.
Default options value is `{}`.
Ran the `heft-webpack5-everything-test` project in watch mode.
Documentation for the accessor.
=> [webpack5] Add onGetWatchOptions hook

common/changes/@microsoft/rush/main_2024-06-07-19-17.json, common/config/rush/version-policies.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/assets/rush-init/common/config/rush/experiments.json, libraries/rush-lib/src/api/ExperimentsConfiguration.ts, libraries/rush-lib/src/cli/RushCommandLineParser.ts, libraries/rush-lib/src/logic/test/workspaceRepo/common/config/rush/experiments.json, libraries/rush-lib/src/schemas/experiments.schema.json
The `phasedCommands` feature has been out for a very long time and is stable at this point. It makes sense to remove the experiment flag at this point.
Ran `rush build` in a repo without the experiment flag.
https://rushjs.io/pages/configs/experiments_json/ needs to be updated.
=> [rush] Graduate the 'phasedCommands' experiment.

common/changes/@microsoft/rush/report-obsolete-snapshots_2024-06-10-23-46.json, common/changes/@rushstack/heft-jest-plugin/main_2024-06-10-23-03.json, common/changes/@rushstack/package-deps-hash/report-obsolete-snapshots_2024-06-10-23-46.json, heft-plugins/heft-jest-plugin/src/HeftJestReporter.ts, libraries/package-deps-hash/src/test/__snapshots__/getRepoDeps.test.ts.snap, rush-plugins/rush-redis-cobuild-plugin/src/test/__snapshots__/RedisCobuildLockProvider.test.ts.snap
Heft's Jest plugin currently doesn't report obsolete snapshots. This PR updates the reporter to print a warning if a snapshot is unchecked.
Introduced an unchecked snapshot and ran `heft test`.
None.
=> [jest] Update the test reporter to report unchecked snapshots.

common/changes/@microsoft/rush/main_2024-06-11-02-39.json, libraries/rush-lib/src/logic/Git.ts, libraries/rush-lib/src/logic/test/Git.test.ts
The problem is rush install always check user.email on git configuration and throws error if user didn't configure email address EVEN user didn't configure `allowedEmailRegExps` settings on rush.json. ([Example](https://github.com/kc-workspace/kcws-js/actions/runs/9451572312/job/26032839959#step:3:150))
This is because `tryGetGitEmailAsync` function will always throw error first if it cannot fetch  email successfully. Therefore email will never by undefined in the first place and the if email equals undefined will never catch.
https://github.com/microsoft/rushstack/blob/dbaebcd68f5195872dae95545decb2d26d81d273/libraries/rush-lib/src/logic/policy/GitEmailPolicy.ts#L37-L47
I add some tests to ensure the function can return both string (email) and undefined.
This should not impact any public …
=> [rush-lib] Fix rush install failed when user didn't configure git user.email and didn't configure allow email regexp

common/changes/@microsoft/rush/fix-alias-workspace-protocol-selector_2024-05-24-07-55.json, libraries/rush-lib/src/api/RushConfigurationProject.ts, libraries/rush-lib/src/logic/DependencySpecifier.ts, libraries/rush-lib/src/logic/test/DependencySpecifier.test.ts
currently, when declaring dependency with `NPM` alias with workspace protocol `workspace:`, the dependency won't be picked up by selectors (eg: --to-except)
eg: `"alias-for-my-controls": "workspace:my-controls@^1.0.0"`
2 dependencies added in package.json: 
```
"name": "my-app",
"dependencies": {
"my-toolchain": "workspace:^1.0.0",
"alias-for-my-controls": "workspace:my-controls@^1.0.0"
},
... 
```
when running `rush list --to-except my-app`
the output will only print `my-toolchain`, while `my-controls` is absent.
```
Starting "rush list"
my-toolchain
```
TODO
=> [rush] Fix an issue about dependency using NPM alias with workspace protocol is not selected by selectors (eg: --to .)

common/changes/@microsoft/rush/chao-fix-rush-pnpm-patch_2024-06-12-23-51.json, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts
Support `rush-pnpm patch` for subspace scenario.
In the [PR 4662](https://github.com/microsoft/rushstack/pull/4662) , we already support to pass a subspace name when run `rush-pnpm` command, so all need to do here is to pass the subspace name to the patch action. 
Manually tested with rushstack repo locally.
=> [rush-lib] Fix an issue where rush-pnpm patch is not working for the subspace scenario

common/changes/@microsoft/rush/sennyeya-clustering-by-operation-name_2024-06-17-19-57.json, libraries/rush-lib/src/logic/operations/CacheableOperationPlugin.ts
Followup to #4750, this was accidentally reverted in https://github.com/microsoft/rushstack/pull/4750/commits/86c54bb24ed557506093607c01e26eb6240155a0. We need to use operation name instead of phase name to cluster by since shards have the same phase but different operation names. I found this while trying to support clustering in our local instance.
Tested on the `build-tests/rush-redis-cobuild-plugin-integration-test/sandbox/sharded-repo`. You can see in the below screenshot that shards for package a and b are cobuilt across both machines.
None.
=> fix(rush,sharding): add back clustering based on operation name

common/changes/@microsoft/rush/chao-fix-pnpm-sync_2024-06-18-19-25.json, common/config/subspaces/build-tests-subspace/pnpm-lock.yaml, common/config/subspaces/build-tests-subspace/repo-state.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json, libraries/rush-lib/package.json, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, rush.json
1. Add a logic to remove out of date `.pnpm-sync.json` file during rush install or update
2. Upgrade `pnpm-sync-lib` to `0.2.8`
Normally, when users upgrade rush engine version, it won't clear the all existing `node_modules` cache, and rush will reuse these `node_modules` cache during `rush install/update`. 
This could sometime causes a problem for pnpm-sync. Since `.pnpm-sync.json` is versioned, it should be regenerated even though the installation is up to date. 
Also, in real practice, if a Monorepo is using feature based development flow, different branches can has different rush engine version, and if you switch between these branches, the `node_modules` won't be cleared and rush will try to resue the installation cache as well. This will also causes the problem that installation is …
=> [rush] Add a logic to remove out of date .pnpm-sync.json file during rush install or update

common/changes/@microsoft/rush/rush-pnpm-exit-code_2024-06-19-21-22.json, common/config/subspaces/build-tests-subspace/repo-state.json, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts, libraries/rush-lib/src/utilities/Utilities.ts
Fixes https://github.com/microsoft/rushstack/issues/4795
This was accidentally broken by https://github.com/microsoft/rushstack/pull/4350.
Tested in the repro repo in https://github.com/microsoft/rushstack/issues/4795
None.
=> [rush] Fix an issue where the 'rush-pnpm ...' command always terminates with an exit code of 1.

common/changes/@microsoft/rush/chao-fix-getPackageJsonInjectedDependenciesHash_2024-06-25-17-48.json, libraries/rush-lib/src/api/Subspace.ts
No need to include `package.json`'s version field when calculating packageJsonInjectedDependenciesHash. It is because that these projects are all workspace projects, we always using the whatever latest version in the Monorepo. 
Manually tested with Monorepo locally.
=> [rush] Don't include package.json version field when calculating packageJsonInjectedDependenciesHash

common/changes/@microsoft/rush/chao-improve-getPackageJsonInjectedDependenciesHash_2024-06-26-04-40.json, common/config/subspaces/build-tests-subspace/repo-state.json, libraries/rush-lib/src/api/Subspace.ts, rush.json
If you declare a workspace package in peerDependencies, though you put the version range there, PNPM does not respect it. Below is an example: 
peerDependencies section in `@rushstack/heft-api-extractor-plugin` project package.json
```
"peerDependencies": {
"@rushstack/heft": "0.66.18"
},
```
The actual `pnpm-lock.yaml`
So, we don't need to take these packages into consideration when calculating packageJsonInjectedDependenciesHash.
Manually tested with Monorepo locally.
=> [rush] Fix an edge case for workspace peer dependencies when calculating packageJsonInjectedDependenciesHash to improve its accuracy

common/changes/@microsoft/rush/spelling_2024-06-27-17-49.json, libraries/rush-lib/assets/rush-init/rush.json, libraries/rush-lib/src/schemas/rush.schema.json
Fix a spelling error in both the rush.json schema and the rush.json template.
`commiting` -> `committing`
N/A
None.
=> [rush] Fix spelling of "committing" in rush.json schema and template

common/changes/@microsoft/rush/kenrick-fix-rush-add_2024-06-27-02-39.json, common/changes/@rushstack/node-core-library/kenrick-fix-rush-add_2024-06-27-02-39.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/JsonFile.ts, libraries/rush-lib/src/api/PackageJsonEditor.ts
Attempt to fix #4811
I investigated and found out that when saving JSON with "jju.update", it always use Json5 mode. This may cause issue when updating things that expect strict JSON like package.json.
So the fix here is to pass a `jsonSyntax` option to let `PackageJsonEditor` use that `JsonSyntax.Strict` mode.
I build locally and it works on the repro: https://github.com/kenrick95/rush-repro-rush-add-malformed-package-json
- IJsonFileStringifyOptions adds "jsonSyntax" as an option. Is that okay?
=> [rush] malformed package.json by explicitly setting jsonSyntax to strict

common/changes/@microsoft/rush/fix-rush-add_2024-07-10-19-56.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/CommonVersionsConfiguration.ts, libraries/rush-lib/src/api/RushConfiguration.ts, libraries/rush-lib/src/api/Subspace.ts, libraries/rush-lib/src/api/test/CommonVersionsConfiguration.test.ts, libraries/rush-lib/src/api/test/__snapshots__/CommonVersionsConfiguration.test.ts.snap, libraries/rush-lib/src/api/test/jsonFiles/common-versions-with-ensureConsistentVersionsTrue.json
Fixes https://github.com/microsoft/rushstack/issues/4826
The code that determines which version to add uses the `ensureConsistentVersions` property from the object that is constructed from the `common-versions.json` file. This was introduced in https://github.com/microsoft/rushstack/pull/4735. This issue was caused by a missed case - the `ensureConsistentVersions` property of `rushConfiguration` is marked as `@deprecated`, but its value wasn't plumbed into the `CommonVersionsConfiguration` object. This PR uses the `rush.json` value if a value wasn't provided in `common-versions.json`
Tested in a repo with a repro, and added unit tests for the `CommonVersionsConfiguration` change.
None.
=> [rush] Fix an issue where `rush add` always adds the latest version if `ensureConsistentVersions` is set in `rush.json`.

apps/heft/src/schemas/templates/heft.json, common/changes/@rushstack/heft/octogonz-heft-json-template_2024-07-11-01-18.json
Although we don't (currently) have a `heft init` command, the file [schemas/templates/heft.json](https://github.com/microsoft/rushstack/blob/main/apps/heft/src/schemas/templates/heft.json) was meant to provide a starter file that documents all the settings.
It seems this file has gotten out of sync with the website.
This file is documentation only.
Corresponds to PR https://github.com/microsoft/rushstack-websites/pull/237
=> [heft] Update schemas/templates/heft.json

build-tests-subspace/rush-sdk-test/config/heft.json, build-tests-subspace/rush-sdk-test/src/run-start.ts, build-tests-subspace/rush-sdk-test/src/start.ts, common/changes/@microsoft/rush/fix-deep-reference-to-internal-api_2024-07-05-09-42.json, libraries/rush-sdk/package.json
This PR is to address the issue https://github.com/microsoft/rushstack/issues/4308
We can now import APIs from deep paths.
None
=> [rush] Support deep references to internal Apis

common/changes/@microsoft/rush/chore-inject-deps_2024-07-11-06-27.json, libraries/rush-lib/src/logic/RepoStateFile.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
Yesterday, we received an on-call stating that a user experienced a failure in the CI installation process, even after executing `rush update`.
After investigating, we discovered that the `repo-state.json` file includes the `packageJsonInjectedDependenciesHash`, but `alwaysInjectDependenciesFromOtherSubspaces` is not enabled. 
We believe this error negatively impacts the user experience. Users do not know how to resolve the issue after receiving the error message. So, we made a small modification to the source code:
I think a better way is to give a warning without interrupting the installation process.
1. Remove `alwaysInjectDependenciesFromOtherSubspaces` from  the`pnpm-config.json` file.
2. Run `rush update`.
3. Run `rush install`.
4. Installion successful.
None.
=> [rush-lib] Don't interrupt the installation process if the user hasn't enabled the inject dependencies feature.

common/changes/@rushstack/operation-graph/main_2024-07-15-21-27.json, libraries/operation-graph/src/WatchLoop.ts
Adds error handling in the event that Heft, when orchestrated in IPC mode, fails to send a postmessage to the host. This condition is treated as a fatal error and rejects the watcher promise, which will cause the process to exit with a non-zero exit code and log the error, instead of hitting the unhandled error hook.
Copied the version over and ran it locally to confirm that the normal code path still works. Error handling not currently separately tested.
None.
=> [heft] Handle errors when IPC messaging host

common/changes/@microsoft/rush/octogonz-rush-init-fix2_2024-07-17-07-12.json, common/config/rush/version-policies.json, libraries/rush-lib/src/cli/RushCommandLineParser.ts, libraries/rush-lib/src/cli/actions/InitAction.ts
`rush init` was broken in 5.130.0
=> [rush] Fix "rush init" regression

rush.json
PNPM 8.15.9 includes a [backport](https://github.com/pnpm/pnpm/releases/tag/v8.15.9) of PR https://github.com/pnpm/pnpm/pull/8126 which fixed issue https://github.com/pnpm/pnpm/issues/7833.  It is a race condition that was causing Rush Stack CI pipelines to fail `rush install` occasionally with various error messages such as:
- `PERM: operation not permitted`
- `'nt.js" --config .eslintrc.js' is not recognized as an internal or external command`
🏆 Thank you @KSXGitHub for the fix.
=> Upgrade to PNPM 8.15.9

common/changes/@microsoft/rush/fix-edge-case_2024-07-18-06-38.json, libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
After removing `dependenciesMeta` from `package.json` and running `rush update`, the pnpm lockfile isn't updated because Rush doesn't consider the update of `dependenciesMeta`.
After removing `dependenciesMeta` and running `rush update`, it can update the lockfile normally.
None.
=> [rush-lib] Fix edge cases where Rush does not update the lockfile

apps/api-extractor/src/api/ExtractorConfig.ts, apps/api-extractor/src/api/IConfigFile.ts, apps/api-extractor/src/schemas/api-extractor-template.json, apps/api-extractor/src/schemas/api-extractor.schema.json, common/changes/@microsoft/api-extractor/octogonz-ae-reportfilename-extension_2024-07-22-22-08.json
Motivated by the discussion from https://github.com/microsoft/rushstack/issues/4842:
- Clarify the docs for reportFileName
- Fix an edge case where the code that stripped the file extension would incorrectly match the middle of a string @Josmithr 
After this is merged, we need to add website docs for the new `reportVariants` setting (PR https://github.com/microsoft/rushstack/pull/4621)
=> [api-extractor] Clarify "reportFileName" semantics

apps/api-extractor/src/schemas/api-extractor-template.json, common/changes/@microsoft/api-extractor/octogonz-ae-reportfilename-extension_2024-07-23-18-27.json
Update some comments while syncing with the website in PR https://github.com/microsoft/rushstack-websites/pull/262
=> [api-extractor] Update some comments in api-extractor-template.json

common/changes/@rushstack/webpack5-localization-plugin/localization-stats_2024-07-30-17-34.json, common/reviews/api/webpack5-localization-plugin.api.md, webpack/webpack5-localization-plugin/src/LocalizationPlugin.ts, webpack/webpack5-localization-plugin/src/interfaces.ts, webpack/webpack5-localization-plugin/src/test/LocalizedNoAsync.test.ts
Adds the current webpack `Compilation` object as an additional parameter to the `localizationStats` callback. This ensures that a caller who wishes to do custom serialization of the object can use the webpack compilation to emit it.
Exactly as it says on the tin.
Added unit test coverage.
Docs on the callback.
=> [localization-plugin] Include webpack compilation in stats callback

common/changes/@microsoft/rush/sennyeya-prevent-errors-on-before-execute_2024-07-28-22-23.json, libraries/rush-lib/src/logic/operations/CacheableOperationPlugin.ts
Fixes #4831.
This ended up being easier than I thought it would be, the issue was that `afterExecuteOperation` runs regardless of it `beforeExecuteOperation` threw. `afterExecuteOperation` expects the build cache terminal to still be open, and cleans up the terminal itself after execution. All we need to do is remove the double cleanup in `beforeExecuteOperation`
Tested locally with `build-tests/rush-redis-cobuild-plugin-integration-test/sandbox/sharded-repo`. 
<details><summary>Before</summary>
<p>
```
==[ FAILURE: 9 operations ]====================================================
--[ FAILURE: b (build) - shard 1/5 ]-------------------------[ 0.01 seconds ]--
Internal Error: Early return status should not be set: EXECUTING
You have encountered a software defect. Please consider reporting …
```
=> fix(rush): don't panic when cache beforeExecute fails

common/changes/@rushstack/webpack5-localization-plugin/localization-plugin-perf_2024-08-06-01-24.json, webpack/webpack5-localization-plugin/src/AssetProcessor.ts
Applies some preliminary checks to localized replacement strings before invoking `string.replace` to avoid allocating unnecessary strings when there are no characters that need escaping.
The calls to `string.replace` are expensive and most localized strings don't contain `\`, `"`, `'`, `\t`, `\n` or `\r`.
Unit tests for behavior.
Before:
After:
None.
=> [localization-plugin] Improve localized asset construction performance by 50%

common/changes/@microsoft/rush/fix-rush-sdk-bundling_2024-08-08-21-07.json, common/config/rush/version-policies.json, libraries/rush-sdk/.npmignore, libraries/rush-sdk/webpack.config.js
Currently when `@rushstack/rush-sdk` is bundled by a dependent project, calling into it won't work because a shared chunk is generated and isn't consumed by the bundler. This PR removes the commons chunk.
Tested in a project that has an issue.
=> [rush] Fix bundling of rush-sdk.

common/changes/@microsoft/rush/fix-pnpm-patch_2024-08-09-10-38.json, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts
After upgrading the rush version(5.131.0) in tiktok monorepo, we encountered an error when running `rush-pnpm --subspace subspaceName patch-commit xxxx`
After taking a close look at the rush source code, I found that the path to the folder related to the pnpm patches was incorrect. Therefore, I fixed this issue in that MR
To test the implementation, the following commands were executed:
1. `rush install -t .`
2. `rush-pnpm --subspace subspaceName patch xxx`
3. `rush-pnpm --subspace subspaceName patch-commit xxx`
No errors were encountered.
None
=> [rush-pnpm] Fix rush-pnpm patch-commit command

apps/lockfile-explorer/src/utils/init.ts, common/changes/@microsoft/rush/fix-patches-subspace-folder_2024-08-11-02-27.json, common/changes/@rushstack/lockfile-explorer/fix-patches-subspace-folder_2024-08-11-03-11.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/LastInstallFlag.ts, libraries/rush-lib/src/api/Subspace.ts, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts, libraries/rush-lib/src/cli/actions/DeployAction.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/cli/test/TestUtils.ts, libraries/rush-lib/src/logic/TempProjectHelper.ts, libraries/rush-lib/src/logic/UnlinkManager.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/base/BaseLinkManager.ts, libraries/rush-lib/src/logic/installManager/InstallHelpers.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/logic/pnpm/PnpmProjectShrinkwrapFile.ts, libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts, libraries/rush-lib/src/logic/pnpm/SubspacePnpmfileConfiguration.ts, libraries/rush-lib/src/logic/test/ShrinkwrapFile.test.ts
https://github.com/microsoft/rushstack/pull/4874 inadvertently moved the pnpm-patches folder from `common/pnpm-patches` to `common/config/rush/pnpm-patches` when subspaces are disabled. This PR restores the previous location for the non-subspaces case.
Tested on a non-subspaces repo and in this repo (which is using subspaces).
=> [rush] Put pnpm patches back in common/pnpm-patches when subspaces are not enabled.

common/changes/@rushstack/localization-utilities/allow-569XZilmsin-string-names_2024-08-12-05-26.json, common/changes/@rushstack/node-core-library/allow-569XZilmsin-string-names_2024-08-12-21-24.json, common/reviews/api/node-core-library.api.md, libraries/localization-utilities/src/parsers/parseLocJson.ts, libraries/localization-utilities/src/schemas/locJson.schema.json, libraries/node-core-library/src/JsonSchema.ts, libraries/node-core-library/src/index.ts
Adds the `$` character to the schema for `.loc.json` string names. The `$` character is allowed in JavaScript variable names.
~~https://jsbench.me/wxlsb1hcmr/1~~
~~Consideration, this is about 20% slower.~~
Revised the approach to add an API to node-core-library's `JsonSchema` validation to ignore the `$schema` property.
=> [localization-utilities] Update the .loc.json schema to allow for string names that include the '$' character.

common/changes/@rushstack/ts-command-line/patch-1_2024-08-14-11-35.json, libraries/ts-command-line/README.md
Fixes a typo on ts-command-line's README
=> [ts-command-line] Fixes a typo in the README

common/changes/@rushstack/heft-lint-plugin/user-danade-LintFixer_2024-08-14-00-32.json, heft-plugins/heft-lint-plugin/heft-plugin.json, heft-plugins/heft-lint-plugin/src/Eslint.ts, heft-plugins/heft-lint-plugin/src/LintPlugin.ts, heft-plugins/heft-lint-plugin/src/LinterBase.ts, heft-plugins/heft-lint-plugin/src/Tslint.ts, heft-plugins/heft-lint-plugin/src/internalTypings/TslintInternals.ts, heft-plugins/heft-lint-plugin/src/schemas/heft-lint-plugin.schema.json
Add fixer support for ESLint and TSLint.
Fixes #2769.
Fixes can now be automatically applied when the `--fix` CLI flag is provided, or the `alwaysFix` plugin option is provided in heft.json. 
- Validated in-repo via TSLint- and ESLint-enabled projects
=> [heft-lint-plugin] Add ESLint and TSLint fixer support

common/changes/@microsoft/rush/jmaher-prevent-decoupled-workspace-deps_2024-07-30-15-46.json, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
Adds a check in install step to prevent a host project depending on a workspace: package version if the package is also listed in decoupledLocalDependencies.
Currently unaware of any use case that this would be intended. We came across this issue when migrating a dependency from an external feed (e.g. `"@<namespace>/packageA": "1.2.3"`) to a workspace dependency, and didn't remove the package from `decoupledLocalDependencies`. 
We came across an issue which allows a host package to depend on a package with `workspace:` notation while also listing that package in its `decoupledLocalDependencies`. Because this is currently not checked, this can result in a missing dependency in CI runs because the `package@workspace:` is not guaranteed to be built prior to the package that depends on it, so …
=> [rush-lib] prevent workspace dependencies in decoupledLocalDependencies

common/changes/@microsoft/rush/kenrick-overrides-check_2024-08-22-06-49.json, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts
Fixes #4820
Add one more condition in WorkspaceInstallManager to compare the objects:
- pnpm-config.json's `globalOverrides`
- shrinkwrap's `overrides`
1. Run `testrush update` in a Rush repo
2. Change `globalOverrides`
3. Run `testrush update` and expect that it updates the lockfile
```
> testrush update
Rush Multi-Project Build Tool 5.132.0 (unmanaged) - https://rushjs.io
Node.js version is 18.20.4 (LTS)
Starting "rush update"
Checking Git policy for this repository.
Found files in the "common/git-hooks" folder.
Successfully installed these Git hook scripts: commit-msg, owners.json, post-checkout, pre-commit, pre-push
Trying to acquire lock for pnpm-8.15.8
Acquired lock for pnpm-8.15.8
Found pnpm version 8.15.8 in /path/to/user/.rush/node-v18.20.4/pnpm-8.15.8
Symlinking …
```
=> [rush-lib] fix: update shrinkwrap when globalOverrides has change

common/changes/@microsoft/rush/user-dmichon-suppress-registry-call_2024-08-22-21-46.json, libraries/rush-lib/assets/rush-init/rush.json, libraries/rush-lib/src/api/RushConfiguration.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/setup/SetupPackageRegistry.ts, libraries/rush-lib/src/schemas/rush.schema.json
Add a new option to rush.json `"suppressRushIsPublicVersionCheck"` that disables a hardcoded call to the public npmjs.org registry to validate that the executing version of Rush (according to `package.json`) matches one that has been published to the public registry.
This feature is to support enterprises that run Rush on machines that they are denying access to npmjs.org.
Also defer loads the `WebClient` wrapper around `node-fetch` to reduce startup time.
Updated `rush-init` template to include the setting.
Walked through `rush install` under debugger and validated that the condition hit both branches depending on the setting in `rush.json`.
Docs for `rush.json`
=> [rush] Add option to suppress hardcoded npmjs.org registry call

common/changes/@rushstack/webpack-workspace-resolve-plugin/resolver-new_2024-08-23-23-41.json, webpack/webpack-workspace-resolve-plugin/src/KnownDescriptionFilePlugin.ts
Some plugins manage to still be impacted by mutating a `ResolveRequest` object. Stop doing so.
Removes an attempted optimization in `KnownDescriptionFilePlugin`.
Unit tests.
Testing in a target repository.
None.
=> [webpack-resolve] Fix bug caused by mutating request

common/changes/@microsoft/rush/bundled-dependencies_2024-08-24-01-03.json, common/changes/@rushstack/lookup-by-path/bundled-dependencies_2024-08-26-18-08.json, common/changes/@rushstack/webpack-workspace-resolve-plugin/bundled-dependencies_2024-08-24-01-03.json, common/reviews/api/lookup-by-path.api.md, common/reviews/api/webpack-workspace-resolve-plugin.api.md, libraries/lookup-by-path/src/LookupByPath.test.ts, libraries/lookup-by-path/src/LookupByPath.ts, libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts, rush-plugins/rush-resolver-cache-plugin/src/afterInstallAsync.ts, rush-plugins/rush-resolver-cache-plugin/src/computeResolverCacheFromLockfileAsync.ts, rush-plugins/rush-resolver-cache-plugin/src/helpers.ts, rush-plugins/rush-resolver-cache-plugin/src/test/__snapshots__/computeResolverCacheFromLockfileAsync.test.ts.snap, rush-plugins/rush-resolver-cache-plugin/src/test/computeResolverCacheFromLockfileAsync.test.ts, rush-plugins/rush-resolver-cache-plugin/src/types.ts, rush-plugins/rush-resolver-cache-plugin/test-collateral/bundled-dependencies.yaml, webpack/webpack-workspace-resolve-plugin/src/KnownDescriptionFilePlugin.ts, webpack/webpack-workspace-resolve-plugin/src/KnownPackageDependenciesPlugin.ts, webpack/webpack-workspace-resolve-plugin/src/WorkspaceLayoutCache.ts, webpack/webpack-workspace-resolve-plugin/src/test/KnownPackageDependenciesPlugin.test.ts, webpack/webpack-workspace-resolve-plugin/src/test/createResolveForTests.ts
Updates `@rushstack/lookup-by-path` to return a linked list of matches from `findLongestPrefixMatch`, where the head of the list is the longest match and each link is a successively shorter match.
Updates `@rushstack/rush-resolver-cache-plugin` to parse `bundledDependencies` and include that data in the resolver cache file.
Updates `@rushstack/webpack-workspace-resolve-plugin` to handle hierarchical `node_modules` if the cache indicates such.
Cache file now allows a context to have a pointer to the parent context.
Cache file now allows the `deps` field to be omitted.
Docs for the plugins.
=> Support bundled dependencies in resolver plugin

common/changes/@microsoft/rush/sennyeya-ignore-flags-when-resolution-only_2024-08-28-17-54.json, libraries/rush-lib/src/logic/base/BaseInstallManager.ts
Fixes an issue with #4893 where running `rush install --resolution-only` would write the LastInstall flag but wouldn't install any packages, so subsequent `rush install`'s would pass without doing anything, causing a broken module state. This PR skips the LastInstall check when using `--resolution-only` and runs pnpm every time.
I set the `usePnpmFrozenLockfileForRushInstall` experiment to false in both our monorepo and the rush monorepo, 
1. ran `rush purge`
1. ran `node ./apps/rush/lib/start-dev install --resolution-only` 
2. ran `node ./apps/rush/lib/start-dev install` - ensured that the install actually finished
3. ran `node ./apps/rush/lib/start-dev install --resolution-only` to ensure that the resolution check happens again
2. ran `node ./apps/rush/lib/start-dev install` to ensure …
=> [rush] fix: ignore flags when doing install with resolution only

common/changes/@rushstack/webpack-workspace-resolve-plugin/fix-workspace-resolve_2024-08-28-22-55.json, webpack/webpack-workspace-resolve-plugin/src/WorkspaceResolvePlugin.ts
Fixes a bug in `@rushstack/webpack-workspace-resolve-plugin` wherein cross-package imports didn't use `@rushstack/webpack-workspace-resolve-plugin` to lookup the `package.json` for the destination package.
Added a missing instance of `KnownDescriptionFilePlugin` after `KnownPackageDependenciesPlugin`.
Ran the modified version against a real production repository and verified successful build (using `@rushstack/rush-resolver-cache-plugin`.
None.
=> [workspace-resolve] Fix cross-package import

common/changes/@microsoft/rush/resolver-cache-windows_2024-08-29-18-03.json, rush-plugins/rush-resolver-cache-plugin/src/computeResolverCacheFromLockfileAsync.ts, rush-plugins/rush-resolver-cache-plugin/src/test/computeResolverCacheFromLockfileAsync.test.ts
Fixes compatibility of `@rushstack/rush-resolver-cache-plugin` with Windows.
Performs slash normalization on inputs so that `path.posix.join` calls work correctly.
Updated unit tests to try passing in `\` delimited paths and verified that the output is unchanged.
None.
=> [rush-resolver-cache] Fix Windows compatibility

common/changes/@microsoft/rush/expose_credentialCacheId_2024-09-06-23-00.json, common/reviews/api/rush-azure-storage-build-cache-plugin.api.md, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureAuthenticationBase.ts
Marks `AzureAuthenticationBase._credentialCacheId` as protected to allow subclasses to read it.
N/A
None.
=> [rush] Expose AzureAuthenticationBase._credentialCacheId.

common/changes/@microsoft/rush/rush-pnpm-patch-remove_2024-09-01-01-28.json, libraries/rush-lib/src/cli/RushPnpmCommandLineParser.ts
Support `rush-pnpm patch-remove` command
"pnpm patch-remove" was introduced in the pnpm's 8.5.0 version. It's used to remove the patched dependencies. Official doc: https://pnpm.io/cli/patch-remove.
Technically, it follows the same fashion of `rush-pnpm patch-commit`. Sync up related files after executing `pnpm patch-remove` internally.
Here is a screenshot running the command locally.
Tested in Sparo repo.
I suppose not. The current `rush-pnpm` page in rush.js website doesn't list all supported commands there.
Quick link: https://rushjs.io/pages/commands/rush-pnpm/
=> [rush] supports "rush-pnpm patch-remove" command

common/changes/@rushstack/node-core-library/rf-jsonschema-add-custom-formats_2024-09-10-03-15.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/JsonSchema.ts, libraries/node-core-library/src/index.ts, libraries/node-core-library/src/test/JsonSchema.test.ts
Was putting up a [PR to Relay](https://github.com/facebook/relay/pull/4780) to load configuration files and was running into issues using `JsonSchema` because Relay's configuration JSON schema has formats like `uint8` coming from [schemars](https://github.com/GREsau/schemars).  Rather than dropping down to raw AJV was just hoping to expose some minimal/reasonable API surface here to support validating custom formats
=> Add custom formats to JsonSchema

common/changes/@rushstack/package-extractor/user-danade-CustomLinkCreationScriptPath_2024-09-10-23-52.json, common/reviews/api/package-extractor.api.md, libraries/package-extractor/src/PackageExtractor.ts, libraries/package-extractor/src/scripts/create-links.ts, libraries/package-extractor/src/test/PackageExtractor.test.ts
Allows for placing the "create-links.json" file and it's associated metadata file to be modified when operating in "script" mode.
Currently the "create-links.js" file gets created in the root of the extraction. This PR allows for changing where this file gets placed, which will allow for overlaying of multiple extractions from the same repository while allowing a custom location for all extraction scripts and metadatas.
Added unit tests
May require website document updates for new parameter
=> [package-extractor] Allow for a custom link creation script path to be used for the create-links.js file

common/changes/@microsoft/rush/kenrick-fix-update-shrinkwrap-packageExtensions_2024-09-06-03-55.json, common/changes/@rushstack/node-core-library/kenrick-fix-update-shrinkwrap-packageExtensions_2024-09-06-03-55.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/Sort.ts, libraries/node-core-library/src/index.ts, libraries/node-core-library/src/test/Sort.test.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
Fixes #4901
Add one more condition in WorkspaceInstallManager to compare the values of:
- pnpm-config.json's `globalPackageExtensions` checksum
- shrinkwrap's `packageExtensionsChecksum`
To calculate the checksum, I added the same implementation as per what's used in pnpm ([ref](https://github.com/pnpm/pnpm/blob/ba9409ffcef0c36dc1b167d770a023c87444822d/pkg-manager/core/src/install/index.ts#L821-L824)). The code snippet used in pnpm is as such:
```ts
const packageExtensionsChecksum = isEmpty(opts.packageExtensions ?? {}) ? undefined : createObjectChecksum(opts.packageExtensions!)
export function createObjectChecksum (obj: Record<string, unknown>) {
const s = JSON.stringify(sortKeys(obj, { deep: true }))
return crypto.createHash('md5').update(s).digest('hex')
}
```
Since it depends on …
=> [rush-lib] fix: update shrinkwrap when globalPackageExtensions has been changed

common/changes/@microsoft/rush/pass-credential-cache_2024-09-12-23-22.json, common/reviews/api/rush-azure-storage-build-cache-plugin.api.md, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureAuthenticationBase.ts
Pass the initialized credentials cache to `AzureAuthenticationBase._getCredentialFromTokenAsync` in `@rushstack/rush-azure-storage-build-cache-plugin`.
N/A
API
=> [rush] Pass the credentials cache into _getCredentialFromTokenAsync.

common/changes/@rushstack/eslint-config/main_2024-09-18-08-53.json, common/changes/@rushstack/eslint-plugin-security/main_2024-09-18-08-53.json, common/changes/@rushstack/eslint-plugin/main_2024-09-18-08-53.json, eslint/eslint-config/README.md, eslint/eslint-plugin-security/README.md, eslint/eslint-plugin/README.md
PR #3065 moved the location of the ESLInt files. This PR adjusts sources to changes.
=> Fix ESLint links

apps/rush/UPGRADING.md, build-tests/rush-redis-cobuild-plugin-integration-test/sandbox/sharded-repo/projects/a/config/rush-project.json, build-tests/rush-redis-cobuild-plugin-integration-test/sandbox/sharded-repo/projects/b/config/rush-project.json, build-tests/rush-redis-cobuild-plugin-integration-test/sandbox/sharded-repo/projects/e/config/rush-project.json, common/changes/@microsoft/rush/sennyeya-shard-schema-updates_2024-09-13-22-46.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/RushProjectConfiguration.ts, libraries/rush-lib/src/logic/operations/ShardedPhaseOperationPlugin.ts, libraries/rush-lib/src/schemas/rush-project.schema.json
Followup to @iclanton's comments in https://github.com/microsoft/rushstack/pull/4871. Moving the config for shards to its own object instead of piggybacking onto the collate operation.
As-is this is a breaking change, open to thoughts on how to roll this out safely.
Tested locally against the rush-redis-cobuild-plugin-integration-tests.
Schema definitions will need to be updated.
=> [rush] move sharded operation config to its own block

common/changes/@microsoft/rush/fix-project-folder_2024-09-20-00-10.json, rush-plugins/rush-resolver-cache-plugin/src/computeResolverCacheFromLockfileAsync.ts, rush-plugins/rush-resolver-cache-plugin/src/test/computeResolverCacheFromLockfileAsync.test.ts
Fixes forward vs back slashes in the `projectFolder` value for Rush projects on Windows in the `rush-resolver-cache-plugin`.
Normalizes to forward slashes inside of the processor.
Updated unit tests.
Ran an install with it on Windows.
None.
=> [rush-resolver-cache] Fix projectFolder on Windows

build-tests/rush-redis-cobuild-plugin-integration-test/README.md, build-tests/rush-redis-cobuild-plugin-integration-test/sandbox/sharded-repo/common/config/rush/experiments.json, build-tests/rush-redis-cobuild-plugin-integration-test/sandbox/sharded-repo/projects/e/config/rush-project.json, common/changes/@microsoft/rush/sennyeya-allow-cobuild-orchestration_2024-08-08-23-11.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/assets/rush-init/common/config/rush/experiments.json, libraries/rush-lib/src/api/CobuildConfiguration.ts, libraries/rush-lib/src/api/EnvironmentConfiguration.ts, libraries/rush-lib/src/api/ExperimentsConfiguration.ts, libraries/rush-lib/src/api/RushProjectConfiguration.ts, libraries/rush-lib/src/logic/operations/CacheableOperationPlugin.ts, libraries/rush-lib/src/schemas/experiments.schema.json, libraries/rush-lib/src/schemas/rush-project.schema.json
From my thread in Zulip, [here](https://rushstack.zulipchat.com/#narrow/stream/262513-general/topic/cobuild.20support.20for.20orchestrating.20tasks.20without.20build.20cache/near/455446864). 
Currently, cobuilds rebuild un-cacheable operations across all machines. This is the expected behavior for core nodes that aren't cacheable to ensure artifacts are found for projects further up the tree. For operations like uploading/processing coverage or image building, that approach doesn't apply well and ends up in (number of machines)x more work being done. This PR attempts to add a new experiment/feature that allows users to use the cobuild orchestration engine without relying on the build cache. Inherently, this introduces risk for projects that enable this without knowing what it does as …
=> [rush] feat(cobuilds): allow orchestration without using the build cache

common/changes/@microsoft/rush/logging-enhancement_2024-09-19-00-28.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/index.ts, libraries/rush-lib/src/logic/operations/CacheableOperationPlugin.ts, libraries/rush-lib/src/logic/operations/IOperationExecutionResult.ts, libraries/rush-lib/src/logic/operations/OperationExecutionRecord.ts, libraries/rush-lib/src/logic/operations/ProjectLogWritable.ts, rush-plugins/rush-serve-plugin/src/RushProjectServeConfigFile.ts, rush-plugins/rush-serve-plugin/src/RushServePlugin.ts, rush-plugins/rush-serve-plugin/src/api.types.ts, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts, rush-plugins/rush-serve-plugin/src/schemas/rush-serve-plugin-options.schema.json
Leaves ANSI escape codes present in the JSONL log files, so that color information will be preserved when replaying from cache.
Adds a property `logFilePaths` to `IOperationExecutionResult` so that they are available to plugins that may wish to interact with them.
Adds a property `logServePath` to the options for `rush-serve-plugin` that specifies a base path under which all log files will be made available via the local server.
The `logFilePaths` property will only be defined for operations that created log files.
Served files are all in a single flat directory. This may cause collisions if two projects in the same repository have the same unscoped package name, since the naming convention for log files uses the unscoped package name, rather than the full package name.
Refactors …
=> [rush] Logging enhancements

common/changes/@rushstack/package-deps-hash/hash-files-async_2024-09-20-22-45.json, common/reviews/api/package-deps-hash.api.md, libraries/package-deps-hash/src/getRepoState.ts, libraries/package-deps-hash/src/index.ts
Exposes an asynchronous API for hashing files via `git hash-object`. This API supports the file names being provided asynchronously.
This is the underlying API that performs file hashing for untracked or locally-modified files in `getRepoStateAsync`.
This differs from `getGitHashForFiles` in that the API is asynchronous, and that it does not invoke `path.resolve`.
It is used by `getRepoStateAsync`, so the existing unit tests for `getRepoStateAsync` cover its functionality.
Function documentation.
=> [package-deps-hash] Expose `hashFilesAsync` API

common/changes/@rushstack/webpack5-localization-plugin/webpack-loc-related-loop_2024-09-23-21-19.json, webpack/webpack5-localization-plugin/src/AssetProcessor.ts
Fixes a bug that was causing emitting of webpack stats to encounter a stack overflow.
The `related` property on the webpack `AssetInfo` objects must not be cyclic for the current version of the webpack stats emitter.
Used the modified version to emit webpack stats.
None.
=> [webpack-localization-plugin] Fix circular reference in assetInfo.related

common/changes/@microsoft/rush/fix-variants-param_2024-09-26-22-21.json, common/config/rush/version-policies.json, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/installManager/doBasicInstallAsync.ts
Minor follow-up from https://github.com/microsoft/rushstack/pull/4927
Tested in this repo.
None.
=> [rush] Fix a few issues with the variants PR.

common/changes/@rushstack/typings-generator/main_2024-09-27-16-41.json, libraries/typings-generator/README.md
Commit 78e6fd312930750428f42cca81b55dc2a4090ec1 moved the location of `Terminal.ts`. This PR adjusts sources to changes.
=> Fix Terminal reference

apps/heft/src/operations/runners/TaskOperationRunner.ts, apps/heft/src/pluginFramework/IncrementalBuildInfo.ts, apps/heft/src/pluginFramework/tests/IncrementalBuildInfo.test.ts, apps/heft/src/pluginFramework/tests/__snapshots__/IncrementalBuildInfo.test.ts.snap, apps/heft/src/plugins/CopyFilesPlugin.ts, build-tests/heft-copy-files-test/config/rush-project.json, common/changes/@rushstack/heft/copy-file-if-changed_2024-09-26-22-16.json
Fixes #4942
Updates the underlying logic in Heft's `copy-files-plugin` to write an incremental cache file, that will be used to only copy files where the inputs have changed. This also impacts the file copy in `heft-typescript-plugin`.
Adds a new API to read and write incremental cache files, for use by other plugins.
Incremental cache files store a config hash, a list of input files with SHA-256 hashes, and optionally a mapping from output file names to indices of input files.
Each task will get its own unique `file-copy.json` cache file in the task's temp folder if there are a non-zero number of copy operations configured for the task.
Using `build-tests/heft-copy-files-plugin`.
Copy files.
=> [heft] Update file copy layer to support incremental disk cache

apps/heft/src/pluginFramework/IncrementalBuildInfo.ts, apps/heft/src/plugins/CopyFilesPlugin.ts, common/changes/@rushstack/heft/copy-file-watch_2024-09-30-20-22.json
Fixes bugs in #4943
 
Ensures that the file copy incremental cache file contains the correct entries.
Ensures that the file copy incremental cache file preserves all entries during a watch mode rebuild, and not only the entries that were changed in the most recent incremental iteration.
Running `heft build-watch` in `build-tests/heft-file-copy-test` and validating the content of the cache file.
None
=> [heft] Fix incremental copy cache file

apps/heft/src/operations/runners/TaskOperationRunner.ts, apps/heft/src/pluginFramework/IncrementalBuildInfo.ts, apps/heft/src/plugins/CopyFilesPlugin.ts, apps/heft/src/plugins/DeleteFilesPlugin.ts, apps/heft/src/plugins/FileGlobSpecifier.ts, common/changes/@rushstack/heft/copy-files-hash_2024-10-01-20-05.json
Fixes an issue where the configHash for incremental file copy state was calculated by hashing absolute paths and was therefore not portable.
Fixes the hash to be calculated using relative paths.
Moves hash computation to avoid duplicate work on watch mode rebuilds.
Existing build tests, plus running `heft-webpack5-everything-test` under debugger and validating the inputs to the hash were relative, since these come from `heft-typescript-plugin` and are therefore a more interesting case than the `CopyFilesPlugin`.
None
=> [heft] Fix portability of configHash for incremental file copy

build-tests/heft-sass-test/config/sass.json, build-tests/heft-sass-test/package.json, common/changes/@rushstack/heft-sass-plugin/sass-silence-deprecations_2024-10-02-01-20.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json, heft-plugins/heft-sass-plugin/package.json, heft-plugins/heft-sass-plugin/src/SassProcessor.ts, heft-plugins/heft-sass-plugin/src/schemas/heft-sass-plugin.schema.json, heft-plugins/heft-sass-plugin/src/templates/sass.json
Adds new options to `sass.json`:
- `ignoreDeprecationsInDependencies` - Ignores deprecation warnings that originate in externals. Same as the `--quiet-deps` CLI flag to the SASS compiler.
- `silenceDeprecations` - Takes an array of deprecation codes and silences all warnings about them. Same as the `--silence-deprecations` CLI parameter to the SASS compiler.
Modified heft-sass-test to use the option. It has some instances of the `"mixed-decls"` deprecation in existing files.
Options for the `heft-sass-plugin`.
=> [heft-sass] Allow suppressing SASS deprecation warnings

common/changes/@microsoft/rush/script-priority_2024-10-03-01-47.json, libraries/rush-lib/src/logic/operations/IPCOperationRunnerPlugin.ts, libraries/rush-lib/src/logic/operations/ShardedPhaseOperationPlugin.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunner.ts, libraries/rush-lib/src/logic/operations/ShellOperationRunnerPlugin.ts, libraries/rush-lib/src/schemas/command-line.schema.json
Changes the algorithm for executing phased commands in watch mode to prefer a script named `_phase:<name>:incremental` for every iteration after the first. The typical scenario for such would be to omit cleaning from an incremental run.
The build cache will still treat the `:incremental` commands as having the same cache key as the non-incremental command, so later iterations can still encounter cache hits. However, cache writes do not occur in iterations after the first.
Temporarily added a `_phase:build:incremental` to a project and ran `rush start`. Validated that the `_phase:build:incremental` script was used for the second iteration. Validated that modifying inputs back to a state known to be present in the cache resulted in a cache hit.
Documentation on phased commands.
=> [rush] Look for `:incremental` suffixed scripts in watch mode

apps/api-extractor/src/analyzer/ExportAnalyzer.ts, apps/api-extractor/src/analyzer/TypeScriptInternals.ts, common/changes/@microsoft/api-extractor/fix-5.6_2024-10-14-19-47.json
Fixes #4919
`getModeForUsageLocation` has required compiler options for a while, but this was hidden by an `as any`. Passing in the compiler options prevents the crash.
I made the same change in `node_modules` for typescript-eslint, and api-extractor no longer crashed.
It's not clear to me how to test this otherwise without also upgrading the repo to TS 5.6.
None.
=> [api-extractor] pass compilerOptions into getModeForUsageLocation to fix TS 5.6

common/changes/@rushstack/heft-typescript-plugin/heft-typescript-plugin-typescript-56-support_2024-10-13-22-44.json, heft-plugins/heft-typescript-plugin/src/TypeScriptBuilder.ts, heft-plugins/heft-typescript-plugin/src/internalTypings/TypeScriptInternals.ts
Updates the heft typescript plugin for breaking changes made to the typescript internals that the plugin relies on
The breakage was caused by an internal change of `BuilderProgram.getState()` to `BuilderProgram.state` in [this](https://github.com/microsoft/TypeScript/commit/b9d96df61f01375da6504f37a31151cfdce0645c) commit. 
Changing the code to use `.state` instead of `.getState()` if `state` is defined was the only change required
Fixes #4921 
Linked into our monorepo and a full build of all packages was done
Then everything was started in watch mode and a webpack based package was started up to verify that watch mode changes are still picked up correctly
Our monorepo does not use heft for linting so I haven't tested if this change still works correctly with the heft lint plugin
=> [heft-typescript-plugin] feat: support typescript 5.6

common/changes/@rushstack/ts-command-line/expand-alternatives-api_2024-10-17-07-31.json, common/changes/@rushstack/ts-command-line/expand-alternatives-api_2024-10-17-07-33.json, common/reviews/api/ts-command-line.api.md, libraries/ts-command-line/src/parameters/BaseClasses.ts, libraries/ts-command-line/src/parameters/CommandLineChoiceListParameter.ts, libraries/ts-command-line/src/parameters/CommandLineChoiceParameter.ts, libraries/ts-command-line/src/parameters/CommandLineDefinition.ts, libraries/ts-command-line/src/providers/CommandLineParameterProvider.ts, libraries/ts-command-line/src/providers/TabCompletionAction.ts, vscode-extensions/rush-vscode-command-webview/src/ParameterView/ParameterForm/index.tsx
Expand the `alternatives` and `completions` options of `CommandLineChoiceParameter` and `CommandLineChoiceListParameter` to allow readonly arrays and sets.
Ran the build in this repo.
API docs.
=> [ts-command-line] Expand the ts-command-line choice parameter APIs.

apps/heft/package.json, apps/heft/src/configuration/HeftConfiguration.ts, common/changes/@rushstack/heft/kill-true-case-path_2024-10-11-23-03.json, common/config/subspaces/build-tests-subspace/repo-state.json, common/config/subspaces/default/pnpm-lock.yaml
Remove usage of `true-case-path` in Heft.
The implementation of `true-case-path` performs directory enumeration of every folder between the file system root and heft's working directory. Usage of this tool was motivated by issues with drive letter casing normalization on Windows, but the implementation of doing so in true-case-path is just a hardcoded "if on Windows, uppercase the drive letter", so we may as well just do the same directly.
The directory enumerations cause problems when running inside of build systems that monitor file system accesses, since they cause the system to see the process as enumerating root-level folders.
The pipelines for this PR cover Heft sufficiently.
None.
=> [heft] Stop using true-case-path

common/changes/@rushstack/heft-config-file/update-jsonpath-plus_2024-10-23-18-42.json, common/config/subspaces/build-tests-subspace/pnpm-lock.yaml, common/config/subspaces/build-tests-subspace/repo-state.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json, libraries/heft-config-file/package.json, libraries/heft-config-file/src/test/ConfigurationFile.test.ts
Resolves https://github.com/microsoft/rushstack/issues/4966.
See [CVE-2024-21534](https://nvd.nist.gov/vuln/detail/CVE-2024-21534)
Built and ran unit tests that exercise this functionality.
=> [heft-config-file] Update jsonpath-plus to ~10.1.0

common/changes/@microsoft/rush/stdio-blank-summary_2024-10-29-00-31.json, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts
Fixes #4882 
Child process that only writes to stdout but is configured to exit with code 2.
Before:
After:
With this change, Rush internally writes any fatal error from an Operation to the `stderr` stream of the `StdioSummarizer` instead of the `stdout` stream. This effectively makes the error seen by Rush be treated as lower priority for the logs than any `stderr` output from the Operation itself.
Added `process.exitCode = 2` to the end of the build script in api-extractor-lib1-test.
Anything about the error reporting for non-zero exit codes.
=> [rush] Fix logging for non-zero exit codes

common/changes/@microsoft/rush/fix-empty-error-logs_2024-11-08-01-18.json, libraries/rush-lib/src/logic/operations/ProjectLogWritable.ts
Fixes #4991 
The lazy initializer was still present. Removes a forced initialization of the error log file.
Built a project with and without an error.
=> [rush] Fix empty error logs

common/changes/@microsoft/rush/azure-default-credential_2024-11-07-22-38.json, common/reviews/api/rush-azure-storage-build-cache-plugin.api.md, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureAuthenticationBase.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureStorageBuildCacheProvider.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/RushAzureInteractiveAuthPlugin.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/RushAzureStorageBuildCachePlugin.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/schemas/azure-blob-storage-config.schema.json, rush-plugins/rush-azure-storage-build-cache-plugin/src/schemas/azure-interactive-auth.schema.json
Improve configurability of `rush-azure-storage-build-cache-plugin`.
Adds new configuration properties:
- `loginFlow` allows specifying the interactive login flow to use: one of `AdoCodespacesAuth`, `InteractiveBrowser` or `DeviceCode`. Defaults to `InteractiveBrowser` (will fall back to `DeviceCode`).
- `readRequiresAuthentication` will make not having a valid SAS token a fatal error during cache read.
PR release
=> [rush] New parameters for Azure Storage plugin

common/changes/@microsoft/rush/include-local-only-in-build-cache-schema_2024-11-07-23-36.json, libraries/rush-lib/src/schemas/build-cache.schema.json
Simple build-cache.schema.json fix as it didn't include "local-only" option for "cacheProvider" field.
=> [rush] Fix lack of "local-only" option for cacheProvider in build-cache.schema.json

common/changes/@microsoft/rush/fix-build-cache-schema_2024-11-19-23-27.json, common/config/rush/version-policies.json, libraries/rush-lib/assets/rush-init/common/config/rush/build-cache.json, libraries/rush-lib/src/schemas/build-cache.schema.json
Updates the schema in build-cache.json so that the features in #4995 can be used.
Adds `loginFlow` and `readRequiresAuthentication` properties to the build cache schema.
Built to verify that the schema still accepts existing values.
Content of the build-cache.schema.json
=> [rush] Build cache schema reconciliation

common/changes/@rushstack/heft-jest-plugin/fix-jest-bug_2024-11-22-23-43.json, heft-plugins/heft-jest-plugin/src/JestRealPathPatch.ts
For Jest, specifically, the `realpathSync` function inside of `jest-resolve` is supposed to return the input path if part of the path does not exist.
Since `jest-resolve`'s `realpathSync` internally calls `jest-util`'s `tryRealpathSync`, and the latter is already overridden, this PR just removes the separate override in jest-resolve in favor of relying on `tryRealpathSync` being overridden centrally.
Note that this ends up caching all the paths twice, but that's less of a concern than the syscalls this feature is avoiding.
Local test invocation.
None
=> [heft-jest] Fix node-modules-symlink-resolver

common/changes/@microsoft/rush/pedrogomes-fix-install-all-projects_2024-11-26-04-35.json, libraries/rush-lib/src/cli/actions/BaseInstallAction.ts
Fix install all projects of all subspaces in a monorepo
We have a project which depends on ALL of the rest of the local packages of different subspaces.
When we run `rush install -t P1`, all subspaces except the current, are ignored with the message: "No projects matched the filters in XXX".
In other words, NO dependencies are installed (node_modules folders are empty) for the cross-subspaces that the project requires.
Subspace S1 is installed, but S2 and S3 are not! Both S2 and S3 will show the message "No projects matched the filters in XXX".
All related cross-subspaces should be properly installed. I would expect no message: "No projects matched the filters in XXX" to be shown.
After diagnosing the `pnpm install` command during a subspace installation, we discovered a package filtering …
=> [rush-lib] Fix filtered install behavior when there are dependencies on other subspaces

common/changes/@microsoft/rush/pedrogomes-fix-pnpm-overrides_2024-11-25-03-53.json, common/changes/@microsoft/rush/pedrogomes-fix-pnpm-overrides_2024-11-27-06-31.json, libraries/rush-lib/assets/rush-init/common/config/rush/pnpm-config.json, libraries/rush-lib/src/logic/ShrinkwrapFileFactory.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/logic/policy/ShrinkwrapFilePolicy.ts, libraries/rush-lib/src/logic/test/ShrinkwrapFile.test.ts
Consider subspace pnpm `globalOverrides` and `globalPackageExtensions` during install & update
During rush installation `rush install -t .`, some subspace lock files were being considered "out of date" with the warning: "The overrides settings doesn't match the current shrinkwrap.", even though nothing was changed.
We identified that one of the subspaces had ~10 global overrides (e.g. common/config/subspaces/unified_wallet/pnpm-config.json), which were the **same** as stated in its shrinkwrap file (e.g. common/config/subspaces/unified_wallet/pnpm-lock.yaml). BUT the warning was still being logged for this subspace.
Rush should consider each subspace pnpm-config.json file during shrinkwrap up-to-date evaluation. 
I would expect no warning being logged, if the subspace shrinkwrap …
=> [rush-lib] Fix overrides settings and package extensions conditions

common/changes/@microsoft/rush/fix-a-missing-variant-case_2024-12-02-22-05.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/Subspace.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts
Fixes an issue where the ability to skip 'rush install' may be incorrectly calculated when using the variants feature.
The only code path where a variant-dependent `pnpm-config.json` file referenced is in the install detection code. This removes the variant from that code path.
Tested by running `rush install` with and without `package.json` changes.
None.
=> [rush] Fix an issue where the ability to skip 'rush install' may be incorrectly calculated when using the variants feature.

apps/heft/src/utilities/CoreConfigFiles.ts, common/changes/@microsoft/rush/support-pnpm-config.json-extends_2024-12-02-23-58.json, common/changes/@rushstack/heft-api-extractor-plugin/support-pnpm-config.json-extends_2024-12-03-03-27.json, common/changes/@rushstack/heft-config-file/support-pnpm-config.json-extends_2024-12-02-23-57.json, common/changes/@rushstack/heft-config-file/support-pnpm-config.json-extends_2024-12-03-03-27.json, common/changes/@rushstack/heft-jest-plugin/support-pnpm-config.json-extends_2024-12-03-03-27.json, common/changes/@rushstack/heft-sass-plugin/support-pnpm-config.json-extends_2024-12-03-03-27.json, common/changes/@rushstack/heft-typescript-plugin/support-pnpm-config.json-extends_2024-12-03-03-27.json, common/changes/@rushstack/heft/support-pnpm-config.json-extends_2024-12-03-03-27.json, common/reviews/api/heft-config-file.api.md, heft-plugins/heft-api-extractor-plugin/src/ApiExtractorPlugin.ts, heft-plugins/heft-jest-plugin/src/JestPlugin.ts, heft-plugins/heft-jest-plugin/src/test/JestPlugin.test.ts, heft-plugins/heft-sass-plugin/src/SassPlugin.ts, heft-plugins/heft-typescript-plugin/src/TypeScriptPlugin.ts, libraries/heft-config-file/src/ConfigurationFileBase.ts, libraries/heft-config-file/src/NonProjectConfigurationFile.ts, libraries/heft-config-file/src/ProjectConfigurationFile.ts, libraries/heft-config-file/src/TestUtilities.ts, libraries/heft-config-file/src/index.ts, libraries/heft-config-file/src/test/ConfigurationFile.test.ts, libraries/heft-config-file/src/test/__snapshots__/ConfigurationFile.test.ts.snap, libraries/rush-lib/src/api/RushProjectConfiguration.ts, libraries/rush-lib/src/logic/pnpm/PnpmOptionsConfiguration.ts, libraries/rush-lib/src/logic/pnpm/test/PnpmOptionsConfiguration.test.ts, libraries/rush-lib/src/logic/test/InstallHelpers.test.ts, libraries/rush-lib/src/schemas/pnpm-config.schema.json, rush-plugins/rush-serve-plugin/src/RushProjectServeConfigFile.ts
Add support for an `"extends"` property in `pnpm-config.json` files.
Also refactors and expands the `@rushstack/heft-config-file` project to include a new API designed for loading configuration files not in projects.
Tested in a branch that has subspace `pnpm-config.json` files in subspaces that extend from the `common/config/rush/pnpm-config.json` file.
A note should be added to https://rushjs.io/pages/configs/pnpm-config_json/#docusaurus_skipToContent_fallback
=> [rush] Add support for an `"extends"` property in `pnpm-config.json` files.

common/changes/@microsoft/rush/remove-node-fetch-http-from-http_2024-12-04-02-57.json, common/config/subspaces/default/pnpm-lock.yaml, rush-plugins/rush-http-build-cache-plugin/package.json, rush-plugins/rush-http-build-cache-plugin/src/HttpBuildCacheProvider.ts, rush-plugins/rush-http-build-cache-plugin/src/RushHttpBuildCachePlugin.ts, rush-plugins/rush-http-build-cache-plugin/src/index.ts, rush-plugins/rush-http-build-cache-plugin/src/test/HttpBuildCacheProvider.test.ts
Similar to https://github.com/microsoft/rushstack/pull/5025, this PR updates the `rush-http-build-cache-plugin` to use `WebClient` instead of `node-fetch`.
Will be published as a prerelease.
None.
=> [rush] Update rush-http-build-cache-plugin to use WebClient instead of node-fetch

common/changes/@microsoft/rush/bump-azure-packages_2024-12-09-23-49.json, common/changes/@microsoft/rush/bump-azure-packages_2024-12-09-23-50.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json, libraries/rush-lib/src/logic/NodeJsCompatibility.ts, rush-plugins/rush-azure-storage-build-cache-plugin/package.json
Bump @azure/identity and @azure/storage-blob to add support for Node 22.
The current version of `@azure/storage-blob` has an indirect dependency on `punycode`, which is deprecated in Node 22. The upgraded versions don't have this dependency.
This PR also bumps the maximum supported LTS version.
Published as 5.144.1-pr5037.0.
Node support matrix may need to be updated.
=> [rush] Bump @azure/identity and @azure/storage-blob to add support for Node 22.

apps/lockfile-explorer/package.json, apps/lockfile-explorer/src/utils/shrinkwrap.ts, common/changes/@microsoft/rush/feature-support_pnpmv9_2024-11-19-08-24.json, common/changes/@rushstack/lockfile-explorer/feature-support_pnpmv9_2024-11-25-14-05.json, common/config/rush/nonbrowser-approved-packages.json, common/config/subspaces/build-tests-subspace/pnpm-lock.yaml, common/config/subspaces/build-tests-subspace/repo-state.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json, libraries/rush-lib/package.json, libraries/rush-lib/src/logic/pnpm/PnpmLinkManager.ts, libraries/rush-lib/src/logic/pnpm/PnpmShrinkWrapFileConverters.ts, libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts, libraries/rush-lib/src/logic/pnpm/test/PnpmShrinkwrapConverters.test.ts, libraries/rush-lib/src/logic/pnpm/test/PnpmShrinkwrapFile.test.ts, libraries/rush-lib/src/logic/pnpm/test/yamlFiles/pnpm-lock-v9/inconsistent-dep-devDep.yaml, libraries/rush-lib/src/logic/pnpm/test/yamlFiles/pnpm-lock-v9/modified.yaml, libraries/rush-lib/src/logic/pnpm/test/yamlFiles/pnpm-lock-v9/not-modified.yaml, libraries/rush-lib/src/logic/pnpm/test/yamlFiles/pnpm-lock-v9/overrides-not-modified.yaml, libraries/rush-lib/src/logic/pnpm/test/yamlFiles/pnpm-lock-v9/pnpm-lock-v9.yaml, libraries/rush-lib/src/logic/test/ShrinkwrapFile.test.ts, libraries/rush-lib/src/logic/test/__snapshots__/ShrinkwrapFile.test.ts.snap, libraries/rush-lib/src/logic/test/shrinkwrapFile/non-workspace-pnpm-lock-v9.yaml, libraries/rush-lib/src/logic/test/shrinkwrapFile/workspace-pnpm-lock-v9.yaml, libraries/rush-sdk/package.json
pnpm lockfile v9 have some breaking changes on the lockfile format. Rush cannot parse pnpm lockfile v9 correctly with latest version. 
After i execute `rush install` or `rush update` with pnpm v9, the content of `.rush/temp/shrinkwrap-deps.json` is not correct. It may break rush cache system.
The expected output should correctly display the hash of each dependency., but actually:
pnpm have some breaking changes on lockfile v9 format.
1. The packages field has been divided into two parts, packages and snapshots.
2. In non-workspace mode, the top-level dependencies field is moved into `importers['.']`.
3. specifier is not same as lockfile v6
Rush will load the lockfile and parse the information in the lockfile by itself.
https://github.com/microsoft/rushstack/blob/3c6117e0740a48d2248be08edf2 …
=> [rush-lib] Support pnpm lockfile v9

common/changes/@microsoft/rush/feature-support_fallback_syntax_in_npmrc_2024-12-04-13-22.json, common/changes/@microsoft/rush/feature-support_fallback_syntax_in_npmrc_2024-12-10-20-47.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/RushConfiguration.ts, libraries/rush-lib/src/cli/RushXCommandLine.ts, libraries/rush-lib/src/cli/actions/DeployAction.ts, libraries/rush-lib/src/cli/actions/InstallAction.ts, libraries/rush-lib/src/cli/actions/PublishAction.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/Autoinstaller.ts, libraries/rush-lib/src/logic/InstallManagerFactory.ts, libraries/rush-lib/src/logic/ProjectChangeAnalyzer.ts, libraries/rush-lib/src/logic/PurgeManager.ts, libraries/rush-lib/src/logic/RepoStateFile.ts, libraries/rush-lib/src/logic/SetupChecks.ts, libraries/rush-lib/src/logic/StandardScriptUpdater.ts, libraries/rush-lib/src/logic/base/BaseInstallManager.ts, libraries/rush-lib/src/logic/installManager/InstallHelpers.ts, libraries/rush-lib/src/logic/installManager/RushInstallManager.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/logic/setup/SetupPackageRegistry.ts, libraries/rush-lib/src/scripts/install-run.ts, libraries/rush-lib/src/utilities/Utilities.ts, libraries/rush-lib/src/utilities/npmrcUtilities.ts, libraries/rush-lib/src/utilities/test/__snapshots__/npmrcUtilities.test.ts.snap, libraries/rush-lib/src/utilities/test/npmrcUtilities.test.ts
Fixes #5029
I added a regular expression which copies from @pnpm/config.env-replace/env-replace.ts for identifying fallback syntax.
I added some test cases in the `libraries/rush-lib/src/utilities/test/npmrcUtilities.test.ts` file to ensure the rush work goes as expected.
=> Support fallback syntax in .npmrc file

common/changes/@microsoft/rush/main_2024-12-13-20-32.json, libraries/rush-lib/src/logic/operations/OperationExecutionRecord.ts
Ensure that noops don't block cache writing, even if they are disabled.
During phased command execution, if a disabled operation is identified as a No-Op, return `OperationStatus.NoOp` instead of `OperationStatus.Skipped`, since by definition a No-Op should not write any files.
Fiddled with command-line.json so that `@rushstack/eslint-patch` would depend on a noop in `@rushstack/tree-pattern`, then ran `rush build -o eslint-patch --verbose` and verified that it wrote a cache entry.
None, since this is expected.
=> [rush] Treat disabled noops as noop instead of skipped

common/changes/@rushstack/node-core-library/trim-trailing-slash_2024-12-13-02-11.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/RealNodeModulePath.ts, libraries/node-core-library/src/test/RealNodeModulePath.test.ts
Updates `RealNodeModulePath` to match the behavior of `fs.realpathSync.native` with respect to relative paths and trailing slashes.
Relative paths go through `path.resolve`, which will join them with the current working directory.
If the path has one or more trailing path separators, they will be removed, unless the path is a root, at which point it will be normalized to one trailing path separator.
Switched to using `path.join` to ensure that empty path segments get pruned.
This will somewhat slow the performance, since `path.parse` and `path.format` are a bit more work that previous API calls, but it will produce correct results on Windows when link targets are absolute paths with trailing path separators.
Additional unit tests.
None. Semantics of `fs.realpathSync.native` are matched, …
=> [node-core-library] Fix semantics of RealNodeModulePath

common/changes/@microsoft/rush/git-filter-fixes_2024-12-14-00-09.json, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/ProjectChangeAnalyzer.ts
Fixes an issue with the "enableSubpathScan" experiment where the `--only` and `--impacted-by` selection operators would compute incorrect build cache ids and therefore cause cache misses.
Computation of build cache ids always requires the file hashes of all dependencies of selected projects, because the cache id is a function of the cache ids of the operation dependencies (approximately).
Enabled the experiment and verified that running `rush build -o worker-pool --verbose` was a cache hit.
For comparison, reverted this change and did the same and verified a cache miss.
Since the experiment description doesn't specify exactly what filtering is applied, none.
=> [rush] Fix build cache ids when "enableSubpathScan" is enabled

common/changes/@rushstack/lookup-by-path/lookup-enhancements_2024-12-17-22-37.json, common/changes/@rushstack/webpack-workspace-resolve-plugin/lookup-enhancements_2024-12-17-22-42.json, common/reviews/api/lookup-by-path.api.md, libraries/lookup-by-path/src/LookupByPath.ts, libraries/lookup-by-path/src/test/LookupByPath.test.ts, webpack/webpack-workspace-resolve-plugin/src/KnownPackageDependenciesPlugin.ts, webpack/webpack-workspace-resolve-plugin/src/WorkspaceLayoutCache.ts, webpack/webpack-workspace-resolve-plugin/src/WorkspaceResolvePlugin.ts, webpack/webpack-workspace-resolve-plugin/src/test/createResolveForTests.ts
Adds more functionality to `@rushstack/lookup-by-path`, especially with respect to overriding the delimiter per-method.
Fixes path parsing on Windows in `@rushstack/webpack-workspace-resolve-plugin`.
Adds new methods to `LookupByPath<TItem>`:
- `isEmpty(): boolean`
- `get(query: string, delimiter?: string): TItem | undefined`
- `has(query: string, delimiter?: string): boolean`
Enhances all read/write methods with the optional `delimiter?: string` parameter to allow overriding the delimiter used to parse the input.
Since the Rush cache file contains only `/` as the directory separator, updates the parsing in `WorkspaceLayoutCache` to parse all paths using `/` as the delimiter when hydrating `LookupByPath` instances.
API documentation for `LookupByPath`.
=> Enhance LookupByPath, Fix win32 paths in webpack-workspace-resolve-plugin

common/changes/@microsoft/rush/sennyeya-allow-injected-deps-outside-of-subspaces_2024-12-26-19-45.json, libraries/rush-lib/src/logic/RepoStateFile.ts
Original question in Zulip: https://rushstack.zulipchat.com/#narrow/channel/262513-general/topic/Injected.20Dependencies.20and.20Subspaces/near/490904453
I'm trying to enable injected dependencies and was getting some confusing error messages (and a lack of `repo-state.json` changes) that indicated something wasn't updating as it should have. Looks like injected dependencies were gated at some point between subspaces and I can't see a great reason why they should be.
Remove check for having subspaces enabled when using injected dependencies.
Tested in our repository that the repo-state file had changes after running `rush update` and that subsequent runs were cached.
=> fix: allow injected dependencies when subspaces are disabled

common/changes/@microsoft/rush/bugfix-no-unnecessary-condition_2025-01-03-10-05.json, libraries/rush-lib/src/cli/actions/VersionAction.ts
Rush version command throws the following error where I had set ensureConsistentVersions to false in my rush repo.
```text
ERROR: Unable to finish version bump because inconsistencies were encountered. Run "rush check" to find more details.
```
`shouldEnsureConsistentVersions` is a function not a variable.
https://github.com/microsoft/rushstack/blob/7aa7b9f8943359b660b5f563a8496b738b6e4f40/libraries/rush-lib/src/api/Subspace.ts#L328-L335
Therefore, the condition expression here is always true.
https://github.com/microsoft/rushstack/blob/7aa7b9f8943359b660b5f563a8496b738b6e4f40/libraries/rush-lib/src/cli/actions/VersionAction.ts#L219-L221
This issue is introduced by https://github.com/microsoft/rushstack/pull/4927
[no-unnecessary-condition](https://typescript-eslint.io/rules/no-unnecessary- …
=> Fix the issue of accessing shouldEnsureConsistentVersions  method incorrectly.

common/changes/@microsoft/rush/bugfix-yaml_dump_error_2024-12-23-08-19.json, libraries/rush-lib/src/logic/pnpm/PnpmShrinkWrapFileConverters.ts, libraries/rush-lib/src/logic/pnpm/test/PnpmShrinkwrapConverters.test.ts, libraries/rush-lib/src/utilities/objectUtilities.ts, libraries/rush-lib/src/utilities/test/objectUtilities.test.ts
Fixes #5053
After I set the preventManualShrinkwrapChanges field in the pnpm-config.json file to true, I successfully reproduced this problem.
The following code logic will result in the lockfile object having nullish value, so the `yamlModule.safeDump` method will throw an exception.
https://github.com/microsoft/rushstack/blob/724aa515c6c2d1a810dc8430576a7994c25ccb37/libraries/rush-lib/src/logic/pnpm/PnpmShrinkWrapFileConverters.ts#L51-L64
I have added some unit tests to ensure that the importers field in the lockfile will not contain nullish values.
=> [rush] Fixed the issue where the lockfile object has an nullish value causing yaml.dump to report an error

common/changes/@rushstack/eslint-patch/eslint-cache-bug_2025-01-07-00-34.json, eslint/eslint-patch/src/eslint-bulk-suppressions/bulk-suppressions-patch.ts
Fixes an issue where a number of results of probing for `.eslintrc.cjs` and `.eslintrc.js` files weren't being cached.
In a folder structure like:
```
src/
a/
1/
b/
c/
d/
```
Searching for the `.eslintrc.cjs` file from `a/1/` wrote cache records for `src/`, `src/a/`, and `src/a/1/`. However, a subsequent lookup in `src/b/c/` would find the cache record for `src/`, but not write cache records to `src/b/` or `src/b/c/`, resulting in duplicative searches for all subsequent files in these folders.
Under fstrace to observe the disk probes.
None. This is the expected behavior.
=> [eslint-bulk] Fix caching during eslintrc lookup

common/changes/@rushstack/node-core-library/user-danade-AddRetryCount_2025-01-08-22-19.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/Async.ts
Provides the current retry count when running an action with retries. Allows avoiding the need to create an external variable to track in cases where this info is needed.
=> [node-core-library] Provide `retryCount` parameter to actions executed using `Async.runWithRetriesAsync`

common/changes/@microsoft/rush/user-danade-RemoveSocketErrorHandler_2025-01-09-20-04.json, libraries/rush-lib/src/utilities/WebClient.ts
Removes unnecessary error handling when dealing with ECONNRESET-like errors. Fixes #5061.
An error handler was added to the socket to deal with ECONNRESET and other ECONN* errors that seemingly wouldn't bubble up. These errors were difficult to validate the fix against, so minimal testing of the change was done. However, errors began to arrise due to socket reuse in the http/https libraries during periods of high request utilization against the same host, leading to too many error handlers being added to individual sockets.
This change removes the socket handler, as we validated by looking at Node source code that socket errors _should_ bubble up to the request error handler. See: https://github.com/nodejs/node/blob/14b6317641751590ebe5d87d4f15822ae3fdb7d6/lib/_http_client.js#L497
Locally …
=> [rush-lib] Fix issue with `MaxListenersExceeded` while using the HTTP build cache plugin

common/changes/@microsoft/rush/chore-auto-generate-decouple_2025-01-09-12-50.json, common/config/rush/experiments.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/assets/rush-init/common/config/rush/experiments.json, libraries/rush-lib/src/api/ExperimentsConfiguration.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/schemas/experiments.schema.json
Currently, our Monorepo contains numerous projects, and naturally, there are many projects that need to depend on other projects in the monorepo via version numbers rather than workspaces. As a result, business teams need to frequently modify the `rush.json` file. 
The purpose of `decoupledLocalDependencies` is to encourage projects in the repository to depend on each other through workspaces, which is understandable. However, as the number of projects in the monorepo increases, this becomes a burden for everyone. Therefore, there is a need for a capability to disable the configuration of `decoupledLocalDependencies`.
1. Change the project's workspace dependencies to version-based dependencies.
2. Enable `exemptDecoupledDependenciesBetweenSubspaces ` to `true`.
3. Run `rush install` …
=> [rush] Setting to avoid manually configuring decoupledLocalDependencies across subspaces

common/changes/@rushstack/webpack-workspace-resolve-plugin/resolver-cache-fixes_2025-01-10-19-44.json, common/reviews/api/webpack-workspace-resolve-plugin.api.md, webpack/webpack-workspace-resolve-plugin/src/KnownDescriptionFilePlugin.ts, webpack/webpack-workspace-resolve-plugin/src/KnownPackageDependenciesPlugin.ts, webpack/webpack-workspace-resolve-plugin/src/WorkspaceResolvePlugin.ts, webpack/webpack-workspace-resolve-plugin/tsconfig.json
Allows the resolver to be applied to the `context` and `loader` resolvers in addition to the `normal` resolver.
Applies the same performance optimizations as https://github.com/webpack/enhanced-resolve/pull/445
Upgrades the compilation target to ensure that optional chaining is preserved instead of transpiled.
Unit tests for the core functionality.
Plugin instructions.
=> [workspace-resolve] Allow configuration of which resolvers to apply to

common/changes/@rushstack/heft-storybook-plugin/add-docs-to-storybook_2025-01-16-21-48.json, heft-plugins/heft-storybook-plugin/heft-plugin.json, heft-plugins/heft-storybook-plugin/src/StorybookPlugin.ts
Adds support for the --docs parameter to the Heft storybook plugin.
Ran in a project that wants to use this parameter.
=> [heft-storybook-plugin] Add support for the --docs parameter to the Heft storybook plugin.

common/changes/@rushstack/module-minifier/add-workerResourceLimits_2025-01-22-02-09.json, common/changes/@rushstack/worker-pool/add-workerResourceLimits_2025-01-22-02-09.json, common/reviews/api/module-minifier.api.md, common/reviews/api/worker-pool.api.md, libraries/module-minifier/src/WorkerPoolMinifier.ts, libraries/worker-pool/src/WorkerPool.ts
Adds an option to control the resources available to workers.
This allows consumers of `WorkerPoolMinifier` to give workers more memory.
Tested in a project that needs more memory in workers.
None.
=> [module-minifier] [worker-pool] Add an option to control the resources available to workers.

common/changes/@microsoft/rush/enelson-add-timeline-param_2025-01-18-21-32.json, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts
Allow the `--timeline` option even if a phased command does not support parallelism.
Today, the `--timeline` option is only available on the command line if a phased command supports parallelism.
However, this option is useful in many cases even if there is no parallelism -- the histogram can help identify visually which projects are bottlenecks in the execution flow, and the summary at the end is helpful for showing the breakdown of total time spent in the different phases across all projects.
- Unit tests passing
- Ran local Rush monorepo against these changes to confirm `--timeline` option was available
- N/A
=> [rush-lib] Add --timeline parameter for all phased commands

build-tests/api-documenter-scenarios/package.json, build-tests/api-extractor-d-cts-test/package.json, build-tests/api-extractor-d-mts-test/package.json, build-tests/api-extractor-lib1-test/package.json, build-tests/api-extractor-lib2-test/package.json, build-tests/api-extractor-lib3-test/package.json, build-tests/api-extractor-lib4-test/package.json, build-tests/api-extractor-lib5-test/package.json, build-tests/api-extractor-test-01/package.json, build-tests/api-extractor-test-02/package.json, build-tests/api-extractor-test-03/package.json, build-tests/api-extractor-test-04/package.json, build-tests/ts-command-line-test/package.json, common/changes/@rushstack/node-core-library/bump-fs-extra_2025-01-29-22-16.json, common/config/subspaces/build-tests-subspace/pnpm-lock.yaml, common/config/subspaces/build-tests-subspace/repo-state.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json, libraries/node-core-library/package.json
Update fs-extra to 11.3.0 to take advantage of more of the built-in capabilities of the NodeJS fs module and adopt various performance enhancements (such as removing unnecessary `lstat()` calls while deleting a folder).
Minimum NodeJS version for this version of fs-extra is 14.x, but node-core-library is already consuming typings for NodeJS 18.x, so this should not constitute a breaking change.
Rebuilt and retested the repository. FileSystem api is exercised heavily throughout the build process.
None
=> [node-core-library] Bump fs-extra to 11.3.0

common/changes/@microsoft/rush/fix-ensure-consistent-versions_2025-01-29-22-15.json, libraries/rush-lib/src/api/Subspace.ts
Fixes #5086 
Always prefers `common-versions.json` as the source of truth for `ensureConsistentVersions`. Only falls back to `rush.json` if not defined in `common-versions.json`.
- 
New behavior matches the claimed specification, so no change.
=> [rush] Fix ensureConsistentVersions in common-versions

apps/heft/src/cli/HeftActionRunner.ts, apps/heft/src/metrics/MetricsCollector.ts, common/changes/@microsoft/rush/available-parallelism_2025-01-30-01-01.json, common/changes/@rushstack/heft/available-parallelism_2025-01-30-01-01.json, common/changes/@rushstack/module-minifier/available-parallelism_2025-01-30-01-01.json, common/changes/@rushstack/package-extractor/available-parallelism_2025-01-30-01-01.json, common/changes/@rushstack/webpack4-module-minifier-plugin/available-parallelism_2025-01-30-01-01.json, libraries/module-minifier/src/WorkerPoolMinifier.ts, libraries/package-extractor/src/scripts/createLinks/utilities/constants.ts, libraries/rush-lib/src/cli/parsing/ParseParallelism.ts, libraries/rush-lib/src/logic/Telemetry.ts, webpack/webpack4-module-minifier-plugin/src/ParallelCompiler.ts
Prefer using [`os.availableParallelism()`](https://nodejs.org/docs/latest-v22.x/api/os.html#osavailableparallelism) to [`os.cpus().length`](https://nodejs.org/docs/latest-v22.x/api/os.html#oscpus)
The former API was introduced in NodeJS 18 and performs a lot less work than the latter.
In Node 22, `os.cpus()` opens several files to read info about each CPU on every invocation.
Build, since this API is used to determine parallelism of Rush, as well as various unit tests.
Only a few method comments where the default comes from this method.
=> Use os.availableParallelism() instead of os.cpus().length

common/changes/@rushstack/heft-jest-plugin/bugfix-IncorrectHeftJsonPluginSchema_2025-02-06-21-03.json, heft-plugins/heft-jest-plugin/src/schemas/heft-jest-plugin.schema.json
There is a mismatch between the [schema](https://github.com/microsoft/rushstack/blob/main/heft-plugins/heft-jest-plugin/src/schemas/heft-jest-plugin.schema.json) and the possible configuration documented [here](https://heft.rushstack.io/pages/plugins/jest/#heftjson-plugin-options).
This PR extends the schema to match the plugin options.
Extended the schema, mostly with information already available in the documentation.
Note that both `debugHeftReporter` and `detectOpenHandles` were _not_ added to the schema on purpose, since IMO they do not belong in something that is set up statically (but should only be passed from the command line)
Happy to adjust that, if wanted.
I modified the schema json in one of my projects consuming rush (within node_modules) and verified the behaviour.
None; …
=> Extend Heft-Jest-Plugin schema to match with configuration options

common/changes/@microsoft/rush/fix-parameter-kind_2025-02-11-20-25.json, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts
Fix an issue where the port parameter in `@rushstack/rush-serve-plugin` was allowed to be a string parameter.
Ran locally.
=> [rush] Fix an issue where the rush-serve-plugin port parameter was allowed to be a string.

common/changes/@rushstack/webpack5-localization-plugin/fix-incremental-loc_2025-02-14-20-33.json, webpack/webpack5-localization-plugin/src/AssetProcessor.ts
Fixes a bug where `chunk.localizedFiles` was not present when the localized assets came from cache, breaking tooling that depended on it.
Moved the assignment of the property outside of the cached call.
Debugger.
None.
=> [webpack5-loc-plugin] Fix missing metadata during rebuild

apps/api-extractor/package.json, common/changes/@microsoft/api-extractor/main_2025-02-21-18-19.json, common/config/subspaces/build-tests-subspace/pnpm-lock.yaml, common/config/subspaces/build-tests-subspace/repo-state.json, common/config/subspaces/default/common-versions.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json
Upgrade the bundled compiler engine to TypeScript 5.7.3
Precursor to https://github.com/microsoft/rushstack/pull/5117
Ran build tests.
None.
=> [api-extractor] Upgrade the bundled compiler engine to TypeScript 5.7.3

apps/heft/src/index.ts, apps/heft/src/operations/runners/TaskOperationRunner.ts, apps/heft/src/pluginFramework/HeftTaskSession.ts, apps/heft/src/utilities/WatchFileSystemAdapter.ts, common/changes/@rushstack/heft/expose-watch-fs_2025-02-25-23-51.json, common/reviews/api/heft.api.md
Allows plugins to more easily interact with Heft's file watcher layer, such that if they have their own way of reading files, they can still request that Heft watch them without having to build their own file watchers.
Exposes the `WatchFileSystem` that backs `watchGlobAsync` as `watchFs` on `IHeftTaskRunIncrementalHookOptions`.
Surfaces an existing object that is already used in various plugins.
API docs.
=> [heft] Expose watchFs on IncrementalRunOptions

build-tests/localization-plugin-test-02/config/heft.json, common/changes/@rushstack/heft-localization-typings-plugin/loc-loader-ignore-string_2025-02-27-02-42.json, common/changes/@rushstack/localization-utilities/loc-loader-ignore-string_2025-02-27-02-42.json, common/changes/@rushstack/webpack5-localization-plugin/loc-loader-ignore-string_2025-02-27-02-08.json, common/reviews/api/localization-utilities.api.md, heft-plugins/heft-localization-typings-plugin/src/LocalizationTypingsPlugin.ts, heft-plugins/heft-localization-typings-plugin/src/schemas/options.schema.json, libraries/localization-utilities/src/TypingsGenerator.ts, libraries/localization-utilities/src/parsers/parseLocJson.ts, libraries/localization-utilities/src/parsers/test/__snapshots__/parseLocJson.test.ts.snap, libraries/localization-utilities/src/parsers/test/parseLocJson.test.ts, libraries/localization-utilities/src/schemas/locJson.schema.json, webpack/webpack5-localization-plugin/src/loaders/LoaderFactory.ts, webpack/webpack5-localization-plugin/src/loaders/locjson-loader.ts, webpack/webpack5-localization-plugin/src/loaders/resjson-loader.ts, webpack/webpack5-localization-plugin/src/loaders/resx-loader.ts
Modifies the localization toolchain to support emitting processed localization files into the JS output folders. These files are structured such that tools with default extension guessing will find them, and so that they match the schema that the generated typings claim they have.
Files will be emitted with the following extensions depending on input:
```
{
'.loc.json': '.loc.json',
'.resjson': '.resjson',
'.resx': '.resx.json',
'.resx.json': '.resx.json'
}
```
Added unit tests for the `.loc.json` parser and enabled the `trimmedJsonOutputFolders` setting in a build test project.
Plugin documentation for `heft-localization-typings-plugin`.
=> Update localization tooling to support emitting trimmed JSON files for runtime

common/changes/@microsoft/rush/bugfix-include-deps_2025-02-28-22-54.json, libraries/rush-lib/src/logic/operations/PhasedOperationPlugin.ts, libraries/rush-lib/src/logic/operations/test/PhasedOperationPlugin.test.ts
Fixes an issue where `--include-phase-deps` and watch mode rebuilds were both scheduling more operations than necessary.
The new calculation for what is in scope is:
1. Let `All` be the set of operations necessary to form a complete graph that contains the originally requested phases and originally selected projects, including their dependencies.
1. Let `ToExecute` be the set of operations that are in a project with changes and are one of the originally requested phases.
1. Additionally include in `ToExecute` all operations in `All` that depend on any operation in `ToExecute`
2. If `--include-phase-deps` is true and it is not a watch-mode rebuild, additionally include in `ToExecute` all operations that are dependencies of the operations in `ToExecute`.
3. Configure the `enabled` state of …
=> [rush] Fix bug including unnecessary operations

apps/api-extractor/src/analyzer/AstModule.ts, apps/api-extractor/src/analyzer/AstNamespaceImport.ts, apps/api-extractor/src/analyzer/AstSymbolTable.ts, apps/api-extractor/src/analyzer/ExportAnalyzer.ts, apps/api-extractor/src/collector/Collector.ts, apps/api-extractor/src/enhancers/ValidationEnhancer.ts, apps/api-extractor/src/generators/ApiReportGenerator.ts, apps/api-extractor/src/generators/DtsRollupGenerator.ts, build-tests/api-extractor-test-02/dist/api-extractor-test-02-alpha.d.ts, build-tests/api-extractor-test-02/dist/api-extractor-test-02-beta.d.ts, build-tests/api-extractor-test-02/dist/api-extractor-test-02-public.d.ts, build-tests/api-extractor-test-02/dist/api-extractor-test-02.d.ts, build-tests/api-extractor-test-02/etc/api-extractor-test-02.api.md, build-tests/api-extractor-test-02/package.json, build-tests/api-extractor-test-02/src/Ambient.ts, build-tests/api-extractor-test-02/src/index.ts, common/changes/@microsoft/api-extractor/reference-in-index_2025-02-25-01-16.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json
There is an issue where references are not collected from fies that only contain reexports.
Added a repro and fixed it.
None.
=> [api-extractor] Fix an issue with preservation of triple-slash references.

apps/api-extractor/package.json, apps/api-extractor/src/analyzer/TypeScriptInternals.ts, common/changes/@microsoft/api-extractor/feat-ts-85_2025-03-08-00-13.json, common/config/subspaces/build-tests-subspace/pnpm-lock.yaml, common/config/subspaces/build-tests-subspace/repo-state.json, common/config/subspaces/default/common-versions.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json
Upgrade the bundled compiler engine to TypeScript 5.8.2.
Allows using new `erasableSyntaxOnly` option, which currently fails:
```
api-extractor 7.51.1  - https://api-extractor.com/
Using configuration from ./api-extractor.json
ERROR: Error parsing tsconfig.json content: Unknown compiler option 'erasableSyntaxOnly'.
```
Seems to work fine after the upgrade.
Ran the build tests. Also manually overwrote the typescript version used by API extractor in a project, and seems to work just fine.
None, as far as I know.
=> [api-extractor] Upgrade bundled TypeScript to 5.8

common/changes/@rushstack/node-core-library/lstat-cache_2025-03-10-22-47.json, common/changes/@rushstack/node-core-library/lstat-cache_2025-03-10-22-49.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/RealNodeModulePath.ts, libraries/node-core-library/src/test/RealNodeModulePath.test.ts
Update `RealNodeModulePath` to cache negative results (errors or when path elements aren't symbolic links) in addition to positive results.
This is particularly relevant to the `node_modules/.pnpm` and `node_modules/.bin` folders.
Ran in a real project and validated that there aren't excessive statx calls to `node_modules/.pnpm`.
This class.
=> [node-core-library] Negative symlink cache in RealNodeModulePath

apps/heft/src/configuration/RigPackageResolver.ts, apps/heft/src/utilities/CoreConfigFiles.ts, apps/rush/src/start-dev.ts, common/changes/@microsoft/rush/heft-resolve-cache_2025-03-11-01-23.json, common/changes/@rushstack/heft-jest-plugin/heft-resolve-cache_2025-03-11-01-23.json, common/changes/@rushstack/heft-serverless-stack-plugin/heft-resolve-cache_2025-03-11-01-23.json, common/changes/@rushstack/heft-storybook-plugin/heft-resolve-cache_2025-03-11-01-23.json, common/changes/@rushstack/heft/heft-resolve-cache_2025-03-11-01-23.json, common/changes/@rushstack/node-core-library/heft-resolve-cache_2025-03-11-01-20.json, common/reviews/api/node-core-library.api.md, heft-plugins/heft-jest-plugin/src/JestPlugin.ts, heft-plugins/heft-jest-plugin/src/patches/jestWorkerPatch.ts, heft-plugins/heft-serverless-stack-plugin/src/ServerlessStackPlugin.ts, heft-plugins/heft-storybook-plugin/src/StorybookPlugin.ts, libraries/node-core-library/src/Import.ts, libraries/node-core-library/src/test/__snapshots__/Import.test.ts.snap, libraries/rush-lib/src/pluginFramework/PluginManager.ts, libraries/rush-sdk/src/generate-stubs.ts
Adds a new option `useNodeJSResolver: boolean` to `Import.resolvePackage` to use the built-in `require.resolve` algorithm to find the package instead of the `resolve` npm package.
Also changes the query passed to `resolve` if not using `useNodeJSResolver: true` to append `/package.json` instead of simply `/`.
The motivation for this change is that by using `require.resolve` we are able to share NodeJS's caching layer for resolutions.
It is used by the various plugin resolvers in this repository.
Only the added option.
=> [node-core-library] Add and use `useNodeJSResolver` option on `Import.resolvePackage`

apps/heft/src/configuration/RigPackageResolver.ts, apps/heft/src/utilities/CoreConfigFiles.ts, common/changes/@microsoft/rush/heft-revert-use-native_2025-03-11-18-53.json, common/changes/@rushstack/hashed-folder-copy-plugin/heft-revert-use-native_2025-03-11-18-53.json, common/changes/@rushstack/heft/heft-revert-use-native_2025-03-11-18-53.json, libraries/rush-lib/src/pluginFramework/PluginManager.ts, libraries/rush-sdk/package.json, rush-plugins/rush-resolver-cache-plugin/package.json, rush-plugins/rush-serve-plugin/package.json, webpack/hashed-folder-copy-plugin/package.json
Reverts usage of `useNodeJSResolver: true` in `Import.resolvePackage` when loading plugins in `Heft` and `Rush` to compensate for malformed plugins that have an `exports` field that does not include an entry for `./package.json`.
Switches back to old behavior using the `resolve` npm package instead of relying on the built-in resolver.
Local run.
None
=> [rush, heft] Revert `useNodeJSResolver: true`

common/changes/@rushstack/heft-lint-plugin/fix-eslint-fix_2025-03-24-22-49.json, heft-plugins/heft-lint-plugin/src/Eslint.ts
Fixes an issue with the heft-lint-plugin `--fix` argument when a file contains only fixable issues.
The lint result shows up as having no messages, no warnings or errors when `--fix` is passed, so need to select based on the presence of the pre-extracted "fixable" messages.
Local run against rules with autofixers.
None. Works per original documentation.
=> [heft-lint] Fix autofixer when a file contains only fixable issues

common/changes/@rushstack/node-core-library/remove-legacyAdapters-from-FileSystem_2025-03-24-22-21.json, common/changes/@rushstack/node-core-library/remove-legacyAdapters-from-FileSystem_2025-03-24-22-40.json, common/reviews/api/node-core-library.api.md, libraries/node-core-library/src/FileSystem.ts, libraries/node-core-library/src/test/writeBuffersToFile.test.ts
Removes the dependency on LegacyAdatpers in FileSystem.
Built this repo.
None.
=> [node-core-library] Remove the dependency on `LegacyAdatpers` in `FileSystem` and expand the `FileSystem.writeBuffersToFile*` APIs.

build-tests/heft-webpack5-everything-test/src/chunks/image.d.png.ts, build-tests/heft-webpack5-everything-test/src/test/Image.test.ts, build-tests/heft-webpack5-everything-test/tsconfig.json, common/changes/@rushstack/heft-jest-plugin/main_2025-03-31-23-18.json, heft-plugins/heft-jest-plugin/includes/jest-shared.config.json, heft-plugins/heft-jest-plugin/src/transformers/StringMockTransformer.ts
Updates the `jest-string-mock-transformer` that is the default transformation for static assets to emit slash-normalized paths relative to `config.rootDir`, rather than absolute paths. This ensures that the result of the transform can be safely used in snapshot tests, and will continue to work if the path is passed directly into file system APIs, because the `fs` API resolves relative paths to the current working directory.
The motivation for this change is that the current implementation of the transformer is unsafe to use in snapshot tests, since it returns platform-specific absolute paths.
Example:
```ts
import myImage from './my-image.png';
// Path will use slashes and be relative to the current working directory
// It will be the relative path to the *output* file in the CommonJS …
```
=> [heft-jest] (BREAKING CHANGE) Use slash-normalized relative paths for asset URLs

apps/heft/src/configuration/HeftConfiguration.ts, apps/heft/src/configuration/types.ts, apps/heft/src/index.ts, common/changes/@rushstack/heft-api-extractor-plugin/heft-config-api_2025-03-04-23-15.json, common/changes/@rushstack/heft-config-file/heft-config-api_2025-03-04-23-13.json, common/changes/@rushstack/heft-config-file/multi-emit-plugin_2025-03-04-01-02.json, common/changes/@rushstack/heft-sass-plugin/heft-config-api_2025-03-05-00-29.json, common/changes/@rushstack/heft/multi-emit-plugin_2025-03-01-03-11.json, common/changes/@rushstack/rig-package/multi-emit-plugin_2025-03-01-03-11.json, common/config/subspaces/build-tests-subspace/repo-state.json, common/config/subspaces/default/pnpm-lock.yaml, common/reviews/api/heft-config-file.api.md, common/reviews/api/heft.api.md, heft-plugins/heft-api-extractor-plugin/package.json, heft-plugins/heft-api-extractor-plugin/src/ApiExtractorPlugin.ts, heft-plugins/heft-sass-plugin/package.json, heft-plugins/heft-sass-plugin/src/SassPlugin.ts, heft-plugins/heft-typescript-plugin/src/TypeScriptPlugin.ts, libraries/heft-config-file/src/ConfigurationFileBase.ts, libraries/heft-config-file/src/NonProjectConfigurationFile.ts, libraries/heft-config-file/src/ProjectConfigurationFile.ts, libraries/heft-config-file/src/index.ts, libraries/heft-config-file/src/test/ConfigurationFile.test.ts, libraries/heft-config-file/src/test/__snapshots__/ConfigurationFile.test.ts.snap
Adds a new API to `HeftConfiguration`, `tryLoadProjectConfigurationFileAsync`, so that plugins can load riggable config files without taking a direct dependency (and risking version duplication) on `@rushstack/heft-config-file`.
Starts addressing #5092. The motivation is to get us to a world where Heft plugins don't need any runtime dependencies other than on any external tools they bring with them, because all the core functionality of a Heft plugin is available on arguments passed to `apply`, similar to prior art in webpack plugins, that have the `compiler.webpack` field that provides access to all functionality that would otherwise be obtained via `import ... from 'webpack'`.
This API change removes any need for Heft plugins to take their own dependency on the …
=> [heft] Add `tryLoadProjectConfigurationFileAsync` API and use in plugins

common/changes/@microsoft/rush/main_2025-04-09-20-53.json, libraries/rush-lib/assets/rush-init/common/config/rush/[dot]npmrc, libraries/rush-lib/assets/rush-init/common/config/rush/[dot]npmrc-publish
Improve the `.npmrc` and `.npmrc-publish` documentation to avoid the confusion encountered in https://github.com/microsoft/rushstack/issues/5180
=> [rush] Clarify "rush init" template for .npmrc

common/changes/@microsoft/rush/graceful-exit_2025-04-16-19-31.json, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/ProjectWatcher.ts
Bind the key `q` to gracefully exit Rush's watch mode.
Added abort support to the watcher and leveraged it here.
Local invocation of `rush start` in rushstack and pressing `q` to exit.
Documented in the CLI prompt.
=> [rush] Add "q" for "quit" to the watcher prompt

common/changes/@microsoft/rush/watch-changed-only_2025-04-16-21-54.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/RushProjectConfiguration.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/ProjectWatcher.ts, libraries/rush-lib/src/logic/operations/PhasedOperationPlugin.ts, libraries/rush-lib/src/pluginFramework/PhasedCommandHooks.ts, libraries/rush-lib/src/schemas/rush-project.schema.json
Defines a behavior for `--changed-projects-only` in Rush watch-mode phased commands.
- For the initial build, does nothing, since there is no concept of "project that doesn't need to be built"
- For watch-mode rebuilds, only operations for projects that have changed files, or downstream operations that specify `ignoreChangedProjectsOnlyFlag` in `rush-project.json` will be executed.
You can toggle the behavior on or off between iterations by pressing `c` on the command line.
Local run of `rush start --to heft-webpack5-everything-test` against a different worktree.
Documentation for the command line parameter. The toggle is documented in the CLI UX.
=> [rush] Support --changed-projects-only in watch mode

common/changes/@microsoft/rush/watch-changed-only_2025-04-17-00-17.json, common/changes/@microsoft/rush/watch-changed-only_2025-04-17-00-18.json, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/operations/PhasedOperationPlugin.ts, rush-plugins/rush-serve-plugin/src/api.types.ts, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts
Adds a new command to the websocket protocol to set the `enabled` state of operations in the current session.
Adds a command `set-enabled-states` that takes a `{ [operationName: string]: boolean }` to configure the base enabled states for operations. This is applied after the default selection filter, but will only include operations that are related to changes (invalidating operations will make more projects be considered "changed").
Adds a command `invalidate` that takes an array of operation names to request that they be executed on the next pass.
Also fixes an inaccuracy in the reporting of the status of the `--changed-projects-only` flag when telemetry is enabled, since it can be toggled at runtime.
For the telemetry flag, a local run.
For the websocket, currently hasn't been.
Web …
=> [rush-serve-plugin] Allow configuring operation enable/disable states via websocket

apps/heft/src/pluginFramework/HeftParameterManager.ts, common/changes/@rushstack/heft/parameter-manager-refactor_2025-04-22-04-13.json
Refactor Heft parameter manager.
Built and ran tests.
None.
=> [heft] Refactor Heft parameter manager.

common/changes/@rushstack/heft-config-file/chore-replace-node-structuredclone_2025-04-24-03-50.json, common/config/rush/browser-approved-packages.json, common/config/subspaces/build-tests-subspace/pnpm-lock.yaml, common/config/subspaces/build-tests-subspace/repo-state.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json, libraries/heft-config-file/package.json, libraries/heft-config-file/src/ConfigurationFileBase.ts
Replace the native `structuredClone` with `@ungap/structured-clone`.In this way, Rush can still run in the Node 16 environment.
=> [@rushstack/heft-config-file] Replace node structuredClone

common/changes/@microsoft/rush/fix-implicit-phases_2025-04-24-22-45.json, libraries/rush-lib/src/logic/operations/PhasedOperationPlugin.ts, libraries/rush-lib/src/logic/operations/test/PhasedOperationPlugin.test.ts, libraries/rush-lib/src/logic/operations/test/__snapshots__/PhasedOperationPlugin.test.ts.snap
Fixes a regression in which commands would sometimes not execute all operations on which they depended if not all phases were explicitly specified in the command definition.
The runtime distinguishes the exact set of phases defined in command-line.json from the expanded set that includes all dependencies of those phases. For commands where these two sets differed, if `--include-phase-deps` was not specified, phases that were not explicitly listed were being omitted.
Updated the unit tests for PhasedOperationPlugin
Making this work as expected.
=> [rush] Fix implicit phase expansion regression

common/changes/@rushstack/node-core-library/fix-node-errno_2025-04-30-17-39.json, libraries/node-core-library/src/FileSystem.ts, libraries/node-core-library/src/test/FileSystem.test.ts
Fixes a gap in `FileSystem.isErrnoException` for instances where the file system call was not provided with a file path, e.g. `fs.readSync`, which only takes a file descriptor.
The method was expecting the `path` property to always be present and be a string, but not all methods are provided with a path.
None.
=> [node-core-library] Fix FileSystem.isErrnoException

apps/api-extractor/src/generators/ApiReportGenerator.ts, build-tests/api-extractor-lib2-test/dist/api-extractor-lib2-test.d.ts, build-tests/api-extractor-lib2-test/etc/api-extractor-lib2-test.alpha.api.md, build-tests/api-extractor-lib2-test/etc/api-extractor-lib2-test.api.md, build-tests/api-extractor-lib2-test/etc/api-extractor-lib2-test.public.api.md, build-tests/api-extractor-lib2-test/src/index.ts, common/changes/@microsoft/api-extractor/trim-export-default-from-reports_2025-04-29-00-30.json
Fix for #4775
For an example of the changed behavior, see the diff between the first two commits in this PR. The first adds a repro test scenario, and the second shows the change in behavior.
- Note that the public API report _before_ includes `export default DefaultClass;` when it should not (`DefaultClass` is tagged as `@beta`).
=> [api-extractor] Correctly omit declarations associated with an entity whose release tag does not meet the configured threshold in API reports

apps/rush-mcp-server/package.json, apps/rush-mcp-server/src/index.ts, apps/rush-mcp-server/src/server.ts, apps/rush-mcp-server/src/start.ts, apps/rush-mcp-server/src/tools/base.tool.ts, apps/rush-mcp-server/src/tools/conflict-resolver.tool.ts, apps/rush-mcp-server/src/tools/docs.tool.ts, apps/rush-mcp-server/src/tools/index.ts, apps/rush-mcp-server/src/tools/migrate-project.tool.ts, apps/rush-mcp-server/src/tools/project-details.tool.ts, apps/rush-mcp-server/src/tools/rush-command-validator.tool.ts, apps/rush-mcp-server/src/tools/workspace-details.ts, apps/rush-mcp-server/src/utilities/command-runner.ts, apps/rush-mcp-server/src/utilities/common.ts, apps/rush-mcp-server/src/utilities/log.ts, common/changes/@rushstack/mcp-server/origin-main_2025-05-01-15-48.json, common/config/rush/browser-approved-packages.json, common/config/rush/nonbrowser-approved-packages.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json
| prompt | tools | screenshots |
|------|------|------|
| 1. Which other projects does ‘rush-lib-test’ depend on? Please show them in the form of a directory tree. | rush_project_details | ![image](https://github.com/user-attachments/assets/39de27c0-8db7-423b-9644-d38278609d8d) |
| 2. Which other projects does ‘rush-lib-test’ depend on, including transitive dependencies? Please display them in the form of a directory tree | rush_workspace_details | ![image](https://github.com/user-attachments/assets/79fea8ff-4dc0-41a1-8811-59148d65f752) |
| 3. Please add the React dependency to the rush-lib-test project. | rush_command_validator | ![image](https://github.com/user-attachments/assets/0bc879a5-2fd1-4c08-b97f-22ca8ee61c1d) |
| 4. Please help move the @rushstack/eslint-config project to the …
=> [mcp-server] Add more tools to mcp server

build-tests/rush-redis-cobuild-plugin-integration-test/sandbox/sharded-repo/projects/e/config/rush-project.json, common/changes/@microsoft/rush/sennyeya-operation-timings_2024-05-07-16-36.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/operations/CacheableOperationPlugin.ts, libraries/rush-lib/src/logic/operations/ConsoleTimelinePlugin.ts, libraries/rush-lib/src/logic/operations/IOperationExecutionResult.ts, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/OperationExecutionRecord.ts, libraries/rush-lib/src/logic/operations/OperationMetadataManager.ts, libraries/rush-lib/src/logic/operations/OperationResultSummarizerPlugin.ts, libraries/rush-lib/src/logic/operations/test/OperationExecutionManager.test.ts, libraries/rush-lib/src/logic/operations/test/__snapshots__/OperationExecutionManager.test.ts.snap, libraries/rush-lib/src/utilities/Stopwatch.ts
`OperationExecutionRecord` is currently only tracking cache restore time for cobuilt operations that are marked as `RemoteOperating` and are then restored from cache. This is a confusing UX and causes developers + maintainers to have to search across multiple machine logs to determine operation run times. This PR adjusts that to use the `nonCachedDurationMs` from the state file. This felt like something that #3649 was intending to do or is in a similar vein.
This overwrites the existing stopwatch for operations that were not cobuilt on the specific agent. It adds a new `beforeResult` method to `OperationExecutionRecord#executeAsync` to handle the `afterExecuteOperation` hook instead of passing that work into the `onResult` method which ended up receiving running stopwatches and had other …
=> fix(timeline,cobuilds): cobuilt operations should reflect the cobuild time and not cache restore time

common/changes/@microsoft/rush/snapshot-local_2025-05-07-18-39.json, common/changes/@rushstack/package-deps-hash/snapshot-local_2025-05-07-18-39.json, common/reviews/api/package-deps-hash.api.md, common/reviews/api/rush-lib.api.md, libraries/package-deps-hash/src/getRepoState.ts, libraries/package-deps-hash/src/index.ts, libraries/package-deps-hash/src/test/__snapshots__/getRepoDeps.test.ts.snap, libraries/package-deps-hash/src/test/getRepoDeps.test.ts, libraries/rush-lib/src/cli/test/RushCommandLineParser.test.ts, libraries/rush-lib/src/cli/test/RushCommandLineParserFailureCases.test.ts, libraries/rush-lib/src/logic/ProjectChangeAnalyzer.ts, libraries/rush-lib/src/logic/incremental/InputsSnapshot.ts, libraries/rush-lib/src/logic/incremental/test/InputsSnapshot.test.ts, libraries/rush-lib/src/logic/test/ProjectChangeAnalyzer.test.ts
Adds a flag `hasUncommittedChanges` to the metadata for the input snapshot that plugins can use to identify if the current repository state has uncommitted changes. This is useful if trying to tie state to a git commit.
Adds `getDetailedRepoStateAsync` API to `@rushstack/package-deps-hash` to expose `hasUncommittedChanges` and `hasSubmodules` in addition to the existing `files` map. The information to compute these fields was already available in the calculation of `getRepoStateAsync`.
Updates `getRepoStateAsync` to just be a wrapper around `getDetailedRepoStateAsync` that extracts and returns the `files` property.
Updated the existing unit tests for `getRepoStateAsync` to instead operate on the expanded data of `getDetailedRepoStateAsync`.
The API doc for `@rushstack/package-deps-hash`, …
=> [rush] Expose `hasUncommittedChanges` flag on input snapshot

common/changes/@rushstack/lookup-by-path/git-first-difference_2025-05-07-22-00.json, common/changes/@rushstack/lookup-by-path/git-first-difference_2025-05-07-22-01.json, common/reviews/api/lookup-by-path.api.md, libraries/lookup-by-path/src/LookupByPath.ts, libraries/lookup-by-path/src/getFirstDifferenceInCommonNodes.ts, libraries/lookup-by-path/src/index.ts, libraries/lookup-by-path/src/test/getFirstDifferenceInCommonNodes.test.ts
Adds an API `getFirstDifferenceInCommonNodes` for comparing two `LookupByPath` instances of the same type.
Exposes a readonly `tree` property on `LookupByPath` that can be used for manual tree traversal.
Adds a recursive `getFirstDifferenceInCommonNodes` API that looks for value mismatches in shared nodes between two subtrees.
Documentation for this library.
=> [lookup-by-path] Add `getFirstDifferenceInCommonNodes`, `tree`

common/changes/@microsoft/rush/feat-add-cursor-rules_2025-05-08-12-27.json, libraries/rush-lib/src/utilities/HotlinkManager.ts
=> [rush] Fix path parsing issue when running rush bridge-package

apps/api-extractor/src/cli/ApiExtractorCommandLine.ts, apps/api-extractor/src/cli/RunAction.ts, common/changes/@microsoft/api-extractor/user-danade-FixTsCommandLine_2025-05-13-00-41.json
Fixes API extractor throwing of errors when changed APIs are encountered.
A recent change to the handling of errors in the API Extractor ts-command-line parser usage broke error handling when not using `--local` flag. This PR fixes that handling while keeping the newer approach intact
Locally using API Extractor CLI.
N/A
=> [api-extractor] Fix error handling when encountering changed APIs

common/changes/@rushstack/lookup-by-path/lookup-delete-subtree_2025-05-13-00-49.json, common/reviews/api/lookup-by-path.api.md, libraries/lookup-by-path/src/LookupByPath.ts, libraries/lookup-by-path/src/test/LookupByPath.test.ts
Adds a `deleteSubtree` method to `LookupByPath` to delete a node and all of its children.
This method is useful when using LookupByPath as a virtual file system to delete an entire directory hierarchy.
Class documentation for LookupByPath.
=> [lookup-by-path] Add deleteSubtree

build-tests/heft-sass-test/src/ExampleApp.tsx, build-tests/heft-sass-test/src/stylesAltSyntax.module.scss, build-tests/heft-sass-test/src/test/__snapshots__/lib-commonjs.test.ts.snap, build-tests/heft-sass-test/src/test/__snapshots__/lib-css.test.ts.snap, build-tests/heft-sass-test/src/test/__snapshots__/lib.test.ts.snap, build-tests/heft-sass-test/src/test/__snapshots__/sass-ts.test.ts.snap, common/changes/@rushstack/heft-sass-plugin/sass-quote-classes_2025-05-14-18-43.json, heft-plugins/heft-sass-plugin/src/SassProcessor.ts
Fix an issue where heft-sass-plugin would produce invalid .d.ts outputs for classnames that contain non-identifier characters.
If `exportAsDefault: false` and a classname contains invalid identifier characters, this will throw. For `exportAsDefault: true`, the classnames will be quoted and JSON escaped.
Added a classname with `-` into `heft-sass-test`.
None in particular.
=> [heft-sass] Ensure valid d.ts output for non-identifier classnames

apps/rush-mcp-server/src/pluginFramework/RushMcpPluginLoader.ts, apps/rush-mcp-server/src/schemas/rush-mcp.schema.json, apps/rush-mcp-server/src/start.ts, build-tests/rush-mcp-example-plugin/src/rush-mcp-example-plugin.schema.json, common/changes/@rushstack/mcp-server/octogonz-mcp-fixes_2025-06-06-07-20.json
- Fix an issue when resolving "." on Windows OS
- Improve error reporting for plugin load failures
- Remove `pluginName` from `rush-mcp.json` because it can be obtained from the plugin manifest
=> [mcp-server] Fix some issues with the plugin loader

common/changes/@microsoft/rush/pnpm-virtual-store-dir-max-length-fix_2025-06-03-18-27.json, libraries/rush-lib/src/logic/pnpm/PnpmLinkManager.ts
The default value of `virtual-store-dir-max-length` on Linux/MacOS is 120: https://pnpm.io/next/settings#virtualstoredirmaxlength
Tested on Linux and Windows [with pnpm v10 using azure-sdk-for-js repo](https://github.com/Azure/azure-sdk-for-js/compare/main...jeremymeng:azure-sdk-for-js:engsys/rush-pnpm-upgrades)
=> [rush] Add Linux/MacOS support for 'virtual-store-dir-max-length' default value in PNPM v10

common/changes/@microsoft/rush/pnpm-sync-0.3.1_2025-06-10-18-05.json, common/config/subspaces/build-tests-subspace/pnpm-lock.yaml, common/config/subspaces/build-tests-subspace/repo-state.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json, libraries/rush-lib/package.json
Bumps `pnpm-sync-lib` to `0.3.2` support PNPM v9.
~~Attempted to bump the pnpm version in this repo to `9.15.9` and run `rush update` with the version of Rush in this branch. There are several issues.~~ This works under pnpm 8.
None.
=> [rush] Bump pnpm-sync-lib to support PNPM v9.

README.md, apps/heft/package.json, apps/heft/src/cli/HeftActionRunner.ts, apps/heft/src/index.ts, apps/heft/src/operations/runners/PhaseOperationRunner.ts, apps/heft/src/operations/runners/TaskOperationRunner.ts, apps/heft/src/pluginFramework/HeftLifecycle.ts, apps/heft/src/pluginFramework/HeftLifecycleSession.ts, apps/heft/src/pluginFramework/HeftPhase.ts, apps/heft/src/pluginFramework/HeftTask.ts, build-tests/heft-example-lifecycle-plugin/.eslintrc.js, build-tests/heft-example-lifecycle-plugin/config/heft.json, build-tests/heft-example-lifecycle-plugin/config/rush-project.json, build-tests/heft-example-lifecycle-plugin/heft-plugin.json, build-tests/heft-example-lifecycle-plugin/package.json, build-tests/heft-example-lifecycle-plugin/src/index.ts, build-tests/heft-example-lifecycle-plugin/tsconfig.json, build-tests/heft-node-everything-test/config/heft.json, build-tests/heft-node-everything-test/package.json, common/changes/@rushstack/heft/sennyeya-heft-lifecycle_2025-06-11-16-53.json, common/changes/@rushstack/operation-graph/sennyeya-heft-lifecycle_2025-06-11-16-53.json, common/config/rush/browser-approved-packages.json, common/config/rush/nonbrowser-approved-packages.json, common/config/subspaces/default/pnpm-lock.yaml, common/reviews/api/heft.api.md, common/reviews/api/operation-graph.api.md, libraries/operation-graph/src/Operation.ts, libraries/operation-graph/src/OperationExecutionManager.ts, libraries/operation-graph/src/OperationGroupRecord.ts, rush.json
Alternative to #5232 that exposes Operation lifecycle events directly instead of through a metrics interface.
We're trying to measure the duration of specific Heft tasks similar to the duration of specific Rush phases. Specifically, I'm trying to understand the impact of migrating from Webpack to Rspack beyond manual benchmarking. This also opens up visibility into sync/blocking tasks and how to improve Heft parallelism.
Added new project that verified that output had the correct information,
```
---- build started ---- 
[lifecycle:example-lifecycle-plugin] --- build started ---
[build:clean] Deleted 0 files and 5 folders
[lifecycle:example-lifecycle-plugin] --- typescript started ---
[build:typescript] Using TypeScript version 5.8.2
[build:lint] Using ESLint version 8.57.0
[build:lint] …
```
=> [heft] feat: add lifecycle events for Heft tasks + phases

common/changes/@microsoft/rush/bridge-cache-both_2025-07-01-21-37.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/pluginFramework/PhasedCommandHooks.ts, rush-plugins/rush-bridge-cache-plugin/README.md, rush-plugins/rush-bridge-cache-plugin/rush-plugin-manifest.json, rush-plugins/rush-bridge-cache-plugin/src/BridgeCachePlugin.ts, rush-plugins/rush-bridge-cache-plugin/src/schemas/bridge-cache-config.schema.json
Updates `@rushstack/rush-bridge-cache-plugin` to use a choice parameter instead of a flag parameter, which options of "read" or "write.
- "write" matches the prior behavior of the plugin, i.e. writes build cache entries from all existing outputs of selected operations
- "read" is a best-effort replay-from-build-cache for all selected operations. Failures will display warnings but the exit code will still be 0.
The existing options schema was malformed, so this technically should not be a breaking change.
Also exposes the configured Rush `parallelism` on the phased operation context object, so that it can be used by plugins.
Locally wired it into the repository and ran various permutations of `rush build --bridge-cache-action=read` and `rush build --bridge-cache-action=write` for different …
=> [rush-bridge-cache] Support read or write of cache

common/changes/@microsoft/rush/performance-marks_2025-07-03-20-39.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/Rush.ts, libraries/rush-lib/src/cli/RushCommandLineParser.ts, libraries/rush-lib/src/cli/actions/BaseInstallAction.ts, libraries/rush-lib/src/cli/actions/BaseRushAction.ts, libraries/rush-lib/src/cli/scriptActions/GlobalScriptAction.ts, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/Telemetry.ts, libraries/rush-lib/src/logic/test/Telemetry.test.ts, libraries/rush-lib/src/start.ts, libraries/rush-lib/src/utilities/performance.ts, rush.json
Adds enhanced performance monitoring data to the Rush telemetry payloads.
Note that the Rush telemetry subsystem by default only writes to a file (if enabled by the `telemetryEnabled: true` flag in `rush.json`) and does not get uploaded anywhere without custom plugins.
Adds performance measures around various critical pieces of Rush, paying particular attention to phased commands.
Updates the telemetry subsystem to extract all performance measures since the last payload (if any) and record them as a `performanceEntries` array in the telemetry payload.
Note that these values are not present during the `beforeLog` hook and are only available in `flushTelemetry`.
`rush build -o tree-pattern` in rushstack repository
```json
[
{
"name": "build",
"durationInSeconds": 0.21093514500000005, …
```
=> [rush] Enhance performance data in telemetry payload

common/changes/@microsoft/rush/login-flow-failover_2025-07-09-21-02.json, common/reviews/api/rush-azure-storage-build-cache-plugin.api.md, libraries/rush-lib/src/schemas/build-cache.schema.json, rush-plugins/rush-azure-storage-build-cache-plugin/src/AzureAuthenticationBase.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/RushAzureStorageBuildCachePlugin.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/index.ts, rush-plugins/rush-azure-storage-build-cache-plugin/src/schemas/azure-blob-storage-config.schema.json
Updates the `azureBlobStorageConfiguration` section of the Rush `build-cache.json` schema to allow all valid values for `loginFlow` and to support configuration of `loginFlowFailover` to specify what order to try authentication providers in.
`loginFlow` supports the following values:
- 'DeviceCode'
- 'InteractiveBrowser'
- 'AdoCodespacesAuth'
- 'VisualStudioCode'
- 'AzureCli'
- 'AzureDeveloperCli'
- 'AzurePowerShell'
The `loginFlowFailover` field is an object that maps valid `loginFlow` types to other `loginFlow` types as the next fallback option. If no entry is defined for a given `loginFlow`, failures in that login flow will be terminal.
Locally configured the `azure-blob-storage` provider in `build-cache.json` and tried out different values of `loginFlow` and `loginFlowFailover` with …
=> [azure-build-cache] Expose loginFlowFailover in build-cache schema

common/changes/@microsoft/rush/build-cache-override-support_2025-03-08-23-35.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/BuildCacheConfiguration.ts, libraries/rush-lib/src/api/EnvironmentConfiguration.ts
This PR adds support for a `RUSH_BUILD_CACHE_OVERRIDE_JSON` environment variable that allows users to override the build cache configuration.
Tested by setting up and pulling cache from a Gradle server in this repo.
https://rushjs.io/pages/configs/environment_vars/#docusaurus_skipToContent_fallback
=> [rush] Add a `RUSH_BUILD_CACHE_OVERRIDE_JSON` env var to override the build cache configuration.

common/changes/@microsoft/rush/sennyeya-blobless-clone_2025-07-23-12-58.json, libraries/rush-lib/src/cli/actions/VersionAction.ts, libraries/rush-lib/src/logic/PublishGit.ts
Our monorepo is growing pretty quickly and we're starting to explore blobless clones in our CI set up to improve performance. One thing that I noticed turning on blobless clones in testing is that our `rush version` execution time went from seconds to 10m+ with a lot of 
```
remote: Enumerating objects: 831265, done.
remote: Counting objects: 100% (282323/282323), done.
remote: Compressing objects: 100% (56787/56787), done.
remote: Total 831265 (delta 270471), reused 225536 (delta 225536), pack-reused 548942 (from 1)
Receiving objects: 100% (831265/831265), 100.34 MiB | 38.66 MiB/s, done.
```
logs.
I _think_ this is related to the use of follow-tags here. As we're only pushing a single branch in the `rush version` command, we don't need to actually do any operations related to tagging. …
=> fix(rush): don't follow-tags on `rush version`

build-tests/heft-swc-test/package.json, common/changes/@rushstack/heft-isolated-typescript-transpile-plugin/swc-incremental_2025-07-25-23-40.json, common/changes/@rushstack/heft-typescript-plugin/swc-incremental_2025-07-25-23-40.json, heft-plugins/heft-isolated-typescript-transpile-plugin/src/SwcIsolatedTranspilePlugin.ts, heft-plugins/heft-typescript-plugin/src/internalTypings/TypeScriptInternals.ts
Adds file watching support to `@rushstack/heft-isolated-typescript-transpile-plugin`.
Wires the `tsconfig` parser into Heft's file watcher subsystem for directory reads, and checks for changes of individual files before invoking the transpiler.
Invocation of `heft build-watch` in `heft-swc-test`.
None
=> [heft-swc] Support watch mode

common/changes/@microsoft/rush/benkeen-bridge-cache-safety-check_2025-07-16-16-53.json, rush-plugins/rush-bridge-cache-plugin/README.md, rush-plugins/rush-bridge-cache-plugin/src/BridgeCachePlugin.ts, rush-plugins/rush-bridge-cache-plugin/src/schemas/bridge-cache-config.schema.json
This adds a optional safety check flag to the `write` action for the Bridge Cache plugin to verify all defined output folders for a task has been created on disk in order to populate the cache entry. If there's any missing, it outputs a warning stating which folders are missing and doesn't populate the cache for that particular action.
=> [rush] Add safety check to Bridge Cache plugin write action

common/changes/@rushstack/heft-isolated-typescript-transpile-plugin/main_2025-08-04-19-18.json, heft-plugins/heft-isolated-typescript-transpile-plugin/src/SwcIsolatedTranspilePlugin.ts
Updates the watch logic to only watch folders that TypeScript has identified has having wildcard patterns for source files, rather than all folders enumerated during TSConfig parsing.
This avoids, for example, watching for changes to the project root folder.
The TSConfig parser returns a `wildcardDirectories` object that indicates folders that contained wildcards and if the wildcard is local (`*` or `?`) or recursive (`**`). This is used to determine the directories that should be watched by Heft's watcher.
Local `heft run-watch --only build -- --clean` in `heft-swc-test` and creating/modifying/deleting files at various points in the directory hierarchy.
Linked the new version into a repository that was having infinite loop issues and verified that no such issues occur.
None.
=> [heft-swc] Reduce set of watched folders

apps/api-extractor/src/api/CompilerState.ts, common/changes/@microsoft/api-extractor/fix-self-import-resolution_2025-08-07-10-22.json
This PR fixes an issue where API Extractor incorrectly resolves self-package imports to source `.ts` files instead of the intended `.d.ts` build artifacts.
When a `.d.ts` file imports the package itself by its name, TypeScript's module resolution redirects to source files instead of analyzing the build outputs. This occurs because TypeScript tries to avoid analyzing build outputs when `outDir` or `declarationDir` compiler options are set.
See the TypeScript compiler logic here: https://github.com/microsoft/TypeScript/blob/391616532d6827254a86dc266121fd5d1958ffb9/src/compiler/moduleNameResolver.ts#L2867
Remove `outDir` and `declarationDir` from the compiler options in `CompilerState.ts`. This prevents TypeScript from redirecting imports and ensures API Extractor analyzes the correct …
=> [api-extractor] Fix self-package import resolution in TypeScript compiler

common/changes/@microsoft/rush/version-policy-exempt_2025-08-19-21-32.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/api/VersionPolicy.ts, libraries/rush-lib/src/api/VersionPolicyConfiguration.ts, libraries/rush-lib/src/api/test/VersionPolicy.test.ts, libraries/rush-lib/src/index.ts
Fixes an issue where the fields `dependencies`, `exemptFromRushChange` and `includeEmailInChangeFile` were discarded from `version-policies.json` during `rush version --bump` or similar commands.
The version bump logic asked for a fresh serialization of the data in the version policies, and the serializer was missing fields.
The revised logic has the version policy track the original JSON and modify it in place so that the `version-policies.json` file will only have the necessary changes.
Ran `rush version --bump` in the rushstack repository after adding `exemptFromRushChange: true` and `includeEmailInChangeFile: true` to the Rush version policy. Verified that in the old version these fields were discarded and in the new version they were preserved.
Documentation is now correct, since it …
=> [rush] Fix version bump removing policy fields

common/changes/@rushstack/debug-certificate-manager/bmiddha-certificatestore-homedir_2025-08-22-20-14.json, libraries/debug-certificate-manager/src/CertificateStore.ts
Handle `~` in `storePath` when reading `debug-certifiacate-manager.json`
Resolve homedir if `storePath` starts with `~`. `path.resolve` does not handle `~`
Tested with `~` path in `debug-certificate-manager.json`
=> [debug-certificate-manager] Handle `~` in `storePath` when reading `debug-certifiacate-manager.json`

common/config/azure-pipelines/vscode-extension-publish.yaml
Fix bug where vsix pipeline artifact is not published because of a bad path
=> [vsix publish] fix pipeline artifact path

common/changes/@microsoft/rush/rush-serve-unref_2025-08-26-21-30.json, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts
Calls `unref()` on the HTTP/2 server owned by `rush-serve-plugin` so that if the user presses `q` to terminate watch mode, the process will actually exit.
Possible this could leak a socket, but it's better than forcing the user to press Ctrl+C to terminate. In the future this should tap some hook indicating that the user is trying to shut down the process.
Ran a watch mode command with `rush-serve-plugin` enabled and verified that pressing `q` causes the process to gracefully exit.
None.
=> [rush-serve] Unref server

vscode-extensions/debug-certificate-manager-vscode-extension/package.json, vscode-extensions/debug-certificate-manager-vscode-extension/src/terminal.ts
Remove timeout for VS Code shell integration
Make activation event more specific
We had reports where users of the Debug Certificate Manger VS Code extension kept running into shell integration timeouts. This can happen when the shell boot up.
Shell integration is activated after the config files are sourced. So if there is anything in the `.bashrc` or `.bash_profile` that takes a while then the `bash` shell integration will be delayed.
We also had cases where the extension does not activate even when `.vscode/debug-certificate-manager.json`
Extension host logs:
```
2025-08-26 13:51:17.935 [info] Not activating extension 'ms-RushStack.debug-certificate-manager': Timed out while searching for 'workspaceContains' pattern .vscode/debug-certificate-manager.json
```
Updated activation event to …
=> [debug-certificate-mangaer] remove shell integration timeout and make make activation event more specific

common/changes/@rushstack/debug-certificate-manager/bmiddha-debug-certificate-manager-homedir-fix_2025-08-28-04-41.json, libraries/debug-certificate-manager/src/CertificateStore.ts
Fix home directory resolution in debug-certificate-manager
Home directory resolution for `debug-certificate-manager.json` was added in #5322.
This change fixes a logic error introduced in that change.
Tested by using the built CertificateStore results and pnpm patching it into the target repo. Validated with debug logging that new codepath is working as expected.
=> [debug-certificate-manager] Fix homedir resolution bug in CertificateStore

common/changes/@microsoft/rush/optimize-detect-local_2025-08-28-20-48.json, libraries/rush-lib/src/logic/DependencyAnalyzer.ts
Adds a fast path for `workspace:` protocol dependencies when analyzing common dependency versions.
The current detection algorithm for identifying local dependencies depended on semver matching; workspace protocol automatically requires the version to be satisfied locally.
Ran in a large monorepo with the change.
Before:
After:
None
=> [rush] Optimize detecting local projects when collating versions

common/changes/@microsoft/rush/dependency-specifier-cache_2025-08-28-20-24.json, libraries/rush-lib/src/api/RushConfigurationProject.ts, libraries/rush-lib/src/logic/ApprovedPackagesChecker.ts, libraries/rush-lib/src/logic/DependencySpecifier.ts, libraries/rush-lib/src/logic/PublishUtilities.ts, libraries/rush-lib/src/logic/VersionManager.ts, libraries/rush-lib/src/logic/installManager/RushInstallManager.ts, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/logic/npm/NpmShrinkwrapFile.ts, libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts, libraries/rush-lib/src/logic/test/DependencySpecifier.test.ts
Adds a caching layer to the parsing of `DependencySpecifier` objects.
In large monorepos, it is very common to see the exact same dependency specifier in many packages, e.g. the dependency on `@rushstack/heft`.
Since dependency specifiers are immutable, dedupes at parse time based on the input strings. Alias targets share the same cache.
Used the new version to run a `rush install` in a large monorepo.
Before:
After:
None.
=> [rush] Dedupe DependencySpecifier parsing

common/changes/@microsoft/rush/resolver-cache-fixes_2025-08-28-19-56.json, common/changes/@microsoft/rush/resolver-cache-fixes_2025-08-28-19-57.json, libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts, rush-plugins/rush-resolver-cache-plugin/src/afterInstallAsync.ts, rush-plugins/rush-resolver-cache-plugin/src/computeResolverCacheFromLockfileAsync.ts
Fixes an issue where the subpackage cache file was accidentally written empty.
The previous fix wrote the file before the data had been populated, making the optimization produce correct results but be useless.
Updates the caching layer in PnpmShrinkwrapFile to be based on a content hash of the raw shrinkwrap text instead of file path, so that writing a new file will never have caching issues.
Added an explicit API to clear the shrinkwrap cache.
Built and copied into a repository using the feature. Validated resolver cache created correctly.
Only the API documentation for PnpmShrinkwrapFile, which doesn't seem to be part of the API.md.
=> [rush-resolver-cache] Fix subpackage cache optimization

common/config/rush/version-policies.json
Sets the version policy to have the next Rush bump be a patch release.
N/A
=> Make the next release of Rush a patch

common/changes/@rushstack/heft-sass-plugin/fix-css-js_2025-08-31-00-57.json, heft-plugins/heft-sass-plugin/src/SassProcessor.ts
Fixes an issue with generation of .scss.js files in files that aren't in the root of the src folder.
Tested in a repo that repros this issue.
=> [heft-sass-plugin] Fix an issue with generation of .scss.js files.

common/changes/@rushstack/terminal/remove-colorable-sequence_2025-09-10-19-34.json, libraries/terminal/src/Terminal.ts
Resolves https://github.com/microsoft/rushstack/issues/4598.
Unit tests cover this.
None. This was never documented in @rushstack/terminal.
=> [Terminal] Remove support for IColorableSequence.

common/changes/@microsoft/rush/rush-abort_2025-09-16-01-25.json, common/reviews/api/rush-lib.api.md, libraries/rush-lib/src/cli/scriptActions/PhasedScriptAction.ts, libraries/rush-lib/src/logic/ProjectWatcher.ts, libraries/rush-lib/src/logic/operations/AsyncOperationQueue.ts, libraries/rush-lib/src/logic/operations/ConsoleTimelinePlugin.ts, libraries/rush-lib/src/logic/operations/OperationExecutionManager.ts, libraries/rush-lib/src/logic/operations/OperationResultSummarizerPlugin.ts, libraries/rush-lib/src/logic/operations/OperationStatus.ts, libraries/rush-lib/src/logic/operations/test/OperationExecutionManager.test.ts, libraries/rush-lib/src/pluginFramework/PhasedCommandHooks.ts, libraries/rush-lib/src/pluginFramework/RushLifeCycle.ts, rush-plugins/rush-bridge-cache-plugin/src/BridgeCachePlugin.ts, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts
Allows watch-mode phased commands abort queued operations via the `a` key. Aborting execution does not stop any operations that are currently executing, but any that are waiting will be aborted and automatically marked as invalid for the next iteration.
Aborting is supported at two levels:
- `IPhasedCommand` now has a `sessionAbortController` property, which can be used to completely abort the session (i.e. in watch mode, kill the watcher), and its `signal` should be listened to by any plugins that have long-lived state (like the `rush-serve-plugin`).
- `IExecuteOperationsContext` also has an `abortController` property, which is bound only to the current execution pass. This can be used to abort the currently queued operations.
Also fixes an issue where when the watcher is "paused", it …
=> [rush] Support aborting phased command execution

.github/workflows/ci.yml
Update CI Workflow to use 22.19 for the node 22 matrix
=> Update CI Workflow to use 22.19 for the node 22 matrix

.github/workflows/ci.yml
Update CI workflow: Run a second rush test step to verify build cache hits
=> Update CI workflow: Run a second rush test step to verify build cache hits

common/changes/@microsoft/rush/rush-serve-dependencies_2025-09-16-23-56.json, rush-plugins/rush-serve-plugin/src/RushProjectServeConfigFile.ts, rush-plugins/rush-serve-plugin/src/RushServePlugin.ts, rush-plugins/rush-serve-plugin/src/api.types.ts, rush-plugins/rush-serve-plugin/src/phasedCommandHandler.ts, rush-plugins/rush-serve-plugin/src/tryEnableBuildStatusWebSocketServer.ts, rush-plugins/rush-serve-plugin/src/types.ts
Updates the websocket protocol for `rush-serve-plugin` to include information about the dependency relationships between operations, and support sending a message to abort the current execution pass.
Added a new `abort-execution` command for aborting the current execution pass. This has the same behavior as pressing `a` at the terminal.
Added a new property `dependencies` to the transfer representation of an operation, containing the names of the operations depended on.
Temporarily wired rush-serve-plugin into rushstack and connected to the web socket.
The plugin's API documentation.
=> [rush-serve] Support dependencies, aborting

common/changes/@rushstack/debug-certificate-manager/bmiddha-cert-store-path-fixup_2025-09-28-00-24.json, libraries/debug-certificate-manager/src/CertificateManager.ts, libraries/debug-certificate-manager/src/CertificateStore.ts
Add information about the Debug Certificate Manager VS Code extension to log message strings in `debug-certificate-manager`. This is intended to make the log messages more actionable for users and help improve the experience when dealing with certificate issues.
- Add VS Code extension info to log message strings
- Break early when extension config is found
=> [debug-certificate-manager] add vs code extension info to log messages

build-tests/heft-swc-test/config/heft.json, common/changes/@rushstack/terminal/late-split_2025-09-30-19-49.json, common/reviews/api/terminal.api.md, libraries/terminal/src/SplitterTransform.ts, libraries/terminal/src/test/SplitterTransform.test.ts, libraries/terminal/src/test/__snapshots__/SplitterTransform.test.ts.snap
Updates the API contract for the `SplitterTransform` to support adding and removing destinations after creation. This is useful for pipelines where a plugin may wish to temporarily listen to the terminal output and direct it somewhere, e.g. over a websocket connection.
Adds new `addDestination` and `removeDestination` APIs to `SplitterTransform`. Updates the underlying implementation of the collection to use a Set instead of an array to simplify removal and deduplication during add. Updates the constructor arguments to accept any `Iterable<TerminalWritable>` so that the caller can pass a `Set` or other collection rather than requiring explicitly an array.
As an unrelated change, also fixed an issue with the `heft-swc-test` project that it was not cleaning the correct folders, causing …
=> [terminal] Allow adding/removing destinations from the SplitterTransform after creation

common/changes/@microsoft/rush/bmiddha-azureauthhelpertrim_2025-10-01-20-20.json, rush-plugins/rush-azure-storage-build-cache-plugin/src/AdoCodespacesAuthCredential.ts
Fix bug where there is a trailing `\n` character in tokens from `AdoCodespacesAuthCredential`
`stdout` from `azure-auth-helper` needs to be trimmed to remove the trailing newline from the token result.
token result:
```
{"token":"ey.....SwzQ\n","expiresOnTimestamp":1759351393000}
```
Validated by using the built JS for AdoCodespacesAuthCredential.js in target repo.
=> [rush-azure-storage-build-cache-plugin] Trim access token output in AdoCodespacesAuthCredential

common/changes/@microsoft/rush/fix-package-extensions-hash_2025-10-03-17-31.json, common/config/rush/nonbrowser-approved-packages.json, common/config/subspaces/build-tests-subspace/pnpm-lock.yaml, common/config/subspaces/build-tests-subspace/repo-state.json, common/config/subspaces/default/pnpm-lock.yaml, common/config/subspaces/default/repo-state.json, libraries/rush-lib/package.json, libraries/rush-lib/src/logic/installManager/WorkspaceInstallManager.ts, libraries/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts
In pnpm v10, the `packageExtensionsChecksum` hash format was changed from a MD5 hex digest to a SHA256 base64 digest. This PR adds support for the latter.
Tested in a repo with package extensions that is being upgraded to pnpm v10.
=> [rush] Fix an issue with validation of packageExtensionsChecksum.

.gitignore, debug-certificate-manager.json
Add repo config for rushstack debug certificate manager
This config is read by
- "Debug Certificate Manager" VS Code extension (`vscode-extensions/debug-certificate-manager`): Config file is used to sync user's debug certificates to the workspace.
- `@rushstack/debug-certificate-manager` package: Config file is used to read/write certificates from/to the filesystem in `CertificateStore`.
Tested by running `npm run start -- --serve` in `heft-webpack5-everything-test` in a codespace. The localhost server through `@rushstack/debug-certificate-manager` on the codespace. The certificates were synced with the codespace by the VS Code extension.
=> Add repo config for rushstack debug certificate manager
